### ISSUE TITLE
KeyError: <sickbeard.tv.TVEpisode object at 0xb4c94d4c>

### ISSUE THREAD

**Issue by gborri** [SiCKRAGETV/sickrage-issues#1017]
I've seen an issue about this error.
I probably found the root cause of the problem but I do not kown why it's happening.

the problem arise when you are backlogging episode 2 and you find S01E01-02 on cache.
in tvcache.py on procedure searchCache episode is 2 but findNeededEpisodes procdure return neededEps with eps 01 due to curEp = curResult["episodes"].split("|")[1].

**Comment by abeloin** [comment]
@gborri Can you provide the logs when this happen?

**Comment by gborri** [comment]
2015-03-25 12:23:55 INFO     SEARCHQUEUE-BACKLOG-210171 :: Beginning backlog search for: [The Killing (US)]
2015-03-25 12:23:55 INFO     SEARCHQUEUE-BACKLOG-210171 :: No scene exceptions update needed
2015-03-25 12:23:55 INFO     SEARCHQUEUE-BACKLOG-210171 :: Building internal name cache for The Killing (US)
2015-03-25 12:23:55 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: Internal name cache set to: {u'the killing us': 210171, u'continuum': 258171, u'the killing': 210171, u'true blood': 82283, u'arrow': 257655, u'the killing 2011': 210171}
2015-03-25 12:23:55 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: [TNTVillage] :: Last update was too soon, using old cache: today()-2015-03-25 12:01:52<0:30:00
2015-03-25 12:23:55 INFO     SEARCHQUEUE-BACKLOG-210171 :: [TNTVillage] :: Performing episode search for The Killing (US)
2015-03-25 12:23:55 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: [TNTVillage] :: Checking if found episode 3x1 is wanted at quality SD TV
2015-03-25 12:23:55 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: [TNTVillage] :: any,best = [1, 2] [] and found 1
2015-03-25 12:23:55 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: [TNTVillage] :: Existing episode status: 3 (Wanted)
2015-03-25 12:23:55 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: [TNTVillage] :: Existing episode status is wanted/unaired/skipped, getting found episode
2015-03-25 12:23:55 INFO     SEARCHQUEUE-BACKLOG-210171 :: [TNTVillage] :: Found result The.Killing.S03e01-12.HDTV.x264 at http://forum.tntvillage.scambioetico.org/index.php?act=Attach&type=post&id=13624196
2015-03-25 12:23:55 ERROR    SEARCHQUEUE-BACKLOG-210171 :: [TNTVillage] :: Error while searching TNTVillage, skipping: error The Killing (US) - 3x4 - Head Shots
location:
description: The task force shuts down a business; Sarah and Holder unite in their pursuit of "the voice"; Seward is offered motivation to comply with orders.
subtitles:
subtitles_searchcount: 0
subtitles_lastsearch: 0001-01-01 00:00:00
airdate: 735035 (2013-06-16)
hasnfo: False
hastbn: False
status: 3
Traceback (most recent call last):
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/sickbeard/search.py", line 477, in searchProviders
    logger.log(u"Performing season pack search for " + show.name)
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/sickbeard/providers/generic.py", line 269, in findSearchResults
    cacheResult = self.cache.searchCache(epObj, manualSearch, downCurQuality)
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/sickbeard/tvcache.py", line 302, in searchCache
    return neededEps[episode] if len(neededEps) > 0 else []
KeyError: <sickbeard.tv.TVEpisode object at 0xac4e9eac>
2015-03-25 12:23:55 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: [TNTVillage] :: Traceback (most recent call last):
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/sickbeard/search.py", line 477, in searchProviders
    logger.log(u"Performing season pack search for " + show.name)
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/sickbeard/providers/generic.py", line 269, in findSearchResults
    cacheResult = self.cache.searchCache(epObj, manualSearch, downCurQuality)
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/sickbeard/tvcache.py", line 302, in searchCache
    return neededEps[episode] if len(neededEps) > 0 else []
KeyError: <sickbeard.tv.TVEpisode object at 0xac4e9eac>

2015-03-25 12:23:55 ERROR    SEARCHQUEUE-BACKLOG-210171 :: No NZB/Torrent providers found or enabled in the sickrage config for backlog searches. Please check your settings.
Traceback (most recent call last):
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/sickbeard/search.py", line 477, in searchProviders
    logger.log(u"Performing season pack search for " + show.name)
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/sickbeard/providers/generic.py", line 269, in findSearchResults
    cacheResult = self.cache.searchCache(epObj, manualSearch, downCurQuality)
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/sickbeard/tvcache.py", line 302, in searchCache
    return neededEps[episode] if len(neededEps) > 0 else []

**Comment by fernandog** [comment]
@gborri why are you receiving this message?!

2015-03-25 12:23:55 ERROR    SEARCHQUEUE-BACKLOG-210171 :: No NZB/Torrent providers found or enabled in the sickrage config for backlog searches. Please check your settings.

**Comment by gborri** [comment]
@fernandog i don't know, But more then often happen "No NZB/Torrent providers" if for any reason arise an excpetion.

**Comment by fernandog** [comment]
@gborri do you have NZB disabled?

**Comment by gborri** [comment]
yes.

**Comment by fernandog** [comment]
@gborri all enabled providers has dailysearch setting enabled?

**Comment by gborri** [comment]
only one active provider with daily search enabled.

I have troubleshooting a bit on this error, as i have said it heppens when
episode are not available in neededEps.
This case happens only when a S02E01-02 is available and you are searching
for episode 02. In that case the error will happen always.
The point is that i don't know why is now happening.
i think we need to resolve the problem and a solution is in
PR SiCKRAGETV/SickRage#1344 (at least for trasmission client).

**Comment by fernandog** [comment]
@gborri we have to find another solution.

**Comment by abeloin** [comment]
I'm not sure merging PR1344 is a good idea to fix an issue with TNT provider

**Comment by gborri** [comment]
Is not an issue with tnt provider.
I will explain the problem.

Giovanni
Il 28/mar/2015 03:33 "Alexandre Beloin" <notifications@github.com> ha
scritto:

**Comment by fernandog** [comment]
We need to check here if is double episose.

 curEp = curResult["episodes"].split("|")[1].

**Comment by gborri** [comment]
That's the point. I will get code out of PR and make a fix pr

Giovanni
Il 28/mar/2015 11:52 "Fernando" <notifications@github.com> ha scritto:

**Comment by fernandog** [comment]
@gborri any news on this one?

**Comment by abeloin** [comment]
Then check if `curResult["episodes"].split("|")` contain multiple episode. If it do, override curEp for `epObj = showObj.getEpisode(curSeason, curEp)`

**Comment by gborri** [comment]
@abeloin the point is not related to multiepisode torrent.

from tvcache.py

    def searchCache(self, episode, manualSearch=False, downCurQuality=False):
        neededEps = self.findNeededEpisodes(episode, manualSearch, downCurQuality)
        return neededEps[episode] if len(neededEps) > 0 else [] 

get example in which episode is 02

   def findNeededEpisodes(self, episode, manualSearch=False, downCurQuality=False):

search the cache

       myDB = self._getDB()
        if type(episode) != list:
            sqlResults = myDB.select(
                "SELECT * FROM [" + self.providerID + "] WHERE indexerid = ? AND season = ? AND episodes LIKE ?",
                [episode.show.indexerid, episode.season, "%|" + str(episode.episode) + "|%"])
        else:
            for epObj in episode:
                cl.append([
                    "SELECT * FROM [" + self.providerID + "] WHERE indexerid = ? AND season = ? AND episodes LIKE ? AND quality IN (" + ",".join(
                        [str(x) for x in epObj.wantedQuality]) + ")",
                    [epObj.show.indexerid, epObj.season, "%|" + str(epObj.episode) + "|%"]])

            sqlResults = myDB.mass_action(cl, fetchall=True)
            sqlResults = list(itertools.chain(*sqlResults))

found episode S01e01-02

      curEp = curResult["episodes"].split("|")[1]
      epObj = showObj.getEpisode(curSeason, curEp)

            if epObj not in neededEps:
                neededEps[epObj] = [result]
            else:
                neededEps[epObj].append(result)

neededEps has only episode 01 and is searched for episode 2.

**Comment by abeloin** [comment]
@gborri Is The.Killing.S03e01-12.HDTV.x264 one file or a season pack?

**Comment by abeloin** [comment]
Ok looking in tnt website it's a season pack, so it shouldn't be detected as multifile eps.

The reason why you get this error is that you need to set the episode as multi_eps with MULTI_EP_RESULT

**Comment by abeloin** [comment]
Change the previous comment:
The error only happen in season pack search as you return season_pack files as multi_eps to SR.

So the error is in tntvillage search returned result when searching for season pack.

```
2015-03-30 00:19:54 INFO     SEARCHQUEUE-BACKLOG-210171 :: Saved magnet link to D:\SickRage\download\The.Killing.S03e01-12.HDTV.x264.torrent
2015-03-30 00:19:54 INFO     SEARCHQUEUE-BACKLOG-210171 :: Downloading a result from TNTVillage at http://forum.tntvillage.scambioetico.org/index.php?act=Attach&type=post&id=13624196
2015-03-30 00:19:54 INFO     SEARCHQUEUE-BACKLOG-210171 :: Downloading The.Killing.S03e01-12.HDTV.x264 from TNTVillage
2015-03-30 00:19:54 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: Checking if we should keep searching after we've found The.Killing.S03e01-12.HDTV.x264
2015-03-30 00:19:54 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: Checking if we should keep searching after we've found The.Killing.S03e01-12.HDTV.x264
2015-03-30 00:19:54 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: Checking if we should keep searching after we've found The.Killing.S03e01-12.HDTV.x264
2015-03-30 00:19:54 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: Checking if we should keep searching after we've found The.Killing.S03e01-12.HDTV.x264
2015-03-30 00:19:54 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: Checking if we should keep searching after we've found The.Killing.S03e01-12.HDTV.x264
2015-03-30 00:19:54 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: Checking if we should keep searching after we've found The.Killing.S03e01-12.HDTV.x264
2015-03-30 00:19:54 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: Checking if we should keep searching after we've found The.Killing.S03e01-12.HDTV.x264
2015-03-30 00:19:54 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: Checking if we should keep searching after we've found The.Killing.S03e01-12.HDTV.x264
2015-03-30 00:19:54 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: Checking if we should keep searching after we've found The.Killing.S03e01-12.HDTV.x264
2015-03-30 00:19:54 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: Checking if we should keep searching after we've found The.Killing.S03e01-12.HDTV.x264
2015-03-30 00:19:54 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: Checking if we should keep searching after we've found The.Killing.S03e01-12.HDTV.x264
2015-03-30 00:19:54 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: Checking if we should keep searching after we've found The.Killing.S03e01-12.HDTV.x264
2015-03-30 00:19:54 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: All of these episodes were covered by another multi-episode nzbs, ignoring this multi-ep result
2015-03-30 00:19:54 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: Multi-ep check result is multiNeededEps: [], multiNotNeededEps: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2015-03-30 00:19:54 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: Single-ep check result is neededEps: [], notNeededEps: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2015-03-30 00:19:54 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: Seeing if we want to bother with multi-episode result The.Killing.S03e01-12.HDTV.x264
2015-03-30 00:19:54 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: All of these episodes were covered by another multi-episode nzbs, ignoring this multi-ep result
2015-03-30 00:19:54 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: Multi-ep check result is multiNeededEps: [], multiNotNeededEps: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2015-03-30 00:19:54 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: Single-ep check result is neededEps: [], notNeededEps: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2015-03-30 00:19:53 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: Seeing if we want to bother with multi-episode result The.Killing.S03e01-12.HDTV.x264
2015-03-30 00:19:53 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: Multi-ep check result is multiNeededEps: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], multiNotNeededEps: []
2015-03-30 00:19:53 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: Single-ep check result is neededEps: [], notNeededEps: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2015-03-30 00:19:53 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: Seeing if we want to bother with multi-episode result The.Killing.S03e01-12.HDTV.x264
2015-03-30 00:19:53 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: The highest quality of any match is SD TV
2015-03-30 00:19:53 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: [TNTVillage] :: Separating multi-episode result to check for later - result contains episodes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2015-03-30 00:19:53 DEBUG    SEARCHQUEUE-BACKLOG-210171 :: [TNTVillage] :: Found result The.Killing.S03e01-12.HDTV.x264 at http://forum.tntvillage.scambioetico.org/index.php?act=Attach&type=post&id=13624196
```

**Comment by abeloin** [comment]
Season pack search disabled for tntvillage until it is fixed.

@gborri Can you test the PR?

**Comment by gborri** [comment]
let me understand better the situation. i will try to fix tntvillage. how can you define a multiepisode result or a season result for other provider?

**Comment by abeloin** [comment]
@gborri Here what I was trying to explain when I said it would download multiple time:
http://pastebin.com/raw.php?i=XkTqaQAJ

**Comment by gborri** [comment]
@abeloin I was thinking this morning about the repeating.
It's true, but it's correct. The fix (SiCKRAGETV/SickRag#1680) probably in incorrect and could not be merged without the entire change for PR SiCKRAGETV/SickRage#1344.
The SiCKRAGETV/SickRage#1344 will make a snatch for every episode also on multiepisode/season result. We need to change a bit the logging to be more meaningful.
The point is that I have to make a single snatch for ever episode. 

Example if i have on cache those torrent:

S01E02       --> seed 3, leech 3
S01E02-03  --> seed 2, leech 2
S01E01-05  ->> seed 1, leech 1

i will prefer torrent S01E02-03 for episode 3
i will prefer torrent S01E02 fot for episode 2
i will prefer torrent S01E01-05 for episode 1,4 and 5.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1169

@gborri

**Comment by gborri** [comment]
@fernandog it's not so easy to resolve the problem. I think we need to change deeply the code. The SiCKRAGETV/SickRage#1680 could be a work around. but as a solution i think we need to implement the donwload single episode from multiple file torrent rewriting the searchProvider, searchForNeeded Episode and FindSearchResult in order to manage multiple episode torrent.

**Comment by fernandog** [comment]
@gborri for now let's just warn user that we don´t support download one episode from a multi-episode torrent. We won't support this for now. Maybe in the future. Can you do the warning PR please?

**Comment by gborri** [comment]
@fernandog will try

**Comment by gborri** [comment]
@abeloin can I use a try except on return command like this?
```
try:
    return neededEps[episode] if len(neededEps) > 0 else []
except KeyError
     logging....
```

**Comment by fernandog** [comment]
@gborri I don't think so. I would assign to a variable first

**Comment by abeloin** [comment]
@gborri Not sure what you want to do exactly, but I would recommend this instead:

`return neededEps[episode] if episode in neededEps else []`

**Comment by gborri** [comment]
@abeloin i have to catch the KeyError Exception.

**Comment by gborri** [comment]
@abeloin i have understood only now your suggestion

**Comment by gborri** [comment]
i will change the PR.
