### ISSUE TITLE
Cant change from develop to master

### ISSUE THREAD

**Issue by Sykeya** [SiCKRAGETV/sickrage-issues#1030]
I've run all of the git commands to change to master yet my web interface is still stating "You're using the develop branch. Please use 'master' unless specifically asked"

a  git rev-parse --abbrev-ref HEAD gives me:
master

a  git pull gives me:
Already up-to-date.

**Comment by Sykeya** [comment]
log error is:

2015-03-25 09:55:56 Thread-131 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 3580, in index
    return t.respond()
  File "/opt/sickrage/cache/cheetah/cheetah__opt_sickrage_gui_slick_interfaces_default_config_general_tmpl_1427273388_97_39439.py", line 957, in respond
    if VFFSL(SL,"sickbeard.NO_RESTART",True) : # generated from line 526, col 67
NotFound: cannot find 'NO_RESTART' while searching for 'sickbeard.NO_RESTART'

2015-03-25 09:50:12 Thread-109 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 3887, in index
    if len(results) > 0:
  File "/opt/sickrage/cache/cheetah/_opt_sickrage_gui_slick_interfaces_default_config_postProcessing_tmpl.py", line 381, in respond
    if VFFSL(SL,"sickbeard.NO_DELETE",True) == True : # generated from line 199, col 84
NotFound: cannot find 'NO_DELETE' while searching for 'sickbeard.NO_DELETE'

**Comment by fernandog** [comment]
git checkout master

**Comment by TagForce** [comment]
Stop SR before doinganything with git on the commandline.

**Comment by Sykeya** [comment]
Thanks,

Stopped SR with

service sickrage stop

Ran:
git checkout master
git reset --hard
git clean -df
git pull

still same in web ui "You're using the develop branch. Please use 'master' unless specifically asked"

**Comment by TagForce** [comment]
Just remove the branch from config.ini
branch = 
instead of branch = develop

**Comment by Sykeya** [comment]
Thanks Tagforce,

I did that and still no change.

**Comment by cyberundertaker** [comment]
Backup SR develop database
modify config.ini (branch = master
git_remote = origin
git_remote_url = https://github.com/SiCKRAGETV/SickRage.git
cur_commit_hash = c28ca92c6d19ce1610a83ac08707529ad0796718
cur_commit_branch = master)
download master branch from git
run master branch and then restore the modified config.ini and database

That should work
