### ISSUE TITLE
PP: verify_freespace doesn't check if the path exist

### ISSUE THREAD

**Issue by abeloin** [SiCKRAGETV/sickrage-issues#1036]
```
SR Version: 	BRANCH: (master) / COMMIT: (49ae3401940df85b19475c331aed191690acbed8) 
Python Version:	2.7.8 (default, Nov 10 2014, 08:19:18) [GCC 4.9.2 20141101 (Red Hat 4.9.2-1)]
```

Steps to reproduce:
* PP a file for Show X
* Delete Show X with data
* Add Show X
* PP same file
* Error

What you expected: No crash :wink: 

```
2015-03-25 12:14:38 DEBUG    TORNADO :: Failed doing webui request "processEpisode": Traceback (most recent call last):
AAOSError: [Errno 2] Aucun fichier ou dossier de ce type: '/home/abeloin/Public/sickrage/Log Horizon/020. Log Horizon - Contract.mkv'
AA    return os.stat(filename).st_size
AA  File "/usr/lib64/python2.7/genericpath.py", line 49, in getsize
AA    result = func(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
AA  File "/home/abeloin/git/sr_alex/sickbeard/encodingKludge.py", line 58, in ek
AA    neededspace -= ek.ek(os.path.getsize, file.location)
AA  File "/home/abeloin/git/sr_alex/sickbeard/helpers.py", line 1510, in verify_freespace
AA    if not verify_freespace(self.file_path, ek.ek(os.path.dirname, ep_obj.location), [ep_obj] + ep_obj.relatedEps):
AA  File "/home/abeloin/git/sr_alex/sickbeard/postProcessor.py", line 874, in process
AA    result.result = processor.process()
AA  File "/home/abeloin/git/sr_alex/sickbeard/processTV.py", line 504, in process_media
AA    process_media(path, [video], nzbName, process_method, force, is_priority, result)
AA  File "/home/abeloin/git/sr_alex/sickbeard/processTV.py", line 203, in processDir
AA    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
AA  File "/home/abeloin/git/sr_alex/sickbeard/webserve.py", line 2134, in processEpisode
AA    result = function(**kwargs)
AA  File "/home/abeloin/git/sr_alex/sickbeard/webserve.py", line 258, in async_call
AATraceback (most recent call last):
AAOSError: [Errno 2] Aucun fichier ou dossier de ce type: '/home/abeloin/Public/sickrage/Log Horizon/020. Log Horizon - Contract.mkv'
AA    return os.stat(filename).st_size
AA  File "/usr/lib64/python2.7/genericpath.py", line 49, in getsize
AA    result = func(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
AA  File "/home/abeloin/git/sr_alex/sickbeard/encodingKludge.py", line 58, in ek
AA    neededspace -= ek.ek(os.path.getsize, file.location)
AA  File "/home/abeloin/git/sr_alex/sickbeard/helpers.py", line 1510, in verify_freespace
AA    if not verify_freespace(self.file_path, ek.ek(os.path.dirname, ep_obj.location), [ep_obj] + ep_obj.relatedEps):
AA  File "/home/abeloin/git/sr_alex/sickbeard/postProcessor.py", line 874, in process
AA    result.result = processor.process()
AA  File "/home/abeloin/git/sr_alex/sickbeard/processTV.py", line 504, in process_media
AA    process_media(path, [video], nzbName, process_method, force, is_priority, result)
AA  File "/home/abeloin/git/sr_alex/sickbeard/processTV.py", line 203, in processDir
AA    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
AA  File "/home/abeloin/git/sr_alex/sickbeard/webserve.py", line 2134, in processEpisode
AA    result = function(**kwargs)
AA  File "/home/abeloin/git/sr_alex/sickbeard/webserve.py", line 258, in async_call
```

**Comment by fernandog** [comment]
@TagForce

**Comment by abeloin** [comment]
@TagForce FYI We need to add a try...except catching error 2 in line 1510 of helpers.py

**Comment by TagForce** [comment]
@abeloin I'll fix it...

**Comment by TagForce** [comment]
@abeloin There's a bigger problem here...
Hold on, I need to fix this differently.

**Comment by TagForce** [comment]
@abeloin Ok, check the PR.. I just checked on windows, can you check your edge case (:D) again with that PR?

**Comment by abeloin** [comment]
@TagForce Working, Thanks
