### ISSUE TITLE
traktException: 500 Server Error: Internal Server Error

### ISSUE THREAD

**Issue by gborri** [SiCKRAGETV/sickrage-issues#1041]
is it possible to manage this exception?

```
2015-03-26 12:13:22 DEBUG    TRAKTCHECKER :: Traceback (most recent call last):
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/sickbeard/traktChecker.py", line 84, in run
    self.syncWatchlist()
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/sickbeard/traktChecker.py", line 187, in syncWatchlist
    if self._getShowWatchlist():
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/sickbeard/traktChecker.py", line 369, in _getShowWatchlist
    self.ShowWatchlist = self.trakt_api.traktRequest("sync/watchlist/shows")
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/lib/trakt/trakt.py", line 86, in traktRequest
    raise traktException(e)
traktException: 500 Server Error: Internal Server Error
```

**Comment by gborri** [comment]
2015-03-26 12:13:22 DEBUG    TRAKTCHECKER :: Traceback (most recent call last):
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/sickbeard/traktChecker.py", line 84, in run
    self.syncWatchlist()
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/sickbeard/traktChecker.py", line 187, in syncWatchlist
    if self._getShowWatchlist():
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/sickbeard/traktChecker.py", line 369, in _getShowWatchlist
    self.ShowWatchlist = self.trakt_api.traktRequest("sync/watchlist/shows")
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/lib/trakt/trakt.py", line 86, in traktRequest
    raise traktException(e)
traktException: 500 Server Error: Internal Server Error

**Comment by fernandog** [comment]
do something like this
https://github.com/SiCKRAGETV/SickRage/pull/1363/files

**Comment by abeloin** [comment]
@gborri Is @fernandog PR OK? Or you meant something else?

**Comment by gborri** [comment]
@abeloin @fernandog that's what i had in mind. Now we need to manage the exception on all the code.

**Comment by fernandog** [comment]
@gborri dont need

**Comment by gborri** [comment]
@fernandog are you sure? 
at least we need to add the exception.....

```
except (traktException, traktAuthException, traktServerBusy) as e:
                logger.log(u"Could not connect to Trakt service: %s" % ex(e), logger.WARNING)
                pass

```

**Comment by abeloin** [comment]
@gborri Just change this `except (traktException, traktAuthException, traktServerBusy) as e:` to this
`except traktException as e:` it will catch all trakt exception

**Comment by fernandog** [comment]
I will add to my PR.

**Comment by gborri** [comment]
@fernandog sure? i don't have much knowledge on exception, but i think that except traktException get only the traktException  exception and not the other, am I wrong?

**Comment by fernandog** [comment]
PR updated

**Comment by abeloin** [comment]
@gborri Look at the exceptions class in https://github.com/fernandog/SickRage/blob/trakt_url_500/lib/trakt/exceptions.py you can see they all inherit traktException.

**Comment by gborri** [comment]
good to know. Thanks
