### ISSUE TITLE
NotFound: cannot find 'PLAY_VIDEOS' while searching for 'sickbeard.PLAY_VIDEOS'

### ISSUE THREAD

**Issue by gborri** [SiCKRAGETV/sickrage-issues#1046]
2015-03-27 00:26:20 DEBUG    TORNADO :: Failed doing webui request "displayShow": Traceback (most recent call last):
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/sickbeard/webserve.py", line 243, in get
    results = yield self.async_call(method)
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/tornado/gen.py", line 642, in run
    value = future.result()
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/lib/concurrent/futures/_base.py", line 400, in result
    return self.__get_result()
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/lib/concurrent/futures/_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/lib/concurrent/futures/_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/lib/concurrent/futures/thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/sickbeard/webserve.py", line 1248, in displayShow
    return t.respond()
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage_test/cache/cheetah/cheetah__home_mediacenter_src_sickbeard_sickrage_sickrage_gui_slick_interfaces_default_displayShow_tmpl_1427412346_92_46362.py", line 929, in respond
    if VFFSL(SL,"sickbeard.PLAY_VIDEOS",True): # generated from line 364, col 4
NotFound: cannot find 'PLAY_VIDEOS' while searching for 'sickbeard.PLAY_VIDEOS'

**Comment by gborri** [comment]
@fernandog

**Comment by fernandog** [comment]
You updated using git pull.
restart SR please.
you should update from UI

**Comment by abeloin** [comment]
Fix on the way

**Comment by abeloin** [comment]
PLease update PR merge
