### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by gborri** [SiCKRAGETV/sickrage-issues#1051]
```
015-03-27 18:07:05 DEBUG    TORNADO :: Failed doing webui request "displayShow": Traceback (most recent call last):
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/sickbeard/webserve.py", line 243, in get
    results = yield self.async_call(method)
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/tornado/gen.py", line 642, in run
    value = future.result()
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/lib/concurrent/futures/_base.py", line 400, in result
    return self.__get_result()
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/lib/concurrent/futures/_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/lib/concurrent/futures/_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/lib/concurrent/futures/thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/sickbeard/webserve.py", line 1247, in displayShow
    return t.respond()
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage_test/cache/cheetah/_home_mediacenter_src_sickbeard_sickrage_sickrage_gui_slick_interfaces_default_displayShow_tmpl.py", line 972, in respond
    if int(VFFSL(SL,"epResult",True)["status"]) != VFFSL(SL,"UNAIRED",True): # generated from line 400, col 3
```

**Comment by abeloin** [comment]
### SUBMITTING A BUG/ISSUE TICKET
(DO NOT POST ANYTHING THAT CONTAINS YOUR LOGIN INFORMATION OR API KEY)<br />
Please include the following when opening a new ticket:
 - Branch
 - Commit hash
 - Your operating system and python version
 - What you did
 - What happened
 - What you expected
 - Link to a copy/paste of your logfile with clear debug info of the error on [GIST](http://gist.github.com)

**Comment by fernandog** [comment]
@gborri are you using pure develop or develop+  your patches?

**Comment by gborri** [comment]
Pure develop.

Giovanni
Il 27/mar/2015 19:19 "Fernando" <notifications@github.com> ha scritto:

**Comment by fernandog** [comment]
@gborri please post missing info as abeloin said

**Comment by gborri** [comment]
Branch: develop
Commit hash: f4f4527dc8b528fae08619c824c763abfb9b8bbb
Your operating system and python version: ubuntu 14.4, python 2.7.6
What you did: display show
What happened: reload home page
What you expected: see show detail

**Comment by fernandog** [comment]
Logs??

**Comment by gborri** [comment]
the log is what i have attached. there's no more info. it happen when open
a show in sickrage.

**Comment by fernandog** [comment]
Which show? Everytime you add does this error happen? Can you debug what is going on?
check database fo this show. sees what is wrong. Check data in ndexer. etc...

**Comment by fernandog** [comment]
@gborri please reply or we will close it

**Comment by gborri** [comment]
@fernandog there are more then one show (Grimm, The Blacklist and other). It happen when oper the show not add. i don't know what is going on.

**Comment by gborri** [comment]
I've tried now and the problem is disappearing.

**Comment by abeloin** [comment]
@gborri The error is because epResult["status"] can't be converted to a int. Maybe your DB got wrong value in it and a show refresh fixed the issue?

**Comment by gborri** [comment]
@abeloin could be. yesterday I have made a lot of refresh.
