### ISSUE TITLE
Redirect Loop after last update

### ISSUE THREAD

**Issue by thesmackdown** [SiCKRAGETV/sickrage-issues#1053]
Hi,

I just updated to: c28ca92c6d19ce1610a83ac08707529ad0796718 this morning.  Now I am getting a redirect loop error from Chrome.

**Comment by fernandog** [comment]
@thesmackdown how did you updated? UI or command line?

**Comment by thesmackdown** [comment]
Through the UI.

**Comment by fernandog** [comment]
@thesmackdown post log error, post contents of localhost:xxxx/config

**Comment by thesmackdown** [comment]
Config contents:


SR Version:	BRANCH: (master) / COMMIT: (c28ca92c6d19ce1610a83ac08707529ad0796718) 
SR User:	Evan Sayre
SR Locale:	('en_US', 'cp1252')
SR Config file:	C:\SickRage\config.ini
SR Database file:	C:\SickRage\sickbeard.db
SR Cache Dir:	C:\SickRage\cache
SR Log Dir:	C:\SickRage\Logs
SR Arguments:	[]
Python Version:	2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]

Log:

2015-03-27 19:26:45 Thread-162 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 723, in index
    return t.respond()
  File "C:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_home_tmpl.py", line 1014, in respond
    _v = VFN(VFSL([locals()]+SL+[globals(), builtin],"calendar",True),"timegm",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"pdatetime",True),"timetuple",False)()) # u'$calendar.timegm($pdatetime.timetuple())' on line 607, col 39
  File "C:\SickRage\lib\dateutil\tz.py", line 114, in dst
    if self._isdst(dt):
  File "C:\SickRage\lib\dateutil\tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: (22, 'Invalid argument')

2015-03-27 19:26:44 Thread-62 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 723, in index
    return t.respond()
  File "C:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_home_tmpl.py", line 1014, in respond
    _v = VFN(VFSL([locals()]+SL+[globals(), builtin],"calendar",True),"timegm",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"pdatetime",True),"timetuple",False)()) # u'$calendar.timegm($pdatetime.timetuple())' on line 607, col 39
  File "C:\SickRage\lib\dateutil\tz.py", line 114, in dst
    if self._isdst(dt):
  File "C:\SickRage\lib\dateutil\tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: (22, 'Invalid argument')

2015-03-27 19:26:44 Thread-139 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 723, in index
    return t.respond()
  File "C:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_home_tmpl.py", line 1014, in respond
    _v = VFN(VFSL([locals()]+SL+[globals(), builtin],"calendar",True),"timegm",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"pdatetime",True),"timetuple",False)()) # u'$calendar.timegm($pdatetime.timetuple())' on line 607, col 39
  File "C:\SickRage\lib\dateutil\tz.py", line 114, in dst
    if self._isdst(dt):
  File "C:\SickRage\lib\dateutil\tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: (22, 'Invalid argument')

2015-03-27 19:26:44 Thread-118 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 723, in index
    return t.respond()
  File "C:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_home_tmpl.py", line 1014, in respond
    _v = VFN(VFSL([locals()]+SL+[globals(), builtin],"calendar",True),"timegm",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"pdatetime",True),"timetuple",False)()) # u'$calendar.timegm($pdatetime.timetuple())' on line 607, col 39
  File "C:\SickRage\lib\dateutil\tz.py", line 114, in dst
    if self._isdst(dt):
  File "C:\SickRage\lib\dateutil\tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: (22, 'Invalid argument')

2015-03-27 19:26:43 Thread-112 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 723, in index
    return t.respond()
  File "C:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_home_tmpl.py", line 1014, in respond
    _v = VFN(VFSL([locals()]+SL+[globals(), builtin],"calendar",True),"timegm",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"pdatetime",True),"timetuple",False)()) # u'$calendar.timegm($pdatetime.timetuple())' on line 607, col 39
  File "C:\SickRage\lib\dateutil\tz.py", line 114, in dst
    if self._isdst(dt):
  File "C:\SickRage\lib\dateutil\tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: (22, 'Invalid argument')

2015-03-27 19:26:43 Thread-137 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 723, in index
    return t.respond()
  File "C:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_home_tmpl.py", line 1014, in respond
    _v = VFN(VFSL([locals()]+SL+[globals(), builtin],"calendar",True),"timegm",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"pdatetime",True),"timetuple",False)()) # u'$calendar.timegm($pdatetime.timetuple())' on line 607, col 39
  File "C:\SickRage\lib\dateutil\tz.py", line 114, in dst
    if self._isdst(dt):
  File "C:\SickRage\lib\dateutil\tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: (22, 'Invalid argument')

2015-03-27 19:26:42 Thread-59 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 723, in index
    return t.respond()
  File "C:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_home_tmpl.py", line 1014, in respond
    _v = VFN(VFSL([locals()]+SL+[globals(), builtin],"calendar",True),"timegm",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"pdatetime",True),"timetuple",False)()) # u'$calendar.timegm($pdatetime.timetuple())' on line 607, col 39
  File "C:\SickRage\lib\dateutil\tz.py", line 114, in dst
    if self._isdst(dt):
  File "C:\SickRage\lib\dateutil\tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: (22, 'Invalid argument')

2015-03-27 19:26:42 Thread-131 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 723, in index
    return t.respond()
  File "C:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_home_tmpl.py", line 1014, in respond
    _v = VFN(VFSL([locals()]+SL+[globals(), builtin],"calendar",True),"timegm",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"pdatetime",True),"timetuple",False)()) # u'$calendar.timegm($pdatetime.timetuple())' on line 607, col 39
  File "C:\SickRage\lib\dateutil\tz.py", line 114, in dst
    if self._isdst(dt):
  File "C:\SickRage\lib\dateutil\tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: (22, 'Invalid argument')

2015-03-27 19:26:41 Thread-119 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 723, in index
    return t.respond()
  File "C:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_home_tmpl.py", line 1014, in respond
    _v = VFN(VFSL([locals()]+SL+[globals(), builtin],"calendar",True),"timegm",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"pdatetime",True),"timetuple",False)()) # u'$calendar.timegm($pdatetime.timetuple())' on line 607, col 39
  File "C:\SickRage\lib\dateutil\tz.py", line 114, in dst
    if self._isdst(dt):
  File "C:\SickRage\lib\dateutil\tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: (22, 'Invalid argument')

2015-03-27 19:26:41 Thread-63 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 723, in index
    return t.respond()
  File "C:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_home_tmpl.py", line 1014, in respond
    _v = VFN(VFSL([locals()]+SL+[globals(), builtin],"calendar",True),"timegm",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"pdatetime",True),"timetuple",False)()) # u'$calendar.timegm($pdatetime.timetuple())' on line 607, col 39
  File "C:\SickRage\lib\dateutil\tz.py", line 114, in dst
    if self._isdst(dt):
  File "C:\SickRage\lib\dateutil\tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: (22, 'Invalid argument')

2015-03-27 19:26:41 Thread-123 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 723, in index
    return t.respond()
  File "C:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_home_tmpl.py", line 1014, in respond
    _v = VFN(VFSL([locals()]+SL+[globals(), builtin],"calendar",True),"timegm",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"pdatetime",True),"timetuple",False)()) # u'$calendar.timegm($pdatetime.timetuple())' on line 607, col 39
  File "C:\SickRage\lib\dateutil\tz.py", line 114, in dst
    if self._isdst(dt):
  File "C:\SickRage\lib\dateutil\tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: (22, 'Invalid argument')

2015-03-27 19:26:40 Thread-113 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 723, in index
    return t.respond()
  File "C:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_home_tmpl.py", line 1014, in respond
    _v = VFN(VFSL([locals()]+SL+[globals(), builtin],"calendar",True),"timegm",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"pdatetime",True),"timetuple",False)()) # u'$calendar.timegm($pdatetime.timetuple())' on line 607, col 39
  File "C:\SickRage\lib\dateutil\tz.py", line 114, in dst
    if self._isdst(dt):
  File "C:\SickRage\lib\dateutil\tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: (22, 'Invalid argument')

2015-03-27 19:26:40 Thread-60 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 723, in index
    return t.respond()
  File "C:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_home_tmpl.py", line 1014, in respond
    _v = VFN(VFSL([locals()]+SL+[globals(), builtin],"calendar",True),"timegm",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"pdatetime",True),"timetuple",False)()) # u'$calendar.timegm($pdatetime.timetuple())' on line 607, col 39
  File "C:\SickRage\lib\dateutil\tz.py", line 114, in dst
    if self._isdst(dt):
  File "C:\SickRage\lib\dateutil\tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: (22, 'Invalid argument')

2015-03-27 19:26:39 Thread-64 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 723, in index
    return t.respond()
  File "C:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_home_tmpl.py", line 1014, in respond
    _v = VFN(VFSL([locals()]+SL+[globals(), builtin],"calendar",True),"timegm",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"pdatetime",True),"timetuple",False)()) # u'$calendar.timegm($pdatetime.timetuple())' on line 607, col 39
  File "C:\SickRage\lib\dateutil\tz.py", line 114, in dst
    if self._isdst(dt):
  File "C:\SickRage\lib\dateutil\tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: (22, 'Invalid argument')

2015-03-27 19:26:39 Thread-61 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 723, in index
    return t.respond()
  File "C:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_home_tmpl.py", line 1014, in respond
    _v = VFN(VFSL([locals()]+SL+[globals(), builtin],"calendar",True),"timegm",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"pdatetime",True),"timetuple",False)()) # u'$calendar.timegm($pdatetime.timetuple())' on line 607, col 39
  File "C:\SickRage\lib\dateutil\tz.py", line 114, in dst
    if self._isdst(dt):
  File "C:\SickRage\lib\dateutil\tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: (22, 'Invalid argument')

2015-03-27 19:26:38 Thread-58 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 723, in index
    return t.respond()
  File "C:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_home_tmpl.py", line 1014, in respond
    _v = VFN(VFSL([locals()]+SL+[globals(), builtin],"calendar",True),"timegm",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"pdatetime",True),"timetuple",False)()) # u'$calendar.timegm($pdatetime.timetuple())' on line 607, col 39
  File "C:\SickRage\lib\dateutil\tz.py", line 114, in dst
    if self._isdst(dt):
  File "C:\SickRage\lib\dateutil\tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: (22, 'Invalid argument')

2015-03-27 19:26:37 Thread-59 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 723, in index
    return t.respond()
  File "C:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_home_tmpl.py", line 1014, in respond
    _v = VFN(VFSL([locals()]+SL+[globals(), builtin],"calendar",True),"timegm",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"pdatetime",True),"timetuple",False)()) # u'$calendar.timegm($pdatetime.timetuple())' on line 607, col 39
  File "C:\SickRage\lib\dateutil\tz.py", line 114, in dst
    if self._isdst(dt):
  File "C:\SickRage\lib\dateutil\tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: (22, 'Invalid argument')

2015-03-27 19:26:37 Thread-62 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 723, in index
    return t.respond()
  File "C:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_home_tmpl.py", line 1014, in respond
    _v = VFN(VFSL([locals()]+SL+[globals(), builtin],"calendar",True),"timegm",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"pdatetime",True),"timetuple",False)()) # u'$calendar.timegm($pdatetime.timetuple())' on line 607, col 39
  File "C:\SickRage\lib\dateutil\tz.py", line 114, in dst
    if self._isdst(dt):
  File "C:\SickRage\lib\dateutil\tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: (22, 'Invalid argument')

2015-03-27 19:26:36 Thread-60 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 723, in index
    return t.respond()
  File "C:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_home_tmpl.py", line 1014, in respond
    _v = VFN(VFSL([locals()]+SL+[globals(), builtin],"calendar",True),"timegm",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"pdatetime",True),"timetuple",False)()) # u'$calendar.timegm($pdatetime.timetuple())' on line 607, col 39
  File "C:\SickRage\lib\dateutil\tz.py", line 114, in dst
    if self._isdst(dt):
  File "C:\SickRage\lib\dateutil\tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: (22, 'Invalid argument')

2015-03-27 19:26:35 Thread-58 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 723, in index
    return t.respond()
  File "C:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_home_tmpl.py", line 1014, in respond
    _v = VFN(VFSL([locals()]+SL+[globals(), builtin],"calendar",True),"timegm",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"pdatetime",True),"timetuple",False)()) # u'$calendar.timegm($pdatetime.timetuple())' on line 607, col 39
  File "C:\SickRage\lib\dateutil\tz.py", line 114, in dst
    if self._isdst(dt):
  File "C:\SickRage\lib\dateutil\tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: (22, 'Invalid argument')

2015-03-27 19:26:34 Thread-58 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 723, in index
    return t.respond()
  File "C:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_home_tmpl.py", line 1014, in respond
    _v = VFN(VFSL([locals()]+SL+[globals(), builtin],"calendar",True),"timegm",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"pdatetime",True),"timetuple",False)()) # u'$calendar.timegm($pdatetime.timetuple())' on line 607, col 39
  File "C:\SickRage\lib\dateutil\tz.py", line 114, in dst
    if self._isdst(dt):
  File "C:\SickRage\lib\dateutil\tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: (22, 'Invalid argument')

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1037

**Comment by fernandog** [comment]
We will push a fix sunday. This does not impact the SR search&download
@abeloin

**Comment by abeloin** [comment]
@fernandog Yes?

Ref https://github.com/SiCKRAGETV/SickRage/pull/1648

**Comment by fernandog** [comment]
Yes. Just FYI
