### ISSUE TITLE
Unicode Encode Error in Calendar

### ISSUE THREAD

**Issue by tchirou** [SiCKRAGETV/sickrage-issues#1069]
Hello
BRANCH: (master) / COMMIT: (33921ecd1697f99ef47015c700331358481c9b98) 
Python 2.7.6 / Win 8.1

Recently added shows didn't appear in the calendar. So I wanted to take a look at http://sickrage.local:8081/calendar which gives the following

Error
'charmap' codec can't encode character u'\u014d' in position 62: character maps to

Traceback
```
Traceback (most recent call last): 
File "C:\Program Files (x86)\SABnzbd\SickRage\tornado\web.py", line 1336, in _execute result = method(*self.path_args, **self.path_kwargs) 
File "C:\Program Files (x86)\SABnzbd\SickRage\sickbeard\webserve.py", line 545, in get self.write(self.calendar()) 
File "C:\Program Files (x86)\SABnzbd\SickRage\sickbeard\webserve.py", line 609, in calendar episode['description'].splitlines()[0]) 
File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode return codecs.charmap_encode(input,errors,encoding_table) 
UnicodeEncodeError: 'charmap' codec can't encode character u'\u014d' in position 62: character maps to 
```
Many thanks

**Comment by fernandog** [comment]
@tchirou test this please:

stop SR
edit SickRage/sickbeard/webserve.py
and do this change:
https://github.com/fernandog/SickRage/commit/792042b52508d55e0f24b538726be040202ca3db
start SR,
test and report

**Comment by tchirou** [comment]
Thanks bit does not work

**Comment by tchirou** [comment]
Error

'utf8' codec can't decode byte 0x93 in position 50: invalid start byte

Traceback

Traceback (most recent call last): 
File "C:\Program Files (x86)\SABnzbd\SickRage\tornado\web.py", line 1336, in _execute result = method(*self.path_args, **self.path_kwargs) 
File "C:\Program Files (x86)\SABnzbd\SickRage\sickbeard\webserve.py", line 545, in get self.write(self.calendar()) 
File "C:\Program Files (x86)\SABnzbd\SickRage\sickbeard\webserve.py", line 609, in calendar episode['description'].decode('utf-8').splitlines()[0]) 
File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode return codecs.utf_8_decode(input, errors, True) 
UnicodeDecodeError: 'utf8' codec can't decode byte 0x93 in position 50: invalid start byte

**Comment by fernandog** [comment]
@tchirou updated the code. read above comment again

**Comment by tchirou** [comment]
Oh I clicked on the link directly in the mail
I will try tonight
Thanks

**Comment by tchirou** [comment]
Hello
It works.
Except there is a new update and I can't update. I checked git reset in the webui. I even tried with a git checkout master, git reset --hard HEAD, git pull but I get an error saying I have to commit the changes in postprocessor.py

**Comment by tchirou** [comment]
Alright I followed this 
git remote add upstream https://github.com/SiCKRAGETV/SickRage.git
git fetch upstream
git checkout master
git reset --hard upstream/master
git pull
And the update worked
Great job guys
