### ISSUE TITLE
Synology. Sickbeard-Custom. No automatic Post-Processing

### ISSUE THREAD

**Issue by Xusqui** [SiCKRAGETV/sickrage-issues#1111]
Branch: Master (Sickbeard-custom)
Commit Hash: ff7aee90fd26db93cc571be1cb5c62a6fcf08e19
System: Synology DSM 5.2. (Synology DS214Play).
Python: Python: 2.7.9-13

I use Torrents, which are sent to Synology DownloadStation and files are downloaded to /volumeUSB1/usbshare1-1/download/DownloadStation

I configured Sickrage to perform automatic post-processing every 10 minutes, but no auto-post-processing is done. When I perform manual post-processing, everything is moved to its place.

The log starts at 10:48 and stops at 1:28. As it is programmed to perform the action every 10 minutes, it should have tried to do it at least 3 times, but nothing is shown in the log (actually, nothing is done)

Gist Log: https://gist.githubusercontent.com/Xusqui/e98c04ea5552cfb4650b/raw/No%20auto-post-processing

Thanks in advance!

**Comment by neoatomic** [comment]
@Xusqui Looks like a permission problem.

``` 

2015-04-05 10:49:38 ERROR    SHOWQUEUE-REFRESH :: File air date stamping failed. The error is: 1 and the message is: Operation not permitted.
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1219, in touchFile
    os.utime(fname, (atime, atime))
OSError: [Errno 1] Operation not permitted: '/volumeUSB1/usbshare1-1/Series/The Walking Dead/Season 1/The.Walking.Dead.S01E01.720p.HDTV.x264-CTU.avi'
2015-04-05 10:49:38 ERROR    SHOWQUEUE-REFRESH :: 153021: Unable to modify date of The.Walking.Dead.S01E01.720p.HDTV.x264-CTU.avi to show air date Nov 01,2010 (02:00)
None
2015-04-05 10:49:38 DEBUG    SHOWQUEUE-REFRESH :: 153021: About to modify date of '/volumeUSB1/usbshare1-1/Series/The Walking Dead/Season 1/The.Walking.Dead.S01E02.720p.HDTV.x264-CTU.avi' to show air date Nov 08,2010 (03:00)
2015-04-05 10:49:38 ERROR    SHOWQUEUE-REFRESH :: File air date stamping failed. The error is: 1 and the message is: Operation not permitted.
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1219, in touchFile
    os.utime(fname, (atime, atime))
```

**Comment by fernandog** [comment]
@Xusqui disable change date/time setting in PP

**Comment by Xusqui** [comment]
OK. I disabled changing date/time and don't have those errors... But anyway Auto-Post-Processing is not performed :(, actually SickRage doesn't realizes when a download is finished and is always marked as snatched. Only changes to downloaded when a manual post-proc is done.

I also noticed an issue with thepiratebay, so I'm starting a new threat.

**Comment by abeloin** [comment]
@Xusqui Restart SR and check PP is running after the restart

**Comment by Xusqui** [comment]
Yes, I forgot to say I had already rebooted the whole NAS and still didn't work :(

**Comment by TRBPRO23** [comment]
I am also having the same issue.

**Comment by abeloin** [comment]
@Xusqui Post log
@TRBPRO23 Post log

**Comment by Xusqui** [comment]
Sorry... Very busy these days!!!

I fixed it by ticketing the option "Scan and process" under the Post-Processing options...
