### ISSUE TITLE
Sickrage is not notifying Plex when show has been processed. Kodi error also?

### ISSUE THREAD

**Issue by ruinit** [SiCKRAGETV/sickrage-issues#1123]
Sickrage is not notifying Plex server when shows are processed?

I am trying to set up notifications and sickrage is not notifying Plex that shows have been post processed? The errors I am getting relate to KODI which I don't even have enabled? Any help would be great.

2015-04-03 10:51:22 Thread-67 :: Failed to detect KODI version for '192.168.1.250:32400', check configuration and try again. 2015-04-03 10:51:21 Thread-50 :: Failed to detect KODI version for '192.168.1.250:32400', check configuration and try again.
​
Kodi is not enabled but keep getting these in log?

2015-04-03 14:03:15 POSTPROCESSER :: Exception generated in thread POSTPROCESSER: mismatched tag: line 8, column 2 2015-04-03 14:03:14 POSTPROCESSER :: Failed to detect KODI version for '192.168.1.250:3000', check configuration and try again.

Had to disable plex notifications to make the errors go away.

Plex settings
http://pasteboard.co/2jHRyk82.png

**Comment by fernandog** [comment]
@ruinit FULL logs in GIST

**Comment by ruinit** [comment]
MediaServer> vi config.ini
[General]
git_autoissues = 0
git_username = ""
git_password = ""
git_reset = 0
branch = master
git_remote = origin
git_remote_url = https://github.com/SiCKRAGETV/SickRage.git
cur_commit_hash = 345541ef6313f8f5d7ff45ef84647d44a2c29304
cur_commit_branch = ""
config_version = 7
encryption_version = 2
encryption_secret = uigZD+sQSbOEm4agTAwyPx2gf0WZpk7zqV9iuEl+VKY=
log_dir = Logs
log_nr = 5
log_size = 1048576
socket_timeout = None
web_port = 8083
web_host = 0.0.0.0
web_ipv6 = 0
web_log = 0
web_root = ""
web_username = ""
- config.ini 1/777 0%

**Comment by abeloin** [comment]
@ruinit Please update and test again

**Comment by ruinit** [comment]
Didn't call KODI but take a look at log not sure it worked properly either

2015-04-06 17:59:17 Thread-21 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
RuntimeError: maximum recursion depth exceeded

Log
https://gist.github.com/ruinit/6e006ef283996b8fd1ec

**Comment by abeloin** [comment]
Reverted PR

**Comment by abeloin** [comment]
Please update

**Comment by ruinit** [comment]
getting failed update :(

**Comment by abeloin** [comment]
What the log says?

**Comment by ruinit** [comment]
I think it overwrote the log I did a reset pull can't find the error now

**Comment by ruinit** [comment]
2015-04-06 18:59:54 DEBUG    TORNADO :: Failed doing webui request "update": Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 243, in get
    results = yield self.async_call(method)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/tornado/gen.py", line 642, in run
    value = future.result()
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/_base.py", line 400, in result
    return self.__get_result()
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1089, in update
    if sickbeard.versionCheckScheduler.action.update():
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/versionChecker.py", line 269, in update
    return self.updater.update()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/versionChecker.py", line 561, in update
    notifiers.notify_git_update(sickbeard.CUR_COMMIT_HASH if sickbeard.CUR_COMMIT_HASH else "")
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/notifiers/__init__.py", line 111, in notify_git_update
    n.notify_git_update(new_version)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/notifiers/plex.py", line 74, in notify_git_update
    self._notify_pmc(update_text + new_version, title)

**Comment by ruinit** [comment]
Do you need anything else from me on this bug?

**Comment by abeloin** [comment]
@ruinit Been a rough week, pushed back to v4.0.17

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1206

**Comment by Thraxis** [comment]
@ruinit Are you using Plex Home Theater (PHT) ?

**Comment by ruinit** [comment]
Using on Plex Media Server on A Synology Diskstation Nas. Using the Plexpass version if that matters

**Comment by Thraxis** [comment]
Needed to know if it was PMS vs PHT and yes Plexpass does matter but it looks like you have the auth token in already.

I'd say you can remove the Plex Client IP / Port as you're trying to update the PMS nor a client.
And can you confirm that your Plex Server IP is correct?

**Comment by ruinit** [comment]
getting this now all of a sudden 
2015-04-13 15:23:14 CHECKVERSION :: git symbolic-ref -q HEAD returned : fatal: unable to access '.git/config': Permission denied

**Comment by ruinit** [comment]
@Thraxis 
taking out plex client ip gives me an error that says please fill out spaces. 
Plex server ip is correct http://192.168.1.250:32400/web/index.html takes me to my plex media server page.

I get this error still and Kodi is not enabled 
2015-04-13 15:32:03 ERROR    Thread-30 :: Failed to detect KODI version for '192.168.1.250:3000', check configuration and try again.
2015-04-13 15:32:03 WARNING  Thread-30 :: Warning: Couldn't contact KODI HTTP at http://192.168.1.250:3000/kodiCmds/kodiHttp/?command=Help error [Errno 111] Connection refused
2015-04-13 15:32:03 WARNING  Thread-30 :: Error while trying to retrieve KODI API version for 192.168.1.250:3000: error [Errno 111] Connection refused
2015-04-13 15:32:03 INFO     Thread-30 :: Sending KODI notification to '192.168.1.250:3000' - Testing Plex notifications from SickRage

**Comment by abeloin** [comment]
@ruinit Make sure SR has the proper permissions to access that file(chmod,chown)

>2015-04-13 15:23:14 CHECKVERSION :: git symbolic-ref -q HEAD returned : fatal: unable to access '.git/config': Permission denied

**Comment by fernandog** [comment]
@Thraxis you can change label from "fix pending" to "fix" when there's a PR available that fix the issue and remove priority - if it was set =)

**Comment by ruinit** [comment]
I am still getting this error config.ini has 777 permissions
2015-04-15 13:58:41 Thread-57 :: git symbolic-ref -q HEAD returned : fatal: unable to access '.git/config': Permission denied
Also checkout branch is still no selection available. Not sure what to do here

**Comment by ruinit** [comment]
@Thraxis I do not seem to be getting kodi errors any longer on the Develop version
