### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/mnt/scratch/temp/Greek S01E22 DVDRip XviD-ORPHEUS/greek.s01e22.dvdrip.xvid-orpheus.1.avi'

### ISSUE THREAD

**Issue by thecolorchanges** [SiCKRAGETV/sickrage-issues#1171]
### INFO
Python Version: **2.6.5 (r265:79063, Jul 24 2010, 21:39:31) [GCC 4.2.3]**
Operating System: **Linux-3.0.3-unRAID-i686-AMD_Athlon-tm-_II_Neo_N36L_Dual-Core_Processor-with-slackware-13.1.0**
Locale: UTF8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@449115e9d2542cfdf815ff4ac6834bc62267d21e
Link to Log: https://gist.github.com/929d5cf88dd8604a6f79
### ERROR
```
Thread-40 :: Failed doing webui callback: Traceback (most recent call last):
  File "/mnt/scratch/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/mnt/scratch/SickRage/sickbeard/webserve.py", line 2144, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/mnt/scratch/SickRage/sickbeard/processTV.py", line 203, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/mnt/scratch/SickRage/sickbeard/processTV.py", line 504, in process_media
    result.result = processor.process()
  File "/mnt/scratch/SickRage/sickbeard/postProcessor.py", line 866, in process
    existing_file_status = self._checkForExistingFile(ep_obj.location)
  File "/mnt/scratch/SickRage/sickbeard/postProcessor.py", line 132, in _checkForExistingFile
    if ek.ek(os.path.getsize, existing_file) > ek.ek(os.path.getsize, self.file_path):
  File "/mnt/scratch/SickRage/sickbeard/encodingKludge.py", line 58, in ek
    result = func(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
  File "/usr/lib/python2.6/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/mnt/scratch/temp/Greek S01E22 DVDRip XviD-ORPHEUS/greek.s01e22.dvdrip.xvid-orpheus.1.avi'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by thecolorchanges** [comment]
Error in PostProcessing. All shows affected.

**Comment by abeloin** [comment]
Please post all sickrage.log files in sickrage/Logs folder

**Comment by thecolorchanges** [comment]
All logs uploaded to gist. Please let me know if I can assist further
https://gist.github.com/thecolorchanges

**Comment by thecolorchanges** [comment]
Normal daily search postprocessing seems to be working. I had invoked a backlog search on this specific show and a few others that produced the error. Sorry for not mentioning sooner!

**Comment by abeloin** [comment]
Is it possible that you download this release with SABnzb 2 times, that would explain the 1 in the file

**Comment by thecolorchanges** [comment]
I selected a season that was 'skipped' and changed to 'wanted' hit go and invoked the backlog search. The really weird thing is that it did move the episode, but it would also move the ".1" file as well which was only ~15MB or so. Once I deleted the .1's manually Plex and Kodi played the episode just fine. It's almost like it was trying to copy twice at the same time.

**Comment by fernandog** [comment]
@thecolorchanges when you change to wanted it already does a backlog search. Did pushed manual searchafter changed to want? Maybe it downloaded twice.

**Comment by thecolorchanges** [comment]
@fernandog I changed to wanted and hit go, knowing the backlog would kickoff automatically. I did not perform manual searches, double-checked SabNZBD's queue at the time and only 1 episode was grabbed and moved to the post-process folder.

**Comment by fernandog** [comment]
@thecolorchanges check the file inside the nzb in your nzbindexer. See if the original file has ".1" in it

**Comment by fernandog** [comment]
@TagForce any thoughts on this one?

**Comment by TagForce** [comment]
@fernandog from sickrage.log.2:
```
Moving file from /mnt/scratch/temp/Greek S01E17 DVDRip XviD-ORPHEUS/greek.s01e17.dvdrip.xvid-orpheus.1.avi to /mnt/sublight/TV_Overflow/Greek/Season 1/Greek - S01E17 - 47 Hours & 11 Minutes.1.avi
```

What is happening is the following:
One of 2 things happen first:
The release actually has a file with .1.avi as an extension OR the release is downloaded twice (unlikely as only the avi has a .1.avi duplicate), and get downloaded to the complete folder:
```/mnt/scratch/temp/Greek S01E17 DVDRip XviD-ORPHEUS/```

Post Processing happens which lists the following:
All video files in the folder (so both the avi's)
All unwanted files (every file that is not a video file)
Associated files (every file that starts with the filename of the videofile excluding the extension)

This means that unwanted files does NOT have the .1.avi file, and associated files DOES have the .1.avi file. Post Processing happens for the good avi file, and move associated files is turned on, so it moves the avi file first, and then moves the associated files (including the .1.avi file)...

Post Processing finishes correctly for the correct avi, and proceeds with the next avi file, which is the .1.avi file... But that has just been moved already. And that causes the error.

The relevant lines from the log for this file:
```
2015-04-10 09:49:11 DEBUG    Thread-63 :: Moving file from /mnt/scratch/temp/Greek S01E17 DVDRip XviD-ORPHEUS/greek.s01e17.dvdrip.xvid-orpheus.avi to /mnt/sublight/TV_Overflow/Greek/Season 1/Greek - S01E17 - 47 Hours & 11 Minutes.avi
2015-04-10 09:49:15 DEBUG    Thread-63 :: Setting permissions for /mnt/sublight/TV_Overflow/Greek/Season 1/Greek - S01E17 - 47 Hours & 11 Minutes.avi to 666 as parent directory has 777
2015-04-10 09:49:15 DEBUG    Thread-63 :: Moving file from /mnt/scratch/temp/Greek S01E17 DVDRip XviD-ORPHEUS/greek.s01e17.dvdrip.xvid-orpheus.nfo to /mnt/sublight/TV_Overflow/Greek/Season 1/Greek - S01E17 - 47 Hours & 11 Minutes.nfo-orig
2015-04-10 09:49:15 DEBUG    Thread-63 :: Setting permissions for /mnt/sublight/TV_Overflow/Greek/Season 1/Greek - S01E17 - 47 Hours & 11 Minutes.nfo-orig to 666 as parent directory has 777
2015-04-10 09:49:15 DEBUG    Thread-63 :: Moving file from /mnt/scratch/temp/Greek S01E17 DVDRip XviD-ORPHEUS/greek.s01e17.dvdrip.xvid-orpheus.sfv to /mnt/sublight/TV_Overflow/Greek/Season 1/Greek - S01E17 - 47 Hours & 11 Minutes.sfv
2015-04-10 09:49:15 DEBUG    Thread-63 :: Setting permissions for /mnt/sublight/TV_Overflow/Greek/Season 1/Greek - S01E17 - 47 Hours & 11 Minutes.sfv to 666 as parent directory has 777
2015-04-10 09:49:15 DEBUG    Thread-63 :: Moving file from /mnt/scratch/temp/Greek S01E17 DVDRip XviD-ORPHEUS/greek.s01e17.dvdrip.xvid-orpheus.1.avi to /mnt/sublight/TV_Overflow/Greek/Season 1/Greek - S01E17 - 47 Hours & 11 Minutes.1.avi
```

To fix this: I could remove any video file from the associated file list, but this will likely cause leftover files if the release comes with a sample file.
Another solution would be to check whether the releases really have a .1.avi file, and if not, figure out why SabNZBd creates them.

**Comment by abeloin** [comment]
@TagForce Sabnzbd create them when there is duplicate data, see the following:

https://forums.sabnzbd.org/viewtopic.php?t=9795

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1319
