### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by trancen** [SiCKRAGETV/sickrage-issues#1177]
Got the following Error: 
SR Version:	BRANCH: (master) / COMMIT: (669046ea40a7a26a6121a1b07721f3c1c3cf5b10) 
Python Version:	2.7.3 (default, Feb 27 2014, 19:37:34) [GCC 4.7.2]

```
AA
AAValueError: No JSON object could be decoded
AA    raise ValueError("No JSON object could be decoded")
AA  File "/var/www/sickrage/lib/simplejson/decoder.py", line 353, in raw_decode
AA    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
AA  File "/var/www/sickrage/lib/simplejson/decoder.py", line 335, in decode
AA    return _default_decoder.decode(s)
AA  File "/var/www/sickrage/lib/simplejson/__init__.py", line 307, in loads
AA    return json.loads(self.text, **kwargs)
AA  File "/var/www/sickrage/lib/requests/models.py", line 799, in json
AA    return resp.content if not json else resp.json()
AA  File "/var/www/sickrage/sickbeard/helpers.py", line 1311, in getURL
AA    session=self.session, json=json, proxyGlypeProxySSLwarning=self.proxyGlypeProxySSLwarning)
AA  File "/var/www/sickrage/sickbeard/providers/generic.py", line 135, in getURL
AA    parsedJSON = self.getURL(searchURL, json=True)
AA  File "/var/www/sickrage/sickbeard/providers/eztv.py", line 96, in _doSearch
AA    itemList += self._doSearch(curString, 'eponly', len(episodes), epObj=epObj)
AA  File "/var/www/sickrage/sickbeard/providers/generic.py", line 293, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/var/www/sickrage/sickbeard/search.py", line 480, in searchProviders
AAValueError: No JSON object could be decoded
AA    raise ValueError("No JSON object could be decoded")
AA  File "/var/www/sickrage/lib/simplejson/decoder.py", line 353, in raw_decode
AA    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
AA  File "/var/www/sickrage/lib/simplejson/decoder.py", line 335, in decode
AA    return _default_decoder.decode(s)
AA  File "/var/www/sickrage/lib/simplejson/__init__.py", line 307, in loads
AA    return json.loads(self.text, **kwargs)
AA  File "/var/www/sickrage/lib/requests/models.py", line 799, in json
AA    return resp.content if not json else resp.json()
AA  File "/var/www/sickrage/sickbeard/helpers.py", line 1311, in getURL
AA    session=self.session, json=json, proxyGlypeProxySSLwarning=self.proxyGlypeProxySSLwarning)
AA  File "/var/www/sickrage/sickbeard/providers/generic.py", line 135, in getURL
AA    parsedJSON = self.getURL(searchURL, json=True)
AA  File "/var/www/sickrage/sickbeard/providers/eztv.py", line 96, in _doSearch
AA    itemList += self._doSearch(curString, 'eponly', len(episodes), epObj=epObj)
AA  File "/var/www/sickrage/sickbeard/providers/generic.py", line 293, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/var/www/sickrage/sickbeard/search.py", line 480, in searchProviders
AATraceback (most recent call last):
2015-04-10 18:31:35 ERROR    SEARCHQUEUE-MANUAL-281662 :: [EZTV] :: Error while searching EZTV, skipping: No JSON object could be decoded
```

**Comment by abeloin** [comment]
Fix in develop, will me merged in master on Sunday

**Comment by trancen** [comment]
Thanks

**Comment by abeloin** [comment]
@trancen Please update and report. Thanks

**Comment by trancen** [comment]
Resolved.

**Comment by trancen** [comment]
Resolved.
