### ISSUE TITLE
[APP SUBMITTED]: [Errno 13] Permission denied: '/home'

### ISSUE THREAD

**Issue by javelin4effect** [SiCKRAGETV/sickrage-issues#1183]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.2.0-72-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
Link to Log: https://gist.github.com/1e64169e559fb376f6aa
### ERROR
```
Thread-255 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/disk20/blade3dfx/sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/disk20/blade3dfx/sickrage/sickbeard/webserve.py", line 655, in index
    return json.dumps(foldersAtPath(path, True, bool(int(includeFiles))))
  File "/home/disk20/blade3dfx/sickrage/sickbeard/browser.py", line 87, in foldersAtPath
    fileList = [{'name': filename, 'path': ek.ek(os.path.join, parentPath, filename)} for filename in ek.ek(os.listdir, parentPath)]
  File "/home/disk20/blade3dfx/sickrage/sickbeard/encodingKludge.py", line 58, in ek
    result = func(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
OSError: [Errno 13] Permission denied: '/home'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
Make sure SR user has the proper permission for /home/disk20
