### ISSUE TITLE
[APP SUBMITTED]: unsupported operand type(s) for -: 'str' and 'int'

### ISSUE THREAD

**Issue by EirikUtvik** [SiCKRAGETV/sickrage-issues#1187]
### INFO
Python Version: **2.7.3 (default, Dec 27 2013, 16:05:18) [GCC 4.6.3]**
Operating System: **Linux-3.4.26-i686-with-glibc2.3**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
Link to Log: https://gist.github.com/91997dbb6967eb54b5e3
### ERROR
```
Thread-92 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/sickbeard/webserve.py", line 2140, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/sickbeard/processTV.py", line 203, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/sickbeard/processTV.py", line 504, in process_media
    result.result = processor.process()
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/sickbeard/postProcessor.py", line 841, in process
    old_ep_status, old_ep_quality = common.Quality.splitCompositeStatus(ep_obj.status)
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/sickbeard/common.py", line 260, in splitCompositeStatus
    return (status - x * 100, x)
TypeError: unsupported operand type(s) for -: 'str' and 'int'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@EirikUtvik please do a mass update in all your shows

**Comment by D4nte** [comment]
Hi,

I have the same issue. did a mass update and errors are still appearing.

Best regards,
D4nte
