### ISSUE TITLE
[APP SUBMITTED]: HTTPSConnectionPool(host='sceneaccess.eu', port=443): Read timed out. (read timeout=30)

### ISSUE THREAD

**Issue by larstomas** [SiCKRAGETV/sickrage-issues#1188]
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:07:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [SceneAccess] :: Failed parsing SceneAccess Traceback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/scc.py", line 225, in _doSearch
    data = self.getURL(self.url + "/" + link['href'])
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/generic.py", line 126, in getURL
    if not self._doLogin():
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/scc.py", line 95, in _doLogin
    response = self.session.post(self.urls['login'], data=login_params, headers=self.headers, timeout=30, verify=False)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 504, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 599, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 192, in resolve_redirects
    allow_redirects=False,
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/cachecontrol/adapter.py", line 34, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='sceneaccess.eu', port=443): Read timed out. (read timeout=30)

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
Check your internet connection or sceneacces.eu, one of them didn't respond
