### ISSUE TITLE
Show Updater Error

### ISSUE THREAD

**Issue by tjw1184** [SiCKRAGETV/sickrage-issues#1193]
BRANCH: (master) / COMMIT: (669046ea40a7a26a6121a1b07721f3c1c3cf5b10) 

Every night, the show updater appears to error out.  Logs and specific error lines below:

From Error Logs:

```
AAUnboundLocalError: local variable 'curQueueItem' referenced before assignment
AA    piList.append(curQueueItem)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/showUpdater.py", line 90, in run
AA    self.action.run(self.force)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/scheduler.py", line 79, in run
AATraceback (most recent call last):
2015-04-11 03:18:08 ERROR    SHOWUPDATER :: Exception generated in thread SHOWUPDATER: local variable 'curQueueItem' referenced before assignment
2015-04-11 03:17:55 INFO     SHOWUPDATER :: Trying to clean cache folder /usr/local/sickbeard-custom/var/cache
2015-04-11 03:17:55 INFO     SHOWUPDATER :: Doing full update on all shows
```

From debug logs:

```
2015-04-11 03:18:08 DEBUG    SHOWUPDATER :: 'Traceback (most recent call last):\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/scheduler.py", line 79, in run\n    self.action.run(self.force)\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/showUpdater.py", line 90, in run\n    piList.append(curQueueItem)\nUnboundLocalError: local variable \'curQueueItem\' referenced before assignment\n'
2015-04-11 03:18:08 ERROR    SHOWUPDATER :: Exception generated in thread SHOWUPDATER: local variable 'curQueueItem' referenced before assignment
2015-04-11 03:18:08 DEBUG    SHOWUPDATER :: Unable to update show: SHOW NAME is in process of being updated by Post-processor or manually started, can't update again until it's done.
2015-04-11 03:18:08 DEBUG    SHOWUPDATER :: 269008: No episode found... need to implement a show status
2015-04-11 03:18:08 DEBUG    SHOWUPDATER :: 269008: Finding the episode which airs next
2015-04-11 03:17:55 INFO     SHOWUPDATER :: Trying to clean cache folder /usr/local/sickbeard-custom/var/cache
2015-04-11 03:17:55 INFO     SHOWUPDATER :: Doing full update on all shows
```

**Comment by MaximusCub** [comment]
I'm new here, but posted a patch to fix this issue. Hopefully it gets accepted. :)

**Comment by fernandog** [comment]
@MaximusCub welcome!

Feel free to pick other issue:
https://github.com/SiCKRAGETV/sickrage-issues/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+-label%3A%221%3A+Support+%2F+question%22+-label%3A%221%3A+Feature+request%22+-label%3A%223%3A+Fix%22+

**Comment by tjw1184** [comment]
Thanks @MaximusCub!

**Comment by fernandog** [comment]
Merged in develop branch
