### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by javelin4effect** [SiCKRAGETV/sickrage-issues#1194]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.2.0-72-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
No Log available with ERRORS: 
### ERROR
```
Thread-42 :: Unable to run synoindex: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

```
AA
AAKeyError: 522
AA    resp.status_code) + ': ' + clients.http_error_code[resp.status_code], logger.DEBUG)
AA  File "/home/disk20/*********/sickrage/sickbeard/helpers.py", line 1286, in getURL
2015-04-13 07:33:36 WARNING  SEARCHQUEUE-BACKLOG-71663 :: [ThePirateBay] :: Unknown exception while loading URL https://thepiratebay.se/search/The.Simpsons%20S05E08%7C5x08%20/0/7/200: Traceback (most recent call last):
```

**Comment by abeloin** [comment]
Need more debug logs

**Comment by javelin4effect** [comment]
Sickrage use to download the vidoes automatically to my seed server, now it
just puts the torrent file on the seed server.

attached is my log

thanks for any help you can provide

On Mon, Apr 13, 2015 at 12:28 AM, Alexandre Beloin <notifications@github.com
> wrote:

> Need more debug logs
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/sickrage-issues/issues/1194#issuecomment-92080624>
> .
>



-- 
Warrant Officer Three

2015-04-13 07:33:54 INFO     SEARCHQUEUE-BACKLOG-71663 :: No needed episodes found during backlog search for: [The Simpsons]
AA
AAKeyError: 522
AA    resp.status_code) + ': ' + clients.http_error_code[resp.status_code], logger.DEBUG)
AA  File "/home/disk20/*********/sickrage/sickbeard/helpers.py", line 1286, in getURL
2015-04-13 07:33:54 WARNING  SEARCHQUEUE-BACKLOG-71663 :: [ThePirateBay] :: Unknown exception while loading URL https://thepiratebay.se/search/The.Simpsons%20S13E12%7C13x12%20/0/7/200: Traceback (most recent call last):
2015-04-13 07:33:39 INFO     SEARCHQUEUE-BACKLOG-71663 :: [ThePirateBay] :: Performing episode search for The Simpsons
2015-04-13 07:33:38 INFO     SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Performing episode search for The Simpsons
2015-04-13 07:33:38 INFO     SEARCHQUEUE-BACKLOG-71663 :: [KickAssTorrents] :: Performing episode search for The Simpsons
2015-04-13 07:33:38 INFO     SEARCHQUEUE-BACKLOG-71663 :: [FreshOnTV] :: Performing episode search for The Simpsons
2015-04-13 07:33:38 INFO     SEARCHQUEUE-BACKLOG-71663 :: Building internal name cache for The Simpsons
2015-04-13 07:33:38 INFO     SEARCHQUEUE-BACKLOG-71663 :: No scene exceptions update needed
2015-04-13 07:33:38 INFO     SEARCHQUEUE-BACKLOG-71663 :: Beginning backlog search for: [The Simpsons]
2015-04-13 07:33:36 INFO     SEARCHQUEUE-BACKLOG-71663 :: No needed episodes found during backlog search for: [The Simpsons]
AA
AAKeyError: 522
AA    resp.status_code) + ': ' + clients.http_error_code[resp.status_code], logger.DEBUG)
AA  File "/home/disk20/*********/sickrage/sickbeard/helpers.py", line 1286, in getURL
2015-04-13 07:33:36 WARNING  SEARCHQUEUE-BACKLOG-71663 :: [ThePirateBay] :: Unknown exception while loading URL https://thepiratebay.se/search/The.Simpsons%20S05E08%7C5x08%20/0/7/200: Traceback (most recent call last):
2015-04-13 07:33:21 INFO     SEARCHQUEUE-BACKLOG-71663 :: [ThePirateBay] :: Performing episode search for The Simpsons
2015-04-13 07:33:20 INFO     SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Performing episode search for The Simpsons
2015-04-13 07:33:20 INFO     SEARCHQUEUE-BACKLOG-71663 :: [KickAssTorrents] :: Performing episode search for The Simpsons
2015-04-13 07:33:20 INFO     SEARCHQUEUE-BACKLOG-71663 :: [FreshOnTV] :: Performing episode search for The Simpsons
2015-04-13 07:33:20 INFO     SEARCHQUEUE-BACKLOG-71663 :: Building internal name cache for The Simpsons
2015-04-13 07:33:20 INFO     SEARCHQUEUE-BACKLOG-71663 :: No scene exceptions update needed
2015-04-13 07:33:20 INFO     SEARCHQUEUE-BACKLOG-71663 :: Beginning backlog search for: [The Simpsons]
2015-04-13 07:33:18 INFO     SEARCHQUEUE-BACKLOG-71663 :: No needed episodes found during backlog search for: [The Simpsons]
AA
AAKeyError: 522
AA    resp.status_code) + ': ' + clients.http_error_code[resp.status_code], logger.DEBUG)
AA  File "/home/disk20/*********/sickrage/sickbeard/helpers.py", line 1286, in getURL
2015-04-13 07:33:18 WARNING  SEARCHQUEUE-BACKLOG-71663 :: [ThePirateBay] :: Unknown exception while loading URL https://thepiratebay.se/search/The.Simpsons%20S02E18%7C2x18%20/0/7/200: Traceback (most recent call last):
2015-04-13 07:33:03 INFO     SEARCHQUEUE-BACKLOG-71663 :: [ThePirateBay] :: Performing episode search for The Simpsons
2015-04-13 07:33:02 INFO     SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Performing episode search for The Simpsons
2015-04-13 07:33:02 INFO     SEARCHQUEUE-BACKLOG-71663 :: [KickAssTorrents] :: Performing episode search for The Simpsons
2015-04-13 07:33:02 INFO     SEARCHQUEUE-BACKLOG-71663 :: [FreshOnTV] :: Performing episode search for The Simpsons
2015-04-13 07:33:02 INFO     SEARCHQUEUE-BACKLOG-71663 :: Building internal name cache for The Simpsons
2015-04-13 07:33:02 INFO     SEARCHQUEUE-BACKLOG-71663 :: No scene exceptions update needed
2015-04-13 07:33:02 INFO     SEARCHQUEUE-BACKLOG-71663 :: Beginning backlog search for: [The Simpsons]
2015-04-13 07:32:59 INFO     SEARCHQUEUE-BACKLOG-75978 :: No needed episodes found during backlog search for: [Family Guy]
AA
AAKeyError: 522
AA    resp.status_code) + ': ' + clients.http_error_code[resp.status_code], logger.DEBUG)
AA  File "/home/disk20/*********/sickrage/sickbeard/helpers.py", line 1286, in getURL
2015-04-13 07:32:59 WARNING  SEARCHQUEUE-BACKLOG-75978 :: [ThePirateBay] :: Unknown exception while loading URL https://thepiratebay.se/search/Family%20Guy%20Season%207%20-Ep%2A/0/7/200: Traceback (most recent call last):
AA
AAKeyError: 522
AA    resp.status_code) + ': ' + clients.http_error_code[resp.status_code], logger.DEBUG)
AA  File "/home/disk20/*********/sickrage/sickbeard/helpers.py", line 1286, in getURL
2015-04-13 07:32:44 WARNING  SEARCHQUEUE-BACKLOG-75978 :: [ThePirateBay] :: Unknown exception while loading URL https://thepiratebay.se/search/Family%20Guy%20Season%207%20-Ep%2A/0/7/200: Traceback (most recent call last):
AA
AAKeyError: 522
AA    resp.status_code) + ': ' + clients.http_error_code[resp.status_code], logger.DEBUG)
AA  File "/home/disk20/*********/sickrage/sickbeard/helpers.py", line 1286, in getURL
2015-04-13 07:32:29 WARNING  SEARCHQUEUE-BACKLOG-75978 :: [ThePirateBay] :: Unknown exception while loading URL https://thepiratebay.se/search/Family%20Guy%20S07/0/7/200: Traceback (most recent call last):
2015-04-13 07:32:14 INFO     SEARCHQUEUE-BACKLOG-75978 :: [ThePirateBay] :: Performing episode search for Family Guy
2015-04-13 07:32:12 INFO     SEARCHQUEUE-BACKLOG-75978 :: [IPTorrents] :: Performing episode search for Family Guy
2015-04-13 07:32:11 INFO     SEARCHQUEUE-BACKLOG-75978 :: [KickAssTorrents] :: Performing episode search for Family Guy
2015-04-13 07:32:11 INFO     SEARCHQUEUE-BACKLOG-75978 :: [FreshOnTV] :: Performing episode search for Family Guy
2015-04-13 07:32:11 INFO     SEARCHQUEUE-BACKLOG-75978 :: Building internal name cache for Family Guy
2015-04-13 07:32:11 INFO     SEARCHQUEUE-BACKLOG-75978 :: No scene exceptions update needed
2015-04-13 07:32:11 INFO     SEARCHQUEUE-BACKLOG-75978 :: Beginning backlog search for: [Family Guy]
2015-04-13 07:32:10 INFO     SEARCHQUEUE-BACKLOG-81251 :: No needed episodes found during backlog search for: [Pixar Shorts]
AA
AAKeyError: 522
AA    resp.status_code) + ': ' + clients.http_error_code[resp.status_code], logger.DEBUG)
AA  File "/home/disk20/*********/sickrage/sickbeard/helpers.py", line 1286, in getURL
2015-04-13 07:32:10 WARNING  SEARCHQUEUE-BACKLOG-81251 :: [ThePirateBay] :: Unknown exception while loading URL https://thepiratebay.se/search/Pixar%20Shorts%20Season%201%20-Ep%2A/0/7/200: Traceback (most recent call last):
AA
AAKeyError: 522
AA    resp.status_code) + ': ' + clients.http_error_code[resp.status_code], logger.DEBUG)
AA  File "/home/disk20/*********/sickrage/sickbeard/helpers.py", line 1286, in getURL
2015-04-13 07:31:54 WARNING  SEARCHQUEUE-BACKLOG-81251 :: [ThePirateBay] :: Unknown exception while loading URL https://thepiratebay.se/search/Pixar%20Shorts%20Season%201%20-Ep%2A/0/7/200: Traceback (most recent call last):
AA
AAKeyError: 522
AA    resp.status_code) + ': ' + clients.http_error_code[resp.status_code], logger.DEBUG)
AA  File "/home/disk20/*********/sickrage/sickbeard/helpers.py", line 1286, in getURL
2015-04-13 07:31:39 WARNING  SEARCHQUEUE-BACKLOG-81251 :: [ThePirateBay] :: Unknown exception while loading URL https://thepiratebay.se/search/Pixar%20Shorts%20S01/0/7/200: Traceback (most recent call last):
2015-04-13 07:31:24 INFO     SEARCHQUEUE-BACKLOG-81251 :: [ThePirateBay] :: Performing episode search for Pixar Shorts
2015-04-13 07:31:17 INFO     SEARCHQUEUE-BACKLOG-81251 :: [IPTorrents] :: Performing episode search for Pixar Shorts
2015-04-13 07:31:17 INFO     SEARCHQUEUE-BACKLOG-81251 :: [KickAssTorrents] :: Performing episode search for Pixar Shorts
2015-04-13 07:31:17 INFO     SEARCHQUEUE-BACKLOG-81251 :: [FreshOnTV] :: Performing episode search for Pixar Shorts
2015-04-13 07:31:17 INFO     SEARCHQUEUE-BACKLOG-81251 :: Building internal name cache for Pixar Shorts
2015-04-13 07:31:17 INFO     SEARCHQUEUE-BACKLOG-81251 :: No scene exceptions update needed
2015-04-13 07:31:17 INFO     SEARCHQUEUE-BACKLOG-81251 :: Beginning backlog search for: [Pixar Shorts]
2015-04-13 07:31:15 INFO     SEARCHQUEUE-BACKLOG-252747 :: No needed episodes found during backlog search for: [Tyler Perry's For Better or Worse]
AA
AAKeyError: 522
AA    resp.status_code) + ': ' + clients.http_error_code[resp.status_code], logger.DEBUG)
AA  File "/home/disk20/*********/sickrage/sickbeard/helpers.py", line 1286, in getURL
2015-04-13 07:31:15 WARNING  SEARCHQUEUE-BACKLOG-252747 :: [ThePirateBay] :: Unknown exception while loading URL https://thepiratebay.se/search/Tyler.Perrys.For.Better.or.Worse%20S05E03%7C5x03%20/0/7/200: Traceback (most recent call last):
2015-04-13 07:30:59 INFO     SEARCHQUEUE-BACKLOG-252747 :: [ThePirateBay] :: Performing episode search for Tyler Perry's For Better or Worse
2015-04-13 07:30:59 INFO     SEARCHQUEUE-BACKLOG-252747 :: [IPTorrents] :: Performing episode search for Tyler Perry's For Better or Worse
2015-04-13 07:30:59 INFO     SEARCHQUEUE-BACKLOG-252747 :: [KickAssTorrents] :: Performing episode search for Tyler Perry's For Better or Worse
2015-04-13 07:30:59 INFO     SEARCHQUEUE-BACKLOG-252747 :: [FreshOnTV] :: Performing episode search for Tyler Perry's For Better or Worse
2015-04-13 07:30:59 INFO     SEARCHQUEUE-BACKLOG-252747 :: Building internal name cache for Tyler Perry's For Better or Worse
2015-04-13 07:30:59 INFO     SEARCHQUEUE-BACKLOG-252747 :: No scene exceptions update needed
2015-04-13 07:30:59 INFO     SEARCHQUEUE-BACKLOG-252747 :: Beginning backlog search for: [Tyler Perry's For Better or Worse]
2015-04-13 07:30:58 INFO     SEARCHQUEUE-BACKLOG-252747 :: No needed episodes found during backlog search for: [Tyler Perry's For Better or Worse]
AA
AAKeyError: 522
AA    resp.status_code) + ': ' + clients.http_error_code[resp.status_code], logger.DEBUG)
AA  File "/home/disk20/*********/sickrage/sickbeard/helpers.py", line 1286, in getURL
2015-04-13 07:30:58 WARNING  SEARCHQUEUE-BACKLOG-252747 :: [ThePirateBay] :: Unknown exception while loading URL https://thepiratebay.se/search/Tyler%20Perry%27s%20For%20Better%20or%20Worse%20Season%204%20-Ep%2A/0/7/200: Traceback (most recent call last):
AA
AAKeyError: 522
AA    resp.status_code) + ': ' + clients.http_error_code[resp.status_code], logger.DEBUG)
AA  File "/home/disk20/*********/sickrage/sickbeard/helpers.py", line 1286, in getURL
2015-04-13 07:30:43 WARNING  SEARCHQUEUE-BACKLOG-252747 :: [ThePirateBay] :: Unknown exception while loading URL https://thepiratebay.se/search/Tyler%20Perry%27s%20For%20Better%20or%20Worse%20Season%204%20-Ep%2A/0/7/200: Traceback (most recent call last):
AA
AAKeyError: 522
AA    resp.status_code) + ': ' + clients.http_error_code[resp.status_code], logger.DEBUG)
AA  File "/home/disk20/*********/sickrage/sickbeard/helpers.py", line 1286, in getURL
2015-04-13 07:30:28 WARNING  SEARCHQUEUE-BACKLOG-252747 :: [ThePirateBay] :: Unknown exception while loading URL https://thepiratebay.se/search/Tyler%20Perry%27s%20For%20Better%20or%20Worse%20S04/0/7/200: Traceback (most recent call last):
2015-04-13 07:30:13 INFO     SEARCHQUEUE-BACKLOG-252747 :: [ThePirateBay] :: Performing episode search for Tyler Perry's For Better or Worse
2015-04-13 07:30:08 INFO     SEARCHQUEUE-BACKLOG-252747 :: [IPTorrents] :: Performing episode search for Tyler Perry's For Better or Worse
2015-04-13 07:30:08 INFO     SEARCHQUEUE-BACKLOG-252747 :: [KickAssTorrents] :: Performing episode search for Tyler Perry's For Better or Worse
2015-04-13 07:30:08 INFO     SEARCHQUEUE-BACKLOG-252747 :: [FreshOnTV] :: Performing episode search for Tyler Perry's For Better or Worse
2015-04-13 07:30:08 INFO     SEARCHQUEUE-BACKLOG-252747 :: Building internal name cache for Tyler Perry's For Better or Worse
2015-04-13 07:30:08 INFO     SEARCHQUEUE-BACKLOG-252747 :: No scene exceptions update needed
2015-04-13 07:30:08 INFO     SEARCHQUEUE-BACKLOG-252747 :: Beginning backlog search for: [Tyler Perry's For Better or Worse]
2015-04-13 07:30:05 INFO     SEARCHQUEUE-BACKLOG-252747 :: No needed episodes found during backlog search for: [Tyler Perry's For Better or Worse]
AA
AAKeyError: 522
AA    resp.status_code) + ': ' + clients.http_error_code[resp.status_code], logger.DEBUG)
AA  File "/home/disk20/*********/sickrage/sickbeard/helpers.py", line 1286, in getURL
2015-04-13 07:30:05 WARNING  SEARCHQUEUE-BACKLOG-252747 :: [ThePirateBay] :: Unknown exception while loading URL https://thepiratebay.se/search/Tyler%20Perry%27s%20For%20Better%20or%20Worse%20Season%203%20-Ep%2A/0/7/200: Traceback (most recent call last):
AA
AAKeyError: 522
AA    resp.status_code) + ': ' + clients.http_error_code[resp.status_code], logger.DEBUG)
AA  File "/home/disk20/*********/sickrage/sickbeard/helpers.py", line 1286, in getURL
2015-04-13 07:29:50 WARNING  SEARCHQUEUE-BACKLOG-252747 :: [ThePirateBay] :: Unknown exception while loading URL https://thepiratebay.se/search/Tyler%20Perry%27s%20For%20Better%20or%20Worse%20Season%203%20-Ep%2A/0/7/200: Traceback (most recent call last):
AA
AAKeyError: 522
AA    resp.status_code) + ': ' + clients.http_error_code[resp.status_code], logger.DEBUG)
AA  File "/home/disk20/*********/sickrage/sickbeard/helpers.py", line 1286, in getURL
2015-04-13 07:29:35 WARNING  SEARCHQUEUE-BACKLOG-252747 :: [ThePirateBay] :: Unknown exception while loading URL https://thepiratebay.se/search/Tyler%20Perry%27s%20For%20Better%20or%20Worse%20S03/0/7/200: Traceback (most recent call last):
2015-04-13 07:29:20 INFO     SEARCHQUEUE-BACKLOG-252747 :: [ThePirateBay] :: Performing episode search for Tyler Perry's For Better or Worse
2015-04-13 07:29:11 INFO     SEARCHQUEUE-BACKLOG-252747 :: [IPTorrents] :: Performing episode search for Tyler Perry's For Better or Worse
2015-04-13 07:29:11 INFO     SEARCHQUEUE-BACKLOG-252747 :: [KickAssTorrents] :: Performing episode search for Tyler Perry's For Better or Worse
2015-04-13 07:29:11 INFO     SEARCHQUEUE-BACKLOG-252747 :: [FreshOnTV] :: Performing episode search for Tyler Perry's For Better or Worse
2015-04-13 07:29:11 INFO     SEARCHQUEUE-BACKLOG-252747 :: Building internal name cache for Tyler Perry's For Better or Worse
2015-04-13 07:29:11 INFO     SEARCHQUEUE-BACKLOG-252747 :: No scene exceptions update needed
2015-04-13 07:29:11 INFO     SEARCHQUEUE-BACKLOG-252747 :: Beginning backlog search for: [Tyler Perry's For Better or Worse]
2015-04-13 07:29:08 INFO     SEARCHQUEUE-BACKLOG-252747 :: No needed episodes found during backlog search for: [Tyler Perry's For Better or Worse]
AA
AAKeyError: 522
AA    resp.status_code) + ': ' + clients.http_error_code[resp.status_code], logger.DEBUG)
AA  File "/home/disk20/*********/sickrage/sickbeard/helpers.py", line 1286, in getURL
2015-04-13 07:29:08 WARNING  SEARCHQUEUE-BACKLOG-252747 :: [ThePirateBay] :: Unknown exception while loading URL https://thepiratebay.se/search/Tyler%20Perry%27s%20For%20Better%20or%20Worse%20Season%202%20-Ep%2A/0/7/200: Traceback (most recent call last):
AA
AAKeyError: 522
AA    resp.status_code) + ': ' + clients.http_error_code[resp.status_code], logger.DEBUG)
AA  File "/home/disk20/*********/sickrage/sickbeard/helpers.py", line 1286, in getURL
2015-04-13 07:28:53 WARNING  SEARCHQUEUE-BACKLOG-252747 :: [ThePirateBay] :: Unknown exception while loading URL https://thepiratebay.se/search/Tyler%20Perry%27s%20For%20Better%20or%20Worse%20Season%202%20-Ep%2A/0/7/200: Traceback (most recent call last):
AA
AAKeyError: 522
AA    resp.status_code) + ': ' + clients.http_error_code[resp.status_code], logger.DEBUG)
AA  File "/home/disk20/*********/sickrage/sickbeard/helpers.py", line 1286, in getURL
2015-04-13 07:28:38 WARNING  SEARCHQUEUE-BACKLOG-252747 :: [ThePirateBay] :: Unknown exception while loading URL https://thepiratebay.se/search/Tyler%20Perry%27s%20For%20Better%20or%20Worse%20S02/0/7/200: Traceback (most recent call last):
2015-04-13 07:28:23 INFO     SEARCHQUEUE-BACKLOG-252747 :: [ThePirateBay] :: Performing episode search for Tyler Perry's For Better or Worse
2015-04-13 07:28:11 INFO     SEARCHQUEUE-BACKLOG-252747 :: [IPTorrents] :: Performing episode search for Tyler Perry's For Better or Worse
2015-04-13 07:28:11 INFO     SEARCHQUEUE-BACKLOG-252747 :: [KickAssTorrents] :: Performing episode search for Tyler Perry's For Better or Worse
2015-04-13 07:28:10 INFO     SEARCHQUEUE-BACKLOG-252747 :: [FreshOnTV] :: Performing episode search for Tyler Perry's For Better or Worse
2015-04-13 07:28:10 INFO     SEARCHQUEUE-BACKLOG-252747 :: Building internal name cache for Tyler Perry's For Better or Worse
2015-04-13 07:28:10 INFO     SEARCHQUEUE-BACKLOG-252747 :: No scene exceptions update needed
2015-04-13 07:28:10 INFO     SEARCHQUEUE-BACKLOG-252747 :: Beginning backlog search for: [Tyler Perry's For Better or Worse]
2015-04-13 07:28:08 INFO     SEARCHQUEUE-BACKLOG-95731 :: Unable to run synodsmnotify: error 2 : No such file or directory
2015-04-13 07:28:08 INFO     SEARCHQUEUE-BACKLOG-95731 :: Executing command ['/usr/syno/bin/synodsmnotify', '@administrators', 'Started Download', u'Nurse Jackie - 7x01 - Clean - SD TV from KickAssTorrents']
2015-04-13 07:28:08 INFO     SEARCHQUEUE-BACKLOG-95731 :: Saved magnet link to /home/disk20/*********/torrents/downloads/Nurse.Jackie.S07E01.HDTV.x264-LOL.torrent
2015-04-13 07:28:08 INFO     SEARCHQUEUE-BACKLOG-95731 :: Downloading a result from KickAssTorrents at http://torcache.net/torrent/890289303149C967F54887E96BD8B1C6AD5E0B6E.torrent
2015-04-13 07:28:08 INFO     SEARCHQUEUE-BACKLOG-95731 :: Downloading Nurse.Jackie.S07E01.HDTV.x264-LOL. from KickAssTorrents
2015-04-13 07:28:08 INFO     SEARCHQUEUE-BACKLOG-95731 :: Quality of Nurse.Jackie.S07E01.HDTV.XviD-FUM is SD TV
2015-04-13 07:28:08 INFO     SEARCHQUEUE-BACKLOG-95731 :: Quality of Nurse.Jackie.S07E01.HDTV.x264-LOL. is SD TV
2015-04-13 07:28:08 INFO     SEARCHQUEUE-BACKLOG-95731 :: [KickAssTorrents] :: Performing episode search for Nurse Jackie
2015-04-13 07:28:07 INFO     SEARCHQUEUE-BACKLOG-95731 :: [FreshOnTV] :: Performing episode search for Nurse Jackie
2015-04-13 07:28:07 INFO     SEARCHQUEUE-BACKLOG-95731 :: Building internal name cache for Nurse Jackie
2015-04-13 07:28:07 INFO     SEARCHQUEUE-BACKLOG-95731 :: No scene exceptions update needed
2015-04-13 07:28:07 INFO     SEARCHQUEUE-BACKLOG-95731 :: Beginning backlog search for: [Nurse Jackie]
2015-04-13 07:28:07 INFO     SEARCHQUEUE-BACKLOG-79824 :: No needed episodes found during backlog search for: [Naruto Shippuden]
AA
AAKeyError: 522
AA    resp.status_code) + ': ' + clients.http_error_code[resp.status_code], logger.DEBUG)
AA  File "/home/disk20/*********/sickrage/sickbeard/helpers.py", line 1286, in getURL
2015-04-13 07:28:07 WARNING  SEARCHQUEUE-BACKLOG-79824 :: [ThePirateBay] :: Unknown exception while loading URL https://thepiratebay.se/search/Naruto.Shippuden%20S01E407%7C1x407%20/0/7/200: Traceback (most recent call last):
AA
AAKeyError: 522
AA    resp.status_code) + ': ' + clients.http_error_code[resp.status_code], logger.DEBUG)
AA  File "/home/disk20/*********/sickrage/sickbeard/helpers.py", line 1286, in getURL
2015-04-13 07:27:51 WARNING  SEARCHQUEUE-BACKLOG-79824 :: [ThePirateBay] :: Unknown exception while loading URL https://thepiratebay.se/search/NARUTO.Ji%20Feng%20Chuan%20%20S01E407%7C1x407%20/0/7/200: Traceback (most recent call last):
AA
AAKeyError: 522
AA    resp.status_code) + ': ' + clients.http_error_code[resp.status_code], logger.DEBUG)
AA  File "/home/disk20/*********/sickrage/sickbeard/helpers.py", line 1286, in getURL
2015-04-13 07:27:36 WARNING  SEARCHQUEUE-BACKLOG-79824 :: [ThePirateBay] :: Unknown exception while loading URL https://thepiratebay.se/search/Naruto.Shippuuden%20S01E407%7C1x407%20/0/7/200: Traceback (most recent call last):
2015-04-13 07:27:21 INFO     SEARCHQUEUE-BACKLOG-79824 :: [ThePirateBay] :: Performing episode search for Naruto Shippuden
2015-04-13 07:27:20 INFO     SEARCHQUEUE-BACKLOG-79824 :: [IPTorrents] :: Performing episode search for Naruto Shippuden
2015-04-13 07:27:20 INFO     SEARCHQUEUE-BACKLOG-79824 :: [KickAssTorrents] :: Performing episode search for Naruto Shippuden
2015-04-13 07:27:19 INFO     SEARCHQUEUE-BACKLOG-79824 :: [FreshOnTV] :: Performing episode search for Naruto Shippuden
2015-04-13 07:27:19 INFO     SEARCHQUEUE-BACKLOG-79824 :: Building internal name cache for Naruto Shippuden
2015-04-13 07:27:19 INFO     SEARCHQUEUE-BACKLOG-79824 :: No scene exceptions update needed
2015-04-13 07:27:19 INFO     SEARCHQUEUE-BACKLOG-79824 :: Beginning backlog search for: [Naruto Shippuden]
2015-04-13 07:27:18 INFO     SEARCHQUEUE-BACKLOG-281622 :: No needed episodes found during backlog search for: [The Last Man on Earth]
AA
AAKeyError: 522
AA    resp.status_code) + ': ' + clients.http_error_code[resp.status_code], logger.DEBUG)
AA  File "/home/disk20/*********/sickrage/sickbeard/helpers.py", line 1286, in getURL
2015-04-13 07:27:18 WARNING  SEARCHQUEUE-BACKLOG-281622 :: [ThePirateBay] :: Unknown exception while loading URL https://thepiratebay.se/search/The.Last.Man.on.Earth%20S01E02%7C1x02%20/0/7/200: Traceback (most recent call last):
2015-04-13 07:27:03 INFO     SEARCHQUEUE-BACKLOG-281622 :: [ThePirateBay] :: Performing episode search for The Last Man on Earth
2015-04-13 07:27:02 INFO     SEARCHQUEUE-BACKLOG-281622 :: [IPTorrents] :: Performing episode search for The Last Man on Earth
2015-04-13 07:27:02 INFO     SEARCHQUEUE-BACKLOG-281622 :: [KickAssTorrents] :: Performing episode search for The Last Man on Earth
2015-04-13 07:27:02 INFO     SEARCHQUEUE-BACKLOG-281622 :: [FreshOnTV] :: Performing episode search for The Last Man on Earth
2015-04-13 07:27:01 INFO     SEARCHQUEUE-BACKLOG-281622 :: Building internal name cache for The Last Man on Earth
2015-04-13 07:27:01 INFO     SEARCHQUEUE-BACKLOG-281622 :: No scene exceptions update needed
2015-04-13 07:27:01 INFO     SEARCHQUEUE-BACKLOG-281622 :: Beginning backlog search for: [The Last Man on Earth]
2015-04-13 07:26:59 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
AA
AAKeyError: 522
AA    resp.status_code) + ': ' + clients.http_error_code[resp.status_code], logger.DEBUG)
AA  File "/home/disk20/*********/sickrage/sickbeard/helpers.py", line 1286, in getURL
2015-04-13 07:26:59 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Unknown exception while loading URL https://thepiratebay.se/tv/latest/: Traceback (most recent call last):
2015-04-13 07:26:43 INFO     SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from The Bernie Mac Show
2015-04-13 07:26:43 INFO     SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from Partners (2014)
2015-04-13 07:26:43 INFO     SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from The Middle
2015-04-13 07:26:43 INFO     SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from The Walking Dead

**Comment by abeloin** [comment]
@javelin4effect Please use pastebin or gist for long log next time.

**Comment by fernandog** [comment]
@abeloin

**Comment by fernandog** [comment]
@TagForce is this ok the code above? It's a simple url code return. Ir returned 522 but the error raised

**Comment by TagForce** [comment]
@fernandog Yes, in python you can have line breaks in the code without issue if you keep to the following rules:

in parameters (anything between ()):
Simply continue on the next line like so:
```
avar = get_somevalue(parameter1,
                                    parameter2, parameter3)
```

On normal expressions:
Preferred way is to use () around the expression like so:
```
avar = (1 + bvar + 5
             + cvar + 7)
```
but you can optionally use a \ to denote line breaks like so:
```
avar = 1 + bvar + 5 \
           + cvar + 7
```

**Comment by fernandog** [comment]
@TagForce so any clue what's wrong in the code?

**Comment by TagForce** [comment]
@fernandog It should work... But you can add a \ at the end of the top line to make sure it understands it's a line break.

**Comment by fernandog** [comment]
@TagForce damm! thanks!

**Comment by TagForce** [comment]
@fernandog There's 2 more occurences of the same if clause... Change those 2 as well.

https://github.com/fernandog/SickRage/blob/develop/sickbeard/helpers.py#L1296
https://github.com/fernandog/SickRage/blob/develop/sickbeard/helpers.py#L1340

**Comment by fernandog** [comment]
@TagForce isn't better to add the code conversion here ?

try
    return_code = clients.http_error_code[resp.status_code]
except:
...

https://github.com/fernandog/SickRage/blob/develop/sickbeard/helpers.py#L1286

and in the logger.log we change to "return_code" ?

**Comment by TagForce** [comment]
@fernandog In this case it doesn't really matter where you do it. It uses a bit more memory doing it your way (assigning a value to a variable instead of directly referencing the value), but the end result is the same. I think encapsulating the logger code in a try...except will result in a bit cleaner code, because everything is in the same code-block.

You'll still have to do it 3 times, because the resp variable is set differently for each occurence.

**Comment by fernandog** [comment]
@TagForce so how to catch this exception in the main try:except block that already exists? or I need to add anothers (3 try:excepts blocks)?

**Comment by fernandog** [comment]
@TagForce 

created a DEF
what do you think?
https://github.com/fernandog/SickRage/commit/d8928fcdfdc544491acb82d5e2160a36b411dc7e

**Comment by TagForce** [comment]
@fernandog Won't work... There is no self.CodeDescription as CodeDescription is not defined as part of a class. You can add the def CodeDescription to the getURL function though, and you can call it simply by its name.

You can just add try...except clauses in a nested form, just like a nested if...
