### ISSUE TITLE
[APP SUBMITTED]: HTTPSConnectionPool(host='sceneaccess.eu', port=443): Read timed out. (read timeout=30)

### ISSUE THREAD

**Issue by chrisriteco** [SiCKRAGETV/sickrage-issues#1204]
### INFO
Python Version: **2.7.3 (default, Apr 12 2012, 20:25:04) [GCC 4.2.1]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
Link to Log: https://gist.github.com/12f74f923d6d8539c99f
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [SceneAccess] :: Failed parsing SceneAccess Traceback: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/providers/scc.py", line 225, in _doSearch
    data = self.getURL(self.url + "/" + link['href'])
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/providers/generic.py", line 126, in getURL
    if not self._doLogin():
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/providers/scc.py", line 95, in _doLogin
    response = self.session.post(self.urls['login'], data=login_params, headers=self.headers, timeout=30, verify=False)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/lib/requests/sessions.py", line 504, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/lib/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/lib/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/lib/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='sceneaccess.eu', port=443): Read timed out. (read timeout=30)

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
@chrisriteco sceneaccess didn't reply before the timeout, check your internet, if sceneaccess is up then retry
