### ISSUE TITLE
[APP SUBMITTED]: [Errno 8] nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by rodrigompaz** [SiCKRAGETV/sickrage-issues#1207]
### INFO
Python Version: **2.7.6 (default, Sep  9 2014, 15:04:36) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]**
Operating System: **Darwin-14.1.0-x86_64-i386-64bit**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@669046ea40a7a26a6121a1b07721f3c1c3cf5b10
Link to Log: https://gist.github.com/601e3d88bd416aa191db
### ERROR
```
Thread-51 :: Failed doing webui callback: Traceback (most recent call last):
  File "/Applications/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/Applications/SickRage/sickbeard/webserve.py", line 2140, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/Applications/SickRage/sickbeard/processTV.py", line 203, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/Applications/SickRage/sickbeard/processTV.py", line 504, in process_media
    result.result = processor.process()
  File "/Applications/SickRage/sickbeard/postProcessor.py", line 1037, in process
    cur_ep.downloadSubtitles(force=True)
  File "/Applications/SickRage/sickbeard/tv.py", line 1461, in downloadSubtitles
    notifiers.notify_subtitle_download(self.prettyName(), subtitleList)
  File "/Applications/SickRage/sickbeard/notifiers/__init__.py", line 101, in notify_subtitle_download
    n.notify_subtitle_download(ep_name, lang)
  File "/Applications/SickRage/sickbeard/notifiers/emailnotify.py", line 160, in notify_subtitle_download
    sickbeard.EMAIL_USER, sickbeard.EMAIL_PASSWORD, to, msg):
  File "/Applications/SickRage/sickbeard/notifiers/emailnotify.py", line 193, in _sendmail
    srv = smtplib.SMTP(host, int(port))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 311, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 286, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@rodrigompaz please send a screen shot of your email notifications settings

**Comment by rodrigompaz** [comment]
Hi @fernandog: 
My email notifications are not selected because of the error I saw in the logs.. 
I don't know why is still appearing .. 

![captura de pantalla 2015-04-13 a las 13 51 23](https://cloud.githubusercontent.com/assets/11908891/7115034/48639828-e1e4-11e4-99fd-4f12b7a10a35.png)

**Comment by fernandog** [comment]
@rodrigompaz but what were the settings ? please enabled and send a screen shot of the settings

**Comment by rodrigompaz** [comment]
![image](https://cloud.githubusercontent.com/assets/11908891/7115126/4e5df27c-e1e5-11e4-9477-930dbadbddfd.png)

![image](https://cloud.githubusercontent.com/assets/11908891/7115131/588a2bbc-e1e5-11e4-8f25-7f617fe2198f.png)

**Comment by fernandog** [comment]
@rodrigompaz where did you get the smtp host?

https://support.google.com/mail/troubleshooter/1668960

**Comment by rodrigompaz** [comment]
Thanks, @fernandog It's working now. 
I was trying to upload an issue about post-processing not working in my server...  and with the button of Report error it sent this one..  :-(

It seems that the problem with the email was stopping my post-processing process. Is it possible?

**Comment by fernandog** [comment]
@rodrigompaz maybe. don't know for sure

**Comment by rodrigompaz** [comment]
![image](https://cloud.githubusercontent.com/assets/11908891/7115493/67698228-e1e9-11e4-8d9d-d88efa95d901.png)

I'm sure..  ;-) 
Thanks

**Comment by abeloin** [comment]
@fernandog This need to be in a try...except block
```
File "/Applications/SickRage/sickbeard/notifiers/emailnotify.py", line 193, in _sendmail
    srv = smtplib.SMTP(host, int(port))
```

**Comment by fernandog** [comment]
@rodrigompaz please update and try to reproduce the error

**Comment by fernandog** [comment]
@rodrigompaz please reply

**Comment by rodrigompaz** [comment]
@fernandog I'm sorry. 
I'm moving to develop again and testing this morning, but it's taking a whole life to restart... 
![image](https://cloud.githubusercontent.com/assets/11908891/7214501/42653b4c-e5af-11e4-8ca4-52e23cc31c0c.png)
I'll let you know when it finishes. I have a few files waiting for the test..

**Comment by rodrigompaz** [comment]
Now it's OK, I used wrong email settings and the postprocess worked. Thank you. 

I have some messages in my error log and log. 

Error log: 

2015-04-18 10:06:03 Thread-49 :: Failed doing webui callback: Traceback (most recent call last):
  File "/Applications/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/Applications/SickRage/sickbeard/webserve.py", line 2144, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/Applications/SickRage/sickbeard/processTV.py", line 203, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/Applications/SickRage/sickbeard/processTV.py", line 504, in process_media
    result.result = processor.process()
  File "/Applications/SickRage/sickbeard/postProcessor.py", line 1028, in process
    cur_ep.downloadSubtitles(force=True)
  File "/Applications/SickRage/sickbeard/tv.py", line 1461, in downloadSubtitles
    notifiers.notify_subtitle_download(self.prettyName(), subtitleList)
  File "/Applications/SickRage/sickbeard/notifiers/__init__.py", line 101, in notify_subtitle_download
    n.notify_subtitle_download(ep_name, lang)
  File "/Applications/SickRage/sickbeard/notifiers/emailnotify.py", line 160, in notify_subtitle_download
    sickbeard.EMAIL_USER, sickbeard.EMAIL_PASSWORD, to, msg):
  File "/Applications/SickRage/sickbeard/notifiers/emailnotify.py", line 193, in _sendmail
    srv = smtplib.SMTP(host, int(port))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 311, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 286, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known

2015-04-18 10:06:02 Thread-49 :: Failed to detect KODI version for 'localhost:3000', check configuration and try again.
2015-04-18 10:04:08 Thread-71 :: git checkout -f develop returned : error: pathspec 'develop' did not match any file(s) known to git.
2015-04-18 09:48:06 POSTPROCESSER :: Failed to detect KODI version for 'localhost:3000', check configuration and try again.
2015-04-18 09:38:31 POSTPROCESSER :: Failed to detect KODI version for 'localhost:3000', check configuration and try again.
2015-04-18 09:38:18 TRAKTROLLING :: Exception generated in thread TRAKTROLLING: error 404 Client Error: Not Found

Log file: 
2015-04-18 10:06:03 ERROR    Thread-49 :: Failed doing webui callback: Traceback (most recent call last):
2015-04-18 10:06:02 ERROR    Thread-49 :: Failed to detect KODI version for 'localhost:3000', check configuration and try again.
2015-04-18 10:06:02 WARNING  Thread-49 :: Warning: Couldn't contact KODI HTTP at http://localhost:3000/kodiCmds/kodiHttp/?command=Help error [Errno 61] Connection refused
2015-04-18 10:06:02 WARNING  Thread-49 :: Error while trying to retrieve KODI API version for localhost:3000: error [Errno 61] Connection refused
2015-04-18 10:06:02 INFO     Thread-49 :: Sending KODI notification to 'localhost:3000' - American Odyssey - 1x02 - Oscar Mike: Spanish; Castilian
2015-04-18 10:05:58 INFO     Thread-49 :: Folder name (Finished) appears to be a valid release name. Using it.
2015-04-18 10:05:58 INFO     Thread-49 :: Trying to clean any empty folders under /Users/rodrigom/Downloads/FrostWire/SERIES/American Odyssey
2015-04-18 10:05:57 INFO     Thread-49 :: Analyzing name u'American.Odyssey.S01E02.Os.mp4'
2015-04-18 10:05:57 INFO     Thread-49 :: Analyzing name None
2015-04-18 10:05:57 INFO     Thread-49 :: Processing /Users/rodrigom/Downloads/FrostWire/DESCARGASBRUTAS/Finished/American.Odyssey.S01E02.Os.mp4 (None)

I don't know if this can help you. 

I have Plesk Media Server, I don't know why is calling KODI ;-) but that's another issue I guess. 

Thanks.

**Comment by fernandog** [comment]
Open another please
