### ISSUE TITLE
cannot find 'sbLogin' 

### ISSUE THREAD

**Issue by Derping1** [SiCKRAGETV/sickrage-issues#121]
Branch  master) / 

Updating from:
Commit hash (a67957d4f0aa9786d233aedc928d0d6096daaa80)

Your operating system and python version  
Raspbian (RPI) - Python 2.7.3

What you did 
Update from the GUI. The error below appeared. Tried to update from console with sudo git remote update. Same happened. 

What happened
Sickrage cannot be accessed and shows that info. 

What you expected
Expected a normal update. From  (you're 179 commits behind) to actual update from today 17.12.2014. 

Extra info on comment below: 
HTTPS is enabled. User/password always remember by Firefox. Tried to manually enter it again as well. 

Error message: 

Traceback
```
Traceback (most recent call last):
File "/usr/local/sickbeard/tornado/web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback))
File "/usr/local/sickbeard/tornado/web.py", line 1479, in wrapper result = method(self, *args, **kwargs)
File "/usr/local/sickbeard/sickbeard/webserve.py", line 244, in get raise
File "/usr/local/sickbeard/sickbeard/webserve.py", line 237, in _dispatch
File "/usr/local/sickbeard/sickbeard/webserve.py", line 3365, in index super(Config, self).__init__(*args, **kwargs)
File "/usr/local/sickbeard/sickbeard/webserve.py", line 576, in _munge "%H%M%S") + 'Z\r\n'
File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1010, in __unicode__ return getattr(self, mainMethName)()
File "/var/sickbeard/cache/cheetah/cheetah__usr_local_sickbeard_gui_slick_interfaces_default_home_tmpl_1418840057_95_17538.py", line 102, in respond self._handleCheetahInclude(VFN(VFFSL(SL,"os.path",True),"join",False)(VFFSL(SL,"sickbeard.PROG_DIR",True), "gui/slick/interfaces/default/inc_top.tmpl"), trans=trans, includeFrom="file", raw=False)
File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1615, in _handleCheetahInclude self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
File "cheetah__usr_local_sickbeard_gui_slick_interfaces_default_inc_top_tmpl_1418839902_05_28622.py", line 476, in respond
NotFound: cannot find 'sbLogin' 
```

**Comment by Derping1** [comment]
You mean, manual update from the console? With git remote update? I'll try that, if that doesn't work, I will try a fresh install from scratch, will try to restore settings from the GUI Backup feature. 

But in the forums I ready at least 2 other people with the same error. I'll keep you guys up to date on this issue. Thanks.

**Comment by Derping1** [comment]
Update: Deleted everything and started new. Now it's fine on the last master commit. Restoring settings from backup didn't work, so I did it manually. Right now it's adding every show. 

Guess we could close this issue? 
Thanks!

**Comment by markheloking** [comment]
I meant just shutting down sickrage and copying (and overwriting) everything just by hand/explorer, but this works as well.
