### ISSUE TITLE
Post Processing fails if unable to notify

### ISSUE THREAD

**Issue by runjmc** [SiCKRAGETV/sickrage-issues#1235]
BRANCH: (master) / COMMIT: (281409d366b228a455879e02b2d55d3967db29e4) 
2.7.8 (default, Oct 20 2014, 15:05:19) [GCC 4.9.1]

I have plex notification setup with a server and client.  If my plex client goes to sleep and SR tries to send a notification it fails and Post Processing fails and in the scheduler Post Processing shows alive as false and Post Processing stops running.

**Comment by fernandog** [comment]
@abeloin same thing like the email notify. If notification fails PP dont run

**Comment by fernandog** [comment]
@TagForce can you confirm please?

**Comment by TagForce** [comment]
@runjmc Can you post a log of this happening?
I want to see the last entry of the post processing, as it looks like it should always cleanly exit the notification.

**Comment by fernandog** [comment]
@TagForce maybe the log in this issue may help
https://github.com/SiCKRAGETV/sickrage-issues/issues/1216

**Comment by TagForce** [comment]
@fernandog Nope, that error occurs elsewhere in the code.

**Comment by runjmc** [comment]
2015-04-14 06:39:28 DEBUG    POSTPROCESSER :: 'Traceback (most recent call last):\n  File "/home/john/SickRage/sickbeard/scheduler.py", line 97, in run\n    self.action.run(self.force)\n  File "/home/john/SickRage/sickbeard/autoPostProcesser.py", line 50, in run\n    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR)\n  File "/home/john/SickRage/sickbeard/processTV.py", line 203, in processDir\n    process_media(path, [video], nzbName, process_method, force, is_priority, result)\n  File "/home/john/SickRage/sickbeard/processTV.py", line 504, in process_media\n    result.result = processor.process()\n  File "/home/john/SickRage/sickbeard/postProcessor.py", line 1059, in process\n    notifiers.notify_download(ep_obj._format_pattern(\'%SN - %Sx%0E - %EN - %QN\'))\n  File "/home/john/SickRage/sickbeard/notifiers/__init__.py", line 96, in notify_download\n    n.notify_download(ep_name)\n  File "/home/john/SickRage/sickbeard/notifiers/plex.py", line 64, in notify_download\n    self._notify_pmc(ep_name, common.notifyStrings[common.NOTIFY_DOWNLOAD])\n  File "/home/john/SickRage/sickbeard/notifiers/plex.py", line 56, in _notify_pmc\n    force=True)\n  File "/home/john/SickRage/sickbeard/notifiers/****.py", line 131, in _notify_****\n    ****api = self._get_****_version(curHost, username, password)\n  File "/home/john/SickRage/sickbeard/notifiers/****.py", line 88, in _get_****_version\n    request = self._send_to_****(testCommand, host, username, password)\n  File "/home/john/SickRage/sickbeard/notifiers/****.py", line 243, in _send_to_****\n    response = urllib2.urlopen(req)\n  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen\n    return _opener.open(url, data, timeout)\n  File "/usr/lib/python2.7/urllib2.py", line 404, in open\n    response = self._open(req, data)\n  File "/usr/lib/python2.7/urllib2.py", line 422, in _open\n    \'_open\', req)\n  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain\n    result = func(*args)\n  File "/usr/lib/python2.7/urllib2.py", line 1199, in http_open\n    return self.do_open(httplib.HTTPConnection, req)\n  File "/usr/lib/python2.7/urllib2.py", line 1172, in do_open\n    r = h.getresponse(buffering=True)\n  File "/usr/lib/python2.7/httplib.py", line 1073, in getresponse\n    response.begin()\n  File "/usr/lib/python2.7/httplib.py", line 415, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python2.7/httplib.py", line 379, in _read_status\n    raise BadStatusLine(line)\nBadStatusLine: \'\'\n'
AABadStatusLine: ''
AA    raise BadStatusLine(line)
AA  File "/usr/lib/python2.7/httplib.py", line 379, in _read_status
AA    version, status, reason = self._read_status()
AA  File "/usr/lib/python2.7/httplib.py", line 415, in begin
AA    response.begin()
AA  File "/usr/lib/python2.7/httplib.py", line 1073, in getresponse
AA    r = h.getresponse(buffering=True)
AA  File "/usr/lib/python2.7/urllib2.py", line 1172, in do_open
AA    return self.do_open(httplib.HTTPConnection, req)
AA  File "/usr/lib/python2.7/urllib2.py", line 1199, in http_open
AA    result = func(*args)
AA  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
AA    '_open', req)
AA  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
AA    response = self._open(req, data)
AA  File "/usr/lib/python2.7/urllib2.py", line 404, in open
AA    return _opener.open(url, data, timeout)
AA  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
AA    response = urllib2.urlopen(req)
AA  File "/home/john/SickRage/sickbeard/notifiers/****.py", line 243, in _send_to_****
AA    request = self._send_to_****(testCommand, host, username, password)
AA  File "/home/john/SickRage/sickbeard/notifiers/****.py", line 88, in _get_****_version
AA    ****api = self._get_****_version(curHost, username, password)
AA  File "/home/john/SickRage/sickbeard/notifiers/****.py", line 131, in _notify_****
AA    force=True)
AA  File "/home/john/SickRage/sickbeard/notifiers/plex.py", line 56, in _notify_pmc
AA    self._notify_pmc(ep_name, common.notifyStrings[common.NOTIFY_DOWNLOAD])
AA  File "/home/john/SickRage/sickbeard/notifiers/plex.py", line 64, in notify_download
AA    n.notify_download(ep_name)
AA  File "/home/john/SickRage/sickbeard/notifiers/__init__.py", line 96, in notify_download
AA    notifiers.notify_download(ep_obj._format_pattern('%SN - %Sx%0E - %EN - %QN'))
AA  File "/home/john/SickRage/sickbeard/postProcessor.py", line 1059, in process
AA    result.result = processor.process()
AA  File "/home/john/SickRage/sickbeard/processTV.py", line 504, in process_media
AA    process_media(path, [video], nzbName, process_method, force, is_priority, result)
AA  File "/home/john/SickRage/sickbeard/processTV.py", line 203, in processDir
AA    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR)
AA  File "/home/john/SickRage/sickbeard/autoPostProcesser.py", line 50, in run
AA    self.action.run(self.force)
AA  File "/home/john/SickRage/sickbeard/scheduler.py", line 97, in run
AATraceback (most recent call last):
2015-04-14 06:39:28 ERROR    POSTPROCESSER :: Exception generated in thread POSTPROCESSER: ''
2015-04-14 06:39:28 DEBUG    POSTPROCESSER :: Contacting KODI via url: http://ip:3005/****Cmds/****Http/?command=Help
2015-04-14 06:39:28 DEBUG    POSTPROCESSER :: KODI encoded API command: command=Help
2015-04-14 06:39:28 WARNING  POSTPROCESSER :: Error while trying to retrieve KODI API version for 192.168.22.166:3005: 
2015-04-14 06:39:28 DEBUG    POSTPROCESSER :: Contacting KODI via url: http://ip:3005/jsonrpc
2015-04-14 06:39:28 DEBUG    POSTPROCESSER :: KODI JSON command: {"jsonrpc":"2.0","method":"JSONRPC.Version","id":1}
2015-04-14 06:39:28 INFO     POSTPROCESSER :: Sending KODI notification to 'ip:3005' - Elementary - 2x17 - Ears to You - SD TV

**Comment by TagForce** [comment]
Can you edit the following line (in kodi.py)
https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/notifiers/kodi.py#L243

to read:
```
try:
    response = urllib2.urlopen(req)
except:
    return False
```

Mind the indentation.

**Comment by fernandog** [comment]
@TagForce @abeloin why not change this line to catch all errors?

https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/notifiers/kodi.py#L250

        except Exception, e:
            logger.log(u"Warning: Couldn't contact KODI HTTP at " + ek.ss(url) + " " + repr(e),
                       logger.WARNING)
            return False

* ex(e) > repr(e)

**Comment by TagForce** [comment]
@fernandog Yeah, that should work too :)

**Comment by abeloin** [comment]
@fernandog Yes, you should use `except Exception as e` to make it work with python3(future proof)

Also we should consider changing all to those call using urlib2 to requests
