### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/dateutil/zoneinfo/zoneinfo-2015c.tmp'

### ISSUE THREAD

**Issue by neoatomic** [SiCKRAGETV/sickrage-issues#1241]
### INFO
Python Version: **2.7.9 (default, Mar 22 2015, 23:23:23) [GCC 4.6.4]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@83c176cfdc50b42812b7a813d6a16a5d438dd76c
No Log available with ERRORS: 
### ERROR
```
MAIN :: Unable to save the file: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

```
2015-04-14 14:55:09 INFO     FINDSUBTITLES :: Checking for subtitles
2015-04-14 14:55:09 DEBUG    BACKLOG :: Nothing needs to be downloaded for Ice Cold Gold, skipping
2015-04-14 14:55:09 INFO     BACKLOG :: Seeing if we need anything from Kitchen Nightmares (US)
2015-04-14 14:55:09 DEBUG    MAIN :: Internal name cache set to: {u'pawn stars': 111051, u'kitchen nightmares usa': 80552, u'outlander': 270408, u'penny dreadful': 265766, u'mountain men': 259203, u'better call saul': 273181, u'once upon a time': 248835, u'die drei vom pfandhaus': 111051, u'vikings': 260449, u'black sails': 262407, u'marco polo 2014': 266091, u'game of thrones': 121361, u'kitchen nightmares us': 80552, u'ax men': 81578, u'the walking dead': 153021, u'wolf hall': 281977, u'atlantis': 248596, u'hotel hell': 257609, u'storage wars': 207621, u'cops': 74709, u'deadliest catch': 78957, u'ice cold gold': 268619, u'the blacklist': 266189, u'vincis demons': 259669, u'turn washingtons spies': 272135, u'the first 48': 81275, u'once upon a time 2011': 248835, u'davincis demons': 259669, u'da vincis demons': 259669, u'atlantis 2013': 248596, u'south park': 75897, u'the strain': 276564, u'true detective': 270633}
2015-04-14 14:55:09 DEBUG    BACKLOG :: Nothing needs to be downloaded for Kitchen Nightmares (US), skipping
2015-04-14 14:55:09 INFO     BACKLOG :: Seeing if we need anything from TURN: Washingtonâ€™s Spies
2015-04-14 14:55:09 DEBUG    BACKLOG :: 272135: An object for episode 2x1 didn't exist in the cache, trying to create it
2015-04-14 14:55:09 DEBUG    BACKLOG :: 272135: Loading episode details from DB for episode 2x1
2015-04-14 14:55:09 DEBUG    BACKLOG :: 272135: An object for episode 2x2 didn't exist in the cache, trying to create it
2015-04-14 14:55:09 DEBUG    BACKLOG :: 272135: Loading episode details from DB for episode 2x2
2015-04-14 14:55:09 DEBUG    BACKLOG :: Nothing needs to be downloaded for TURN: Washingtonâ€™s Spies, skipping
2015-04-14 14:55:09 INFO     BACKLOG :: Seeing if we need anything from Mountain Men
2015-04-14 14:55:09 DEBUG    BACKLOG :: Nothing needs to be downloaded for Mountain Men, skipping
2015-04-14 14:55:09 INFO     BACKLOG :: Seeing if we need anything from Penny Dreadful
2015-04-14 14:55:09 DEBUG    BACKLOG :: Nothing needs to be downloaded for Penny Dreadful, skipping
2015-04-14 14:55:09 INFO     BACKLOG :: Seeing if we need anything from True Detective
2015-04-14 14:55:10 DEBUG    BACKLOG :: Nothing needs to be downloaded for True Detective, skipping
2015-04-14 14:55:10 INFO     BACKLOG :: Seeing if we need anything from Cops
2015-04-14 14:55:10 DEBUG    BACKLOG :: Nothing needs to be downloaded for Cops, skipping
2015-04-14 14:55:10 INFO     BACKLOG :: Seeing if we need anything from The First 48
2015-04-14 14:55:10 DEBUG    BACKLOG :: Nothing needs to be downloaded for The First 48, skipping
2015-04-14 14:55:10 INFO     BACKLOG :: Seeing if we need anything from The Strain
2015-04-14 14:55:10 DEBUG    BACKLOG :: Nothing needs to be downloaded for The Strain, skipping
2015-04-14 14:55:10 INFO     BACKLOG :: Seeing if we need anything from The Blacklist
2015-04-14 14:55:10 DEBUG    BACKLOG :: Nothing needs to be downloaded for The Blacklist, skipping
2015-04-14 14:55:10 INFO     BACKLOG :: Seeing if we need anything from The Walking Dead
2015-04-14 14:55:10 DEBUG    BACKLOG :: Nothing needs to be downloaded for The Walking Dead, skipping
2015-04-14 14:55:10 INFO     BACKLOG :: Seeing if we need anything from Atlantis
2015-04-14 14:55:10 DEBUG    FINDSUBTITLES :: Episode file does not exist, cannot download subtitles for episode 8x17 of show Ax Men
2015-04-14 14:55:10 DEBUG    DAILYSEARCHER :: Setting permissions for /volume1/@appstore/sickbeard-custom/var/SickBeard/lib/dateutil/zoneinfo/zoneinfo-2015c.tmp to 644 as parent directory has 755
2015-04-14 14:55:10 INFO     DAILYSEARCHER :: Updating timezone info with new one: zoneinfo-2015c.tar.gz
2015-04-14 14:55:10 DEBUG    BACKLOG :: Nothing needs to be downloaded for Atlantis, skipping
2015-04-14 14:55:10 INFO     BACKLOG :: Seeing if we need anything from Ax Men
2015-04-14 14:55:10 DEBUG    BACKLOG :: Nothing needs to be downloaded for Ax Men, skipping
2015-04-14 14:55:10 INFO     BACKLOG :: Seeing if we need anything from Outlander
2015-04-14 14:55:10 DEBUG    BACKLOG :: Nothing needs to be downloaded for Outlander, skipping
2015-04-14 14:55:10 INFO     BACKLOG :: Seeing if we need anything from Better Call Saul
2015-04-14 14:55:10 DEBUG    BACKLOG :: Nothing needs to be downloaded for Better Call Saul, skipping
2015-04-14 14:55:10 INFO     BACKLOG :: Seeing if we need anything from Once Upon A Time
2015-04-14 14:55:10 DEBUG    BACKLOG :: Nothing needs to be downloaded for Once Upon A Time, skipping
2015-04-14 14:55:10 INFO     BACKLOG :: Seeing if we need anything from Marco Polo (2014)
2015-04-14 14:55:10 DEBUG    BACKLOG :: Nothing needs to be downloaded for Marco Polo (2014), skipping
2015-04-14 14:55:10 INFO     BACKLOG :: Seeing if we need anything from South Park
2015-04-14 14:55:10 DEBUG    BACKLOG :: Nothing needs to be downloaded for South Park, skipping
2015-04-14 14:55:10 ERROR    MAIN :: Unable to save the file: error 2 : No such file or directory
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1348, in download_file
    chmodAsParent(filename)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 564, in chmodAsParent
    childPathStat = ek.ek(os.stat, childPath)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/encodingKludge.py", line 58, in ek
    result = func(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
OSError: [Errno 2] No such file or directory: '/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/dateutil/zoneinfo/zoneinfo-2015c.tmp'
2015-04-14 14:55:10 INFO     BACKLOG :: Seeing if we need anything from Storage Wars
2015-04-14 14:55:10 DEBUG    BACKLOG :: Nothing needs to be downloaded for Storage Wars, skipping
2015-04-14 14:55:10 INFO     BACKLOG :: Seeing if we need anything from Pawn Stars
2015-04-14 14:55:10 DEBUG    BACKLOG :: 111051: An object for episode 2015x23 didn't exist in the cache, trying to create it
2015-04-14 14:55:10 DEBUG    BACKLOG :: 111051: Loading episode details from DB for episode 2015x23
2015-04-14 14:55:10 DEBUG    BACKLOG :: Nothing needs to be downloaded for Pawn Stars, skipping
2015-04-14 14:55:10 INFO     BACKLOG :: Seeing if we need anything from Wolf Hall
2015-04-14 14:55:10 DEBUG    BACKLOG :: Nothing needs to be downloaded for Wolf Hall, skipping
```

**Comment by fernandog** [comment]
@neoatomic restart helps?

**Comment by neoatomic** [comment]
@fernandog Yes, didn't get the error after a restart.
Submitted it as i hadn't seen this error before.
