### ISSUE TITLE
[APP SUBMITTED]: 'utf8' codec can't decode byte 0xa6 in position 10: invalid start byte

### ISSUE THREAD

**Issue by SweBel** [SiCKRAGETV/sickrage-issues#1242]
### INFO
Python Version: **2.7.3 (default, Mar 31 2015, 15:16:49) [GCC 4.9.2]**
Operating System: **Linux-3.18.10-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@281409d366b228a455879e02b2d55d3967db29e4
No Log available with ERRORS: 
### ERROR
```
Thread-14 :: Failed doing webui callback: Traceback (most recent call last):
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/webserve.py", line 3818, in index
    return t.respond()
  File "/storage/.kodi/userdata/addon_data/service.downloadmanager.SickPotatoHead/sbcache/cheetah/_storage__kodi_addons_service_downloadmanager_SickPotatoHead_resources_SickBeard_gui_slick_interfaces_default_config_search_tmpl.py", line 815, in respond
    if _v is not None: write(_filter(_v, rawExpr=u'$sickbeard.TORRENT_PASSWORD')) # from line 541, col 87.
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/webserve.py", line 95, in filter
    logger.log(u'Unable to decode using {0}, trying utf-8. Error is: {1}'.format(sickbeard.SYS_ENCODING, ex(e)),logger.DEBUG)
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/exceptions.py", line 49, in ex
    e_message = e_message + " : " + fixed_arg
  File "/home/stephan/projects/openelec-5.0/build.OpenELEC-RPi2.arm-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa6 in position 10: invalid start byte

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@SweBel please set locale to UTF-8

**Comment by SweBel** [comment]
Wow, thanks for the fast reply!

I am using openelec, when writing locale in the terminal it gives me:

OpenELEC:~ # locale
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=

OpenELEC:~ # locale -a
C
POSIX

How can I change the locale in openelec? I tried to google it but no success...

**Comment by fernandog** [comment]
@SweBel asked them in openelec.tv/forum/
