### ISSUE TITLE
[APP SUBMITTED]: None

### ISSUE THREAD

**Issue by lbjb** [SiCKRAGETV/sickrage-issues#1263]
### INFO
Python Version: **2.7.6 (default, Jan 29 2014, 07:56:46) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@281409d366b228a455879e02b2d55d3967db29e4
Link to Log: https://gist.github.com/c8d747c57604d1ca1341
### ERROR
```
Thread-92 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickbeard-amd64/share/sickbeard/Sick-Beard/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickbeard-amd64/share/sickbeard/Sick-Beard/sickbeard/webserve.py", line 1970, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "/usr/pbi/sickbeard-amd64/share/sickbeard/Sick-Beard/sickbeard/webserve.py", line 1936, in getEpisodes
    'overview': Overview.overviewStrings[showObj.getOverview(int(epObj.status or -1))]})
KeyError: None

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@lbjb please full update all your tv shows
