### ISSUE TITLE
[APP SUBMITTED]: Connection unexpectedly closed: timed out

### ISSUE THREAD

**Issue by lussierj** [SiCKRAGETV/sickrage-issues#1300]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@281409d366b228a455879e02b2d55d3967db29e4
No Log available with ERRORS: 
### ERROR
```
Thread-25 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 2144, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "C:\SickRage\sickbeard\processTV.py", line 203, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "C:\SickRage\sickbeard\processTV.py", line 504, in process_media
    result.result = processor.process()
  File "C:\SickRage\sickbeard\postProcessor.py", line 1059, in process
    notifiers.notify_download(ep_obj._format_pattern('%SN - %Sx%0E - %EN - %QN'))
  File "C:\SickRage\sickbeard\notifiers\__init__.py", line 96, in notify_download
    n.notify_download(ep_name)
  File "C:\SickRage\sickbeard\notifiers\emailnotify.py", line 122, in notify_download
    sickbeard.EMAIL_USER, sickbeard.EMAIL_PASSWORD, to, msg):
  File "C:\SickRage\sickbeard\notifiers\emailnotify.py", line 193, in _sendmail
    srv = smtplib.SMTP(host, int(port))
  File "C:\Python27\lib\smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "C:\Python27\lib\smtplib.py", line 312, in connect
    (code, msg) = self.getreply()
  File "C:\Python27\lib\smtplib.py", line 360, in getreply
    + str(e))
SMTPServerDisconnected: Connection unexpectedly closed: timed out

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Time out

**Comment by AubreyKloppers** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.9**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
Link to Log: https://gist.github.com/5aea37b826056224b238
### ERROR
```
Thread-47 :: Exception generated while sending e-mail: Connection unexpectedly closed: timed out
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by AubreyKloppers** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.9**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Exception generated while sending e-mail: Connection unexpectedly closed: timed out
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
