### ISSUE TITLE
Sickrage doesnt start

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#1306]
On the latest sr develop version i AM unable to start sr 
It just gives the following terror  supergonkas@supergonkas:~$ sudo service sickrage start
Starting SickBeard
Traceback (most recent call last):
  File "SickBeard.py", line 69, in <module>
    import sickbeard
  File "/home/supergonkas/SickRage/sickbeard/__init__.py", line 37, in <module>
    from sickbeard import providers, metadata, config, webserveInit
  File "/home/supergonkas/SickRage/sickbeard/config.py", line 28, in <module>    from sickbeard import naming
  File "/home/supergonkas/SickRage/sickbeard/naming.py", line 24, in <module>    from sickbeard import tv
  File "/home/supergonkas/SickRage/sickbeard/tv.py", line 1442
    if e.code = 503:
              ^
SyntaxError: invalid syntax

**Comment by fernandog** [comment]
@matigonkas sorry! please git pull

**Comment by matigonkas** [comment]
its now fixed
