### ISSUE TITLE
[APP SUBMITTED]: unsupported operand type(s) for -: 'str' and 'int'

### ISSUE THREAD

**Issue by chimchild** [SiCKRAGETV/sickrage-issues#1310]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@281409d366b228a455879e02b2d55d3967db29e4
No Log available with ERRORS: 
### ERROR
```
Thread-42 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1970, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "/opt/sickrage/sickbeard/webserve.py", line 1935, in getEpisodes
    'quality': self.getQualityClass(epObj),
  File "/opt/sickrage/sickbeard/webserve.py", line 1979, in getQualityClass
    ep_status, ep_quality = Quality.splitCompositeStatus(ep_obj.status)
  File "/opt/sickrage/sickbeard/common.py", line 260, in splitCompositeStatus
    return (status - x * 100, x)
TypeError: unsupported operand type(s) for -: 'str' and 'int'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1187
