### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/home/hd8/mraniki/media/TV Shows/Mad Men/Season 07/Mad Men - S07E09 - New Business.eng.srt'

### ISSUE THREAD

**Issue by mraniki** [SiCKRAGETV/sickrage-issues#1319]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-45-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@281409d366b228a455879e02b2d55d3967db29e4
Link to Log: https://gist.github.com/246a972ede47c917a119
### ERROR
```
Thread-43 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/hd8/mraniki/apps/sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/hd8/mraniki/apps/sickrage/sickbeard/webserve.py", line 1254, in displayShow
    return t.respond()
  File "/home/hd8/mraniki/.config/sickrage/cache/cheetah/_home_hd8_mraniki_apps_sickrage_gui_slick_interfaces_default_displayShow_tmpl.py", line 654, in respond
    _v = VFN(VFFSL(SL,"sickbeard.helpers",True),"pretty_filesize",False)(sickbeard.helpers.get_size(VFFSL(SL,"showLoc",True)[0])) # u'$sickbeard.helpers.pretty_filesize(sickbeard.helpers.get_size($showLoc[0]))' on line 246, col 46
  File "/home/hd8/mraniki/apps/sickrage/sickbeard/helpers.py", line 1412, in get_size
    total_size += ek.ek(os.path.getsize, fp)
  File "/home/hd8/mraniki/apps/sickrage/sickbeard/encodingKludge.py", line 58, in ek
    result = func(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
  File "/usr/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/home/hd8/mraniki/media/TV Shows/Mad Men/Season 07/Mad Men - S07E09 - New Business.eng.srt'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@mraniki what did you do to cause this?

**Comment by mraniki** [comment]
I clicked on the poster of the show to view the show details.
Results is i'm back to the main page with all the posters and error is generated in the log.

**Comment by fernandog** [comment]
Do you have the option enabled to see the file size?

**Comment by fernandog** [comment]
@mraniki do you still have that file in the directory?

**Comment by mraniki** [comment]
no it was not there and that was the reason why the error occurred. only a shortcut in the sick rage directory was there.

**Comment by fernandog** [comment]
@mraniki symlink or hardlink?

**Comment by fernandog** [comment]
@mraniki where the link points to? is it broken?

**Comment by mraniki** [comment]
yes hardlink that was broken.
