### ISSUE TITLE
Failed parsing T411 Traceback

### ISSUE THREAD

**Issue by Romano84** [SiCKRAGETV/sickrage-issues#1336]
Hello,

I recently wanted to download the new game of throne épisode in 720p vostfr from t411. In the website we have following result ;
* Game.of.Thrones.S05E02.720p.HDTV.x264-IMMERSE (N) -> should match
* Game.of.Thrones.S05E02.PROPER.VOSTFR.HDTV.x264-ASA... (N) -> should not match
* Game.of.Thrones.S05E02.720p.PROPER.VOSTFR.HDTV.x26... (N) (A) -> should match
* Game of Thrones S05e02 HDTV Natif 1080p (N)  -> should not match
* Game.of.Thrones.S05E02.PROPER.VOSTFR.HDTV.XviD-GOD... (A) -> should not match

So we potentially have two possibility of episode

Here the log search result : 
<pre>2015-04-20 14:24:14 DEBUG    SEARCHQUEUE-MANUAL-24493 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
2015-04-20 14:24:14 DEBUG    SEARCHQUEUE-MANUAL-24493 :: formatting pattern: %SN - %Sx%0E - %EN -> Game of Thrones - 5x02 - The House of Black and White
2015-04-20 14:24:14 INFO     SEARCHQUEUE-MANUAL-24493 :: Beginning manual search for: [Game of Thrones - 5x02 - The House of Black and White]
2015-04-20 14:24:14 INFO     SEARCHQUEUE-MANUAL-24493 :: No scene exceptions update needed
2015-04-20 14:24:14 INFO     SEARCHQUEUE-MANUAL-24493 :: Building internal name cache for Game of Thrones
2015-04-20 14:24:14 DEBUG    SEARCHQUEUE-MANUAL-24493 :: Internal name cache set to: {u'vikings': 260449, u'dragon ball kai 139 hd': 25859, u'game of thrones': 24493, u'dragon ball kai 137 hd': 25859, u'dragon ball kai 138 hd': 25859, u'greys anatomy': 73762, u'one piece': 81797, u'dragon ball kai 140 hd': 25859, u'breaking bad': 81189, u'better call saul': 273181, u'orange is the new black': 264586, u'downloads [kaerizaki fansub] one piece 686 [vostfr][hd': 8205}
2015-04-20 14:24:14 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: _doSearch started with ...{'RSS': ['']}
2015-04-20 14:24:14 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: T411 search page URL: https://api.t411.io/torrents/search/?cid=433&limit=100
2015-04-20 14:24:14 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: T411 Authentication token is still valid
2015-04-20 14:24:14 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: Error while searching T411, skipping: ValueError('No JSON object could be decoded',)
2015-04-20 14:24:14 INFO     SEARCHQUEUE-MANUAL-24493 :: [T411] :: Performing episode search for Game of Thrones
2015-04-20 14:24:14 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: _doSearch started with ...{'Episode': [u'Game.of.Thrones.S05E02.']}
2015-04-20 14:24:14 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: T411 search page URL: https://api.t411.io/torrents/search/Game.of.Thrones.S05E02.?cid=433&limit=100
2015-04-20 14:24:14 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: T411 Authentication token is still valid
2015-04-20 14:24:15 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: Found result: Game.of.Thrones.S05E02.HDTV.x264-Xclusive (https://api.t411.io/torrents/download/5296837)
2015-04-20 14:24:15 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: Found result: Game.of.Thrones.S05E02.FASTSUB.VOSTFR.HDTV.x264-Xclusive (https://api.t411.io/torrents/download/5297426)
2015-04-20 14:24:15 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: Found result: Game.of.Thrones.S05E02.PROPER.VOSTFR.HDTV.x264-ASAP (https://api.t411.io/torrents/download/5302008)
2015-04-20 14:24:15 ERROR    SEARCHQUEUE-MANUAL-24493 :: [T411] :: Failed parsing T411 Traceback: Traceback (most recent call last):
  File "/usr/local/sickrage/sickbeard/providers/t411.py", line 186, in _doSearch
    torrent_name = torrent['name']
TypeError: 'int' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/local/sickrage/sickbeard/providers/t411.py", line 186, in _doSearch
    torrent_name = torrent['name']
TypeError: 'int' object has no attribute '__getitem__'
2015-04-20 14:24:15 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: T411 search page URL: https://api.t411.io/torrents/search/Game.of.Thrones.S05E02.?cid=637&limit=100
2015-04-20 14:24:15 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: T411 Authentication token is still valid
2015-04-20 14:24:15 WARNING  SEARCHQUEUE-MANUAL-24493 :: [T411] :: The Data returned from T411 do not contains any torrent
2015-04-20 14:24:15 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: T411 search page URL: https://api.t411.io/torrents/search/Game.of.Thrones.S05E02.?cid=455&limit=100
2015-04-20 14:24:15 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: T411 Authentication token is still valid
2015-04-20 14:24:15 WARNING  SEARCHQUEUE-MANUAL-24493 :: [T411] :: The Data returned from T411 do not contains any torrent
2015-04-20 14:24:15 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: T411 search page URL: https://api.t411.io/torrents/search/Game.of.Thrones.S05E02.?cid=639&limit=100
2015-04-20 14:24:15 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: T411 Authentication token is still valid
2015-04-20 14:24:16 WARNING  SEARCHQUEUE-MANUAL-24493 :: [T411] :: The Data returned from T411 do not contains any torrent
2015-04-20 14:24:16 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: Using ALL regexes
2015-04-20 14:24:16 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: Using cached parse result for: Game.of.Thrones.S05E02.HDTV.x264-Xclusive
2015-04-20 14:24:16 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: Checking if found episode 5x2 is wanted at quality SD TV
2015-04-20 14:24:16 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: any,best = [4, 32, 128] [] and found 1
2015-04-20 14:24:16 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: Don't want this quality, ignoring found episode
2015-04-20 14:24:16 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: Ignoring result Game.of.Thrones.S05E02.HDTV.x264-Xclusive because we don't want an episode that is SD TV
2015-04-20 14:24:16 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: Using ALL regexes
2015-04-20 14:24:16 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: Using cached parse result for: Game.of.Thrones.S05E02.FASTSUB.VOSTFR.HDTV.x264-Xclusive
2015-04-20 14:24:16 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: Checking if found episode 5x2 is wanted at quality SD TV
2015-04-20 14:24:16 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: any,best = [4, 32, 128] [] and found 1
2015-04-20 14:24:16 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: Don't want this quality, ignoring found episode
2015-04-20 14:24:16 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: Ignoring result Game.of.Thrones.S05E02.FASTSUB.VOSTFR.HDTV.x264-Xclusive because we don't want an episode that is SD TV
2015-04-20 14:24:16 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: Using ALL regexes
2015-04-20 14:24:16 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: Using cached parse result for: Game.of.Thrones.S05E02.PROPER.VOSTFR.HDTV.x264-ASAP
2015-04-20 14:24:16 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: Checking if found episode 5x2 is wanted at quality SD TV
2015-04-20 14:24:16 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: any,best = [4, 32, 128] [] and found 1
2015-04-20 14:24:16 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: Don't want this quality, ignoring found episode
2015-04-20 14:24:16 DEBUG    SEARCHQUEUE-MANUAL-24493 :: [T411] :: Ignoring result Game.of.Thrones.S05E02.PROPER.VOSTFR.HDTV.x264-ASAP because we don't want an episode that is SD TV
2015-04-20 14:24:16 DEBUG    SEARCHQUEUE-MANUAL-24493 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
2015-04-20 14:24:16 DEBUG    SEARCHQUEUE-MANUAL-24493 :: formatting pattern: %SN - %Sx%0E - %EN -> Game of Thrones - 5x02 - The House of Black and White
2015-04-20 14:24:16 DEBUG    SEARCHQUEUE-MANUAL-24493 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
2015-04-20 14:24:16 DEBUG    SEARCHQUEUE-MANUAL-24493 :: formatting pattern: %SN - %Sx%0E - %EN -> Game of Thrones - 5x02 - The House of Black and White
2015-04-20 14:24:16 INFO     SEARCHQUEUE-MANUAL-24493 :: Unable to find a download for: [Game of Thrones - 5x02 - The House of Black and White]</pre>

**Comment by abeloin** [comment]
The api from t411 is returning some invalid data

**Comment by abeloin** [comment]
Fixed in develop, will be merged into master on Sunday

**Comment by Romano84** [comment]
great ! thanks :)

**Comment by fernandog** [comment]
@Romano84 please reopen if you still have this issue after tomorrow's update

**Comment by fernandog** [comment]
@Romano84 did you updated? Everything ok?

**Comment by Romano84** [comment]
@fernandog yes it seems all good now. Thanks :)
