### ISSUE TITLE
[APP SUBMITTED]: 'utf8' codec can't decode byte 0xc5 in position 7: invalid continuation byte

### ISSUE THREAD

**Issue by rafaelrosars** [SiCKRAGETV/sickrage-issues#1345]
### INFO
Python Version: **2.7.3 (default, Mar 31 2015, 15:16:49) [GCC 4.9.2]**
Operating System: **Linux-3.18.10-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@a5dd1d93107d03b406d2a14f99bd29bfffc7c0d5
No Log available with ERRORS: 
### ERROR
```
Thread-62 :: Failed doing webui callback: Traceback (most recent call last):
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/webserve.py", line 3884, in index
    return t.respond()
  File "/storage/.kodi/userdata/addon_data/service.downloadmanager.SickPotatoHead/sbcache/cheetah/_storage__kodi_addons_service_downloadmanager_SickPotatoHead_resources_SickBeard_gui_slick_interfaces_default_config_search_tmpl.py", line 815, in respond
    if _v is not None: write(_filter(_v, rawExpr=u'$sickbeard.TORRENT_PASSWORD')) # from line 541, col 87.
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/webserve.py", line 95, in filter
    logger.log(u'Unable to decode using {0}, trying utf-8. Error is: {1}'.format(sickbeard.SYS_ENCODING, ex(e)),logger.DEBUG)
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/exceptions.py", line 49, in ex
    e_message = e_message + " : " + fixed_arg
  File "/home/stephan/projects/openelec-5.0/build.OpenELEC-RPi2.arm-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc5 in position 7: invalid continuation byte

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rafaelrosars** [comment]
I get this error when i try to go Config/Search Settings

**Comment by abeloin** [comment]
Make sure your locale is UTF8

**Comment by rafaelrosars** [comment]
Where should I change the location? At Openelec or i have this option on sickrage?

Att,
Rafael Rosa.

**Comment by rafaelrosars** [comment]
Please, how can i fix?

Att,
Rafael Rosa.

**Comment by abeloin** [comment]
@rafaelrosars Check the following link it might help: http://unix.stackexchange.com/questions/74618/how-to-change-locale-environment-variable

Each distro have there on way off setting the locale, so should ask in the openelec forum.

**Comment by rafaelrosars** [comment]
I think my problem is becouse when i installed sickrage, iam at a wrong timezone. After i setup sickrage i change timezone at openelec. Can i solve this without have to reinstall sickrage?

Att,
Rafael Rosa.
