### ISSUE TITLE
[APP SUBMITTED]: global name 'traceback' is not defined

### ISSUE THREAD

**Issue by flaifel** [SiCKRAGETV/sickrage-issues#1352]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@975c0dd208c59cac8fd8a77a91da5d1dfc7235df
Link to Log: https://gist.github.com/0dcdf8cd981b8515bab6
### ERROR
```
Thread-92 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 2211, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "C:\SickRage\sickbeard\processTV.py", line 203, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "C:\SickRage\sickbeard\processTV.py", line 504, in process_media
    result.result = processor.process()
  File "C:\SickRage\sickbeard\postProcessor.py", line 1073, in process
    notifiers.notify_download(ep_obj._format_pattern('%SN - %Sx%0E - %EN - %QN'))
  File "C:\SickRage\sickbeard\notifiers\__init__.py", line 96, in notify_download
    n.notify_download(ep_name)
  File "C:\SickRage\sickbeard\notifiers\emailnotify.py", line 122, in notify_download
    sickbeard.EMAIL_USER, sickbeard.EMAIL_PASSWORD, to, msg):
  File "C:\SickRage\sickbeard\notifiers\emailnotify.py", line 197, in _sendmail
    logger.log(traceback.format_exc(), logger.DEBUG)
NameError: global name 'traceback' is not defined

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
merged in develop
