### ISSUE TITLE
[APP SUBMITTED]: CheckVersion instance has no attribute 'amActive'

### ISSUE THREAD

**Issue by konomimaster** [SiCKRAGETV/sickrage-issues#1355]
### INFO
Python Version: **2.7.3 (default, Mar 31 2015, 15:16:49) [GCC 4.9.2]**
Operating System: **Linux-3.18.10-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@975c0dd208c59cac8fd8a77a91da5d1dfc7235df
Link to Log: https://gist.github.com/6bd3f8e4dd2b2ab3223d
### ERROR
```
Thread-28 :: Failed doing webui callback: Traceback (most recent call last):
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/webserve.py", line 3725, in saveGeneral
    config.change_VERSION_NOTIFY(config.checkbox_to_value(version_notify))
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/config.py", line 214, in change_VERSION_NOTIFY
    sickbeard.versionCheckScheduler.forceRun()
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/scheduler.py", line 66, in forceRun
    if not self.action.amActive:
AttributeError: CheckVersion instance has no attribute 'amActive'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@abeloin @TagForce where should I add "self.amActive = True" ?

https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/scheduler.py#L71

**Comment by TagForce** [comment]
@fernandog https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/versionChecker.py#L53
self.amActive = False

You don't really need the value for this thread, as it doesn't matter if it's running twice.
This way it will be set to False upon instantiating.

**Comment by fernandog** [comment]
merged in develop
