### ISSUE TITLE
cannot find 'FILTER_ROW' while searching for 'sickbeard.FILTER_ROW'

### ISSUE THREAD

**Issue by danielb2** [SiCKRAGETV/sickrage-issues#1395]
I get the below error after `git co v4.0.17`. (FreeBSD). 

Do I need to do something to update the database?
```
Error

cannot find 'FILTER_ROW' while searching for 'sickbeard.FILTER_ROW'

Traceback

Traceback (most recent call last): 
File "/usr/local/sickrage/tornado/web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback)) 
File "/usr/local/sickrage/tornado/stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs) 
File "/usr/local/sickrage/tornado/concurrent.py", line 226, in lambda future: callback(future.result())) 
File "/usr/local/sickrage/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result() 
File "/usr/local/sickrage/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "/usr/local/sickrage/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "/usr/local/sickrage/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "/usr/local/sickrage/sickbeard/webserve.py", line 230, in async_call super(WebHandler, self).__init__(*args, **kwargs) 
File "/usr/local/sickrage/sickbeard/webserve.py", line 706, in index 
File "/usr/local/sickrage/cache/cheetah/cheetah__usr_local_sickrage_gui_slick_interfaces_default_home_tmpl_1429766088_01_22766.py", line 206, in respond if VFFSL(SL,"sickbeard.FILTER_ROW",True): # generated from line 106, col 4 
NotFound: cannot find 'FILTER_ROW' while searching for 'sickbeard.FILTER_ROW' 

Request Info

body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /home/
query_arguments: {}
_start_time: 1429766464.17
headers: {'Accept-Language': 'en-US,en;q=0.8,sv;q=0.6', 'Accept-Encoding': 'gzip, deflate, sdch', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36', 'Dnt': '1', 'Host': 'luffy:8081', 'Cookie': 'snatched_view2=list; soon_view2=thumbs; suggestions_charts_menu_selected=suggestions; plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0; _ga=GA1.1.773035649.1416026420', 'Cache-Control': 'max-age=0'}
host: luffy:8081
version: HTTP/1.1
arguments: {}
_finish_time: None
query: 
path: /home/
method: GET
remote_ip: 192.168.1.8

View Log(Errors)
```

**Comment by TagForce** [comment]
restart SR.

**Comment by danielb2** [comment]
I've done that multiple times. In fact, it was not running when I upgraded it.  Would you please re-open this ticket?

**Comment by fernandog** [comment]
@danielb2 you probably updated from command line, this is why you shouldn't

stop SR,
delete /cheetah folder inside /usr/local/sickrage/cache

**Comment by Thraxis** [comment]
@danielb2 FILTER_ROW is defined in sickrage/sickbeard/__init__.py there should be no possible way for it not to be found / defined by the template system.  Right around line 494

**Comment by danielb2** [comment]
thanks much. works now

**Comment by fernandog** [comment]
@danielb2 please update using UI, not command line

**Comment by danielb2** [comment]
I'll try next time. I've had some issues with that in the past. Thanks again

**Comment by fernandog** [comment]
updating from UI, you have auto-backup. You don't have that in command line

**Comment by danielb2** [comment]
I do a snapshot of the directory before I update every time ;)

**Comment by danielb2** [comment]
Well, I have been anyway
