### ISSUE TITLE
[APP SUBMITTED]: datetime.date(1897, 5, 8) is not JSON serializable

### ISSUE THREAD

**Issue by frucstuk** [SiCKRAGETV/sickrage-issues#1396]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-34-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@c1c519b720acfbbc5cec7c5a89c48053e9f1b980
Link to Log: https://gist.github.com/cc4c665c0809b0378e0c
### ERROR
```
Thread-46 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 2268, in searchIndexersForShowName
    return json.dumps({'results': final_results, 'langid': lang_id})
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.date(1897, 5, 8) is not JSON serializable

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@frucstuk what did you do to cause this error?
