### ISSUE TITLE
[APP SUBMITTED]: local variable 'showObj' referenced before assignment

### ISSUE THREAD

**Issue by firatuzman** [SiCKRAGETV/sickrage-issues#1397]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-45-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@c1c519b720acfbbc5cec7c5a89c48053e9f1b980
Link to Log: https://gist.github.com/feee5d950717969fca00
### ERROR
```
Thread-63 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1705, in updateKODI
    if showObj:
UnboundLocalError: local variable 'showObj' referenced before assignment

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by firatuzman** [comment]
Every time I update KODI manually from home page I get this error since the last updates
But the command is sent to KODI and KODI updates normally.
Hope this helps

**Comment by Thraxis** [comment]
I will have a PR done tonight to fix this

**Comment by TagForce** [comment]
@Thraxis how are you fixing it? just curious.

**Comment by Thraxis** [comment]
adding a showObj = none to the begining of the updateKodi function:

```python
    def updateKODI(self, show=None):        
        showName=None
        showObj=None
        
        if show:
            showObj = sickbeard.helpers.findCertainShow(sickbeard.showList, int(show))
            if showObj:
                showName=urllib.quote_plus(showObj.name.encode('utf-8'))
            
        # only send update to first host in the list -- workaround for kodi sql backend users
        if sickbeard.KODI_UPDATE_ONLYFIRST:
            # only send update to first host in the list -- workaround for kodi sql backend users
            host = sickbeard.KODI_HOST.split(",")[0].strip()
        else:
            host = sickbeard.KODI_HOST

        if notifiers.kodi_notifier.update_library(showName=showName):
            ui.notifications.message("Library update command sent to KODI host(s): " + host)
        else:
            ui.notifications.error("Unable to contact one or more KODI host(s): " + host)
            
        if showObj:
            return self.redirect('/home/displayShow?show=' + str(showObj.indexerid))
        else:
            return self.redirect('/home/')
```

**Comment by Thraxis** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1824

**Comment by fernandog** [comment]
@firatuzman merged in develop. wait until sunday to be on master
