### ISSUE TITLE
[APP SUBMITTED]: 'utf8' codec can't decode byte 0x8a in position 27005: invalid start byte

### ISSUE THREAD

**Issue by neives** [SiCKRAGETV/sickrage-issues#1436]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.7+-armv6l-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
No Log available with ERRORS: 
### ERROR
```
Thread-25 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 4134, in index
    t = PageTemplate(rh=self, file="config_providers.tmpl")
  File "/opt/sickrage/sickbeard/webserve.py", line 110, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1259, in __init__
    self._compile(source, file, compilerSettings=compilerSettings)
  File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1553, in _compile
    keepRefToGeneratedCode=True)
  File "/opt/sickrage/sickbeard/webserve.py", line 153, in compile
    return super(PageTemplate, self).compile(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 740, in compile
    settings=(compilerSettings or {}))
  File "/usr/lib/python2.7/dist-packages/Cheetah/Compiler.py", line 1579, in __init__
    source = unicode(source)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8a in position 27005: invalid start byte

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Set locale to utf-8

**Comment by neives** [comment]
i change raspbian locale to en_us utf-8 and doesn't solve..
