### ISSUE TITLE
[APP SUBMITTED]: 'utf8' codec can't decode byte 0xc5 in position 7: invalid continuation byte

### ISSUE THREAD

**Issue by rafaelrosars** [SiCKRAGETV/sickrage-issues#1438]
### INFO
Python Version: **2.7.3 (default, Mar 31 2015, 15:16:49) [GCC 4.9.2]**
Operating System: **Linux-3.18.10-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
No Log available with ERRORS: 
### ERROR
```
Thread-50 :: Failed doing webui callback: Traceback (most recent call last):
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/webserve.py", line 3631, in index
    return t.respond()
  File "/storage/.kodi/userdata/addon_data/service.downloadmanager.SickPotatoHead/sbcache/cheetah/_storage__kodi_addons_service_downloadmanager_SickPotatoHead_resources_SickBeard_gui_slick_interfaces_default_config_general_tmpl.py", line 850, in respond
    if _v is not None: write(_filter(_v, rawExpr=u'$sickbeard.WEB_PASSWORD')) # from line 453, col 78.
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/webserve.py", line 95, in filter
    logger.log(u'Unable to decode using {0}, trying utf-8. Error is: {1}'.format(sickbeard.SYS_ENCODING, ex(e)),logger.DEBUG)
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/exceptions.py", line 49, in ex
    e_message = e_message + " : " + fixed_arg
  File "/home/stephan/projects/openelec-5.0/build.OpenELEC-RPi2.arm-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc5 in position 7: invalid continuation byte

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rafaelrosars** [comment]
I get this same error when hit Settings/Search Settings, but now after update sick rage to latest version i get same error with Settings. Now i can`t change nothing at SR becouse i can`t go to settings page.

**Comment by fernandog** [comment]
Set locale to utf-8

**Comment by rafaelrosars** [comment]
Any ideia how? I can't get help with Openelec support
