### ISSUE TITLE
[APP SUBMITTED]: timed out

### ISSUE THREAD

**Issue by miropereira** [SiCKRAGETV/sickrage-issues#1444]
### INFO
Python Version: **2.7.8 (default, Dec 15 2014, 02:33:48) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: timed out
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by kylliox** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5770d33ef96e619af764b452ea35ad33e5755add
Link to Log: https://gist.github.com/514f53f1b0794222d045
### ERROR
```
SEARCHQUEUE-BACKLOG-259640 :: [FrenchTorrentDB] :: Error while searching FrenchTorrentDB, skipping: timed out
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-26-generic-i686-with-Ubuntu-15.04-vivid**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@5cd131dfa040c24db044cab51f9e7322f6ff23cc
Link to Log: https://gist.github.com/cfee45d379b0763aa8da
### ERROR
```
Thread-46 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 260, in async_call
    result = function(**kwargs)
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 2268, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/home/supergonkas/SickRage/sickbeard/processTV.py", line 204, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/home/supergonkas/SickRage/sickbeard/processTV.py", line 491, in process_media
    result.result = processor.process()
  File "/home/supergonkas/SickRage/sickbeard/postProcessor.py", line 1086, in process
    notifiers.notify_download(ep_obj._format_pattern('%SN - %Sx%0E - %EN - %QN'))
  File "/home/supergonkas/SickRage/sickbeard/notifiers/__init__.py", line 98, in notify_download
    n.notify_download(ep_name)
  File "/home/supergonkas/SickRage/sickbeard/notifiers/pushover.py", line 139, in notify_download
    self._notifyPushover(title, ep_name)
  File "/home/supergonkas/SickRage/sickbeard/notifiers/pushover.py", line 168, in _notifyPushover
    return self._sendPushover(message, title, userKey, apiKey)
  File "/home/supergonkas/SickRage/sickbeard/notifiers/pushover.py", line 92, in _sendPushover
    urllib.urlencode(args), {"Content-type": "application/x-www-form-urlencoded"})
  File "/usr/lib/python2.7/httplib.py", line 1048, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1088, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1044, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 888, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 850, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1261, in connect
    HTTPConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 831, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
timeout: timed out

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by danhunsaker** [comment]
### INFO
Python Version: **2.7.8 (default, Dec 15 2014, 02:33:48) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@9f8ae2924808eaf9f64bb37e09bc45a76b43969c
Link to Log: https://gist.github.com/0b40fcf51677874035b6
### ERROR
```
Thread-26 :: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/logger.py", line 305, in submit_errors
    if not report.raw_data['locked']:
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/GithubObject.py", line 93, in raw_data
    self._completeIfNeeded()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/GithubObject.py", line 232, in _completeIfNeeded
    self.__complete()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/GithubObject.py", line 237, in __complete
    self._url.value
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 212, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 251, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 275, in __requestRaw
    requestHeaders
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 995, in request
    self._send_request(method, url, body, headers)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 1029, in _send_request
    self.endheaders(body)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 991, in endheaders
    self._send_output(message_body)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 844, in _send_output
    self.send(msg)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 806, in send
    self.connect()
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 1194, in connect
    self.timeout, self.source_address)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/socket.py", line 571, in create_connection
    raise err
timeout: timed out

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by ausheikh** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
Thread-61 :: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\logger.py", line 249, in submit_errors
    gist = gh.get_user().create_gist(True, {"sickrage.log": InputFileContent(paste_data)})
  File "C:\SickRage\lib\github\AuthenticatedUser.py", line 473, in create_gist
    input=post_parameters
  File "C:\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickRage\lib\github\Requester.py", line 212, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "C:\SickRage\lib\github\Requester.py", line 251, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "C:\SickRage\lib\github\Requester.py", line 275, in __requestRaw
    requestHeaders
  File "C:\Python27\lib\httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 850, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 812, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 1208, in connect
    HTTPConnection.connect(self)
  File "C:\Python27\lib\httplib.py", line 793, in connect
    self.timeout, self.source_address)
  File "C:\Python27\lib\socket.py", line 571, in create_connection
    raise err
timeout: timed out

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
