### ISSUE TITLE
[APP SUBMITTED]: 'ascii' codec can't encode characters in position 48-49: ordinal not in range(128)

### ISSUE THREAD

**Issue by sickrager** [SiCKRAGETV/sickrage-issues#1448]
### INFO
Python Version: **2.7.8 (default, Dec 15 2014, 02:33:48) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/5e69592ffe86ef29a11d
### ERROR
```
Thread-84 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 2160, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 250, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 504, in process_media
    result.result = processor.process()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/postProcessor.py", line 1066, in process
    cur_ep.airdateModifyStamp()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 2597, in airdateModifyStamp
    filemtime = datetime.datetime.fromtimestamp(os.path.getmtime(self.location)).replace(tzinfo=tzlocal())
  File "/usr/pbi/sickrage-amd64/lib/python2.7/genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
UnicodeEncodeError: 'ascii' codec can't encode characters in position 48-49: ordinal not in range(128)

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Set your OS locale to uft-8
