### ISSUE TITLE
[APP SUBMITTED]: malformed start tag, at line 14, column 49

### ISSUE THREAD

**Issue by horrorman666** [SiCKRAGETV/sickrage-issues#1478]
### INFO
Python Version: **2.6.6 (r266:84292, Aug 12 2014, 07:57:07) [GCC 4.4.5]**
Operating System: **Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-debian-6.0.10**
Locale: UTF8
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/b3ca6462d44f95940876
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [BitSoup] :: Failed parsing BitSoup Traceback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/providers/bitsoup.py", line 176, in _doSearch
    with BS4Parser(data, "html.parser") as html:
  File "/opt/sickrage/sickbeard/bs4_parser.py", line 6, in __init__
    self.soup = BeautifulSoup(*args, **kwargs)
  File "/opt/sickrage/lib/bs4/__init__.py", line 196, in __init__
    self._feed()
  File "/opt/sickrage/lib/bs4/__init__.py", line 210, in _feed
    self.builder.feed(self.markup)
  File "/opt/sickrage/lib/bs4/builder/_htmlparser.py", line 164, in feed
    raise e
HTMLParseError: malformed start tag, at line 14, column 49

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@horrorman666 probaly they have changed their code
