### ISSUE TITLE
[APP SUBMITTED]: cannot import name _unicode

### ISSUE THREAD

**Issue by jdfalk** [SiCKRAGETV/sickrage-issues#1482]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-stretch-sid**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/5597ff939d8679ff9689
### ERROR
```
Thread-128 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1177, in displayShow
    t = PageTemplate(rh=self, file="displayShow.tmpl")
  File "/opt/sickrage/sickbeard/webserve.py", line 110, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1259, in __init__
    self._compile(source, file, compilerSettings=compilerSettings)
  File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1553, in _compile
    keepRefToGeneratedCode=True)
  File "/opt/sickrage/sickbeard/webserve.py", line 153, in compile
    return super(PageTemplate, self).compile(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 788, in compile
    exec(co, mod.__dict__)
  File "/home/sickrage/.sickrage/cache/cheetah/_opt_sickrage_gui_slick_interfaces_default_displayShow_tmpl.py", line 35, in <module>
    import ntpath
  File "/usr/lib/python2.7/ntpath.py", line 15, in <module>
    from genericpath import _unicode
ImportError: cannot import name _unicode

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by jackiass** [comment]
I think I have something of the same here.
I'm using Openelec 5.0.8 on a RPi2.
SickRage master branch
Python 2.7.3
The error: https://gist.github.com/jackiass/87b3502949c5cf2dbb7b

I get:
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd4 in position 7: invalid continuation byte
Whenever I try to access general settings it just goes to home and adds en error to the log.

**Comment by jdfalk** [comment]
I realized this was happening during an aptitude full upgrade and the
solution was to restart and pull the latest changes from master.

**Comment by jackiass** [comment]
OpenELEC does not have Git and pull is not so easy. I tried downloading the latest master and overwriting the sickrage folder but that did not change anything.
