### ISSUE TITLE
[APP SUBMITTED]: unsupported operand type(s) for -: 'str' and 'int'

### ISSUE THREAD

**Issue by Alexwijn** [SiCKRAGETV/sickrage-issues#1500]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.7+-armv6l-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
No Log available with ERRORS: 
### ERROR
```
Thread-76 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1973, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "/opt/sickrage/sickbeard/webserve.py", line 1932, in getEpisodes
    'quality': self.getQualityClass(searchThread.segment),
  File "/opt/sickrage/sickbeard/webserve.py", line 1986, in getQualityClass
    ep_status, ep_quality = Quality.splitCompositeStatus(ep_obj.status)
  File "/opt/sickrage/sickbeard/common.py", line 260, in splitCompositeStatus
    return (status - x * 100, x)
TypeError: unsupported operand type(s) for -: 'str' and 'int'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Alexwijn** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.7+-armv6l-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
No Log available with ERRORS: 
### ERROR
```
Thread-53 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1973, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "/opt/sickrage/sickbeard/webserve.py", line 1932, in getEpisodes
    'quality': self.getQualityClass(searchThread.segment),
  File "/opt/sickrage/sickbeard/webserve.py", line 1986, in getQualityClass
    ep_status, ep_quality = Quality.splitCompositeStatus(ep_obj.status)
  File "/opt/sickrage/sickbeard/common.py", line 260, in splitCompositeStatus
    return (status - x * 100, x)
TypeError: unsupported operand type(s) for -: 'str' and 'int'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1187
