### ISSUE TITLE
[APP SUBMITTED]: 401 Client Error: Unauthorized

### ISSUE THREAD

**Issue by abetancort** [SiCKRAGETV/sickrage-issues#1505]
### INFO
Python Version: **2.7.9 (default, Mar 23 2015, 00:07:04) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@5ef5a0b27e27cf937011408cb55329d1bd21ce9d
Link to Log: https://gist.github.com/d3cf3718982b0681a895
### ERROR
```
Thread-56 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1487, in editShow
    if not sickbeard.traktRollingScheduler.action.updateWantedList(showObj.indexerid):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/traktChecker.py", line 663, in updateWantedList
    if not self.refreshEpisodeWatched():
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/traktChecker.py", line 653, in refreshEpisodeWatched
    if not self._getEpisodeWatched():
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/traktChecker.py", line 641, in _getEpisodeWatched
    self.EpisodeWatched = self.trakt_api.traktRequest("sync/watched/shows")
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/trakt/trakt.py", line 60, in traktRequest
    self.validateAccount()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/trakt/trakt.py", line 44, in validateAccount
    raise traktAuthException(e)
traktAuthException: 401 Client Error: Unauthorized

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
check your trakt settings
