### ISSUE TITLE
FreeMobile SMS Notifier : unicode problem

### ISSUE THREAD

**Issue by djack42** [SiCKRAGETV/sickrage-issues#1513]
Another unicode problem
https://gist.github.com/djack42/2633843787d9bbb8e923#file-freemobile_sickrage-log

Configuration
SR Version:	BRANCH: (master) / COMMIT: (7af9a845c324bd0b0698da0ae85b68b54568f6e1) 
SR Locale:	('en_US', 'UTF-8')
SR Arguments:	['-q', '--daemon', '--nolaunch', '--datadir=/opt/sickbeard']
Python Version:	2.7.9 (default, Apr 29 2015, 19:33:17) [GCC 4.8.3 20140401 (prerelease)]

```
2015-05-04 20:54:41 DEBUG    SEARCHQUEUE-MANUAL-81797 :: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/search_queue.py", line 184, in run
    self.success = search.snatchEpisode(searchResult[0])
  File "/opt/sickbeard/sickbeard/search.py", line 166, in snatchEpisode
    notifiers.notify_snatch(curEpObj._format_pattern('%SN - %Sx%0E - %EN - %QN') + " from " + result.provider.name)
  File "/opt/sickbeard/sickbeard/notifiers/__init__.py", line 106, in notify_snatch
    n.notify_snatch(ep_name)
  File "/opt/sickbeard/sickbeard/notifiers/freemobile.py", line 88, in notify_snatch
    self._notifyFreeMobile(title, ep_name)
  File "/opt/sickbeard/sickbeard/notifiers/freemobile.py", line 122, in _notifyFreeMobile
    return self._sendFreeMobileSMS(title, message, id, apiKey)
  File "/opt/sickbeard/sickbeard/notifiers/freemobile.py", line 53, in _sendFreeMobileSMS
    msg_quoted = urllib2.quote(title + ": " + msg)
  File "/usr/lib/python2.7/urllib.py", line 1294, in quote
    return ''.join(map(quoter, s))
```

**Comment by fernandog** [comment]
@Heisenberg74 can you check this please?

**Comment by fernandog** [comment]
@miigotu to fix this:

msg_quoted = urllib2.quote(title + ": " + msg.decode('utf-8')) ?

**Comment by miigotu** [comment]
Yes, but is it the title or msg?

unicode still needs alot of work, we should only be converting on input on output, everywhere inside SR should stay unicode.

**Comment by fernandog** [comment]
decode or encode?

checked pushbullet
https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/notifiers/pushbullet.py#L94

**Comment by miigotu** [comment]
encode

**Comment by fernandog** [comment]
possible fix in develop
