### ISSUE TITLE
[APP SUBMITTED]: bad character range

### ISSUE THREAD

**Issue by jdfalk** [SiCKRAGETV/sickrage-issues#1526]
### INFO
Python Version: **2.7.9 (default, Apr 29 2015, 18:34:06) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-stretch-sid**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@1c1f80877b22531fe73aef61fad784b140fef605
Link to Log: https://gist.github.com/99b7709bb2a7d203bdc1
### ERROR
```
Thread-138 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 2160, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/opt/sickrage/sickbeard/processTV.py", line 203, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/opt/sickrage/sickbeard/processTV.py", line 504, in process_media
    result.result = processor.process()
  File "/opt/sickrage/sickbeard/postProcessor.py", line 1026, in process
    sickbeard.USE_SUBTITLES and ep_obj.show.subtitles)
  File "/opt/sickrage/sickbeard/postProcessor.py", line 348, in _move
    subtitles=subtitles)
  File "/opt/sickrage/sickbeard/postProcessor.py", line 279, in _combined_file_operation
    file_list = file_list + self.list_associated_files(file_path)
  File "/opt/sickrage/sickbeard/postProcessor.py", line 190, in list_associated_files
    checklist = ek.ek(glob.glob, ek.ek(os.path.join, ek.ek(os.path.dirname, file_path), '*')) # get a list of all the files in the folder
  File "/opt/sickrage/sickbeard/encodingKludge.py", line 73, in ek
    result = func(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
  File "/usr/lib/python2.7/glob.py", line 27, in glob
    return list(iglob(pathname))
  File "/usr/lib/python2.7/glob.py", line 63, in iglob
    for dirname in dirs:
  File "/usr/lib/python2.7/glob.py", line 64, in iglob
    for name in glob_in_dir(dirname, basename):
  File "/usr/lib/python2.7/glob.py", line 83, in glob1
    return fnmatch.filter(names, pattern)
  File "/usr/lib/python2.7/fnmatch.py", line 56, in filter
    _cache[pat] = re_pat = re.compile(res)
  File "/usr/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
error: bad character range

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@miigotu regex issue?

**Comment by jdfalk** [comment]
Yeah, I had to remove most of the -_/\ type characters which I assume confused re, in the folder and file name and then it post processed correctly.

**Comment by Doc1992** [comment]
I'm getting the same issue, my post processing hasn't been working for a few days now, any solution?

**Comment by Doc1992** [comment]
fixed it by removing this folder: [CBM] Attack on Titan 14-25+Extras+V2s (Dual Audio) [BDRip-1080p-8bit-FLAC]

**Comment by Shemes** [comment]
### INFO
Python Version: **2.7.3 (default, Apr 12 2012, 13:08:47) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@92bf581ba8a7d4f2f912db795ce571b6ad38c3c2
Link to Log: https://gist.github.com/484391923280a5e68f5a
### ERROR
```
Thread-137 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/webserve.py", line 2174, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/processTV.py", line 250, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/processTV.py", line 504, in process_media
    result.result = processor.process()
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/postProcessor.py", line 1023, in process
    sickbeard.USE_SUBTITLES and ep_obj.show.subtitles)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/postProcessor.py", line 369, in _copy
    subtitles=subtitles)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/postProcessor.py", line 281, in _combined_file_operation
    file_list = file_list + self.list_associated_files(file_path, subtitles_only=True)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/postProcessor.py", line 190, in list_associated_files
    checklist = ek.ek(glob.glob, ek.ek(os.path.join, ek.ek(os.path.dirname, file_path), '*')) # get a list of all the files in the folder
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/encodingKludge.py", line 73, in ek
    result = func(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
  File "/opt/lib/python2.7/glob.py", line 16, in glob
    return list(iglob(pathname))
  File "/opt/lib/python2.7/glob.py", line 41, in iglob
    for dirname in dirs:
  File "/opt/lib/python2.7/glob.py", line 42, in iglob
    for name in glob_in_dir(dirname, basename):
  File "/opt/lib/python2.7/glob.py", line 61, in glob1
    return fnmatch.filter(names, pattern)
  File "/opt/lib/python2.7/fnmatch.py", line 54, in filter
    _cache[pat] = re.compile(res)
  File "/opt/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/opt/lib/python2.7/re.py", line 242, in _compile
    raise error, v # invalid expression
error: bad character range

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Shemes** [comment]
### INFO
Python Version: **2.7.3 (default, Apr 12 2012, 13:08:47) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@92bf581ba8a7d4f2f912db795ce571b6ad38c3c2
Link to Log: https://gist.github.com/96dad2f3a0ec125197ca
### ERROR
```
Thread-167 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/webserve.py", line 2174, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/processTV.py", line 250, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/processTV.py", line 504, in process_media
    result.result = processor.process()
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/postProcessor.py", line 1023, in process
    sickbeard.USE_SUBTITLES and ep_obj.show.subtitles)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/postProcessor.py", line 369, in _copy
    subtitles=subtitles)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/postProcessor.py", line 281, in _combined_file_operation
    file_list = file_list + self.list_associated_files(file_path, subtitles_only=True)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/postProcessor.py", line 190, in list_associated_files
    checklist = ek.ek(glob.glob, ek.ek(os.path.join, ek.ek(os.path.dirname, file_path), '*')) # get a list of all the files in the folder
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/encodingKludge.py", line 73, in ek
    result = func(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
  File "/opt/lib/python2.7/glob.py", line 16, in glob
    return list(iglob(pathname))
  File "/opt/lib/python2.7/glob.py", line 41, in iglob
    for dirname in dirs:
  File "/opt/lib/python2.7/glob.py", line 42, in iglob
    for name in glob_in_dir(dirname, basename):
  File "/opt/lib/python2.7/glob.py", line 61, in glob1
    return fnmatch.filter(names, pattern)
  File "/opt/lib/python2.7/fnmatch.py", line 54, in filter
    _cache[pat] = re.compile(res)
  File "/opt/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/opt/lib/python2.7/re.py", line 242, in _compile
    raise error, v # invalid expression
error: bad character range

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by pokeimon** [comment]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@52a6c31cdf545c4e2fd22925a92a3d0824c429cf
Link to Log: https://gist.github.com/f5cf36eef5f1539db902
### ERROR
```
Thread-86 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 2174, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 203, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 498, in process_media
    result.result = processor.process()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/postProcessor.py", line 1042, in process
    sickbeard.USE_SUBTITLES and ep_obj.show.subtitles)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/postProcessor.py", line 411, in _moveAndSymlink
    action=_int_move_and_sym_link)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/postProcessor.py", line 279, in _combined_file_operation
    file_list = file_list + self.list_associated_files(file_path)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/postProcessor.py", line 190, in list_associated_files
    checklist = ek.ek(glob.glob, ek.ek(os.path.join, ek.ek(os.path.dirname, file_path), '*')) # get a list of all the files in the folder
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/encodingKludge.py", line 73, in ek
    result = func(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/glob.py", line 27, in glob
    return list(iglob(pathname))
  File "/usr/pbi/sickrage-amd64/lib/python2.7/glob.py", line 63, in iglob
    for dirname in dirs:
  File "/usr/pbi/sickrage-amd64/lib/python2.7/glob.py", line 64, in iglob
    for name in glob_in_dir(dirname, basename):
  File "/usr/pbi/sickrage-amd64/lib/python2.7/glob.py", line 83, in glob1
    return fnmatch.filter(names, pattern)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/fnmatch.py", line 54, in filter
    _cache[pat] = re.compile(res)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
error: bad character range

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by mbrackeva** [comment]
Exact same issue. This is new. I fixed it by removing [] characters from the source names. This used to work previously. Those characters aren't uncommon.
Especially annoying because the postprocessor crashes and won't run again. So you have to first notice it, and then restart Sickrage in order to get the postprocessor run again.

Python version 2.7.9
OS: Windows 8.1

**Comment by miigotu** [comment]
glob.glob having issues with * and items having [ and ]. I'll have to think about a good solution (might have to walk the dir)

**Comment by Alexwijn** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  8 2015, 00:52:26) [GCC 4.9.2]**
Operating System: **Linux-3.18.11+-armv6l-with-debian-7.8**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@ae2c0e8006bf0c8ec3d3379148a951847b2c5f39
Link to Log: https://gist.github.com/8c3ec6b1e013de29915a
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: bad character range
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
