### ISSUE TITLE
[APP SUBMITTED]: not a valid bencoded string

### ISSUE THREAD

**Issue by fifou3101** [SiCKRAGETV/sickrage-issues#1578]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@bf2baf309bd01683fdc06d57ece0b89d53b4a180
Link to Log: https://gist.github.com/9fecfe3a38e247cf8779
### ERROR
```
SEARCHQUEUE-BACKLOG-21934 :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fifou3101** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@bf2baf309bd01683fdc06d57ece0b89d53b4a180
Link to Log: https://gist.github.com/29bd58120d7a8d4fff5c
### ERROR
```
SEARCHQUEUE-BACKLOG-21934 :: Deluge: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
problem with the torrent file

**Comment by fifou3101** [comment]
The problem seems to be EZTV. If i take out EZTV as search provider, no more errors.

**Comment by lwshll1** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/b5ba99df08f013516b39
### ERROR
```
SEARCHQUEUE-BACKLOG-258744 :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@fifou3101 
Looks like the domain of EZTV was compromised.
https://github.com/SiCKRAGETV/sickrage-issues/issues/1640

**Comment by Nibeck1309** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.11+-armv6l-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/4e4f51273f8449c3344e
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Nibeck1309** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.11+-armv6l-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/5fc4e48359f99703e08d
### ERROR
```
SEARCHQUEUE-BACKLOG-114801 :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by sea3pea0** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 28 2014, 22:27:57) [GCC 4.7.3]**
Operating System: **Linux-3.15.2-hardened-whatbox-x86_64-Intel-R-_Xeon-R-_CPU_E5620_@_2.40GHz-with-gentoo-2.2**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by sea3pea0** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 28 2014, 22:27:57) [GCC 4.7.3]**
Operating System: **Linux-3.15.2-hardened-whatbox-x86_64-Intel-R-_Xeon-R-_CPU_E5620_@_2.40GHz-with-gentoo-2.2**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: rTorrent: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fifou3101** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Nibeck1309** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.11+-armv6l-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/03ef7b3edb6338cf3557
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by woodjl1650** [comment]
### INFO
Python Version: **2.7.8 (default, Dec 15 2014, 02:33:48) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@42b8d5a9c71c87fcde301967b6254ef08c3093ac
Link to Log: https://gist.github.com/0c778e93a84698051a77
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by krandor** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-36-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@42b8d5a9c71c87fcde301967b6254ef08c3093ac
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Morphello** [comment]
### INFO
Python Version: **2.7.9 (9c4588d731b7, Mar 23 2015, 20:00:36)[PyPy 2.5.1 with MSC v.1500 32 bit]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@ae2c0e8006bf0c8ec3d3379148a951847b2c5f39
Link to Log: https://gist.github.com/d5f5ce08476ef8b5dfa4
### ERROR
```
SEARCHQUEUE-MANUAL-255326 :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Morphello** [comment]
Posting from a previous comment, this error seems to be linked to using the proxy option for providers. When searching for an episode with KAT I get the following successful search:

```
2015-06-29 20:03:51 INFO     SHOWQUEUE-REFRESH :: Performing refresh on Defiance
AA
AA
AA
2015-06-29 20:03:40 INFO     SEARCHQUEUE-MANUAL-255326 :: Downloading Defiance.S02E04.HDTV.x264-2HD from KickAssTorrents
2015-06-29 20:03:39 INFO     SEARCHQUEUE-MANUAL-255326 :: Quality of Defiance.S02E04.HDTV.x264-2HD.[VTV].mp4 is SDTV
2015-06-29 20:03:38 INFO     SEARCHQUEUE-MANUAL-255326 :: Quality of Defiance.S02E04.HDTV.x264-2HD[ettv] is SDTV
2015-06-29 20:03:38 INFO     SEARCHQUEUE-MANUAL-255326 :: Quality of Defiance.S02E04.HDTV.x264-2HD is SDTV
2015-06-29 20:03:37 INFO     SEARCHQUEUE-MANUAL-255326 :: Quality of Defiance.S02E04.HDTV.x264-2HD[rartv] is SDTV
2015-06-29 20:03:36 INFO     SEARCHQUEUE-MANUAL-255326 :: Quality of Defiance.S02E04.HDTV.x264-2HD.[eztv] is SDTV
2015-06-29 20:03:35 INFO     SEARCHQUEUE-MANUAL-255326 :: Quality of Defiance.S02E04.HDTV.x264-2HD is SDTV
2015-06-29 20:03:35 INFO     SEARCHQUEUE-MANUAL-255326 :: Found result Defiance.S02E04.HDTV.x264-2HD.[VTV].mp4 at magnet:?xt=urn:btih:C04ECE208B6AD334AE00D870435E43BE35996BD2&dn=defiance+s02e04+hdtv+x264+2hd+vtv+mp4&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
2015-06-29 20:03:35 INFO     SEARCHQUEUE-MANUAL-255326 :: Found result Defiance.S02E04.HDTV.x264-2HD[ettv] at magnet:?xt=urn:btih:3CD6EA7A9675746CC746244B710ABB52A1060D56&dn=defiance+s02e04+hdtv+x264+2hd+ettv&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
2015-06-29 20:03:35 INFO     SEARCHQUEUE-MANUAL-255326 :: Found result Defiance.S02E04.HDTV.x264-2HD at magnet:?xt=urn:btih:83BF6D4D55D5710391FB4F59B4611FCE66089E62&dn=defiance+s02e04+hdtv+x264+2hd&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
2015-06-29 20:03:35 INFO     SEARCHQUEUE-MANUAL-255326 :: Found result Defiance.S02E04.HDTV.x264-2HD[rartv] at magnet:?xt=urn:btih:79186B68D61297FD198B2CF99D7C20FE444FE9EE&dn=defiance+s02e04+hdtv+x264+2hd+rartv&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
2015-06-29 20:03:35 INFO     SEARCHQUEUE-MANUAL-255326 :: Found result Defiance.S02E04.HDTV.x264-2HD.[eztv] at magnet:?xt=urn:btih:49316942423930350E47057CE4485225230452A2&dn=defiance+s02e04+hdtv+x264+2hd+eztv&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
2015-06-29 20:03:35 INFO     SEARCHQUEUE-MANUAL-255326 :: Found result Defiance.S02E04.HDTV.x264-2HD at magnet:?xt=urn:btih:38712D384F94E5F150A7ECFEDFD29A7FA41BDBE3&dn=defiance+s02e04+hdtv+x264+2hd&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
2015-06-29 20:03:35 INFO     SEARCHQUEUE-MANUAL-255326 :: Performing episode search for Defiance
2015-06-29 20:03:33 INFO     SEARCHQUEUE-MANUAL-255326 :: [KickAssTorrents] :: Performing season pack search for Defiance
2015-06-29 20:03:33 INFO     SEARCHQUEUE-MANUAL-255326 :: Building internal name cache for Defiance
2015-06-29 20:03:33 INFO     SEARCHQUEUE-MANUAL-255326 :: Beginning manual search for: [Defiance - 2x04 - Beasts of Burden]
```

However when I select this option http://i.imgur.com/bFS2zp1.png within the search provider settings on ANY provider, I get the following:

```
2015-06-29 20:07:38 INFO     POSTPROCESSER :: Processing completed
2015-06-29 20:07:38 INFO     POSTPROCESSER :: PostProcessing Path: C:\Torrents\Complete\TV
AA. Error: 'charmap' codec can't decode byte 0x8d in position 33: character maps to <undefined>
AARelease Group: 2HD
AASize: -1
AAName: Defiance.S02E04.HDTV.x264-2HD
AAQuality: SDTV
AAEpisode: [<sickbeard.tv.TVEpisode object at 0x055e6550>]
AAExtra Info:
AAUnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 33: character maps to <undefined>
AA    return codecs.charmap_decode(input,errors,decoding_table)
AA  File "C:\AtlasCore\Core\PyPy\lib-python\2.7\encodings\cp1252.py", line 15, in decode
AA    message = meThread + u" :: " + msg
AA  File "C:\AtlasCore\Programs\SickRage\sickbeard\logger.py", line 133, in log
AA    logger.log('Torrent bencoded data: {0}'.format(str(result.content)), logger.DEBUG)
AA  File "C:\AtlasCore\Programs\SickRage\sickbeard\clients\generic.py", line 160, in _get_torrent_hash
AA    result = self._get_torrent_hash(result)
AA  File "C:\AtlasCore\Programs\SickRage\sickbeard\clients\generic.py", line 186, in sendTORRENT
AATraceback (most recent call last):
2015-06-29 20:06:30 ERROR    SEARCHQUEUE-MANUAL-255326 :: uTorrent: Failed Sending Torrent
AABTFailure: not a valid bencoded string
AA    raise BTFailure("not a valid bencoded string")
AA  File "C:\AtlasCore\Programs\SickRage\lib\bencode\bencode.py", line 68, in bdecode
AA    torrent_bdecode = bdecode(result.content)
AA  File "C:\AtlasCore\Programs\SickRage\sickbeard\clients\generic.py", line 157, in _get_torrent_hash
AATraceback (most recent call last):
2015-06-29 20:06:30 ERROR    SEARCHQUEUE-MANUAL-255326 :: Unable to bdecode torrent
2015-06-29 20:06:29 INFO     SEARCHQUEUE-MANUAL-255326 :: Downloading Defiance.S02E04.HDTV.x264-2HD from KickAssTorrents
2015-06-29 20:06:29 INFO     SEARCHQUEUE-MANUAL-255326 :: Quality of Defiance.S02E04.HDTV.x264-2HD.[VTV].mp4 is SDTV
2015-06-29 20:06:28 INFO     SEARCHQUEUE-MANUAL-255326 :: Quality of Defiance.S02E04.HDTV.x264-2HD[ettv] is SDTV
2015-06-29 20:06:28 INFO     SEARCHQUEUE-MANUAL-255326 :: Quality of Defiance.S02E04.HDTV.x264-2HD is SDTV
2015-06-29 20:06:27 INFO     SEARCHQUEUE-MANUAL-255326 :: Quality of Defiance.S02E04.HDTV.x264-2HD[rartv] is SDTV
2015-06-29 20:06:27 INFO     SEARCHQUEUE-MANUAL-255326 :: Quality of Defiance.S02E04.HDTV.x264-2HD.[eztv] is SDTV
2015-06-29 20:06:26 INFO     SEARCHQUEUE-MANUAL-255326 :: Quality of Defiance.S02E04.HDTV.x264-2HD is SDTV
2015-06-29 20:06:26 INFO     SEARCHQUEUE-MANUAL-255326 :: [KickAssTorrents] :: Found result Defiance.S02E04.HDTV.x264-2HD.[VTV].mp4 at magnet:?xt=urn:btih:C04ECE208B6AD334AE00D870435E43BE35996BD2&dn=defiance+s02e04+hdtv+x264+2hd+vtv+mp4&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
2015-06-29 20:06:26 INFO     SEARCHQUEUE-MANUAL-255326 :: [KickAssTorrents] :: Found result Defiance.S02E04.HDTV.x264-2HD[ettv] at magnet:?xt=urn:btih:3CD6EA7A9675746CC746244B710ABB52A1060D56&dn=defiance+s02e04+hdtv+x264+2hd+ettv&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
2015-06-29 20:06:26 INFO     SEARCHQUEUE-MANUAL-255326 :: [KickAssTorrents] :: Found result Defiance.S02E04.HDTV.x264-2HD at magnet:?xt=urn:btih:83BF6D4D55D5710391FB4F59B4611FCE66089E62&dn=defiance+s02e04+hdtv+x264+2hd&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
2015-06-29 20:06:26 INFO     SEARCHQUEUE-MANUAL-255326 :: [KickAssTorrents] :: Found result Defiance.S02E04.HDTV.x264-2HD[rartv] at magnet:?xt=urn:btih:79186B68D61297FD198B2CF99D7C20FE444FE9EE&dn=defiance+s02e04+hdtv+x264+2hd+rartv&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
2015-06-29 20:06:26 INFO     SEARCHQUEUE-MANUAL-255326 :: [KickAssTorrents] :: Found result Defiance.S02E04.HDTV.x264-2HD.[eztv] at magnet:?xt=urn:btih:49316942423930350E47057CE4485225230452A2&dn=defiance+s02e04+hdtv+x264+2hd+eztv&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
2015-06-29 20:06:26 INFO     SEARCHQUEUE-MANUAL-255326 :: [KickAssTorrents] :: Found result Defiance.S02E04.HDTV.x264-2HD at magnet:?xt=urn:btih:38712D384F94E5F150A7ECFEDFD29A7FA41BDBE3&dn=defiance+s02e04+hdtv+x264+2hd&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
2015-06-29 20:06:26 INFO     SEARCHQUEUE-MANUAL-255326 :: [KickAssTorrents] :: Performing episode search for Defiance
2015-06-29 20:06:26 INFO     SEARCHQUEUE-MANUAL-255326 :: Building internal name cache for Defiance
2015-06-29 20:06:26 INFO     SEARCHQUEUE-MANUAL-255326 :: Beginning manual search for: [Defiance - 2x04 - Beasts of Burden]
```
It looks as if "Access provider via proxy" is currently broken. Tested with KAT and Piratebay, both producing the same error.

**Comment by fifou3101** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@ae2c0e8006bf0c8ec3d3379148a951847b2c5f39
Link to Log: https://gist.github.com/0faad54da654f45ea478
### ERROR
```
SEARCHQUEUE-MANUAL-74608 :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SATAN999** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@aa9c1bf1ca2bf3df9cd33fe4e798c8247dfe1881
Link to Log: https://gist.github.com/19fc17ca3f800e0993a0
### ERROR
```
SEARCHQUEUE-MANUAL-175001 :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by ziggyke** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.0.101.RNx86_64.3-x86_64-with-debian-7.8**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@aa9c1bf1ca2bf3df9cd33fe4e798c8247dfe1881
Link to Log: https://gist.github.com/63263f3b6b18c64fe670
### ERROR
```
SEARCHQUEUE-MANUAL-205281 :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fifou3101** [comment]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@aa9c1bf1ca2bf3df9cd33fe4e798c8247dfe1881
Link to Log: https://gist.github.com/763ba8c40cc1f0678119
### ERROR
```
SEARCHQUEUE-BACKLOG-274897 :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
torcache issue. already fixed. will be in master soon

**Comment by Morphello** [comment]
So just to confirm, it was a torcache issue causing proxies not to work? After the fix I'll be able to reactivate "Access provider via proxy"?

**Comment by fernandog** [comment]
Yes

**Comment by Morphello** [comment]
Fantastic. Great work!

**Comment by SATAN999** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@4a47a5cf7eff76f0d99a9c0f3b574027d1f56dd8
Link to Log: https://gist.github.com/d67c764719b25599fff5
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
