### ISSUE TITLE
[APP SUBMITTED]: 'utf8' codec can't decode byte 0xe9 in position 703: invalid continuation byte

### ISSUE THREAD

**Issue by aschnabl** [SiCKRAGETV/sickrage-issues#1592]
### INFO
Python Version: **2.7.3 (default, Mar 13 2015, 14:51:38) [GCC 4.9.2]**
Operating System: **Linux-3.18.9-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@
No Log available with ERRORS: 
### ERROR
```
Thread-76 :: Failed doing webui callback: Traceback (most recent call last):
  File "/storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/sickbeard/webserve.py", line 3006, in backlogOverview
    [curShow.indexerid])
  File "/storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/sickbeard/db.py", line 192, in select
    sqlResults = self.action(query, args, fetchall=True)
  File "/storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/sickbeard/db.py", line 170, in action
    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/sickbeard/db.py", line 86, in execute
    return self._execute(query, args).fetchall()
  File "/storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/sickbeard/db.py", line 235, in _unicode_text_factory
    return unicode(x, sickbeard.SYS_ENCODING)
  File "/home/stephan/projects/openelec-5.0/build.OpenELEC-RPi2.arm-5.0.6/Python-2.7.3/.install_pkg/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 703: invalid continuation byte

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@aschnabl set locale to UTF-8

**Comment by aschnabl** [comment]
Ok that sounds good, but how do i do that?

**Comment by fernandog** [comment]
https://sickrage.tv/forums/forum/help-support/general-support/12825-ensuring-your-locale-s-are-set-properly-to-avoid-unicode-issues
