### ISSUE TITLE
Cannot find episodes on BTN

### ISSUE THREAD

**Issue by shaikio** [SiCKRAGETV/sickrage-issues#1602]
I had to uninstall and reinstall Sickbeard because I was getting all sorts of get errors. The reinstall fixed my update issues, but now it seems to have broken finding episodes on BTN. It won't pull them automatically, and I can't get them to snatch manually either. I tried adding another search provider and it was able to find the episode I was looking for.

**Comment by shaikio** [comment]
Here are my most recent logs:

2015-05-14 10:33:56 INFO     SEARCHQUEUE-MANUAL-94571 :: Unable to find a download for: [Community - 6x10 - Basic RV Repair and Palmistry]
AA
AAAttributeError: '_socketobject' object has no attribute 'set_tlsext_host_name'
AA    cnx.set_tlsext_host_name(server_hostname)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 296, in ssl_wrap_socket
AA    ssl_version=resolved_ssl_version)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connection.py", line 238, in connect
AA    conn.connect()
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 740, in _validate_conn
AA    self._validate_conn(conn)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 326, in _make_request
AA    body=body, headers=headers)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 529, in urlopen
AA    timeout=timeout
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/adapters.py", line 370, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/cachecontrol/adapter.py", line 34, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 573, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 461, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 473, in get
AA    resp = session.get(url, timeout=timeout)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1294, in getURL
2015-05-14 10:33:56 WARNING  SEARCHQUEUE-MANUAL-94571 :: Unknown exception while loading URL https://broadcasthe.net/torrents.php?action=download&id=509445&authkey=d355631d4f79d66e079b60a05ab893a1&torrent_pass=eeydzojmpw30cld3kq432bcfmv77ulmj: Traceback (most recent call last):
AA
AAAttributeError: '_socketobject' object has no attribute 'set_tlsext_host_name'
AA    cnx.set_tlsext_host_name(server_hostname)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 296, in ssl_wrap_socket
AA    ssl_version=resolved_ssl_version)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connection.py", line 238, in connect
AA    conn.connect()
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 740, in _validate_conn
AA    self._validate_conn(conn)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 326, in _make_request
AA    body=body, headers=headers)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 529, in urlopen
AA    timeout=timeout
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/adapters.py", line 370, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/cachecontrol/adapter.py", line 34, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 573, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 461, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 473, in get
AA    resp = session.get(url, timeout=timeout)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1294, in getURL
2015-05-14 10:33:56 WARNING  SEARCHQUEUE-MANUAL-94571 :: Unknown exception while loading URL https://broadcasthe.net/torrents.php?action=download&id=508509&authkey=d355631d4f79d66e079b60a05ab893a1&torrent_pass=eeydzojmpw30cld3kq432bcfmv77ulmj: Traceback (most recent call last):
AA
AAAttributeError: '_socketobject' object has no attribute 'set_tlsext_host_name'
AA    cnx.set_tlsext_host_name(server_hostname)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 296, in ssl_wrap_socket
AA    ssl_version=resolved_ssl_version)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connection.py", line 238, in connect
AA    conn.connect()
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 740, in _validate_conn
AA    self._validate_conn(conn)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 326, in _make_request
AA    body=body, headers=headers)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 529, in urlopen
AA    timeout=timeout
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/adapters.py", line 370, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/cachecontrol/adapter.py", line 34, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 573, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 461, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 473, in get
AA    resp = session.get(url, timeout=timeout)
AA  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1294, in getURL
2015-05-14 10:33:56 WARNING  SEARCHQUEUE-MANUAL-94571 :: Unknown exception while loading URL https://broadcasthe.net/torrents.php?action=download&id=508633&authkey=d355631d4f79d66e079b60a05ab893a1&torrent_pass=eeydzojmpw30cld3kq432bcfmv77ulmj: Traceback (most recent call last):
2015-05-14 10:33:55 INFO     SEARCHQUEUE-MANUAL-94571 :: [BTN] :: Performing episode search for Community
2015-05-14 10:33:55 INFO     SEARCHQUEUE-MANUAL-94571 :: Building internal name cache for Community
2015-05-14 10:33:55 INFO     SEARCHQUEUE-MANUAL-94571 :: No scene exceptions update needed
AANone
2015-05-14 10:33:55 ERROR    SEARCHQUEUE-MANUAL-94571 :: Check scene exceptions update failed. Unable to get URL: https://raw.githubusercontent.com/SiCKRAGETV/sr_tvrage_scene_exceptions/master/exceptions.txt

**Comment by shaikio** [comment]
Here is some debug of me trying to grab an episode:

2015-05-14 12:18:26 INFO     SEARCHQUEUE-MANUAL-95011 :: Unable to find a download for: [Modern Family - 6x23 - Crying Out Loud]
2015-05-14 12:18:26 DEBUG    SEARCHQUEUE-MANUAL-95011 :: formatting pattern: %SN - %Sx%0E - %EN -> Modern Family - 6x23 - Crying Out Loud
2015-05-14 12:18:26 DEBUG    SEARCHQUEUE-MANUAL-95011 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
2015-05-14 12:18:26 DEBUG    SEARCHQUEUE-MANUAL-95011 :: formatting pattern: %SN - %Sx%0E - %EN -> Modern Family - 6x23 - Crying Out Loud
2015-05-14 12:18:26 DEBUG    SEARCHQUEUE-MANUAL-95011 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
2015-05-14 12:18:26 DEBUG    SEARCHQUEUE-MANUAL-95011 :: No result picked.
