### ISSUE TITLE
[APP SUBMITTED]: timestamp out of range for platform time_t

### ISSUE THREAD

**Issue by luxmoggy** [SiCKRAGETV/sickrage-issues#1630]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.7+-armv6l-with-debian-7.8**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/1bf677e0f837311ef2ba
### ERROR
```
Thread-36 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/local/sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/usr/local/sickrage/sickbeard/webserve.py", line 2166, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/usr/local/sickrage/sickbeard/processTV.py", line 203, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/usr/local/sickrage/sickbeard/processTV.py", line 504, in process_media
    result.result = processor.process()
  File "/usr/local/sickrage/sickbeard/postProcessor.py", line 1066, in process
    cur_ep.airdateModifyStamp()
  File "/usr/local/sickrage/sickbeard/tv.py", line 2599, in airdateModifyStamp
    if filemtime != airdatetime:
  File "/usr/local/sickrage/lib/dateutil/tz.py", line 108, in utcoffset
    if self._isdst(dt):
  File "/usr/local/sickrage/lib/dateutil/tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: timestamp out of range for platform time_t

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by luxmoggy** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.7+-armv6l-with-debian-7.8**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/151d72ef79efc4da364f
### ERROR
```
Thread-39 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/local/sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/usr/local/sickrage/sickbeard/webserve.py", line 2166, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/usr/local/sickrage/sickbeard/processTV.py", line 203, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/usr/local/sickrage/sickbeard/processTV.py", line 504, in process_media
    result.result = processor.process()
  File "/usr/local/sickrage/sickbeard/postProcessor.py", line 1066, in process
    cur_ep.airdateModifyStamp()
  File "/usr/local/sickrage/sickbeard/tv.py", line 2599, in airdateModifyStamp
    if filemtime != airdatetime:
  File "/usr/local/sickrage/lib/dateutil/tz.py", line 108, in utcoffset
    if self._isdst(dt):
  File "/usr/local/sickrage/lib/dateutil/tz.py", line 152, in _isdst
    return time.localtime(timestamp+time.timezone).tm_isdst
ValueError: timestamp out of range for platform time_t

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Probably a bad date on the indexer. check:
https://github.com/SiCKRAGETV/sickrage-issues/issues/840

**Comment by blakadder** [comment]
### INFO
Python Version: **2.7.9 (default, Jan 16 2015, 11:00:00) [GCC 4.9.2]**
Operating System: **Linux-2.6.31.8-armv5tel-with-libc0**
Locale: ISO8859-1
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: timestamp out of range for platform time_t
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
