### ISSUE TITLE
[APP SUBMITTED]: tuple index out of range

### ISSUE THREAD

**Issue by aflics** [SiCKRAGETV/sickrage-issues#1637]
### INFO
Python Version: **2.7.6 (default, Sep  9 2014, 15:04:36) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]**
Operating System: **Darwin-14.3.0-x86_64-i386-64bit**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/750b79efebc1be5f4577
### ERROR
```
Thread-48 :: Failed doing webui callback: Traceback (most recent call last):
  File "/Applications/SickRage-master/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/Applications/SickRage-master/sickbeard/webserve.py", line 2166, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/Applications/SickRage-master/sickbeard/processTV.py", line 250, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/Applications/SickRage-master/sickbeard/processTV.py", line 504, in process_media
    result.result = processor.process()
  File "/Applications/SickRage-master/sickbeard/postProcessor.py", line 1081, in process
    notifiers.plex_notifier.update_library(ep_obj)
  File "/Applications/SickRage-master/sickbeard/notifiers/plex.py", line 254, in update_library
    hosts_try = (hosts_all.copy(), hosts_match.copy())[len(hosts_match)]
IndexError: tuple index out of range

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@Thraxis can you check this please? do you also have this error?

**Comment by tacosan1** [comment]
I have been plagued with the almost the same error (line difference in processTV.py):

2015-05-20 21:45:37 Thread-58 :: Failed doing webui callback: Traceback (most recent call last):
  File "******/sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "******/sickrage/sickbeard/webserve.py", line 2166, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "******/sickrage/sickbeard/processTV.py", line 203, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "******/sickrage/sickbeard/processTV.py", line 504, in process_media
    result.result = processor.process()
  File "******/sickrage/sickbeard/postProcessor.py", line 1081, in process
    notifiers.plex_notifier.update_library(ep_obj)
  File "******/sickrage/sickbeard/notifiers/plex.py", line 254, in update_library
    hosts_try = (hosts_all.copy(), hosts_match.copy())[len(hosts_match)]
IndexError: tuple index out of range

**Comment by Thraxis** [comment]
I'll take a look at this tonight.  I've not personally had the error myself.

**Comment by alaorath** [comment]
This may be the cause of the POSTPROCESSOR thread no longer starting.

Checking my logs, the message `POSTPROCESSER :: Starting new thread: POSTPROCESSER` has occurred only once in the past 7 days (previously it runs about 90 times a day... which is what you'd expect for a 15 minute task).

BRANCH: (master) / COMMIT: (26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9)

**Comment by alaorath** [comment]
bump.

Still occurring, seems to be worse when post-processing a full season (or new show)... I had to manually copy the episodes to the destination and then force a Re-scan to pick them up.

BRANCH: (master) / COMMIT: (68c55eadbd502c63ae35e42ccc741509e94f3d6a)

**Comment by aflics** [comment]
Personally I disabled the Plex notification and it allowed me to post process again. I have changed it to no longer notify Plex and instead Plex monitors folders for changes. More resource intensive on the disk reads but allows me to not get an error.

**Comment by fernandog** [comment]
@Thraxis did you had the time to check this?

@aflics can you send a screenshot of all your PLEX settings?
do you still have this issue?

**Comment by fernandog** [comment]
no replies

**Comment by thesatman** [comment]
### INFO
Python Version: **2.7.8 (default, Jul  2 2014, 19:48:49) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7600**
Branch: **master**
Commit: SiCKRAGETV/SickRage@0769c527da9b41180618db6cc23039547a4be3d8
Link to Log: https://gist.github.com/45cb1775cf9484f3269a
### ERROR
```
Thread-62 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 2306, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "C:\SickRage\sickbeard\processTV.py", line 204, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "C:\SickRage\sickbeard\processTV.py", line 491, in process_media
    result.result = processor.process()
  File "C:\SickRage\sickbeard\postProcessor.py", line 1092, in process
    notifiers.plex_notifier.update_library(ep_obj)
  File "C:\SickRage\sickbeard\notifiers\plex.py", line 260, in update_library
    hosts_try = (hosts_all.copy(), hosts_match.copy())[len(hosts_match)]
IndexError: tuple index out of range

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by thesatman** [comment]
### INFO
Python Version: **2.7.8 (default, Jul  2 2014, 19:48:49) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7600**
Branch: **master**
Commit: SiCKRAGETV/SickRage@0769c527da9b41180618db6cc23039547a4be3d8
Link to Log: https://gist.github.com/b26b608d996f9a467e6d
### ERROR
```
Thread-72 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 2306, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "C:\SickRage\sickbeard\processTV.py", line 204, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "C:\SickRage\sickbeard\processTV.py", line 491, in process_media
    result.result = processor.process()
  File "C:\SickRage\sickbeard\postProcessor.py", line 1092, in process
    notifiers.plex_notifier.update_library(ep_obj)
  File "C:\SickRage\sickbeard\notifiers\plex.py", line 260, in update_library
    hosts_try = (hosts_all.copy(), hosts_match.copy())[len(hosts_match)]
IndexError: tuple index out of range

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by thesatman** [comment]
Happened after a complete tv show serie was downloaded. First SR did a file corruption check on all shows in the download (10 episodes). Files are then copied from torrent map to processed map. Then postprocessing begins and manages to copy 1 episode to Plex media folder. Then it aborts. The remaining 9 episodes are still in the processed map, and the torrent + original files are not removed. I can however in SR choose manual postprocess. It will then process, rename and move 1 episode to Plex. So I had to do this 9 times. Plex was not updated.

**Comment by miigotu** [comment]
That should be bool(hosts_match). But you will still get an error after that fix.

**Comment by miigotu** [comment]
@thesatman can you please update and try again? I merged a hotfix.
