### ISSUE TITLE
[APP SUBMITTED]: Command has timed out

### ISSUE THREAD

**Issue by megabitus98** [SiCKRAGETV/sickrage-issues#1638]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:38) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-37-generic-i686-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/4060b560901297bdba4d
### ERROR
```
Thread-38 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1411, in editShow
    shortwhitelist = short_group_names(whitelist)
  File "/opt/sickrage/sickbeard/blackandwhitelist.py", line 104, in short_group_names
    group = sickbeard.ADBA_CONNECTION.group(gname=groupName)
  File "/opt/sickrage/lib/adba/__init__.py", line 565, in group
    return self.handle(GroupCommand(gid, gname), callback)
  File "/opt/sickrage/lib/adba/__init__.py", line 127, in handle
    raise AniDBCommandTimeoutError("Command has timed out")
AniDBCommandTimeoutError: Command has timed out

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@megabitus98 This looks to be a one time error, and a restart should be enough.
If the error is showing again and again than please let us know.

**Comment by Ic3Nine** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@9956e7beb05a387d7fbe68883c48dcb01230be6a
Link to Log: https://gist.github.com/33611c56cd58b0a18b72
### ERROR
```
Thread-50 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2773, in addNewShow
    whitelist = short_group_names(whitelist)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/blackandwhitelist.py", line 104, in short_group_names
    group = sickbeard.ADBA_CONNECTION.group(gname=groupName)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/adba/__init__.py", line 565, in group
    return self.handle(GroupCommand(gid, gname), callback)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/adba/__init__.py", line 127, in handle
    raise AniDBCommandTimeoutError("Command has timed out")
AniDBCommandTimeoutError: Command has timed out

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by bb12489** [comment]
### INFO
Python Version: **2.7.7 (default, Jun  1 2014, 14:21:57) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@136f531f93093a5287b588ca37e19c11153f47a4
No Log available with ERRORS: 
### ERROR
```
Thread-67 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 2060, in fetch_releasegroups
    groups = anime.get_groups()
  File "C:\SickRage\lib\adba\aniDBAbstracter.py", line 171, in get_groups
    self.rawData = self.aniDB.groupstatus(aid=self.aid)
  File "C:\SickRage\lib\adba\__init__.py", line 581, in groupstatus
    return self.handle(GroupstatusCommand(aid, state), callback)
  File "C:\SickRage\lib\adba\__init__.py", line 127, in handle
    raise AniDBCommandTimeoutError("Command has timed out")
AniDBCommandTimeoutError: Command has timed out

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@miigotu try/except with `groups = anime.get_groups()` ?

**Comment by miigotu** [comment]
How about just increase the timeout?

**Comment by fernandog** [comment]
And when really timeout? Traceback again? New issue?

**Comment by miigotu** [comment]
I guess catch it too..

**Comment by fernandog** [comment]
Can we reuse all that exceptions from helpers.getURl? How to re-use that code for this and for other places?

**Comment by miigotu** [comment]
@fernandog no. It isnt throwing a requests exception.

`from adba.aniDBerrors import AniDBCommandTimeoutError`


then in sickbeard/blackandwhitelist.py", in short_group_names

try/except AniDBCommandTimeoutError

**Comment by fernandog** [comment]
@miigotu

like this?

```
def short_group_names(groups):
    """
    Find AniDB short group names for release groups

    :param groups: list of groups to find short group names for
    :return: list of shortened group names
    """
    groups = groups.split(",")
    shortGroupList = []
    if helpers.set_up_anidb_connection():
        for groupName in groups:
            try:
                group = sickbeard.ADBA_CONNECTION.group(gname=groupName)
            except AniDBCommandTimeoutError:
                logger.log(u"Timeout while loading group from AniDB", logger.DEBUG)
            except:
                logger.log(u"Failed while loading group from AniDB. Trying next group", logger.DEBUG)
            else:
                for line in group.datalines:
                    if line["shortname"]:
                        shortGroupList.append(line["shortname"])
                    else:
                        if not groupName in shortGroupList:
                            shortGroupList.append(groupName)
    else:
        shortGroupList = groups
    return shortGroupList
```
