### ISSUE TITLE
Exception raised when sending torrent

### ISSUE THREAD

**Issue by alaorath** [SiCKRAGETV/sickrage-issues#1650]
SR Version:	BRANCH: (master) / COMMIT: (26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9) 
Python Version:	2.7.3 (default, Jul 4 2012, 17:31:14) [GCC 4.3.2]
`$ uname -or`
`2.6.37.6.RNx86_64.2.4 GNU/Linux`

Observed:
* New shows not downloading automatically.
* Logging into the web interface, in all cases they are listed as "snagged" but no information in transmission indicates they were properly passed to the torrent client.

Expected:
* clicking the magnifier "search" next to each "snagged" show (and selecting 'yes' to same quality). the episode of the show is found, and added to transmission for downloading (and I would presume, post-processed).

Unfortunately the log files overwrite very quickly.

But... I've started Splunking them... ("Splunk all the things!")

I've attached one log snippet (searching sickrage logs for the string "Downloading Game.of.Thrones.S05E06" and then expanding the search to +/- 15 seconds of that, exporting the Splunked result to raw logs, and finally trimming out all clutter (other shows that were processes in the same cycle)

Hmm, can't figure how to attach a log file... let's try inline...

2015-05-18 06:26:26 INFO     DAILYSEARCHER :: Searching for new released episodes ...
2015-05-18 06:26:26 INFO     DAILYSEARCHER :: No new released episodes found ...
2015-05-18 06:26:26 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2015-05-18 06:26:26 INFO     SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from Game of Thrones
2015-05-18 06:26:26 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Search string: https://thepiratebay.se/tv/latest/
2015-05-18 06:26:26 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: EZTV search page URL: https://eztv.ch/
2015-05-18 06:26:26 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: Search string: https://kat.cr/tv/?field=time_add&sorder=desc&rss=1
2015-05-18 06:26:26 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [showrss] :: TorrentRssCache cache update URL: http://showrss.info/rss.php?user_id=37967&hd=2&proper=null&raw=true
2015-05-18 06:26:27 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Connection error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error while loading URL https://thepiratebay.se/tv/latest/
2015-05-18 06:26:28 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [showrss] :: Attempting to add item to cache: Game.of.Thrones.S05E06.720p.HDTV.x264.IMMERSE
2015-05-18 06:26:28 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [showrss] :: Using ALL regexes
2015-05-18 06:26:28 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [showrss] :: Converted parsed result Game.of.Thrones.S05E06.720p.HDTV.x264.IMMERSE into Game of Thrones - S5E6 [ANIME VER: -1] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-05-18 06:26:28 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [showrss] :: Parsed Game.of.Thrones.S05E06.720p.HDTV.x264.IMMERSE into Game of Thrones - S5E6 [ANIME VER: -1] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-05-18 06:26:28 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [showrss] :: Added RSS item: [Game.of.Thrones.S05E06.720p.HDTV.x264.IMMERSE] to cache: [showrss]
2015-05-18 06:26:28 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [showrss] :: Attempting to add item to cache: Game.of.Thrones.S05E06.HDTV.x264.ASAP
2015-05-18 06:26:28 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [showrss] :: Using ALL regexes
2015-05-18 06:26:28 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [showrss] :: Converted parsed result Game.of.Thrones.S05E06.HDTV.x264.ASAP into Game of Thrones - S5E6 [ANIME VER: -1] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-05-18 06:26:28 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [showrss] :: Parsed Game.of.Thrones.S05E06.HDTV.x264.ASAP into Game of Thrones - S5E6 [ANIME VER: -1] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-05-18 06:26:28 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [showrss] :: Added RSS item: [Game.of.Thrones.S05E06.HDTV.x264.ASAP] to cache: [showrss]
2015-05-18 06:26:30 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Empty lookup result - no XEM data for show 121361 on theTVDB
2015-05-18 06:26:30 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Converted parsed result Game.of.Thrones.S05E06.1080p.HDTV.x264-BATV into Game of Thrones - S5E6 [ANIME VER: -1] [GROUP: BATV] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-05-18 06:26:30 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Parsed Game.of.Thrones.S05E06.1080p.HDTV.x264-BATV into Game of Thrones - S5E6 [ANIME VER: -1] [GROUP: BATV] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-05-18 06:26:30 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Added RSS item: [Game.of.Thrones.S05E06.1080p.HDTV.x264-BATV] to cache: [eztv]
2015-05-18 06:26:30 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Attempting to add item to cache: Game.of.Thrones.S05E06.INTERNAL.720p.HDTV.x264-BATV
2015-05-18 06:26:30 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Using ALL regexes
2015-05-18 06:26:30 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Converted parsed result Game.of.Thrones.S05E06.INTERNAL.720p.HDTV.x264-BATV into Game of Thrones - S5E6 [ANIME VER: -1] [GROUP: BATV] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-05-18 06:26:30 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Parsed Game.of.Thrones.S05E06.INTERNAL.720p.HDTV.x264-BATV into Game of Thrones - S5E6 [ANIME VER: -1] [GROUP: BATV] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-05-18 06:26:30 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Added RSS item: [Game.of.Thrones.S05E06.INTERNAL.720p.HDTV.x264-BATV] to cache: [eztv]
2015-05-18 06:26:30 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Converted parsed result Game.of.Thrones.S05E06.INTERNAL.HDTV.x264-BATV into Game of Thrones - S5E6 [ANIME VER: -1] [GROUP: BATV] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-05-18 06:26:30 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Parsed Game.of.Thrones.S05E06.INTERNAL.HDTV.x264-BATV into Game of Thrones - S5E6 [ANIME VER: -1] [GROUP: BATV] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-05-18 06:26:30 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Added RSS item: [Game.of.Thrones.S05E06.INTERNAL.HDTV.x264-BATV] to cache: [eztv]
2015-05-18 06:26:30 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Converted parsed result Game.of.Thrones.S05E06.1080i.HDTV.MPEG2.DD5.1-CtrlHD into Game of Thrones - S5E6 [ANIME VER: -1] [GROUP: CtrlHD] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-05-18 06:26:30 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Parsed Game.of.Thrones.S05E06.1080i.HDTV.MPEG2.DD5.1-CtrlHD into Game of Thrones - S5E6 [ANIME VER: -1] [GROUP: CtrlHD] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-05-18 06:26:30 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Added RSS item: [Game.of.Thrones.S05E06.1080i.HDTV.MPEG2.DD5.1-CtrlHD] to cache: [eztv]
2015-05-18 06:26:31 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Attempting to add item to cache: Game.of.Thrones.S05E06.HDTV.x264-ASAP
2015-05-18 06:26:31 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Using ALL regexes
2015-05-18 06:26:31 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Converted parsed result Game.of.Thrones.S05E06.HDTV.x264-ASAP into Game of Thrones - S5E6 [ANIME VER: -1] [GROUP: ASAP] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-05-18 06:26:31 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Parsed Game.of.Thrones.S05E06.HDTV.x264-ASAP into Game of Thrones - S5E6 [ANIME VER: -1] [GROUP: ASAP] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-05-18 06:26:31 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Added RSS item: [Game.of.Thrones.S05E06.HDTV.x264-ASAP] to cache: [eztv]
2015-05-18 06:26:31 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [showrss] :: Attempting to add item to cache: Game.Of.Thrones.S05E05.720p.HDTV.x264.0SEC
2015-05-18 06:26:31 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [showrss] :: Using ALL regexes
2015-05-18 06:26:31 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [showrss] :: Converted parsed result Game.Of.Thrones.S05E05.720p.HDTV.x264.0SEC into Game Of Thrones - S5E5 [ANIME VER: -1] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-05-18 06:26:32 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [showrss] :: Parsed Game.Of.Thrones.S05E05.720p.HDTV.x264.0SEC into Game Of Thrones - S5E5 [ANIME VER: -1] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-05-18 06:26:32 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [showrss] :: Added RSS item: [Game.Of.Thrones.S05E05.720p.HDTV.x264.0SEC] to cache: [showrss]
2015-05-18 06:26:32 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [showrss] :: Transaction with 26 queries executed
2015-05-18 06:26:32 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Transaction with 42 queries executed
2015-05-18 06:26:32 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Transaction with 42 queries executed
2015-05-18 06:26:32 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Checking if found episode 5x6 is wanted at quality 1080p HDTV
2015-05-18 06:26:32 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: any,best = [16, 64, 256] [] and found 16
2015-05-18 06:26:32 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Existing episode status: 3 (Wanted)
2015-05-18 06:26:32 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Existing episode status is wanted/unaired/skipped, getting found episode
2015-05-18 06:26:32 INFO     SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Found result Game.of.Thrones.S05E06.1080p.HDTV.x264-BATV at magnet:?xt=urn:btih:&dn=%5Beztv%5D&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969
2015-05-18 06:26:32 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Picking the best result out of [u'Game.of.Thrones.S05E06.1080p.HDTV.x264-BATV']
2015-05-18 06:26:32 INFO     SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Quality of Game.of.Thrones.S05E06.1080p.HDTV.x264-BATV is 1080p HDTV
2015-05-18 06:26:32 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: Picked Game.of.Thrones.S05E06.1080p.HDTV.x264-BATV as the best
2015-05-18 06:26:32 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: Transaction with 42 queries executed
2015-05-18 06:26:32 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [showrss] :: Transaction with 42 queries executed
2015-05-18 06:26:32 INFO     SEARCHQUEUE-DAILY-SEARCH :: Downloading Game.of.Thrones.S05E06.1080p.HDTV.x264-BATV from EZTV
2015-05-18 06:26:32 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Calling Transmission Client
2015-05-18 06:26:32 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Transmission: Requested a POST connection to url http://localhost:8181/transmission/rpc with Params= {} Data={"arguments": {}, "method": "session-get"}
2015-05-18 06:26:32 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Transmission: Requested a POST connection to url http://localhost:8181/transmission/rpc with Params= {} Data={"arguments": {}, "method": "session-get"}
2015-05-18 06:26:32 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Transmission: Response to POST request is {"arguments":{"alt-speed-down":2000,"alt-speed-enabled":false,"alt-speed-time-begin":360,"alt-speed-time-day":127,"alt-speed-time-enabled":false,"alt-speed-time-end":1410,"alt-speed-up":100,"blocklist-enabled":true,"blocklist-size":227851,"blocklist-url":"http://list.iblocklist.com/?list=bt_level1&fileformat=p2p&archiveformat=gz","cache-size-mb":200,"config-dir":"/c/addons-config/Transmission/transmission-daemon","dht-enabled":false,"download-dir":"/c/media/BitTorrent/Finished","download-dir-free-space":5071822381056,"download-queue-enabled":true,"download-queue-size":4,"encryption":"preferred","idle-seeding-limit":120,"idle-seeding-limit-enabled":true,"incomplete-dir":"/c/media/BitTorrent/.Incomplete","incomplete-dir-enabled":true,"lpd-enabled":false,"peer-limit-global":240,"peer-limit-per-torrent":60,"peer-port":51413,"peer-port-random-on-start":false,"pex-enabled":true,"port-forwarding-enabled":true,"queue-stalled-enabled":true,"queue-stalled-minutes":30,"rename-partial-files":true,"rpc-version":14,"rpc-version-minimum":1,"script-torrent-done-enabled":false,"script-torrent-done-filename":"/c/addons-config/Transmission/email_alert","seed-queue-enabled":false,"seed-queue-size":10,"seedRatioLimit":0.8000,"seedRatioLimited":true,"speed-limit-down":600,"speed-limit-down-enabled":false,"speed-limit-up":90,"speed-limit-up-enabled":true,"start-added-torrents":true,"trash-original-torrent-files":true,"units":{"memory-bytes":1024,"memory-units":["KiB","MiB","GiB","TiB"],"size-bytes":1000,"size-units":["kB","MB","GB","TB"],"speed-bytes":1000,"speed-units":["kB/s","MB/s","GB/s","TB/s"]},"utp-enabled":true,"version":"2.77 (14031)"},"result":"success"}
2015-05-18 06:26:32 ERROR    SEARCHQUEUE-DAILY-SEARCH :: Transmission: Failed Sending Torrent
Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/clients/generic.py", line 186, in sendTORRENT
    result = self._get_torrent_hash(result)
  File "/opt/sickbeard/sickbeard/clients/generic.py", line 148, in _get_torrent_hash
    result.hash = re.findall('urn:btih:([\w]{32,40})', result.url)[0]
IndexError: list index out of range
2015-05-18 06:26:32 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Transmission: Exception raised when sending torrent: EZTV @ magnet:?xt=urn:btih:&dn=%5Beztv%5D&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969
Extra Info:
Episode: [<sickbeard.tv.TVEpisode object at 0x9aaaeec>]
Quality: 1080p HDTV
Name: Game.of.Thrones.S05E06.1080p.HDTV.x264-BATV
Size: -1
Release Group: BATV
. Error: list index out of range

**Comment by alaorath** [comment]
Sorry if this is a dup, I tried searching and couldn't find anything quite the same.  Plus since I have really good logs from Splunk I thought I'd post.

**Comment by neoatomic** [comment]
@alaorath Problem is the EZTV provider. Looks like it sends not valid torrents. https://github.com/SiCKRAGETV/sickrage-issues/issues/1640

**Comment by alaorath** [comment]
Okay thanks, I'll pull it out of my config rotation.  Seems like providers are dropping like flies these days :(

**Comment by alaorath** [comment]
I think the issues with EZTV are un-related.  Scraping the logs files in more detail, there are only three "Exception raised when sending torrent" errors, but between the past week and Monday, no torrent was successfully added to Transmission (or downloaded).

Reviewing the "SEARCHQUEUE-DAILY-SEARCH" for that time range shows no errors (aside from the above mentioned three from EZTV) - despite not episodes being downloaded. It looks like the problem is on the Transmission side (which I don't have good logging for)... the plot thickens.
