### ISSUE TITLE
errors running on freeNAS

### ISSUE THREAD

**Issue by ovizii** [SiCKRAGETV/sickrage-issues#1652]
I'm running the sickrage plugin on freeNAS and SR seems to have problems saving its config. Whenever I change stuff, then reload the config page it seems it simply didn't save it or has trouble reading it. So obviously I can't really enable debug since that doesn't get saved...

Here is what I have:
_2015-05-21 09:41:23 Thread-24 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 3771, in saveGeneral
    sickbeard.save_config()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/__init__.py", line 1613, in save_config
    new_config['General']['log_nr'] = int(LOG_NR)
ValueError: invalid literal for int() with base 10: ''

2015-05-21 09:41:21 Thread-32 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 3771, in saveGeneral
    sickbeard.save_config()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/__init__.py", line 1613, in save_config
    new_config['General']['log_nr'] = int(LOG_NR)
ValueError: invalid literal for int() with base 10: ''

2015-05-21 09:34:23 Thread-26 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 3771, in saveGeneral
    sickbeard.save_config()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/__init__.py", line 1613, in save_config
    new_config['General']['log_nr'] = int(LOG_NR)
ValueError: invalid literal for int() with base 10: ''

2015-05-21 09:34:12 Thread-30 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 3771, in saveGeneral
    sickbeard.save_config()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/__init__.py", line 1613, in save_config
    new_config['General']['log_nr'] = int(LOG_NR)
ValueError: invalid literal for int() with base 10: ''_

SR Version:	BRANCH: (master) / COMMIT: (26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9) 
SR User:	media
SR Locale:	(None, None)
SR Config file:	/var/db/sickrage/config.ini
SR Database file:	/var/db/sickrage/sickbeard.db
SR Cache Dir:	/var/db/sickrage/cache
SR Log Dir:	/var/db/sickrage
SR Arguments:	['--datadir', '/var/db/sickrage', '-d', '--pidfile', '/var/run/sickrage/sickrage.pid', '-q', '--nolaunch']
Python Version:	2.7.9 (default, Apr 30 2015, 06:12:10) [GCC 4.2.1 20070831 patched [FreeBSD]]

**Comment by neoatomic** [comment]
@ovizii  Sounds like an installation/permission problem. 

"SR Locale: (None, None)" is also not correct, should be ('en_US', 'UTF-8'). Another indication that its a bad installation...
Best to ask the plug-in creator, or on the FreeNAS forums how to properly setup/install this for your specific device.

**Comment by ovizii** [comment]
I understand, I'll try those forums. Thanks for the pointers.
