### ISSUE TITLE
[APP SUBMITTED]: HTTPSConnectionPool(host='sceneaccess.eu', port=443): Read timed out. (read timeout=30)

### ISSUE THREAD

**Issue by sea3pea0** [SiCKRAGETV/sickrage-issues#1659]
### INFO
Python Version: **2.7.9 (default, Dec 28 2014, 22:27:57) [GCC 4.7.3]**
Operating System: **Linux-3.15.2-hardened-whatbox-x86_64-Intel-R-_Xeon-R-_CPU_E5620_@_2.40GHz-with-gentoo-2.2**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/6cd19a854f7d92e048bf
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [SceneAccess] :: Failed parsing SceneAccess Traceback: Traceback (most recent call last):
  File "/mnt/sdg1/sea3pea0/sickbeard/sickbeard/providers/scc.py", line 225, in _doSearch
    data = self.getURL(self.url + "/" + link['href'])
  File "/mnt/sdg1/sea3pea0/sickbeard/sickbeard/providers/generic.py", line 126, in getURL
    if not self._doLogin():
  File "/mnt/sdg1/sea3pea0/sickbeard/sickbeard/providers/scc.py", line 95, in _doLogin
    response = self.session.post(self.urls['login'], data=login_params, headers=self.headers, timeout=30, verify=False)
  File "/mnt/sdg1/sea3pea0/sickbeard/lib/requests/sessions.py", line 504, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/mnt/sdg1/sea3pea0/sickbeard/lib/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/sdg1/sea3pea0/sickbeard/lib/requests/sessions.py", line 599, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/mnt/sdg1/sea3pea0/sickbeard/lib/requests/sessions.py", line 192, in resolve_redirects
    allow_redirects=False,
  File "/mnt/sdg1/sea3pea0/sickbeard/lib/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/mnt/sdg1/sea3pea0/sickbeard/lib/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='sceneaccess.eu', port=443): Read timed out. (read timeout=30)

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@sea3pea0 Connection timeout. Should be a one time error.
