### ISSUE TITLE
[APP SUBMITTED]: [Error 2] The system cannot find the file specified: u'D:\\SABnzbd_complete\\TV\\mickey mouse clubhouse\\Mickey Mouse ClubHouse -S01E09 Goofy On Mars.mp4'

### ISSUE THREAD

**Issue by ntrantham** [SiCKRAGETV/sickrage-issues#1673]
### INFO
Python Version: **2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/9368d03c70c2429b0ea5
### ERROR
```
Thread-220 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 2166, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "C:\SickRage\sickbeard\processTV.py", line 250, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "C:\SickRage\sickbeard\processTV.py", line 504, in process_media
    result.result = processor.process()
  File "C:\SickRage\sickbeard\postProcessor.py", line 880, in process
    existing_file_status = self._checkForExistingFile(ep_obj.location)
  File "C:\SickRage\sickbeard\postProcessor.py", line 132, in _checkForExistingFile
    if ek.ek(os.path.getsize, existing_file) > ek.ek(os.path.getsize, self.file_path):
  File "C:\SickRage\sickbeard\encodingKludge.py", line 71, in ek
    result = func(*args, **kwargs)
  File "C:\Python27\lib\genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
WindowsError: [Error 2] The system cannot find the file specified: u'D:\\SABnzbd_complete\\TV\\mickey mouse clubhouse\\Mickey Mouse ClubHouse -S01E09 Goofy On Mars.mp4'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Windows cant find the file. It was already moved.? Of NTFS rights aren't correctly set on that location.?
