### ISSUE TITLE
[APP SUBMITTED]: 'ascii' codec can't encode character u'\xe9' in position 118: ordinal not in range(128)

### ISSUE THREAD

**Issue by Nibeck1309** [SiCKRAGETV/sickrage-issues#1680]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.11+-armv6l-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/228a43119d482544427a
### ERROR
```
Thread-34 :: Failed doing webui callback: Traceback (most recent call last):
  File "/media/media/Config_Files/sickrage/sickrage-server/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/media/media/Config_Files/sickrage/sickrage-server/sickbeard/webserve.py", line 2166, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/media/media/Config_Files/sickrage/sickrage-server/sickbeard/processTV.py", line 203, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/media/media/Config_Files/sickrage/sickrage-server/sickbeard/processTV.py", line 504, in process_media
    result.result = processor.process()
  File "/media/media/Config_Files/sickrage/sickrage-server/sickbeard/postProcessor.py", line 1066, in process
    cur_ep.airdateModifyStamp()
  File "/media/media/Config_Files/sickrage/sickrage-server/sickbeard/tv.py", line 2597, in airdateModifyStamp
    filemtime = datetime.datetime.fromtimestamp(os.path.getmtime(self.location)).replace(tzinfo=tzlocal())
  File "/usr/lib/python2.7/genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 118: ordinal not in range(128)

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

Full log here : http://pastebin.com/AQS6Xpsa

**Comment by neoatomic** [comment]
Same as https://github.com/SiCKRAGETV/sickrage-issues/issues/1655
