### ISSUE TITLE
[APP SUBMITTED]: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by ardalista** [SiCKRAGETV/sickrage-issues#1689]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-53-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@26a1aaec8a9a0b8cc82cfe78f33c720845b7bdd9
Link to Log: https://gist.github.com/010366246062c3ddb5fb
### ERROR
```
Thread-39 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/ardalista/.sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/ardalista/.sickrage/sickbeard/webserve.py", line 2166, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/home/ardalista/.sickrage/sickbeard/processTV.py", line 250, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/home/ardalista/.sickrage/sickbeard/processTV.py", line 504, in process_media
    result.result = processor.process()
  File "/home/ardalista/.sickrage/sickbeard/postProcessor.py", line 1075, in process
    notifiers.notify_download(ep_obj._format_pattern('%SN - %Sx%0E - %EN - %QN'))
  File "/home/ardalista/.sickrage/sickbeard/notifiers/__init__.py", line 96, in notify_download
    n.notify_download(ep_name)
  File "/home/ardalista/.sickrage/sickbeard/notifiers/nma.py", line 20, in notify_download
    message=ep_name)
  File "/home/ardalista/.sickrage/sickbeard/notifiers/nma.py", line 55, in _sendNMA
    response = p.push(title, event, message, priority=nma_priority, batch_mode=batch)
  File "/home/ardalista/.sickrage/lib/pynma/pynma.py", line 94, in push
    res = self.callapi('POST', ADD_PATH, datas)
  File "/home/ardalista/.sickrage/lib/pynma/pynma.py", line 108, in callapi
    http_handler.request(method, path, urlencode(args), headers)
  File "/usr/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1176, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 104] Connection reset by peer

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
This is an SSL error. Check your installation.
https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors

**Comment by ardalista** [comment]
already running latest version of openssl and python.. had been running fine until midway thru the day yesterday with no changes or updates made to my system... then this error started appearing.. will give sonarr a try I guess

**Comment by neoatomic** [comment]
@ardalista This error was fixed earlier today. NMA changed the url, so thats where the SSL error came from.

**Comment by ardalista** [comment]
oh hey thanks for the heads up.
