### ISSUE TITLE
2015-05-27 08:29:16 POSTPROCESSER :: Exception generated in thread POSTPROCESSER: error 10054 : An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by skeelkat** [SiCKRAGETV/sickrage-issues#1702]
Anyone have an Idea why Post processing is failing on?
Windows 7 x86 installation

2015-05-27 14:58:20 Thread-206 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\HTPC\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\HTPC\SickRage\sickbeard\webserve.py", line 2166, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "C:\HTPC\SickRage\sickbeard\processTV.py", line 250, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "C:\HTPC\SickRage\sickbeard\processTV.py", line 504, in process_media
    result.result = processor.process()
  File "C:\HTPC\SickRage\sickbeard\postProcessor.py", line 1075, in process
    notifiers.notify_download(ep_obj._format_pattern('%SN - %Sx%0E - %EN - %QN'))
  File "C:\HTPC\SickRage\sickbeard\notifiers\__init__.py", line 96, in notify_download
    n.notify_download(ep_name)
  File "C:\HTPC\SickRage\sickbeard\notifiers\nma.py", line 20, in notify_download
    message=ep_name)
  File "C:\HTPC\SickRage\sickbeard\notifiers\nma.py", line 55, in _sendNMA
    response = p.push(title, event, message, priority=nma_priority, batch_mode=batch)
  File "C:\HTPC\SickRage\lib\pynma\pynma.py", line 94, in push
    res = self.callapi('POST', ADD_PATH, datas)
  File "C:\HTPC\SickRage\lib\pynma\pynma.py", line 108, in callapi
    http_handler.request(method, path, urlencode(args), headers)
  File "C:\Python27\lib\httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 850, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 812, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 1216, in connect
    server_hostname=server_hostname)
  File "C:\Python27\lib\ssl.py", line 350, in wrap_socket
    _context=self)
  File "C:\Python27\lib\ssl.py", line 566, in __init__
    self.do_handshake()
  File "C:\Python27\lib\ssl.py", line 788, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 10054] An existing connection was forcibly closed by the remote host

**Comment by neoatomic** [comment]
Its notify my android device. Fixed that yesterday. With the next update for master it should be working again. Or if you cant wait you can switch to Develop branch.

**Comment by skeelkat** [comment]
Thanks man...

WORKED 100%

Kind Regards,

Johan Badenhorst
+264 (81) 129 1921
