### ISSUE TITLE
[APP SUBMITTED]: [Errno 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by georgeh12** [SiCKRAGETV/sickrage-issues#1707]
### INFO
Python Version: **2.7 (r27:82525, Jul  4 2010, 07:43:08) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-post2008Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@92bf581ba8a7d4f2f912db795ce571b6ad38c3c2
Link to Log: https://gist.github.com/4d48069073ff71a88611
### ERROR
```
Thread-38 :: Failed doing webui callback: Traceback (most recent call last):
  File "D:\Dropbox\programs\pvr\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "D:\Dropbox\programs\pvr\SickRage\sickbeard\webserve.py", line 1117, in update
    sickbeard.versionCheckScheduler.action.check_for_new_version(force=True)
  File "D:\Dropbox\programs\pvr\SickRage\sickbeard\versionChecker.py", line 269, in update
    return self.updater.update()
  File "D:\Dropbox\programs\pvr\SickRage\sickbeard\versionChecker.py", line 561, in update
    notifiers.notify_git_update(sickbeard.CUR_COMMIT_HASH if sickbeard.CUR_COMMIT_HASH else "")
  File "D:\Dropbox\programs\pvr\SickRage\sickbeard\notifiers\__init__.py", line 111, in notify_git_update
    n.notify_git_update(new_version)
  File "D:\Dropbox\programs\pvr\SickRage\sickbeard\notifiers\nma.py", line 31, in notify_git_update
    self._sendNMA(nma_api=None, nma_priority=None, event=title, message=update_text + new_version)
  File "D:\Dropbox\programs\pvr\SickRage\sickbeard\notifiers\nma.py", line 55, in _sendNMA
    response = p.push(title, event, message, priority=nma_priority, batch_mode=batch)
  File "D:\Dropbox\programs\pvr\SickRage\lib\pynma\pynma.py", line 94, in push
    res = self.callapi('POST', ADD_PATH, datas)
  File "D:\Dropbox\programs\pvr\SickRage\lib\pynma\pynma.py", line 108, in callapi
    http_handler.request(method, path, urlencode(args), headers)
  File "D:\Dropbox\Programs\Python\Python27\lib\httplib.py", line 946, in request
    self._send_request(method, url, body, headers)
  File "D:\Dropbox\Programs\Python\Python27\lib\httplib.py", line 987, in _send_request
    self.endheaders(body)
  File "D:\Dropbox\Programs\Python\Python27\lib\httplib.py", line 940, in endheaders
    self._send_output(message_body)
  File "D:\Dropbox\Programs\Python\Python27\lib\httplib.py", line 803, in _send_output
    self.send(msg)
  File "D:\Dropbox\Programs\Python\Python27\lib\httplib.py", line 755, in send
    self.connect()
  File "D:\Dropbox\Programs\Python\Python27\lib\httplib.py", line 1156, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "D:\Dropbox\Programs\Python\Python27\lib\ssl.py", line 342, in wrap_socket
    ciphers=ciphers)
  File "D:\Dropbox\Programs\Python\Python27\lib\ssl.py", line 121, in __init__
    self.do_handshake()
  File "D:\Dropbox\Programs\Python\Python27\lib\ssl.py", line 281, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 10054] An existing connection was forcibly closed by the remote host

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
This was fixed a few days ago. Update SickRage.

**Comment by Azno** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@5d4bec2c6022a9e2d5ec934791cf80a0b2553a6f
Link to Log: https://gist.github.com/bb6328deda38a980633c
### ERROR
```
Thread-68 :: Traceback (most recent call last):
  File "F:\SickRage\SickRage\sickbeard\logger.py", line 242, in submit_errors
    gist = gh.get_user().create_gist(True, {"sickrage.log": InputFileContent(paste_data)})
  File "F:\SickRage\SickRage\lib\github\AuthenticatedUser.py", line 473, in create_gist
    input=post_parameters
  File "F:\SickRage\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "F:\SickRage\SickRage\lib\github\Requester.py", line 212, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "F:\SickRage\SickRage\lib\github\Requester.py", line 251, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "F:\SickRage\SickRage\lib\github\Requester.py", line 281, in __requestRaw
    output = response.read()
  File "F:\SickRage\Python\lib\httplib.py", line 596, in read
    s = self._safe_read(self.length)
  File "F:\SickRage\Python\lib\httplib.py", line 703, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "F:\SickRage\Python\lib\socket.py", line 384, in read
    data = self._sock.recv(left)
  File "F:\SickRage\Python\lib\ssl.py", line 734, in recv
    return self.read(buflen)
  File "F:\SickRage\Python\lib\ssl.py", line 621, in read
    v = self._sslobj.read(len or 1024)
error: [Errno 10054] An existing connection was forcibly closed by the remote host

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Azno** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
Link to Log: https://gist.github.com/4f0a387e46c5b8ccd0b1
### ERROR
```
Thread-360 :: Traceback (most recent call last):
  File "F:\SickRage\SickRage\sickbeard\logger.py", line 305, in submit_errors
    if not report.raw_data['locked']:
  File "F:\SickRage\SickRage\lib\github\GithubObject.py", line 93, in raw_data
    self._completeIfNeeded()
  File "F:\SickRage\SickRage\lib\github\GithubObject.py", line 232, in _completeIfNeeded
    self.__complete()
  File "F:\SickRage\SickRage\lib\github\GithubObject.py", line 237, in __complete
    self._url.value
  File "F:\SickRage\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "F:\SickRage\SickRage\lib\github\Requester.py", line 212, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "F:\SickRage\SickRage\lib\github\Requester.py", line 251, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "F:\SickRage\SickRage\lib\github\Requester.py", line 277, in __requestRaw
    response = cnx.getresponse()
  File "F:\SickRage\Python\lib\httplib.py", line 1132, in getresponse
    response.begin()
  File "F:\SickRage\Python\lib\httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "F:\SickRage\Python\lib\httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "F:\SickRage\Python\lib\socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "F:\SickRage\Python\lib\ssl.py", line 734, in recv
    return self.read(buflen)
  File "F:\SickRage\Python\lib\ssl.py", line 621, in read
    v = self._sslobj.read(len or 1024)
error: [Errno 10054] An existing connection was forcibly closed by the remote host

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
