### ISSUE TITLE
[APP SUBMITTED]: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by ZulDemon** [SiCKRAGETV/sickrage-issues#1714]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@92bf581ba8a7d4f2f912db795ce571b6ad38c3c2
No Log available with ERRORS: 
### ERROR
```
Thread-42 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 2131, in fetch_releasegroups
    groups = anime.get_groups()
  File "C:\SickRage\lib\adba\aniDBAbstracter.py", line 167, in get_groups
    self.rawData = self.aniDB.groupstatus(aid=self.aid)
  File "C:\SickRage\lib\adba\__init__.py", line 581, in groupstatus
    return self.handle(GroupstatusCommand(aid, state), callback)
  File "C:\SickRage\lib\adba\__init__.py", line 115, in handle
    self.link.request(command)
  File "C:\SickRage\lib\adba\aniDBlink.py", line 218, in request
    self._send(command)
  File "C:\SickRage\lib\adba\aniDBlink.py", line 199, in _send
    self.sock.sendto(data, self.target)
  File "C:\Python27\lib\socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Please provide logs, or we are unable to look into this.

**Comment by ZulDemon** [comment]
Logs are n/a and issue hasn't appeared again. Thank you.
