### ISSUE TITLE
Manual Post Processing Failing

### ISSUE THREAD

**Issue by spang11ers** [SiCKRAGETV/sickrage-issues#1718]
I get the following error when trying to manually postprocess;

```
2015-05-30 12:08:51 Thread-28 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2174, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 203, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 504, in process_media
    result.result = processor.process()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/postProcessor.py", line 1069, in process
    ep_obj.createMetaFiles()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/tv.py", line 1916, in createMetaFiles
    self.createThumbnail()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/tv.py", line 1935, in createThumbnail
    result = cur_provider.create_episode_thumb(self) or result
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/metadata/generic.py", line 332, in create_episode_thumb
    return self.save_thumbnail(ep_obj)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/metadata/generic.py", line 499, in save_thumbnail
    thumb_url = self._get_episode_thumb_url(ep_obj)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/metadata/generic.py", line 386, in _get_episode_thumb_url
    myEp = helpers.validateShow(cur_ep.show, cur_ep.season, cur_ep.episode)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1046, in validateShow
    return t[show.indexerid][season][episode]
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tvdb_api/tvdb_api.py", line 948, in __getitem__
    self._getShowData(key, self.config['language'], True)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tvdb_api/tvdb_api.py", line 843, in _getShowData
    self.config['url_seriesInfo'] % (sid, getShowInLanguage)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tvdb_api/tvdb_api.py", line 632, in _getetsrc
    raise tvdb_error(e)
tvdb_error: Unknown exception while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/292421/en.xml: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tvdb_api/tvdb_api.py", line 574, in _loadUrl
    resp = session.get(url.strip(), cache_auto=True, params=params)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/cachecontrol/session.py", line 23, in get
    return super(CacheControlSession, self).get(*args, **kw)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/cachecontrol/adapter.py", line 27, in send
    cached_response = self.controller.cached_request(request)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/cachecontrol/controller.py", line 102, in cached_request
    parsedate_tz(headers['date'])
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'date'
```
Latest update and on Synology NAS. Nothing has changed except SickRage update

**Comment by stourwalk** [comment]
This is the same issue that I'm having, when reporting the issue from within Sickrage - it attached itself to 1712 (misposted probably because of the length of the single line it tried to name the issue after)

**Comment by neoatomic** [comment]
Follow the guidelines for posting an issue.: https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

**Comment by dsm1212** [comment]
Same problem on netgear nas. If I have time tomorrow night and no one has gathered logs yet I will. It's easily reproduced.

**Comment by dsm1212** [comment]
Updated when I got home and this seems to be fixed for me. I'm still plagued by the tlsv1 ssl error, but that's a different problem..

**Comment by neoatomic** [comment]
@spang11ers Backup and Install the new Sickrage package from Synocommunity. See https://github.com/SiCKRAGETV/sickrage-issues/issues/1730 for more info.
