### ISSUE TITLE
everything was working beautifully, until the last update

### ISSUE THREAD

**Issue by pierre2013** [SiCKRAGETV/sickrage-issues#1720]
Sorry if I am doing this wrong... This is what I got in my log. Maybe someone can point me in the right direction to sort this out? The post processing now shows up as not active...

Thanks 
```
2015-05-30 11:08:09 Thread-41 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 2174, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "C:\SickRage\sickbeard\processTV.py", line 203, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "C:\SickRage\sickbeard\processTV.py", line 504, in process_media
    result.result = processor.process()
  File "C:\SickRage\sickbeard\postProcessor.py", line 1069, in process
    ep_obj.createMetaFiles()
  File "C:\SickRage\sickbeard\tv.py", line 1916, in createMetaFiles
    self.createThumbnail()
  File "C:\SickRage\sickbeard\tv.py", line 1935, in createThumbnail
    result = cur_provider.create_episode_thumb(self) or result
  File "C:\SickRage\sickbeard\metadata\generic.py", line 332, in create_episode_thumb
    return self.save_thumbnail(ep_obj)
  File "C:\SickRage\sickbeard\metadata\generic.py", line 499, in save_thumbnail
    thumb_url = self._get_episode_thumb_url(ep_obj)
  File "C:\SickRage\sickbeard\metadata\generic.py", line 386, in _get_episode_thumb_url
    myEp = helpers.validateShow(cur_ep.show, cur_ep.season, cur_ep.episode)
  File "C:\SickRage\sickbeard\helpers.py", line 1046, in validateShow
    return t[show.indexerid][season][episode]
  File "C:\SickRage\lib\tvrage_api\tvrage_api.py", line 688, in __getitem__
    self._getShowData(key, True)
  File "C:\SickRage\lib\tvrage_api\tvrage_api.py", line 607, in _getShowData
    self.config['params_seriesInfo']
  File "C:\SickRage\lib\tvrage_api\tvrage_api.py", line 512, in _getetsrc
    raise tvrage_error(e)
tvrage_error: Unknown exception while loading URL http://services.tvrage.com/myfeeds/showinfo.php: Traceback (most recent call last):
  File "C:\SickRage\lib\tvrage_api\tvrage_api.py", line 410, in _loadUrl
    resp = session.get(url.strip(), cache_auto=True, params=params)
  File "C:\SickRage\lib\cachecontrol\session.py", line 23, in get
    return super(CacheControlSession, self).get(*args, **kw)
  File "C:\SickRage\lib\requests\sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "C:\SickRage\lib\requests\sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\SickRage\lib\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\SickRage\lib\cachecontrol\adapter.py", line 27, in send
    cached_response = self.controller.cached_request(request)
  File "C:\SickRage\lib\cachecontrol\controller.py", line 102, in cached_request
    parsedate_tz(headers['date'])
  File "C:\SickRage\lib\requests\structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'date'


2015-05-30 11:07:47 Thread-41 :: Unable to connect to TVRage while creating meta files - skipping - error Unknown exception while loading URL http://services.tvrage.com/myfeeds/showinfo.php: Traceback (most recent call last):
  File "C:\SickRage\lib\tvrage_api\tvrage_api.py", line 410, in _loadUrl
    resp = session.get(url.strip(), cache_auto=True, params=params)
  File "C:\SickRage\lib\cachecontrol\session.py", line 23, in get
    return super(CacheControlSession, self).get(*args, **kw)
  File "C:\SickRage\lib\requests\sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "C:\SickRage\lib\requests\sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\SickRage\lib\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\SickRage\lib\cachecontrol\adapter.py", line 27, in send
    cached_response = self.controller.cached_request(request)
  File "C:\SickRage\lib\cachecontrol\controller.py", line 102, in cached_request
    parsedate_tz(headers['date'])
  File "C:\SickRage\lib\requests\structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'date'

2015-05-30 10:49:48 POSTPROCESSER :: Exception generated in thread POSTPROCESSER: error Unknown exception while loading URL http://services.tvrage.com/myfeeds/showinfo.php: Traceback (most recent call last):
  File "C:\SickRage\lib\tvrage_api\tvrage_api.py", line 410, in _loadUrl
    resp = session.get(url.strip(), cache_auto=True, params=params)
  File "C:\SickRage\lib\cachecontrol\session.py", line 23, in get
    return super(CacheControlSession, self).get(*args, **kw)
  File "C:\SickRage\lib\requests\sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "C:\SickRage\lib\requests\sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\SickRage\lib\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\SickRage\lib\cachecontrol\adapter.py", line 27, in send
    cached_response = self.controller.cached_request(request)
  File "C:\SickRage\lib\cachecontrol\controller.py", line 102, in cached_request
    parsedate_tz(headers['date'])
  File "C:\SickRage\lib\requests\structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'date'

2015-05-30 10:49:27 POSTPROCESSER :: Unable to connect to TVRage while creating meta files - skipping - error Unknown exception while loading URL http://services.tvrage.com/myfeeds/showinfo.php: Traceback (most recent call last):
  File "C:\SickRage\lib\tvrage_api\tvrage_api.py", line 410, in _loadUrl
    resp = session.get(url.strip(), cache_auto=True, params=params)
  File "C:\SickRage\lib\cachecontrol\session.py", line 23, in get
    return super(CacheControlSession, self).get(*args, **kw)
  File "C:\SickRage\lib\requests\sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "C:\SickRage\lib\requests\sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\SickRage\lib\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\SickRage\lib\cachecontrol\adapter.py", line 27, in send
    cached_response = self.controller.cached_request(request)
  File "C:\SickRage\lib\cachecontrol\controller.py", line 102, in cached_request
    parsedate_tz(headers['date'])
  File "C:\SickRage\lib\requests\structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'date'
```

**Comment by neoatomic** [comment]
Follow the guidelines for posting an issue.: https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

**Comment by trick77** [comment]
The code assumes the date is present in the HTTP header. Since I'm not a Python dev and I don't know what I'm doing I'm not gonna submit a PR but here's how I fixed it:

lib/cachecontrol/controller.py around line 102:

given:
          date = calendar.timegm(
              parsedate_tz(headers['date'])
          )
          current_age = max(0, now - date)

replace with:

        if 'date' in headers:
          date = calendar.timegm(
              parsedate_tz(headers['date'])
          )
          current_age = max(0, now - date)
        else:
          current_age = 0

**Comment by adampetrovic** [comment]
Can also confirm that I am receiving this error since upgrading.

**Comment by pierre2013** [comment]
Thank you for the replies.

The error somehow went away after I shut the machine down completely, and started up again. A normal reboot was not enough???

**Comment by brendanheyu** [comment]
I have this same problem. Reboot and SR restart did not seem to help

**Comment by darklow** [comment]
I am also receiving same error
```
09:21:02 WARNING::SEARCHQUEUE-BACKLOG-72227 :: [TorrentLeech] :: Unknown exception while loading URL https://torrentleech.org/torrents/browse/index/query/Two%20and%20a%20Half%20Men%20S03/categories/2,26,27,32: Traceback (most recent call last):
  File "/www/*******/recap/sickbeard/sickrage/sickbeard/helpers.py", line 1294, in getURL
    resp = session.get(url, timeout=timeout)
  File "/www/*******/recap/sickbeard/sickrage/lib/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/www/*******/recap/sickbeard/sickrage/lib/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/www/*******/recap/sickbeard/sickrage/lib/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/www/*******/recap/sickbeard/sickrage/lib/cachecontrol/adapter.py", line 27, in send
    cached_response = self.controller.cached_request(request)
  File "/www/*******/recap/sickbeard/sickrage/lib/cachecontrol/controller.py", line 102, in cached_request
    parsedate_tz(headers['date'])
  File "/www/*******/recap/sickbeard/sickrage/lib/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'date'
```

**Comment by forrestrae** [comment]
Also getting the error.

**Comment by fernandog** [comment]
@trick77 can you make a PR in develop?

**Comment by trick77** [comment]
Is there no dependency management in SickRage? I'm wondering if I have to submit the latest cachecontrol version as a PR.

**Comment by miigotu** [comment]
@trick77 its not as simple as just replacing a library. Most of them need changes in the code to work with new versions of libraries, and most libraries have now dropped support for Python 2.6 (which we are going to do soon also).

CacheControl has now been updated in SR, as well as introduced some issues we are ironing out.

**Comment by trick77** [comment]
Thanks, miigotu, I really appreciate your work on this project.

**Comment by pierre2013** [comment]
I appreciate everyones work on the whole SickRage!!

Thank you for assisting with my ticket, everything is sorted out!!!

Big up!
