### ISSUE TITLE
[APP SUBMITTED]: unsupported operand type(s) for -: 'str' and 'int'

### ISSUE THREAD

**Issue by ThaPwned** [SiCKRAGETV/sickrage-issues#1729]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@92bf581ba8a7d4f2f912db795ce571b6ad38c3c2
Link to Log: https://gist.github.com/de35e10d99d1ecccca9d
### ERROR
```
Thread-61 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 1987, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 1946, in getEpisodes
    'quality': self.getQualityClass(searchThread.segment),
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 2000, in getQualityClass
    ep_status, ep_quality = Quality.splitCompositeStatus(ep_obj.status)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/common.py", line 264, in splitCompositeStatus
    return (status - x * 100, x)
TypeError: unsupported operand type(s) for -: 'str' and 'int'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Veldkornet** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 13:42:00) [GCC 4.6.4]**
Operating System: **Linux-2.6.32.12-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@68c55eadbd502c63ae35e42ccc741509e94f3d6a
Link to Log: https://gist.github.com/72e13036efc7961bbd2b
### ERROR
```
Thread-36 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 1987, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 1946, in getEpisodes
    'quality': self.getQualityClass(searchThread.segment),
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 2000, in getQualityClass
    ep_status, ep_quality = Quality.splitCompositeStatus(ep_obj.status)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/common.py", line 264, in splitCompositeStatus
    return (status - x * 100, x)
TypeError: unsupported operand type(s) for -: 'str' and 'int'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Veldkornet** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 13:42:00) [GCC 4.6.4]**
Operating System: **Linux-2.6.32.12-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@68c55eadbd502c63ae35e42ccc741509e94f3d6a
No Log available with ERRORS: 
### ERROR
```
Thread-26 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 1987, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 1946, in getEpisodes
    'quality': self.getQualityClass(searchThread.segment),
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 2000, in getQualityClass
    ep_status, ep_quality = Quality.splitCompositeStatus(ep_obj.status)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/common.py", line 264, in splitCompositeStatus
    return (status - x * 100, x)
TypeError: unsupported operand type(s) for -: 'str' and 'int'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@miigotu maybe status returned -1 ?

**Comment by miigotu** [comment]
status should never be -1. If it is, we need to find out where/why and stop it from happening.

**Comment by fernandog** [comment]
@miigotu what do you think adding a check if x is int before doing (status - x * 100, x) and it's not show a error message so user can open an issue?

**Comment by fernandog** [comment]
this is a duplicate or is it another issue? you referenced to another issue. I don't see what's common on they

**Comment by miigotu** [comment]
Invalid reference.

**Comment by fernandog** [comment]
@ThaPwned are you still having this issue?

**Comment by ThaPwned** [comment]
@fernandog Nope, nothing to see in the logs.
