### ISSUE TITLE
Post Process only works once after restart

### ISSUE THREAD

**Issue by scottwf** [SiCKRAGETV/sickrage-issues#1737]
BRANCH: (master) 
COMMIT: (42b8d5a9c71c87fcde301967b6254ef08c3093ac) 
Ubuntu 14.04.2 LTS
Python 2.7.6
Log file https://gist.github.com/scottwf/95df8fd91c9cc892bfda
If I restart sick rage the post processor will process one file and then the status page will list the post processor status alive as false.
Manual post processing works, but it will also only process one episode at a time so you have to submit manual post processing for each episode. 
It's been happening for the last 3 weeks and I keep hoping an update will fix the problem but I don't remember if it started failing after a particular update.

**Comment by neoatomic** [comment]
@scottwf It seems to error on the user-name. So check if you have the correct user-name/password in the autoPostProcesser. And disable Plex notifier for testing.
Your log shows the below error.:
  
```
2015-06-01 10:59:33 DEBUG POSTPROCESSER :: 'Traceback (most recent call last):\n File "/home/*****/Software/sickrage/sickbeard/scheduler.py", line 97, in run\n self.action.run(self.force)\n File "/home/*****/Software/sickrage/sickbeard/autoPostProcesser.py", line 50, in run\n processTV.processDir(sickbeard.TV_DOWNLOAD_DIR)\n File "/home/*****/Software/sickrage/sickbeard/processTV.py", line 203, in processDir\n process_media(path, [video], nzbName, process_method, force, is_priority, result)\n File "/home/*****/Software/sickrage/sickbeard/processTV.py", line 504, in process_media\n result.result = processor.process()\n File "/home/*****/Software/sickrage/sickbeard/postProcessor.py", line 1081, in process\n notifiers.plex_notifier.update_library(ep_obj)\n File "/home/*****/Software/sickrage/sickbeard/notifiers/plex.py", line 254, in update_library\n hosts_try = (hosts_all.copy(), hosts_match.copy())[len(hosts_match)]\nIndexError: tuple index out of range\n'
AAIndexError: tuple index out of range
AA hosts_try = (hosts_all.copy(), hosts_match.copy())[len(hosts_match)]
AA File "/home/*****/Software/sickrage/sickbeard/notifiers/plex.py", line 254, in update_library
AA notifiers.plex_notifier.update_library(ep_obj)
AA File "/home/*****/Software/sickrage/sickbeard/postProcessor.py", line 1081, in process
AA result.result = processor.process()
AA File "/home/*****/Software/sickrage/sickbeard/processTV.py", line 504, in process_media
AA process_media(path, [video], nzbName, process_method, force, is_priority, result)
AA File "/home/*****/Software/sickrage/sickbeard/processTV.py", line 203, in processDir
AA processTV.processDir(sickbeard.TV_DOWNLOAD_DIR)
AA File "/home/*****/Software/sickrage/sickbeard/autoPostProcesser.py", line 50, in run
AA self.action.run(self.force)
AA File "/home/*****/Software/sickrage/sickbeard/scheduler.py", line 97, in run
AATraceback (most recent call last): 
```
.

**Comment by scottwf** [comment]
The username and password were empty in the settings for plex notifications. 
I've unchecked the plex server notifications and now it works. I tried again with the username and password and it still works. 
Not sure how the credentials were removed, but thank you for the easy fix.
