### ISSUE TITLE
Database disk image is malformed and too many redirects issue

### ISSUE THREAD

**Issue by yongbi85** [SiCKRAGETV/sickrage-issues#1738]
Hello,

I'm on last commit for Sickrage branch master 

And since the last update, I can't open the homepage of sickrage anymore failing with a too many redirects..
If i type another page directly i can go to it so i could check the logs and this is what is displayed :+1: 
Also for information i did a restore of the db before the issue occured but still the same problem...
Anyone had this issue and know how to solve it ?

System : Synology
SR Version:	BRANCH: (master) / COMMIT: (42b8d5a9c71c87fcde301967b6254ef08c3093ac) 
SR User:	root
SR Locale:	('en_US', 'UTF-8')
SR Config file:	/usr/local/sickbeard-custom/var/config.ini
SR Database file:	/usr/local/sickbeard-custom/var/sickbeard.db
SR Cache Dir:	/usr/local/sickbeard-custom/var/cache
SR Log Dir:	/usr/local/sickbeard-custom/var/Logs
SR Arguments:	['--daemon', '--pidfile', '/usr/local/sickbeard-custom/var/sickbeard-custom.pid', '--config', '/usr/local/sickbeard-custom/var/config.ini', '--datadir', '/usr/local/sickbeard-custom/var/']
Python Version:	2.7.9 (default, Mar 23 2015, 00:07:04) [GCC 4.7.3 20130102 (prerelease)]

2015-06-02 07:19:39 Thread-352 :: Fatal error executing query: database disk image is malformed
2015-06-02 07:19:39 Thread-352 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 734, in index
    return t.respond()
  File "/usr/local/sickbeard-custom/var/cache/cheetah/_usr_local_sickbeard_custom_var_SickBeard_gui_slick_interfaces_default_home_tmpl.py", line 132, in respond
    sql_result = VFN(VFFSL(SL,"myDB",True),"select",False)(VFFSL(SL,"sql_statement",True))
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/db.py", line 192, in select
    sqlResults = self.action(query, args, fetchall=True)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/db.py", line 170, in action
    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/db.py", line 86, in execute
    return self._execute(query, args).fetchall()
DatabaseError: database disk image is malformed

**Comment by neoatomic** [comment]
@yongbi85 Backup and Install the new Sickrage package from Synocommunity. See https://github.com/SiCKRAGETV/sickrage-issues/issues/1730 for more info.

**Comment by fernandog** [comment]
@yongbi85 

how to fix database:
https://github.com/SiCKRAGETV/sickrage-issues/issues/549#issuecomment-72844385
