### ISSUE TITLE
[APP SUBMITTED]: not well-formed (invalid token): line 5, column 14

### ISSUE THREAD

**Issue by albertrdixon** [SiCKRAGETV/sickrage-issues#1756]
### INFO
Python Version: **2.7.9 (default, May 20 2015, 08:25:59) [GCC 4.9.2]**
Operating System: **Linux-3.19.4-031904-generic-x86_64-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@42b8d5a9c71c87fcde301967b6254ef08c3093ac
Link to Log: https://gist.github.com/bebd981bc8f815a2ef93
### ERROR
```
Thread-46 :: Failed doing webui callback: Traceback (most recent call last):
  File "/sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/sickrage/sickbeard/webserve.py", line 2174, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/sickrage/sickbeard/processTV.py", line 203, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/sickrage/sickbeard/processTV.py", line 504, in process_media
    result.result = processor.process()
  File "/sickrage/sickbeard/postProcessor.py", line 1081, in process
    notifiers.plex_notifier.update_library(ep_obj)
  File "/sickrage/sickbeard/notifiers/plex.py", line 224, in update_library
    xml_tree = etree.parse(urllib.urlopen(url))
  File "<string>", line 62, in parse
  File "<string>", line 38, in parse
ParseError: not well-formed (invalid token): line 5, column 14

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Check if you have added the Token to the Plex settings in SickRage. Seems the recent Plex update needs it now for https.

**Comment by fernandog** [comment]
we should catch this error and show a warning to user.
@neoatomic want to try?

**Comment by neoatomic** [comment]
@fernandog No, not comfortable to code it. :)
