### ISSUE TITLE
Sickrage doesn't start on Synology NAS, DB error

### ISSUE THREAD

**Issue by budsbenzer** [SiCKRAGETV/sickrage-issues#1777]
I installed the Sickrage Synocommunity package on my DS214play. Current branch is `develop`, current HEAD is `efa4fea2619f1b3f06c7402750fa44e9d862ebb4`. Python version is `2.7.10 (default, Jun  3 2015, 23:30:53)`

When I run the service from the Package Manager, it just says it failed after a while. I expected it to launch Sickrage. There seems to be trouble with the database, see [this gist](https://gist.github.com/budsbenzer/4adaed77781b391d92da#file-gistfile1-txt).

I tried deleting the database, but the same problem happens again. I also tried branch `master`, to no avail.

**Comment by WyzrdX** [comment]
I too am having an issue starting Sickrage on Syno. I have used the Sickbeard-custom as well as the premade Sickrage package. Both are timing out with a failed to start package service. I tried to use ssh and see if I could get it started and edned up with a db error as in [this gist](https://gist.github.com/WyzrdX/713a030419e450dcd76b.js).

**Comment by TheMalkavien** [comment]
I had the same problem with the MASTER branch (yesterday). Impossible to initialize a new database.
So I downloaded the release v4.0.22, launch it one first time. All was working good.
Then I updated to last MASTER commit, and all was still working good.

**Comment by Skrog** [comment]
Exact same issue here, running:
DSM 5.2-5565 Update 1 on DS1812+
Python: 2.7.10 (default, Jun 3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]

Tried both via the sickbeard-custom app and SickRage app (via SynoCommunity) and both the master and development branch.

Logfile seems identical to budsbenzer, but pasted for reference [here](https://gist.github.com/Skrog/0d629af5e9f53851cdb6)

**Comment by Grimthorr** [comment]
It seems the most recent commit has broken the repo for Synology users. I fixed this by manually reverting to commit SiCKRAGETV/sickrage@42b8d5a9c71c87fcde301967b6254ef08c3093ac (version 4.0.23) by connecting to my Synology NAS through SSH and running the following commands:

```sh
cd /volume1/@appstore/sickrage/var/SickRage
/volume1/@appstore/git/bin/git reset --hard 42b8d5a9c71c87fcde301967b6254ef08c3093ac
```

**Comment by batmanraid** [comment]
Hi,

I've tried but after executing the git command it replies with:

fatal: Unable to create '/volume1/@appstore/sickrage/var/SickRage/.git/index.lock': Permission denied

**Comment by Grimthorr** [comment]
@batmanraid Make sure you're logged in as root.

**Comment by batmanraid** [comment]
Ooooops!!!!

Done and running.

Thanks,

**Comment by WyzrdX** [comment]
@Grimthorr Thanks for the info. Reverted to 4.0.23 and all is good again.

**Comment by meauses** [comment]
I have the same issue, been working all day to get SickRage running. even bootstrapped my NAS and install python2.6 and such to no avail, while in the past this was never necessary. Forcing the older commit works like a charm. 
Hope they fix it soon!

**Comment by budsbenzer** [comment]
Thank you @Grimthorr !
I did a bisect search and the bug seems to have appeared in commit [c2d334b](https://github.com/SiCKRAGETV/SickRage/commit/c2d334b59e7053524005561d63881d916ee3f9de).

**Comment by fernandog** [comment]
Mine is ok (not NAS)
@miigotu can yoy check this please?

@neoatomic do you have this issue too?

**Comment by neoatomic** [comment]
No problem here. All runnings smoothly.
Did restart the NAS. Stopped/started the package. Updated Sickrage. Still no problem.

I have a DS213j and i'm running DSM 5.2-5565 Update 1 with the new Sickrage (Synocommunity) package.

```
SR Version: 	BRANCH: (develop) / COMMIT: (dd46f2ea25931e9c84e02dd688e89013481a9468)
SR User:	sickrage
SR Locale:	(None, None)
SR Config file:	/usr/local/sickrage/var/config.ini
SR Database file:	/usr/local/sickrage/var/sickbeard.db
SR Cache Dir:	/usr/local/sickrage/var/cache
SR Log Dir:	/volumeUSB4/usbshare/Temp
SR Arguments:	['--daemon', '--pidfile', '/usr/local/sickrage/var/sickrage.pid', '--config', '/usr/local/sickrage/var/config.ini', '--datadir', '/usr/local/sickrage/var/', '--nolaunch']
Python Version:	2.7.10 (default, Jun 3 2015, 17:38:42) [GCC 4.6.4]
```

**Comment by neoatomic** [comment]
Looking at the traceback errors you posted, it seems to be "db_version" that is causing the problems.?
The commit shows that this was changed in cache.db & failed.db. 

So try to remove those 2 files and see if that solves it.

**Comment by miigotu** [comment]
Already committed a fix to this, for some reason the Quality.NONE replacement was causing it to fail in failed_db.py.

**Comment by batmanraid** [comment]
Hi,

I've updated the version and the error is still there:

2015-06-13 10:05:35 DEBUG    Thread-66 :: Checking if we can use git commands: git version
2015-06-13 10:05:35 DEBUG    Thread-66 :: Executing git version with your shell in /usr/local/sickrage/var/SickRage
2015-06-13 10:05:35 DEBUG    Thread-66 :: git version : returned successful
2015-06-13 10:05:35 DEBUG    Thread-66 :: Using: git
2015-06-13 10:05:35 INFO     Thread-66 :: Config backup in progress...
2015-06-13 10:05:41 INFO     Thread-66 :: Config backup successful, updating...
2015-06-13 10:05:41 DEBUG    Thread-66 :: Executing git symbolic-ref -q HEAD with your shell in /usr/local/sickrage/var/SickRage
2015-06-13 10:05:41 DEBUG    Thread-66 :: git symbolic-ref -q HEAD : returned successful
2015-06-13 10:05:41 DEBUG    Thread-66 :: Executing git rev-parse HEAD with your shell in /usr/local/sickrage/var/SickRage
2015-06-13 10:05:41 DEBUG    Thread-66 :: git rev-parse HEAD : returned successful
2015-06-13 10:05:41 DEBUG    Thread-66 :: Executing git config remote.origin.url https://github.com/SiCKRAGETV/SickRage.git with your shell in /usr/local/sickrage/var/SickRage
2015-06-13 10:05:41 DEBUG    Thread-66 :: git config remote.origin.url https://github.com/SiCKRAGETV/SickRage.git : returned successful
2015-06-13 10:05:41 DEBUG    Thread-66 :: Executing git fetch origin with your shell in /usr/local/sickrage/var/SickRage
2015-06-13 10:05:43 DEBUG    Thread-66 :: git fetch origin : returned successful
2015-06-13 10:05:43 DEBUG    Thread-66 :: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /usr/local/sickrage/var/SickRage
2015-06-13 10:05:43 DEBUG    Thread-66 :: git rev-parse --verify --quiet "@{upstream}" : returned successful
2015-06-13 10:05:43 DEBUG    Thread-66 :: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /usr/local/sickrage/var/SickRage
2015-06-13 10:05:43 DEBUG    Thread-66 :: git rev-list --left-right "@{upstream}"...HEAD : returned successful
2015-06-13 10:05:43 DEBUG    Thread-66 :: cur_commit = 42b8d5a9c71c87fcde301967b6254ef08c3093ac, newest_commit = 68c55eadbd502c63ae35e42ccc741509e94f3d6a, num_commits_behind = 41, num_commits_ahead = 0
2015-06-13 10:05:43 DEBUG    Thread-66 :: Executing git config remote.origin.url https://github.com/SiCKRAGETV/SickRage.git with your shell in /usr/local/sickrage/var/SickRage
2015-06-13 10:05:43 DEBUG    Thread-66 :: git config remote.origin.url https://github.com/SiCKRAGETV/SickRage.git : returned successful
2015-06-13 10:05:43 DEBUG    Thread-66 :: Executing git symbolic-ref -q HEAD with your shell in /usr/local/sickrage/var/SickRage
2015-06-13 10:05:43 DEBUG    Thread-66 :: git symbolic-ref -q HEAD : returned successful
2015-06-13 10:05:43 DEBUG    Thread-66 :: Executing git pull -f origin master with your shell in /usr/local/sickrage/var/SickRage
2015-06-13 10:05:46 DEBUG    Thread-66 :: git pull -f origin master : returned successful
2015-06-13 10:05:46 DEBUG    Thread-66 :: Executing git rev-parse HEAD with your shell in /usr/local/sickrage/var/SickRage
2015-06-13 10:05:46 DEBUG    Thread-66 :: git rev-parse HEAD : returned successful
2015-06-13 10:05:46 INFO     EVENT-QUEUE :: Aborting all threads
2015-06-13 10:05:46 INFO     EVENT-QUEUE :: Waiting for the EVENTS thread to exit
2015-06-13 10:05:46 INFO     EVENT-QUEUE :: Waiting for the DAILYSEARCH thread to exit
2015-06-13 10:05:46 INFO     EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2015-06-13 10:05:47 INFO     EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2015-06-13 10:05:47 INFO     EVENT-QUEUE :: Waiting for the VERSIONCHECKER thread to exit
2015-06-13 10:05:48 INFO     EVENT-QUEUE :: Waiting for the SHOWQUEUE thread to exit
2015-06-13 10:05:48 INFO     EVENT-QUEUE :: Waiting for the SEARCHQUEUE thread to exit
2015-06-13 10:05:49 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSER thread to exit
2015-06-13 10:05:50 INFO     EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2015-06-13 10:05:51 INFO     EVENT-QUEUE :: Waiting for the TRAKTROLLING thread to exit
2015-06-13 10:05:52 INFO     EVENT-QUEUE :: Waiting for the PROPERFINDER thread to exit
2015-06-13 10:05:53 INFO     EVENT-QUEUE :: Waiting for the SUBTITLESFINDER thread to exit
2015-06-13 10:05:53 INFO     EVENT-QUEUE :: Saving all shows to the database
2015-06-13 10:05:53 DEBUG    EVENT-QUEUE :: 95491: Saving show info to database
2015-06-13 10:05:54 DEBUG    EVENT-QUEUE :: 121361: Saving show info to database
2015-06-13 10:05:54 DEBUG    EVENT-QUEUE :: 274431: Saving show info to database
2015-06-13 10:05:54 DEBUG    EVENT-QUEUE :: 247897: Saving show info to database
2015-06-13 10:05:54 DEBUG    EVENT-QUEUE :: 266883: Saving show info to database
2015-06-13 10:05:54 DEBUG    EVENT-QUEUE :: 265766: Saving show info to database
2015-06-13 10:05:54 DEBUG    EVENT-QUEUE :: 283468: Saving show info to database
2015-06-13 10:05:54 DEBUG    EVENT-QUEUE :: 276564: Saving show info to database
2015-06-13 10:05:54 DEBUG    EVENT-QUEUE :: 279121: Saving show info to database
2015-06-13 10:05:54 INFO     EVENT-QUEUE :: Saving config file to disk
2015-06-13 10:05:54 INFO     EVENT-QUEUE :: Shutting down Tornado
2015-06-13 10:05:54 INFO     EVENT-QUEUE :: Restarting SickRage with ['/usr/local/sickrage/env/bin/python', '/usr/local/sickrage/var/SickRage/SickBeard.py', '--daemon', '--pidfile', '/usr/local/sickrage/var/sickrage.pid', '--config', '/usr/local/sickrage/var/config.ini', '--datadir', '/usr/local/sickrage/var/', '--nolaunch']
2015-06-13 10:06:21 DEBUG    MAIN :: Trying to clean cache folder /usr/local/sickrage/var/cache
2015-06-13 10:06:22 DEBUG    MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S2E3 [ANIME VER: -1] [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-06-13 10:06:22 DEBUG    MAIN :: Episode has no release group, replacing it with 'RLSGROUP'
2015-06-13 10:06:22 DEBUG    MAIN :: formatting pattern: %SN - S%0SE%0E - %EN -> Show Name - S02E03 - Ep Name
2015-06-13 10:06:22 DEBUG    MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S2E3 [ANIME VER: -1] [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-06-13 10:06:22 DEBUG    MAIN :: formatting pattern: Season %0S -> Season 02
2015-06-13 10:06:22 DEBUG    MAIN :: Trying to parse Show Name - S02E03 - Ep Name.ext
2015-06-13 10:06:22 DEBUG    MAIN :: Parsed Show Name - S02E03 - Ep Name.ext into Show Name - S2E3 [ANIME VER: -1] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-06-13 10:06:22 DEBUG    MAIN :: The name Show Name - S02E03 - Ep Name.ext parsed into Show Name - S2E3 [ANIME VER: -1] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-06-13 10:06:23 DEBUG    MAIN :: Checking database structure...sickbeard.db
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Initial Schema database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: InitialSchema upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Size And Scene Name Fields database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddSizeAndSceneNameFields upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Rename Season Folders database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: RenameSeasonFolders upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add1080p And Raw Qualities database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: Add1080pAndRawHDQualities upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Showid Tvdbid Index database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddShowidTvdbidIndex upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Last Update database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddLastUpdateTVDB upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Increase To15 database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddDBIncreaseTo15 upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Db Info database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddIMDbInfo upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Proper Naming Support database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddProperNamingSupport upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Email Subscription Table database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddEmailSubscriptionTable upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Proper Search database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddProperSearch upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Dvd Order Option database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddDvdOrderOption upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Subtitles Support database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddSubtitlesSupport upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Convert Shows To Indexer Scheme database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: ConvertTVShowsToIndexerScheme upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Convert Episodes To Indexer Scheme database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: ConvertTVEpisodesToIndexerScheme upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Convert Info To Indexer Scheme database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: ConvertIMDBInfoToIndexerScheme upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Convert Info To Indexer Scheme database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: ConvertInfoToIndexerScheme upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Archive First Match Option database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddArchiveFirstMatchOption upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Scene Numbering database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddSceneNumbering upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Convert Indexer To Integer database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: ConvertIndexerToInteger upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Require And Ignore Words database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddRequireAndIgnoreWords upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Sports Option database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddSportsOption upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Scene Numbering To Tv Episodes database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddSceneNumberingToTvEpisodes upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Anime Show database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddAnimeTVShow upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Absolute Numbering database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddAbsoluteNumbering upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Scene Absolute Numbering database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddSceneAbsoluteNumbering upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Anime Blacklist Whitelist database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddAnimeBlacklistWhitelist upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Scene Absolute Numbering database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddSceneAbsoluteNumbering upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Xem Refresh database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddXemRefresh upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Scene To Tv Shows database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddSceneToTvShows upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Indexer Mapping database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddIndexerMapping upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Version To Tv Episodes database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddVersionToTvEpisodes upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Default Ep Status To Tv Shows database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddDefaultEpStatusToTvShows upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Alter Shows Field Types database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AlterTVShowsFieldTypes upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking database structure...cache.db
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Initial Schema database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: InitialSchema upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Scene Exceptions database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddSceneExceptions upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Scene Name Cache database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddSceneNameCache upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Network Timezones database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddNetworkTimezones upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Last Search database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddLastSearch upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Scene Exceptions Seasons database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddSceneExceptionsSeasons upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Scene Exceptions Custom database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddSceneExceptionsCustom upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Add Scene Exceptions Refresh database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: AddSceneExceptionsRefresh upgrade not required
2015-06-13 10:06:23 DEBUG    MAIN :: Checking database structure...failed.db
2015-06-13 10:06:23 DEBUG    MAIN :: Checking Initial Schema database upgrade
2015-06-13 10:06:23 DEBUG    MAIN :: Database upgrade required: Initial Schema
2015-06-13 10:06:23 ERROR    MAIN :: DB error: table failed already exists
Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/db.py", line 170, in action
    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/db.py", line 90, in execute
    return self._execute(query, args)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/db.py", line 78, in _execute
    return self.connection.cursor().execute(query)
OperationalError: table failed already exists
2015-06-13 10:06:23 ERROR    MAIN :: DB error: table failed already exists
Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/db.py", line 170, in action
    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/db.py", line 90, in execute
    return self._execute(query, args)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/db.py", line 78, in _execute
    return self.connection.cursor().execute(query)
OperationalError: table failed already exists

**Comment by miigotu** [comment]
delete failed.db and failed.db-journal (if it exists), make sure you are up to date, reboot

**Comment by batmanraid** [comment]
Done and running!!!

Thanks,
