### ISSUE TITLE
[APP SUBMITTED]: 'charmap' codec can't decode byte 0x9d in position 106: character maps to <undefined>

### ISSUE THREAD

**Issue by SpecialKeezie** [SiCKRAGETV/sickrage-issues#1779]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@d185980c89055f7179deec708141710ce386a572
Link to Log: https://gist.github.com/b707fa4aca1eb20c8666
### ERROR
```
Thread-28 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 1131, in update
    if sickbeard.versionCheckScheduler.action.update():
  File "C:\SickRage\sickbeard\versionChecker.py", line 269, in update
    return self.updater.update()
  File "C:\SickRage\sickbeard\versionChecker.py", line 781, in update
    notifiers.notify_git_update(sickbeard.NEWEST_VERSION_STRING)
  File "C:\SickRage\sickbeard\notifiers\__init__.py", line 111, in notify_git_update
    n.notify_git_update(new_version)
  File "C:\SickRage\sickbeard\notifiers\pushbullet.py", line 56, in notify_git_update
    self._sendPushbullet(pushbullet_api=None, event=title, message=update_text + new_version, notificationType="note", method="POST")
  File "C:\SickRage\sickbeard\notifiers\pushbullet.py", line 108, in _sendPushbullet
    logger.log(u"Pushbullet response: %s" % request_body, logger.DEBUG)
  File "C:\Python27\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 106: character maps to <undefined>

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@SpecialKeezie Looks like something go's wrong with the Pushbullet notification.
Try to re-add the account data to SR. Or are you using special characters in the account/password.?

**Comment by anzerman** [comment]
Hi, sorry I just noticed that this was here. This was occurring when renaming some episodes of "One Piece" one of the episodes that seemed to be causing an issue was "664 Start Operation SOP — Usoland Charges"  
No sure if this is relevant information or not
