### ISSUE TITLE
[APP SUBMITTED]: cannot find 'TRAKT_PIN_URL'

### ISSUE THREAD

**Issue by jantograaf** [SiCKRAGETV/sickrage-issues#1782]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@d185980c89055f7179deec708141710ce386a572
Link to Log: https://gist.github.com/88ee92c5eee86c302087
### ERROR
```
Thread-661 :: Failed doing webui callback: Traceback (most recent call last):
  File "c:\SickRage\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "c:\SickRage\sickbeard\webserve.py", line 4599, in index
    @route('/config/notifications(/?.*)')
  File "c:\SickRage\cache\cheetah\_SickRage_gui_slick_interfaces_default_config_notifications_tmpl.py", line 2336, in respond
    _v = VFSL([locals()]+SL+[globals(), builtin],"sickbeard.TRAKT_PIN_URL",True) # u'$sickbeard.TRAKT_PIN_URL' on line 1451, col 76
  File "C:\Python27\lib\site-packages\Cheetah\NameMapper.py", line 245, in valueFromSearchList
    executeCallables=executeCallables)
  File "C:\Python27\lib\site-packages\Cheetah\NameMapper.py", line 226, in _valueForName
    _raiseNotFoundException(key, obj)
  File "C:\Python27\lib\site-packages\Cheetah\NameMapper.py", line 167, in _raiseNotFoundException
    raise NotFound(excString)
NotFound: cannot find 'TRAKT_PIN_URL'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Thraxis** [comment]
Stop your sickrage and then delete the files in the c:\SickRage\cache\cheetah\ folder then restart sickrage again
