### ISSUE TITLE
[APP SUBMITTED]: 'result' - Post Processing is failing

### ISSUE THREAD

**Issue by Cybernetic-Revolt** [SiCKRAGETV/sickrage-issues#1786]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-32-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@d185980c89055f7179deec708141710ce386a572
Link to Log: https://gist.github.com/f6d6e5fefdaa06c998aa
### ERROR
```
Thread-94 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/bilco/sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/bilco/sickrage/sickbeard/webserve.py", line 2174, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/home/bilco/sickrage/sickbeard/processTV.py", line 250, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/home/bilco/sickrage/sickbeard/processTV.py", line 501, in process_media
    result.result = processor.process()
  File "/home/bilco/sickrage/sickbeard/postProcessor.py", line 1075, in process
    notifiers.notify_download(ep_obj._format_pattern('%SN - %Sx%0E - %EN - %QN'))
  File "/home/bilco/sickrage/sickbeard/notifiers/__init__.py", line 96, in notify_download
    n.notify_download(ep_name)
  File "/home/bilco/sickrage/sickbeard/notifiers/kodi.py", line 511, in notify_download
    self._notify_kodi(ep_name, common.notifyStrings[common.NOTIFY_DOWNLOAD])
  File "/home/bilco/sickrage/sickbeard/notifiers/kodi.py", line 132, in _notify_kodi
    kodiapi = self._get_kodi_version(curHost, username, password)
  File "/home/bilco/sickrage/sickbeard/notifiers/kodi.py", line 85, in _get_kodi_version
    return result["result"]["version"]
KeyError: 'result'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Post processing is not actually failing. Your kodi setting or sr settings for kodi notifications are wrong. You get the error because it cannot notify kodi.

Kodi notifications work here: https://gist.github.com/miigotu/02e0e8bfb30d0f8747cb
