### ISSUE TITLE
[APP SUBMITTED]: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/273181/en.xml

### ISSUE THREAD

**Issue by mbnoimi** [SiCKRAGETV/sickrage-issues#1797]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-18-generic-x86_64-with-LinuxMint-17.1-rebecca**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@f9246bcfdb95929e95e5f422d577fc9aa7d69953
Link to Log: https://gist.github.com/7961842f128a09ff1ab4
### ERROR
```
Thread-85 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/mbnoimi/.sickrage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/mbnoimi/.sickrage/sickbeard/webserve.py", line 2174, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/home/mbnoimi/.sickrage/sickbeard/processTV.py", line 203, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/home/mbnoimi/.sickrage/sickbeard/processTV.py", line 501, in process_media
    result.result = processor.process()
  File "/home/mbnoimi/.sickrage/sickbeard/postProcessor.py", line 1069, in process
    ep_obj.createMetaFiles()
  File "/home/mbnoimi/.sickrage/sickbeard/tv.py", line 1916, in createMetaFiles
    self.createThumbnail()
  File "/home/mbnoimi/.sickrage/sickbeard/tv.py", line 1935, in createThumbnail
    result = cur_provider.create_episode_thumb(self) or result
  File "/home/mbnoimi/.sickrage/sickbeard/metadata/generic.py", line 332, in create_episode_thumb
    return self.save_thumbnail(ep_obj)
  File "/home/mbnoimi/.sickrage/sickbeard/metadata/generic.py", line 499, in save_thumbnail
    thumb_url = self._get_episode_thumb_url(ep_obj)
  File "/home/mbnoimi/.sickrage/sickbeard/metadata/generic.py", line 386, in _get_episode_thumb_url
    myEp = helpers.validateShow(cur_ep.show, cur_ep.season, cur_ep.episode)
  File "/home/mbnoimi/.sickrage/sickbeard/helpers.py", line 1046, in validateShow
    return t[show.indexerid][season][episode]
  File "/home/mbnoimi/.sickrage/lib/tvdb_api/tvdb_api.py", line 948, in __getitem__
    self._getShowData(key, self.config['language'], True)
  File "/home/mbnoimi/.sickrage/lib/tvdb_api/tvdb_api.py", line 843, in _getShowData
    self.config['url_seriesInfo'] % (sid, getShowInLanguage)
  File "/home/mbnoimi/.sickrage/lib/tvdb_api/tvdb_api.py", line 632, in _getetsrc
    raise tvdb_error(e)
tvdb_error: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/273181/en.xml

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@mbnoimi I have this show myself and no problems. Looking at the log it unable to connect. "Unable to connect to theTVDB"
Are you using proxy's or similar.? Or maybe a bad Internet connection.?

Also i see you use oldpiratebay, but that doesnt work anymore. it redirects to Kickass torrents.

**Comment by miigotu** [comment]
Lets remove it! xD
