### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by ctindel** [SiCKRAGETV/sickrage-issues#1801]
I tried master as well as the develop branch.  Here's a log:
```
2015-06-11 22:11:37 DEBUG    Thread-62 :: Searching for Show with searchterm: west wing on Indexer: TVRage
2015-06-11 22:11:42 ERROR    SEARCHQUEUE-BACKLOG-78956 :: [dognzb.cr] :: Error while searching dognzb.cr, skipping: 'module' object is not callable
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 473, in searchProviders
    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/generic.py", line 342, in findSearchResults
    parse_result = myParser.parse(title)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/name_parser/parser.py", line 417, in parse
    file_name_result = self._parse_string(base_file_name)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/name_parser/parser.py", line 248, in _parse_string
    logger.log(u"Unable to contact " + sickbeard.indexerApi(bestResult.show.indexer).name + ": " + ex(e), logger.WARNING)
TypeError: 'module' object is not callable
2015-06-11 22:11:42 DEBUG    SEARCHQUEUE-BACKLOG-78956 :: [dognzb.cr] :: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 473, in searchProviders
    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/generic.py", line 342, in findSearchResults
    parse_result = myParser.parse(title)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/name_parser/parser.py", line 417, in parse
    file_name_result = self._parse_string(base_file_name)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/name_parser/parser.py", line 248, in _parse_string
    logger.log(u"Unable to contact " + sickbeard.indexerApi(bestResult.show.indexer).name + ": " + ex(e), logger.WARNING)
TypeError: 'module' object is not callable
```

**Comment by miigotu** [comment]
dognzb.cr is redirecting to wikipedia? lol

**Comment by neoatomic** [comment]
@ctindel Follow the guidelines for posing an issue. : https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

@miigotu http://www.reddit.com/r/usenet/comments/37m7sy/dognzbcr_redirecting_to_wiki_page/

**Comment by ctindel** [comment]
@neoatomic Actually the issue I was trying to post was that adding a new show didn't work.  It just timed out when searching.  I restored to a version that was 23 commits out of date and it started working again.

I thought maybe the log messages were related or something.

**Comment by neoatomic** [comment]
@ctindel Ok, i will close this than. Thanks for letting us know.
