### ISSUE TITLE
[APP SUBMITTED]: 'ascii' codec can't encode character u'\u2019' in position 90: ordinal not in range(128)

### ISSUE THREAD

**Issue by LennyM8472** [SiCKRAGETV/sickrage-issues#1822]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@e6c4cfd6546b74d5527361f6f0bdc3adc232bdb0
No Log available with ERRORS: 
### ERROR
```
Thread-47 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 2174, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/processTV.py", line 250, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/processTV.py", line 498, in process_media
    result.result = processor.process()
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/postProcessor.py", line 1076, in process
    cur_ep.airdateModifyStamp()
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/tv.py", line 2613, in airdateModifyStamp
    filemtime = datetime.datetime.fromtimestamp(os.path.getmtime(self.location)).replace(tzinfo=tzlocal())
  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 90: ordinal not in range(128)

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@LennyM8472 check the user SR is running in localhost:8081/config and set locale to UTF-8 for that user

https://sickrage.tv/forums/forum/help-support/general-support/12825-ensuring-your-locale-s-are-set-properly-to-avoid-unicode-issues

**Comment by uraza** [comment]
I have a similar issue on my side:
```
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 14: ordinal not in range(128)
```

Locales seem to be set correctly on my user account (which is the one running SR):
```
LANG=fr_FR.UTF-8
LANGUAGE=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=fr_FR.UTF-8
```
