### ISSUE TITLE
Post processing error

### ISSUE THREAD

**Issue by tresni** [SiCKRAGETV/sickrage-issues#1835]
Branch: master
Commit: e6c4cfd6546b74d5527361f6f0bdc3adc232bdb0
OS: OSX 10.10.3
**Steps to Reproduce:**
1. Restart sickrage or wait for postprocessing to start

**What I expect to happen:**
1. Post processing

**What actually happens:**
1. Dies with that error, no post processing or worker threads run from that point forward until I restart SickRage

```
10:15:05 ERROR::POSTPROCESSER :: Exception generated in thread POSTPROCESSER: 'module' object is not callable
Traceback (most recent call last):
  File "/opt/software/TPB/sickbeard/scheduler.py", line 97, in run
    self.action.run(self.force)
  File "/opt/software/TPB/sickbeard/autoPostProcesser.py", line 50, in run
    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR)
  File "/opt/software/TPB/sickbeard/processTV.py", line 217, in processDir
    if (not validateDir(path, processPath, nzbNameOriginal, failed, result)):
  File "/opt/software/TPB/sickbeard/processTV.py", line 336, in validateDir
    NameParser().parse(video, cache_result=False)
  File "/opt/software/TPB/sickbeard/name_parser/parser.py", line 417, in parse
    file_name_result = self._parse_string(base_file_name)
  File "/opt/software/TPB/sickbeard/name_parser/parser.py", line 248, in _parse_string
    logger.log(u"Unable to contact " + sickbeard.indexerApi(bestResult.show.indexer).name + ": " + ex(e), logger.WARNING)
TypeError: 'module' object is not callable
```

**Comment by tresni** [comment]
Problem is that you import `ex` as a module.

```python
from sickbeard import logger, helpers, scene_numbering, common, exceptions as ex, scene_exceptions, encodingKludge as ek, db
```

Then you later try to call it as a module...  Either import ex from exceptions (vs as):
```diff
diff --git a/sickbeard/name_parser/parser.py b/sickbeard/name_parser/parser.py
index e2ad166..e13b4eb 100644
--- a/sickbeard/name_parser/parser.py
+++ b/sickbeard/name_parser/parser.py
@@ -26,7 +26,8 @@ import os.path
 import regexes
 import sickbeard

-from sickbeard import logger, helpers, scene_numbering, common, exceptions as ex, scene_exceptions, encodingKludge as ek, db
+from sickbeard import logger, helpers, scene_numbering, common, scene_exceptions, encodingKludge as ek, db
+from sickbeard.exceptions import ex
 from dateutil import parser
```

Or call the class from the module:
```diff
diff --git a/sickbeard/name_parser/parser.py b/sickbeard/name_parser/parser.py
index e2ad166..93ce698 100644
--- a/sickbeard/name_parser/parser.py
+++ b/sickbeard/name_parser/parser.py
@@ -245,7 +245,7 @@ class NameParser(object):
                         logger.log(u"Unable to find episode with date " + str(bestResult.air_date) + " for show " + bestResult.show.name + ", skipping", logger.WARNING)
                         episode_numbers = []
                     except sickbeard.indexer_error, e:
-                        logger.log(u"Unable to contact " + sickbeard.indexerApi(bestResult.show.indexer).name + ": " + ex(e), logger.WARNING)
+                        logger.log(u"Unable to contact " + sickbeard.indexerApi(bestResult.show.indexer).name + ": " + ex.ex(e), logger.WARNING)
                         episode_numbers = []

                 for epNo in episode_numbers:
```

**Comment by tresni** [comment]
(Did not mean to close...)

**Comment by fernandog** [comment]
Feel free to make a PR in develop

**Comment by neoatomic** [comment]
@tresni Thanks for contributing. 
As this is merged now, the issue can be closed.
