### ISSUE TITLE
[APP SUBMITTED]: 79337: Could not refresh subtitles

### ISSUE THREAD

**Issue by cgram23** [SiCKRAGETV/sickrage-issues#1880]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-39-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@2d515e9aa4aea0ec1798289df691cd5e949828ed
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-REFRESH :: 79337: Could not refresh subtitles
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Logs please.?

**Comment by fernandog** [comment]
@miigotu maybe we don't have log with errors because DEBUG is disabled. can be that?

**Comment by cgram23** [comment]
Here's the relevant traceback.  Let me know if you need any other information:

2015-06-24 10:51:26 DEBUG    SHOWQUEUE-REFRESH :: 79337: Not creating SQL queue - record is not dirty
2015-06-24 10:51:26 DEBUG    SHOWQUEUE-REFRESH :: 79337: Creating episode from /mnt/Media/DVR/Friday Night Lights/Friday Night Lights - 1x19 - Ch-Ch-Ch-Ch-Changes.mp4
2015-06-24 10:51:26 DEBUG    SHOWQUEUE-REFRESH :: 79337: Creating episode object from /mnt/Media/DVR/Friday Night Lights/Friday Night Lights - 1x19 - Ch-Ch-Ch-Ch-Changes.mp4
2015-06-24 10:51:26 DEBUG    SHOWQUEUE-REFRESH :: Parsed /mnt/Media/DVR/Friday Night Lights/Friday Night Lights - 1x19 - Ch-Ch-Ch-Ch-Changes.mp4 into Friday Night Lights - S1E19 [ANIME VER: -1] [GROUP: Changes] [ABD: False] [ANIME: False] [whichReg: ['fov']]
2015-06-24 10:51:26 DEBUG    SHOWQUEUE-REFRESH :: 79337: /mnt/Media/DVR/Friday Night Lights/Friday Night Lights - 1x19 - Ch-Ch-Ch-Ch-Changes.mp4 parsed to Friday Night Lights 1x19
2015-06-24 10:51:26 DEBUG    SHOWQUEUE-REFRESH :: 79337: An object for episode 1x19 didn't exist in the cache, trying to create it
2015-06-24 10:51:26 DEBUG    SHOWQUEUE-REFRESH :: 79337: Loading episode details from DB for episode 1x19
2015-06-24 10:51:26 DEBUG    SHOWQUEUE-REFRESH :: Setter sets location to /mnt/Media/DVR/Friday Night Lights/Friday Night Lights - 1x19 - Ch-Ch-Ch-Ch-Changes.mp4
2015-06-24 10:51:26 DEBUG    SHOWQUEUE-REFRESH :: Setter sets location to /mnt/Media/DVR/Friday Night Lights/Friday Night Lights - 1x19 - Ch-Ch-Ch-Ch-Changes.mp4
2015-06-24 10:51:26 DEBUG    SHOWQUEUE-REFRESH :: 79337: Not creating SQL queue - record is not dirty
2015-06-24 10:51:26 DEBUG    SHOWQUEUE-REFRESH :: Transaction with 0 queries executed
2015-06-24 10:51:26 DEBUG    SHOWQUEUE-REFRESH :: Parsed Friday Night Lights - 1x19 - Ch-Ch-Ch-Ch-Changes into Friday Night Lights - S1E19 [ANIME VER: -1] [GROUP: Changes] [ABD: False] [ANIME: False] [whichReg: ['fov']]
2015-06-24 10:51:26 ERROR    SHOWQUEUE-REFRESH :: 79337: Could not refresh subtitles
Traceback (most recent call last):
  File "/home/chris/.sickrage/sickbeard/tv.py", line 455, in loadEpisodesFromDir
    curEpisode.refreshSubtitles()
  File "/home/chris/.sickrage/sickbeard/tv.py", line 1422, in refreshSubtitles
    self.subtitles = subtitles.subtitlesLanguages(self.location)
  File "/home/chris/.sickrage/sickbeard/subtitles.py", line 70, in subtitlesLanguages
    video = subliminal.videos.Video.from_path(video_path)
  File "/home/chris/.sickrage/lib/subliminal/videos.py", line 85, in from_path
    guess = guessit.guess_file_info(path, 'autodetect')
  File "/home/chris/.sickrage/lib/guessit/__init__.py", line 210, in guess_file_info
    result.append(_guess_filename(filename, filetype))
  File "/home/chris/.sickrage/lib/guessit/__init__.py", line 138, in _guess_filename
    title2 = next(find_nodes(mtree2.match_tree, 'title'))
StopIteration
2015-06-24 10:51:26 DEBUG    SHOWQUEUE-REFRESH :: Traceback (most recent call last):
  File "/home/chris/.sickrage/sickbeard/tv.py", line 455, in loadEpisodesFromDir
    curEpisode.refreshSubtitles()
  File "/home/chris/.sickrage/sickbeard/tv.py", line 1422, in refreshSubtitles
    self.subtitles = subtitles.subtitlesLanguages(self.location)
  File "/home/chris/.sickrage/sickbeard/subtitles.py", line 70, in subtitlesLanguages
    video = subliminal.videos.Video.from_path(video_path)
  File "/home/chris/.sickrage/lib/subliminal/videos.py", line 85, in from_path
    guess = guessit.guess_file_info(path, 'autodetect')
  File "/home/chris/.sickrage/lib/guessit/__init__.py", line 210, in guess_file_info
    result.append(_guess_filename(filename, filetype))
  File "/home/chris/.sickrage/lib/guessit/__init__.py", line 138, in _guess_filename
    title2 = next(find_nodes(mtree2.match_tree, 'title'))
StopIteration

**Comment by fernandog** [comment]
@cgram23 this episode has a bad naming. download manually

https://github.com/SiCKRAGETV/sickrage-issues/issues/1031
