### ISSUE TITLE
[APP SUBMITTED]: Proper instance has no attribute 'resultType'

### ISSUE THREAD

**Issue by mcmikev** [SiCKRAGETV/sickrage-issues#1889]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@207bd7ac693e4beee0b72d4d3a05e0c7aca95300
No Log available with ERRORS: 
### ERROR
```
FINDPROPERS :: Exception generated in thread FINDPROPERS: Proper instance has no attribute 'resultType'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dirkr07** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  4 2015, 00:30:19) [GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@207bd7ac693e4beee0b72d4d3a05e0c7aca95300
Link to Log: https://gist.github.com/a8bf64150037169573b4
### ERROR
```
FINDPROPERS :: Exception generated in thread FINDPROPERS: Proper instance has no attribute 'resultType'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Full log please. Traceback isn't in that log.

**Comment by dirkr07** [comment]
```
2015-06-25 09:27:55 DEBUG    FINDPROPERS :: 'Traceback (most recent call last):\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/scheduler.py", line 97, in run\n    self.action.run(self.force)\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/properFinder.py", line 48, in run\n    propers = self._getProperList()\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/properFinder.py", line 145, in _getProperList\n    bestResult = pickBestResult(curProper, parse_result.show)\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 239, in pickBestResult\n    if cur_result.resultType == "torrent" and sickbeard.TORRENT_METHOD != "blackhole":\nAttributeError: Proper instance has no attribute \'resultType\'\n'
AAAttributeError: Proper instance has no attribute 'resultType'
AA    if cur_result.resultType == "torrent" and sickbeard.TORRENT_METHOD != "blackhole":
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 239, in pickBestResult
AA    bestResult = pickBestResult(curProper, parse_result.show)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/properFinder.py", line 145, in _getProperList
AA    propers = self._getProperList()
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/properFinder.py", line 48, in run
AA    self.action.run(self.force)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/scheduler.py", line 97, in run
AATraceback (most recent call last):
2015-06-25 09:27:55 ERROR    FINDPROPERS :: Exception generated in thread FINDPROPERS: Proper instance has no attribute 'resultType'
2015-06-25 09:27:55 INFO     FINDPROPERS :: Quality of Suits.S05E01.REPACK.HDTV.x264-KILLERS.mp4 is SDTV
2015-06-25 09:27:55 DEBUG    FINDPROPERS :: Picking the best result out of [u'Suits.S05E01.REPACK.HDTV.x264-KILLERS.mp4']
2015-06-25 09:27:55 DEBUG    FINDPROPERS :: Successful match! Result Suits.S05E01.REPACK.HDTV.x264-KILLERS.mp4 matched to show Suits
2015-06-25 09:27:55 DEBUG    FINDPROPERS :: Parsed Suits.S05E01.REPACK.HDTV.x264-KILLERS.mp4 into Suits - S5E1 [ANIME VER: -1] [GROUP: KILLERS.mp4] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-06-25 09:27:54 DEBUG    FINDPROPERS :: [TorrentDay] :: No torrents found in JSON for Deadliest.Catch+S11E11+PROPER|REPACK
2015-06-25 09:27:53 DEBUG    FINDPROPERS :: [TorrentDay] :: Search string: Deadliest.Catch S11E11 PROPER|REPACK
2015-06-25 09:27:53 DEBUG    FINDPROPERS :: [TorrentDay] :: No torrents found in JSON for Rizzoli.and.Isles+S06E02+PROPER|REPACK
2015-06-25 09:27:53 DEBUG    FINDPROPERS :: [TorrentDay] :: Search string: Rizzoli.and.Isles S06E02 PROPER|REPACK
2015-06-25 09:27:53 DEBUG    FINDPROPERS :: [TorrentDay] :: No torrents found in JSON for Stitchers+S01E04+PROPER|REPACK
2015-06-25 09:27:52 DEBUG    FINDPROPERS :: [TorrentDay] :: Search string: Stitchers S01E04 PROPER|REPACK
2015-06-25 09:27:51 INFO     FINDPROPERS :: [TorrentDay] :: Searching for any new PROPER releases from TorrentDay
2015-06-25 09:27:51 DEBUG    FINDPROPERS :: Found new proper: Suits.S05E01.REPACK.HDTV.x264-KILLERS.mp4
2015-06-25 09:27:51 DEBUG    FINDPROPERS :: Found new proper: Suits.S05E01.REPACK.720p.HDTV.x264-KILLERS.mkv
2015-06-25 09:27:51 INFO     FINDPROPERS :: [Shazbat.tv] :: Searching for any new PROPER releases from Shazbat.tv
2015-06-25 09:27:51 INFO     FINDPROPERS :: Beginning the search for new propers
2015-06-25 09:27:51 DEBUG    FINDPROPERS :: Starting new thread: FINDPROPERS
```

**Comment by miigotu** [comment]
Found it, pushing shortly.
