### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: 'lib/network_timezones/zoneinfo.txt'

### ISSUE THREAD

**Issue by neoatomic** [SiCKRAGETV/sickrage-issues#1892]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 17:38:42) [GCC 4.6.4]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@33f51a24c6a274e92cf431a32fda9c723e3d0cbd
Link to Log: https://gist.github.com/3b1788a4d8173b8fc983
http://pastebin.com/VtEbsKnp

### ERROR
```
DAILYSEARCHER :: Crazy problem with zoneinfo: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Just updated on Develop. Got 2 errors. :large_blue_circle: 

```
2015-06-25 15:59:07 INFO     SEARCHQUEUE-BACKLOG-23281 :: Beginning backlog search for: [Pawn Star$]
2015-06-25 15:59:07 INFO     SEARCHQUEUE-BACKLOG-23281 :: Checking for scene exception updates for theTVDB
2015-06-25 15:59:07 DEBUG    SEARCHQUEUE-BACKLOG-23281 :: Traceback (most recent call last):
  File "/volume1/@appstore/********/var/SickRage/sickbeard/search_queue.py", line 221, in run
    searchResult = search.searchProviders(self.show, self.segment, False)
  File "/volume1/@appstore/********/var/SickRage/sickbeard/search.py", line 435, in searchProviders
    sickbeard.name_cache.buildNameCache(show)
  File "/volume1/@appstore/********/var/SickRage/sickbeard/name_cache.py", line 87, in buildNameCache
    sickbeard.scene_exceptions.retrieve_exceptions()
  File "/volume1/@appstore/********/var/SickRage/sickbeard/scene_exceptions.py", line 179, in retrieve_exceptions
    with open(loc, 'r') as file:
IOError: [Errno 2] No such file or directory: 'lib/scene_exceptions/tvdb/exceptions.txt'
```
```
2015-06-25 15:58:51 DEBUG    CHECKVERSION :: Starting new thread: CHECKVERSION
2015-06-25 15:58:51 INFO     CHECKVERSION :: Checking for updates using GIT
2015-06-25 15:58:51 DEBUG    CHECKVERSION :: Executing git symbolic-ref -q HEAD with your shell in /usr/local/********/var/SickRage
2015-06-25 15:58:51 DEBUG    BACKLOG :: Nothing needs to be downloaded for Black Sails, skipping
2015-06-25 15:58:52 DEBUG    BACKLOG :: Seeing if we need anything from Game of Thrones
2015-06-25 15:58:52 ERROR    DAILYSEARCHER :: Crazy problem with zoneinfo: error 2 : No such file or directory
Traceback (most recent call last):
  File "/volume1/@appstore/********/var/SickRage/sickbeard/network_timezones.py", line 82, in _update_zoneinfo
    with open(loc_zv, 'r') as file:
IOError: [Errno 2] No such file or directory: 'lib/network_timezones/zoneinfo.txt'
2015-06-25 15:58:52 DEBUG    BACKLOG :: Nothing needs to be downloaded for Game of Thrones, skipping
2015-06-25 15:58:52 DEBUG    BACKLOG :: Seeing if we need anything from Da Vinci's Demons
2015-06-25 15:58:52 ERROR    DAILYSEARCHER :: Exception generated in thread DAILYSEARCHER: error 2 : No such file or directory
Traceback (most recent call last):
  File "/volume1/@appstore/********/var/SickRage/sickbeard/scheduler.py", line 97, in run
    self.action.run(self.force)
  File "/volume1/@appstore/********/var/SickRage/sickbeard/dailysearcher.py", line 47, in run
    network_timezones.update_network_dict()
  File "/volume1/@appstore/********/var/SickRage/sickbeard/network_timezones.py", line 157, in update_network_dict
    with open(loc, 'r') as file:
IOError: [Errno 2] No such file or directory: 'lib/network_timezones/network_timezones.txt'
```

**Comment by miigotu** [comment]
Need to prepend the sickrage.PROG_DIR to the paths, I'll do it when I get home.

**Comment by miigotu** [comment]
SiCKRAGETV/SickRage#2008

**Comment by neoatomic** [comment]
@miigotu Updated and the errors are gone/SR is restarting fine.
Thanks.!
