### ISSUE TITLE
[APP SUBMITTED]: 'ascii' codec can't encode character u'\xe9' in position 63: ordinal not in range(128)

### ISSUE THREAD

**Issue by fairwood136** [SiCKRAGETV/sickrage-issues#1914]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@ae2c0e8006bf0c8ec3d3379148a951847b2c5f39
Link to Log: https://gist.github.com/bef407ebd2c6445a05c0
### ERROR
```
Thread-42 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 2174, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 251, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 499, in process_media
    result.result = processor.process()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/postProcessor.py", line 913, in process
    if not helpers.isFileLocked(self.file_path, False):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/helpers.py", line 1653, in isFileLocked
    if(not(os.path.exists(file))):
  File "/usr/pbi/sickrage-amd64/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 63: ordinal not in range(128)

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Problem are the special characters in "Déjà"

https://sickrage.tv/forums/forum/help-support/general-support/12825-ensuring-your-locale-s-are-set-properly-to-avoid-unicode-issues
