### ISSUE TITLE
[APP SUBMITTED]: 'module' object has no attribute 'language'

### ISSUE THREAD

**Issue by matigonkas** [SiCKRAGETV/sickrage-issues#1917]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-21-generic-i686-with-Ubuntu-15.04-vivid**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@0f0c920d22788a7609170f069f4283e2908ed430
Link to Log: https://gist.github.com/466269b0aa618eb4320d
### ERROR
```
Thread-14 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 4849, in index
    return t.respond()
  File "/home/supergonkas/SickRage/cache/cheetah/_home_supergonkas_SickRage_gui_slick_interfaces_default_config_subtitles_tmpl.py", line 122, in respond
    write(_filter(",\r\n".join("{id: \"" + lang[2] + "\", name: \"" + lang[3] + "\"}" for lang in subtitles.subtitleLanguageFilter())))
  File "/home/supergonkas/SickRage/sickbeard/subtitles.py", line 82, in subtitleLanguageFilter
    return [language for language in subliminal.language.LANGUAGES if language[2] != ""]
AttributeError: 'module' object has no attribute 'language'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by matigonkas** [comment]
happened when opening the Subtitle settings" page

**Comment by matigonkas** [comment]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-21-generic-i686-with-Ubuntu-15.04-vivid**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@0f0c920d22788a7609170f069f4283e2908ed430
Link to Log: https://gist.github.com/954cf195604b1f3e03a4
### ERROR
```
Thread-41 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 1296, in displayShow
    return t.respond()
  File "/home/supergonkas/SickRage/cache/cheetah/_home_supergonkas_SickRage_gui_slick_interfaces_default_displayShow_tmpl.py", line 1336, in respond
    for sub_lang in subliminal.language.language_list([x.strip() for x in VFN(VFFSL(SL,"epResult",True)["subtitles"],"split",False)(',') if x != ""]): # generated from line 582, col 17
AttributeError: 'module' object has no attribute 'language'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by matigonkas** [comment]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-21-generic-i686-with-Ubuntu-15.04-vivid**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@0f0c920d22788a7609170f069f4283e2908ed430
Link to Log: https://gist.github.com/71a5f409c6f75cd2f90a
### ERROR
```
Thread-42 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 1296, in displayShow
    return t.respond()
  File "/home/supergonkas/SickRage/cache/cheetah/_home_supergonkas_SickRage_gui_slick_interfaces_default_displayShow_tmpl.py", line 1336, in respond
    for sub_lang in subliminal.language.language_list([x.strip() for x in VFN(VFFSL(SL,"epResult",True)["subtitles"],"split",False)(',') if x != ""]): # generated from line 582, col 17
AttributeError: 'module' object has no attribute 'language'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by matigonkas** [comment]
It also happens when opnng a show page with subtitles already downloaded

**Comment by cyberundertaker** [comment]
@fernandog @abeloin 
I'm having the same error:

2015-06-29 02:41:56 Thread-57 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\Users\Hanibanz\Desktop\SickRage-develop\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\Users\Hanibanz\Desktop\SickRage-develop\sickbeard\webserve.py", line 4849, in index
    return t.respond()
  File "C:\Users\Hanibanz\Desktop\SickRage-develop\cache\cheetah\_Users_Hanibanz_Desktop_SickRage_develop_gui_slick_interfaces_default_config_subtitles_tmpl.py", line 122, in respond
    write(_filter(",\r\n".join("{id: \"" + lang[2] + "\", name: \"" + lang[3] + "\"}" for lang in subtitles.subtitleLanguageFilter())))
  File "C:\Users\Hanibanz\Desktop\SickRage-develop\sickbeard\subtitles.py", line 82, in subtitleLanguageFilter
    return [language for language in subliminal.language.LANGUAGES if language[2] != ""]
AttributeError: 'module' object has no attribute 'language'

2015-06-29 02:41:49 Thread-48 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\Users\Hanibanz\Desktop\SickRage-develop\sickbeard\webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "C:\Users\Hanibanz\Desktop\SickRage-develop\sickbeard\webserve.py", line 1296, in displayShow
    return t.respond()
  File "C:\Users\Hanibanz\Desktop\SickRage-develop\cache\cheetah\_Users_Hanibanz_Desktop_SickRage_develop_gui_slick_interfaces_default_displayShow_tmpl.py", line 1336, in respond
    for sub_lang in subliminal.language.language_list([x.strip() for x in VFN(VFSL([locals()]+SL+[globals(), builtin],"epResult",True)["subtitles"],"split",False)(',') if x != ""]): # generated from line 582, col 17
AttributeError: 'module' object has no attribute 'language'


I can't enter in any show to see the episode list, and also can't enter the subtitle settings...in both cases it returns to home screen.
I tried changing "use subtitle" in config.ini from 1 to 0, but the problem is still here.

FYI:
SR Version:	BRANCH: (develop) / COMMIT: (45dcc74fe1e3cef00be7930a88fee4b1439e01e2) 
Python Version:	2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]
OS: Win 7

**Comment by miigotu** [comment]
I am mid-upgrade to the new subliminal, which is why you get these errors.
