### ISSUE TITLE
Kickasstorrents stopped working for me

### ISSUE THREAD

**Issue by ersenosman** [SiCKRAGETV/sickrage-issues#1920]
BRANCH: (master) / COMMIT: (ae2c0e8006bf0c8ec3d3379148a951847b2c5f39) 
Using sickrage and downloadstation on DSM
pyphon 2.7.10-14

Ive been getting this error today, i can download the file using a torrent and magnet file from KAT but when i try to do it in sickrage it just wont send it

all other providers are happily sending to downloadstation for download

2015-06-28 21:22:58 DEBUG    SEARCHQUEUE-MANUAL-291965 :: DownloadStation: Exception raised when sending torrent: KickAssTorrents @ http://torcache.net/torrent/60E300176DAC94DEBCACE4344A95A662F0FB61BE.torrent
AAUnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 24: invalid start byte
AA    return codecs.utf_8_decode(input, errors, True)
AA  File "/usr/local/sickbeard-custom/env/lib/python2.7/encodings/utf_8.py", line 16, in decode
AA    message = meThread + u" :: " + msg
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/logger.py", line 133, in log
AA    logger.log('Torrent bencoded data: {0}'.format(str(result.content)), logger.DEBUG)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/clients/generic.py", line 160, in _get_torrent_hash
AA    result = self._get_torrent_hash(result)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/clients/generic.py", line 186, in sendTORRENT
AATraceback (most recent call last):
2015-06-28 21:22:58 ERROR    SEARCHQUEUE-MANUAL-291965 :: DownloadStation: Failed Sending Torrent
AABTFailure: not a valid bencoded string
AA    raise BTFailure("not a valid bencoded string")
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/bencode/bencode.py", line 68, in bdecode
AA    torrent_bdecode = bdecode(result.content)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/clients/generic.py", line 157, in _get_torrent_hash
AATraceback (most recent call last):
2015-06-28 21:22:58 ERROR    SEARCHQUEUE-MANUAL-291965 :: Unable to bdecode torrent
2015-06-28 21:22:57 DEBUG    SEARCHQUEUE-MANUAL-291965 :: Calling DownloadStation Client

**Comment by Morphello** [comment]
Same issue here. "Unable to bdecode torrent"

I believe it might be related to Proxy settings. After disabling the proxy, restarting, it seems to be working again for me.

**Comment by ersenosman** [comment]
ah thanks for that, i had to edit the kat.py file and change it to http://kickass.proxyindex.net/ as kat is blocked with my provider (btopenworld)

all works now

thanks again

**Comment by Morphello** [comment]
Well it's still broken for me if I have proxies enabled. Default KAT isn't blocked via my ISP, but for added security, was using the in build proxies. All of which cause issues.

**Comment by fernandog** [comment]
Use rarbg. Better than kat

**Comment by Morphello** [comment]
How is it better than KAT? Ignoring the fact that the first 3 shows I attempted to search for weren't available on the site, the actual provider isn't working at all.

http://i.imgur.com/6pibwDQ.png

I can see the actual episode I want to download, but it can't. For that matter, I'm not sure why piratebay isn't working either. The only criteria for the episodes is "SD" and "5 seeds minimum".

Selecting KAT provides me with the same episodes but actually downloads them.

2015-06-29 20:03:51 INFO     SHOWQUEUE-REFRESH :: Performing refresh on Defiance
AA
AA
AA
2015-06-29 20:03:40 INFO     SEARCHQUEUE-MANUAL-255326 :: Downloading Defiance.S02E04.HDTV.x264-2HD from KickAssTorrents
2015-06-29 20:03:39 INFO     SEARCHQUEUE-MANUAL-255326 :: Quality of Defiance.S02E04.HDTV.x264-2HD.[VTV].mp4 is SDTV
2015-06-29 20:03:38 INFO     SEARCHQUEUE-MANUAL-255326 :: Quality of Defiance.S02E04.HDTV.x264-2HD[ettv] is SDTV
2015-06-29 20:03:38 INFO     SEARCHQUEUE-MANUAL-255326 :: Quality of Defiance.S02E04.HDTV.x264-2HD is SDTV
2015-06-29 20:03:37 INFO     SEARCHQUEUE-MANUAL-255326 :: Quality of Defiance.S02E04.HDTV.x264-2HD[rartv] is SDTV
2015-06-29 20:03:36 INFO     SEARCHQUEUE-MANUAL-255326 :: Quality of Defiance.S02E04.HDTV.x264-2HD.[eztv] is SDTV
2015-06-29 20:03:35 INFO     SEARCHQUEUE-MANUAL-255326 :: Quality of Defiance.S02E04.HDTV.x264-2HD is SDTV
2015-06-29 20:03:35 INFO     SEARCHQUEUE-MANUAL-255326 :: Found result Defiance.S02E04.HDTV.x264-2HD.[VTV].mp4 at magnet:?xt=urn:btih:C04ECE208B6AD334AE00D870435E43BE35996BD2&dn=defiance+s02e04+hdtv+x264+2hd+vtv+mp4&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
2015-06-29 20:03:35 INFO     SEARCHQUEUE-MANUAL-255326 :: Found result Defiance.S02E04.HDTV.x264-2HD[ettv] at magnet:?xt=urn:btih:3CD6EA7A9675746CC746244B710ABB52A1060D56&dn=defiance+s02e04+hdtv+x264+2hd+ettv&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
2015-06-29 20:03:35 INFO     SEARCHQUEUE-MANUAL-255326 :: Found result Defiance.S02E04.HDTV.x264-2HD at magnet:?xt=urn:btih:83BF6D4D55D5710391FB4F59B4611FCE66089E62&dn=defiance+s02e04+hdtv+x264+2hd&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
2015-06-29 20:03:35 INFO     SEARCHQUEUE-MANUAL-255326 :: Found result Defiance.S02E04.HDTV.x264-2HD[rartv] at magnet:?xt=urn:btih:79186B68D61297FD198B2CF99D7C20FE444FE9EE&dn=defiance+s02e04+hdtv+x264+2hd+rartv&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
2015-06-29 20:03:35 INFO     SEARCHQUEUE-MANUAL-255326 :: Found result Defiance.S02E04.HDTV.x264-2HD.[eztv] at magnet:?xt=urn:btih:49316942423930350E47057CE4485225230452A2&dn=defiance+s02e04+hdtv+x264+2hd+eztv&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
2015-06-29 20:03:35 INFO     SEARCHQUEUE-MANUAL-255326 :: Found result Defiance.S02E04.HDTV.x264-2HD at magnet:?xt=urn:btih:38712D384F94E5F150A7ECFEDFD29A7FA41BDBE3&dn=defiance+s02e04+hdtv+x264+2hd&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
2015-06-29 20:03:35 INFO     SEARCHQUEUE-MANUAL-255326 :: Performing episode search for Defiance
2015-06-29 20:03:33 INFO     SEARCHQUEUE-MANUAL-255326 :: [KickAssTorrents] :: Performing season pack search for Defiance
2015-06-29 20:03:33 INFO     SEARCHQUEUE-MANUAL-255326 :: Building internal name cache for Defiance
2015-06-29 20:03:33 INFO     SEARCHQUEUE-MANUAL-255326 :: Beginning manual search for: [Defiance - 2x04 - Beasts of Burden]


However when I select this option http://i.imgur.com/bFS2zp1.png within the search provider settings on ANY provider, I get the following:

2015-06-29 20:07:38 INFO     POSTPROCESSER :: Processing completed
2015-06-29 20:07:38 INFO     POSTPROCESSER :: PostProcessing Path: C:\Torrents\Complete\TV
AA. Error: 'charmap' codec can't decode byte 0x8d in position 33: character maps to <undefined>
AARelease Group: 2HD
AASize: -1
AAName: Defiance.S02E04.HDTV.x264-2HD
AAQuality: SDTV
AAEpisode: [<sickbeard.tv.TVEpisode object at 0x055e6550>]
AAExtra Info:
AAUnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 33: character maps to <undefined>
AA    return codecs.charmap_decode(input,errors,decoding_table)
AA  File "C:\AtlasCore\Core\PyPy\lib-python\2.7\encodings\cp1252.py", line 15, in decode
AA    message = meThread + u" :: " + msg
AA  File "C:\AtlasCore\Programs\SickRage\sickbeard\logger.py", line 133, in log
AA    logger.log('Torrent bencoded data: {0}'.format(str(result.content)), logger.DEBUG)
AA  File "C:\AtlasCore\Programs\SickRage\sickbeard\clients\generic.py", line 160, in _get_torrent_hash
AA    result = self._get_torrent_hash(result)
AA  File "C:\AtlasCore\Programs\SickRage\sickbeard\clients\generic.py", line 186, in sendTORRENT
AATraceback (most recent call last):
2015-06-29 20:06:30 ERROR    SEARCHQUEUE-MANUAL-255326 :: uTorrent: Failed Sending Torrent
AABTFailure: not a valid bencoded string
AA    raise BTFailure("not a valid bencoded string")
AA  File "C:\AtlasCore\Programs\SickRage\lib\bencode\bencode.py", line 68, in bdecode
AA    torrent_bdecode = bdecode(result.content)
AA  File "C:\AtlasCore\Programs\SickRage\sickbeard\clients\generic.py", line 157, in _get_torrent_hash
AATraceback (most recent call last):
2015-06-29 20:06:30 ERROR    SEARCHQUEUE-MANUAL-255326 :: Unable to bdecode torrent
2015-06-29 20:06:29 INFO     SEARCHQUEUE-MANUAL-255326 :: Downloading Defiance.S02E04.HDTV.x264-2HD from KickAssTorrents
2015-06-29 20:06:29 INFO     SEARCHQUEUE-MANUAL-255326 :: Quality of Defiance.S02E04.HDTV.x264-2HD.[VTV].mp4 is SDTV
2015-06-29 20:06:28 INFO     SEARCHQUEUE-MANUAL-255326 :: Quality of Defiance.S02E04.HDTV.x264-2HD[ettv] is SDTV
2015-06-29 20:06:28 INFO     SEARCHQUEUE-MANUAL-255326 :: Quality of Defiance.S02E04.HDTV.x264-2HD is SDTV
2015-06-29 20:06:27 INFO     SEARCHQUEUE-MANUAL-255326 :: Quality of Defiance.S02E04.HDTV.x264-2HD[rartv] is SDTV
2015-06-29 20:06:27 INFO     SEARCHQUEUE-MANUAL-255326 :: Quality of Defiance.S02E04.HDTV.x264-2HD.[eztv] is SDTV
2015-06-29 20:06:26 INFO     SEARCHQUEUE-MANUAL-255326 :: Quality of Defiance.S02E04.HDTV.x264-2HD is SDTV
2015-06-29 20:06:26 INFO     SEARCHQUEUE-MANUAL-255326 :: [KickAssTorrents] :: Found result Defiance.S02E04.HDTV.x264-2HD.[VTV].mp4 at magnet:?xt=urn:btih:C04ECE208B6AD334AE00D870435E43BE35996BD2&dn=defiance+s02e04+hdtv+x264+2hd+vtv+mp4&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
2015-06-29 20:06:26 INFO     SEARCHQUEUE-MANUAL-255326 :: [KickAssTorrents] :: Found result Defiance.S02E04.HDTV.x264-2HD[ettv] at magnet:?xt=urn:btih:3CD6EA7A9675746CC746244B710ABB52A1060D56&dn=defiance+s02e04+hdtv+x264+2hd+ettv&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
2015-06-29 20:06:26 INFO     SEARCHQUEUE-MANUAL-255326 :: [KickAssTorrents] :: Found result Defiance.S02E04.HDTV.x264-2HD at magnet:?xt=urn:btih:83BF6D4D55D5710391FB4F59B4611FCE66089E62&dn=defiance+s02e04+hdtv+x264+2hd&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
2015-06-29 20:06:26 INFO     SEARCHQUEUE-MANUAL-255326 :: [KickAssTorrents] :: Found result Defiance.S02E04.HDTV.x264-2HD[rartv] at magnet:?xt=urn:btih:79186B68D61297FD198B2CF99D7C20FE444FE9EE&dn=defiance+s02e04+hdtv+x264+2hd+rartv&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
2015-06-29 20:06:26 INFO     SEARCHQUEUE-MANUAL-255326 :: [KickAssTorrents] :: Found result Defiance.S02E04.HDTV.x264-2HD.[eztv] at magnet:?xt=urn:btih:49316942423930350E47057CE4485225230452A2&dn=defiance+s02e04+hdtv+x264+2hd+eztv&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
2015-06-29 20:06:26 INFO     SEARCHQUEUE-MANUAL-255326 :: [KickAssTorrents] :: Found result Defiance.S02E04.HDTV.x264-2HD at magnet:?xt=urn:btih:38712D384F94E5F150A7ECFEDFD29A7FA41BDBE3&dn=defiance+s02e04+hdtv+x264+2hd&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
2015-06-29 20:06:26 INFO     SEARCHQUEUE-MANUAL-255326 :: [KickAssTorrents] :: Performing episode search for Defiance
2015-06-29 20:06:26 INFO     SEARCHQUEUE-MANUAL-255326 :: Building internal name cache for Defiance
2015-06-29 20:06:26 INFO     SEARCHQUEUE-MANUAL-255326 :: Beginning manual search for: [Defiance - 2x04 - Beasts of Burden]

It looks as if "Access provider via proxy" is currently broken. Tested all 3 providers with and without proxies, with a complete sickrage restart in between each test. Should I open a new ticket?

**Comment by fernandog** [comment]
@Morphello you should open a ticked inside SR with "submit errors". 

more than 3.000 SR users are using rarbg without an issue and no need for proxy

**Comment by Morphello** [comment]
How do you submit a ticket within SR? I can't find the option.

**Comment by fernandog** [comment]
add github user/pass in advanced settings. the button will come up when you have errors

**Comment by Morphello** [comment]
Thank you.
