### ISSUE TITLE
[APP SUBMITTED]: fixGlob() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by thecolorchanges** [SiCKRAGETV/sickrage-issues#1930]
### INFO
Python Version: **2.6.5 (r265:79063, Jul 24 2010, 21:39:31) [GCC 4.2.3]**
Operating System: **Linux-3.0.3-unRAID-i686-AMD_Athlon-tm-_II_Neo_N36L_Dual-Core_Processor-with-slackware-13.1.0**
Locale: UTF8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@4a5426d013025ad1b413daef68f66aa9402f8755
Link to Log: https://gist.github.com/3a8bb43668a9f893436d
### ERROR
```
Thread-35 :: Failed doing webui callback: Traceback (most recent call last):
  File "/mnt/scratch/SickRage/sickbeard/webserve.py", line 259, in async_call
    result = function(**kwargs)
  File "/mnt/scratch/SickRage/sickbeard/webserve.py", line 2175, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/mnt/scratch/SickRage/sickbeard/processTV.py", line 251, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/mnt/scratch/SickRage/sickbeard/processTV.py", line 499, in process_media
    result.result = processor.process()
  File "/mnt/scratch/SickRage/sickbeard/postProcessor.py", line 1035, in process
    sickbeard.USE_SUBTITLES and ep_obj.show.subtitles)
  File "/mnt/scratch/SickRage/sickbeard/postProcessor.py", line 349, in _move
    subtitles=subtitles)
  File "/mnt/scratch/SickRage/sickbeard/postProcessor.py", line 280, in _combined_file_operation
    file_list = file_list + self.list_associated_files(file_path)
  File "/mnt/scratch/SickRage/sickbeard/postProcessor.py", line 191, in list_associated_files
    checklist = ek.ek(glob.glob, helpers.fixGlob(ek.ek(os.path.join, ek.ek(os.path.dirname, file_path)), '*')) # get a list of all the files in the folder
TypeError: fixGlob() takes exactly 1 argument (2 given)

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@thecolorchanges We are making some major changes in Develop so please switch to Master.
Here you can find more info. : https://github.com/SiCKRAGETV/sickrage-issues/issues/1913

**Comment by fernandog** [comment]
keep open so we know it has to be fixed

**Comment by miigotu** [comment]
Fook a missed parenthesis
