### ISSUE TITLE
SR not starting

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#1931]
Traceback (most recent call last):
  File "SickBeard.py", line 90, in <module>
    import sickbeard
  File "/home/osmc/SickRage/sickbeard/__init__.py", line 37, in <module>
    from sickbeard import providers, metadata, config, webserveInit
  File "/home/osmc/SickRage/sickbeard/metadata/__init__.py", line 22, in <module                       >
    import kodi, kodi_12plus, mediabrowser, ps3, wdtv, tivo, mede8er
  File "/home/osmc/SickRage/sickbeard/metadata/kodi.py", line 19, in <module>
    import generic
  File "/home/osmc/SickRage/sickbeard/metadata/generic.py", line 30, in <module>
    from sickbeard.metadata import helpers as metadata_helpers
  File "/home/osmc/SickRage/sickbeard/metadata/helpers.py", line 22, in <module>
    meta_session = requests.Session()
NameError: name 'requests' is not defined

@miigotu

**Comment by miigotu** [comment]
Missed import, just fixed in develop.
