### ISSUE TITLE
[APP SUBMITTED]: u'und'

### ISSUE THREAD

**Issue by hlavicka** [SiCKRAGETV/sickrage-issues#1946]
### INFO
Python Version: **2.7.9 (default, Jan 16 2015, 11:00:00) [GCC 4.9.2]**
Operating System: **Linux-2.6.31.8-armv5tel-with-libc0**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@f943c06c11430e91e25a1ab5ffbad5dfc0bbbf72
Link to Log: https://gist.github.com/24ad3887e4dbf405edb3
### ERROR
```
Thread-55 :: Failed doing webui callback: Traceback (most recent call last):
  File "/e-data/fe690528-4823-48e1-8747-38c1024f00b2/opt/SickBeard-TVRage/sickbeard/webserve.py", line 259, in async_call
    result = function(**kwargs)
  File "/e-data/fe690528-4823-48e1-8747-38c1024f00b2/opt/SickBeard-TVRage/sickbeard/webserve.py", line 1297, in displayShow
    return t.respond()
  File "/ffp/opt/Sick-Beard-TvRage/cache/cheetah/_ffp_opt_Sick_Beard_TvRage_gui_slick_interfaces_default_displayShow_tmpl.py", line 1337, in respond
    for sub_lang in [babelfish.Language.fromalpha2(x.strip()) for x in VFN(VFFSL(SL,"epResult",True)["subtitles"],"split",False)(',') if x != ""]: # generated from line 583, col 17
  File "/ffp/opt/Sick-Beard-TvRage/lib/babelfish/language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/ffp/opt/Sick-Beard-TvRage/lib/babelfish/converters/__init__.py", line 165, in reverse
    raise LanguageReverseError(code)
LanguageReverseError: u'und'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@hlavicka 
It was already reported. :  https://github.com/SiCKRAGETV/sickrage-issues/issues/1913#issuecomment-117739257
Currently there are some major changes on develop, as we try to overhaul/update the subtitle section.
So best to switch to Master if you are running in a live environment.
