### ISSUE TITLE
Sickrage not snatching any episodes

### ISSUE THREAD

**Issue by davymunch** [SiCKRAGETV/sickrage-issues#1955]
I have sickrage running on my DSM NAS. It worked fine for about a while but recently i can't seem to snatch any episodes. The Episodes are found but i get an error sending it to my downloadstation (or even transmission). The problem occurs when searching episodes both manually and automaticaly.
Any suggestions on what might help me solve this issue ?

BRANCH: (master) / COMMIT: (aa9c1bf1ca2bf3df9cd33fe4e798c8247dfe1881)

log:

AA. Error: not a valid bencoded string
AARelease Group: ASAP
AASize: -1
AAName: True.Detective.S02E02.HDTV.x264-ASAP
AAQuality: SDTV
AAEpisode: [<****beard.tv.TVEpisode object at 0x7fb3184672d0>]
AAExtra Info:
AABTFailure: not a valid bencoded string
AA    raise BTFailure("not a valid bencoded string")
AA  File "/volume1/@appstore/****rage/var/SickRage/lib/bencode/bencode.py", line 68, in bdecode
AA    torrent_bdecode = bdecode(result.content)
AA  File "/volume1/@appstore/****rage/var/SickRage/****beard/clients/generic.py", line 157, in _get_torrent_hash
AA    result = self._get_torrent_hash(result)
AA  File "/volume1/@appstore/****rage/var/SickRage/****beard/clients/generic.py", line 186, in sendTORRENT
AATraceback (most recent call last):
2015-07-02 13:58:35 ERROR    SEARCHQUEUE-MANUAL-270633 :: DownloadStation: Failed Sending Torrent
AABTFailure: not a valid bencoded string
AA    raise BTFailure("not a valid bencoded string")
AA  File "/volume1/@appstore/****rage/var/SickRage/lib/bencode/bencode.py", line 68, in bdecode
AA    torrent_bdecode = bdecode(result.content)
AA  File "/volume1/@appstore/****rage/var/SickRage/****beard/clients/generic.py", line 157, in _get_torrent_hash
AATraceback (most recent call last):
2015-07-02 13:58:35 ERROR    SEARCHQUEUE-MANUAL-270633 :: Unable to bdecode torrent
2015-07-02 13:58:35 INFO     SEARCHQUEUE-MANUAL-270633 :: Downloading True.Detective.S02E02.HDTV.x264-ASAP from Speedcd
2015-07-02 13:58:35 INFO     SEARCHQUEUE-MANUAL-270633 :: Quality of True.Detective.S02E02.HDTV.x264-ASAP is SDTV

2015-07-02 14:00:07 SEARCHQUEUE-BACKLOG-74608 :: Unable to bdecode torrent
2015-07-02 14:00:07 SEARCHQUEUE-BACKLOG-74608 :: DownloadStation: Failed Sending Torrent
2015-07-02 13:58:35 SEARCHQUEUE-MANUAL-270633 :: Unable to bdecode torrent
2015-07-02 13:58:35 SEARCHQUEUE-MANUAL-270633 :: DownloadStation: Failed Sending Torrent
2015-07-02 13:58:11 SEARCHQUEUE-MANUAL-270633 :: Unable to bdecode torrent
2015-07-02 13:58:11 SEARCHQUEUE-MANUAL-270633 :: DownloadStation: Failed Sending Torrent
2015-07-02 13:55:25 SEARCHQUEUE-BACKLOG-247808 :: Unable to bdecode torrent
2015-07-02 13:55:25 SEARCHQUEUE-BACKLOG-247808 :: DownloadStation: Failed Sending Torrent
2015-07-02 13:55:20 SEARCHQUEUE-BACKLOG-148581 :: Unable to bdecode torrent
2015-07-02 13:55:20 SEARCHQUEUE-BACKLOG-148581 :: DownloadStation: Failed Sending Torrent
2015-07-02 13:54:52 SEARCHQUEUE-DAILY-SEARCH :: Unable to bdecode torrent
2015-07-02 13:54:52 SEARCHQUEUE-DAILY-SEARCH :: DownloadStation: Failed Sending Torrent
2015-07-02 13:54:49 SEARCHQUEUE-DAILY-SEARCH :: Unable to bdecode torrent
2015-07-02 13:54:49 SEARCHQUEUE-DAILY-SEARCH :: DownloadStation: Failed Sending Torrent
2015-07-02 13:54:47 SEARCHQUEUE-DAILY-SEARCH :: Unable to bdecode torrent
2015-07-02 13:54:47 SEARCHQUEUE-DAILY-SEARCH :: DownloadStation: Failed Sending Torrent

**Comment by fernandog** [comment]
follow guidelines: https://github.com/SiCKRAGETV/sickrage-issues/
