### ISSUE TITLE
6box.me indexer not working. DB error: unrecognized token: "6box_me"

### ISSUE THREAD

**Issue by neoatomic** [SiCKRAGETV/sickrage-issues#1983]
As i came across some tickets that had 6box.me as a provider/problems i registered an account. (free and open nzb indexer)

However i cant get it to work.
Could anyone try to register an account to test if they have time.? So we can confirm problems with this indexer? (or that my install has gone bad.)
It gives me a DB error and then tells the token is wrong. Needless to say i have checked the apikey numerous times and its correct...

When i manually do the call in my browser with the api key it gives results.:

```
https://6box.me/api?t=tvsearch&cat=5030,5040&extended=1&apikey=********&offset=0&limit=100&rid=38584&season=1&ep=9
```

![naamloos](https://cloud.githubusercontent.com/assets/7928052/8544648/4dfda8e0-24a7-11e5-95d9-cfa3ec09a9cd.png)

The error that is shown in the log : 

```
2015-07-07 11:44:07 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [6box.me] :: DB error: unrecognized token: "6box_me"
Traceback (most recent call last):
  File "/volume1/@appstore/********/var/SickRage/sickbeard/db.py", line 168, in action
    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/volume1/@appstore/********/var/SickRage/sickbeard/db.py", line 84, in execute
    return self._execute(query, args).fetchall()
  File "/volume1/@appstore/********/var/SickRage/sickbeard/db.py", line 76, in _execute
    return self.connection.cursor().execute(query)
OperationalError: unrecognized token: "6box_me"
2015-07-07 11:44:07 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [6box.me] :: Error while searching 6box.me, skipping: unrecognized token: "6box_me"
Traceback (most recent call last):
  File "/volume1/@appstore/********/var/SickRage/sickbeard/search.py", line 392, in searchForNeededEpisodes
    curFoundResults = curProvider.searchRSS(episodes)
  File "/volume1/@appstore/********/var/SickRage/sickbeard/providers/generic.py", line 265, in searchRSS
    return self.cache.findNeededEpisodes(episodes)
  File "/volume1/@appstore/********/var/SickRage/sickbeard/tvcache.py", line 317, in findNeededEpisodes
    myDB = self._getDB()
  File "/volume1/@appstore/********/var/SickRage/sickbeard/tvcache.py", line 89, in _getDB
    self.providerDB = CacheDBConnection(self.providerID)
  File "/volume1/@appstore/********/var/SickRage/sickbeard/tvcache.py", line 59, in __init__
    if not self.hasColumn(providerName, 'release_group'):
  File "/volume1/@appstore/********/var/SickRage/sickbeard/db.py", line 246, in hasColumn
    return column in self.tableInfo(tableName)
  File "/volume1/@appstore/********/var/SickRage/sickbeard/db.py", line 224, in tableInfo
    sqlResult = self.select("PRAGMA table_info(%s)" % tableName)
  File "/volume1/@appstore/********/var/SickRage/sickbeard/db.py", line 191, in select
    sqlResults = self.action(query, args, fetchall=True)
  File "/volume1/@appstore/********/var/SickRage/sickbeard/db.py", line 168, in action
    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/volume1/@appstore/********/var/SickRage/sickbeard/db.py", line 84, in execute
    return self._execute(query, args).fetchall()
  File "/volume1/@appstore/********/var/SickRage/sickbeard/db.py", line 76, in _execute
    return self.connection.cursor().execute(query)
OperationalError: unrecognized token: "6box_me"
2015-07-07 11:44:07 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [6box.me] :: Traceback (most recent call last):
  File "/volume1/@appstore/********/var/SickRage/sickbeard/search.py", line 392, in searchForNeededEpisodes
    curFoundResults = curProvider.searchRSS(episodes)
  File "/volume1/@appstore/********/var/SickRage/sickbeard/providers/generic.py", line 265, in searchRSS
    return self.cache.findNeededEpisodes(episodes)
  File "/volume1/@appstore/********/var/SickRage/sickbeard/tvcache.py", line 317, in findNeededEpisodes
    myDB = self._getDB()
  File "/volume1/@appstore/********/var/SickRage/sickbeard/tvcache.py", line 89, in _getDB
    self.providerDB = CacheDBConnection(self.providerID)
  File "/volume1/@appstore/********/var/SickRage/sickbeard/tvcache.py", line 59, in __init__
    if not self.hasColumn(providerName, 'release_group'):
  File "/volume1/@appstore/********/var/SickRage/sickbeard/db.py", line 246, in hasColumn
    return column in self.tableInfo(tableName)
  File "/volume1/@appstore/********/var/SickRage/sickbeard/db.py", line 224, in tableInfo
    sqlResult = self.select("PRAGMA table_info(%s)" % tableName)
  File "/volume1/@appstore/********/var/SickRage/sickbeard/db.py", line 191, in select
    sqlResults = self.action(query, args, fetchall=True)
  File "/volume1/@appstore/********/var/SickRage/sickbeard/db.py", line 168, in action
    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/volume1/@appstore/********/var/SickRage/sickbeard/db.py", line 84, in execute
    return self._execute(query, args).fetchall()
  File "/volume1/@appstore/********/var/SickRage/sickbeard/db.py", line 76, in _execute
    return self.connection.cursor().execute(query)
OperationalError: unrecognized token: "6box_me"

2015-07-07 11:44:07 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
```

**Comment by legoman666** [comment]
Change the name of the provider to not start with a number. This is a known issue.

**Comment by neoatomic** [comment]
@legoman666 Thanks, wasn't aware of this.
