### ISSUE TITLE
[APP SUBMITTED]: Unknown exception while loading URL http://thetvdb.com

### ISSUE THREAD

**Issue by Nitrowolf** [SiCKRAGETV/sickrage-issues#1995]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:38) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-43-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@4a47a5cf7eff76f0d99a9c0f3b574027d1f56dd8
Link to Log: https://gist.github.com/7ecb1d491c66fcc52b3f
### ERROR
```
Thread-137 :: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Nitrowolf** [comment]
Trying to submit the actual errors produces an error itself, here:

AAGithubException: 422 {u'documentation_url': u'https://developer.github.com/v3/issues/#create-an-issue', u'message': u'Validation Failed', u'errors': [{u'field': u'title', u'message': u'title is too long', u'code': u'custom', u'resource': u'Issue'}]}
AA    raise self.__createException(status, responseHeaders, output)
AA  File "/opt/SickRage/lib/github/Requester.py", line 177, in __check
AA    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
AA  File "/opt/SickRage/lib/github/Requester.py", line 169, in requestJsonAndCheck
AA    input=post_parameters
AA  File "/opt/SickRage/lib/github/Repository.py", line 857, in create_issue
AA    issue = gh.get_organization(gh_org).get_repo(gh_repo).create_issue(title_Error, message)
AA  File "/opt/SickRage/sickbeard/logger.py", line 253, in submit_errors
AATraceback (most recent call last):
2015-07-07 18:23:07 ERROR    Thread-147 ::

**Comment by Nitrowolf** [comment]
What I actually tried to submit as errors:

2015-07-07 18:23:07 Thread-147 :: 
2015-07-07 18:12:09 Thread-121 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/opt/SickRage/sickbeard/webserve.py", line 2174, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/opt/SickRage/sickbeard/processTV.py", line 251, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/opt/SickRage/sickbeard/processTV.py", line 499, in process_media
    result.result = processor.process()
  File "/opt/SickRage/sickbeard/postProcessor.py", line 1079, in process
    ep_obj.createMetaFiles()
  File "/opt/SickRage/sickbeard/tv.py", line 1932, in createMetaFiles
    self.createThumbnail()
  File "/opt/SickRage/sickbeard/tv.py", line 1951, in createThumbnail
    result = cur_provider.create_episode_thumb(self) or result
  File "/opt/SickRage/sickbeard/metadata/generic.py", line 332, in create_episode_thumb
    return self.save_thumbnail(ep_obj)
  File "/opt/SickRage/sickbeard/metadata/generic.py", line 499, in save_thumbnail
    thumb_url = self._get_episode_thumb_url(ep_obj)
  File "/opt/SickRage/sickbeard/metadata/generic.py", line 386, in _get_episode_thumb_url
    myEp = helpers.validateShow(cur_ep.show, cur_ep.season, cur_ep.episode)
  File "/opt/SickRage/sickbeard/helpers.py", line 1069, in validateShow
    return t[show.indexerid][season][episode]
  File "/opt/SickRage/lib/tvdb_api/tvdb_api.py", line 948, in __getitem__
    self._getShowData(key, self.config['language'], True)
  File "/opt/SickRage/lib/tvdb_api/tvdb_api.py", line 843, in _getShowData
    self.config['url_seriesInfo'] % (sid, getShowInLanguage)
  File "/opt/SickRage/lib/tvdb_api/tvdb_api.py", line 632, in _getetsrc
    raise tvdb_error(e)
tvdb_error: Unknown exception while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/205281/en.xml: Traceback (most recent call last):
  File "/opt/SickRage/lib/tvdb_api/tvdb_api.py", line 574, in _loadUrl
    resp = session.get(url.strip(), cache_auto=True, params=params)
  File "/opt/SickRage/lib/cachecontrol/session.py", line 23, in get
    return super(CacheControlSession, self).get(*args, **kw)
  File "/opt/SickRage/lib/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/opt/SickRage/lib/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/SickRage/lib/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/opt/SickRage/lib/cachecontrol/adapter.py", line 27, in send
    cached_response = self.controller.cached_request(request)
  File "/opt/SickRage/lib/cachecontrol/controller.py", line 102, in cached_request
    parsedate_tz(headers['date'])
  File "/opt/SickRage/lib/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'date'


2015-07-07 18:11:48 Thread-121 :: Unable to connect to theTVDB while creating meta files - skipping - error Unknown exception while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/205281/en.xml: Traceback (most recent call last):
  File "/opt/SickRage/lib/tvdb_api/tvdb_api.py", line 574, in _loadUrl
    resp = session.get(url.strip(), cache_auto=True, params=params)
  File "/opt/SickRage/lib/cachecontrol/session.py", line 23, in get
    return super(CacheControlSession, self).get(*args, **kw)
  File "/opt/SickRage/lib/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/opt/SickRage/lib/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/SickRage/lib/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/opt/SickRage/lib/cachecontrol/adapter.py", line 27, in send
    cached_response = self.controller.cached_request(request)
  File "/opt/SickRage/lib/cachecontrol/controller.py", line 102, in cached_request
    parsedate_tz(headers['date'])
  File "/opt/SickRage/lib/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'date'

**Comment by miigotu** [comment]
`KeyError: 'date'` Fixed in develop. Wait till next merge
