### ISSUE TITLE
[APP SUBMITTED]: 'ascii' codec can't encode character u'\u03bc' in position 50: ordinal not in range(128)

### ISSUE THREAD

**Issue by fifou3101** [SiCKRAGETV/sickrage-issues#1999]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@e2318076201cb9a0b4e6fb0bce7aa6504be524a3
Link to Log: https://gist.github.com/33666380394daa047027
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: ascii : /home/fifou/Torrent/completed/Love Live! - 2x10 - μ's.mkv : error 50 : error 51 : ordinal not in range(128)
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
@fifou3101 Pleas give full log, the exception can't be seen in that one, and I'm hoping the fix I just did in develop fixes this.

**Comment by fifou3101** [comment]
Here is the log i've got about this issue :
```
AAUnicodeEncodeError: 'ascii' codec can't encode character u'\u03bc' in position 50: ordinal not in range(128)
AA    os.stat(path)
AA  File "/usr/lib/python2.7/genericpath.py", line 18, in exists
AA    if(not(os.path.exists(file))):
AA  File "/home/fifou/sickrage_install/sickbeard/helpers.py", line 1653, in isFileLocked
AA    if not helpers.isFileLocked(self.file_path, False):
AA  File "/home/fifou/sickrage_install/sickbeard/postProcessor.py", line 913, in process
AA    result.result = processor.process()
AA  File "/home/fifou/sickrage_install/sickbeard/processTV.py", line 499, in process_media
AA    process_media(path, [video], nzbName, process_method, force, is_priority, result)
AA  File "/home/fifou/sickrage_install/sickbeard/processTV.py", line 204, in processDir
AA    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR)
AA  File "/home/fifou/sickrage_install/sickbeard/autoPostProcesser.py", line 50, in run
AA    self.action.run(self.force)
AA  File "/home/fifou/sickrage_install/sickbeard/scheduler.py", line 97, in run
AATraceback (most recent call last):
2015-07-08 10:27:13 ERROR    POSTPROCESSER :: Exception generated in thread POSTPROCESSER: ascii : /home/fifou/Torrent/completed/Love Live! - 2x10 - μ's.mkv : error 50 : error 51 : ordinal not in range(128)
2015-07-08 10:27:13 INFO     POSTPROCESSER :: Processing /home/fifou/Torrent/completed/Love Live! - 2x10 - μ's.mkv (None)
```

**Comment by miigotu** [comment]
Thats what I was missing =P.

I just fixed this in develop branch like an hour ago. Should be a develop->master merge soon.

**Comment by fifou3101** [comment]
Great! Thanks!
