### ISSUE TITLE
Error occurred when downloading subtitles

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#2]
I constantly getting the following error within last month. Could you please take a look at it?

Many thanks.
```
2014-11-17 16:10:10 FINDSUBTITLES :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/tv.py", line 1372, in downloadSubtitles
    multi=True, cache_dir=sickbeard.CACHE_DIR)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/api.py", line 98, in download_subtitles
    subtitles.sort(key=lambda s: key_subtitles(s, video, languages, services, order), reverse=True)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/api.py", line 98, in 
    subtitles.sort(key=lambda s: key_subtitles(s, video, languages, services, order), reverse=True)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/core.py", line 240, in key_subtitles
    confidence = matching_confidence(video, subtitle)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/core.py", line 159, in matching_confidence
    guess = guessit.guess_file_info(subtitle.release, 'autodetect')
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/guessit/__init__.py", line 205, in guess_file_info
    result.append(_guess_filename(filename, filetype))
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/guessit/__init__.py", line 106, in _guess_filename
    mtree = IterativeMatcher(filename, filetype=filetype)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/guessit/matcher.py", line 157, in __init__
    apply_transfo('post_process')
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/guessit/matcher.py", line 99, in apply_transfo
    transfo.process(mtree, *args, **kwargs)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/guessit/transfo/post_process.py", line 56, in process
    promote_subtitle()
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/guessit/transfo/post_process.py", line 37, in promote_subtitle
    node.guess.set('subtitleLanguage', node.guess['language'],
KeyError: u'language'
```

**Comment by fernandog** [comment]
@Rafkat are you still having this issue? Did you try the latest DEVELOP branch?
