### ISSUE TITLE
[APP SUBMITTED]: bad character range

### ISSUE THREAD

**Issue by Basjuhhh** [SiCKRAGETV/sickrage-issues#2002]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@e2318076201cb9a0b4e6fb0bce7aa6504be524a3
Link to Log: https://gist.github.com/b65582dfa8e65a3db9b6
### ERROR
```
Thread-201 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 2174, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/processTV.py", line 251, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/processTV.py", line 499, in process_media
    result.result = processor.process()
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/postProcessor.py", line 1034, in process
    sickbeard.USE_SUBTITLES and ep_obj.show.subtitles)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/postProcessor.py", line 348, in _move
    subtitles=subtitles)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/postProcessor.py", line 279, in _combined_file_operation
    file_list = file_list + self.list_associated_files(file_path)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/postProcessor.py", line 190, in list_associated_files
    checklist = ek.ek(glob.glob, ek.ek(os.path.join, ek.ek(os.path.dirname, file_path), '*')) # get a list of all the files in the folder
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/encodingKludge.py", line 73, in ek
    result = func(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
  File "/usr/local/python/lib/python2.7/glob.py", line 27, in glob
    return list(iglob(pathname))
  File "/usr/local/python/lib/python2.7/glob.py", line 63, in iglob
    for dirname in dirs:
  File "/usr/local/python/lib/python2.7/glob.py", line 64, in iglob
    for name in glob_in_dir(dirname, basename):
  File "/usr/local/python/lib/python2.7/glob.py", line 83, in glob1
    return fnmatch.filter(names, pattern)
  File "/usr/local/sickrage/env/lib/python2.7/fnmatch.py", line 56, in filter
    _cache[pat] = re_pat = re.compile(res)
  File "/usr/local/sickrage/env/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/local/sickrage/env/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
error: bad character range

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Basjuhhh** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@e2318076201cb9a0b4e6fb0bce7aa6504be524a3
Link to Log: https://gist.github.com/253f41a4705e5b798455
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: bad character range
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
already fixed in develop
