### ISSUE TITLE
[APP SUBMITTED]: u'pb'

### ISSUE THREAD

**Issue by jnsaraiva** [SiCKRAGETV/sickrage-issues#2013]
### INFO
Python Version: **2.7.6 (default, Sep  9 2014, 15:04:36) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]**
Operating System: **Darwin-14.3.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@a4f329fbc394e8939977bf9c43aa540f948fec75
Link to Log: https://gist.github.com/dc494a98388c1daa5aef
### ERROR
```
Thread-107 :: Failed doing webui callback: Traceback (most recent call last):
  File "/Applications/SickRage/sickbeard/webserve.py", line 269, in async_call
    result = function(**kwargs)
  File "/Applications/SickRage/sickbeard/webserve.py", line 1307, in displayShow
    return t.respond()
  File "/Applications/SickRage/cache/cheetah/_Applications_SickRage_gui_slick_interfaces_default_displayShow_tmpl.py", line 1341, in respond
    for sub_lang in [babelfish.Language.fromietf(x) for x in VFN(VFFSL(SL,"epResult",True)["subtitles"],"split",False)(',') if VFFSL(SL,"epResult",True)["subtitles"]]: # generated from line 583, col 13
  File "/Applications/SickRage/lib/babelfish/language.py", line 124, in fromietf
    language = cls.fromalpha2(language_subtag)
  File "/Applications/SickRage/lib/babelfish/language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/Applications/SickRage/lib/babelfish/converters/__init__.py", line 165, in reverse
    raise LanguageReverseError(code)
LanguageReverseError: u'pb'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Lgomes104** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.14-v7+-armv7l-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@a4f329fbc394e8939977bf9c43aa540f948fec75
Link to Log: https://gist.github.com/8d54b780eea3b4c8cc4b
### ERROR
```
Thread-45 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/pi/.sickrage/sickbeard/webserve.py", line 269, in async_call
    result = function(**kwargs)
  File "/home/pi/.sickrage/sickbeard/webserve.py", line 1307, in displayShow
    return t.respond()
  File "/home/pi/.sickrage/cache/cheetah/_home_pi__sickrage_gui_slick_interfaces_default_displayShow_tmpl.py", line 1341, in respond
    for sub_lang in [babelfish.Language.fromietf(x) for x in VFN(VFFSL(SL,"epResult",True)["subtitles"],"split",False)(',') if VFFSL(SL,"epResult",True)["subtitles"]]: # generated from line 583, col 13
  File "/home/pi/.sickrage/lib/babelfish/language.py", line 124, in fromietf
    language = cls.fromalpha2(language_subtag)
  File "/home/pi/.sickrage/lib/babelfish/language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/home/pi/.sickrage/lib/babelfish/converters/__init__.py", line 165, in reverse
    raise LanguageReverseError(code)
LanguageReverseError: u'pb'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
https://github.com/Diaoul/subliminal/issues/323

pb is not a valid language code, it was from a hack, and it is being worked on there.
