### ISSUE TITLE
[APP SUBMITTED]: global name 'urllib2' is not defined

### ISSUE THREAD

**Issue by oceloti** [SiCKRAGETV/sickrage-issues#2020]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-55-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@1153ba18112827eb0fa8c71f111e076aca186416
No Log available with ERRORS: 
### ERROR
```
FINDPROPERS :: [IPTorrents] :: Error while searching IPTorrents, skipping: global name 'urllib2' is not defined
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by oceloti** [comment]
Could be linked to https://github.com/SiCKRAGETV/sickrage-issues/issues/2015

BRANCH: (master) / COMMIT: (1153ba18112827eb0fa8c71f111e076aca186416) 
Hi,

I updated to include the above commit and now the error has manifested. I too am using a global proxy.

Thank you for this @miigotu

2015-07-10 09:57:05 FINDPROPERS :: [IPTorrents] :: Error while searching IPTorrents, skipping: global name 'urllib2' is not defined
2015-07-10 09:57:01 FINDPROPERS :: [TorrentLeech] :: Error while searching TorrentLeech, skipping: global name 'urllib2' is not defined
2015-07-10 09:28:08 Thread-499 :: Failed doing webui callback: Traceback (most recent call last):
File "/opt/sickrage/sickbeard/webserve.py", line 269, in async_call
result = function(**kwargs)
File "/opt/sickrage/sickbeard/webserve.py", line 2184, in processEpisode
is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
File "/opt/sickrage/sickbeard/processTV.py", line 251, in processDir
process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
File "/opt/sickrage/sickbeard/processTV.py", line 491, in process_media
result.result = processor.process()
File "/opt/sickrage/sickbeard/postProcessor.py", line 1080, in process
ep_obj.createMetaFiles()
File "/opt/sickrage/sickbeard/tv.py", line 1998, in createMetaFiles
self.createThumbnail()
File "/opt/sickrage/sickbeard/tv.py", line 2017, in createThumbnail
result = cur_provider.create_episode_thumb(self) or result
File "/opt/sickrage/sickbeard/metadata/generic.py", line 332, in create_episode_thumb
return self.save_thumbnail(ep_obj)
File "/opt/sickrage/sickbeard/metadata/generic.py", line 506, in save_thumbnail
thumb_data = metadata_helpers.getShowImage(thumb_url)
File "/opt/sickrage/sickbeard/metadata/helpers.py", line 38, in getShowImage
image_data = helpers.getURL(tempURL, session=meta_session)
File "/opt/sickrage/sickbeard/helpers.py", line 1378, in getURL
session = _setUpSession(session, headers)
File "/opt/sickrage/sickbeard/helpers.py", line 1320, in _setUpSession
scheme, address = urllib2.splittype(sickbeard.PROXY_SETTING)
NameError: global name 'urllib2' is not defined

2015-07-10 09:27:53 POSTPROCESSER :: Exception generated in thread POSTPROCESSER: global name 'urllib2' is not defined
