### ISSUE TITLE
Got this error when try to open a tv show.

### ISSUE THREAD

**Issue by JoaoProductDev** [SiCKRAGETV/sickrage-issues#2029]
2015-07-10 09:45:57 Thread-20 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 269, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1307, in displayShow
    return t.respond()
  File "/usr/local/sickbeard-custom/var/cache/cheetah/_usr_local_sickbeard_custom_var_SickBeard_gui_slick_interfaces_default_displayShow_tmpl.py", line 1341, in respond
    for sub_lang in [babelfish.Language.fromietf(x) for x in VFN(VFFSL(SL,"epResult",True)["subtitles"],"split",False)(',') if VFFSL(SL,"epResult",True)["subtitles"]]: # generated from line 583, col 13
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/babelfish/language.py", line 124, in fromietf
    language = cls.fromalpha2(language_subtag)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/babelfish/language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/babelfish/converters/__init__.py", line 165, in reverse
    raise LanguageReverseError(code)
LanguageReverseError: u'pb'

**Comment by miigotu** [comment]
pb is not a language code, it was a hack to workaround in old subliminal. New subliminal there is a thread requesting it to be used.

https://github.com/Diaoul/subliminal/issues/323

You can rename *.pb.srt to *.pob.srt or *.pt.srt for now
