### ISSUE TITLE
Error while Sickrage is starting

### ISSUE THREAD

**Issue by megabitus98** [SiCKRAGETV/sickrage-issues#2040]
```
Traceback (most recent call last):
  File "SickBeard.py", line 90, in <module>
    import sickbeard
  File "/home/megabitus/.sickrage/sickbeard/__init__.py", line 37, in <module>
    from sickbeard import providers, metadata, config, webserveInit
  File "/home/megabitus/.sickrage/sickbeard/providers/__init__.py", line 54, in <module>
    import generic
  File "/home/megabitus/.sickrage/sickbeard/providers/generic.py", line 32, in <module>
    from sickbeard import helpers, classes, logger, db
  File "/home/megabitus/.sickrage/sickbeard/helpers.py", line 60, in <module>
    from sickbeard.subtitles import isValidLanguage
  File "/home/megabitus/.sickrage/sickbeard/subtitles.py", line 25, in <module>
    from sickbeard import helpers
ImportError: cannot import name helpers
```
Sickrage won't start anymore, can anyone help?

**Comment by megabitus98** [comment]
I did a sudo git pull, and now it works again.

**Comment by Arcanemagus** [comment]
I hit this too, shortly after getting the alert that it was updating between these two revisions: https://github.com/SiCKRAGETV/SickRage/compare/57760adc12e1559e8baa68564c064a6807769e9e...50e1c30a3f53fc623e70483f758c1a9f96ea38d1

It looks like it was fixed in https://github.com/SiCKRAGETV/SickRage/commit/c2436b4f76029bfe903ba4a4bb0792a1d2f6c6aa so anyone that updated before that was pushed will be in the same state.
