### ISSUE TITLE
Subtitles not found on opensubtitles

### ISSUE THREAD

**Issue by hlavicka** [SiCKRAGETV/sickrage-issues#2050]
Hi @miigotu 
I have only enabled opensubtitles plugin to download subtitles and there are no subtitles found by SR even if they are found by standalone subliminal using command line. To trace the issue I have used the subliminal logging lines in tv.py and this is the output:

```
Scanning video u'Game.of.Thrones.S05E04.HDTV.x264-Xclusive.mp4' in u'/i-data/md0/video/TVShows/Game of Thrones'
Size is 358482656
Computed hashes {u'opensubtitles': u'6839bd3b8c023ec4', u'thesubdb': 'd8369fd0fa431460886f0b2ab7dc1e42'}
Found subtitles set([])
Listing subtitles for <Episode [u'Game of Thrones', 5x4]>
Listing subtitles for <Episode [u'Game of Thrones', 5x4]>
Unexpected error in provider 'opensubtitles', discarding it
Traceback (most recent call last):
  File "/ffp/opt/Sick-Beard-TvRage/lib/subliminal/providers/__init__.py", line 290, in list_subtitles
    provider = self.get_initialized_provider(provider_name)
  File "/ffp/opt/Sick-Beard-TvRage/lib/subliminal/providers/__init__.py", line 262, in get_initialized_provider
    provider.initialize()
  File "/ffp/opt/Sick-Beard-TvRage/lib/subliminal/providers/opensubtitles.py", line 92, in initialize
    response = checked(self.server.LogIn('', '', 'eng', 'subliminal v%s' % __version__.split('-')[0]))
  File "/ffp/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/ffp/lib/python2.7/xmlrpclib.py", line 1591, in __request
    verbose=self.__verbose
  File "/ffp/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/ffp/lib/python2.7/xmlrpclib.py", line 1321, in single_request
    response.msg,
ProtocolError: <ProtocolError for api.opensubtitles.org/xml-rpc: 503 Service Unavailable>
Found 0 subtitles total

```

Here is the log for the same tv show when downloading subtitle using cli https://gist.github.com/hlavicka/3e957845a30621990d39

**Comment by fernandog** [comment]
As you can see in log "503 Service Unavailable>
Found 0 subtitles total"

Opensubtitles is well known about this.

**Comment by miigotu** [comment]
We cannot control if the service is down.

**Comment by fernandog** [comment]
@miigotu
We should catch this error and show a warning. Or we will have tons of this 503 url error everyday.
something we can do in SR or only in subliminal?

**Comment by miigotu** [comment]
@fernandog subliminal already handles this error correctly, OP just enabled the subliminal debug logging I left commented in https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/tv.py#L1440

**Comment by hlavicka** [comment]
I'm sorry to bother you with this, but I don't agree. Since the update SR does not download from opensubtitles. Using command line subliminal always downloads. Please have a look at it again. At least try your self to download subtitles for czech language. Thanks in advance.

**Comment by miigotu** [comment]
`ProtocolError: <ProtocolError for api.opensubtitles.org/xml-rpc: 503 Service Unavailable>`
You can not believe me, but logs don't lie. http://bfy.tw/lPb

There is an api limit of 100 downloads in 12 hours also.

https://github.com/Diaoul/subliminal/issues/63

**Comment by fernandog** [comment]
in the past before this update this error was a warning

Issues:
https://github.com/SiCKRAGETV/sickrage-issues/issues?utf8=%E2%9C%93&q=is%3Aissue+opensubtitles+503+service+unavailable+is%3Aclosed+

fix in the old version:
https://github.com/SiCKRAGETV/SickRage/pull/1348/files

**Comment by miigotu** [comment]
@fernandog this error doesnt show up in SR, he just enabled debug logging for subliminal itself.

**Comment by fernandog** [comment]
i know. I was telling it's a common issue from opensubtitle the 503 error

**Comment by hlavicka** [comment]
I see, I think I found another error message in the log. Its saying that imdbid is not number

```
Unexpected error in provider 'opensubtitles', discarding it
Traceback (most recent call last):
  File "/ffp/opt/Sick-Beard-TvRage/lib/subliminal/providers/__init__.py", line 292, in list_subtitles
    provider_subtitles = provider.list_subtitles(video, provider_languages)
  File "/ffp/opt/Sick-Beard-TvRage/lib/subliminal/providers/opensubtitles.py", line 140, in list_subtitles
    query=query, season=season, episode=episode)
  File "/ffp/opt/Sick-Beard-TvRage/lib/subliminal/providers/opensubtitles.py", line 117, in query
    response = checked(self.server.SearchSubtitles(self.token, searches))
  File "/ffp/opt/Sick-Beard-TvRage/lib/subliminal/providers/opensubtitles.py", line 205, in checked
    raise OpenSubtitlesError(response['status'])
OpenSubtitlesError: 408 Invalid parameters; imdbid is not number
```
Maybe this is why subtitles are not downloaded. Also it seems that with each new file scanned every action is executed by subliminal one more time. First video is scanned once, second is scanned twice, fifth is scanned five times. Here is the debug log just for the subliminal https://gist.github.com/hlavicka/5a546c7749c7b9ea1868

**Comment by miigotu** [comment]
@hlavicka now that imdb error makes more sense. I'll have to check into the extra scans because that makes no sense.

**Comment by miigotu** [comment]
Not sure why they want a number as all imdb id's start with `tt`

**Comment by miigotu** [comment]
```
17:27:12 DEBUG::FINDSUBTITLES :: Downloading subtitles for episode 5x4 of show Game of Thrones
17:27:12 DEBUG::FINDSUBTITLES :: 121361: Downloading subtitles for S05E04
17:27:12 DEBUG::FINDSUBTITLES :: 121361: No release name for S05E04, using existing file name
17:27:30 DEBUG::FINDSUBTITLES :: 121361: Saving episode details to database
17:27:30 DEBUG::FINDSUBTITLES :: STATUS IS 6402
17:27:30 DEBUG::FINDSUBTITLES :: 121361: Downloaded French, Dutch, English, Spanish, German, Italian subtitles for S05E04
17:27:30 DEBUG::FINDSUBTITLES :: Parsed /home/dusted/Projects/SickRage/Shows/Game of Thrones/Season 05/Game of Thrones - S05E04 - Sons of the Harpy into Game of Thrones - S5E4 [ANIME VER: -1] [ABD: False] [ANIME: False] [whichReg: ['standard', 'season_only']]
17:27:30 DEBUG::FINDSUBTITLES :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
17:27:30 DEBUG::FINDSUBTITLES :: formatting pattern: %SN - %Sx%0E - %EN -> Game of Thrones - 5x04 - Sons of the Harpy
17:27:30 DEBUG::FINDSUBTITLES :: Notification for NMJ scan update not enabled, skipping this notification
17:27:30 DEBUG::FINDSUBTITLES :: history.logSubtitle thesubdb, eng
17:27:30 DEBUG::FINDSUBTITLES :: history.logSubtitle thesubdb, spa
17:27:30 DEBUG::FINDSUBTITLES :: history.logSubtitle opensubtitles, ita
17:27:31 DEBUG::FINDSUBTITLES :: history.logSubtitle opensubtitles, fra
17:27:31 DEBUG::FINDSUBTITLES :: history.logSubtitle opensubtitles, nld
17:27:31 DEBUG::FINDSUBTITLES :: history.logSubtitle opensubtitles, deu
17:27:31 INFO::FINDSUBTITLES :: Downloaded subtitles for S05E04 in fra, nld, eng, spa, deu, ita
```

```
17:38:54 DEBUG::Thread-35 :: 121361: Downloading subtitles for S05E03
17:38:54 DEBUG::Thread-35 :: 121361: No release name for S05E03, using existing file name
17:39:14 DEBUG::Thread-35 :: 121361: Saving episode details to database
17:39:14 DEBUG::Thread-35 :: STATUS IS 6402
17:39:14 DEBUG::Thread-35 :: 121361: Downloaded Czech subtitles for S05E03
17:39:14 DEBUG::Thread-35 :: Parsed /home/dusted/Projects/SickRage/Shows/Game of Thrones/Season 05/Game of Thrones - S05E03 - High Sparrow into Game of Thrones - S5E3 [ANIME VER: -1] [ABD: False] [ANIME: False] [whichReg: ['standard', 'season_only']]
17:39:14 DEBUG::Thread-35 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
17:39:14 DEBUG::Thread-35 :: formatting pattern: %SN - %Sx%0E - %EN -> Game of Thrones - 5x03 - High Sparrow
17:39:14 DEBUG::Thread-35 :: Notification for NMJ scan update not enabled, skipping this notification
17:39:14 DEBUG::Thread-35 :: history.logSubtitle opensubtitles, ces
```

**Comment by miigotu** [comment]
Also, this is with a renamed file.
