### ISSUE TITLE
TNTvillage provider not working

### ISSUE THREAD

**Issue by johnkillerbob** [SiCKRAGETV/sickrage-issues#2062]
When doing a backlog search I get multiple errors like this:
```
2015-07-11 12:49:50 SEARCHQUEUE-BACKLOG-121361 :: Failed parsing TNTVillage Traceback: Traceback (most recent call last):
  File "/home/john/.sickrage/sickbeard/providers/tntvillage.py", line 436, in _doSearch
    if not self._is_italian(result) and not self.subtitle:
  File "/home/john/.sickrage/sickbeard/providers/tntvillage.py", line 309, in _is_italian
    if not re.search(sub, name, re.I):
  File "/usr/lib/python2.7/re.py", line 142, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer
```

**Comment by neoatomic** [comment]
Please add the missing info. : 
https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

**Comment by miigotu** [comment]
Been fixed in develop: 

SiCKRAGETV/SickRage#2066
