### ISSUE TITLE
Error Getting Log Using Web API  CMD_Logs

### ISSUE THREAD

**Issue by Hiltronix** [SiCKRAGETV/sickrage-issues#2104]
Retrieving the SickRage log using the webapi returns error when the log contains non English characters.

Example Result from API CMD_Logs:

https://192.168.0.115:8080/api/xxx/?cmd=logs&min_level=info

	{
	    "data": {
	        "args": [], 
	        "error_msg": "utf8 : 2015-07-13 20:40:26 ERROR    TORNADO :: API :: utf8 : 2015-07-13 20:39:41 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [IsoHunt] :: Unable to parse the filename Un.Sueño.Roto.SPANISH.ESPAÑOL.DVDRip.XviD-DVXT into a valid show\n : error 159 : error 160 : invalid continuation byte", 
	        "kwargs": {
	            "min_level": "info"
	        }
	    }, 
	    "message": "SickRage encountered an internal error! Please report to the Devs", 
	    "result": "fatal"
	}

Section of error log during this call:

	2015-07-13 20:40:26 DEBUG TORNADO :: API :: 192.168.0.115 - gave correct API KEY. ACCESS GRANTED
	2015-07-13 20:40:26 DEBUG TORNADO :: API :: all args: '()'
	2015-07-13 20:40:26 DEBUG TORNADO :: API :: all kwargs: '{'min_level': 'info', 'cmd': 'logs'}'
	2015-07-13 20:40:26 DEBUG TORNADO :: API :: logs: curKwargs {'min_level': 'info'}
	2015-07-13 20:40:26 ERROR TORNADO :: API :: utf8 : 2015-07-13 20:39:41 DEBUG SEARCHQUEUE-DAILY-SEARCH :: [IsoHunt] :: Unable to parse the filename Un.Sueño.Roto.SPANISH.ESPAÑOL.DVDRip.XviD-DVXT into a valid show
	: error 105 : error 106 : invalid continuation byte
	Traceback (most recent call last):
	File "D:\SickRage\sickbeard\webapi.py", line 118, in get
	outDict = _call_dispatcher(args, kwargs)
	File "D:\SickRage\sickbeard\webapi.py", line 188, in call_dispatcher
	curOutDict = func(curArgs, curKwargs).run()
	File "D:\SickRage\sickbeard\webapi.py", line 1341, in run
	x = x.decode('utf-8')
	File "D:\Development\Python27\lib\encodings\utf_8.py", line 16, in decode
	return codecs.utf_8_decode(input, errors, True)
	UnicodeDecodeError: 'utf8' codec can't decode byte 0xf1 in position 105: invalid continuation byte

I'm running Python 2.7 64bit.
BRANCH: (master) / COMMIT: (010325315d75ed7aab47619b57106bcca6d280f6) 

If I comment out line 1341 from webapi.py 
x = x.decode('utf-8')
and restart SickRage, the same log file can then be processed without error.  Not my suggested fix, just insight from my experimenting to resolve the error.

**Comment by miigotu** [comment]
That is exactly the fix that needs done. codecs.open returns unicode, so attempting to decode to unicode from utf-8 when the data is already unicode is a problem.
