### ISSUE TITLE
ImportError: cannot import name helpers

### ISSUE THREAD

**Issue by Rek-SSU** [SiCKRAGETV/sickrage-issues#2117]
Having an issues start SickRage all the sudden....

When trying to start SickRage via "service sickrage start" I get the error below.
OS : Ubuntu 14.04.2
Version : Python 2.7.6
Branch : master

`Starting SickRage
Traceback (most recent call last):
  File "SickBeard.py", line 90, in <module>
    import sickbeard
  File "/home/user/.sickrage/sickbeard/__init__.py", line 37, in <module>
    from sickbeard import providers, metadata, config, webserveInit
  File "/home/user/.sickrage/sickbeard/providers/__init__.py", line 54, in <module>
    import generic
  File "/home/user/.sickrage/sickbeard/providers/generic.py", line 32, in <module>
    from sickbeard import helpers, classes, logger, db
  File "/home/user/.sickrage/sickbeard/helpers.py", line 60, in <module>
    from sickbeard.subtitles import isValidLanguage
  File "/home/user/.sickrage/sickbeard/subtitles.py", line 25, in <module>
    from sickbeard import helpers
ImportError: cannot import name helpers`

**Comment by miigotu** [comment]
cd into the SickRage dir, and do `git pull`
There was a broken commit where a double import broke startup, and could not be auto-updated
