### ISSUE TITLE
[APP SUBMITTED]: u'nld'

### ISSUE THREAD

**Issue by NLEagle1** [SiCKRAGETV/sickrage-issues#2123]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@608c06810abb05ab6e9d07947c86d42b1b1a21c2
Link to Log: https://gist.github.com/adeaeccedafd38cf229b
### ERROR
```
Thread-105 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 1320, in displayShow
    return t.respond()
  File "/usr/local/sickrage/var/cache/cheetah/_usr_local_sickrage_var_SickRage_gui_slick_interfaces_default_displayShow_tmpl.py", line 1335, in respond
    for sub_lang in [VFN(VFFSL(SL,"subtitles",True),"fromietf",False)(x) for x in VFN(VFFSL(SL,"epResult",True)["subtitles"],"split",False)(',') if VFFSL(SL,"epResult",True)["subtitles"]]: # generated from line 581, col 13
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/subtitles.py", line 70, in fromietf
    return babelfish.Language.fromopensubtitles(language)
  File "/usr/local/sickrage/var/SickRage/lib/babelfish/language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/usr/local/sickrage/var/SickRage/lib/babelfish/converters/opensubtitles.py", line 36, in reverse
    raise LanguageReverseError(opensubtitles)
LanguageReverseError: u'nld'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Edit config and remove languages from your ini at `subtitles_languages=`, then set your languages again using the ui.
