### ISSUE TITLE
SickRage stopped working after last release

### ISSUE THREAD

**Issue by palmfighter** [SiCKRAGETV/sickrage-issues#2132]
Hi,

Big issue, when clicking on a show I go back to the main screen. No way of selecting a series anymore. 

Build:
BRANCH: (master) / COMMIT: (608c06810abb05ab6e9d07947c86d42b1b1a21c2) 

Error:
```
2015-07-15 16:10:26 Thread-69 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1320, in displayShow
    return t.respond()
  File "/usr/local/sickbeard-custom/var/cache/cheetah/_usr_local_sickbeard_custom_var_SickBeard_gui_slick_interfaces_default_displayShow_tmpl.py", line 1335, in respond
    for sub_lang in [VFN(VFFSL(SL,"subtitles",True),"fromietf",False)(x) for x in VFN(VFFSL(SL,"epResult",True)["subtitles"],"split",False)(',') if VFFSL(SL,"epResult",True)["subtitles"]]: # generated from line 581, col 13
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/subtitles.py", line 70, in fromietf
    return babelfish.Language.fromopensubtitles(language)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/babelfish/language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/babelfish/converters/opensubtitles.py", line 36, in reverse
    raise LanguageReverseError(opensubtitles)
LanguageReverseError: u'nld'
```

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/2125
