### ISSUE TITLE
[APP SUBMITTED]: u'nld'

### ISSUE THREAD

**Issue by discofris** [SiCKRAGETV/sickrage-issues#2136]
### INFO
Python Version: **2.7.6 (default, Sep  9 2014, 15:04:36) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]**
Operating System: **Darwin-14.4.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@608c06810abb05ab6e9d07947c86d42b1b1a21c2
Link to Log: https://gist.github.com/4de5028cfe54ca24f704
### ERROR
```
Thread-24 :: Failed doing webui callback: Traceback (most recent call last):
  File "/Users/Davy/Stuff/SickRage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/Users/Davy/Stuff/SickRage/sickbeard/webserve.py", line 1320, in displayShow
    return t.respond()
  File "/Users/Davy/Stuff/SickRage/cache/cheetah/_Users_Davy_Stuff_SickRage_gui_slick_interfaces_default_displayShow_tmpl.py", line 1335, in respond
    for sub_lang in [VFN(VFFSL(SL,"subtitles",True),"fromietf",False)(x) for x in VFN(VFFSL(SL,"epResult",True)["subtitles"],"split",False)(',') if VFFSL(SL,"epResult",True)["subtitles"]]: # generated from line 581, col 13
  File "/Users/Davy/Stuff/SickRage/sickbeard/subtitles.py", line 70, in fromietf
    return babelfish.Language.fromopensubtitles(language)
  File "/Users/Davy/Stuff/SickRage/lib/babelfish/language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/Users/Davy/Stuff/SickRage/lib/babelfish/converters/opensubtitles.py", line 36, in reverse
    raise LanguageReverseError(opensubtitles)
LanguageReverseError: u'nld'

```
### TO REPRODUCE
Update to latest version.
When clicking a show name in the Poster layout, it doesn't go to the single show view. It stays on the homepage. Occurs on every layout ...
Already tried disabling the Subtitles Search plugin as the errors point somewhat into that direction. But no luck :-(.
Only reproducable on some shows. 'Better Call Saul' goest to the show page.
Got a feeling it has got something to do with the broken country flags ... ?

---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/2125#issuecomment-121740934
