### ISSUE TITLE
Clicking on a show gives error and returns to "Shows" view

### ISSUE THREAD

**Issue by DeBaard** [SiCKRAGETV/sickrage-issues#2138]
Since the latest update there is a little problem here. When clicking on a show in the "shows" list Sickrage  seemingly refreshes the "Shows" list. Also an error is written in the log, it's this one:

2015-07-15 21:43:43 Thread-17 :: Failed doing webui callback: Traceback (most recent call last):
  File "/Users/mediacenter/Apps/sickbeard/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/Users/mediacenter/Apps/sickbeard/sickbeard/webserve.py", line 1320, in displayShow
    return t.respond()
  File "/Users/mediacenter/Apps/sickbeard/cache/cheetah/_Users_mediacenter_Apps_sickbeard_gui_slick_interfaces_default_displayShow_tmpl.py", line 1335, in respond
    for sub_lang in [VFN(VFFSL(SL,"subtitles",True),"fromietf",False)(x) for x in VFN(VFFSL(SL,"epResult",True)["subtitles"],"split",False)(',') if VFFSL(SL,"epResult",True)["subtitles"]]: # generated from line 581, col 13
  File "/Users/mediacenter/Apps/sickbeard/sickbeard/subtitles.py", line 70, in fromietf
    return babelfish.Language.fromopensubtitles(language)
  File "/Users/mediacenter/Apps/sickbeard/lib/babelfish/language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/Users/mediacenter/Apps/sickbeard/lib/babelfish/converters/opensubtitles.py", line 36, in reverse
    raise LanguageReverseError(opensubtitles)
LanguageReverseError: u'nld'

**Comment by renini** [comment]
I have the same issue, i'm using it behind a apache reverse proxy. You?
