### ISSUE TITLE
[APP SUBMITTED]: u'fra'

### ISSUE THREAD

**Issue by mstraa** [SiCKRAGETV/sickrage-issues#2139]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-3.18.13-1-osmc-armv7l-with-debian-8.1**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@608c06810abb05ab6e9d07947c86d42b1b1a21c2
Link to Log: https://gist.github.com/5e9536046c0acdcbe2fe
### ERROR
```
Thread-61 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1320, in displayShow
    return t.respond()
  File "/opt/sickrage/cache/cheetah/_opt_sickrage_gui_slick_interfaces_default_displayShow_tmpl.py", line 1335, in respond
    for sub_lang in [VFN(VFFSL(SL,"subtitles",True),"fromietf",False)(x) for x in VFN(VFFSL(SL,"epResult",True)["subtitles"],"split",False)(',') if VFFSL(SL,"epResult",True)["subtitles"]]: # generated from line 581, col 13
  File "/opt/sickrage/sickbeard/subtitles.py", line 70, in fromietf
    return babelfish.Language.fromopensubtitles(language)
  File "/opt/sickrage/lib/babelfish/language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/opt/sickrage/lib/babelfish/converters/opensubtitles.py", line 36, in reverse
    raise LanguageReverseError(opensubtitles)
LanguageReverseError: u'fra'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Read all this
https://github.com/SiCKRAGETV/sickrage-issues/issues/2125
