### ISSUE TITLE
[APP SUBMITTED]: u'ron'

### ISSUE THREAD

**Issue by megabitus98** [SiCKRAGETV/sickrage-issues#2144]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-43-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@608c06810abb05ab6e9d07947c86d42b1b1a21c2
Link to Log: https://gist.github.com/6cf3e1b776f964c56f58
### ERROR
```
Thread-52 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/megabitus/.sickrage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/home/megabitus/.sickrage/sickbeard/webserve.py", line 1320, in displayShow
    return t.respond()
  File "/home/megabitus/.sickrage/cache/cheetah/_home_megabitus__sickrage_gui_slick_interfaces_default_displayShow_tmpl.py", line 1335, in respond
    for sub_lang in [VFN(VFFSL(SL,"subtitles",True),"fromietf",False)(x) for x in VFN(VFFSL(SL,"epResult",True)["subtitles"],"split",False)(',') if VFFSL(SL,"epResult",True)["subtitles"]]: # generated from line 581, col 13
  File "/home/megabitus/.sickrage/sickbeard/subtitles.py", line 70, in fromietf
    return babelfish.Language.fromopensubtitles(language)
  File "/home/megabitus/.sickrage/lib/babelfish/language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/home/megabitus/.sickrage/lib/babelfish/converters/opensubtitles.py", line 36, in reverse
    raise LanguageReverseError(opensubtitles)
LanguageReverseError: u'ron'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/2125#issuecomment-121740934
