### ISSUE TITLE
Failed doing webui callback

### ISSUE THREAD

**Issue by Paradoxx2015** [SiCKRAGETV/sickrage-issues#2152]
When i was updating statuses on shows.

SR Version:	BRANCH: (master) / COMMIT: (efdad7f24b806536abee630cd98211b6f64997b4) 
Python Version:	2.7.10 (default, Jun 3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]

Error log:
```
2015-07-16 08:14:23 Thread-24 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 270, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 2897, in changeEpisodeStatuses
    self.setStatus(cur_indexer_id, '|'.join(to_change[cur_indexer_id]), newStatus, direct=True)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 1735, in setStatus
    epObj = showObj.getEpisode(int(epInfo[0]), int(epInfo[1]))
ValueError: invalid literal for int() with base 10: ''
```

**Comment by miigotu** [comment]
STOP OPENING NEW ISSUES FOR THE SAME PROBLEM
