### ISSUE TITLE
[APP SUBMITTED]: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by Aesculapius** [SiCKRAGETV/sickrage-issues#2163]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-57-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@8e38759d53db01998426e0add03e089be5076007
Link to Log: https://gist.github.com/4e9d3e47509d8f81f9b9
### ERROR
```
FINDSUBTITLES :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "/home/laurens/.sickrage/sickbeard/tv.py", line 1473, in downloadSubtitles
    foundSubs = subliminal.download_best_subtitles([video], languages=languages, providers=providers, single=not sickbeard.SUBTITLES_MULTI, hearing_impaired=False)
  File "/home/laurens/.sickrage/lib/subliminal/api.py", line 88, in download_best_subtitles
    for subtitle, score in sorted([(s, s.compute_score(video)) for s in video_subtitles],
  File "/home/laurens/.sickrage/lib/subliminal/subtitle.py", line 131, in compute_score
    initial_matches = self.compute_matches(video)
  File "/home/laurens/.sickrage/lib/subliminal/providers/opensubtitles.py", line 61, in compute_matches
    matches |= compute_guess_matches(video, guessit.guess_episode_info(self.movie_release_name + '.mkv'))
  File "/home/laurens/.sickrage/lib/guessit/__init__.py", line 358, in guess_episode_info
    return guess_file_info(filename, info=info, options=options, type='episode', **kwargs)
  File "/home/laurens/.sickrage/lib/guessit/__init__.py", line 290, in guess_file_info
    result.append(_guess_filename(filename, options, **kwargs))
  File "/home/laurens/.sickrage/lib/guessit/__init__.py", line 110, in _guess_filename
    mtree = _build_filename_mtree(filename, options=options, **kwargs)
  File "/home/laurens/.sickrage/lib/guessit/__init__.py", line 123, in _build_filename_mtree
    mtree = IterativeMatcher(filename, options=merged_options, **kwargs)
  File "/home/laurens/.sickrage/lib/guessit/matcher.py", line 120, in __init__
    self._process(transformer, False)
  File "/home/laurens/.sickrage/lib/guessit/matcher.py", line 138, in _process
    transformer.process(self.match_tree, self.options)
  File "/home/laurens/.sickrage/lib/guessit/transfo/guess_episodes_rexps.py", line 195, in process
    GuessFinder(self.guess_episodes_rexps, None, self.log, options).process_nodes(mtree.unidentified_leaves())
  File "/home/laurens/.sickrage/lib/guessit/matcher.py", line 236, in process_nodes
    self.process_node(node)
  File "/home/laurens/.sickrage/lib/guessit/matcher.py", line 308, in process_node
    self.process_node(node, partial_span=partition_span)
  File "/home/laurens/.sickrage/lib/guessit/matcher.py", line 308, in process_node
    self.process_node(node, partial_span=partition_span)
  File "/home/laurens/.sickrage/lib/guessit/matcher.py", line 308, in process_node
    self.process_node(node, partial_span=partition_span)
 
{this goes on for like hundreds time}

  File "/home/laurens/.sickrage/lib/guessit/matcher.py", line 308, in process_node
    self.process_node(node, partial_span=partition_span)
  File "/home/laurens/.sickrage/lib/guessit/matcher.py", line 308, in process_node
    self.process_node(node, partial_span=partition_span)
  File "/home/laurens/.sickrage/lib/guessit/matcher.py", line 276, in process_node
    tmp_node = MatchTree(value, span=partition_span, parent=node)
  File "/home/laurens/.sickrage/lib/guessit/matchtree.py", line 83, in __init__
    self.guess = Guess()
  File "/home/laurens/.sickrage/lib/guessit/guess.py", line 148, in __init__
    metadata_kwargs, kwargs = _split_kwargs(**kwargs)
  File "/home/laurens/.sickrage/lib/guessit/guess.py", line 132, in _split_kwargs
    for prop in dir(GuessMetadata):
RuntimeError: maximum recursion depth exceeded while calling a Python object
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Still happen if you update to latest master? I cannot reproduce this nor do I know where to look. 

If it still happens with latest master, put the full log (with debug enabled) up on gist and link it here mentioning me.

**Comment by Aesculapius** [comment]
Still happening after latest update indeed. I've now cleared the log and enabled debug logging so we'll see...

**Comment by miigotu** [comment]
Do you know which video this happens on? Seems to be a bug in guessit, not SR.

**Comment by fernandog** [comment]
https://github.com/wackou/guessit/issues/209

**Comment by fernandog** [comment]
@Aesculapius can you tell us the filename that raised this?

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/2176

**Comment by fernandog** [comment]
@Aesculapius please?

**Comment by fernandog** [comment]
@Aesculapius please reply or will close this issue

**Comment by Aesculapius** [comment]
Whow that happened fast :) I was still waiting for it to happen again after I turned on debug logging, as I could find out the filename this was happening to from the normal logging.
But it appears to happen to the following episode:

Error occurred when downloading subtitles for: /media/st01/Series_1/The X-Files/X-Files.S02.DVDRip.XviD-SDG/X-Files.2x18.Fearful_Symmetry.DVDRip.XviD-SDG.avi

**Comment by miigotu** [comment]
Someone needs to make an issue report to guessit repo with this filename, and the error log.

**Comment by miigotu** [comment]
Actually not sure about this one,

```bash
For: /media/st01/Series_1/The X-Files/X-Files.S02.DVDRip.XviD-SDG/X-Files.2x18.Fearful_Symmetry.DVDRip.XviD-SDG.avi
GuessIt found: {
    [1.00] "mimetype": "video/x-msvideo", 
    [1.00] "episodeNumber": 18, 
    [1.00] "videoCodec": "XviD", 
    [1.00] "container": "avi", 
    [1.00] "format": "DVD", 
    [0.50] "series": "X-Files", 
    [0.50] "title": "Fearful Symmetry", 
    [1.00] "releaseGroup": "SDG", 
    [0.60] "season": 2, 
    [1.00] "type": "episode"
}
```

**Comment by fernandog** [comment]
@miigotu maybe file metadata is too long crashing GuessMetadata?

**Comment by miigotu** [comment]
Yeah maybe the guess works for me because I don't have the file.

**Comment by fernandog** [comment]
@miigotu how the user can easyly post metadata here?

**Comment by miigotu** [comment]
We can't have them posting file contents on github, for DMCA reasons. Github could shut the repo down for things like that.

**Comment by fernandog** [comment]
not file contents. just metadata.

**Comment by Aesculapius** [comment]
Can I make an export of the file meta data somehow? Would be more than happy to share...

**Comment by miigotu** [comment]
I have no clue how. Google might help =P he's pretty smart.

**Comment by fernandog** [comment]
@miigotu already fixed upstream

**Comment by fernandog** [comment]
fixed upstream in
https://github.com/wackou/guessit/commit/15bb35b885b94c6494fbfbdf872890d0717dfabf

**Comment by miigotu** [comment]
we need to update guessit again. As for subliminal, its still waiting for some changes before I finish trying to update to 1.0

**Comment by miigotu** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/2221
