### ISSUE TITLE
[APP SUBMITTED]: No module named bierdopje

### ISSUE THREAD

**Issue by HardbitCoded** [SiCKRAGETV/sickrage-issues#2178]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 23:30:12) [GCC 4.8.2]**
Operating System: **Linux-3.4.61+-armv7l-with-Linaro-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@0657d64e2d0d3feb159d0a41e9b3a407cf520618
Link to Log: https://gist.github.com/8b1806c1ba3c4316fa87
### ERROR
```
FINDSUBTITLES :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "/home/rui/SickRage/sickbeard/tv.py", line 1473, in downloadSubtitles
    foundSubs = subliminal.download_best_subtitles([video], languages=languages, providers=providers, single=not sickbeard.SUBTITLES_MULTI, hearing_impaired=False)
  File "/home/rui/SickRage/lib/subliminal/api.py", line 74, in download_best_subtitles
    with ProviderPool(providers, provider_configs) as pp:
  File "/home/rui/SickRage/lib/subliminal/providers/__init__.py", line 241, in __init__
    self.providers = dict([(p, provider_manager[p]) for p in (providers or provider_manager.available_providers)])
  File "/home/rui/SickRage/lib/subliminal/providers/__init__.py", line 180, in __getitem__
    self.providers[ep.name] = ep.load()
  File "/home/rui/SickRage/lib/pkg_resources.py", line 1954, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named bierdopje

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by HardbitCoded** [comment]
Please ignore this submit
