### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/opt/sickrage/gui/slick/interfaces/default/news.tmpl'

### ISSUE THREAD

**Issue by gabestover** [SiCKRAGETV/sickrage-issues#2185]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-4.0.4-unRAID-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@e38274d6f33bc2e15092367a8e2aa6bee5e4da5f
Link to Log: https://gist.github.com/53b05eb6634c1de17e95
### ERROR
```
Thread-45 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 271, in async_call
  File "/opt/sickrage/sickbeard/webserve.py", line 2165, in index
    def index(self):
  File "/opt/sickrage/sickbeard/webserve.py", line 123, in __init__
    kwargs['filter'] = html_entities
  File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1259, in __init__
    self._compile(source, file, compilerSettings=compilerSettings)
  File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1546, in _compile
    self._fileMtime = os.path.getmtime(file)
  File "/usr/lib/python2.7/genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: '/opt/sickrage/gui/slick/interfaces/default/news.tmpl'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@gabestover make sure /opt/sickrage/gui/slick/interfaces/default/news.tmpl exists

**Comment by miigotu** [comment]
@fernandog it doesn't, it was renamed to markdown.tmpl

**Comment by miigotu** [comment]
Maybe you have editted webserve.py and the git pull failed?
