### ISSUE TITLE
[APP SUBMITTED]: [Error 2] The system cannot find the file specified: u'T:\\Downloaded Torrents\\Parks and Recreation - The Complete Season 4 [HDTV]\\Parks.and.Recreation.S04E22.HDTV.x264-LOL.mp4'

### ISSUE THREAD

**Issue by creamerssubmit** [SiCKRAGETV/sickrage-issues#2189]
### INFO
Python Version: **2.7.2 (default, Jun 12 2011, 15:08:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@e38274d6f33bc2e15092367a8e2aa6bee5e4da5f
Link to Log: https://gist.github.com/103370722784b38771e7
### ERROR
```
Thread-154 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 2233, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "C:\SickRage\sickbeard\processTV.py", line 251, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "C:\SickRage\sickbeard\processTV.py", line 491, in process_media
    result.result = processor.process()
  File "C:\SickRage\sickbeard\postProcessor.py", line 881, in process
    existing_file_status = self._checkForExistingFile(ep_obj.location)
  File "C:\SickRage\sickbeard\postProcessor.py", line 132, in _checkForExistingFile
    if ek.ek(os.path.getsize, existing_file) > ek.ek(os.path.getsize, self.file_path):
  File "C:\SickRage\sickbeard\encodingKludge.py", line 65, in ek
    result = func(*args, **kwargs)
  File "C:\Python27\lib\genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
WindowsError: [Error 2] The system cannot find the file specified: u'T:\\Downloaded Torrents\\Parks and Recreation - The Complete Season 4 [HDTV]\\Parks.and.Recreation.S04E22.HDTV.x264-LOL.mp4'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by creamerssubmit** [comment]
To note this is only happening when I have a large amount of files in the to process directory, when I have only the needed files to process it works fine. When it errors out it deletes everything in the downloaded folder as well.

**Comment by miigotu** [comment]
Don't run post processor manually. This "error" happens when the automatic post processor is running and the manual post processor had just moved the files before it is finished. The files were already processed.
