### ISSUE TITLE
[APP SUBMITTED]: 422 {u'documentation_url': u'https://developer.github.com/v3/issues/#create-an-issue', u'message': u'Validation Failed', u'errors': [{u'field': u'title', u'message': u'title is too long', u'code': u'custom', u'resource': u'Issue'}]}

### ISSUE THREAD

**Issue by ariscottle** [SiCKRAGETV/sickrage-issues#2191]
### INFO
Python Version: **2.6.1 (r261:67515, Jun 24 2010, 21:47:49) [GCC 4.2.1 (Apple Inc. build 5646)]**
Operating System: **Darwin-10.8.0-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@e38274d6f33bc2e15092367a8e2aa6bee5e4da5f
Link to Log: https://gist.github.com/48e24193ccc6fb7f75d0
### ERROR
```
Thread-60 :: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
@ariscottle Can you upload the full log so I can see both your original error and this error properly?

**Comment by miigotu** [comment]
@ariscottle Just something I noticed from your log also:
```
2015-07-17 23:51:13 INFO     POSTPROCESSER :: PostProcessing Path: /Users/scott/Desktop/Torrents
2015-07-17 23:51:13 DEBUG    POSTPROCESSER :: TV_DOWNLOAD_DIR: /Users/scott/Desktop/Torrents
2015-07-17 23:51:13 DEBUG    POSTPROCESSER :: Processing folder /Users/scott/Desktop/Torrents
```

Your tv shows root dir and post processing path cannot be the same. Your Library cannot be the same as or inside of the post processing folder.

**Comment by ariscottle** [comment]
AA
AATypeError: __init__() keywords must be strings
AA    **cached["response"]
AA  File "/Users/scott/Applications/SickRage/lib/cachecontrol/serialize.py", line 145, in prepare_response
AA    return self.prepare_response(request, cached)
AA  File "/Users/scott/Applications/SickRage/lib/cachecontrol/serialize.py", line 184, in _loads_v2
AA    return getattr(self, "_loads_v{0}".format(ver))(request, data)
AA  File "/Users/scott/Applications/SickRage/lib/cachecontrol/serialize.py", line 108, in loads
AA    resp = self.serializer.loads(request, self.cache.get(cache_url))
AA  File "/Users/scott/Applications/SickRage/lib/cachecontrol/controller.py", line 102, in cached_request
AA    cached_response = self.controller.cached_request(request)
AA  File "/Users/scott/Applications/SickRage/lib/cachecontrol/adapter.py", line 36, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/Users/scott/Applications/SickRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/Users/scott/Applications/SickRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/Users/scott/Applications/SickRage/lib/requests/sessions.py", line 476, in get
AA    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "/Users/scott/Applications/SickRage/sickbeard/helpers.py", line 1392, in getURL
2015-07-18 03:00:02 WARNING  SHOWUPDATER :: Traceback (most recent call last):
2015-07-18 03:00:02 WARNING  SHOWUPDATER :: Unknown exception in getURL http://sickragetv.github.io/sb_network_timezones/network_timezones.txt. Error: __init__() keywords must be strings
2015-07-18 03:00:02 WARNING  SHOWUPDATER :: Loading zoneinfo.txt failed, this can happen from time to time. Unable to get URL: http://sickragetv.github.io/sb_network_timezones/zoneinfo.txt
AA
AATypeError: __init__() keywords must be strings
AA    **cached["response"]
AA  File "/Users/scott/Applications/SickRage/lib/cachecontrol/serialize.py", line 145, in prepare_response
AA    return self.prepare_response(request, cached)
AA  File "/Users/scott/Applications/SickRage/lib/cachecontrol/serialize.py", line 184, in _loads_v2
AA    return getattr(self, "_loads_v{0}".format(ver))(request, data)
AA  File "/Users/scott/Applications/SickRage/lib/cachecontrol/serialize.py", line 108, in loads
AA    resp = self.serializer.loads(request, self.cache.get(cache_url))
AA  File "/Users/scott/Applications/SickRage/lib/cachecontrol/controller.py", line 102, in cached_request
AA    cached_response = self.controller.cached_request(request)
AA  File "/Users/scott/Applications/SickRage/lib/cachecontrol/adapter.py", line 36, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/Users/scott/Applications/SickRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/Users/scott/Applications/SickRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/Users/scott/Applications/SickRage/lib/requests/sessions.py", line 476, in get
AA    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "/Users/scott/Applications/SickRage/sickbeard/helpers.py", line 1392, in getURL
2015-07-18 03:00:02 WARNING  SHOWUPDATER :: Traceback (most recent call last):
2015-07-18 03:00:02 WARNING  SHOWUPDATER :: Unknown exception in getURL http://sickragetv.github.io/sb_network_timezones/zoneinfo.txt. Error: __init__() keywords must be strings
2015-07-18 02:51:14 INFO     POSTPROCESSER :: Processing completed
2015-07-18 02:51:14 INFO     POSTPROCESSER :: PostProcessing Path: /Users/scott/Desktop/Torrents
2015-07-18 02:41:14 INFO     POSTPROCESSER :: Processing completed
2015-07-18 02:41:14 INFO     POSTPROCESSER :: PostProcessing Path: /Users/scott/Desktop/Torrents
2015-07-18 02:31:14 INFO     POSTPROCESSER :: Processing completed
2015-07-18 02:31:14 INFO     POSTPROCESSER :: PostProcessing Path: /Users/scott/Desktop/Torrents
2015-07-18 02:21:14 INFO     POSTPROCESSER :: Processing completed
2015-07-18 02:21:14 INFO     POSTPROCESSER :: PostProcessing Path: /Users/scott/Desktop/Torrents
2015-07-18 02:21:11 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2015-07-18 02:21:10 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2015-07-18 02:21:10 INFO     DAILYSEARCHER :: No new released episodes found ...
2015-07-18 02:21:10 INFO     DAILYSEARCHER :: Searching for new released episodes ...
2015-07-18 02:11:14 INFO     POSTPROCESSER :: Processing completed
2015-07-18 02:11:14 INFO     POSTPROCESSER :: PostProcessing Path: /Users/scott/Desktop/Torrents
2015-07-18 02:01:14 INFO     POSTPROCESSER :: Processing completed
2015-07-18 02:01:14 INFO     POSTPROCESSER :: PostProcessing Path: /Users/scott/Desktop/Torrents
2015-07-18 01:51:14 INFO     POSTPROCESSER :: Processing completed
2015-07-18 01:51:14 INFO     POSTPROCESSER :: PostProcessing Path: /Users/scott/Desktop/Torrents
2015-07-18 01:41:14 INFO     POSTPROCESSER :: Processing completed
2015-07-18 01:41:14 INFO     POSTPROCESSER :: PostProcessing Path: /Users/scott/Desktop/Torrents
2015-07-18 01:41:12 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2015-07-18 01:41:10 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2015-07-18 01:41:10 INFO     DAILYSEARCHER :: No new released episodes found ...
2015-07-18 01:41:10 INFO     DAILYSEARCHER :: Searching for new released episodes ...
2015-07-18 01:31:14 INFO     POSTPROCESSER :: Processing completed
2015-07-18 01:31:14 INFO     POSTPROCESSER :: PostProcessing Path: /Users/scott/Desktop/Torrents
2015-07-18 01:21:13 INFO     POSTPROCESSER :: Processing completed
2015-07-18 01:21:13 INFO     POSTPROCESSER :: PostProcessing Path: /Users/scott/Desktop/Torrents
2015-07-18 01:11:13 INFO     POSTPROCESSER :: Processing completed
2015-07-18 01:11:13 INFO     POSTPROCESSER :: PostProcessing Path: /Users/scott/Desktop/Torrents
2015-07-18 01:01:13 INFO     POSTPROCESSER :: Processing completed
2015-07-18 01:01:13 INFO     POSTPROCESSER :: PostProcessing Path: /Users/scott/Desktop/Torrents
2015-07-18 01:01:11 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2015-07-18 01:01:10 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2015-07-18 01:01:09 INFO     DAILYSEARCHER :: No new released episodes found ...
2015-07-18 01:01:09 INFO     DAILYSEARCHER :: Searching for new released episodes ...
2015-07-18 00:51:13 INFO     POSTPROCESSER :: Processing completed
2015-07-18 00:51:13 INFO     POSTPROCESSER :: PostProcessing Path: /Users/scott/Desktop/Torrents
2015-07-18 00:41:13 INFO     POSTPROCESSER :: Processing completed
2015-07-18 00:41:13 INFO     POSTPROCESSER :: PostProcessing Path: /Users/scott/Desktop/Torrents
2015-07-18 00:31:13 INFO     POSTPROCESSER :: Processing completed
2015-07-18 00:31:13 INFO     POSTPROCESSER :: PostProcessing Path: /Users/scott/Desktop/Torrents
2015-07-18 00:21:13 INFO     POSTPROCESSER :: Processing completed
2015-07-18 00:21:13 INFO     POSTPROCESSER :: PostProcessing Path: /Users/scott/Desktop/Torrents
2015-07-18 00:21:11 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2015-07-18 00:21:09 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2015-07-18 00:21:09 INFO     DAILYSEARCHER :: No new released episodes found ...
2015-07-18 00:21:09 INFO     DAILYSEARCHER :: Searching for new released episodes ...
2015-07-18 00:11:13 INFO     POSTPROCESSER :: Processing completed
2015-07-18 00:11:13 INFO     POSTPROCESSER :: PostProcessing Path: /Users/scott/Desktop/Torrents
2015-07-18 00:01:13 INFO     POSTPROCESSER :: Processing completed
2015-07-18 00:01:13 INFO     POSTPROCESSER :: PostProcessing Path: /Users/scott/Desktop/Torrents
2015-07-17 23:52:58 INFO     Thread-63 :: Your issue ticket #2191 was submitted successfully!
AAGithubException: 422 {u'documentation_url': u'https://developer.github.com/v3/issues/#create-an-issue', u'message': u'Validation Failed', u'errors': [{u'field': u'title', u'message': u'title is too long', u'code': u'custom', u'resource': u'Issue'}]}
AA    raise self.__createException(status, responseHeaders, output)
AA  File "/Users/scott/Applications/SickRage/lib/github/Requester.py", line 177, in __check
AA    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
AA  File "/Users/scott/Applications/SickRage/lib/github/Requester.py", line 169, in requestJsonAndCheck
AA    input=post_parameters
AA  File "/Users/scott/Applications/SickRage/lib/github/Repository.py", line 857, in create_issue
AA    issue = gh.get_organization(gh_org).get_repo(gh_repo).create_issue(title_Error, message)
AA  File "/Users/scott/Applications/SickRage/sickbeard/logger.py", line 253, in submit_errors
AATraceback (most recent call last):
2015-07-17 23:52:41 ERROR    Thread-60 :: 
2015-07-17 23:51:13 INFO     POSTPROCESSER :: Processing completed
2015-07-17 23:51:13 INFO     POSTPROCESSER :: PostProcessing Path: /Users/scott/Desktop/Torrents
2015-07-17 23:47:45 INFO     Thread-60 :: Please set your GitHub username and password in the config, unable to submit issue ticket to GitHub!
2015-07-17 23:43:14 INFO     Thread-54 :: Please set your GitHub username and password in the config, unable to submit issue ticket to GitHub!
AA
AATypeError: __init__() keywords must be strings
AA    **cached["response"]
AA  File "/Users/scott/Applications/SickRage/lib/cachecontrol/serialize.py", line 145, in prepare_response
AA    return self.prepare_response(request, cached)
AA  File "/Users/scott/Applications/SickRage/lib/cachecontrol/serialize.py", line 184, in _loads_v2
AA    return getattr(self, "_loads_v{0}".format(ver))(request, data)
AA  File "/Users/scott/Applications/SickRage/lib/cachecontrol/serialize.py", line 108, in loads
AA    resp = self.serializer.loads(request, self.cache.get(cache_url))
AA  File "/Users/scott/Applications/SickRage/lib/cachecontrol/controller.py", line 102, in cached_request
AA    cached_response = self.controller.cached_request(request)
AA  File "/Users/scott/Applications/SickRage/lib/cachecontrol/adapter.py", line 36, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/Users/scott/Applications/SickRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/Users/scott/Applications/SickRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/Users/scott/Applications/SickRage/lib/requests/sessions.py", line 476, in get
AA    resp = session.get(url.strip(), params=params)
AA  File "/Users/scott/Applications/SickRage/lib/tvdb_api/tvdb_api.py", line 577, in _loadUrl
AAtvdb_error: Unknown exception while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/76884/en.xml: Traceback (most recent call last):
AA    raise tvdb_error(e)
AA  File "/Users/scott/Applications/SickRage/lib/tvdb_api/tvdb_api.py", line 635, in _getetsrc
AA    self.config['url_seriesInfo'] % (sid, getShowInLanguage)
AA  File "/Users/scott/Applications/SickRage/lib/tvdb_api/tvdb_api.py", line 846, in _getShowData
AA    self._getShowData(key, self.config['language'], True)
AA  File "/Users/scott/Applications/SickRage/lib/tvdb_api/tvdb_api.py", line 951, in __getitem__
AA    myEp = t[self.indexerid]
AA  File "/Users/scott/Applications/SickRage/sickbeard/tv.py", line 874, in loadFromIndexer
AA    newShow.loadFromIndexer()
AA  File "/Users/scott/Applications/SickRage/sickbeard/show_queue.py", line 297, in run
AATraceback (most recent call last):
AATypeError: __init__() keywords must be strings
AA    **cached["response"]
AA  File "/Users/scott/Applications/SickRage/lib/cachecontrol/serialize.py", line 145, in prepare_response
AA    return self.prepare_response(request, cached)
AA  File "/Users/scott/Applications/SickRage/lib/cachecontrol/serialize.py", line 184, in _loads_v2
AA    return getattr(self, "_loads_v{0}".format(ver))(request, data)
AA  File "/Users/scott/Applications/SickRage/lib/cachecontrol/serialize.py", line 108, in loads
AA    resp = self.serializer.loads(request, self.cache.get(cache_url))
AA  File "/Users/scott/Applications/SickRage/lib/cachecontrol/controller.py", line 102, in cached_request
AA    cached_response = self.controller.cached_request(request)
AA  File "/Users/scott/Applications/SickRage/lib/cachecontrol/adapter.py", line 36, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/Users/scott/Applications/SickRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/Users/scott/Applications/SickRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/Users/scott/Applications/SickRage/lib/requests/sessions.py", line 476, in get
AA    resp = session.get(url.strip(), params=params)
AA  File "/Users/scott/Applications/SickRage/lib/tvdb_api/tvdb_api.py", line 577, in _loadUrl
2015-07-17 23:41:16 ERROR    SHOWQUEUE-ADD :: Unable to add show due to an error with theTVDB: error Unknown exception while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/76884/en.xml: Traceback (most recent call last):
2015-07-17 23:41:13 INFO     POSTPROCESSER :: Processing completed
2015-07-17 23:41:13 INFO     POSTPROCESSER :: PostProcessing Path: /Users/scott/Desktop/Torrents
2015-07-17 23:41:09 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2015-07-17 23:41:09 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2015-07-17 23:41:09 INFO     DAILYSEARCHER :: No new released episodes found ...
2015-07-17 23:41:09 INFO     DAILYSEARCHER :: Searching for new released episodes ...
2015-07-17 23:41:07 INFO     Thread-59 :: Processing completed

**Comment by fernandog** [comment]
@ariscottle 

Please set your GitHub username and password in the config, unable to submit issue ticket to GitHub!

Unable to add show due to an error with theTVDB

**Comment by miigotu** [comment]
Still want to find and fix the `title is too long` thing. It's set to max len 1024 in logger

**Comment by miigotu** [comment]
I think it needs to be 1024 bytes, not 1024 chars, because unicode can be 1-4 bytes per char

**Comment by fernandog** [comment]
@miigotu reply from github

```
You should be able to create titles with lengths up to 1024.

Let us know if you have any other questions.

Cheers,
Ivan

> What is the issue title max lenght?
There is nothin in DOC

{u'documentation_url': u'https://developer.github.com/v3/issues/#create-an-issue', u'message': u'Validation Failed', u'errors': [{u'field': u'title', u'message': u'title is too long', u'code': u'custom', u'resource': u'Issue'}]}
```

**Comment by miigotu** [comment]
@fernandog we need to cut that back, or calculate the length better, taking unicode into account.

That 1024 means 1024 bytes, not characters. ascii is 1 byte per chacter, unicode is only 1 byte/character up to 0x7F

**Comment by miigotu** [comment]
So an ascii string of 1024 characters is 1024 bytes and is allowed, a unicode string of 1024 characters could theoretically be up to 4096 bytes.

**Comment by fernandog** [comment]
Didnt know that

**Comment by fernandog** [comment]
@miigotu len(tittle.encode('utf-8') ?

**Comment by miigotu** [comment]
Dont think that works, because of the slice.

**Comment by fernandog** [comment]
Slice?

**Comment by miigotu** [comment]
title_error[0:1024] is a slice

the 1024 there might not be right ^

**Comment by fernandog** [comment]
It will get 1024 from 4096 (max).
Isnt?

**Comment by miigotu** [comment]
@fernandog here is the problem:
title_Error = u"[APP SUBMITTED]: " + title_Error

No need to change the other len check.

If the title was chopped to 1024, then you add u"[APP SUBMITTED]: " it is > 1024.

The original length it is chopped at needs to be 1007, want me to fix?

**Comment by fernandog** [comment]
ok!

**Comment by miigotu** [comment]
Done.
