### ISSUE TITLE
[APP SUBMITTED]: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by HotBlack77** [SiCKRAGETV/sickrage-issues#2203]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@ea897589698c18007ff0fd062b224d68d76d3bb5
Link to Log: https://gist.github.com/654659d6064b46aeb4bd
### ERROR
```
SEARCHQUEUE-BACKLOG-75160 :: [Cpasbien] :: Failed parsing Cpasbien Traceback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/providers/cpasbien.py", line 126, in _doSearch
    with BS4Parser(data, features=["html5lib", "permissive"]) as html:
  File "/opt/sickbeard/sickbeard/bs4_parser.py", line 6, in __init__
    self.soup = BeautifulSoup(*args, **kwargs)
  File "/opt/sickbeard/lib/bs4/__init__.py", line 162, in __init__
    elif len(markup) <= 256:
TypeError: object of type 'NoneType' has no len()

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by adaur** [comment]
It seems the server returned a 503 error before sickrage crashed. 

Could you retry to get the torrent from cpasbien please?

**Comment by miigotu** [comment]
@adaur do it like `if markup and len(markup)` or stop processing before this point `if not markup`

**Comment by Trapizomba** [comment]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 06:12:10) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4028db3d7a2cc582b0f591d981ed3af344b4e75a
Link to Log: https://gist.github.com/8d1ad1a4ee64435cde85
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [NextGen] :: Failed to login: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/nextgen.py", line 95, in _doLogin
    with BS4Parser(data) as bs:
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/bs4_parser.py", line 24, in __init__
    self.soup = BeautifulSoup(*args, **kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/bs4/__init__.py", line 162, in __init__
    elif len(markup) <= 256:
TypeError: object of type 'NoneType' has no len()

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Trapizomba** [comment]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 06:12:10) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4028db3d7a2cc582b0f591d981ed3af344b4e75a
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [NextGen] :: Failed to login: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/nextgen.py", line 95, in _doLogin
    with BS4Parser(data) as bs:
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/bs4_parser.py", line 24, in __init__
    self.soup = BeautifulSoup(*args, **kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/bs4/__init__.py", line 162, in __init__
    elif len(markup) <= 256:
TypeError: object of type 'NoneType' has no len()

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Trapizomba** [comment]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 06:12:10) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4028db3d7a2cc582b0f591d981ed3af344b4e75a
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [NextGen] :: Failed to login: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/nextgen.py", line 95, in _doLogin
    with BS4Parser(data) as bs:
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/bs4_parser.py", line 24, in __init__
    self.soup = BeautifulSoup(*args, **kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/bs4/__init__.py", line 162, in __init__
    elif len(markup) <= 256:
TypeError: object of type 'NoneType' has no len()

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Trapizomba** [comment]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 06:12:10) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4028db3d7a2cc582b0f591d981ed3af344b4e75a
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [NextGen] :: Failed to login: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/nextgen.py", line 95, in _doLogin
    with BS4Parser(data) as bs:
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/bs4_parser.py", line 24, in __init__
    self.soup = BeautifulSoup(*args, **kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/bs4/__init__.py", line 162, in __init__
    elif len(markup) <= 256:
TypeError: object of type 'NoneType' has no len()

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Trapizomba** [comment]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 06:12:10) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4028db3d7a2cc582b0f591d981ed3af344b4e75a
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [NextGen] :: Failed to login: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/nextgen.py", line 95, in _doLogin
    with BS4Parser(data) as bs:
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/bs4_parser.py", line 24, in __init__
    self.soup = BeautifulSoup(*args, **kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/bs4/__init__.py", line 162, in __init__
    elif len(markup) <= 256:
TypeError: object of type 'NoneType' has no len()

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Trapizomba** [comment]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 06:12:10) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4028db3d7a2cc582b0f591d981ed3af344b4e75a
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [NextGen] :: Failed to login: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/nextgen.py", line 95, in _doLogin
    with BS4Parser(data) as bs:
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/bs4_parser.py", line 24, in __init__
    self.soup = BeautifulSoup(*args, **kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/bs4/__init__.py", line 162, in __init__
    elif len(markup) <= 256:
TypeError: object of type 'NoneType' has no len()

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Trapizomba** [comment]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 06:12:10) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4028db3d7a2cc582b0f591d981ed3af344b4e75a
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [NextGen] :: Failed to login: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/nextgen.py", line 95, in _doLogin
    with BS4Parser(data) as bs:
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/bs4_parser.py", line 24, in __init__
    self.soup = BeautifulSoup(*args, **kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/bs4/__init__.py", line 162, in __init__
    elif len(markup) <= 256:
TypeError: object of type 'NoneType' has no len()

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Trapizomba** [comment]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 06:12:10) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4028db3d7a2cc582b0f591d981ed3af344b4e75a
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [NextGen] :: Failed to login: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/nextgen.py", line 95, in _doLogin
    with BS4Parser(data) as bs:
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/bs4_parser.py", line 24, in __init__
    self.soup = BeautifulSoup(*args, **kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/bs4/__init__.py", line 162, in __init__
    elif len(markup) <= 256:
TypeError: object of type 'NoneType' has no len()

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Trapizomba** [comment]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 06:12:10) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4028db3d7a2cc582b0f591d981ed3af344b4e75a
Link to Log: https://gist.github.com/c18a5017f110ee7af8c6
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [NextGen] :: Failed to login: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/nextgen.py", line 95, in _doLogin
    with BS4Parser(data) as bs:
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/bs4_parser.py", line 24, in __init__
    self.soup = BeautifulSoup(*args, **kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/bs4/__init__.py", line 162, in __init__
    elif len(markup) <= 256:
TypeError: object of type 'NoneType' has no len()

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Trapizomba** [comment]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 06:12:10) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4028db3d7a2cc582b0f591d981ed3af344b4e75a
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [NextGen] :: Failed to login: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/nextgen.py", line 95, in _doLogin
    with BS4Parser(data) as bs:
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/bs4_parser.py", line 24, in __init__
    self.soup = BeautifulSoup(*args, **kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/bs4/__init__.py", line 162, in __init__
    elif len(markup) <= 256:
TypeError: object of type 'NoneType' has no len()

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Trapizomba** [comment]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 06:12:10) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4028db3d7a2cc582b0f591d981ed3af344b4e75a
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [NextGen] :: Failed to login: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/nextgen.py", line 95, in _doLogin
    with BS4Parser(data) as bs:
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/bs4_parser.py", line 24, in __init__
    self.soup = BeautifulSoup(*args, **kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/bs4/__init__.py", line 162, in __init__
    elif len(markup) <= 256:
TypeError: object of type 'NoneType' has no len()

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Trapizomba** [comment]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 06:12:10) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4028db3d7a2cc582b0f591d981ed3af344b4e75a
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [NextGen] :: Failed to login: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/nextgen.py", line 95, in _doLogin
    with BS4Parser(data) as bs:
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/bs4_parser.py", line 24, in __init__
    self.soup = BeautifulSoup(*args, **kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/bs4/__init__.py", line 162, in __init__
    elif len(markup) <= 256:
TypeError: object of type 'NoneType' has no len()

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Trapizomba** [comment]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 06:12:10) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4028db3d7a2cc582b0f591d981ed3af344b4e75a
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [NextGen] :: Failed to login: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/nextgen.py", line 95, in _doLogin
    with BS4Parser(data) as bs:
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/bs4_parser.py", line 24, in __init__
    self.soup = BeautifulSoup(*args, **kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/bs4/__init__.py", line 162, in __init__
    elif len(markup) <= 256:
TypeError: object of type 'NoneType' has no len()

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Trapizomba** [comment]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 06:12:10) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4028db3d7a2cc582b0f591d981ed3af344b4e75a
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [NextGen] :: Failed to login: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/nextgen.py", line 95, in _doLogin
    with BS4Parser(data) as bs:
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/bs4_parser.py", line 24, in __init__
    self.soup = BeautifulSoup(*args, **kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/bs4/__init__.py", line 162, in __init__
    elif len(markup) <= 256:
TypeError: object of type 'NoneType' has no len()

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Trapizomba** [comment]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 06:12:10) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4028db3d7a2cc582b0f591d981ed3af344b4e75a
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [NextGen] :: Failed to login: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/nextgen.py", line 95, in _doLogin
    with BS4Parser(data) as bs:
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/bs4_parser.py", line 24, in __init__
    self.soup = BeautifulSoup(*args, **kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/bs4/__init__.py", line 162, in __init__
    elif len(markup) <= 256:
TypeError: object of type 'NoneType' has no len()

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Trapizomba** [comment]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 06:12:10) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4028db3d7a2cc582b0f591d981ed3af344b4e75a
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [NextGen] :: Failed to login: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/nextgen.py", line 95, in _doLogin
    with BS4Parser(data) as bs:
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/bs4_parser.py", line 24, in __init__
    self.soup = BeautifulSoup(*args, **kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/bs4/__init__.py", line 162, in __init__
    elif len(markup) <= 256:
TypeError: object of type 'NoneType' has no len()

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Trapizomba** [comment]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 06:12:10) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4028db3d7a2cc582b0f591d981ed3af344b4e75a
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [NextGen] :: Failed to login: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/nextgen.py", line 95, in _doLogin
    with BS4Parser(data) as bs:
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/bs4_parser.py", line 24, in __init__
    self.soup = BeautifulSoup(*args, **kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/bs4/__init__.py", line 162, in __init__
    elif len(markup) <= 256:
TypeError: object of type 'NoneType' has no len()

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Trapizomba** [comment]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 06:12:10) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4028db3d7a2cc582b0f591d981ed3af344b4e75a
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [NextGen] :: Failed to login: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/nextgen.py", line 95, in _doLogin
    with BS4Parser(data) as bs:
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/bs4_parser.py", line 24, in __init__
    self.soup = BeautifulSoup(*args, **kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/bs4/__init__.py", line 162, in __init__
    elif len(markup) <= 256:
TypeError: object of type 'NoneType' has no len()

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
