### ISSUE TITLE
[APP SUBMITTED]: No module named err

### ISSUE THREAD

**Issue by wakingsleeper** [SiCKRAGETV/sickrage-issues#2205]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.8**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@f0ef24bf7dbd5ffa451bbdb8694448139d8c4631
Link to Log: https://gist.github.com/e2c57a9bcd77a57a3541
### ERROR
```
Thread-52 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 814, in testTorrent
    client = clients.getClientIstance(torrent_method)
  File "/opt/sickbeard/sickbeard/clients/__init__.py", line 118, in getClientIstance
    module = getClientModule(name)
  File "/opt/sickbeard/sickbeard/clients/__init__.py", line 114, in getClientModule
    return __import__(prefix + name + '_client', fromlist=__all__)
  File "/opt/sickbeard/sickbeard/clients/rtorrent_client.py", line 26, in <module>
    from rtorrent.err import MethodError
ImportError: No module named err

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by wakingsleeper** [comment]
Had to delete the .pyc files under the clients.  followed this thread here https://github.com/SiCKRAGETV/sickrage-issues/issues/2188
