### ISSUE TITLE
[APP SUBMITTED]: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by razlebol** [SiCKRAGETV/sickrage-issues#2212]
### INFO
Python Version: **2.7.6 (default, Apr  3 2014, 09:45:36) [GCC 4.5.3]**
Operating System: **Linux-3.4.90-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@f0ef24bf7dbd5ffa451bbdb8694448139d8c4631
No Log available with ERRORS: 
### ERROR
```
Thread-108 :: Failed doing webui callback: Traceback (most recent call last):
  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/sickbeard/webserve.py", line 2942, in changeEpisodeStatuses
    self.setStatus(cur_indexer_id, '|'.join(to_change[cur_indexer_id]), newStatus, direct=True)
  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/sickbeard/webserve.py", line 1737, in setStatus
    epObj = showObj.getEpisode(int(epInfo[0]), int(epInfo[1]))
ValueError: invalid literal for int() with base 10: ''

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Caused by #2214
