### ISSUE TITLE
[APP SUBMITTED]: invalid syntax (opensubtitles.py, line 85)

### ISSUE THREAD

**Issue by skalvaro** [SiCKRAGETV/sickrage-issues#2222]
### INFO
Python Version: **2.6.6 (r266:84292, Jan 22 2014, 09:42:36) [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]**
Operating System: **Linux-2.6.32-504.30.3.el6.x86_64-x86_64-with-centos-6.6-Final**
Locale: UTF8
Branch: **master**
Commit: SiCKRAGETV/SickRage@f0ef24bf7dbd5ffa451bbdb8694448139d8c4631
Link to Log: https://gist.github.com/c24d9dcf3bcd7244b8d8
### ERROR
```
Thread-57 :: Traceback (most recent call last):
  File "/var/lib/sickrage/sickbeard/tv.py", line 1474, in downloadSubtitles
    foundSubs = subliminal.download_best_subtitles([video], languages=languages, providers=providers, single=not sickbeard.SUBTITLES_MULTI, hearing_impaired=False)
  File "/var/lib/sickrage/lib/subliminal/api.py", line 74, in download_best_subtitles
    with ProviderPool(providers, provider_configs) as pp:
  File "/var/lib/sickrage/lib/subliminal/providers/__init__.py", line 241, in __init__
    self.providers = dict([(p, provider_manager[p]) for p in (providers or provider_manager.available_providers)])
  File "/var/lib/sickrage/lib/subliminal/providers/__init__.py", line 184, in __getitem__
    self.providers[ep.name] = ep.load(require=False)
  File "/var/lib/sickrage/lib/pkg_resources.py", line 1954, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/var/lib/sickrage/lib/subliminal/providers/opensubtitles.py", line 85
    languages = {babelfish.Language.fromopensubtitles(l) for l in babelfish.language_converters['opensubtitles'].codes}
                                                           ^
SyntaxError: invalid syntax

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by skalvaro** [comment]
This is after disabling addic7ed as subtitle provider. #2221 If I disable opensubtitles a syntax error pops up in tvsubtitles.

**Comment by fernandog** [comment]
@miigotu didnt understand this line

**Comment by miigotu** [comment]
Update to python 2.7+, SickRage is in the process of dropping python 2.6, as you see subliminal has ^
