### ISSUE TITLE
Connection to rTorrent does not work.  "test" link fails as well. SOLVED

### ISSUE THREAD

**Issue by k1200s** [SiCKRAGETV/sickrage-issues#2226]
Found in log after SR says it sent to 
AA
AAImportError: No module named err
AA    from rtorrent.err import MethodError
AA  File "/home/disk23/******/sickrage/sickbeard/clients/rtorrent_client.py", line 26, in <module>
AA    return __import__(prefix + name + '_client', fromlist=__all__)
AA  File "/home/disk23/******/sickrage/sickbeard/clients/__init__.py", line 114, in getClientModule
AA    module = getClientModule(name)
AA  File "/home/disk23/******/sickrage/sickbeard/clients/__init__.py", line 118, in getClientIstance
AA    client = clients.getClientIstance(sickbeard.TORRENT_METHOD)()
AA  File "/home/disk23/******/sickrage/sickbeard/search.py", line 137, in snatchEpisode
AA    search.snatchEpisode(result)
AA  File "/home/disk23/******/sickrage/sickbeard/search_queue.py", line 227, in run  

2015-07-20 05:59:20 INFO     SEARCHQUEUE-BACKLOG-38517 :: Downloading Ballers.2015.S01E05.720p.HDTV.x264-0SEC from xxxxxxxx
2015-07-20 05:59:20 INFO     SEARCHQUEUE-BACKLOG-38517 :: Quality of Ballers.2015.S01E05.720p.HDTV.x264-0SEC is HDTV

In log after testing connection to rTorrent:

2015-07-20 05:59:43 Thread-46 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/disk23/******/sickrage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/home/disk23/******/sickrage/sickbeard/webserve.py", line 814, in testTorrent
    client = clients.getClientIstance(torrent_method)
  File "/home/disk23/******/sickrage/sickbeard/clients/__init__.py", line 118, in getClientIstance
    module = getClientModule(name)
  File "/home/disk23/******/sickrage/sickbeard/clients/__init__.py", line 114, in getClientModule
    return __import__(prefix + name + '_client', fromlist=__all__)
  File "/home/disk23/******/sickrage/sickbeard/clients/rtorrent_client.py", line 26, in <module>
    from rtorrent.err import MethodError
ImportError: No module named err

**Comment by pedbarbosa** [comment]
I am also getting similar errors to the one above and SickRage hasn't been able to push any torrents files into my rTorrent client since at least 2015/07/18 3:00 AM GMT:

2015-07-21 09:54:49 DEBUG    SEARCHQUEUE-BACKLOG-281537 :: Traceback (most recent call last):
  File "/dev/shm/asd-********/opt/sickrage/sickbeard/search_queue.py", line 227, in run
    search.snatchEpisode(result)
  File "/dev/shm/asd-********/opt/sickrage/sickbeard/search.py", line 137, in snatchEpisode
    client = clients.getClientIstance(sickbeard.TORRENT_METHOD)()
  File "/dev/shm/asd-********/opt/sickrage/sickbeard/clients/__init__.py", line 118, in getClientIstance
    module = getClientModule(name)
  File "/dev/shm/asd-********/opt/sickrage/sickbeard/clients/__init__.py", line 114, in getClientModule
    return __import__(prefix + name + '_client', fromlist=__all__)
  File "/dev/shm/asd-********/opt/sickrage/sickbeard/clients/rtorrent_client.py", line 26, in <module>
    from rtorrent.err import MethodError
ImportError: No module named err

**Comment by anomaly15** [comment]
I get a similar error when trying to connect to rTorrent:

2015-07-21 01:56:59 Thread-60 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home5/*****/software/SickRage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/home5/*****/software/SickRage/sickbeard/webserve.py", line 814, in testTorrent
    client = clients.getClientIstance(torrent_method)
  File "/home5/*****/software/SickRage/sickbeard/clients/__init__.py", line 118, in getClientIstance
    module = getClientModule(name)
  File "/home5/*****/software/SickRage/sickbeard/clients/__init__.py", line 114, in getClientModule
    return __import__(prefix + name + '_client', fromlist=__all__)
  File "/home5/*****/software/SickRage/sickbeard/clients/rtorrent_client.py", line 26, in <module>
    from rtorrent.err import MethodError
ImportError: No module named err

**Comment by k1200s** [comment]
Fixed by running rm sickbeard/clients/*.pyc from SSH on my box in the /sickrage directory.

source: https://github.com/SiCKRAGETV/sickrage-issues/issues/2188

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/commit/3f7f9adfcfd76e4aa92cff405e38a7b9f757312d
