### ISSUE TITLE
Cannot post-process some files because of character encodings

### ISSUE THREAD

**Issue by dejavous** [SiCKRAGETV/sickrage-issues#2236]
Apologies if this has been reported already or not an issue - I searched but found nothing that I thought matched apart from #1425 which is marked as closed.

SR Version:	BRANCH: (master) / COMMIT: (ac27935188e351a7ffd869ff1555767987f62ce3) 
SR Locale:	('en_GB', 'cp1252')
SR Config file:	C:\Media\SickRage\config.ini
SR Database file:	C:\Media\SickRage\sickbeard.db
SR Cache Dir:	C:\Media\SickRage\cache
SR Log Dir:	C:\Media\SickRage\Logs
SR Arguments:	['--nolaunch']
Python Version:	2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]
OS: Windows 8.1 x64

Recently moved from SickBeard to SickRage and I've noticed that recently it is scraping some non-alphabetic characters incorrectly. This results in inconsistencies between the filenames and the titles in the DB which is causing these episodes to be listed as Archived.

For example, Lost S03E14 Exposé appears as: Expos????????????? ?????????????????? ????????????????????????????????????????? ?????????????????????????????????????????????????? ? ?????????????????????????????????????????????????? ??????????????????????????????????
See attachment for a screengrab. 

Another example is The Walking Dead S05E09 What Happened and What's Going On. The apostraphe is a non ascii character and it gets mangled in the scraping. The HEX code of the character in the .nfo (ANSI) file is ce 93 c3 87 c3 96 where as the HEX value of the same apostraphe typed from the keyboard in this editor is 27. When I convert the file encoding to UTF8, it looks correct then view the HEX the values are e2 80 99 and still 27 for the normal apostraphe. 

I tested and the same files being pulled by SickBeard are inserted into the database as extracted from TheTVDB information and displayed correctly with no such issues. Perhaps SickRage is performing some form of conversion or using the wrong characterset?.

From the logs in SikRage I see this:
```
2015-07-20 14:24:37 WARNING  POSTPROCESSER :: Processing failed for C:\Media\Downloads\downloaded\Lost - S03E14 - .avi: Unable to move the files to their new home
AAOSError: [Errno 22] Invalid argument
AA    fout = os.open(dst, WRITE_FLAGS)
AA  File "C:\Media\SickRage\lib\shutil_custom\__init__.py", line 42, in copyfile_custom
AA    result = func(*args, **kwargs)
AA  File "C:\Media\SickRage\sickbeard\encodingKludge.py", line 65, in ek
AA    ek.ek(shutil.copyfile, srcFile, destFile)
AA  File "C:\Media\SickRage\sickbeard\helpers.py", line 400, in copyFile
AA    copyFile(srcFile, destFile)
AA  File "C:\Media\SickRage\sickbeard\helpers.py", line 412, in moveFile
AA    helpers.moveFile(cur_file_path, new_file_path)
AA  File "C:\Media\SickRage\sickbeard\postProcessor.py", line 342, in _int_move
AATraceback (most recent call last):
2015-07-20 14:24:37 ERROR    POSTPROCESSER :: Unable to move file C:\Media\Downloads\downloaded\Lost - S03E14 - .avi to Z:\Media\TV\Lost\Season 03\Lost - S03E14 - ExposÃƒÆ’Ã†â€Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢ÃƒÆ’Ã†â€Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â©.avi: error 22 : Invalid argument
2015-07-20 14:24:37 DEBUG    POSTPROCESSER :: Moving file from C:\Media\Downloads\downloaded\Lost - S03E14 - .avi to Z:\Media\TV\Lost\Season 03\Lost - S03E14 - ExposÃƒÆ’Ã†â€Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢ÃƒÆ’Ã†â€Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â©.avi
2015-07-20 14:24:36 DEBUG    POSTPROCESSER :: Checking if the path Z:\Media\TV\Lost\Season 03 already exists
2015-07-20 14:24:36 DEBUG    POSTPROCESSER :: Destination folder for this episode: Z:\Media\TV\Lost\Season 03
2015-07-20 14:24:36 DEBUG    POSTPROCESSER :: formatting pattern: Season %0S -> Season 03
2015-07-20 14:24:36 DEBUG    POSTPROCESSER :: Episode has no release name, replacing it with a generic one: Season %0S
2015-07-20 14:24:36 DEBUG    POSTPROCESSER :: formatting pattern: %SN - S%0SE%0E - %EN -> Lost - S03E14 - ExposÃƒÆ’Ã†â€Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢ÃƒÆ’Ã†â€Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â©
2015-07-20 14:24:36 DEBUG    POSTPROCESSER :: Episode has no release name, replacing it with a generic one: %SN - S%0SE%0E - %EN
2015-07-20 14:24:36 DEBUG    POSTPROCESSER :: Folder name (downloaded) appears to be a valid release name. Using it.
2015-07-20 14:24:36 DEBUG    POSTPROCESSER :: Trying to determine free space on destination drive
2015-07-20 14:24:36 DEBUG    POSTPROCESSER :: There is no existing file so there's no worries about replacing it
2015-07-20 14:24:36 DEBUG    POSTPROCESSER :: Is ep a priority download: False
2015-07-20 14:24:36 DEBUG    POSTPROCESSER :: Quality of the episode we're processing: 1
2015-07-20 14:24:36 DEBUG    POSTPROCESSER :: Lost - S03E14 - .avi looks like it has quality SDTV, using that
2015-07-20 14:24:36 DEBUG    POSTPROCESSER :: Guessing quality for name Lost - S03E14 - .avi, got SDTV
2015-07-20 14:24:36 DEBUG    POSTPROCESSER :: Looking up quality for name Lost - S03E14 - .avi, got Unknown
2015-07-20 14:24:36 DEBUG    POSTPROCESSER :: Looking up quality for name downloaded, got Unknown
2015-07-20 14:24:36 DEBUG    POSTPROCESSER :: Retrieving episode object for 3x14
2015-07-20 14:24:36 DEBUG    POSTPROCESSER :: Parse result(release_group): None
2015-07-20 14:24:36 DEBUG    POSTPROCESSER ::  or Parse result(air_date): None
2015-07-20 14:24:36 DEBUG    POSTPROCESSER :: Parse result(episode_numbers): [14]
2015-07-20 14:24:36 DEBUG    POSTPROCESSER :: Parse result(season_number): 3
2015-07-20 14:24:36 DEBUG    POSTPROCESSER :: Parse result(series_name): Lost
2015-07-20 14:24:36 DEBUG    POSTPROCESSER :: Parse result not sufficient (all following have to be set). will not save release name
2015-07-20 14:24:36 DEBUG    POSTPROCESSER :: Using cached parse result for: Lost - S03E14
2015-07-20 14:24:36 DEBUG    POSTPROCESSER :: Analyzing name u'Lost - S03E14 - .avi'
2015-07-20 14:24:36 INFO     POSTPROCESSER :: Processing C:\Media\Downloads\downloaded\Lost - S03E14 - .avi (None)
2015-07-20 14:24:35 DEBUG    POSTPROCESSER :: PostProcessing VideoInRar: []
2015-07-20 14:24:35 DEBUG    POSTPROCESSER :: PostProcessing RarContent: []
2015-07-20 14:24:35 DEBUG    POSTPROCESSER :: PostProcessing VideoFiles: [u'Lost - S03E14 - .avi']
2015-07-20 14:24:35 DEBUG    POSTPROCESSER :: PostProcessing Files: [u'Lost - S03E14 - .avi']
2015-07-20 14:24:35 INFO     POSTPROCESSER :: PostProcessing Path: C:\Media\Downloads\downloaded
2015-07-20 14:24:35 DEBUG    POSTPROCESSER :: TV_DOWNLOAD_DIR: C:\Media\Downloads\downloaded
2015-07-20 14:24:35 DEBUG    POSTPROCESSER :: Processing folder C:\Media\Downloads\downloaded
2015-07-20 14:24:35 DEBUG    POSTPROCESSER :: Starting new thread: POSTPROCESSER
```
Other episode effected in a similar way are (all scraped using TheTVDB):

30 Rock 5x13
American Dad! 7x11
Boardwalk Empire 4x5
Chaos (2011) 1x5
Copper 1x5
Elementary 1x18
Hart of Dixie 3x1
Horizon 2014x7
Lost 3x14
Moone Boy 2x1
Natural World 34x10
Penny Dreadful 1x2
Prison Break 3x1
Red Dwarf 1x6
South Park 14x14
Southcliffe 1x3
The Big Bang Theory 2x7
The Originals 1x11
The Returned 1x7
The Venture Bros. 2x11
The Walking Dead 5x9
Weeds 7x11
e2 Transport 1x2

**Comment by fernandog** [comment]
@dejavous before run sickrage run:

chcp 65001

**Comment by dejavous** [comment]
Thanks for the reply, I did that and immediately on startup it processed the Lost episode, however the filename on the filesystem and the name in sickrage is ExposÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â© instead of Exposé.

**Comment by fernandog** [comment]
rename that file to Exposé and to a show refresh
and try again. probally next episodes won't have this issue

**Comment by dejavous** [comment]
Unfortunately not, attempted another of the effected files and it failed to process the file as originally detailed above.

**Comment by fernandog** [comment]
if the file is already renamed with this bad chars, issue will persist

**Comment by dejavous** [comment]
Previously the show refresh update was failing which I didn't notice (sometimes sketchy wireless). Ran it again and then followed the stops and it's all sweet. Thanks for the assistance!
