### ISSUE TITLE
[APP SUBMITTED]: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2243]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-22-generic-i686-with-Ubuntu-15.04-vivid**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@a017c6e6eda57317a0be3dde9891789a169f97c4
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-RETRY-80270 :: [T411] :: Error while searching T411, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@duramato Please add the logs.

**Comment by fernandog** [comment]
@duramato Please add the logs.

**Comment by bioshock47** [comment]
hello, i have the same error, here's my log
https://www.dropbox.com/s/jjyw1wzmf19zizm/Log%20sickrage.txt?dl=0

**Comment by fernandog** [comment]
@bioshock47 you get "AAAttributeError: '_socketobject' object has no attribute 'set_tlsext_host_name'"

please read this: https: //github.com/SiCKRAGETV/sickrage-issues/issues/2268

**Comment by bioshock47** [comment]
Thanks @fernandog.

I try to install centos 6 but i have a QNAP for NAS, and it's not working.
Sorry but i'm a beginner in nas...

**Comment by fernandog** [comment]
@bioshock47 me neither! =) try asking in centos forum

**Comment by bioshock47** [comment]
@fernandog, i'm french if you french too it can be easyear to talk, if you'r not, why my problem is connected to centos OS?

**Comment by fernandog** [comment]
because you need to update a library in your centos OS

**Comment by bioshock47** [comment]
but its linux whiich is install in QNAP not centos os right?

**Comment by fernandog** [comment]
Please reply in the other issue. This is another thing

**Comment by MGaetan89** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:58:35) [GCC 4.6.4]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@27ded15e814bcbd47d06d9bf16d130f9d42ebd45
Link to Log: https://gist.github.com/612665a10f7770d663d7
### ERROR
```
TORNADO :: API :: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by MGaetan89** [comment]
I have this error when calling the `shows.stats` API command.
The command itself returns:

```json
{
    "data": {
        "args": [], 
        "error_msg": "argument of type 'NoneType' is not iterable", 
        "kwargs": {}
    }, 
    "message": "SickRage encountered an internal error! Please report to the Devs", 
    "result": "fatal"
}
```

**Comment by adaur** [comment]
Can you retry without proxy?

**Comment by MGaetan89** [comment]
I'm not using any proxy

**Comment by fernandog** [comment]
Missing parameter?
Try with apibuilder

**Comment by MGaetan89** [comment]
The error I posted is from the apibuilder. This command does not use parameters if I remember correctly.

**Comment by fernandog** [comment]
showstats runs ok here

you need to pass the indexerid

```
/api/****/?cmd=show.stats&indexerid=270633
{
    "data": {
        "archived": 0, 
        "downloaded": {
            "1080p_bluray": 0, 
            "1080p_hdtv": 0, 
            "1080p_web-dl": 0, 
            "720p_bluray": 0, 
            "720p_web-dl": 0, 
            "hdtv": 14, 
            "rawhd": 0, 
            "sd_dvd": 0, 
            "sdtv": 0, 
            "total": 14, 
            "unknown": 0
        }, 
```

**Comment by MGaetan89** [comment]
You're trying the wrong command. It's `shows.stats` that's broken.

**Comment by fernandog** [comment]
```
/api/******76ceeea5a8b824bf439eb4/?cmd=shows.stats
{
    "data": {
        "ep_downloaded": 3275, 
        "ep_snatched": 4, 
        "ep_total": 3293, 
        "shows_active": 66, 
        "shows_total": 75
    }, 
    "message": "", 
    "result": "success"
}
```

**Comment by fernandog** [comment]
enable DEBUG while running apibuilder

**Comment by MGaetan89** [comment]
I enabled `debug` before sending the issue (and calling `shows.stats`).
I will investigate more to see where it comes from.

**Comment by fernandog** [comment]
how many snatched episodes do you have?

**Comment by miigotu** [comment]
```json
/api/************/?cmd=shows.stats&profile=1&jsonp=foo
foo({
    "data": {
        "ep_downloaded": 5, 
        "ep_snatched": 37, 
        "ep_total": 186, 
        "shows_active": 4, 
        "shows_total": 4
    }, 
    "message": "", 
    "result": "success"
});
```

**Comment by fernandog** [comment]
@MGaetan89 how many snatched?

**Comment by miigotu** [comment]
@MGaetan89 look at the bottom of that lof you posted. Seems the error was just the last error in your errorviewer, from libertalia.

**Comment by MGaetan89** [comment]
I didn't have time to investigate more.
But since I updated to 4.0.49, it is working again ...

**Comment by fernandog** [comment]
How many snatched episodes?

**Comment by MGaetan89** [comment]
Sorry, forgot to answer your question ...
Now it's 288, but it changed since I submitted the issue.

**Comment by miigotu** [comment]
@fernandog If it's working now there is nothing to worry about, xD

**Comment by zaggash** [comment]
### INFO
Python Version: **2.7.5 (default, Jun 24 2015, 00:41:19) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]**
Operating System: **Linux-3.10.0-229.11.1.el7.x86_64-x86_64-with-centos-7.1.1503-Core**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@fe0111aa88dc6d65177f339e643ca971405f926f
Link to Log: https://gist.github.com/e9ed4d2d6c56d5a8520b
### ERROR
```
SEARCHQUEUE-MANUAL-247808 :: [T411] :: Error while searching T411, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by zaggash** [comment]
### INFO
Python Version: **2.7.5 (default, Jun 24 2015, 00:41:19) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]**
Operating System: **Linux-3.10.0-229.11.1.el7.x86_64-x86_64-with-centos-7.1.1503-Core**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@fe0111aa88dc6d65177f339e643ca971405f926f
Link to Log: https://gist.github.com/a0354681de169c85825c
### ERROR
```
SEARCHQUEUE-MANUAL-247808 :: [T411] :: Error while searching T411, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by adaur** [comment]
T411 is down at the moment, it's normal.

**Comment by kylliox** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5770d33ef96e619af764b452ea35ad33e5755add
Link to Log: https://gist.github.com/824f607f05f6020f84c9
### ERROR
```
SEARCHQUEUE-BACKLOG-259640 :: [T411] :: Error while searching T411, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by zaggash** [comment]
Hello, same thing here.
The tracker is down

**Comment by adaur** [comment]
503 Service Unavailable

Please don't post when a tracker is down.

**Comment by miigotu** [comment]
I'll make this not error when I get home.

**Comment by jobenso** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.2-rafaela**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@5391476827cf369a2d16a4e7ee8128f47a75f74c
Link to Log: https://gist.github.com/997de556249de15c5db5
### ERROR
```
TORNADO :: API :: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by jobenso** [comment]
So this error happened when I turned on anime, used the database (http://anidb.net/) and split the sections. Now anything new I add is loading....

(loading)		Loading... (/storage/video/TV/Million Doll)				
(loading)		Loading... (/storage/video/TV/Blood and Oil)

**Comment by OmgImAlexis** [comment]
@MGaetan89 looks like an API issue now.

**Comment by MGaetan89** [comment]
I think it's the same error that I reported in a previous comment here.
Without looking too much, I'd say that one of the following SQL queries is doing something bad in some cases: https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/webapi.py#L2815

**Comment by jobenso** [comment]
I deleted my database file, reloading TV library. Most was cached, so it wasn't too bad.

**Comment by miigotu** [comment]
@MGaetan89 Ill have a look at those sql and see if I can improve the reliability there. I think it fails when one of those returns 0 results, and the SQL is asking for a count.

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-31-generic-i686-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@2122b7ca3969ca7a4b2031f00e6e702f5907569a
Link to Log: https://gist.github.com/a81bf02c7da06a4722a1
### ERROR
```
SEARCHQUEUE-MANUAL-194751 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@duramato no traceback?

**Comment by duramato** [comment]
@fernandog ```
2015-10-27 15:45:44 DEBUG    SEARCHQUEUE-MANUAL-194751 :: [Torrentz] :: Traceback (most recent call last):
AATypeError: argument of type 'NoneType' is not iterable
AA    if 'tv' not in item['category']:
AA  File "/home/home/SickRage/sickbeard/providers/torrentz.py", line 99, in _doSearch
AA    itemList += self._doSearch(curString, search_mode, len(episodes), epObj=epObj)
AA  File "/home/home/SickRage/sickbeard/providers/generic.py", line 350, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/home/home/SickRage/sickbeard/search.py", line 496, in searchProviders
AATraceback (most recent call last):
2015-10-27 15:45:44 ERROR    SEARCHQUEUE-MANUAL-194751 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
2015-10-27 15:45:42 INFO     SEARCHQUEUE-MANUAL-194751 :: [Torrentz] :: https://torrentz.eu/feed_verified?q=Conan+2015%7C10%7C20
2015-10-27 15:45:42 INFO     SEARCHQUEUE-MANUAL-194751 :: [Torrentz] :: Performing episode search for Conan (2010)
```

**Comment by miigotu** [comment]
Fixed

**Comment by Chuffi** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@297ccc3043957ffa96fa142035a9393845cdb024
Link to Log: https://gist.github.com/96002c3c555eaab32d36
### ERROR
```
SEARCHQUEUE-BACKLOG-264492 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by MrsAngelD** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-51-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@78fdf429c6bdef4771edc8fa1bf5d73dc5dd55dc
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-MANUAL-71256 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by killinme1** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.16.0-0.bpo.4-amd64-x86_64-with-debian-7.9**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5f496885827bf88e4b24a4c94dc163dd016b2bca
Link to Log: https://gist.github.com/4f4546976ba589b2148a
### ERROR
```
SEARCHQUEUE-BACKLOG-301608 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by felixbrucker** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-4.2.3-2-pve-x86_64-with-debian-8.1**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
Link to Log: https://gist.github.com/1d1adb4663845d06e708
### ERROR
```
SEARCHQUEUE-BACKLOG-152831 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by maggbg** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-250487 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by maggbg** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-247909 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by shadowcharly** [comment]
### INFO
Python Version: **2.7.10 (default, Jul 14 2015, 19:46:27) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]**
Operating System: **Darwin-14.5.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-295829 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by shadowcharly** [comment]
### INFO
Python Version: **2.7.10 (default, Jul 14 2015, 19:46:27) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]**
Operating System: **Darwin-14.5.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-295829 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by shadowcharly** [comment]
### INFO
Python Version: **2.7.10 (default, Jul 14 2015, 19:46:27) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]**
Operating System: **Darwin-14.5.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-295829 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by shadowcharly** [comment]
### INFO
Python Version: **2.7.10 (default, Jul 14 2015, 19:46:27) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]**
Operating System: **Darwin-14.5.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-295829 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by sverleysen** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
Link to Log: https://gist.github.com/14700d6c174cafd7fd16
### ERROR
```
SEARCHQUEUE-BACKLOG-82696 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by DrEVILish** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
Link to Log: https://gist.github.com/c4d9c1c09ce02fa41a16
### ERROR
```
SEARCHQUEUE-MANUAL-263365 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by DrEVILish** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
Link to Log: https://gist.github.com/9377a3c230215118e8ca
### ERROR
```
SEARCHQUEUE-BACKLOG-281470 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by DrEVILish** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
Link to Log: https://gist.github.com/4eef3c255f19e0260d50
### ERROR
```
SEARCHQUEUE-BACKLOG-83462 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by DrEVILish** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
Link to Log: https://gist.github.com/9fcf39feff9d61a0851b
### ERROR
```
SEARCHQUEUE-BACKLOG-248835 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by DrEVILish** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
Link to Log: https://gist.github.com/0050a026b2dbeb6d8410
### ERROR
```
SEARCHQUEUE-MANUAL-263365 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by DrEVILish** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
Link to Log: https://gist.github.com/98643daec7ba70bb7e6e
### ERROR
```
SEARCHQUEUE-MANUAL-248835 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by DrEVILish** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
Link to Log: https://gist.github.com/1ab3a69f6b41ab9bd8e8
### ERROR
```
SEARCHQUEUE-MANUAL-248835 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by DrEVILish** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
Link to Log: https://gist.github.com/c319c0237f4aa776b1dc
### ERROR
```
SEARCHQUEUE-MANUAL-248835 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by DrEVILish** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
Link to Log: https://gist.github.com/adbf6ff75292119d22f1
### ERROR
```
SEARCHQUEUE-BACKLOG-83462 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by DrEVILish** [comment]
Just to add it's not Windows 8 I'm running it's Windows 10 64-Bit

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
Link to Log: https://gist.github.com/b5c5a336af493f19074a
### ERROR
```
SEARCHQUEUE-BACKLOG-92411 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-95441 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-72108 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-72108 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-72108 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-72108 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-72108 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-75710 :: [Torrentz] :: Error while searching Torrentz, skipping: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
