### ISSUE TITLE
[APP SUBMITTED]: saveSearch() got an unexpected keyword argument 'layout'

### ISSUE THREAD

**Issue by Takayuki80** [SiCKRAGETV/sickrage-issues#2262]
### INFO
Python Version: **2.7.3 (default, Dec 18 2014, 19:10:20) [GCC 4.6.3]**
Operating System: **Linux-2.6.32-042stab102.9-x86_64-with-Ubuntu-12.04-precise**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@ac27935188e351a7ffd869ff1555767987f62ce3
Link to Log: https://gist.github.com/57e938df19f7d9f5e1c6
### ERROR
```
2015-07-21 11:42:00 ERROR    Thread-53 :: Failed doing webui callback: Traceback (most recent call last):

TypeError: saveSearch() got an unexpected keyword argument 'layout'
    result = function(**kwargs)
  File "/home/********/sickrage_install/sickbeard/webserve.py", line 272, in async_call
    result = self.fn(*self.args, **self.kwargs)
  File "/home/********/sickrage_install/lib/concurrent/futures/thread.py", line 61, in run
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "/home/********/sickrage_install/lib/concurrent/futures/_compat.py", line 107, in reraise
    reraise(self._exception, self._traceback)
  File "/home/********/sickrage_install/lib/concurrent/futures/_base.py", line 359, in __get_result
    return self.__get_result()
  File "/home/********/sickrage_install/lib/concurrent/futures/_base.py", line 400, in result
    value = future.result()
  File "/home/********/sickrage_install/tornado/gen.py", line 807, in run
    results = yield self.async_call(method)
  File "/home/********/sickrage_install/sickbeard/webserve.py", line 257, in get
2015-07-21 11:41:57 DEBUG    TORNADO :: Failed doing webui request "saveSearch": Traceback (most recent call last):
TypeError: saveSearch() got an unexpected keyword argument 'layout'
    result = function(**kwargs)
  File "/home/********/sickrage_install/sickbeard/webserve.py", line 272, in async_call
Traceback (most recent call last):
TypeError: saveSearch() got an unexpected keyword argument 'layout'
    result = function(**kwargs)
  File "/home/********/sickrage_install/sickbeard/webserve.py", line 272, in async_call
2015-07-21 11:41:57 ERROR    Thread-50 :: Failed doing webui callback: Traceback (most recent call last):

ImportError: No module named err
    from rtorrent.err import MethodError
  File "/home/********/sickrage_install/sickbeard/clients/rtorrent_client.py", line 26, in <module>
    return __import__(prefix + name + '_client', fromlist=__all__)
  File "/home/********/sickrage_install/sickbeard/clients/__init__.py", line 114, in getClientModule
    module = getClientModule(name)
  File "/home/********/sickrage_install/sickbeard/clients/__init__.py", line 118, in getClientIstance
    client = clients.getClientIstance(torrent_method)
  File "/home/********/sickrage_install/sickbeard/webserve.py", line 814, in testTorrent
    result = function(**kwargs)
  File "/home/********/sickrage_install/sickbeard/webserve.py", line 272, in async_call
    result = self.fn(*self.args, **self.kwargs)
  File "/home/********/sickrage_install/lib/concurrent/futures/thread.py", line 61, in run
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "/home/********/sickrage_install/lib/concurrent/futures/_compat.py", line 107, in reraise
    reraise(self._exception, self._traceback)
  File "/home/********/sickrage_install/lib/concurrent/futures/_base.py", line 359, in __get_result
    return self.__get_result()
  File "/home/********/sickrage_install/lib/concurrent/futures/_base.py", line 400, in result
    value = future.result()
  File "/home/********/sickrage_install/tornado/gen.py", line 807, in run
    results = yield self.async_call(method)
  File "/home/********/sickrage_install/sickbeard/webserve.py", line 257, in get

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@Takayuki80 what did you do to raise this error? how to reproduce?

**Comment by miigotu** [comment]
@fernandog pyc and clients issue.

@Takayuki80 See https://github.com/SiCKRAGETV/sickrage-issues/issues/2247#issuecomment-123275228
