### ISSUE TITLE
[APP SUBMITTED]: unsupported operand type(s) for -: 'str' and 'int'

### ISSUE THREAD

**Issue by KoenDeMol** [SiCKRAGETV/sickrage-issues#2281]
### INFO
Python Version: **2.7.9 (default, Apr 30 2015, 10:19:51) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@eb6f4d46709f4b3dd337c56573feb5bac27b10a9
Link to Log: https://gist.github.com/d357fc40f21bafc1930a
### ERROR
```
Thread-62 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/webserve.py", line 2254, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/processTV.py", line 251, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/processTV.py", line 491, in process_media
    result.result = processor.process()
  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/postProcessor.py", line 856, in process
    old_ep_status, old_ep_quality = common.Quality.splitCompositeStatus(ep_obj.status)
  File "/share/CACHEDEV1_DATA/.qpkg/SickRage/SickRage/sickbeard/common.py", line 285, in splitCompositeStatus
    return (status - x * 100, x)
TypeError: unsupported operand type(s) for -: 'str' and 'int'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by KoenDeMol** [comment]
I updated today (was about 70 commits behind). Post-processing not working since (still did before the upgrade).

**Comment by miigotu** [comment]
I need to look into this one as it has been reported several times over the past few months.

I think it is more to do with previous errors in your log though.

Cd into the sickrage folder and try to do a `git reset --hard && git pull`

**Comment by KoenDeMol** [comment]
The git reset worked like a charm! Working again, .. thx!

P.S.: There were (and still are) a lot of errors on the "downloadSubtitles" part (was on #2282 which you closed), but nothing else. I did a clean install on the NAS of a friend of mine two days ago, performed the updates there and he has the same problem ...
