### ISSUE TITLE
OSError when "Append language codes to subtitle filenames?" is not checked

### ISSUE THREAD

**Issue by hackedbellini** [SiCKRAGETV/sickrage-issues#2299]
After updating my sickrage instance, I noticed the following traceback on my log after a show finished downloading.

```
2015-07-23 11:20:34 POSTPROCESSER :: Traceback (most recent call last):
  File "/home/xbian/apps/sickrage/sickrage/sickbeard/tv.py", line 1477, in downloadSubtitles
    helpers.chmodAsParent(subpath)
  File "/home/xbian/apps/sickrage/sickrage/sickbeard/helpers.py", line 603, in chmodAsParent
    childPathStat = ek.ek(os.stat, childPath)
  File "/home/xbian/apps/sickrage/sickrage/sickbeard/encodingKludge.py", line 67, in ek
    result = func(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
OSError: [Errno 2] No such file or directory: '/home/xbian/media/media/Videos/Series/The Strain/Season 02/The Strain S02E02.pt.srt'
```

Looking at that path, that file really doesn't exist. But there's one ending with `.srt` instead of `.pt.srt`.

I think that it might be related to the fact that I don't have `Append language codes to subtitle filenames?` checked.

**Comment by fernandog** [comment]
@miigotu

**Comment by miigotu** [comment]
I know what this is from -.- will fix it soonish.
