### ISSUE TITLE
[APP SUBMITTED]: unsupported operand type(s) for -: 'str' and 'int'

### ISSUE THREAD

**Issue by abetancort** [SiCKRAGETV/sickrage-issues#2305]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@eb6f4d46709f4b3dd337c56573feb5bac27b10a9
Link to Log: https://gist.github.com/1c971e3d582fb5a97869
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: unsupported operand type(s) for -: 'str' and 'int'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abetancort** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@eb6f4d46709f4b3dd337c56573feb5bac27b10a9
Link to Log: https://gist.github.com/816b834aac4af7059862
### ERROR
```
Thread-95 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2254, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 204, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 491, in process_media
    result.result = processor.process()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/postProcessor.py", line 856, in process
    old_ep_status, old_ep_quality = common.Quality.splitCompositeStatus(ep_obj.status)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/common.py", line 285, in splitCompositeStatus
    return (status - x * 100, x)
TypeError: unsupported operand type(s) for -: 'str' and 'int'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Did you create a new DB when switching to SR or did you use this DB with another fork at any time?

**Comment by abetancort** [comment]
No

**Comment by miigotu** [comment]
I would try git reset --hard && git pull again just to make sure, because this error makes no sense. Everywhere that this function is called it is with the proper type as far as I have found. As a matter of fact it is casted to int as soon as it is read from the DB.

**Comment by abetancort** [comment]
Don't worry I'll do a hard git reset.

**Comment by abetancort** [comment]
Done.

**Comment by PornOH** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@56fd7a9447fb0e72398568be737c1f00b5bb07f4
Link to Log: https://gist.github.com/a20d143a97d34ba20f56
### ERROR
```
Thread-28 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 251, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 2153, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "C:\SickRage\sickbeard\processTV.py", line 273, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "C:\SickRage\sickbeard\processTV.py", line 555, in process_media
    result.result = processor.process()
  File "C:\SickRage\sickbeard\postProcessor.py", line 882, in process
    old_ep_status, old_ep_quality = common.Quality.splitCompositeStatus(ep_obj.status)
  File "C:\SickRage\sickbeard\common.py", line 394, in splitCompositeStatus
    return (status - q * 100, q)
TypeError: unsupported operand type(s) for -: 'str' and 'int'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by tonyp1983** [comment]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: unsupported operand type(s) for -: 'str' and 'int'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by XxUnkn0wnxX** [comment]
### INFO
Python Version: **2.7.10 (default, Sep 23 2015, 04:34:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)]**
Operating System: **Darwin-15.0.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
Link to Log: https://gist.github.com/5a493dcc2df6a622f7a6
### ERROR
```
Thread-57 :: Failed doing webui callback: Traceback (most recent call last):
  File "/Users/ovidijus/Apps/SickRage/sickbeard/webserve.py", line 259, in async_call
    result = function(**kwargs)
  File "/Users/ovidijus/Apps/SickRage/sickbeard/webserve.py", line 2203, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), type=type
  File "/Users/ovidijus/Apps/SickRage/sickbeard/processTV.py", line 225, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/Users/ovidijus/Apps/SickRage/sickbeard/processTV.py", line 554, in process_media
    result.result = processor.process()
  File "/Users/ovidijus/Apps/SickRage/sickbeard/postProcessor.py", line 884, in process
    _, old_ep_quality = common.Quality.splitCompositeStatus(ep_obj.status)
  File "/Users/ovidijus/Apps/SickRage/sickbeard/common.py", line 405, in splitCompositeStatus
    return (status - q * 100, q)
TypeError: unsupported operand type(s) for -: 'str' and 'int'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by XxUnkn0wnxX** [comment]
### INFO
Python Version: **2.7.10 (default, Sep 23 2015, 04:34:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)]**
Operating System: **Darwin-15.0.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
Link to Log: https://gist.github.com/c6101df260c36f0301a2
### ERROR
```
Thread-25 :: Failed doing webui callback: Traceback (most recent call last):
  File "/Users/ovidijus/Apps/SickRage/sickbeard/webserve.py", line 259, in async_call
    result = function(**kwargs)
  File "/Users/ovidijus/Apps/SickRage/sickbeard/webserve.py", line 2203, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), type=type
  File "/Users/ovidijus/Apps/SickRage/sickbeard/processTV.py", line 225, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/Users/ovidijus/Apps/SickRage/sickbeard/processTV.py", line 554, in process_media
    result.result = processor.process()
  File "/Users/ovidijus/Apps/SickRage/sickbeard/postProcessor.py", line 884, in process
    _, old_ep_quality = common.Quality.splitCompositeStatus(ep_obj.status)
  File "/Users/ovidijus/Apps/SickRage/sickbeard/common.py", line 405, in splitCompositeStatus
    return (status - q * 100, q)
TypeError: unsupported operand type(s) for -: 'str' and 'int'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by XxUnkn0wnxX** [comment]
i get this error when i try to replace a archived or deleted episode.

the work around is to set it to wanted or some other status other then archived/skipped

plzz fix this...

**Comment by thenamelessthing** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-68-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: unsupported operand type(s) for -: 'str' and 'int'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
