### ISSUE TITLE
Traceback error upon download

### ISSUE THREAD

**Issue by lqid10t** [SiCKRAGETV/sickrage-issues#2312]
Master
eb6f4d46709f4b3dd337c56573feb5bac27b10a9
Synology DSM 5.2-5592 Update 1
2.7.10 (default, Jun 3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]
I attempted to force a download for Chaos Dragon via the magnifying glass in the show page.
The episode never downloaded, even though the log clearly shows it snatches the file and generated an error.
I expected the file to download
https://gist.github.com/lqid10t/f985f2a58f0e1a985128
```
2015-07-24 06:29:17 INFO     SEARCHQUEUE-MANUAL-296764 :: Downloading [HorribleSubs].Chaos.Dragon.-.04.[720p].mkv from NyaaTorrents
2015-07-24 06:29:17 DEBUG    SEARCHQUEUE-MANUAL-296764 :: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search_queue.py", line 184, in run
    self.success = search.snatchEpisode(searchResult[0])
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 137, in snatchEpisode
    client = clients.getClientIstance(sickbeard.TORRENT_METHOD)()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/clients/__init__.py", line 118, in getClientIstance
    module = getClientModule(name)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/clients/__init__.py", line 114, in getClientModule
    return __import__(prefix + name + '_client', fromlist=__all__)
```

**Comment by lqid10t** [comment]
Also, I'm not sure if this is related or not, but when testing the connection for my torrent client, which is the Synology Download Station, I get the error is the Gist below, and it brings up the front page of Sickrage listing all of my shows.

https://gist.github.com/lqid10t/314ac50ca31abf8dcf7e

**Comment by miigotu** [comment]
@lqid10t First did you know there is an official package for Syno now?

Second, ssh in with admin, `cd /volume1/@appstore/sickbeard-custom/var/SickBeard/`
`git reset --hard && git pull`

This was an error in one commit, that has since been fixed, but requires a git reset.
