### ISSUE TITLE
[APP SUBMITTED]: No module named generic

### ISSUE THREAD

**Issue by tloskpd** [SiCKRAGETV/sickrage-issues#2313]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-58-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@946961f452acb43c39008c847bd8a883c9197503
Link to Log: https://gist.github.com/6e4693d8f9576b74792d
### ERROR
```
Thread-38 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/tloskpd/.sickbeard/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/home/tloskpd/.sickbeard/sickbeard/webserve.py", line 815, in testTorrent
    client = clients.getClientIstance(torrent_method)
  File "/home/tloskpd/.sickbeard/sickbeard/clients/__init__.py", line 118, in getClientIstance
    module = getClientModule(name)
  File "/home/tloskpd/.sickbeard/sickbeard/clients/__init__.py", line 114, in getClientModule
    return __import__(prefix + name + '_client', fromlist=__all__)
  File "/home/tloskpd/.sickbeard/sickbeard/clients/transmission_client.py", line 25, in <module>
    from .generic import GenericClient
ImportError: No module named generic

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@miigotu linux. shoudl'nt SickBeard.py remove the old files?

**Comment by miigotu** [comment]
@fernandog the original function removed a file that is needed (generic.py)

@tloskpd 

stop sickrage, open a terminal and do:
```bash
cd /home/tloskpd/.sickbeard
git reset --hard
git pull
```

**Comment by SunMar** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@8fa7a4bb777c9192bd706115579e540eed8461b2
Link to Log: https://gist.github.com/7bae502592c67155b989
### ERROR
```
Thread-28 :: Failed doing webui callback: Traceback (most recent call last):
  File "D:\Programs\SickRage\sickbeard\webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "D:\Programs\SickRage\sickbeard\webserve.py", line 825, in testTorrent
    client = clients.getClientIstance(torrent_method)
  File "D:\Programs\SickRage\sickbeard\clients\__init__.py", line 118, in getClientIstance
    module = getClientModule(name)
  File "D:\Programs\SickRage\sickbeard\clients\__init__.py", line 114, in getClientModule
    return __import__(prefix + name + '_client', fromlist=__all__)
  File "D:\Programs\SickRage\sickbeard\clients\utorrent_client.py", line 23, in <module>
    from .generic import GenericClient
ImportError: No module named generic

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Dissectional** [comment]
### INFO
Python Version: **2.7.5+ (default, Sep 17 2013, 15:31:50) [GCC 4.8.1]**
Operating System: **Linux-3.11-2-amd64-x86_64-with-LinuxMint-1-debian**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@27ded15e814bcbd47d06d9bf16d130f9d42ebd45
Link to Log: https://gist.github.com/1ee2178aecea11eb707d
### ERROR
```
Thread-30 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/local/src/.sickbeard/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/usr/local/src/.sickbeard/sickbeard/webserve.py", line 825, in testTorrent
    client = clients.getClientIstance(torrent_method)
  File "/usr/local/src/.sickbeard/sickbeard/clients/__init__.py", line 118, in getClientIstance
    module = getClientModule(name)
  File "/usr/local/src/.sickbeard/sickbeard/clients/__init__.py", line 114, in getClientModule
    return __import__(prefix + name + '_client', fromlist=__all__)
  File "/usr/local/src/.sickbeard/sickbeard/clients/rtorrent_client.py", line 24, in <module>
    from .generic import GenericClient
ImportError: No module named generic

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
