### ISSUE TITLE
Problem testing torrent search

### ISSUE THREAD

**Issue by johnvick** [SiCKRAGETV/sickrage-issues#2323]
BRANCH: (master) / COMMIT: (946961f452acb43c39008c847bd8a883c9197503) on Banana Pi

Settings/Search Settings/Torrent Search ......click on test connection and it pulls up the show list.

Restarting  SickRage and restarting Banana Pi - no change. The attached picture illustrates.

![sickrage](https://cloud.githubusercontent.com/assets/10369590/8883680/bbd9921a-32a4-11e5-94fd-a973b8b82026.jpg)
.

**Comment by johnvick** [comment]
This is a log entry just after trying it again:

2015-07-25 08:57:32 Thread-62 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/john/SickRage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/home/john/SickRage/sickbeard/webserve.py", line 815, in testTorrent
    client = clients.getClientIstance(torrent_method)
  File "/home/john/SickRage/sickbeard/clients/__init__.py", line 118, in getClientIstance
    module = getClientModule(name)
  File "/home/john/SickRage/sickbeard/clients/__init__.py", line 114, in getClientModule
    return __import__(prefix + name + '_client', fromlist=__all__)
  File "/home/john/SickRage/sickbeard/clients/transmission_client.py", line 25, in <module>
    from .generic import GenericClient
ImportError: No module named generic

**Comment by fernandog** [comment]
Please search before open issue!!

**Comment by fernandog** [comment]
ImportError: No module named generic
