### ISSUE TITLE
[APP SUBMITTED]: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by jvdpoll** [SiCKRAGETV/sickrage-issues#2331]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 13:42:00) [GCC 4.6.4]**
Operating System: **Linux-2.6.32.12-armv5tel-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@cc698786d1f440ca7017a36ed60831df78ebb391
Link to Log: https://gist.github.com/9794f607bcd3d67937d4
### ERROR
```
Thread-23 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2221, in index
    t.data = markdown2.markdown(changes)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/markdown2.py", line 182, in markdown
    use_file_vars=use_file_vars).convert(text)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/markdown2.py", line 278, in convert
    text = unicode(text, 'utf-8')
TypeError: coercing to Unicode: need string or buffer, NoneType found

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Fixed in develop.
