### ISSUE TITLE
Error when searching thepiratebay. SSL related?

### ISSUE THREAD

**Issue by eli-jordan** [SiCKRAGETV/sickrage-issues#2333]
I get a stack back trace in the logs:

```
2015-07-25 21:19:17 INFO     MAIN :: Checking for XEM scene exception updates for TVRage
AA
AATypeError: __str__ returned non-string (type Error)
AA    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
AA  File "/Users/admin/SickRageTest/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
AA    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
AA  File "/Users/admin/SickRageTest/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
AA    body=body, headers=headers)
AA  File "/Users/admin/SickRageTest/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
AA    timeout=timeout
AA  File "/Users/admin/SickRageTest/SickRage/lib/requests/adapters.py", line 370, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/Users/admin/SickRageTest/SickRage/lib/cachecontrol/adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/Users/admin/SickRageTest/SickRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/Users/admin/SickRageTest/SickRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/Users/admin/SickRageTest/SickRage/lib/requests/sessions.py", line 476, in get
AA    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "/Users/admin/SickRageTest/SickRage/sickbeard/helpers.py", line 1398, in getURL
2015-07-25 21:19:11 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Traceback (most recent call last):
2015-07-25 21:19:11 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Unknown exception in getURL https://thepiratebay.gd/tv/latest/ Error: __str__ returned non-string (type Error)
2015-07-25 21:19:08 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2015-07-25 21:19:08 INFO     DAILYSEARCHER :: No new released episodes found ...
```

I am running on a mac. Prior to getting this problem, I saw an SSL related error, and based on reading other bug reports, performed the following steps.

```
2015-07-25 21:03:38 WARNING  SEARCHQUEUE-BACKLOG-291522 :: Connection error to getURL https://thepiratebay.gd/search/What.Could.Possibly.Go.Wrong%20S01E10%7C1x10%20/0/7/200 Error: error [Errno 1] _ssl.c:507: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```

* Upgraded my openssl version using homebrew
```
admin@mediacenter:~$ openssl version
OpenSSL 1.0.2d 9 Jul 2015
```

* Upgraded my python install using homebrew
```
admin@mediacenter:~$ python --version
Python 2.7.10
```

* Installed several packages using pip
```
admin@mediacenter:~/SickRage$ pip list
cffi (1.1.2)
Cheetah (2.4.4)
cryptography (0.9.3)
enum34 (1.0.4)
idna (2.0)
ipaddress (1.0.14)
lxml (3.4.1)
Markdown (2.2.1)
ndg-httpsclient (0.4.0)
pip (7.1.0)
pyasn1 (0.1.8)
pycparser (2.14)
pyOpenSSL (0.15.1)
setuptools (18.0.1)
six (1.9.0)
urllib3 (1.11)
wheel (0.24.0)
```

* Verified that python is using this version of openssl I upgraded to
```
admin@mediacenter:~$ python -c 'import ssl; print(ssl.OPENSSL_VERSION)'
OpenSSL 1.0.2d 9 Jul 2015
```

Also note that I do get a similar issue when trying a one-liner mentioned elsewhere to test for the problem.

```
admin@mediacenter:~/SickRage$ python -c "import lib.requests.packages.urllib3 as urllib3; ca_certs = 'lib/certifi/cacert.pem'; http = urllib3.PoolManager(cert_reqs='CERT_REQUIRED', ca_certs=ca_certs); r = http.request('GET', 'https://thepiratebay.se/'); print r.status"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "lib/requests/packages/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "lib/requests/packages/urllib3/request.py", line 81, in request_encode_url
    return self.urlopen(method, url, **urlopen_kw)
  File "lib/requests/packages/urllib3/poolmanager.py", line 161, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "lib/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "lib/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type Error)
```

I am not sure what the next troubleshooting steps are? Any help would be greatly appreciated.

**Comment by neoatomic** [comment]
At first glance you have done all the right steps. 
Need to ask, is https://thepiratebay.gd/ blocked in your country.? 

There is a new setting called Verify SSL cert. Disable that and try again.
Also you can try to edit the piratebay code and replace the https urls with http.

**Comment by eli-jordan** [comment]
No thepiratebay.gd is not blocked here in Australia. Disabling verify DSL certs didn't make any difference. What file do I need to change to http not https?

**Comment by neoatomic** [comment]
This is the line. : 
https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/providers/thepiratebay.py#L62
(Shutdown sickrage, change the line, restart end test.)

For testing you can also try another PirateBay domain, not the .GD Maybe the changed something.

**Comment by eli-jordan** [comment]
Thanks for the help. I just figured out what the problem is though. The script I use to launch SickRage was running with a different PATH variable, that didn't include /usr/local/bin and so wan't using the python installed using homebrew.

**Comment by neoatomic** [comment]
Glad you found the problem. :+1:
