### ISSUE TITLE
[APP SUBMITTED]: ('_ssl.c:574: The handshake operation timed out',)

### ISSUE THREAD

**Issue by Rafkat** [SiCKRAGETV/sickrage-issues#2363]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@6831ae9131af765586c1d348cc1835f363f350ce
Link to Log: https://gist.github.com/945f0502500cf53c3d6f
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: _ssl.c:574: The handshake operation timed out
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
One time issue I suspect? Or dsm was down? fix your script =P

**Comment by milesje** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@c6493cd9db2626031c142ce316d20e82a23cf4e4
Link to Log: https://gist.github.com/283f29bc9764c6e564fe
### ERROR
```
Thread-30 :: Traceback (most recent call last):
  File "C:\Users\Jacob\Code\SickRage\sickbeard\logger.py", line 291, in submit_errors
    for report in reports:
  File "C:\Users\Jacob\Code\SickRage\lib\github\PaginatedList.py", line 48, in __iter__
    newElements = self._grow()
  File "C:\Users\Jacob\Code\SickRage\lib\github\PaginatedList.py", line 60, in _grow
    newElements = self._fetchNextPage()
  File "C:\Users\Jacob\Code\SickRage\lib\github\PaginatedList.py", line 158, in _fetchNextPage
    parameters=self.__nextParams
  File "C:\Users\Jacob\Code\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\Users\Jacob\Code\SickRage\lib\github\Requester.py", line 212, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "C:\Users\Jacob\Code\SickRage\lib\github\Requester.py", line 251, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "C:\Users\Jacob\Code\SickRage\lib\github\Requester.py", line 275, in __requestRaw
    requestHeaders
  File "C:\Python27\lib\httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 893, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 855, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 1274, in connect
    server_hostname=server_hostname)
  File "C:\Python27\lib\ssl.py", line 352, in wrap_socket
    _context=self)
  File "C:\Python27\lib\ssl.py", line 579, in __init__
    self.do_handshake()
  File "C:\Python27\lib\ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
SSLError: ('_ssl.c:574: The handshake operation timed out',)

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
