### ISSUE TITLE
[APP SUBMITTED]: Could not decode to UTF-8 column 'resource' with text 'Wayward.Pines.S01E08.SPANISH.ESPAÑOL.HDTV.XviD-DIVXTOTAL'

### ISSUE THREAD

**Issue by pierre2013** [SiCKRAGETV/sickrage-issues#2366]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@6831ae9131af765586c1d348cc1835f363f350ce
No Log available with ERRORS: 
### ERROR
```
Thread-67 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 3630, in index
    [limit])
  File "C:\SickRage\sickbeard\db.py", line 197, in select
    sqlResults = self.action(query, args, fetchall=True)
  File "C:\SickRage\sickbeard\db.py", line 174, in action
    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "C:\SickRage\sickbeard\db.py", line 90, in execute
    return self._execute(query, args).fetchall()
OperationalError: Could not decode to UTF-8 column 'resource' with text 'Wayward.Pines.S01E08.SPANISH.ESPAÑOL.HDTV.XviD-DIVXTOTAL'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Guess this would be resolved if you update. There are about 38 new commits since the once you are on.

**Comment by pierre2013** [comment]
Yes, after the update there is bliss! ;D

Thank you!
