### ISSUE TITLE
NameError: global name 'ep_obj' is not defined while using API

### ISSUE THREAD

**Issue by darklow** [SiCKRAGETV/sickrage-issues#2373]
## Info

Operating system: **Ubuntu 14.04**
Branch: **master**
Python: **2.7.6**
Commit: https://github.com/SiCKRAGETV/SickRage/commit/1ec701e4c12b41d1a34f01ad6091b1fec09967a3
Module: **API**

### Description: 

SickRage produces error when using `episode.subtitlesearch` API:

## Error
```
2015-07-28 16:49:54 DEBUG    TORNADO :: Setter sets location to /www/*******/data/tv/Top Gear/Top.Gear.S04E04.avi
2015-07-28 16:49:54 DEBUG    TORNADO :: 74608: Loading episode details from DB for episode Top Gear S04E04
2015-07-28 16:49:54 DEBUG    TORNADO :: 74608: An object for episode S04E04 didn't exist in the cache, trying to create it
2015-07-28 16:49:54 DEBUG    TORNADO :: API :: episode.subtitlesearch: curKwargs {'season': '4', 'indexerid': '74608', 'episode': '4'}
2015-07-28 16:49:54 DEBUG    TORNADO :: API :: all kwargs: '{'indexerid': '74608', 'season': '4', 'cmd': 'episode.subtitlesearch', 'episode': '4'}'
2015-07-28 16:49:54 DEBUG    TORNADO :: API :: all args: '()'
2015-07-28 16:49:54 DEBUG    TORNADO :: API :: 172.17.42.1 - gave correct API KEY. ACCESS GRANTED
AANameError: global name 'ep_obj' is not defined
AA    newSubtitles = frozenset(ep_obj.subtitles).difference(previous_subtitles)
AA  File "/app/sickrage/sickbeard/webapi.py", line 1103, in run
AA    curOutDict = func(curArgs, curKwargs).run()
AA  File "/app/sickrage/sickbeard/webapi.py", line 188, in call_dispatcher
AA    outDict = _call_dispatcher(args, kwargs)
AA  File "/app/sickrage/sickbeard/webapi.py", line 118, in get
AATraceback (most recent call last):
2015-07-28 16:49:53 ERROR    TORNADO :: API :: global name 'ep_obj' is not defined
2015-07-28 16:49:53 DEBUG    TORNADO :: 276564: No missing subtitles for S02E01
2015-07-28 16:49:53 DEBUG    TORNADO :: 276564: Downloading subtitles for S02E01
```

**Comment by fernandog** [comment]
@darklow what app are you using to access SR?

**Comment by darklow** [comment]
@fernandog 

This error appeared recently. Has been using same code to access api for many months.
Using regular python to access sickrage api:

```py
import requests

url_host = settings.SICKRAGE_HOST
url_base = '%s/api/%s/' % (url_host, key)

def episode_subtitles(tvdb_id, season_nr, episode_nr):
    params = {'cmd': 'episode.subtitlesearch', 'indexerid': tvdb_id,
              'season': season_nr, 'episode': episode_nr}
    r = requests.get(url_base, params=params)
    data = r.json()
    return data
```

**Comment by fernandog** [comment]
try localhost:8081/apibuilder

check if here exists here

**Comment by darklow** [comment]
Same error:
![image](https://cloud.githubusercontent.com/assets/445304/8934477/7ec62948-3550-11e5-89b9-54a5b2696344.png)

**Comment by fernandog** [comment]
@darklow delete that. shows your API

**Comment by fernandog** [comment]
@MGaetan89 do you have that too?

**Comment by miigotu** [comment]
Committed fix to develop, PR'ing now.
