### ISSUE TITLE
Rarbg provider broken

### ISSUE THREAD

**Issue by strike84** [SiCKRAGETV/sickrage-issues#2387]
SR Version:	BRANCH: (master) / COMMIT: (23f36256e8af9383f4bc80ca3b2aca75148a8694)
Python Version:	2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]
OS: Windows 7
What I did: Tried searching with the rarbg provider
What happened: See error below

Every time I update SR I get this when trying to use the Rarbg provider:
```
2015-07-28 21:23:11 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Rarbg search page URL: https://torrentapi.org/pubapi_v2.php?mode=list&app_id=sickrage&category=tv&limit=100&format=json&min_seeders=5&sort=seeders
2015-07-28 21:23:13 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Unknown exception in getURL https://torrentapi.org/pubapi_v2.php?mode=list&app_id=sickrage&category=tv&limit=100&format=json&min_seeders=5&sort=seeders&token=jm238ngqra Error: __str__ returned non-string (type Error)
2015-07-28 21:23:13 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Traceback (most recent call last):

File "C:\SickRage\sickbeard\helpers.py", line 1364, in getURL
    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
  File "C:\SickRage\lib\requests\sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "C:\SickRage\lib\requests\sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\SickRage\lib\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\SickRage\lib\cachecontrol\adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "C:\SickRage\lib\requests\adapters.py", line 370, in send
    timeout=timeout
  File "C:\SickRage\lib\requests\packages\urllib3\connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "C:\SickRage\lib\requests\packages\urllib3\connectionpool.py", line 344, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "C:\SickRage\lib\requests\packages\urllib3\connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type Error)
```
I then have to stop SR, edit rarbg.py by replacing all the https with http. Then it works, I'm just getting tired of doing this every time I update SR.

**Comment by neoatomic** [comment]
Rarbg provider is working fine. You just need  to fix your Python installation. :) 
You can read more about his here what the problem is. https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors

Also see the Windows guides in the link below for some more info and where to get the correct packages.
https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides

**Comment by strike84** [comment]
Ok, thanks, will check the links and see if I can get things working. :)

**Comment by strike84** [comment]
Well, I read the links and I still can't get it to work.. I have the newest OpenSSL which is 1.0.2d. 
I've installed the Python cryptography module, but it won't work. Any ideas?

**Comment by miigotu** [comment]
If you have cryptography you want to update pyOpenSSL completely. 0.13.1 is for people who cant compile the extensions in cryptography.

`sudo pip install -U pyopenssl`

**Comment by strike84** [comment]
Well, I did pip install -U pip pyopenssl
And now the "Unknown exception in getURL" part of the log is gone but instead I get this:

2015-07-30 03:34:00 DEBUG    SEARCHQUEUE-BACKLOG-148581 :: [Rarbg] :: Traceback (most recent call last):
2015-07-30 03:34:00 DEBUG    POSTPROCESSER :: Starting new thread: POSTPROCESSER
AATypeError: __str__ returned non-string (type Error)
AA    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
AA  File "C:\SickRage\lib\requests\packages\urllib3\connectionpool.py", line 314, in _raise_timeout
AA    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
AA  File "C:\SickRage\lib\requests\packages\urllib3\connectionpool.py", line 344, in _make_request
AA    body=body, headers=headers)
AA  File "C:\SickRage\lib\requests\packages\urllib3\connectionpool.py", line 544, in urlopen
AA    timeout=timeout
AA  File "C:\SickRage\lib\requests\adapters.py", line 370, in send
AA    r = adapter.send(request, **kwargs)
AA  File "C:\SickRage\lib\requests\sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "C:\SickRage\lib\requests\sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "C:\SickRage\lib\requests\sessions.py", line 476, in get
AA    response = self.session.get(self.urls['token'], timeout=30, headers=self.headers)
AA  File "C:\SickRage\sickbeard\providers\rarbg.py", line 110, in _doLogin
AA    if not self._doLogin():
AA  File "C:\SickRage\sickbeard\providers\rarbg.py", line 191, in _doSearch
AA    itemList += self._doSearch(curString, 'eponly', len(episodes), epObj=epObj)
AA  File "C:\SickRage\sickbeard\providers\generic.py", line 343, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "C:\SickRage\sickbeard\search.py", line 469, in searchProviders
AATraceback (most recent call last):
2015-07-30 03:34:00 ERROR    SEARCHQUEUE-BACKLOG-148581 :: [Rarbg] :: Error while searching Rarbg, skipping: __str__ returned non-string (type Error)
2015-07-30 03:33:57 INFO     SEARCHQUEUE-BACKLOG-148581 :: [Rarbg] :: Performing episode search for Strike Back

**Comment by miigotu** [comment]
looks like it is just timing out. The token URL isnt even https.

http://torrentapi.org/pubapi_v2.php?get_token=get_token&format=json&app_id=sickrage

**Comment by strike84** [comment]
Humm.. I just can't seem to get this to work. Feel like I've tried everything.. Maybe I just have to edit rarbg.py every time I update SR. The only thing I Haven't tried is to downgrade pyOpenSSL as I'm not sure how to do is in Windows. And do a new install.

**Comment by strike84** [comment]
I guess it's something in my python install that does not work. Can I make rarbg.py read only to combat this problem, I'll guess that could work? So I don't have to edit every time SR updates. Or do I get other problems then?
