### ISSUE TITLE
[APP SUBMITTED]: Thread-48 :: git version returned : 'git' is not recognized as an internal or external command,
operable program or batch file.

### ISSUE THREAD

**Issue by SunMar** [SiCKRAGETV/sickrage-issues#2393]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: ****
Commit: SiCKRAGETV/SickRage@8fa7a4bb777c9192bd706115579e540eed8461b2
Link to Log: https://gist.github.com/abe2ce4e7aa4b74b9a31
### ERROR
```
Thread-48 :: git version returned : 'git' is not recognized as an internal or external command,
operable program or batch file.
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SunMar** [comment]
Heh I think there's an issue with the in-app issue submission, because this is not the error I was trying to submit!

The one I was trying to submit was:
2015-07-30 14:55:01 Thread-46 :: Failed doing webui callback: Traceback (most recent call last):
  File "D:\Programs\SickRage\sickbeard\webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "D:\Programs\SickRage\sickbeard\webserve.py", line 825, in testTorrent
    client = clients.getClientIstance(torrent_method)
  File "D:\Programs\SickRage\sickbeard\clients\__init__.py", line 118, in getClientIstance
    module = getClientModule(name)
  File "D:\Programs\SickRage\sickbeard\clients\__init__.py", line 114, in getClientModule
    return __import__(prefix + name + '_client', fromlist=__all__)
  File "D:\Programs\SickRage\sickbeard\clients\utorrent_client.py", line 23, in <module>
    from .generic import GenericClient
ImportError: No module named generic
