### ISSUE TITLE
[APP SUBMITTED]: Unknown exception while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/77996/en.xml: Traceback (most recent call last):
  File "/opt/sickrage/lib/tvdb_api/tvdb_api.py", line 577, in _loadUrl
    resp = session.get(url.strip(), params=params)
  File "/opt/sickrage/lib/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/opt/sickrage/lib/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/sickrage/lib/requests/sessions.py", line 613, in send
    r.content
  File "/opt/sickrage/lib/requests/models.py", line 733, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/opt/sickrage/lib/requests/models.py", line 656, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/opt/sickrage/lib/requests/packages/urllib3/response.py", line 273, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File 

### ISSUE THREAD

**Issue by gabestover** [SiCKRAGETV/sickrage-issues#2395]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]**
Operating System: **Linux-4.0.4-unRAID-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@6831ae9131af765586c1d348cc1835f363f350ce
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-REFRESH :: Unable to connect to theTVDB while creating meta files - skipping - error Unknown exception while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/77996/en.xml: Traceback (most recent call last):
  File "/opt/sickrage/lib/tvdb_api/tvdb_api.py", line 577, in _loadUrl
    resp = session.get(url.strip(), params=params)
  File "/opt/sickrage/lib/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/opt/sickrage/lib/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/sickrage/lib/requests/sessions.py", line 613, in send
    r.content
  File "/opt/sickrage/lib/requests/models.py", line 733, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/opt/sickrage/lib/requests/models.py", line 656, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/opt/sickrage/lib/requests/packages/urllib3/response.py", line 273, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/opt/sickrage/lib/requests/packages/urllib3/response.py", line 203, in read
    data = self._fp.read(amt)
  File "/opt/sickrage/lib/cachecontrol/filewrapper.py", line 54, in read
    self.__callback(self.__buf.getvalue())
  File "/opt/sickrage/lib/cachecontrol/controller.py", line 244, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/opt/sickrage/lib/cachecontrol/caches/file_cache.py", line 99, in set
    with self.lock_class(name) as lock:
  File "/opt/sickrage/lib/lockfile/__init__.py", line 238, in __enter__
    self.acquire()
  File "/opt/sickrage/lib/lockfile/linklockfile.py", line 34, in acquire
    raise LockFailed("%s" % e.strerror)
LockFailed: Function not implemented

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@miigotu that explains title size error we used to have.

**Comment by miigotu** [comment]
Yep. I thought I added code to catch this exception and pass on it though?

**Comment by miigotu** [comment]
@gabestover https://github.com/SiCKRAGETV/sickrage-issues/issues/2118#issuecomment-121540458
