### ISSUE TITLE
unable to start sickrage due to error:

### ISSUE THREAD

**Issue by thorismud** [SiCKRAGETV/sickrage-issues#2404]
running on Windows 10
Python version 2.6.6
master branch

when i attempt to start the following error shows

c:\>git clone https://github.com/SiCKRAGETV/SickRage.git c:\SickRage
Cloning into 'c:\SickRage'...
remote: Counting objects: 34880, done.
remote: Compressing objects: 100% (157/157), done.
remote: Total 34880 (delta 77), reused 0 (delta 0), pack-reused 34693
Receiving objects: 100% (34880/34880), 34.80 MiB | 1.65 MiB/s, done.
Resolving deltas: 100% (21647/21647), done.
Checking connectivity... done.
Checking out files: 100% (5726/5726), done.

c:\>python c:\SickRage\SickBeard.py

SNI is disabled with pyOpenSSL >= 0.14 when the cryptography module is missing,
you will encounter SSL errors with HTTPS! To fix this issue:
pip install pyopenssl==0.13.1 (easy) or pip install cryptography (pita)
Traceback (most recent call last):
  File "c:\SickRage\SickBeard.py", line 89, in <module>
    import sickbeard
  File "c:\SickRage\sickbeard\__init__.py", line 37, in <module>
    from sickbeard import providers, metadata, config, webserveInit
  File "c:\SickRage\sickbeard\providers\__init__.py", line 59, in <module>
    import generic
  File "c:\SickRage\sickbeard\providers\generic.py", line 32, in <module>
    from sickbeard import helpers, classes, logger, db
  File "c:\SickRage\sickbeard\helpers.py", line 73, in <module>
    from sickbeard.subtitles import isValidLanguage
  File "c:\SickRage\sickbeard\subtitles.py", line 29, in <module>
    import subliminal
  File "c:\SickRage\lib\subliminal\__init__.py", line 9, in <module>
    from .api import list_subtitles, download_subtitles, download_best_subtitles, save_subtitles
  File "c:\SickRage\lib\subliminal\api.py", line 9, in <module>
    from .providers import ProviderPool
  File "c:\SickRage\lib\subliminal\providers\__init__.py", line 9, in <module>
    from ..video import Episode, Movie
  File "c:\SickRage\lib\subliminal\video.py", line 10, in <module>
    import guessit
  File "c:\SickRage\lib\guessit\__init__.py", line 88, in <module>
    from guessit.guess import Guess, smart_merge
  File "c:\SickRage\lib\guessit\guess.py", line 29, in <module>
    from guessit.textutils import common_words
  File "c:\SickRage\lib\guessit\textutils.py", line 250
    _camel_word2_set = {'is', 'to'}
                            ^
SyntaxError: invalid syntax

**Comment by neoatomic** [comment]
You need at least Python 2.7 (with pyopenssl and cryptogafie modules) to run SickRage.

**Comment by TimDowker** [comment]
Since when has python 2.7 been a requirement????

**Comment by miigotu** [comment]
Since 2.6 support has been dropped by all major Python libraries, and it was necessary for us to update the libraries to fix bugs.

**Comment by TimDowker** [comment]
OK, thank you for letting me know. Curious what ipkg users should do as there doesn't seem to be a Cheetah package available yet for python 2.7 under ipkg. I'm running Sickrage on a WD My Book Live and when I try to start it now with python 2.7 installed it states the following

The Python module Cheetah is required

**Comment by WebSpider** [comment]
We're moving away from Cheetah to Mako :)

-----Original Message-----

**Comment by miigotu** [comment]
```
ipkg install python27
ipkg install py27-setuptools
easy_install-2.7 pip
pip2.7 install cheetah
```

**Comment by TimDowker** [comment]
Awesome! Thank you!

**Comment by miigotu** [comment]
Does it work?

**Comment by TimDowker** [comment]
Actually was able to work around it by setting an alias in .bashrc to python 2.7 and manually installing Cheetah from source.

**Comment by miigotu** [comment]
ok, closing this then xD.

**Comment by eduardogd** [comment]
how about openelec on raspberry pi? I have this same issue before update:

OpenELEC:~ # /usr/bin/python /storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/SickBeard.py --daemon --datadir /storage/.kodi/userdata/addon_data/service.downloadmanager.SickPotato
Head/ --pidfile=/var/run/sickbeard.pid --config /storage/.kodi/userdata/addon_data/service.downloadmanager.SickPotatoHead/sickbeard.ini --nolaunch

SNI is disabled with pyOpenSSL >= 0.14 when the cryptography module is missing,
you will encounter SSL errors with HTTPS! To fix this issue:
pip install pyopenssl==0.13.1 (easy) or pip install cryptography (pita)
Traceback (most recent call last):
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/SickBeard.py", line 76, in <module>
    import sickbeard
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/__init__.py", line 37, in <module>
    from . import providers, metadata, config, webserveInit
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/providers/__init__.py", line 58, in <module>
    import generic
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/providers/generic.py", line 32, in <module>
    from sickbeard import helpers, classes, logger, db
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/helpers.py", line 75, in <module>
    from sickbeard.subtitles import isValidLanguage
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/subtitles.py", line 29, in <module>
    import subliminal
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/lib/subliminal/__init__.py", line 9, in <module>
    from .api import list_subtitles, download_subtitles, download_best_subtitles, save_subtitles
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/lib/subliminal/api.py", line 8, in <module>
    import babelfish
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/lib/babelfish/__init__.py", line 20, in <module>
    from .converters import (LanguageConverter, LanguageReverseConverter, LanguageEquivalenceConverter, CountryConverter,
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/lib/babelfish/converters/__init__.py", line 6, in <module>
    from pkg_resources import iter_entry_points, EntryPoint
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/lib/pkg_resources.py", line 698, in <module>
    class Environment(object):
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/lib/pkg_resources.py", line 701, in Environment
    def __init__(self, search_path=None, platform=get_supported_platform(), python=PY_MAJOR):
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/lib/pkg_resources.py", line 96, in get_supported_platform
    plat = get_build_platform(); m = macosVersionString.match(plat)
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/lib/pkg_resources.py", line 221, in get_build_platform
    from distutils.util import get_platform
ImportError: No module named distutils.util
OpenELEC:~ #

**Comment by WebSpider** [comment]
Are you sure this is SickRage and not Sick-Beard?

Afaik, SickPotatoHead contains Sick-Beard

-----Original Message-----

**Comment by eduardogd** [comment]
My mistake, sorry :)

**Comment by miigotu** [comment]
@eduardogd even though you are off-topic and off-project, just want to let you know that a few days ago in the MilHouse releases they updated to python 2.7.10 and re-enabled distutils...

**Comment by eduardogd** [comment]
@miigotu great news, thanks for support and really sorry about my mistake.
