### ISSUE TITLE
[APP SUBMITTED]: <ProtocolError for api.opensubtitles.org/xml-rpc: 503 Service Unavailable>

### ISSUE THREAD

**Issue by pct00** [SiCKRAGETV/sickrage-issues#244]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@49ea8f5ac7841f6654509d48d72506923bc47c2a
### ERROR
```
FINDSUBTITLES :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "C:\Users\Pedro\Desktop\SickRage-master\sickbeard\tv.py", line 1392, in downloadSubtitles
    multi=sickbeard.SUBTITLES_MULTI, cache_dir=sickbeard.CACHE_DIR)
  File "C:\Users\Pedro\Desktop\SickRage-master\lib\subliminal\api.py", line 95, in download_subtitles
    subtitles_by_video = list_subtitles(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "C:\Users\Pedro\Desktop\SickRage-master\lib\subliminal\api.py", line 62, in list_subtitles
    service_instance.terminate()
  File "C:\Users\Pedro\Desktop\SickRage-master\lib\subliminal\services\opensubtitles.py", line 103, in terminate
    raise ServiceError(str(e))
ServiceError: <ProtocolError for api.opensubtitles.org/xml-rpc: 503 Service Unavailable>

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
not an issue. Open subtitle as down.
