### ISSUE TITLE
2 Errors During sabToSickBeard.py Postprocessing

### ISSUE THREAD

**Issue by LanMan04** [SiCKRAGETV/sickrage-issues#2450]
When an episode is post-processing via the sabToSickBeard.py script on download completion, two errors result.  Both errors like like they're within SickBeard, not the processing script:

```
File "/opt/sickrage/lib/tvdb_api/tvdb_api.py", line 635, in _getetsrc
    raise tvdb_error(e)
tvdb_error: Unknown exception while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/276564/en.xml
```
followed by
```
  File "/opt/sickrage/lib/lockfile/linklockfile.py", line 34, in acquire
    raise LockFailed("%s" % e.strerror)
LockFailed: Function not implemented
```
The episode is correctly moved and renamed during post-processing (and appears as downloaded on the show's detail page), but it never appears in the History tab with a "Downloaded" entry (initial Snatch does show up).

I did manually load the URL from the first error via browser URL bar, and it comes up just fine (URL is valid).

Commit:  99ecfb5edcae4a8e5facff73f39ff1415a5e3e96
Python version:  2.7.10 (default, May 26 2015, 04:16:29) [GCC 5.1.0]

Full trace:

```
2015-08-11 09:43:03 Thread-49 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 2306, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/opt/sickrage/sickbeard/processTV.py", line 251, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/opt/sickrage/sickbeard/processTV.py", line 491, in process_media
    result.result = processor.process()
  File "/opt/sickrage/sickbeard/postProcessor.py", line 1080, in process
    ep_obj.createMetaFiles()
  File "/opt/sickrage/sickbeard/tv.py", line 1912, in createMetaFiles
    self.createThumbnail()
  File "/opt/sickrage/sickbeard/tv.py", line 1931, in createThumbnail
    result = cur_provider.create_episode_thumb(self) or result
  File "/opt/sickrage/sickbeard/metadata/generic.py", line 332, in create_episode_thumb
    return self.save_thumbnail(ep_obj)
  File "/opt/sickrage/sickbeard/metadata/generic.py", line 499, in save_thumbnail
    thumb_url = self._get_episode_thumb_url(ep_obj)
  File "/opt/sickrage/sickbeard/metadata/generic.py", line 386, in _get_episode_thumb_url
    myEp = helpers.validateShow(cur_ep.show, cur_ep.season, cur_ep.episode)
  File "/opt/sickrage/sickbeard/helpers.py", line 1099, in validateShow
    return t[show.indexerid][season][episode]
  File "/opt/sickrage/lib/tvdb_api/tvdb_api.py", line 951, in __getitem__
    self._getShowData(key, self.config['language'], True)
  File "/opt/sickrage/lib/tvdb_api/tvdb_api.py", line 846, in _getShowData
    self.config['url_seriesInfo'] % (sid, getShowInLanguage)
  File "/opt/sickrage/lib/tvdb_api/tvdb_api.py", line 635, in _getetsrc
    raise tvdb_error(e)
tvdb_error: Unknown exception while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/276564/en.xml: Traceback (most recent call last):
  File "/opt/sickrage/lib/tvdb_api/tvdb_api.py", line 577, in _loadUrl
    resp = session.get(url.strip(), params=params)
  File "/opt/sickrage/lib/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/opt/sickrage/lib/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/sickrage/lib/requests/sessions.py", line 613, in send
    r.content
  File "/opt/sickrage/lib/requests/models.py", line 733, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/opt/sickrage/lib/requests/models.py", line 656, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/opt/sickrage/lib/requests/packages/urllib3/response.py", line 273, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/opt/sickrage/lib/requests/packages/urllib3/response.py", line 203, in read
    data = self._fp.read(amt)
  File "/opt/sickrage/lib/cachecontrol/filewrapper.py", line 54, in read
    self.__callback(self.__buf.getvalue())
  File "/opt/sickrage/lib/cachecontrol/controller.py", line 244, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/opt/sickrage/lib/cachecontrol/caches/file_cache.py", line 99, in set
    with self.lock_class(name) as lock:
  File "/opt/sickrage/lib/lockfile/__init__.py", line 238, in __enter__
    self.acquire()
  File "/opt/sickrage/lib/lockfile/linklockfile.py", line 34, in acquire
    raise LockFailed("%s" % e.strerror)
LockFailed: Function not implemented
```

**Comment by miigotu** [comment]
@Thraxis ?

**Comment by LanMan04** [comment]
I forgot to mention that Failed Download Handing doesn't trigger this issue (it works correctly, failed download is detected, snatches another version, etc).  Only happens when the download is successful.

**Comment by miigotu** [comment]
@LanMan04 I know, this is a known issue with Unraid, and certain docker versions.

read this comment: https://github.com/SiCKRAGETV/sickrage-issues/issues/2118#issuecomment-129706849

You might find some other info in that thread.

**Comment by LanMan04** [comment]
Thanks!  So sickrage/docker doesn't like the "virtual" user path.  Understood.
