### ISSUE TITLE
[APP SUBMITTED]: global name 'use_imdb_popular' is not defined

### ISSUE THREAD

**Issue by devenashani** [SiCKRAGETV/sickrage-issues#2484]
### INFO
Python Version: **2.7.3 (default, Jul 13 2012, 04:03:47) [GCC 4.4.5]**
Operating System: **Linux-2.6.31.8.nv+v2-armv5tel-with-debian-6.0.3**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@6758e3e6283948544234cfccaadc4369441cdf07
No Log available with ERRORS: 
### ERROR
```
Thread-61 :: Failed doing webui callback: Traceback (most recent call last):
  File "/root/.sickrage/sickbeard/webserve.py", line 260, in async_call
    result = function(**kwargs)
  File "/root/.sickrage/sickbeard/webserve.py", line 4902, in saveNotifications
    sickbeard.USE_IMDB_POPULAR = config.checkbox_to_value(use_imdb_popular)
NameError: global name 'use_imdb_popular' is not defined

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by adelatour11** [comment]
I have the same issue when trying to set the pushbullet notification, each time i want to save it it give this error :+1: 

<h1>ERROR</h1>

```
AANameError: global name 'use_imdb_popular' is not defined AA    sickbeard.USE_IMDB_POPULAR = config.checkbox_to_value(use_imdb_popular)
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 4902, in saveNotifications
AA    result = function(**kwargs)
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 260, in async_call
AA    result = self.fn(*self.args, **self.kwargs)
AA  File "/usr/local/sickrage/var/SickRage/lib/concurrent/futures/thread.py", line 61, in run
AA    exec('raise exc_type, exc_value, traceback', {}, locals_)
AA  File "/usr/local/sickrage/var/SickRage/lib/concurrent/futures/_compat.py", line 107, in reraise
AA    reraise(self._exception, self._traceback)
AA  File "/usr/local/sickrage/var/SickRage/lib/concurrent/futures/_base.py", line 359, in __get_result
AA    return self.__get_result()
AA  File "/usr/local/sickrage/var/SickRage/lib/concurrent/futures/_base.py", line 400, in result
AA    value = future.result()
AA  File "/volume1/@appstore/sickrage/var/SickRage/tornado/gen.py", line 807, in run
AA    results = yield self.async_call(method)
AA  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 245, in get
AANameError: global name 'use_imdb_popular' is not defined
AA    sickbeard.USE_IMDB_POPULAR = config.checkbox_to_value(use_imdb_popular)
```

**Comment by WebSpider** [comment]
Woops. You will get this when saving any kind of config probably. I'll provide a fix in about 4h.
