### ISSUE TITLE
[APP SUBMITTED]: '_home_supergonkas_SickRage_gui_slick_interfaces_default_comingEpisodes_mako'

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2486]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-25-generic-i686-with-Ubuntu-15.04-vivid**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@cb82f7f587072c95532256aa529d6b34cc26d5f6
Link to Log: https://gist.github.com/814f71119c9e3d387131
### ERROR
```
Thread-25 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 260, in async_call
    result = function(**kwargs)
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 542, in comingEpisodes
    t = PageTemplate(rh=self, file="comingEpisodes.mako")
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 109, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/home/supergonkas/SickRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/supergonkas/SickRage/lib/mako/template.py", line 380, in _compile_from_file
    del sys.modules[self.module_id]
KeyError: '_home_supergonkas_SickRage_gui_slick_interfaces_default_comingEpisodes_mako'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
stop SR, delete cache/mako
