### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-72173 :: [KickAssTorrents] :: Failed parsing KickAssTorrents

### ISSUE THREAD

**Issue by raymondtrueman** [SiCKRAGETV/sickrage-issues#2494]
### INFO
Python Version: **2.7.10 (default, Jun  4 2015, 01:18:03) [GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@2c4bfe44c0f9a37533cfdaea3dc28fdb85cf2e4b
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-72173 :: [KickAssTorrents] :: Failed parsing KickAssTorrents Traceback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/kat.py", line 140, in _find_season_quality
    quality = Quality.assumeQuality(fileName)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/common.py", line 262, in assumeQuality
    quality = Quality.qualityFromFileMeta(name)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/common.py", line 278, in qualityFromFileMeta
    parser = createParser(filename)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/hachoir_parser/guess.py", line 136, in createParser
    stream = FileInputStream(filename, real_filename, tags=tags)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/hachoir_core/stream/input_helper.py", line 21, in FileInputStream
    raise InputStreamError(_("Unable to open file %s: %s") % (filename, errmsg))
InputStreamError: Unable to open file Arrested Development S04E08 - Red Hairing.avi: [Errno 2] No such file or directory: u'Arrested Development S04E08 - Red Hairing.avi'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by raymondtrueman** [comment]
Don't understand why its trying to open a file that doesnt exist while its doing a backlog search.... This episode is wanted though

**Comment by WebSpider** [comment]
We need debug logs for this. Please add them as a gist and let us know the link.

**Comment by raymondtrueman** [comment]
@WebSpider http://pastebin.com/qWy9XPPd

**Comment by miigotu** [comment]
Assume quality should only be run for files that already are downloaded....
