### ISSUE TITLE
[APP SUBMITTED]: 'module' object has no attribute '_magic_number'

### ISSUE THREAD

**Issue by Molleke** [SiCKRAGETV/sickrage-issues#2497]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@28f5ad86acc29882918e4671c000259dbe47d09a
Link to Log: https://gist.github.com/c9d7766cac64a9990536
### ERROR
```
Thread-29 :: Failed doing webui callback: Traceback (most recent call last):
  File "f:\Program Files (x86)\SickRage-develop\sickbeard\webserve.py", line 260, in async_call
    result = function(**kwargs)
  File "f:\Program Files (x86)\SickRage-develop\sickbeard\webserve.py", line 741, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "f:\Program Files (x86)\SickRage-develop\sickbeard\webserve.py", line 109, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "f:\Program Files (x86)\SickRage-develop\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "f:\Program Files (x86)\SickRage-develop\lib\mako\template.py", line 381, in _compile_from_file
    if module._magic_number != codegen.MAGIC_NUMBER:
AttributeError: 'module' object has no attribute '_magic_number'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by WebSpider** [comment]
@miigotu ?

**Comment by thesatman** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7600**
Branch: **master**
Commit: SiCKRAGETV/SickRage@303d80c3aa6539fc7fe00dd1a603290d1f954d75
No Log available with ERRORS: 
### ERROR
```
Thread-53 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 645, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 101, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 381, in _compile_from_file
    if module._magic_number != codegen.MAGIC_NUMBER:
AttributeError: 'module' object has no attribute '_magic_number'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by thesatman** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7600**
Branch: **master**
Commit: SiCKRAGETV/SickRage@303d80c3aa6539fc7fe00dd1a603290d1f954d75
No Log available with ERRORS: 
### ERROR
```
Thread-38 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 645, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 101, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 381, in _compile_from_file
    if module._magic_number != codegen.MAGIC_NUMBER:
AttributeError: 'module' object has no attribute '_magic_number'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by thesatman** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7600**
Branch: **master**
Commit: SiCKRAGETV/SickRage@303d80c3aa6539fc7fe00dd1a603290d1f954d75
No Log available with ERRORS: 
### ERROR
```
Thread-37 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 645, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 101, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 381, in _compile_from_file
    if module._magic_number != codegen.MAGIC_NUMBER:
AttributeError: 'module' object has no attribute '_magic_number'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by thesatman** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7600**
Branch: **master**
Commit: SiCKRAGETV/SickRage@303d80c3aa6539fc7fe00dd1a603290d1f954d75
No Log available with ERRORS: 
### ERROR
```
Thread-46 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 645, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 101, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 381, in _compile_from_file
    if module._magic_number != codegen.MAGIC_NUMBER:
AttributeError: 'module' object has no attribute '_magic_number'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by thesatman** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7600**
Branch: **master**
Commit: SiCKRAGETV/SickRage@303d80c3aa6539fc7fe00dd1a603290d1f954d75
No Log available with ERRORS: 
### ERROR
```
Thread-23 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 645, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 101, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 381, in _compile_from_file
    if module._magic_number != codegen.MAGIC_NUMBER:
AttributeError: 'module' object has no attribute '_magic_number'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by thesatman** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7600**
Branch: **master**
Commit: SiCKRAGETV/SickRage@303d80c3aa6539fc7fe00dd1a603290d1f954d75
No Log available with ERRORS: 
### ERROR
```
Thread-52 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 645, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 101, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 381, in _compile_from_file
    if module._magic_number != codegen.MAGIC_NUMBER:
AttributeError: 'module' object has no attribute '_magic_number'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by thesatman** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7600**
Branch: **master**
Commit: SiCKRAGETV/SickRage@303d80c3aa6539fc7fe00dd1a603290d1f954d75
No Log available with ERRORS: 
### ERROR
```
Thread-57 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 645, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 101, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 381, in _compile_from_file
    if module._magic_number != codegen.MAGIC_NUMBER:
AttributeError: 'module' object has no attribute '_magic_number'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by thesatman** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7600**
Branch: **master**
Commit: SiCKRAGETV/SickRage@303d80c3aa6539fc7fe00dd1a603290d1f954d75
No Log available with ERRORS: 
### ERROR
```
Thread-50 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 645, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 101, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 381, in _compile_from_file
    if module._magic_number != codegen.MAGIC_NUMBER:
AttributeError: 'module' object has no attribute '_magic_number'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by thesatman** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7600**
Branch: **master**
Commit: SiCKRAGETV/SickRage@303d80c3aa6539fc7fe00dd1a603290d1f954d75
No Log available with ERRORS: 
### ERROR
```
Thread-51 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 645, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 101, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 381, in _compile_from_file
    if module._magic_number != codegen.MAGIC_NUMBER:
AttributeError: 'module' object has no attribute '_magic_number'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by thesatman** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7600**
Branch: **master**
Commit: SiCKRAGETV/SickRage@303d80c3aa6539fc7fe00dd1a603290d1f954d75
No Log available with ERRORS: 
### ERROR
```
Thread-39 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 645, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 101, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 381, in _compile_from_file
    if module._magic_number != codegen.MAGIC_NUMBER:
AttributeError: 'module' object has no attribute '_magic_number'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by thesatman** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7600**
Branch: **master**
Commit: SiCKRAGETV/SickRage@303d80c3aa6539fc7fe00dd1a603290d1f954d75
No Log available with ERRORS: 
### ERROR
```
Thread-54 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 645, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 101, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 381, in _compile_from_file
    if module._magic_number != codegen.MAGIC_NUMBER:
AttributeError: 'module' object has no attribute '_magic_number'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by thesatman** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7600**
Branch: **master**
Commit: SiCKRAGETV/SickRage@303d80c3aa6539fc7fe00dd1a603290d1f954d75
No Log available with ERRORS: 
### ERROR
```
Thread-47 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 645, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 101, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 381, in _compile_from_file
    if module._magic_number != codegen.MAGIC_NUMBER:
AttributeError: 'module' object has no attribute '_magic_number'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by thesatman** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7600**
Branch: **master**
Commit: SiCKRAGETV/SickRage@303d80c3aa6539fc7fe00dd1a603290d1f954d75
Link to Log: https://gist.github.com/a34b3b4740c58912646d
### ERROR
```
Thread-29 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 645, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 101, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 381, in _compile_from_file
    if module._magic_number != codegen.MAGIC_NUMBER:
AttributeError: 'module' object has no attribute '_magic_number'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by thesatman** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7600**
Branch: **master**
Commit: SiCKRAGETV/SickRage@303d80c3aa6539fc7fe00dd1a603290d1f954d75
Link to Log: https://gist.github.com/9dd1f64f403eea77ef9d
### ERROR
```
Thread-34 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 645, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 101, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 381, in _compile_from_file
    if module._magic_number != codegen.MAGIC_NUMBER:
AttributeError: 'module' object has no attribute '_magic_number'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
stop SR, delete SickRage/cache/mako, start again
