### ISSUE TITLE
[APP SUBMITTED]: Loaded module C__SickRage_gui_slick_interfaces_default_home_mako not found in sys.modules

### ISSUE THREAD

**Issue by oconnellkj** [SiCKRAGETV/sickrage-issues#2507]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@fe0111aa88dc6d65177f339e643ca971405f926f
No Log available with ERRORS: 
### ERROR
```
Thread-20 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 260, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 741, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 109, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module C__SickRage_gui_slick_interfaces_default_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by WebSpider** [comment]
Stop SR, delete C:\SickRage\cache\mako and restart SR

**Comment by ruinit** [comment]
not to hijack but I stopped sickrage, delete cache\mako folder still getting errors.

2015-08-18 15:29:08 Thread-64 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 260, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 741, in index
    t = PageTemplate(rh=self, file="home.mako")
