### ISSUE TITLE
Still getting this error

### ISSUE THREAD

**Issue by ruinit** [SiCKRAGETV/sickrage-issues#2519]
BRANCH: (master) / COMMIT: (7a432bd2eab0f74f89cdf330b0e1af342cf25030) 
Synology Diskstation ds1513+
```
2015-08-19 17:34:36 Thread-42 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 260, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 741, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 109, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/template.py", line 380, in _compile_from_file
    del sys.modules[self.module_id]
KeyError: '_usr_local_sickbeard_custom_var_SickBeard_gui_slick_interfaces_default_home_mako'
```

**Comment by WebSpider** [comment]
Stopping SR, removing /usr/local/sickbeard-custom/var/SickBeard/cache/mako and restarting it didnt solve the problem?

**Comment by ruinit** [comment]
no sorry didn't solve problem just tried again

**Comment by WebSpider** [comment]
Please post the complete error

**Comment by ruinit** [comment]
2015-08-20 16:59:53 Thread-29 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 260, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 741, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 109, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/template.py", line 380, in _compile_from_file
    del sys.modules[self.module_id]
KeyError: '_usr_local_sickbeard_custom_var_SickBeard_gui_slick_interfaces_default_home_mako'

**Comment by neoatomic** [comment]
@ruinit See if you can switch to the official SickRage package on the SynoCommunity Repo. 
And only restore the config.ini and sickbeard.db , not the cache folder.

**Comment by ruinit** [comment]
Same issue now running BRANCH: (master) / COMMIT: (5770d33ef96e619af764b452ea35ad33e5755add) 

2015-08-21 18:33:17 Thread-47 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 260, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 741, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 109, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 380, in _compile_from_file
    del sys.modules[self.module_id]
KeyError: '_usr_local_sickrage_var_SickRage_gui_slick_interfaces_default_home_mako'

**Comment by neoatomic** [comment]
@ruinit Its running fine here on my Synology... 
Or are you using xpenology .?

**Comment by ruinit** [comment]
No I'm on Synology just started getting these errors after the mako stuff was added?

**Comment by WebSpider** [comment]
Please stop sr, remove /usr/local/sickrage/var/cache/mako and restart.

I've had this as well, when upgrading on Synology, usually due the mako cache being misaligned with source updates.

-----Original Message-----

**Comment by ruinit** [comment]
you did read my posts correct? I have done all this many times over. still getting error but thanks for the input
