### ISSUE TITLE
[APP SUBMITTED]: Loaded module _share_HDA_DATA__qpkg_SickBeard_TVRage_gui_slick_interfaces_default_displayShow_mako not found in sys.modules

### ISSUE THREAD

**Issue by kriebb** [SiCKRAGETV/sickrage-issues#2525]
### INFO
Python Version: **2.7.3 (default, Apr 12 2012, 13:08:47) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@7a432bd2eab0f74f89cdf330b0e1af342cf25030
No Log available with ERRORS: 
### ERROR
```
Thread-21 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/sickbeard/webserve.py", line 260, in async_call
    result = function(**kwargs)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/sickbeard/webserve.py", line 1238, in displayShow
    t = PageTemplate(rh=self, file="displayShow.mako")
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/sickbeard/webserve.py", line 109, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _share_HDA_DATA__qpkg_SickBeard_TVRage_gui_slick_interfaces_default_displayShow_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by WebSpider** [comment]
Stop SR, remove cache/mako and restart SR

**Comment by WebSpider** [comment]
Oh and be sure to let us know if this resolved the problem :)

**Comment by neoatomic** [comment]
@kriebb Also use this package. : http://apps.qnap.community/11-community/17-qsickrage
(Your current one has probably SSL problems.)
