### ISSUE TITLE
[APP SUBMITTED]: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by creamerssubmit** [SiCKRAGETV/sickrage-issues#2545]
### INFO
Python Version: **2.7.2 (default, Jun 12 2011, 15:08:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@5770d33ef96e619af764b452ea35ad33e5755add
Link to Log: https://gist.github.com/1b643f1df6cbefd959b5
### ERROR
```
Thread-78 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 260, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 2276, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "C:\SickRage\sickbeard\processTV.py", line 204, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "C:\SickRage\sickbeard\processTV.py", line 491, in process_media
    result.result = processor.process()
  File "C:\SickRage\sickbeard\postProcessor.py", line 864, in process
    new_ep_quality = self._get_quality(ep_obj)
  File "C:\SickRage\sickbeard\postProcessor.py", line 733, in _get_quality
    ep_quality = common.Quality.assumeQuality(self.file_path)
  File "C:\SickRage\sickbeard\common.py", line 262, in assumeQuality
    quality = Quality.qualityFromFileMeta(name)
  File "C:\SickRage\sickbeard\common.py", line 278, in qualityFromFileMeta
    parser = createParser(filename)
  File "C:\SickRage\lib\hachoir_parser\guess.py", line 137, in createParser
    return guessParser(stream)
  File "C:\SickRage\lib\hachoir_parser\guess.py", line 123, in guessParser
    return QueryParser(stream.tags).parse(stream)
  File "C:\SickRage\lib\hachoir_parser\guess.py", line 91, in parse
    parser = self.doparse(stream, fallback)
  File "C:\SickRage\lib\hachoir_parser\guess.py", line 101, in doparse
    parser_obj = parser(stream, validate=self.validate)
  File "C:\SickRage\lib\hachoir_parser\video\mov.py", line 848, in __init__
    Parser.__init__(self, *args, **kw)
  File "C:\SickRage\lib\hachoir_parser\parser.py", line 153, in __init__
    HachoirParser.__init__(self, stream, **args)
  File "C:\SickRage\lib\hachoir_parser\parser.py", line 37, in __init__
    res = self.validate()
  File "C:\SickRage\lib\hachoir_parser\video\mov.py", line 854, in validate
    size = self.stream.readBits(0, 32, self.endian)
  File "C:\SickRage\lib\hachoir_core\stream\input.py", line 180, in readBits
    shift, data, missing = self.read(address, nbits)
  File "C:\SickRage\lib\hachoir_core\stream\input.py", line 405, in read
    data = self._input.read(size)
IOError: [Errno 22] Invalid argument

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by creamerssubmit** [comment]
I am trying to fix a issue of Sickrage not post processing episodes, I am currently trying to use the manual post processor to help solve my issue. I either get this error above or I get a error about the file being locked. When I investigate the file lock I look at the SMB server (2012) R2 and it says the file is only open for read. When I log into the service account on the box running Sickrage I can cut and paste the file both on network shares and local drives. The files are not locked except from when Sickrage is running a post process and then it unlocks them. Though it thinks they are locked since it is currently touching the files at that moment.

2015-08-22 17:27:13 INFO     Thread-55 :: Your issue ticket #2545 was submitted successfully!
2015-08-22 17:27:13 WARNING  POSTPROCESSER :: [T:\Downloaded Torrents\The Tonight Show Starring Jimmy Fallon-S2E189.mp4 : Processing failed: File is locked for reading/writing]
2015-08-22 17:27:13 WARNING  POSTPROCESSER :: [T:\Downloaded Torrents\The Tonight Show Starring Jimmy Fallon 2015.08.20.mp4 : Processing failed: File is locked for reading/writing]
2015-08-22 17:27:13 WARNING  POSTPROCESSER :: Problem(s) during processing, failed the following files/folders:  
2015-08-22 17:27:13 WARNING  POSTPROCESSER :: Processing failed for T:\Downloaded Torrents\The Tonight Show Starring Jimmy Fallon-S2E189.mp4: File is locked for reading/writing
2015-08-22 17:27:13 INFO     POSTPROCESSER :: Processing T:\Downloaded Torrents\The Tonight Show Starring Jimmy Fallon-S2E189.mp4 (None)
2015-08-22 17:27:13 WARNING  POSTPROCESSER :: Processing failed for T:\Downloaded Torrents\The Tonight Show Starring Jimmy Fallon 2015.08.20.mp4: File is locked for reading/writing
2015-08-22 17:27:12 INFO     POSTPROCESSER :: Processing T:\Downloaded Torrents\The Tonight Show Starring Jimmy Fallon 2015.08.20.mp4 (None)
2015-08-22 17:27:12 INFO     POSTPROCESSER :: Processing succeeded for T:\Downloaded Torrents\Hot in Cleveland-S2E11.mp4
2015-08-22 17:27:06 INFO     POSTPROCESSER :: Processing T:\Downloaded Torrents\Hot in Cleveland-S2E11.mp4 (None)
2015-08-22 17:27:06 INFO     POSTPROCESSER :: PostProcessing Path: T:\Downloaded Torrents
2015-08-22 17:26:27 ERROR    Thread-78 :: Failed doing webui callback: Traceback (most recent call last):
2015-08-22 17:26:27 INFO     Thread-78 :: Processing T:\Downloaded Torrents\The Tonight Show Starring Jimmy Fallon 2015.08.20.mp4 (None)
2015-08-22 17:26:27 WARNING  Thread-78 :: Processing failed for T:\Downloaded Torrents\Hot in Cleveland-S2E11.mp4: File is locked for reading/writing
2015-08-22 17:26:27 INFO     Thread-78 :: Processing T:\Downloaded Torrents\Hot in Cleveland-S2E11.mp4 (None)
2015-08-22 17:26:26 INFO     Thread-78 :: PostProcessing Path: T:\Downloaded Torrents

**Comment by miigotu** [comment]
Known issue, working on a fix already. Please use the existing issues next time before opening a new one.

**Comment by RDgiuliom** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.2.0-bananian-armv7l-with-debian-8.2**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@638270689679f3958d1b593c329e7c6e5cb7448e
Link to Log: https://gist.github.com/c320f19dc1dafa5cb160
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/tv.py", line 1479, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/opt/sickrage/sickbeard/tv.py", line 1453, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/opt/sickrage/sickbeard/subtitles.py", line 103, in subtitlesLanguages
    mkv = MKV(f)
  File "/opt/sickrage/lib/enzyme/mkv.py", line 40, in __init__
    segments = ebml.parse(stream, specs, ignore_element_names=['EBML'], max_level=0)
  File "/opt/sickrage/lib/enzyme/parsers/ebml/core.py", line 177, in parse
    stream.seek(element.size, 1)
IOError: [Errno 22] Invalid argument

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by RDgiuliom** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.2.0-bananian-armv7l-with-debian-8.2**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@638270689679f3958d1b593c329e7c6e5cb7448e
Link to Log: https://gist.github.com/0a082f4e73a89ffbdb04
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/tv.py", line 1479, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/opt/sickrage/sickbeard/tv.py", line 1453, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/opt/sickrage/sickbeard/subtitles.py", line 103, in subtitlesLanguages
    mkv = MKV(f)
  File "/opt/sickrage/lib/enzyme/mkv.py", line 40, in __init__
    segments = ebml.parse(stream, specs, ignore_element_names=['EBML'], max_level=0)
  File "/opt/sickrage/lib/enzyme/parsers/ebml/core.py", line 177, in parse
    stream.seek(element.size, 1)
IOError: [Errno 22] Invalid argument

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by RDgiuliom** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.2.0-bananian-armv7l-with-debian-8.2**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@638270689679f3958d1b593c329e7c6e5cb7448e
Link to Log: https://gist.github.com/1584bc945c62781353a2
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/tv.py", line 1479, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/opt/sickrage/sickbeard/tv.py", line 1453, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/opt/sickrage/sickbeard/subtitles.py", line 103, in subtitlesLanguages
    mkv = MKV(f)
  File "/opt/sickrage/lib/enzyme/mkv.py", line 40, in __init__
    segments = ebml.parse(stream, specs, ignore_element_names=['EBML'], max_level=0)
  File "/opt/sickrage/lib/enzyme/parsers/ebml/core.py", line 177, in parse
    stream.seek(element.size, 1)
IOError: [Errno 22] Invalid argument

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by RDgiuliom** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.2.0-bananian-armv7l-with-debian-8.2**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@638270689679f3958d1b593c329e7c6e5cb7448e
No Log available with ERRORS: 
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/tv.py", line 1479, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/opt/sickrage/sickbeard/tv.py", line 1453, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/opt/sickrage/sickbeard/subtitles.py", line 103, in subtitlesLanguages
    mkv = MKV(f)
  File "/opt/sickrage/lib/enzyme/mkv.py", line 40, in __init__
    segments = ebml.parse(stream, specs, ignore_element_names=['EBML'], max_level=0)
  File "/opt/sickrage/lib/enzyme/parsers/ebml/core.py", line 177, in parse
    stream.seek(element.size, 1)
IOError: [Errno 22] Invalid argument

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by RDgiuliom** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.2.0-bananian-armv7l-with-debian-8.2**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@638270689679f3958d1b593c329e7c6e5cb7448e
No Log available with ERRORS: 
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/tv.py", line 1479, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/opt/sickrage/sickbeard/tv.py", line 1453, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/opt/sickrage/sickbeard/subtitles.py", line 103, in subtitlesLanguages
    mkv = MKV(f)
  File "/opt/sickrage/lib/enzyme/mkv.py", line 40, in __init__
    segments = ebml.parse(stream, specs, ignore_element_names=['EBML'], max_level=0)
  File "/opt/sickrage/lib/enzyme/parsers/ebml/core.py", line 177, in parse
    stream.seek(element.size, 1)
IOError: [Errno 22] Invalid argument

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by RDgiuliom** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.2.0-bananian-armv7l-with-debian-8.2**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@638270689679f3958d1b593c329e7c6e5cb7448e
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-REFRESH :: 264991: Could not refresh subtitles
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by RDgiuliom** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.2.0-bananian-armv7l-with-debian-8.2**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@638270689679f3958d1b593c329e7c6e5cb7448e
Link to Log: https://gist.github.com/5de3bd399af7572519d4
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/tv.py", line 1479, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/opt/sickrage/sickbeard/tv.py", line 1453, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/opt/sickrage/sickbeard/subtitles.py", line 103, in subtitlesLanguages
    mkv = MKV(f)
  File "/opt/sickrage/lib/enzyme/mkv.py", line 40, in __init__
    segments = ebml.parse(stream, specs, ignore_element_names=['EBML'], max_level=0)
  File "/opt/sickrage/lib/enzyme/parsers/ebml/core.py", line 177, in parse
    stream.seek(element.size, 1)
IOError: [Errno 22] Invalid argument

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Foucl** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  4 2015, 01:18:03) [GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@7b6040b3a706331bac4bf7ec5dc8b8d2845bf0b4
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-REFRESH :: 264991: Could not refresh subtitles
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Foucl** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  4 2015, 01:18:03) [GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@5d4bec2c6022a9e2d5ec934791cf80a0b2553a6f
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-REFRESH :: 264991: Could not refresh subtitles
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
