### ISSUE TITLE
[APP SUBMITTED]: '_usr_local_sickrage_var_SickRage_gui_slick_interfaces_default_home_mako'

### ISSUE THREAD

**Issue by sverleysen** [SiCKRAGETV/sickrage-issues#2555]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 23:30:53) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@f78ff1a26ef7c8605720a72aa2c646084e692381
Link to Log: https://gist.github.com/f740ca95e993d6e1f116
### ERROR
```
Thread-72 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 260, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 741, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 109, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 380, in _compile_from_file
    del sys.modules[self.module_id]
KeyError: '_usr_local_sickrage_var_SickRage_gui_slick_interfaces_default_home_mako'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
Remove/rename the cache folder and cache.db in the SickRage folder. 
Also clear your browser cache to be sure.

**Comment by miigotu** [comment]
If you remove the cache/images you will need to force a full update also.

**Comment by sverleysen** [comment]
Done, will let you know if the error returns.
Thanks!

2015-08-25 16:44 GMT+02:00 miigotu <notifications@github.com>:
