### ISSUE TITLE
Too many redirects

### ISSUE THREAD

**Issue by danwelcome** [SiCKRAGETV/sickrage-issues#2561]
I am getting an error from Chrome when I try to log into Sickrage, "This webpage has a redirect loop".  I have done the following:

- Reset my database according to this post: https://github.com/SiCKRAGETV/sickrage-issues/issues/549#issuecomment-72844385
- Delete the cache.db, sickbeard.db, and failure.db and restart sickrage, same issue
- Pulled down the latest code from git according to this post: https://github.com/SiCKRAGETV/sickrage-issues

Here is an error message I keep seeing in the logs:
```
2015-08-25 21:43:39 ERROR    Thread-44 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 260, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 739, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 109, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 381, in _compile_from_file
    if module._magic_number != codegen.MAGIC_NUMBER:
AttributeError: 'module' object has no attribute '_magic_number'
Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 260, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 739, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 109, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 381, in _compile_from_file
    if module._magic_number != codegen.MAGIC_NUMBER:
AttributeError: 'module' object has no attribute '_magic_number'
2015-08-25 21:43:39 DEBUG    TORNADO :: Failed doing webui request "index": Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 245, in get
    results = yield self.async_call(method)
  File "C:\SickRage\tornado\gen.py", line 807, in run
    value = future.result()
  File "C:\SickRage\lib\concurrent\futures\_base.py", line 400, in result
    return self.__get_result()
  File "C:\SickRage\lib\concurrent\futures\_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "C:\SickRage\lib\concurrent\futures\_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "C:\SickRage\lib\concurrent\futures\thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 260, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 739, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 109, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 381, in _compile_from_file
    if module._magic_number != codegen.MAGIC_NUMBER:
AttributeError: 'module' object has no attribute '_magic_number'
```

**Comment by WebSpider** [comment]
Please also delete cache/mako and restart SR

**Comment by danwelcome** [comment]
I've tried deleting the cache.db (along with sickbeard and failure) and that didn't work.  I don't see a mako.db file anywhere, but i do see a mako directory inside of the cache directory... but it contains python files, so I take it I shouldn't delete that.

**Comment by MGaetan89** [comment]
@danwelcome  Not the `cache.db` file, but the `cache/mako/` folder.

**Comment by danwelcome** [comment]
That did the trick, thanks!
