### ISSUE TITLE
Adding custom torrent provider issue

### ISSUE THREAD

**Issue by Germetik** [SiCKRAGETV/sickrage-issues#2577]
I am running SickRage on QNAP TS-212 ARM device, and i can't add custom provider.
I downloaded and installed qpkg from here:
http://apps.qnap.community/11-community/5-sickrage
My setup:
Provider name: LostFilm
RSS URL: http://www.lostfilm.tv/rssdd.xml
Cookies: uid=xxx;pass=xxx;usess=xxx
Search element: title

Error when trying to load RSS: must be string or buffer, not None

Log output:
```
2015-08-27 17:37:21 WARNING  Thread-17 :: Traceback (most recent call last):
2015-08-27 17:37:21 WARNING  Thread-17 :: Unknown exception in getURL https://www.lostfilm.tv/download.php?id=15023&Devious.Maids.S03E13.720p.WEB.rus.LostFilm.TV.mp4.torrent Error: '_socketobject' object has no attribute 'set_tlsext_host_name'
AA
AAAttributeError: '_socketobject' object has no attribute 'set_tlsext_host_name'
AA    cnx.set_tlsext_host_name(server_hostname)
AA  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 296, in ssl_wrap_socket
AA    ssl_version=resolved_ssl_version)
AA  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connection.py", line 238, in connect
AA    conn.connect()
AA  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 762, in _validate_conn
AA    self._validate_conn(conn)
AA  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
AA    body=body, headers=headers)
AA  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
AA    timeout=timeout
AA  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/adapters.py", line 370, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/cachecontrol/adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 476, in get
AA    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1369, in getURL
```
How can i manage my problem?

**Comment by neoatomic** [comment]
@Germetik Likely an SSL error. 
You are using an old/outdated package on your QNAP. You need to use http://apps.qnap.community/11-community/17-qsickrage

I'm sure that will fix your issue. :)

**Comment by Germetik** [comment]
neoatomic, the problem is that qsickrage package is for x86 architecture. My nas have ARM architecture. :)

**Comment by neoatomic** [comment]
Sadly noting can be done from our side then... 

You need to get the correct Python modules installed into that package so SSL/HTTPS is supported. (If not you will get those errors when an HTTPS site is used.)
Maybe its possible to replace it with a third party Python package. (qpyton2.?)
