### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'close'

### ISSUE THREAD

**Issue by pr0xyfl00d3r** [SiCKRAGETV/sickrage-issues#258]
### INFO
Python Version: **2.7.8 (default, Dec 15 2014, 02:33:48) 
[GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.3-RELEASE-p6-amd64-64bit-ELF**
Branch: **master**
Commit: SiCKRAGETV/SickRage@49ea8f5ac7841f6654509d48d72506923bc47c2a
Pastebin Log URL: http://pastebin.com/Jd315uHL
### ERROR
```
Thread-39 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 374, in showPoster
    return self.redirect(static_image_path)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 191, in redirect
    super(BaseHandler, self).redirect(url, permanent, status)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/tornado/web.py", line 630, in redirect
    self.finish()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/tornado/web.py", line 893, in finish
    self.request.finish()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/tornado/httputil.py", line 392, in finish
    self.connection.finish()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/tornado/http1connection.py", line 451, in finish
    self._pending_write.add_done_callback(self._finish_request)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/tornado/concurrent.py", line 135, in add_done_callback
    fn(self)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/tornado/http1connection.py", line 480, in _finish_request
    self.close()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/tornado/http1connection.py", line 293, in close
    self.stream.close()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/tornado/iostream.py", line 386, in close
    self.close_fd()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/tornado/iostream.py", line 937, in close_fd
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@pr0xyfl00d3r are you still having this issue? please submit full logs. Report back otherwise will close it.

**Comment by fernandog** [comment]
@pr0xyfl00d3r  please update SR and report back please. Fix was merged
