### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'node_idx'

### ISSUE THREAD

**Issue by didyouexpectthat** [SiCKRAGETV/sickrage-issues#2590]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-2.6.32-40-pve-x86_64-with-debian-8.1**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@3fb81bd65d7710e59d6c89945a3be39d2dbfc386
No Log available with ERRORS: 
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "/usr/share/sickrage/sickbeard/tv.py", line 1469, in downloadSubtitles
    foundSubs = subliminal.download_best_subtitles([video], languages=languages, providers=providers, single=not sickbeard.SUBTITLES_MULTI, hearing_impaired=False)
  File "/usr/share/sickrage/lib/subliminal/api.py", line 88, in download_best_subtitles
    for subtitle, score in sorted([(s, s.compute_score(video)) for s in video_subtitles],
  File "/usr/share/sickrage/lib/subliminal/subtitle.py", line 131, in compute_score
    initial_matches = self.compute_matches(video)
  File "/usr/share/sickrage/lib/subliminal/providers/opensubtitles.py", line 61, in compute_matches
    matches |= compute_guess_matches(video, guessit.guess_episode_info(self.movie_release_name + '.mkv'))
  File "/usr/share/sickrage/lib/guessit/__init__.py", line 358, in guess_episode_info
    return guess_file_info(filename, info=info, options=options, type='episode', **kwargs)
  File "/usr/share/sickrage/lib/guessit/__init__.py", line 290, in guess_file_info
    result.append(_guess_filename(filename, options, **kwargs))
  File "/usr/share/sickrage/lib/guessit/__init__.py", line 110, in _guess_filename
    mtree = _build_filename_mtree(filename, options=options, **kwargs)
  File "/usr/share/sickrage/lib/guessit/__init__.py", line 117, in _build_filename_mtree
    mtree = IterativeMatcher(filename, options=options, **kwargs)
  File "/usr/share/sickrage/lib/guessit/matcher.py", line 120, in __init__
    self._process(transformer, False)
  File "/usr/share/sickrage/lib/guessit/matcher.py", line 138, in _process
    transformer.process(self.match_tree, self.options)
  File "/usr/share/sickrage/lib/guessit/transfo/guess_bonus_features.py", line 68, in process
    if same_group(series, season[0]):
  File "/usr/share/sickrage/lib/guessit/transfo/guess_bonus_features.py", line 46, in same_group
    return g1.node_idx[:2] == g2.node_idx[:2]
AttributeError: 'NoneType' object has no attribute 'node_idx'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by didyouexpectthat** [comment]
2015-08-28 07:28:32 ERROR    FINDSUBTITLES :: Traceback (most recent call last):
2015-08-28 07:28:32 INFO     FINDSUBTITLES :: Error occurred when downloading subtitles for: /tv/Action/s00e01.avi
