### ISSUE TITLE
Catch error in provider and show warning instead of error and traceback

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#2610]
```
AAConnectionError: ('Connection aborted.', error(101, 'A rede est\xc3\xa1 fora de alcance'))
AA    raise ConnectionError(err, request=request)

AA  File "/home/osmc/SickRage/lib/requests/adapters.py", line 415, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/home/osmc/SickRage/lib/cachecontrol/adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/home/osmc/SickRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/home/osmc/SickRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/home/osmc/SickRage/lib/requests/sessions.py", line 476, in get
AA    response = self.session.get(self.urls['token'], timeout=30, headers=self.headers)
AA  File "/home/osmc/SickRage/sickbeard/providers/rarbg.py", line 110, in _doLogin
AATraceback (most recent call last):
2015-08-31 00:34:00 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Unable to connect to Rarbg provider: error ('Connection aborted.', error(101, 'A rede est\xc3\xa1 fora de alcance'))
```

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
