### ISSUE TITLE
Another traceback to handle

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#2617]
I have no clue where to handle this

```
AAerror: [Errno 101] A rede está fora de alcance
AA  File "", line 3, in raise_exc_info
AA    raise_exc_info(self._exc_info)
AA  File "/home/osmc/SickRage/tornado/concurrent.py", line 209, in result
AA    value = future.result()
AA  File "/home/osmc/SickRage/tornado/gen.py", line 807, in run
AA    quiet_exceptions=iostream.StreamClosedError)
AA  File "/home/osmc/SickRage/tornado/http1connection.py", line 166, in _read_message
AA    yielded = self.gen.throw(*sys.exc_info())
AA  File "/home/osmc/SickRage/tornado/gen.py", line 810, in run
AA    raise_exc_info(self._exc_info)
AA  File "/home/osmc/SickRage/tornado/concurrent.py", line 209, in result
AA    value = future.result()
AA  File "/home/osmc/SickRage/tornado/gen.py", line 807, in run
AA    ret = yield conn.read_response(request_delegate)
AA  File "/home/osmc/SickRage/tornado/http1connection.py", line 691, in _server_request_loop
AATraceback (most recent call last):
AA2015-08-31 13:42:13 ERROR    Uncaught exception
AAerror: [Errno 101] A rede está fora de alcance
AA    chunk = self.socket.recv(self.read_chunk_size)
AA  File "/home/osmc/SickRage/tornado/iostream.py", line 976, in read_from_fd
AA    chunk = self.read_from_fd()
AA  File "/home/osmc/SickRage/tornado/iostream.py", line 712, in _read_to_buffer
AA    if self._read_to_buffer() == 0:
AA  File "/home/osmc/SickRage/tornado/iostream.py", line 600, in _read_to_buffer_loop
AA    pos = self._read_to_buffer_loop()
AA  File "/home/osmc/SickRage/tornado/iostream.py", line 630, in _handle_read
AATraceback (most recent call last):
```

**Comment by OmgImAlexis** [comment]
We have switch to using feathub for feature requests. If this feature is still important to anyone, please
check that it has not been added and add it [HERE](http://feathub.com/SiCKRAGETV/SickRage)
Make sure to vote!
