### ISSUE TITLE
[APP SUBMITTED]: 'charmap' codec can't decode byte 0x9d in position 153: character maps to <undefined>

### ISSUE THREAD

**Issue by anzerman** [SiCKRAGETV/sickrage-issues#2633]
### INFO
Python Version: **2.7.3 (default, Apr 10 2012, 23:31:26) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@4db41da61c3e4639a19613a3e4f0dfeef9831fc0
Link to Log: https://gist.github.com/98769b06d78bd8fed5c6
### ERROR
```
Thread-34 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\APPS\SickRage\sickbeard\webserve.py", line 260, in async_call
    result = function(**kwargs)
  File "C:\APPS\SickRage\sickbeard\webserve.py", line 2268, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "C:\APPS\SickRage\sickbeard\processTV.py", line 204, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "C:\APPS\SickRage\sickbeard\processTV.py", line 491, in process_media
    result.result = processor.process()
  File "C:\APPS\SickRage\sickbeard\postProcessor.py", line 1086, in process
    notifiers.notify_download(ep_obj._format_pattern('%SN - %Sx%0E - %EN - %QN'))
  File "C:\APPS\SickRage\sickbeard\notifiers\__init__.py", line 98, in notify_download
    n.notify_download(ep_name)
  File "C:\APPS\SickRage\sickbeard\notifiers\kodi.py", line 529, in notify_download
    self._notify_kodi(ep_name, common.notifyStrings[common.NOTIFY_DOWNLOAD])
  File "C:\APPS\SickRage\sickbeard\notifiers\kodi.py", line 145, in _notify_kodi
    notifyResult = self._send_to_kodi_json(command, curHost, username, password)
  File "C:\APPS\SickRage\sickbeard\notifiers\kodi.py", line 371, in _send_to_kodi_json
    logger.log(u"KODI JSON command: " + command, logger.DEBUG)
  File "C:\Python27\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 153: character maps to <undefined>

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by flightlevel** [comment]
Have you tried https://github.com/SiCKRAGETV/sickrage-issues/issues/1425#issuecomment-133144366 ?

**Comment by WebSpider** [comment]
#1424, #1779 and #1954
