### ISSUE TITLE
Error adding shows from TVRage

### ISSUE THREAD

**Issue by lunarok** [SiCKRAGETV/sickrage-issues#265]
Hi,

If I try adding shows with Tvrage source, it's failing with a popup saying the show cannot be added (showing is Tvrage ID also) and that maybe I need to delete the nfo file and try again manualy)

There is no nfo file, so must be failing before this part.

I have active the debug mode and here are 2 logs with 2 differents show. Whatever a little different, the 2 complain about a 'NoneType' object.
```
2014-12-22 14:21:20 Thread-31 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 374, in showPoster
    return self.redirect(static_image_path)
  File "/opt/sickbeard/sickbeard/webserve.py", line 191, in redirect
    super(BaseHandler, self).redirect(url, permanent, status)
  File "/opt/sickbeard/tornado/web.py", line 630, in redirect
    self.finish()
  File "/opt/sickbeard/tornado/web.py", line 893, in finish
    self.request.finish()
  File "/opt/sickbeard/tornado/httputil.py", line 392, in finish
    self.connection.finish()
  File "/opt/sickbeard/tornado/http1connection.py", line 451, in finish
    self._pending_write.add_done_callback(self._finish_request)
  File "/opt/sickbeard/tornado/concurrent.py", line 135, in add_done_callback
    fn(self)
  File "/opt/sickbeard/tornado/http1connection.py", line 480, in _finish_request
    self.close()
  File "/opt/sickbeard/tornado/http1connection.py", line 293, in close
    self.stream.close()
  File "/opt/sickbeard/tornado/iostream.py", line 386, in close
    self.close_fd()
  File "/opt/sickbeard/tornado/iostream.py", line 937, in close_fd
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

2014-12-22 14:21:20 Thread-64 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 374, in showPoster
    return self.redirect(static_image_path)
  File "/opt/sickbeard/sickbeard/webserve.py", line 191, in redirect
    super(BaseHandler, self).redirect(url, permanent, status)
  File "/opt/sickbeard/tornado/web.py", line 630, in redirect
    self.finish()
  File "/opt/sickbeard/tornado/web.py", line 892, in finish
    self.flush(include_footers=True)
  File "/opt/sickbeard/tornado/web.py", line 846, in flush
    start_line, self._headers, chunk, callback=callback)
  File "/opt/sickbeard/tornado/http1connection.py", line 385, in write_headers
    self._pending_write = self.stream.write(data)
  File "/opt/sickbeard/tornado/iostream.py", line 348, in write
    self._handle_write()
  File "/opt/sickbeard/tornado/iostream.py", line 800, in _handle_write
    _merge_prefix(self._write_buffer, num_bytes)
  File "/opt/sickbeard/tornado/iostream.py", line 1382, in _merge_prefix
    if len(deque) == 1 and len(deque[0]) <= size:
TypeError: object of type 'NoneType' has no len()

2014-12-22 14:21:19 SHOWQUEUE-ADD :: Unable to find show ID:37537 on Indexer: TVRage
2014-12-22 14:21:19 Thread-46 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 374, in showPoster
    return self.redirect(static_image_path)
  File "/opt/sickbeard/sickbeard/webserve.py", line 191, in redirect
    super(BaseHandler, self).redirect(url, permanent, status)
  File "/opt/sickbeard/tornado/web.py", line 630, in redirect
    self.finish()
  File "/opt/sickbeard/tornado/web.py", line 892, in finish
    self.flush(include_footers=True)
  File "/opt/sickbeard/tornado/web.py", line 846, in flush
    start_line, self._headers, chunk, callback=callback)
  File "/opt/sickbeard/tornado/http1connection.py", line 385, in write_headers
    self._pending_write = self.stream.write(data)
  File "/opt/sickbeard/tornado/iostream.py", line 348, in write
    self._handle_write()
  File "/opt/sickbeard/tornado/iostream.py", line 800, in _handle_write
    _merge_prefix(self._write_buffer, num_bytes)
  File "/opt/sickbeard/tornado/iostream.py", line 1382, in _merge_prefix
    if len(deque) == 1 and len(deque[0]) <= size:
TypeError: object of type 'NoneType' has no len()

2014-12-22 14:21:19 Thread-48 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 374, in showPoster
    return self.redirect(static_image_path)
  File "/opt/sickbeard/sickbeard/webserve.py", line 191, in redirect
    super(BaseHandler, self).redirect(url, permanent, status)
  File "/opt/sickbeard/tornado/web.py", line 630, in redirect
    self.finish()
  File "/opt/sickbeard/tornado/web.py", line 892, in finish
    self.flush(include_footers=True)
  File "/opt/sickbeard/tornado/web.py", line 846, in flush
    start_line, self._headers, chunk, callback=callback)
  File "/opt/sickbeard/tornado/http1connection.py", line 385, in write_headers
    self._pending_write = self.stream.write(data)
  File "/opt/sickbeard/tornado/iostream.py", line 348, in write
    self._handle_write()
  File "/opt/sickbeard/tornado/iostream.py", line 800, in _handle_write
    _merge_prefix(self._write_buffer, num_bytes)
  File "/opt/sickbeard/tornado/iostream.py", line 1382, in _merge_prefix
    if len(deque) == 1 and len(deque[0]) <= size:
TypeError: object of type 'NoneType' has no len()

2014-12-22 14:17:06 Thread-39 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 374, in showPoster
    return self.redirect(static_image_path)
  File "/opt/sickbeard/sickbeard/webserve.py", line 191, in redirect
    super(BaseHandler, self).redirect(url, permanent, status)
  File "/opt/sickbeard/tornado/web.py", line 630, in redirect
    self.finish()
  File "/opt/sickbeard/tornado/web.py", line 892, in finish
    self.flush(include_footers=True)
  File "/opt/sickbeard/tornado/web.py", line 846, in flush
    start_line, self._headers, chunk, callback=callback)
  File "/opt/sickbeard/tornado/http1connection.py", line 385, in write_headers
    self._pending_write = self.stream.write(data)
  File "/opt/sickbeard/tornado/iostream.py", line 348, in write
    self._handle_write()
  File "/opt/sickbeard/tornado/iostream.py", line 800, in _handle_write
    _merge_prefix(self._write_buffer, num_bytes)
  File "/opt/sickbeard/tornado/iostream.py", line 1382, in _merge_prefix
    if len(deque) == 1 and len(deque[0]) <= size:
TypeError: object of type 'NoneType' has no len()

2014-12-22 14:17:06 Thread-56 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 374, in showPoster
    return self.redirect(static_image_path)
  File "/opt/sickbeard/sickbeard/webserve.py", line 191, in redirect
    super(BaseHandler, self).redirect(url, permanent, status)
  File "/opt/sickbeard/tornado/web.py", line 630, in redirect
    self.finish()
  File "/opt/sickbeard/tornado/web.py", line 892, in finish
    self.flush(include_footers=True)
  File "/opt/sickbeard/tornado/web.py", line 846, in flush
    start_line, self._headers, chunk, callback=callback)
  File "/opt/sickbeard/tornado/http1connection.py", line 385, in write_headers
    self._pending_write = self.stream.write(data)
  File "/opt/sickbeard/tornado/iostream.py", line 348, in write
    self._handle_write()
  File "/opt/sickbeard/tornado/iostream.py", line 800, in _handle_write
    _merge_prefix(self._write_buffer, num_bytes)
  File "/opt/sickbeard/tornado/iostream.py", line 1382, in _merge_prefix
    if len(deque) == 1 and len(deque[0]) <= size:
TypeError: object of type 'NoneType' has no len()

2014-12-22 14:17:06 Thread-20 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 374, in showPoster
    return self.redirect(static_image_path)
  File "/opt/sickbeard/sickbeard/webserve.py", line 191, in redirect
    super(BaseHandler, self).redirect(url, permanent, status)
  File "/opt/sickbeard/tornado/web.py", line 630, in redirect
    self.finish()
  File "/opt/sickbeard/tornado/web.py", line 892, in finish
    self.flush(include_footers=True)
  File "/opt/sickbeard/tornado/web.py", line 846, in flush
    start_line, self._headers, chunk, callback=callback)
  File "/opt/sickbeard/tornado/http1connection.py", line 385, in write_headers
    self._pending_write = self.stream.write(data)
  File "/opt/sickbeard/tornado/iostream.py", line 348, in write
    self._handle_write()
  File "/opt/sickbeard/tornado/iostream.py", line 800, in _handle_write
    _merge_prefix(self._write_buffer, num_bytes)
  File "/opt/sickbeard/tornado/iostream.py", line 1382, in _merge_prefix
    if len(deque) == 1 and len(deque[0]) <= size:
TypeError: object of type 'NoneType' has no len()

2014-12-22 14:17:04 SHOWQUEUE-ADD :: Unable to find show ID:39033 on Indexer: TVRage
```
If I add show with tvdb, no problem.
Maybe it can helps, the show I have errors are 'in developpment', for exemple cannot find them on tvdb and no season informations. But we can find them by a search :
Preacher, Westworld, Supergirl for exemple

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/173
