### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded - NOT for subtitles. They are disabled

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#2653]
SR Version:	BRANCH: (develop) / COMMIT: (8613e664e9937ea55337f3d4963d61933a87e68b) 

@miigotu 
More than 1000 lines of this
Also happens for TD and NZBGeek

```
2015-09-04 07:27:44 ERROR    SEARCHQUEUE-BACKLOG-258959 :: [HDTorrents] :: Error while searching HDTorrents, skipping: maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/search.py", line 463, in searchProviders
    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
  File "/home/osmc/SickRage/sickbeard/providers/generic.py", line 351, in findSearchResults
    itemList += self._doSearch(curString, search_mode, len(episodes), epObj=epObj)
  File "/home/osmc/SickRage/sickbeard/providers/hdtorrents.py", line 153, in _doSearch
    if not self._doLogin():
  File "/home/osmc/SickRage/sickbeard/providers/hdtorrents.py", line 93, in _doLogin
    response = self.getURL(self.urls['login'],  post_data=login_params, timeout=30)
  File "/home/osmc/SickRage/sickbeard/providers/generic.py", line 139, in getURL
    if not self._doLogin():
  File "/home/osmc/SickRage/sickbeard/providers/hdtorrents.py", line 93, in _doLogin
    response = self.getURL(self.urls['login'],  post_data=login_params, timeout=30)
  File "/home/osmc/SickRage/sickbeard/providers/generic.py", line 139, in getURL
    if not self._doLogin():
  File "/home/osmc/SickRage/sickbeard/providers/hdtorrents.py", line 93, in _doLogin
    response = self.getURL(self.urls['login'],  post_data=login_params, timeout=30)
  File "/home/osmc/SickRage/sickbeard/providers/generic.py", line 139, in getURL
    if not self._doLogin():
  File "/home/osmc/SickRage/sickbeard/providers/hdtorrents.py", line 93, in _doLogin
    response = self.getURL(self.urls['login'],  post_data=login_params, timeout=30)
  File "/home/osmc/SickRage/sickbeard/providers/generic.py", line 139, in getURL
    if not self._doLogin():
  File "/home/osmc/SickRage/sickbeard/providers/hdtorrents.py", line 93, in _doLogin
    response = self.getURL(self.urls['login'],  post_data=login_params, timeout=30)
  File "/home/osmc/SickRage/sickbeard/providers/generic.py", line 139, in getURL
    if not self._doLogin():
  File "/home/osmc/SickRage/sickbeard/providers/hdtorrents.py", line 85, in _doLogin
    if any(requests.utils.dict_from_cookiejar(self.session.cookies).values()):
  File "/home/osmc/SickRage/lib/requests/utils.py", line 270, in dict_from_cookiejar
    for cookie in cj:
RuntimeError: maximum recursion depth exceeded
```

**Comment by fernandog** [comment]
maybe related to this ?

https://github.com/SiCKRAGETV/SickRage/pull/2392/files

**Comment by fernandog** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.1.5-1-osmc-armv7l-with-debian-8.1**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@2982ade92e8ce0b58657103cedb3cb9b2ff3924e
Link to Log: https://gist.github.com/a919dd3212b439eb5a01
### ERROR
```
SEARCHQUEUE-BACKLOG-277462 :: [TorrentDay] :: Error while searching TorrentDay, skipping: maximum recursion depth exceeded
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@miigotu Am I the only having this issue?

**Comment by duramato** [comment]
@fernandog I'm also having, I ve tryed submitting them but don't know which issue they are commented on

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/2339

**Comment by duramato** [comment]
But no traceback only this 
```
2015-09-07 21:15:08 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [AlphaRatio] :: Error while searching AlphaRatio, skipping: RuntimeError('maximum recursion depth exceeded',)
2015-09-07 21:15:08 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [TorrentBytes] :: Error while searching TorrentBytes, skipping: RuntimeError('maximum recursion depth exceeded',)
2015-09-07 21:15:06 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [MoreThanTV] :: Error while searching MoreThanTV, skipping: RuntimeError('maximum recursion depth exceeded while calling a Python object',)
2015-09-07 21:15:05 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [TNTVillage] :: Error while searching TNTVillage, skipping: RuntimeError('maximum recursion depth exceeded',)
2015-09-07 21:15:05 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: Error while searching TorrentLeech, skipping: RuntimeError('maximum recursion depth exceeded',)
```

**Comment by fernandog** [comment]
waiting migotu see this. already told him at IRC.

**Comment by fernandog** [comment]
@duramato can you please contact him? He is not replying IRC or this issue

**Comment by miigotu** [comment]
You do realize I wake up to 30+ notifications a day? I only respond when I have a potential solution.

**Comment by fernandog** [comment]
Ow! Sorry!

**Comment by WebSpider** [comment]
@fernandog acting on a hunch here ... can you clear the session cache?

**Comment by fernandog** [comment]
Cleared my entire cache (thats why I tried that PR about gitignore)

**Comment by miigotu** [comment]
And with a cleared cache, does it then still give the error?

**Comment by fernandog** [comment]
Yes. Strange that only duramato and me have this. Backlog not working because of this

**Comment by miigotu** [comment]
Backlog works here. very strange. Seems to only be with sites needing login.

**Comment by ncksol** [comment]
I am having the same issue on backlog or manual search. Only just started to happen after I've upgraded to the latest version today.

**Comment by didyouexpectthat** [comment]
I do have this issue as well in develop.

**Comment by pattop** [comment]
I've got this issue too with a slightly different backtrace to the one above running commit 9df4588e371248751bd60c4c02a90ea979199f43.

```
ARuntimeError: maximum recursion depth exceeded
AA    wr = ref(item)
AA  File "/usr/lib/python2.7/_weakrefset.py", line 72, in __contains__
AA    if subclass is not None and subclass in cls._abc_cache:
AA  File "/usr/lib/python2.7/abc.py", line 132, in __instancecheck__
AA    if isinstance(other, Mapping):
AA  File "/usr/lib/python2.7/_abcoll.py", line 561, in update
AA    self.update(data, **kwargs)
AA  File "/opt/sickrage/lib/requests/structures.py", line 46, in __init__
AA    self.headers = CaseInsensitiveDict()
AA  File "/opt/sickrage/lib/requests/models.py", line 551, in __init__
AA    response = Response()
AA  File "/opt/sickrage/lib/requests/adapters.py", line 205, in build_response
AA    return self.build_response(request, resp)
AA  File "/opt/sickrage/lib/requests/adapters.py", line 437, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/opt/sickrage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/opt/sickrage/lib/requests/sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/opt/sickrage/lib/requests/sessions.py", line 476, in get
AA    self.session.get(self.urls['login'], timeout=30)
AA  File "/opt/sickrage/sickbeard/providers/iptorrents.py", line 93, in _doLogin
AA    if not self._doLogin():
AA  File "/opt/sickrage/sickbeard/providers/generic.py", line 139, in getURL
AA    response = self.getURL(self.urls['login'],  post_data=login_params, timeout=30)
AA  File "/opt/sickrage/sickbeard/providers/iptorrents.py", line 94, in _doLogin
AA    if not self._doLogin():
AA  File "/opt/sickrage/sickbeard/providers/generic.py", line 139, in getURL
AA    response = self.getURL(self.urls['login'],  post_data=login_params, timeout=30)
AA  File "/opt/sickrage/sickbeard/providers/iptorrents.py", line 94, in _doLogin
AA    if not self._doLogin():
AA  File "/opt/sickrage/sickbeard/providers/generic.py", line 139, in getURL
AA    response = self.getURL(self.urls['login'],  post_data=login_params, timeout=30)
AA  File "/opt/sickrage/sickbeard/providers/iptorrents.py", line 94, in _doLogin
AA    if not self._doLogin():
AA  File "/opt/sickrage/sickbeard/providers/generic.py", line 139, in getURL
AA    response = self.getURL(self.urls['login'],  post_data=login_params, timeout=30)
AA  File "/opt/sickrage/sickbeard/providers/iptorrents.py", line 94, in _doLogin
AA    if not self._doLogin():
AA  File "/opt/sickrage/sickbeard/providers/generic.py", line 139, in getURL
AA    response = self.getURL(self.urls['login'],  post_data=login_params, timeout=30)
AA  File "/opt/sickrage/sickbeard/providers/iptorrents.py", line 94, in _doLogin
AA    if not self._doLogin():
AA  File "/opt/sickrage/sickbeard/providers/generic.py", line 139, in getURL
AA    response = self.getURL(self.urls['login'],  post_data=login_params, timeout=30)
AA  File "/opt/sickrage/sickbeard/providers/iptorrents.py", line 94, in _doLogin
AA    if not self._doLogin():
```

**Comment by fernandog** [comment]
Fixed in develop by @miigotu 
Thanks

@duramato please confirm

**Comment by speedyflipper** [comment]
Im still getting this error

**Comment by fernandog** [comment]
Develop branch?

**Comment by duramato** [comment]
@fernandog & @miigotu  well it fixed that but now im getting this ```
2015-09-09 20:10:55 DEBUG    SEARCHQUEUE-MANUAL-75340 :: [TorrentBytes] :: Error while searching TorrentBytes, skipping: AttributeError("'str' object has no attribute 'text'",)
2015-09-09 20:10:55 DEBUG    SEARCHQUEUE-MANUAL-75340 :: [MoreThanTV] :: Error while searching MoreThanTV, skipping: AttributeError("'str' object has no attribute 'text'",)```

**Comment by miigotu** [comment]
@duramato Fixed in develop.

**Comment by duramato** [comment]
@miigotu thanks it works now
On a side not TorrentLeech login isnt working yet

**Comment by speedyflipper** [comment]
TorrentDay isnt either

**Comment by fernandog** [comment]
TD is working to me (except the search string log. will check it)

```
2015-09-09 17:44:09 DEBUG    SEARCHQUEUE-MANUAL-272127 :: [TorrentDay] :: Attempting to add item to cache: *****
2015-09-09 17:44:09 DEBUG    SEARCHQUEUE-MANUAL-272127 :: [TorrentDay] :: Unable to parse the filename *****
2015-09-09 17:44:09 DEBUG    SEARCHQUEUE-MANUAL-272127 :: [TorrentDay] :: Attempting to add item to cache: ******
2015-09-09 17:44:09 DEBUG    SEARCHQUEUE-MANUAL-272127 :: [TorrentDay] :: Unable to parse the filename ***** into a valid show
2015-09-09 17:44:09 DEBUG    SEARCHQUEUE-MANUAL-272127 :: [TorrentDay] :: Attempting to add item to cache: *****
2015-09-09 17:44:08 DEBUG    SEARCHQUEUE-MANUAL-272127 :: [TorrentDay] :: Search string:
```

**Comment by aeror1** [comment]
Happening to me now with iptorrents. Started after the last update that people had issues with. 

Question, if it fixed in develop, how long does it take to make it to the master?  I'm new to all of this stuff and trying to learn all the different branches and how they work. Thanks!!

**Comment by miigotu** [comment]
@aeror1 that fix is already in master.

**Comment by aeror1** [comment]
Hmm, maybe I'm on the wrong issue?   I'm getting this:

        2015-09-11 10:56:13 SEARCHQUEUE-BACKLOG-281181 :: [IPTorrents] :: Error while searching IPTorrents, skipping: maximum recursion depth exceeded

	BRANCH: (master) / COMMIT: (ecaed9c745dfc645c4e26a268d1ddeca43b006ca) 

Python Version:	2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]

**Comment by miigotu** [comment]
@aeror1 you aren't up to date. there have been like 3 releases to master since you last updated. like 20 commits.

**Comment by aeror1** [comment]
@miigotu thanks.  when i force an update via the GUI, it says I'm up to date.  

to force an update, i do this?

git remote add upstream https://github.com/SiCKRAGETV/SickRage.git
git fetch upstream
git checkout master
git branch -u upstream/master
git reset --hard upstream/master
git pull

**Comment by fernandog** [comment]
@aeror1 please stop SR, delele all folders - except 'images' - inside /SickRage/cache/

report back as this issue is fixed.

**Comment by aeror1** [comment]
@fernandog which issue will this fix? the recursion thats causing no snatching?  the update issue im having that it wont update via the gui?  i did this the other day in order to try to get the banners back but it didnt work.  i see now that i am a few releases behind now that hopefully fixed all my issues.

being new to this, and seeing that the gui wont update, im researching on how to update it to the latest master.  

btw, i deleted the folders like you suggested and no change in posters, snatching or updating.

thanks!

**Comment by didyouexpectthat** [comment]
@aeror1  The latest master is 37914618686ee70479da0fa4b2cca851fa49c5e2
ecaed9c745dfc645c4e26a268d1ddeca43b006ca is not the latest commit. The GUI doesn't appear to just pull latest commits, it seems to pull milestone releases. 
I was also having this error but after pulling the latest from git, I no longer see this issue.

**Comment by miigotu** [comment]
the last one IS a tagged release.

**Comment by miigotu** [comment]
@aeror1 just doing this should work if your origin points to our git:
```
git remote show origin
git fetch origin
git rest --hard origin/master
```

**Comment by didyouexpectthat** [comment]
miigotu That's interesting. I seem to be able to git pull updates when check for updates from the UI returns nothing new.  I'll try the UI again when I notice a new release.
