### ISSUE TITLE
Start error 

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2672]
After updating to the latest dev version
```
sudo service sickrage start
Starting SickBeard
Traceback (most recent call last):
  File "SickBeard.py", line 56, in <module>
    from sickbeard.webserveInit import SRWebServer
  File "/home/supergonkas/SickRage/sickbeard/webserveInit.py", line 5, in <module>
    from sickbeard.webserve import LoginHandler, LogoutHandler, KeyHandler, CalendarHandler
  File "/home/supergonkas/SickRage/sickbeard/webserve.py", line 58, in <module>
    from sickrage.media.ShowFanArt import ShowFanArt
ImportError: No module named ShowFanArt
 ```

**Comment by MGaetan89** [comment]
For some reason, the file `ShowFanArt` gets renamed into `ShowFanart`.
Try renaming it with an uppercase `A` to see if it fix your issue (it is in `sickrage/media/ShowFanArt.py`).

**Comment by fernandog** [comment]
@MGaetan89 travis get this ?

**Comment by fernandog** [comment]
@duramato git pull please

**Comment by MGaetan89** [comment]
@fernandog I don't know. I never looked at what Travis actually does.
