### ISSUE TITLE
Latest update stopped Sickrage from starting.

### ISSUE THREAD

**Issue by StevenChorkley** [SiCKRAGETV/sickrage-issues#2707]
Upon startup 
````
 steven@homeserver:~$ sudo service sickrage start
 Starting SickRage
 Traceback (most recent call last):
   File "SickBeard.py", line 522, in <module
     SickRage().start()
   File "SickBeard.py", line 295, in start
     sickbeard.initialize(consoleLogging=self.consoleLogging)
   File "/home/steven/.sickrage/sickbeard/__init__.py", line 1308, in initialize
     db.sanityCheckDatabase(myDB, mainDB.MainSanityCheck)
   File "/home/steven/.sickrage/sickbeard/db.py", line 254, in sanityCheckDatabase
     sanity_check(connection).check()
   File "/home/steven/.sickrage/sickbeard/databases/mainDB.py", line 46, in check
     self.convert_tvrage_to_tvdb()
   File "/home/steven/.sickrage/sickbeard/databases/mainDB.py", line 77, in convert_tvrage_to_tvdb
    (INDEXER_TVDB, mapping[0]['mindexer_id'], tvrage_show['indexer_id'])
   File "/home/steven/.sickrage/sickbeard/db.py", line 168, in action
     sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
   File "/home/steven/.sickrage/sickbeard/db.py", line 88, in execute
     return self._execute(query, args)
  File "/home/steven/.sickrage/sickbeard/db.py", line 76, in _execute
     return self.connection.cursor().execute(query)
 sqlite3.IntegrityError: UNIQUE constraint failed: tv_shows.indexer_id
 steven@homeserver:~$ 
````

**Comment by OmgImAlexis** [comment]
What commit are you on?

**Comment by WebSpider** [comment]
#2693

**Comment by StevenChorkley** [comment]
Commit 9df4588e371248751bd60c4c02a90ea979199f43
