### ISSUE TITLE
Images are broken

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#2708]
@SiCKRAGETV/moderators please just mark all issues about images/fanart missing as duplicates of this.

@MGaetan89 @miigotu once this is fixed, we'll close this as the issue for it.

**Comment by MGaetan89** [comment]
Only network logos are missing for me. Poster and banner are working fine for me.

**Comment by TheMotto9** [comment]
@MGaetan89 Maybe it's a Windows thing. But even deleting the cache folder did nothing so I've tried everything I could think to do.

**Comment by boyahr** [comment]
Same as MGaetan here, only the networks are missing, even with the latest update

**Comment by LouisvWyk** [comment]
Since last update all my images disappeared(bannes,network, etc) for me. Looks like image in #2705

Updated to BRANCH: (master) / COMMIT: (5a102de0672f658e119f3d45135ca95355d7453b) 

Please let me know if I need to submit any logs.

**Comment by flightlevel** [comment]
@MGaetan89 
Not on Windows here and all my images (network, posters, banners) work perfectly, but maybe they are cached, because if I right click on any image and click view image, you just get a whole lot of gibberish

**Comment by underdog79** [comment]
I'm using SICKRAGE on DS413J;

Some posters are broken (and all network banners) , 
I cannot edit a show, If I click it, it logs the following error:  

        2015-09-09 14:13:13 Thread-24 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 1295, in displayShow
    xem_numbering=get_xem_numbering_for_show(indexerid, indexer),
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/scene_numbering.py", line 380, in get_xem_numbering_for_show
    xem_refresh(indexer_id, indexer)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/scene_numbering.py", line 480, in xem_refresh
    u'Looking up XEM scene mapping for show %s on %s' % (indexer_id, sickbeard.indexerApi(indexer).name,),
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/indexers/indexer_api.py", line 49, in name
    return indexerConfig[self.indexerID]['name']
KeyError: 2


If I try to edit the show (MASS UPDATE TAB) I receive the following error page:

Error !

TypeError: argument of type 'Undefined' is not iterable

<% anyQualityList = filter(lambda x: x > common.Quality.NONE, common.Quality.qualityStrings) %> <select id="anyQualities" name="anyQualities" multiple="multiple" size="${len(anyQualityList)}"> % for curQuality in sorted(anyQualityList): <option value="${curQuality}" ${('', 'selected="selected"')[curQuality in anyQualities]}>${common.Quality.qualityStrings[curQuality]}</option> % endfor </select> </div> <div class="manageCustom pull-left"> <h4>Archive</h4>
/usr/local/sickrage/var/SickRage/gui/slick/views/manage_massEdit.mako, line 59:
<option value="${curQuality}" ${('', 'selected="selected"')[curQuality in anyQualities]}>${common.Quality.qualityStrings[curQuality]}</option>
/usr/local/sickrage/var/SickRage/gui/slick/views/layouts/main.mako, line 217:
/usr/local/sickrage/var/SickRage/lib/mako/runtime.py, line 853:
callable_(context, *args, **kwargs)

**Comment by OmgImAlexis** [comment]
@underdog79 the second one is fixed in develop.

**Comment by underdog79** [comment]
@OmgImAlexis  : Okay, Thanx... I'll see it when it's in MAIN :)

**Comment by MGaetan89** [comment]
@flightlevel If you see some weird text when trying to view an image, it means you are using the latest version (not cache). I will try to improve that in a future version.

**Comment by neoatomic** [comment]
@MGaetan89 @OmgImAlexis https://github.com/SiCKRAGETV/sickrage-issues/issues/2722#issuecomment-139042140

**Comment by OmgImAlexis** [comment]
@MGaetan89 you probably need to send the image's mime type with the file in the headers and that's why they're getting weird text. When it's loaded via the image tag it's loaded by the image processor and doesn't care about mime type, when it's just opened it does.

**Comment by underdog79** [comment]
Just informative; The posters are all back after the update. All series are available (had to re add the one mentioned above as it was gone)  again.

The only thing that remains  broken are the network banners

**Comment by bb12489** [comment]
I just updated to the latest COMMIT: (bb16d3a3e4d3462a73b944c6e7d9384798774ffd), and my images are still missing. Network logos and all.

**Comment by flightlevel** [comment]
@bb12489 What operating system?
Did you stop SR, delete cache folder, start SR and then full update shows?

**Comment by travisll** [comment]
Network logos are the only thing missing here also.

**Comment by bb12489** [comment]
I'm on server 2012 r2. I'll try all of that in a moment. All I did was the update.

**Comment by JeremiahGillis** [comment]
I am on COMMIT: BRANCH: (master) / COMMIT: (bb16d3a3e4d3462a73b944c6e7d9384798774ffd) on FreeBSD. My network images are also broken. I did stop SR, delete cache.db, and restarted SR. The cache.db came back instantly and the network images were still broken. The network name shows up correctly but there is a icon to the left of each network name with is broken.

**Comment by schimi2k** [comment]
I have also the missing images problem:
BRANCH: (master) / COMMIT: (bb16d3a3e4d3462a73b944c6e7d9384798774ffd) 
windows 10 x64
try to delete cache.db and cache folder and full update series again - i can see the image folder with the images in explorer, but no banners or poster in sickrage

**Comment by neoatomic** [comment]
Let me summarize : 

- Currently the Network logos are not working for anyone.

For Windows users the following is not working : 

- Banners and Posters are not working 
(If you are not on Windows and the banners/posters not shown, than do a mass update of the shows. That will download the images again)
- Notification pop-up messages are broken. (first they where looping, now they dont work at all)
- And i just found out a few buttons are not working properly on Windows.


I just did some more testing on Windows and it seems that also some buttons are not working. (But its hard to test as the notifications are not working also.)
First i wanted to switch to the develop branch. I went to General Configuration --> Advanced Settings --> Branch version: , added my Github account and saved. (no pop-up notification showed, but settings where saved.)
Restarted and set Branch develop and pushed the `Checkout Branch` button but noting happened. Reboot, and still noting. Ended up changing the branch manually...
Added a show on develop, still no banners/posters showing. 
Then went to mass update and tried to delete a show, but the `Submit` button isn't working/noting happens.

![1](https://cloud.githubusercontent.com/assets/7928052/9786973/b26e17d4-57be-11e5-92d0-a3f913ea1d3d.png)
![2](https://cloud.githubusercontent.com/assets/7928052/9786972/b26a5b8a-57be-11e5-847f-56a9b2b56cd5.png)


```
SR Version:  BRANCH: (develop) / COMMIT: (1b573dba89e1761945d962ac50117deb583949b5)  
```

**Comment by OmgImAlexis** [comment]
@MGaetan89 the images seem to be sent as text/html by the way, might need to add a header for png/jpeg or something as that may be the issue?

1. Installed Windows 10
2. Installed Chrome
3. Installed SickRage master(bb16d3a3e4d3462a73b944c6e7d9384798774ffd)
4. Added Castle
5. Deleted Castle
6. Added Castle(2009)
7. Tried forced update

Looks like there's an issue with the art being saved, that'd explain why it's not showing up. 

````
2015-09-10 22:27:33 INFO     SHOWQUEUE-ADD :: Done cache check
2015-09-10 22:27:29 INFO     SHOWQUEUE-ADD :: 83462: Updating NFOs for show with new indexer info
2015-09-10 22:27:29 INFO     SHOWQUEUE-ADD :: Building internal name cache for all shows
2015-09-10 22:27:13 INFO     SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5
2015-09-10 22:27:13 INFO     SHOWQUEUE-ADD :: 83462: Unable to find the show in the database
2015-09-10 22:27:12 INFO     SHOWQUEUE-ADD :: theTVDB: {'useZip': True, 'apikey': 'F9C450E78D99172E', 'cache': 'C:\\SickRage\\Data\\cache\\indexers\\theTVDB', 'language': 'en'}
2015-09-10 22:27:11 INFO     SHOWQUEUE-ADD :: Starting to add show C:\Users\xo\Desktop\Tv Shows\Castle (2009)
2015-09-10 22:26:59 INFO     SHOWQUEUE-REMOVE-SHOW :: Attempt to delete cache file C:\SickRage\Data\cache\images\82607.banner.jpg
2015-09-10 22:26:59 INFO     SHOWQUEUE-REMOVE-SHOW :: Removing Castle
2015-09-10 22:26:56 INFO     SHOWQUEUE-REFRESH :: Done cache check
2015-09-10 22:26:56 WARNING  SHOWQUEUE-REFRESH :: Unable to retrieve image to (obj is None) to save in C:\SickRage\Data\cache\images\82607.fanart.jpg, skipping
2015-09-10 22:26:52 WARNING  SHOWQUEUE-REFRESH :: Unable to retrieve image to (obj is None) to save in C:\SickRage\Data\cache\images\thumbnails\82607.poster.jpg, skipping
2015-09-10 22:26:48 WARNING  SHOWQUEUE-REFRESH :: Unable to retrieve image to (obj is None) to save in C:\SickRage\Data\cache\images\82607.poster.jpg, skipping
2015-09-10 22:26:44 INFO     SHOWQUEUE-REFRESH :: Performing refresh on Castle
2015-09-10 22:21:40 INFO     SHOWQUEUE-ADD :: Done cache check
2015-09-10 22:21:40 WARNING  SHOWQUEUE-ADD :: Unable to retrieve image to (obj is None) to save in C:\SickRage\Data\cache\images\82607.fanart.jpg, skipping
2015-09-10 22:21:35 WARNING  SHOWQUEUE-ADD :: Unable to retrieve image to (obj is None) to save in C:\SickRage\Data\cache\images\thumbnails\82607.poster.jpg, skipping
2015-09-10 22:21:31 WARNING  SHOWQUEUE-ADD :: Unable to retrieve image to (obj is None) to save in C:\SickRage\Data\cache\images\82607.poster.jpg, skipping
2015-09-10 22:21:24 INFO     SHOWQUEUE-ADD :: 82607: Updating NFOs for show with new indexer info
2015-09-10 22:21:24 INFO     SHOWQUEUE-ADD :: Building internal name cache for all shows
2015-09-10 22:21:20 INFO     SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5
2015-09-10 22:21:20 INFO     SHOWQUEUE-ADD :: 82607: Unable to find the show in the database
2015-09-10 22:21:20 INFO     SHOWQUEUE-ADD :: theTVDB: {'useZip': True, 'apikey': 'F9C450E78D99172E', 'cache': 'C:\\SickRage\\Data\\cache\\indexers\\theTVDB', 'language': 'en'}
2015-09-10 22:21:20 INFO     SHOWQUEUE-ADD :: Starting to add show C:\Users\xo\Desktop\Tv Shows\Castle
2015-09-10 22:13:44 INFO     MAIN :: Building internal name cache for all shows
2015-09-10 22:13:43 INFO     CHECKVERSION :: Checking for updates using GIT
2015-09-10 22:13:42 INFO     TORNADO :: Starting SickRage on http://0.0.0.0:8081/
2015-09-10 22:13:42 INFO     MAIN :: New API generated
2015-09-10 22:13:42 INFO     MAIN :: Forcing web server to port 8081
2015-09-10 22:13:39 INFO     MAIN :: Checking for shows with tvrage id's, since tvrage is gone
2015-09-10 22:13:11 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSER thread to exit
2015-09-10 22:13:10 INFO     EVENT-QUEUE :: Waiting for the SEARCHQUEUE thread to exit
2015-09-10 22:13:09 INFO     EVENT-QUEUE :: Waiting for the SHOWQUEUE thread to exit
2015-09-10 22:13:09 INFO     EVENT-QUEUE :: Waiting for the VERSIONCHECKER thread to exit
2015-09-10 22:13:08 INFO     EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2015-09-10 22:13:07 INFO     EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2015-09-10 22:13:07 INFO     EVENT-QUEUE :: Waiting for the DAILYSEARCH thread to exit
2015-09-10 22:13:07 INFO     EVENT-QUEUE :: Waiting for the EVENTS thread to exit
2015-09-10 22:13:07 INFO     EVENT-QUEUE :: Aborting all threads
2015-09-10 22:13:07 INFO     MAIN :: Signal 2 caught, saving and exiting...
2015-09-10 22:06:16 INFO     MAIN :: Updating timezone info with new one: zoneinfo-2015d.tar.gz
2015-09-10 22:06:15 INFO     MAIN :: Building internal name cache for all shows
2015-09-10 22:06:15 INFO     MAIN :: Checking for scene exception updates for AniDB
2015-09-10 22:06:13 INFO     MAIN :: Checking for XEM scene exception updates for theTVDB
2015-09-10 22:06:12 INFO     MAIN :: Checking for scene exception updates for theTVDB
2015-09-10 22:06:12 INFO     CHECKVERSION :: Checking for updates using GIT
2015-09-10 22:06:12 INFO     TORNADO :: Starting SickRage on http://0.0.0.0:8081/
2015-09-10 22:06:12 INFO     MAIN :: New API generated
2015-09-10 22:06:12 INFO     MAIN :: Forcing web server to port 8081
2015-09-10 22:06:12 INFO     MAIN :: Checking for shows with tvrage id's, since tvrage is gone
````

Here's my force full update log after turning on debug.

````
2015-09-10 22:32:42 DEBUG    SHOWQUEUE-REFRESH :: No new cache images needed, not retrieving new ones
2015-09-10 22:32:42 DEBUG    SHOWQUEUE-REFRESH :: Checking if file C:\SickRage\Data\cache\images\83462.fanart.jpg exists
2015-09-10 22:32:42 DEBUG    SHOWQUEUE-REFRESH :: Checking if file C:\SickRage\Data\cache\images\thumbnails\83462.banner.jpg exists
2015-09-10 22:32:42 DEBUG    SHOWQUEUE-REFRESH :: Checking if file C:\SickRage\Data\cache\images\thumbnails\83462.poster.jpg exists
2015-09-10 22:32:42 DEBUG    SHOWQUEUE-REFRESH :: Checking if file C:\SickRage\Data\cache\images\83462.banner.jpg exists
2015-09-10 22:32:42 DEBUG    SHOWQUEUE-REFRESH :: Checking if file C:\SickRage\Data\cache\images\83462.poster.jpg exists
2015-09-10 22:32:42 DEBUG    SHOWQUEUE-REFRESH :: Checking if we need any cache images for show 83462
2015-09-10 22:32:42 DEBUG    SHOWQUEUE-REFRESH :: Checking & filling cache for show Castle (2009)
2015-09-10 22:32:42 DEBUG    SHOWQUEUE-REFRESH :: 83462: Writing NFOs for all episodes
2015-09-10 22:32:42 DEBUG    SHOWQUEUE-REFRESH :: 83462: Writing NFOs for show
2015-09-10 22:32:42 DEBUG    SHOWQUEUE-REFRESH :: Running metadata routines for Sony PS3
2015-09-10 22:32:42 DEBUG    SHOWQUEUE-REFRESH :: Running metadata routines for WDTV
2015-09-10 22:32:42 DEBUG    SHOWQUEUE-REFRESH :: Running metadata routines for Mede8er
2015-09-10 22:32:42 DEBUG    SHOWQUEUE-REFRESH :: Running metadata routines for TIVO
2015-09-10 22:32:42 DEBUG    SHOWQUEUE-REFRESH :: Running metadata routines for KODI
2015-09-10 22:32:42 DEBUG    SHOWQUEUE-REFRESH :: Running metadata routines for MediaBrowser
2015-09-10 22:32:42 DEBUG    SHOWQUEUE-REFRESH :: Running metadata routines for KODI 12+
2015-09-10 22:32:42 DEBUG    SHOWQUEUE-REFRESH :: 83462: Loading all episodes with a location from the database
2015-09-10 22:32:42 DEBUG    SHOWQUEUE-REFRESH :: 83462: Found files: []
2015-09-10 22:32:42 DEBUG    SHOWQUEUE-REFRESH :: 83462: Loading all episodes from the show directory C:\Users\xo\Desktop\Tv Shows\Castle (2009)
2015-09-10 22:32:42 INFO     SHOWQUEUE-REFRESH :: Performing refresh on Castle (2009)
````

Trying on develop now.

**Comment by OmgImAlexis** [comment]
This could possibly be part of the issue too, notice this part `C:\\SickRage\\Data\\cache\\indexers\\theTVDB`. I'm not too sure but I'm guess here that Windows probably doesn't like double slashes.

````
2015-09-10 22:32:42 INFO     SHOWQUEUE-REFRESH :: Performing refresh on Castle (2009)
2015-09-10 22:27:33 INFO     SHOWQUEUE-ADD :: Done cache check
2015-09-10 22:27:29 INFO     SHOWQUEUE-ADD :: 83462: Updating NFOs for show with new indexer info
2015-09-10 22:27:29 INFO     SHOWQUEUE-ADD :: Building internal name cache for all shows
2015-09-10 22:27:13 INFO     SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5
2015-09-10 22:27:13 INFO     SHOWQUEUE-ADD :: 83462: Unable to find the show in the database
2015-09-10 22:27:12 INFO     SHOWQUEUE-ADD :: theTVDB: {'useZip': True, 'apikey': 'F9C450E78D99172E', 'cache': 'C:\\SickRage\\Data\\cache\\indexers\\theTVDB', 'language': 'en'}
2015-09-10 22:27:11 INFO     SHOWQUEUE-ADD :: Starting to add show C:\Users\xo\Desktop\Tv Shows\Castle (2009)
2015-09-10 22:26:59 INFO     SHOWQUEUE-REMOVE-SHOW :: Attempt to delete cache file C:\SickRage\Data\cache\images\82607.banner.jpg
2015-09-10 22:26:59 INFO     SHOWQUEUE-REMOVE-SHOW :: Removing Castle
2015-09-10 22:26:56 INFO     SHOWQUEUE-REFRESH :: Done cache check
2015-09-10 22:26:56 WARNING  SHOWQUEUE-REFRESH :: Unable to retrieve image to (obj is None) to save in C:\SickRage\Data\cache\images\82607.fanart.jpg, skipping
2015-09-10 22:26:52 WARNING  SHOWQUEUE-REFRESH :: Unable to retrieve image to (obj is None) to save in C:\SickRage\Data\cache\images\thumbnails\82607.poster.jpg, skipping
2015-09-10 22:26:48 WARNING  SHOWQUEUE-REFRESH :: Unable to retrieve image to (obj is None) to save in C:\SickRage\Data\cache\images\82607.poster.jpg, skipping
2015-09-10 22:26:44 INFO     SHOWQUEUE-REFRESH :: Performing refresh on Castle
````

This is on develop (bb16d3a3e4d3462a73b944c6e7d9384798774ffd)

**Comment by OmgImAlexis** [comment]
This is interesting, are we using strings for file paths? https://stackoverflow.com/questions/22567785/error-with-double-slash-in-windows-path-in-python

**Comment by ProffShadow** [comment]
I also have the poster and banner issue. 
Removed them physically, and forced update - No fix
Removed cache files and forced update - No fix
Unistall and reinstall SR - No fix

I have also picked up another problem with the Windows installer SR. I can not add shows that are on a network drive anymore. I can't even see any network drives. Not sure if this is an issue or not but I could do it before the Windows Intalled SR.

**Comment by OmgImAlexis** [comment]
@MGaetan89 if you haven't worked out the issue I think I know what it is. From the looks of it we either need to use `os.path.join` on ALL strings to join the file paths or use regex to convert them depending on the OS. Ref: [here](https://stackoverflow.com/questions/16333569/mixed-slashes-with-os-path-join-on-windows).

**Comment by ripper1967** [comment]
omginalexis  i sent u an email see if that will help with this issue

**Comment by OmgImAlexis** [comment]
@ripper1967 I actually just setup a Windows 10 virtual machine for testing and I think I've worked out the issue. Sorry if I wasted your time on that. Thanks though.

**Comment by ripper1967** [comment]
no its fine just wanted someone see if it could be fixed no time wasted,,

**Comment by Ockingshay** [comment]
![untitled](https://cloud.githubusercontent.com/assets/5208756/9793263/7d8cc56a-57dc-11e5-8e63-f1029ffc3e36.jpg)

Just network logos for me.

**Comment by MGaetan89** [comment]
@OmgImAlexis Thanks for the tips and the research. It helped a lot!

I will send a PR in a minute, but I don't have a Windows machine with me now to test it. If someone is able to try and give a feedback, that would be greatly appreciated :)

**Comment by MGaetan89** [comment]
Here is the PR: https://github.com/SiCKRAGETV/SickRage/pull/2473

**Comment by MGaetan89** [comment]
The PR is now in `develop`. If you are using `develop`, you can update to see if it works for you.

**Comment by kingmotley** [comment]
On develop: BRANCH: (develop) / COMMIT: (e4d47b65a5b14102648ab5e80d1c3a635e134875) 
Images (posters and network) still broken.

**Comment by kingmotley** [comment]
png images are being sent with a mimetype of "images/x-png" which is invalid.  It should be "images/png"

**Comment by MGaetan89** [comment]
Thanks for the feedback.
Which image was sent as `image/x-png`? The network logo? Because they are properly sent with `image/png` for me. Maybe the mimetype is wrong because the path is wrong.

**Comment by kingmotley** [comment]
/showPoster/?show=268592&which=poster_thumb

**Comment by kingmotley** [comment]
I'm just playing around with it, so I `print static_media_path` in the middle of get_media_type, and the path there is correct.

**Comment by MGaetan89** [comment]
The fact that the path is correct was helpful. I found [this answer](http://stackoverflow.com/a/3198124/1914223):

> You may need to open the file as "rb" (in windows based environments it's usually the case.

It still work for me (on Unix), and a new PR is here for your tot test once it's merged: https://github.com/SiCKRAGETV/SickRage/pull/2475

**Comment by kingmotley** [comment]
That was it.  Posters and network now work.

**Comment by OmgImAlexis** [comment]
@MGaetan89 tested on Windows 10, works perfectly. @VinceVal I noticed your installer pulls down sickrage weirdly, not only did it take about 5x as long to do it's git clone vs me doing it manually but I couldn't checkout develop properly using git in the SickRage folder and had to delete and re clone it.

**Comment by OmgImAlexis** [comment]
Just noticed network icons are still missing, all others seem fine.

**Comment by tanilolli** [comment]
Same here. Windows 10 and network icons are missing on the develop branch.

**Comment by damousys** [comment]
Just cloned a new install of SickRage to a temp folder but still no banners nor logos
BRANCH: (master) / COMMIT: (bb16d3a3e4d3462a73b944c6e7d9384798774ffd)

**Comment by OmgImAlexis** [comment]
@damousys try dev, that's where it's fixed.

**Comment by damousys** [comment]
maybe a stupid question but how do I go to the DEV.
If i change it in settings, nothing changes

**Comment by neoatomic** [comment]
@damousys No need to switch to Develop. It will be pushed to Master branch quickly. :)

**Comment by damousys** [comment]
Thanks, I will be patience then

**Comment by damousys** [comment]
It is fixed @ the master branche Thanks

**Comment by FreelanceX** [comment]
Thanks for the push to master branch.

**Comment by miigotu** [comment]
you're welcome

**Comment by loungebob** [comment]
So I did update (well, update didnt work so deleted the whole SR directory and did a clean install, then added db and ini file back from backup), then did the below just to make sure:

F:\Mediaserver\SickRage\SickRage>git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.

F:\Mediaserver\SickRage\SickRage>git branch -u upstream/master
Branch master set up to track remote branch master from upstream.

F:\Mediaserver\SickRage\SickRage>git reset --hard upstream/master
HEAD is now at e1e4c28 Override UA for RARBG - FIX

F:\Mediaserver\SickRage\SickRage>git pull
Already up-to-date.

So, I'm assuming I'm now where this all should be fixed (no images, endless annoying notification banners). But, I still have no images and the notification banners still come aplenty. 

BRANCH: (master) / COMMIT: (e1e4c284e10f13cebf4277bbd6924d6d5085d1ce) 

![snag-0000](https://cloud.githubusercontent.com/assets/8558865/9834511/91db624c-59bc-11e5-899c-b6d8761b1df3.png)
![snag-0001](https://cloud.githubusercontent.com/assets/8558865/9834512/97e4ae82-59bc-11e5-8768-3b42e4a8a48d.png)
![snag-0002](https://cloud.githubusercontent.com/assets/8558865/9834514/bdb7b550-59bc-11e5-9d5d-8105b3a54e0f.png)
![snag-0003](https://cloud.githubusercontent.com/assets/8558865/9834515/c109b8a2-59bc-11e5-824d-3fd9816c7797.png)

**Comment by miigotu** [comment]
You need to do a full update on all shows.

**Comment by loungebob** [comment]
you mean like this?
![snag-0004](https://cloud.githubusercontent.com/assets/8558865/9834589/898c04fc-59c1-11e5-8ac4-9e0307b83ec6.png)

did this like 10 times. does it take a long time...can I see the progress somewhere? also, some of the shows (the unticked ones) I cannot tick, they show a red circle crossed-through when I try to tick it.

**Comment by loungebob** [comment]
yeah I think I should be patient. stuff is happening and things are appearing.

**Comment by flightlevel** [comment]
@loungebob With that many shows it will take a long time.

**Comment by miigotu** [comment]
under tools menu, select status, scroll down and you'll see the show queue progress.

**Comment by loungebob** [comment]
thank you. all good now.

**Comment by ripper1967** [comment]
yes thank you,all fixed here as well.

**Comment by greg4168** [comment]
Hi - I have an issue similar to what ProffShadow posted above with network drives no longer being available in SickRage since installing over my existing install with the new Windows installer.  I am running it as a service now and tried with both local system and my personal credentials.  I also created the EnableLinkedConnections=1 registry key I read about elsewhere.  Anybody know how to get the network drive to become available in SickRage after the Windows installer?

Thanks much

**Comment by miigotu** [comment]
@greg4168 what does that have to do with the issue here? Make the service use the network user.

**Comment by greg4168** [comment]
@miigotu nothing to do with the image issue, responding to a previous comment in the thread.  Your recommendation didn't work, that's why I'm asking.
