### ISSUE TITLE
[APP SUBMITTED]: 'str' object has no attribute 'text'

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#2728]
### INFO
Python Version: **2.7.9 (default, Apr  2 2015, 15:34:55) [GCC 4.9.2]**
Operating System: **Linux-3.19.0-26-generic-i686-with-Ubuntu-15.04-vivid**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@0af10956fd818520c7a551b628557b978b4e1e02
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-MANUAL-75340 :: [TorrentBytes] :: Error while searching TorrentBytes, skipping: 'str' object has no attribute 'text'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by duramato** [comment]
```2015-09-09 20:19:00 INFO     SEARCHQUEUE-MANUAL-75340 :: [TorrentBytes] :: Unable to find a download for: [Prison Break - 1x09 - Um Novo Chefe]
2015-09-09 20:19:00 ERROR    SEARCHQUEUE-MANUAL-75340 :: [TorrentBytes] :: Error while searching TorrentBytes, skipping: 'str' object has no attribute 'text'
2015-09-09 20:18:57 INFO     SEARCHQUEUE-MANUAL-75340 :: [TorrentBytes] :: Performing episode search for Prison Break
AA
AAAttributeError: 'NoneType' object has no attribute 'text'
AA    if re.search('Invalid Username/password', response.text) \
AA  File "/home/super******/SickRage/sickbeard/providers/alpharatio.py", line 93, in _doLogin
AA    if not self._doLogin():
AA  File "/home/super******/SickRage/sickbeard/providers/alpharatio.py", line 154, in _doSearch
AA    itemList += self._doSearch(curString, search_mode, len(episodes), epObj=epObj)
AA  File "/home/super******/SickRage/sickbeard/providers/generic.py", line 347, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/home/super******/SickRage/sickbeard/search.py", line 462, in searchProviders
2015-09-09 20:18:57 ERROR    SEARCHQUEUE-MANUAL-75340 :: [AlphaRatio] :: Error while searching AlphaRatio, skipping: 'NoneType' object has no attribute 'text'
AA
AATooManyRedirects: Exceeded 30 redirects.
AA    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects)
AA  File "/home/super******/SickRage/lib/requests/sessions.py", line 114, in resolve_redirects
AA    history = [resp for resp in gen] if allow_redirects else []
AA  File "/home/super******/SickRage/lib/requests/sessions.py", line 602, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/home/super******/SickRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('POST', url, data=data, json=json, **kwargs)
AA  File "/home/super******/SickRage/lib/requests/sessions.py", line 507, in post
AA    resp = session.post(url, data=post_data, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "/home/super******/SickRage/sickbeard/helpers.py", line 1376, in getURL
2015-09-09 20:18:57 WARNING  SEARCHQUEUE-MANUAL-75340 :: [AlphaRatio] :: Traceback (most recent call last):```

**Comment by bardic** [comment]
INFO

Python Version:2.7.8 
Operating System: OSX 10.10.3
BRANCH: (master) / COMMIT: (8abad2c4fc72f1610881aea9c2520ce4175911ab) 

Getting the same issue: https://gist.github.com/bardic/5f50a660bf739ab5c7ee

**Comment by duramato** [comment]
@bardic this is already fixed on dev branch ,you will need to wait for it to be on master

**Comment by bardic** [comment]
@duramato sweet thanks for the info

**Comment by technazz** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@8abad2c4fc72f1610881aea9c2520ce4175911ab
Link to Log: https://gist.github.com/723f4241ddf4f28c525b
### ERROR
```
SEARCHQUEUE-MANUAL-300312 :: [TorrentBytes] :: Error while searching TorrentBytes, skipping: 'str' object has no attribute 'text'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
