### ISSUE TITLE
Can't load shows (home page)

### ISSUE THREAD

**Issue by myersam** [SiCKRAGETV/sickrage-issues#2733]
I saw some said it was slow, mine refuses to load though I can get to some other pages like news, history, manage and config.
Error log:
2015-09-09 18:07:03 Thread-16 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage-master\sickbeard\webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "C:\SickRage-master\sickbeard\webserve.py", line 715, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage-master\sickbeard\webserve.py", line 113, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage-master\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage-master\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage-master\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module C__SickRage_master_gui_slick_views_home_mako not found in sys.modules

**Comment by OmgImAlexis** [comment]
Duplicate https://github.com/SiCKRAGETV/sickrage-issues/issues/2735
