### ISSUE TITLE
[APP SUBMITTED]: Loaded module C__SickRage_gui_slick_views_home_mako not found in sys.modules

### ISSUE THREAD

**Issue by johnscrub** [SiCKRAGETV/sickrage-issues#2735]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@8abad2c4fc72f1610881aea9c2520ce4175911ab
No Log available with ERRORS: 
### ERROR
```
Thread-63 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 715, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 113, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module C__SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by flightlevel** [comment]
@johnscrub 
Have you tried clearing your cache?

-Find the location of your cache folder by going to Config -> Help & Info in SickRage
-STOP SickRage and give it a chance to shutdown
-Delete all the folders in the cache folder except images folder
-Start SR

**Comment by johnscrub** [comment]
Thank you!!I will try this when i get home and am able.I did get access to my shows by changing the view from poster.Still no artwork but i could acces them and search.I thank you for your time!!!Date: Wed, 9 Sep 2015 21:55:33 -0700

**Comment by johnscrub** [comment]
I just tired your suggestion and it was a no go..Same issue as before no artwork and cant access unless i change the view..thanks for helping
Date: Wed, 9 Sep 2015 21:55:33 -0700

**Comment by flightlevel** [comment]
A fix has been applied to the develop branch for the images issue, shouldn't be too far away from master. 
Hopefully that will fix both issues.

**Comment by didyouexpectthat** [comment]
I am also getting this randomly as of today. I was fine for most of the day with no errors and then out of the blue, 50-something showed up. 
```
2015-09-10 14:51:45 DEBUG    TORNADO :: Failed doing webui request "index": Traceback (most recent call last):
  File "/usr/share/sickrage/sickbeard/webserve.py", line 257, in get
    results = yield self.async_call(method)
  File "/usr/share/sickrage/tornado/gen.py", line 807, in run
    value = future.result()
  File "/usr/share/sickrage/lib/concurrent/futures/_base.py", line 400, in result
    return self.__get_result()
  File "/usr/share/sickrage/lib/concurrent/futures/_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "/usr/share/sickrage/lib/concurrent/futures/_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "/usr/share/sickrage/lib/concurrent/futures/thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/share/sickrage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/usr/share/sickrage/sickbeard/webserve.py", line 715, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/usr/share/sickrage/sickbeard/webserve.py", line 113, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/share/sickrage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/share/sickrage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/usr/share/sickrage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _usr_share_sickrage_gui_slick_views_home_mako not found in sys.modules
```

BRANCH: (master) / COMMIT: (bb16d3a3e4d3462a73b944c6e7d9384798774ffd

**Comment by johnscrub** [comment]
Thanks!!I really apreciate the work and all the hellp that is provided!!Date: Thu, 10 Sep 2015 18:05:57 -0700

**Comment by MGaetan89** [comment]
Closing for https://github.com/SiCKRAGETV/sickrage-issues/issues/2781

**Comment by jrladislas** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@4d37c1352e1a27023ffd520a4da8ab0f024333e6
Link to Log: https://gist.github.com/6d863faade00858a1bee
### ERROR
```
Thread-15 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 275, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 682, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module C__SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by jrladislas** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@4d37c1352e1a27023ffd520a4da8ab0f024333e6
Link to Log: https://gist.github.com/e856be6aff4255b8943b
### ERROR
```
Thread-14 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 275, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 682, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module C__SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by jrladislas** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@4d37c1352e1a27023ffd520a4da8ab0f024333e6
Link to Log: https://gist.github.com/b2f2d4d7731243d6f1c0
### ERROR
```
Thread-13 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 275, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 682, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module C__SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by jrladislas** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@f8da2f08a098731dc648794f137177ade2f4bb49
No Log available with ERRORS: 
### ERROR
```
Thread-14 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 275, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 670, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module C__SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Biomorph77** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@638270689679f3958d1b593c329e7c6e5cb7448e
No Log available with ERRORS: 
### ERROR
```
Thread-34 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module C__SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Biomorph77** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@638270689679f3958d1b593c329e7c6e5cb7448e
No Log available with ERRORS: 
### ERROR
```
Thread-30 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module C__SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Biomorph77** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@638270689679f3958d1b593c329e7c6e5cb7448e
No Log available with ERRORS: 
### ERROR
```
Thread-38 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module C__SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Biomorph77** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@638270689679f3958d1b593c329e7c6e5cb7448e
No Log available with ERRORS: 
### ERROR
```
Thread-23 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module C__SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Biomorph77** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@638270689679f3958d1b593c329e7c6e5cb7448e
No Log available with ERRORS: 
### ERROR
```
Thread-31 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module C__SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Biomorph77** [comment]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@638270689679f3958d1b593c329e7c6e5cb7448e
No Log available with ERRORS: 
### ERROR
```
Thread-41 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module C__SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
