### ISSUE TITLE
massEditSubmit failed

### ISSUE THREAD

**Issue by mgaulton** [SiCKRAGETV/sickrage-issues#2746]
BRANCH: (master) / COMMIT: (bb16d3a3e4d3462a73b944c6e7d9384798774ffd) 

Tried to edit paths ( A moved to B) and got the below on submit
```
2015-09-10 11:23:30 DEBUG    TORNADO :: Failed doing webui request "massEditSubmit":
 Traceback (most recent call last):
  File "/opt/SickBeard-tvrage/sickbeard/webserve.py", line 257, in get
    results = yield self.async_call(method)
  File "/opt/SickBeard-tvrage/tornado/gen.py", line 807, in run
    value = future.result()
  File "/opt/SickBeard-tvrage/lib/concurrent/futures/_base.py", line 400, in result
    return self.__get_result()
  File "/opt/SickBeard-tvrage/lib/concurrent/futures/_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "/opt/SickBeard-tvrage/lib/concurrent/futures/_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "/opt/SickBeard-tvrage/lib/concurrent/futures/thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/SickBeard-tvrage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/opt/SickBeard-tvrage/sickbeard/webserve.py", line 3310, in massEditSubmit
    directCall=True)
  File "/opt/SickBeard-tvrage/sickbeard/webserve.py", line 1488, in editShow
    showObj.saveToDB()
  File "/opt/SickBeard-tvrage/sickbeard/tv.py", line 1190, in saveToDB
    myDB.upsert("imdb_info", newValueDict, controlValueDict)
  File "/opt/SickBeard-tvrage/sickbeard/db.py", line 216, in upsert
    self.action(query, valueDict.values() + keyDict.values())
  File "/opt/SickBeard-tvrage/sickbeard/db.py", line 168, in action
    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/SickBeard-tvrage/sickbeard/db.py", line 88, in execute
    return self._execute(query, args)
  File "/opt/SickBeard-tvrage/sickbeard/db.py", line 77, in _execute
    return self.connection.cursor().execute(query, args)
OperationalError: near "WHERE": syntax error
```

**Comment by OmgImAlexis** [comment]
@mgaulton can you please update and let me know if you've still got this issue. Otherwise I'll close this.
