### ISSUE TITLE
undefined symbol: sqlite3_transfer_bindings

### ISSUE THREAD

**Issue by p418** [SiCKRAGETV/sickrage-issues#2747]
Hi all,

For a couple of days now, I'm unable to start Sickrage.
I'm using Debian and performed a "GUI" update.

After a restart, when I try to run:

```sh
/etc/init.d/sickrage start
```

it returns following message:

> Traceback (most recent call last):
  File "SickBeard.py", line 53, in <module>
    import sickbeard
  File "/apps/SickRage/sickbeard/__init__.py", line 37, in <module>
    from sickbeard import metadata
  File "/apps/SickRage/sickbeard/metadata/__init__.py", line 22, in <module>
    import kodi, kodi_12plus, mediabrowser, ps3, wdtv, tivo, mede8er
  File "/apps/SickRage/sickbeard/metadata/kodi.py", line 19, in <module>
    import generic
  File "/apps/SickRage/sickbeard/metadata/generic.py", line 29, in <module>
    from sickbeard import helpers
  File "/apps/SickRage/sickbeard/helpers.py", line 70, in <module>
    from sickbeard import db
  File "/apps/SickRage/sickbeard/db.py", line 23, in <module>
    import sqlite3
  File "/usr/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/usr/lib/python2.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: /usr/lib/python2.7/lib-dynload/_sqlite3.so: undefined symbol: sqlite3_transfer_bindings

I've already tried to pull a fresh new version from the repo but got the same.

**Comment by miigotu** [comment]
" /usr/lib/python2.7/lib-dynload/_sqlite3.so"

This is not a part of SR, your python is broken.

**Comment by p418** [comment]
Ouch...
I'm wonderring how a simple SR's update could break Python

**Comment by miigotu** [comment]
its clear in that error it is not an error in SR, but an error with a c extension in your pyhon install.

**Comment by WebSpider** [comment]
You probably updated system libsqlite without updating the related python sqlite module. There have been a couple of security updates out on libsqlite.

**Comment by p418** [comment]
Thanks WebSpider!

After installing `pip` and `python-dev` and run  `pip install pysqlite --upgrade`  all work fine!
