### ISSUE TITLE
[APP SUBMITTED]: Loaded module _share_MD0_DATA__qpkg_SickBeard_TVRage_SickBeard_TVRage_gui_slick_views_home_mako not found in sys.modules

### ISSUE THREAD

**Issue by Peke** [SiCKRAGETV/sickrage-issues#2757]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@f8eedd203011de46f61e7725cacd33de2146439c
Link to Log: https://gist.github.com/8aa8cba74d2a51290cb8
### ERROR
```
Thread-209 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 715, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 113, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _share_MD0_DATA__qpkg_SickBeard_TVRage_SickBeard_TVRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Peke** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@bb16d3a3e4d3462a73b944c6e7d9384798774ffd
Link to Log: https://gist.github.com/a2f4567925d81a00d6f4
### ERROR
```
Thread-20 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 715, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 113, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _share_MD0_DATA__qpkg_SickBeard_TVRage_SickBeard_TVRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Peke** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@bb16d3a3e4d3462a73b944c6e7d9384798774ffd
Link to Log: https://gist.github.com/38251c5075223942a932
### ERROR
```
Thread-56 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 715, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 113, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _share_MD0_DATA__qpkg_SickBeard_TVRage_SickBeard_TVRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
@Peke Its the same as https://github.com/SiCKRAGETV/sickrage-issues/issues/2735 . Could you add the logs and info there. Than we have all in one place, and this can be closed.

**Comment by distracto** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@f913285d1decce196c6054c43507582fb2a2a7ee
Link to Log: https://gist.github.com/18e5190e3e25327e8163
### ERROR
```
Thread-174 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 275, in async_call
    result = function(**kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 682, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _share_MD0_DATA__qpkg_SickBeard_TVRage_SickBeard_TVRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by pheverts** [comment]
### INFO
Python Version: **2.7.3 (default, Apr 12 2012, 13:08:47) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@78650696464c3461fc49cfd9b93ee1ebbabed19b
No Log available with ERRORS: 
### ERROR
```
Thread-26 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _share_MD0_DATA__qpkg_SickBeard_TVRage_SickBeard_TVRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
