### ISSUE TITLE
DistributionNotFound: python-dateutil>=2.1 after Sickrage update

### ISSUE THREAD

**Issue by dogeatdog** [SiCKRAGETV/sickrage-issues#2762]
Branch (master) / COMMIT: (bb16d3a3e4d3462a73b944c6e7d9384798774ffd)  
Your operating system and python version : Ubuntu 14.04 Server. 
Python : 2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]
What you did : I updated via the web gui when it asked me to.
What happened : errors in my logfile with regard to dateutil. 
Logfile : https://gist.github.com/dogeatdog/8b1553d97e7559123835
What you expected : no errors :)

Hi guys,

Just updated my Sickrage install today and when I checked the logs afterwards it's raining errors like this : 

     2015-09-11 15:32:27 POSTPROCESSER :: Traceback (most recent call last):  
File "/opt/sickrage/sickbeard/tv.py", line 1470, in downloadSubtitles     foundSubs = subliminal.download_best_subtitles([video], languages=languages, providers=providers, single=not sickbeard.SUBTITLES_MULTI, hearing_impaired=False)  
File "/opt/sickrage/lib/subliminal/api.py", line 74, in download_best_subtitles     with ProviderPool(providers, provider_configs) as pp:  
File "/opt/sickrage/lib/subliminal/providers/__init__.py", line 241, in __init__     self.providers = dict([(p, provider_manager[p]) for p in (providers or provider_manager.available_providers)])  
File "/opt/sickrage/lib/subliminal/providers/__init__.py", line 180, in __getitem__     self.providers[ep.name] = ep.load()  
File "/opt/sickrage/lib/pkg_resources.py", line 1953, in load     if require: self.require(env, installer)  
File "/opt/sickrage/lib/pkg_resources.py", line 1966, in require     working_set.resolve(self.dist.requires(self.extras  ),env,installer))  
File "/opt/sickrage/lib/pkg_resources.py", line 565, in resolve    
raise DistributionNotFound(req)  # XXX put more info here
DistributionNotFound: python-dateutil>=2.1

Checked out /opt/sickrage/lib/dateutil and the info in __init__.py leads me to believe I do have a good version :

Code:
 # -*- coding: utf-8 -*-
  """
  Copyright (c) 2003-2010  Gustavo Niemeyer <gustavo@niemeyer.net>
   
  This module offers extensions to the standard Python
  datetime module.
  """
  __author__ = "Tomi Pieviläinen <tomi.pievilainen@iki.fi>"
  __license__ = "Simplified BSD"
  __version__ = "2.2"

I have no idea what happened or how I can fix this. Hoping you guys do ?

**Comment by flightlevel** [comment]
Maybe give this a go
Reinstalls dateutil
http://stackoverflow.com/a/12883196

**Comment by dogeatdog** [comment]
Unfortunately, that was the first thing I tried (should've said that, sorry). In fact, I even think I found the same SO-link :) Anyway, that didn't help. Just updated my (external to SR?) dateutil from 2.41 to 2.42. 
I think something is wrong inside SR/Python so it can't find the dateutil distribution altogether (since the version inside SR should satisfy the >=2.1 requirement.  Just don't know how to fix it, other than trying to reinstall SR (which I rather not do).

Thanks for the suggestion anyway :D

**Comment by OmgImAlexis** [comment]
@dogeatdog if you backup your install using the backup feature, move sickrage into another folder like sickrage_old, reinstall and then restore your sickrage using the restore feature you shouldn't lose anything. If that fixes the issue then delete the sickrage_old and we'll close this if it doesn't then let us know.

**Comment by dogeatdog** [comment]
Ok crap. That didn't work. I did exactly what you asked and still no dice. 

Errorlog : https://gist.github.com/dogeatdog/ce6656775c36b90fbb67
Log : https://gist.github.com/dogeatdog/a9016fc6b47e3cd6f995

I used this guide to reinstall sickrage : http://www.htpcguides.com/install-sickrage-ubuntu-14-04/

**Comment by dogeatdog** [comment]
Ok, the plot thickens ..

I decided to install the python-dateutil version that was required. That is, the minimal version, so 2.1 (not 2.1 or higher) : 

sudo pip install python-dateutil==2.1

Once done, I checked an hour later for new errors. Now I saw this : 

        2015-09-13 09:08:09 FINDSUBTITLES :: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/tv.py", line 1470, in downloadSubtitles
    foundSubs = subliminal.download_best_subtitles([video], languages=languages, providers=providers, single=not sickbeard.SUBTITLES_MULTI, hearing_impaired=False)
  File "/opt/sickrage/lib/subliminal/api.py", line 74, in download_best_subtitles
    with ProviderPool(providers, provider_configs) as pp:
  File "/opt/sickrage/lib/subliminal/providers/__init__.py", line 241, in __init__
    self.providers = dict([(p, provider_manager[p]) for p in (providers or provider_manager.available_providers)])
  File "/opt/sickrage/lib/subliminal/providers/__init__.py", line 180, in __getitem__
    self.providers[ep.name] = ep.load()
  File "/opt/sickrage/lib/pkg_resources.py", line 1953, in load
    if require: self.require(env, installer)
  File "/opt/sickrage/lib/pkg_resources.py", line 1966, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "/opt/sickrage/lib/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
DistributionNotFound: stevedore>=0.14

So.. same trick : sudo pip install stevedore==0.14

And lo and behold, the errors were gone and subs were working again.  Should someone give me some explanation as to WHY it stopped working after the last update of sickrage, I'd be so happy :)

**Comment by dogeatdog** [comment]
Closing this issue. Thanks for all contributions !

**Comment by OmgImAlexis** [comment]
@flightlevel incase this happens to someone else.
