### ISSUE TITLE
[APP SUBMITTED]: Loaded module _share_CACHEDEV1_DATA__qpkg_QSickRage_SickRage_gui_slick_views_home_mako not found in sys.modules

### ISSUE THREAD

**Issue by AcerTravel** [SiCKRAGETV/sickrage-issues#2767]
### INFO
Python Version: **2.7.10 (default, Jul  8 2015, 08:04:18) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@37914618686ee70479da0fa4b2cca851fa49c5e2
Link to Log: https://gist.github.com/d0e47fb3043dbf829683
### ERROR
```
Thread-14 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 718, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 113, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _share_CACHEDEV1_DATA__qpkg_QSickRage_SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by WebSpider** [comment]
Please stop sr, remove cache/mako and restart sr

-----Original Message-----

**Comment by AcerTravel** [comment]
Hello,
Where is cache/mako

**Comment by AcerTravel** [comment]
I try and the problem continous
 2015-09-11 21:43:30 Thread-14 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 718, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 113, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _share_CACHEDEV1_DATA__qpkg_QSickRage_SickRage_gui_slick_views_home_mako not found in sys.modules

**Comment by WebSpider** [comment]
Dont know on qnap for sure, but it looks like /share/cachedev1_data/.qpkg/qsickrage/sickrage/cache/mako

**Comment by AcerTravel** [comment]
I found it and deleted. But when starts appears again

**Comment by AcerTravel** [comment]
### INFO
Python Version: **2.7.10 (default, Jul  8 2015, 08:04:18) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@2e08ee65e83f74f9958d9305b697ad27c0820cc5
Link to Log: https://gist.github.com/49b1ba041b9e68b0deaf
### ERROR
```
Thread-13 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 718, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 113, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _share_CACHEDEV1_DATA__qpkg_QSickRage_SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by AcerTravel** [comment]
### INFO
Python Version: **2.7.10 (default, Jul  8 2015, 08:04:18) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@29105fd42b203393cc2393d683a3d11b74a0c752
Link to Log: https://gist.github.com/b42be1daf4d043926f97
### ERROR
```
Thread-40 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 679, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 113, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _share_CACHEDEV1_DATA__qpkg_QSickRage_SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by AcerTravel** [comment]
### INFO
Python Version: **2.7.10 (default, Jul  8 2015, 08:04:18) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@6d7fd7062f8d827f88c53994db696d81270c8354
Link to Log: https://gist.github.com/15dbf7de0b27246e669f
### ERROR
```
Thread-13 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 680, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 114, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _share_CACHEDEV1_DATA__qpkg_QSickRage_SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Legolash2o** [comment]
### INFO
Python Version: **2.7.10 (default, Jul  8 2015, 08:04:18) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@4d37c1352e1a27023ffd520a4da8ab0f024333e6
Link to Log: https://gist.github.com/51f6fcee881f0ba17983
### ERROR
```
Thread-16 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 275, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 682, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _share_CACHEDEV1_DATA__qpkg_QSickRage_SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Legolash2o** [comment]
### INFO
Python Version: **2.7.10 (default, Jul  8 2015, 08:04:18) [GCC 4.3.6]**
Operating System: **Linux-3.12.6-x86_64-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@638270689679f3958d1b593c329e7c6e5cb7448e
Link to Log: https://gist.github.com/d3440a916472610c9458
### ERROR
```
Thread-14 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _share_CACHEDEV1_DATA__qpkg_QSickRage_SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
