### ISSUE TITLE
[APP SUBMITTED]: Loaded module _usr_local_sickbeard_custom_var_SickBeard_gui_slick_views_home_mako not found in sys.modules

### ISSUE THREAD

**Issue by Zzaap** [SiCKRAGETV/sickrage-issues#2781]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 18:49:44) [GCC 4.6.4]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@2e08ee65e83f74f9958d9305b697ad27c0820cc5
Link to Log: https://gist.github.com/61a83ad0a93aa2f1bd7f
### ERROR
```
Thread-14 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 718, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 113, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _usr_local_sickbeard_custom_var_SickBeard_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by WebSpider** [comment]
Please stop SR, clean cache/mako and restart SR

**Comment by Zzaap** [comment]
Thanks, it restarted without error now.

**Comment by mikeo999** [comment]
Error is back.

I did  stop SR, clean cache/mako and restart SR, no Error 
Restart SR again and error is back.

        2015-09-14 08:46:50 Thread-15 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 718, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 113, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _usr_local_sickbeard_custom_var_SickBeard_gui_slick_views_home_mako not found in sys.modules

        2015-09-14 08:46:50 Thread-14 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 718, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 113, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _usr_local_sickbeard_custom_var_SickBeard_gui_slick_views_home_mako not found in sys.modules

**Comment by Zzaap** [comment]
Well i got the same error again too.
For some reasons, when i shutdown SR and start it again, i get no error. But if i click restart i get this error.
I've tried many times, never got an error on shutdown, only with restart.

**Comment by WebSpider** [comment]
This appears to be specific to the SynoCommunity packages. Possible reason: Cache is outside the progdir.

**Comment by flightlevel** [comment]
@Zzaap 
Good find, you're exactly right, it only happens when you restart!
@WebSpider 
Don't think its related to Syno. I can reproduce here on Ubuntu (cache inside SR folder) & QNAP (cache outside)
@miigotu We need the python expert!!!
If you shutdown SR and then start SR no error will appear.
But, if you restart SR you'll get this error. The weird thing is that the error doesn't occur the instant you hit restart. It occurs AFTER SR has completely restarted fully.
Any ideas on how we can narrow down where its coming from.

**Comment by miigotu** [comment]
Actually, I think it is because cache/mako is not in pythonpath, for it to reload the compiled templates.
Clearing the cache/mako wont solve this issue.

I/We need to figure out how to get the cache location and template lookup working better. Until then it cannot be fixed (unless maybe adding cache/mako in pythonpath with `sys.path.insert(1, os.path.join(sickbeard.CACHE_DIR, 'mako'))` works)

**Comment by fernandog** [comment]
strange is that this error not always happen. I can load page multiple times and don't get error. but sometimes in the second load it happens.

**Comment by fernandog** [comment]
@Zzaap @mikeo999 do you still have this issue? I didn't see this error anymore

**Comment by miigotu** [comment]
It happens after update, it is a non fatal error that a clearing of cache/mako fixes. When we find a fix it will immediately get fixed. No need for any open issues related to it since the issue that opens depends on the path.

**Comment by Peke** [comment]
Is theer anything taht we can test. I/ve also found that if you delere mako folder from backup than all works.  And after some tests I also found that Using QSickRage also works best especially as on first start you can easily switch to Dev fork and than update.

**Comment by Peke** [comment]
@miigotu 
I noticed one strange thing in compat.py that PY version is detected as Python 3.3.x and Most of us based on logs have Python 2.7.x so if I set it to be detected as py26 than all works

**Comment by OmgImAlexis** [comment]
@Peke we're trying to move to Python 3+, I'd suggest you update if you're still on an older version.

**Comment by Peke** [comment]
QNAP do not have Python 3.x and all QNAP Packages including QSickRage have Python 2.7, Also I see same from most of logs related to this mako issue eg. lib/mako/compat.py", line 66
