### ISSUE TITLE
error everytime Sickrage starts

### ISSUE THREAD

**Issue by BenjV** [SiCKRAGETV/sickrage-issues#2790]
SR Version:  BRANCH: (master) / COMMIT: (7694b70047796dc0c9c812300a090f78a4240f46)  
Operating system Linux (Synology DSM 5.2)
Python version 2.7.10

Everytime Sickrage starts it give this error:

```
  2015-09-13 11:04:00 Thread-13 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 718, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 113, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/usr/local/sickrage/var/SickRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _usr_local_sickrage_var_SickRage_gui_slick_views_home_mako not found in sys.modules

        2015-09-13 11:04:00 Thread-15 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 718, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 113, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/usr/local/sickrage/var/SickRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _usr_local_sickrage_var_SickRage_gui_slick_views_home_mako not found in sys.modules
```

**Comment by flightlevel** [comment]
Have you tried clearing your cache?

-Find the location of your cache folder by going to Config -> Help & Info in SickRage
-STOP SickRage and give it a chance to shutdown
-Delete all the folders in the cache folder except images folder
-Start SR

Let us know the result

**Comment by BenjV** [comment]
I have done a you suggested and for now the error is gone.

Strangely it created a second cache directory with the name:
/usr/local/sickrage/var/cache-20150610_093026
In there are the folders 
sessions and cheetah

**Comment by WebSpider** [comment]
Cheetah? 
Are you sure you're running a recent version and are not restoring a very old backup?

Cheetah has been removed from SR over a month ago

-----Original Message-----

**Comment by BenjV** [comment]
I am running the latest version,
See my first post.

In the mean time the sessions directory is disappeared but can now be found in the normal cache folder.
In the strange cache folder there are three pyton files to b e found

The directory is:
/usr/local/sickrage/var/cache-20150610_093026/cheetah/

The files are:
_usr_local_sickrage_var_SickRage_gui_slick_interfaces_default_config_backuprestore_tmpl.py
_usr_local_sickrage_var_SickRage_gui_slick_interfaces_default_home_tmpl.py
_usr_local_sickrage_var_SickRage_gui_slick_interfaces_default_restart_tmpl.py

**Comment by neoatomic** [comment]
Got the feeling that this error is only occurring on the Synology. (got the same.) 
(Might be related to the folder structure, although not sure, can seem to find anything...)

**Comment by OmgImAlexis** [comment]
There's no way you're running the latest master if you're seeing anything about cheetah including files ending in tmpl.py. Something's not right with your install.

Also when you see a cache with a date appended to it that means it's an old one that's been backed up after an update. The current cache is the `cache` one, not `cache-20150610_093026`.

**Comment by flightlevel** [comment]
@BenjV 
That cache folder /usr/local/sickrage/var/cache-20150610_093026 wasn't just created now.
Its from the 10th June 2015, safe to delete.
@neoatomic 
I'm getting that error after an update on both Ubuntu & QNAP, seen a few windows users as well, so don't think its just synology. Be interesting to see if the recent update fixes it ( @WebSpider has made the mako cache folder delete after an update)

**Comment by BenjV** [comment]
I have deleted the folder  /usr/local/sickrage/var/cache-20150610_093026
After that I did a shutdown and started again.
Now the error is gone, so somehow Sickrage used this old cache folder.
I also saw that in that old cache folder sometimes al subfolder named sessios appeared (a new one).
