### ISSUE TITLE
[APP SUBMITTED]: Loaded module _usr_local_sickrage_var_SickRage_gui_slick_views_home_mako not found in sys.modules

### ISSUE THREAD

**Issue by Vodka2014** [SiCKRAGETV/sickrage-issues#2794]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@7694b70047796dc0c9c812300a090f78a4240f46
Link to Log: https://gist.github.com/ca6f73f1873813066838
### ERROR
```
Thread-15 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume5/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/volume5/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 718, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/volume5/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 113, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/usr/local/sickrage/var/SickRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _usr_local_sickrage_var_SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by BenjV** [comment]
Same as issue #2790

**Comment by Vodka2014** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@f7d55c141f2001dadbedb8d699513bfc2c51a667
No Log available with ERRORS: 
### ERROR
```
Thread-14 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume5/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 274, in async_call
    result = function(**kwargs)
  File "/volume5/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 681, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/volume5/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 115, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/usr/local/sickrage/var/SickRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _usr_local_sickrage_var_SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by sverleysen** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5391476827cf369a2d16a4e7ee8128f47a75f74c
Link to Log: https://gist.github.com/51a273a64f21c56bc339
### ERROR
```
Thread-58 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 274, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 681, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 115, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/usr/local/sickrage/var/SickRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _usr_local_sickrage_var_SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by elRadix** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@f913285d1decce196c6054c43507582fb2a2a7ee
Link to Log: https://gist.github.com/d30755e69a84418342fc
### ERROR
```
Thread-59 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 275, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 682, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/usr/local/sickrage/var/SickRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _usr_local_sickrage_var_SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
