### ISSUE TITLE
Recurring 'webui callback'  and mako import error...

### ISSUE THREAD

**Issue by richbutler1** [SiCKRAGETV/sickrage-issues#2807]
Here is the error in the log:
2015-09-14 08:01:58 Thread-33 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 718, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 113, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module C__SickRage_gui_slick_views_home_mako not found in sys.modules

**Comment by miigotu** [comment]
Search issues before opening issues. This has been reported a million times,  thanks.
