### ISSUE TITLE
Multiple errors in webserve.py

### ISSUE THREAD

**Issue by Drempelaar** [SiCKRAGETV/sickrage-issues#2824]
BRANCH: (master) / COMMIT: (7694b70047796dc0c9c812300a090f78a4240f46) 
Python: 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]

```
2015-09-15 19:15:50 Thread-15 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 2230, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "/opt/sickrage/sickbeard/processTV.py", line 251, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/opt/sickrage/sickbeard/processTV.py", line 490, in process_media
    result.result = processor.process()
  File "/opt/sickrage/sickbeard/postProcessor.py", line 1084, in process
    notifiers.notify_download(ep_obj._format_pattern('%SN - %Sx%0E - %EN - %QN'))
  File "/opt/sickrage/sickbeard/notifiers/__init__.py", line 97, in notify_download
    n.notify_download(ep_name)
  File "/opt/sickrage/sickbeard/notifiers/prowl.py", line 49, in notify_download
    message=ep_name)
  File "/opt/sickrage/sickbeard/notifiers/prowl.py", line 94, in _sendProwl
    response = http_handler.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 379, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

        2015-09-15 18:19:04 Thread-25 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 718, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/opt/sickrage/sickbeard/webserve.py", line 113, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/opt/sickrage/lib/mako/template.py", line 328, in __init__
    self.callable_ = self.module.render_body
AttributeError: 'module' object has no attribute 'render_body'

        2015-09-15 18:19:04 Thread-59 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 718, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/opt/sickrage/sickbeard/webserve.py", line 113, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/opt/sickrage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/opt/sickrage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/opt/sickrage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _opt_sickrage_gui_slick_views_home_mako not found in sys.modules
```

**Comment by flightlevel** [comment]
Refer issue https://github.com/SiCKRAGETV/sickrage-issues/issues/2781
Clear the error, it shouldn't be causing you any actual problems?
