### ISSUE TITLE
[Resolved] Not able to access Show After failure to add

### ISSUE THREAD

**Issue by wezzlewoo** [SiCKRAGETV/sickrage-issues#2836]
So I attempted to load in The Daily Show, and somewhere in the process of updating all of the information SickRage bombed out on me so I restarted.

My issue now is that when attempting to access this show I get the following error  whenever I try to access the show for a rescan or removal.
```javascript
Traceback (most recent call last):
  File "/root/.********/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/root/.********/sickbeard/webserve.py", line 1301, in displayShow
    title=showObj.name
  File "/root/.********/sickbeard/webserve.py", line 163, in render
    return super(PageTemplate, self).render(*args, **kwargs)
  File "/root/.********/lib/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/root/.********/lib/mako/runtime.py", line 804, in _render
    return context._pop_buffer().getvalue()
  File "/root/.********/lib/mako/util.py", line 145, in getvalue
    return self.delim.join(self.data)
MemoryError
```

**Comment by wezzlewoo** [comment]
Want to add that when I issue /home/updateShow?show=71256&force=1 it also fails out.

**Comment by flightlevel** [comment]
@wezzlewoo 
Have you tried restarting your computer/NAS?

I'd also try clearing cache

-Find the location of your cache folder by going to Config -> Help & Info in SickRage
-STOP SickRage and give it a chance to shutdown
-Delete all the folders in the cache folder except images folder
-Start SR

**Comment by wezzlewoo** [comment]
Sorry for the latent response on this. I was sent out of town for work and didn't have time to mess with it.

I've tried everything suggested above and I've still got a broken entry for the Daily Show

http://sickrage/home/displayShow?show=71256

Still results in the same error.

```javascript
2015-09-23 15:23:13 Thread-26 :: Failed doing webui callback: Traceback (most recent call last):
  File "/root/.sickrage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/root/.sickrage/sickbeard/webserve.py", line 1301, in displayShow
    title=showObj.name
  File "/root/.sickrage/sickbeard/webserve.py", line 163, in render
    return super(PageTemplate, self).render(*args, **kwargs)
  File "/root/.sickrage/lib/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/root/.sickrage/lib/mako/runtime.py", line 804, in _render
    return context._pop_buffer().getvalue()
  File "/root/.sickrage/lib/mako/util.py", line 145, in getvalue
    return self.delim.join(self.data)
MemoryError
```

**Comment by wezzlewoo** [comment]
Is there a way to remove a show ID from my SickRage instance?
