### ISSUE TITLE
Error When Setting Status of Episodes: ValueError: invalid literal for int() with base 10: 'undefined'

### ISSUE THREAD

**Issue by twayz** [SiCKRAGETV/sickrage-issues#285]
Here is an error I'm getting when trying to set the status of snatched episodes as downloaded.
SR Version:	BRANCH: (develop) / COMMIT: (8b84e4f4bc6cdebdc605438e9e75d15f1133d65e) 
```
Error
invalid literal for int() with base 10: 'undefined'

Traceback
Traceback (most recent call last): 
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/tornado/web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback)) 
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/tornado/stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs) 
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/tornado/concurrent.py", line 226, in lambda future: callback(future.result())) 
File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result() 
File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "/usr/local/sickbeard-custom/var/SickBeard/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 230, in async_call result = function(**kwargs) 
File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1548, in setStatus if not statusStrings.has_key(int(status)): 
ValueError: invalid literal for int() with base 10: 'undefined' 
```

**Comment by iculookn** [comment]
Hi, not sure if this is captured in the fix, but also happens when trying to change an episode from Snactched to Wanted.

Thanks

**Comment by markheloking** [comment]
It is just during the changing of the status of an episode, not matter the current status.

**Comment by brando56894** [comment]
Still getting this issue with the dev branch

**Comment by oceloti** [comment]
@brando56894 the pull request that fixes the issue has not been accepted as yet. Therefore the bug still exists, including in Develop.

**Comment by markheloking** [comment]
I temporarily switched back to master: the problem doesn't occur there. We just have to wait for @echel0n to return from the holidays to accept all the pull requests (since he didn't give anyone else write access since the debacle from last time)

**Comment by markheloking** [comment]
Closing this issue as it should be fixed with all the new merges. Please report back if the issue persists.
