### ISSUE TITLE
Error with manual backlog

### ISSUE THREAD

**Issue by AdeHub** [SiCKRAGETV/sickrage-issues#2855]
```
SR Version:	BRANCH: (master) / COMMIT: (b7edb8a61473b140f002bea11174af47ab738bbb) 
Python Version:	2.7.9
OS: OS X Safari
```
Marked an episode as wanted, get the ```Sending backlog...``` message but then nothing, following errors in Safari:

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (jquery.qtip.min.js.map, line 0)
http://localhost:8083/js/lib/jquery.qtip.min.js.map
Traceback (most recent call last):
  File "/Applications/SickRage/tornado/web.py", line 1348, in _execute
    result = yield result
  File "/Applications/SickRage/tornado/gen.py", line 807, in run
    value = future.result()
  File "/Applications/SickRage/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "/Applications/SickRage/tornado/gen.py", line 212, in wrapper
    yielded = next(result)
  File "/Applications/SickRage/tornado/web.py", line 2126, in get
    self.root, absolute_path)
  File "/Applications/SickRage/tornado/web.py", line 2305, in validate_absolute_path
    raise HTTPError(404)
HTTPError: HTTP 404: Not Found
```
Happens with every show

**Comment by miigotu** [comment]
Clear your browser cache.

**Comment by AdeHub** [comment]
Thanks
