### ISSUE TITLE
Errors when Sickrages starts

### ISSUE THREAD

**Issue by BenjV** [SiCKRAGETV/sickrage-issues#2861]
BRANCH: (master) / COMMIT: (29105fd42b203393cc2393d683a3d11b74a0c752) 
System Synology DSM 5.2 (Linux) ARM processor
Python version 2.7.10

Just updated to the latest versie of Sickrage and I am still getting the error messages listed below.

        2015-09-19 12:58:32 Thread-13 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 679, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 113, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/usr/local/sickrage/var/SickRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _usr_local_sickrage_var_SickRage_gui_slick_views_home_mako not found in sys.modules

        2015-09-19 12:58:32 Thread-18 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 272, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 679, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 113, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/usr/local/sickrage/var/SickRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _usr_local_sickrage_var_SickRage_gui_slick_views_home_mako not found in sys.modules

**Comment by ISISNordeen** [comment]
I also get errors on latest build.
SR Version: 	BRANCH: (master) / COMMIT: (29105fd42b203393cc2393d683a3d11b74a0c752) 
Python Version:	2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
Windows 7 64-bit

https://gist.github.com/7bd2db298e43a68f106f.git
