### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'action'

### ISSUE THREAD

**Issue by donslice** [SiCKRAGETV/sickrage-issues#2872]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-43-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@44835360ea335b80bf74ff71c43dde0f4e486a56
Link to Log: https://gist.github.com/25f8a66760adf195a387
### ERROR
```
Thread-34 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1497, in deleteShow
    error, show = Show.delete(show, full)
  File "/opt/sickrage/sickrage/show/Show.py", line 47, in delete
    showQueueScheduler.action.removeShow(show, bool(remove_files))
AttributeError: 'NoneType' object has no attribute 'action'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by donslice** [comment]
Thank you for making it easy to submit errors!

**Comment by meffect** [comment]
I am getting this now. I get it when I try and delete a show. Ubuntu Server 

```
2015-09-20 00:01:26 Thread-31 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/MyUserName/.sickrage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/home/MyUserName/.sickrage/sickbeard/webserve.py", line 1497, in deleteShow
    error, show = Show.delete(show, full)
  File "/home/MyUserName/.sickrage/sickrage/show/Show.py", line 47, in delete
    showQueueScheduler.action.removeShow(show, bool(remove_files))
AttributeError: 'NoneType' object has no attribute 'action'
```

```
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
```

**Comment by MGaetan89** [comment]
@miigotu The code is the same as before my refactoring. Do you know what can cause `showQueueScheduler` to be `None`?

**Comment by miigotu** [comment]
Has this been confirmed by more than one user?

**Comment by MGaetan89** [comment]
Well, @donslice and @meffect in this issue have reported it.

**Comment by miigotu** [comment]
Im not sure off the top of my head I see nothing wrong.

**Comment by meffect** [comment]
tailing the log file while I click 'Yes' on the 'Remove Show' modal

```
MyUserName@vm-upvr:~/.sickrage/Logs$ tail -f sickrage.log
2015-09-20 00:58:00 DEBUG    POSTPROCESSER :: Starting new thread: POSTPROCESSER
2015-09-20 00:58:00 DEBUG    POSTPROCESSER :: Processing folder /diskstation/data/download/sick_beard
2015-09-20 00:58:00 DEBUG    POSTPROCESSER :: TV_DOWNLOAD_DIR: /diskstation/data/download/sick_beard
2015-09-20 00:58:00 INFO     POSTPROCESSER :: PostProcessing Path: /diskstation/data/download/sick_beard
2015-09-20 00:58:00 DEBUG    POSTPROCESSER :: PostProcessing Dirs: []
2015-09-20 00:58:00 DEBUG    POSTPROCESSER :: PostProcessing Files: []
2015-09-20 00:58:00 DEBUG    POSTPROCESSER :: PostProcessing VideoFiles: []
2015-09-20 00:58:00 DEBUG    POSTPROCESSER :: PostProcessing RarContent: []
2015-09-20 00:58:00 DEBUG    POSTPROCESSER :: PostProcessing VideoInRar: []
2015-09-20 00:58:00 INFO     POSTPROCESSER :: Processing completed
2015-09-20 01:04:21 ERROR    Thread-16 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/***/.sickrage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/home/***/.sickrage/sickbeard/webserve.py", line 1497, in deleteShow
    error, show = Show.delete(show, full)
  File "/home/***/.sickrage/sickrage/show/Show.py", line 47, in delete
    showQueueScheduler.action.removeShow(show, bool(remove_files))
AttributeError: 'NoneType' object has no attribute 'action'
Traceback (most recent call last):
  File "/home/***/.sickrage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/home/***/.sickrage/sickbeard/webserve.py", line 1497, in deleteShow
    error, show = Show.delete(show, full)
  File "/home/***/.sickrage/sickrage/show/Show.py", line 47, in delete
    showQueueScheduler.action.removeShow(show, bool(remove_files))
AttributeError: 'NoneType' object has no attribute 'action'
2015-09-20 01:04:21 DEBUG    TORNADO :: Failed doing webui request "deleteShow": Traceback (most recent call last):
  File "/home/***/.sickrage/sickbeard/webserve.py", line 258, in get
    results = yield self.async_call(method)
  File "/home/***/.sickrage/tornado/gen.py", line 807, in run
    value = future.result()
  File "/home/***/.sickrage/lib/concurrent/futures/_base.py", line 400, in result
    return self.__get_result()
  File "/home/***/.sickrage/lib/concurrent/futures/_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "/home/***/.sickrage/lib/concurrent/futures/_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "/home/***/.sickrage/lib/concurrent/futures/thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/***/.sickrage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/home/***/.sickrage/sickbeard/webserve.py", line 1497, in deleteShow
    error, show = Show.delete(show, full)
  File "/home/***/.sickrage/sickrage/show/Show.py", line 47, in delete
    showQueueScheduler.action.removeShow(show, bool(remove_files))
AttributeError: 'NoneType' object has no attribute 'action'
```

**Comment by miigotu** [comment]
Ok, @MGaetan89 you should remove that import, and call it as `sickbeard.showQueueScheduler.action.whatever`, because when it is imported (at the start of the application) it is before the threads are started and the scheduler has not been initialized yet. Using the fully qualified call will(should) always ensure it is the current value.

**Comment by MGaetan89** [comment]
Ok, I did not know that. I will fix that and check that I did not do the same mistake elsewhere.

**Comment by miigotu** [comment]
@meffect @donslice can you guys check develop and verify that it is fixed?

**Comment by meffect** [comment]
Yes https://github.com/SiCKRAGETV/SickRage/commit/5af583d18af328495edb9c23bc749126fcf34f10 fixed it. I can delete shows without error 

These are the steps I performed to test if the commit changes fixed the issue

```
MyUserName@vm-upvr:~/.sickrage$ sudo service sickbeard stop
Stopping SickBeard
MyUserName@vm-upvr:~/.sickrage$
```

```
MyUserName@vm-upvr:~/.sickrage$ git remote add upstream https://github.com/SiCKRAGETV/SickRage.git
MyUserName@vm-upvr:~/.sickrage$ git fetch upstream
MyUserName@vm-upvr:~/.sickrage$ git checkout develop
MyUserName@vm-upvr:~/.sickrage$ git branch -u upstream/develop
MyUserName@vm-upvr:~/.sickrage$ git reset --hard upstream/develop
MyUserName@vm-upvr:~/.sickrage$ git pull
```

```
MyUserName@vm-upvr:~/.sickrage$ git checkout 5af583d18af328495edb9c23bc749126fcf34f10
Note: checking out '5af583d18af328495edb9c23bc749126fcf34f10'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 5af583d... Use full name of `showQueueScheduler` to delete a show
MyUserName@vm-upvr:~/.sickrage$ sudo service sickbeard start
Starting SickBeard
MyUserName@vm-upvr:~/.sickrage$

```
MyUserName@vm-upvr:~/.sickrage$ git rev-parse HEAD
5af583d18af328495edb9c23bc749126fcf34f10
MyUserName@vm-upvr:~/.sickrage$
```

```
MyUserName@vm-upvr:~/.sickrage$ sudo service sickbeard start
Starting SickBeard
MyUserName@vm-upvr:~/.sickrage$
```

(deleted a show and it was successful)

**Comment by donslice** [comment]
Apologies for the late reply. It was 2:00 am Eastern when I submitted the error.

I can confirm this is fixed for me as well.
