### ISSUE TITLE
Updating to Commit#: 425ae078c84207b36832eb98bf0bab581a5eb38b SickRage wont run

### ISSUE THREAD

**Issue by karl0ss** [SiCKRAGETV/sickrage-issues#2883]
I have just updated to the latest commit and now my sickrage won't run, Im on a windows 2012 server box and this is the error -

13:39:28 INFO::MAIN :: Checking for shows with tvrage id's, since tvrage is gone
Traceback (most recent call last):
  File "F:\Downloaders\SickRage\SickBeard.py", line 555, in <module>
    SickRage().start()
  File "F:\Downloaders\SickRage\SickBeard.py", line 324, in start
    self.fix_clients_nonsense()
  File "F:\Downloaders\SickRage\SickBeard.py", line 142, in fix_clients_nonsense
    filename = ek(os.path.join, sickbeard.PROG_DIR, file)
  File "F:\Downloaders\SickRage\sickrage\helper\encoding.py", line 37, in ek
    result = function(*args, **kwargs)
  File "C:\Python27\lib\ntpath.py", line 73, in join
    elif isabs(b):
  File "C:\Python27\lib\ntpath.py", line 57, in isabs
    s = splitdrive(s)[1]
  File "C:\Python27\lib\ntpath.py", line 125, in splitdrive
    if p[1:2] == ':':
TypeError: 'type' object is not subscriptable

Press Enter or Esc to close console...

Hope someone can help..

Thanks

**Comment by Drempelaar** [comment]
Here the same problem but with another error

```
Traceback (most recent call last):
  File "SickBeard.py", line 555, in <module>
    SickRage().start()
  File "SickBeard.py", line 324, in start
    self.fix_clients_nonsense()
  File "SickBeard.py", line 142, in fix_clients_nonsense
    filename = ek(os.path.join, sickbeard.PROG_DIR, file)
  File "/opt/sickrage/sickrage/helper/encoding.py", line 39, in ek
    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
  File "/usr/lib/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: type object 'file' has no attribute 'startswith'
```

**Comment by miigotu** [comment]
Please do a manual git pull, and try again, I missed that one zzz

**Comment by Drempelaar** [comment]
solved indeed

**Comment by Ramorous** [comment]
Thanks, solved.

**Comment by karl0ss** [comment]
Fixed my issue, thanks alot guys :)
