### ISSUE TITLE
[APP SUBMITTED]: cannot import name exceptions

### ISSUE THREAD

**Issue by stacimail** [SiCKRAGETV/sickrage-issues#2890]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 21:59:41) [GCC 4.6.4 20130405 (prerelease)]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@484634d14db2072b62e12fa3f3d4efe684ffc66e
Link to Log: https://gist.github.com/173cd8d0fe7a10f75b1b
### ERROR
```
Thread-29 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 274, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 1315, in editShow
    t = PageTemplate(rh=self, file="editShow.mako")
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 115, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/usr/local/sickrage/var/SickRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
  File "/usr/local/sickrage/var/cache/mako/usr/local/sickrage/var/SickRage/gui/slick/views/editShow.mako.py", line 21, in <module>
    from sickbeard import exceptions
ImportError: cannot import name exceptions

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by stacimail** [comment]
issue happens when hitting the "edit" button on a show page...immediately takes me back to the shows listing and logs this error. Using Synology, completely removed SickRage and Git and reinstalled fresh, same error.

**Comment by stacimail** [comment]
appears this may be related to issue #2887, when adding shows the "custom" option does not load the custom quality selection tool for me either. Redirects me to shows listing when attempting to edit one show as user Jeffoz stated in issue #2887

**Comment by stacimail** [comment]
opening another issue per owner request, closing this one.
