### ISSUE TITLE
migration issues from SB

### ISSUE THREAD

**Issue by brianjmurrell** [SiCKRAGETV/sickrage-issues#2925]
I ran into the following issues trying to migrate a sickbeard.db to SickRage:

```
11:02:21 INFO::MAIN :: Backing up database before upgrade
11:02:22 INFO::MAIN :: Proceeding with upgrade
11:02:22 INFO::MAIN :: Adding column last_proper_search to info
11:02:22 INFO::MAIN :: Adding column dvdorder to tvshows
11:02:42 INFO::MAIN :: Backing up database before upgrade
11:02:42 INFO::MAIN :: Proceeding with upgrade
11:02:42 INFO::MAIN :: Converting TV Shows table to Indexer Scheme...
11:02:42 ERROR::MAIN :: DB error: table tv_shows has 22 columns but 23 values were supplied
Traceback (most recent call last):
  File "/net/linux/src/SickRage/sickbeard/db.py", line 201, in action
    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/net/linux/src/SickRage/sickbeard/db.py", line 100, in execute
    return self._execute(query, args)
  File "/net/linux/src/SickRage/sickbeard/db.py", line 79, in _execute
    return self.connection.cursor().execute(query)
OperationalError: table tv_shows has 22 columns but 23 values were supplied
11:02:42 INFO::MAIN :: Backing up database before upgrade
11:02:42 INFO::MAIN :: Proceeding with upgrade
11:02:42 INFO::MAIN :: Converting TV Shows table to Indexer Scheme...
11:02:42 INFO::MAIN :: Removing temp tv show tables left behind from previous updates...
11:02:43 INFO::MAIN :: Backing up database before upgrade
11:02:43 INFO::MAIN :: Proceeding with upgrade
11:02:43 INFO::MAIN :: Converting TV Episodes table to Indexer Scheme...
11:02:44 ERROR::MAIN :: DB error: table tv_episodes has 19 columns but 17 values were supplied
Traceback (most recent call last):
  File "/net/linux/src/SickRage/sickbeard/db.py", line 201, in action
    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/net/linux/src/SickRage/sickbeard/db.py", line 100, in execute
    return self._execute(query, args)
  File "/net/linux/src/SickRage/sickbeard/db.py", line 79, in _execute
    return self.connection.cursor().execute(query)
OperationalError: table tv_episodes has 19 columns but 17 values were supplied
11:02:44 INFO::MAIN :: Backing up database before upgrade
11:02:44 INFO::MAIN :: Proceeding with upgrade
11:02:44 INFO::MAIN :: Converting TV Episodes table to Indexer Scheme...
11:02:44 INFO::MAIN :: Removing temp tv episode tables left behind from previous updates...
11:02:55 INFO::MAIN :: Backing up database before upgrade
11:02:55 INFO::MAIN :: Proceeding with upgrade
11:02:55 INFO::MAIN :: Converting IMDB Info table to Indexer Scheme...
11:02:55 ERROR::MAIN :: DB error: no such table: imdb_info
Traceback (most recent call last):
  File "/net/linux/src/SickRage/sickbeard/db.py", line 201, in action
    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/net/linux/src/SickRage/sickbeard/db.py", line 100, in execute
    return self._execute(query, args)
  File "/net/linux/src/SickRage/sickbeard/db.py", line 79, in _execute
    return self.connection.cursor().execute(query)
OperationalError: no such table: imdb_info
11:02:55 INFO::MAIN :: Backing up database before upgrade
11:02:55 INFO::MAIN :: Proceeding with upgrade
11:02:55 INFO::MAIN :: Converting IMDB Info table to Indexer Scheme...
11:02:55 ERROR::MAIN :: DB error: no such table: imdb_info
Traceback (most recent call last):
  File "/net/linux/src/SickRage/sickbeard/db.py", line 201, in action
    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/net/linux/src/SickRage/sickbeard/db.py", line 100, in execute
    return self._execute(query, args)
  File "/net/linux/src/SickRage/sickbeard/db.py", line 79, in _execute
    return self.connection.cursor().execute(query)
OperationalError: no such table: imdb_info
Traceback (most recent call last):
  File "SickBeard.py", line 555, in <module>
    SickRage().start()
  File "SickBeard.py", line 315, in start
    sickbeard.initialize(consoleLogging=self.consoleLogging)
  File "/net/linux/src/SickRage/sickbeard/__init__.py", line 1295, in initialize
    db.upgradeDatabase(myDB, mainDB.InitialSchema)
  File "/net/linux/src/SickRage/sickbeard/db.py", line 364, in upgradeDatabase
    _processUpgrade(connection, schema)
  File "/net/linux/src/SickRage/sickbeard/db.py", line 419, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/net/linux/src/SickRage/sickbeard/db.py", line 419, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/net/linux/src/SickRage/sickbeard/db.py", line 419, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/net/linux/src/SickRage/sickbeard/db.py", line 419, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/net/linux/src/SickRage/sickbeard/db.py", line 419, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/net/linux/src/SickRage/sickbeard/db.py", line 419, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/net/linux/src/SickRage/sickbeard/db.py", line 419, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/net/linux/src/SickRage/sickbeard/db.py", line 419, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/net/linux/src/SickRage/sickbeard/db.py", line 419, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/net/linux/src/SickRage/sickbeard/db.py", line 419, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/net/linux/src/SickRage/sickbeard/db.py", line 419, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/net/linux/src/SickRage/sickbeard/db.py", line 419, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/net/linux/src/SickRage/sickbeard/db.py", line 419, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/net/linux/src/SickRage/sickbeard/db.py", line 419, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/net/linux/src/SickRage/sickbeard/db.py", line 419, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/net/linux/src/SickRage/sickbeard/db.py", line 404, in _processUpgrade
    connection.close()
AttributeError: 'DBConnection' object has no attribute 'close'
```

In my SB sickbeard.sb I have this schema for those two tables:
```
sqlite> .schema tv_shows
CREATE TABLE tv_shows (show_id INTEGER PRIMARY KEY, location TEXT, show_name TEXT, tvdb_id NUMERIC, network TEXT, genre TEXT, runtime NUMERIC, quality NUMERIC, airs TEXT, status TEXT, flatten_folders NUMERIC, paused NUMERIC, startyear NUMERIC, tvr_id NUMERIC, tvr_name TEXT, air_by_date NUMERIC, lang TEXT, last_update_tvdb NUMERIC, rls_require_words TEXT, rls_ignore_words TEXT, skip_notices NUMERIC);
CREATE UNIQUE INDEX idx_tvdb_id ON tv_shows (tvdb_id);
sqlite> .schema tv_episodes
CREATE TABLE tv_episodes (episode_id INTEGER PRIMARY KEY, showid NUMERIC, tvdbid NUMERIC, name TEXT, season NUMERIC, episode NUMERIC, description TEXT, airdate NUMERIC, hasnfo NUMERIC, hastbn NUMERIC, status NUMERIC, location TEXT, file_size NUMERIC, release_name TEXT);
CREATE INDEX idx_tv_episodes_showid_airdate ON tv_episodes (showid,airdate);
CREATE INDEX idx_showid ON tv_episodes (showid);
sqlite> select * from db_version;
18
```

Any ideas?

**Comment by OmgImAlexis** [comment]
https://github.com/SiCKRAGETV/sickrage-issues#submitting-a-bugissue-ticket

Also we may not be able to really help as SickBeard and SickRage are almost nothing alike now.

**Comment by neoatomic** [comment]
We strongly advice NOT to use the old Sickbeard  Database. Risks for problems is to big...

Not sure if sickbeard supports the creation of meta data for shows, otherwise create the show.nfo files. (or let another app do it) Than Sickrage will recognize the shows imminently. (and import them) 

Also make sure to check the wiki. : https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides

(I recall there is an guide for the migration, but its probbebly outdated.)

**Comment by brianjmurrell** [comment]
Yeah, importing the existing shows using their .nfo files was much easier than I thought it would be.

Cheers!
