### ISSUE TITLE
[APP SUBMITTED]: Loaded module _home_tv__sickrage_gui_slick_views_home_mako not found in sys.modules

### ISSUE THREAD

**Issue by bluezed** [SiCKRAGETV/sickrage-issues#2927]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-63-generic-i686-athlon-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5391476827cf369a2d16a4e7ee8128f47a75f74c
Link to Log: https://gist.github.com/20616c1801766f69bb4c
### ERROR
```
Thread-14 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/tv/.sickrage/sickbeard/webserve.py", line 274, in async_call
    result = function(**kwargs)
  File "/home/tv/.sickrage/sickbeard/webserve.py", line 681, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/home/tv/.sickrage/sickbeard/webserve.py", line 115, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/home/tv/.sickrage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/tv/.sickrage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/home/tv/.sickrage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _home_tv__sickrage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
know issue. keep loading and page will show

**Comment by bluezed** [comment]
#2781
