### ISSUE TITLE
mktime argument out of range

### ISSUE THREAD

**Issue by depisode** [SiCKRAGETV/sickrage-issues#296]
Unsure what to make of this/fix it - this is the error i get (I only have basic python command knowledge)

Error

mktime argument out of range

Traceback
```python
Traceback (most recent call last): 
File "/Applications/SickRage c/tornado/web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback)) 
File "/Applications/SickRage c/tornado/web.py", line 1479, in wrapper result = method(self, *args, **kwargs) 
File "/Applications/SickRage c/sickbeard/webserve.py", line 244, in get self.finish(self._dispatch()) 
File "/Applications/SickRage c/sickbeard/webserve.py", line 237, in _dispatch return func(**args) 
File "/Applications/SickRage c/sickbeard/webserve.py", line 3365, in index return _munge(t) 
File "/Applications/SickRage c/sickbeard/webserve.py", line 576, in _munge return unicode(string).encode('utf-8', 'xmlcharrefreplace') 
File "/Library/Python/2.7/site-packages/Cheetah-2.4.4-py2.7.egg/Cheetah/Template.py", line 1010, in __unicode__ return getattr(self, mainMethName)() 
File "/Applications/SickRage c/cache/cheetah/_Applications_SickRage_c_gui_slick_interfaces_default_home_tmpl.py", line 914, in respond _v = VFN(VFSL([locals()]+SL+[globals(), builtin],"time",True),"mktime",False)(VFN(VFSL([locals()]+SL+[globals(), builtin],"ldatetime",True),"timetuple",False)()) # u'$time.mktime($ldatetime.timetuple())' on line 533, col 135 
OverflowError: mktime argument out of range 
```
Request Info
```python
body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /home/
query_arguments: {}
_start_time: 1419790000.32
headers: {'Accept-Language': 'en-US,en;q=0.8,es;q=0.6', 'Accept-Encoding': 'gzip, deflate, sdch', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36', 'Dnt': '1', 'Host': 'localhost:8081', 'Cookie': 'manage_view=list; wanted_view=list; manage_view2=list; advanced_toggle_checked=1; snatched_view2=list; soon_view2=thumbs; late_view2=list; wanted_view2=list'}
host: localhost:8081
version: HTTP/1.1
arguments: {}
_finish_time: None
query: 
path: /home/
method: GET
remote_ip: 127.0.0.1
```

**Comment by depisode** [comment]
any help here? still getting this issue

**Comment by markheloking** [comment]
@depisode please update all the info as requested in my last post. If you don't follow the issue posting guidelines, we will be forced to close the issue (to prevent clutter in the github issue tracker).

**Comment by fernandog** [comment]
@depisode can you report back otherwise will close this
