### ISSUE TITLE
[APP SUBMITTED]: 'ascii' codec can't encode character u'\xe8' in position 53: ordinal not in range(128)

### ISSUE THREAD

**Issue by elrock** [SiCKRAGETV/sickrage-issues#2962]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.1.6+-armv7l-with-debian-8.2**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@41dfcaeaf855297d6a478355746d6b769ca8b0da
Link to Log: https://gist.github.com/a5ffcad1eec53a42b9d8
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/tv.py", line 1460, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/opt/sickrage/sickbeard/tv.py", line 1438, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/opt/sickrage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/opt/sickrage/lib/subliminal/video.py", line 204, in scan_video
    video.size = os.path.getsize(path)
  File "/usr/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 53: ordinal not in range(128)

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by neoatomic** [comment]
And make sure you have the locale set to utf-8
Special character is the problem here. `Adèle` or just replace it wit a normal `e`
