### ISSUE TITLE
KeyError: None on FINDSUBTITLES

### ISSUE THREAD

**Issue by hackedbellini** [SiCKRAGETV/sickrage-issues#2965]
Getting this traceback on my logs since latest updates:

```
2015-09-25 22:08:56 FINDSUBTITLES :: Traceback (most recent call last):
  File "/home/xbian/apps/sickrage/sickrage/sickbeard/tv.py", line 1460, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/home/xbian/apps/sickrage/sickrage/sickbeard/tv.py", line 1438, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/home/xbian/apps/sickrage/sickrage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/home/xbian/apps/sickrage/sickrage/lib/subliminal/video.py", line 218, in scan_video
    mkv = enzyme.MKV(f)
  File "/home/xbian/apps/sickrage/sickrage/lib/enzyme/mkv.py", line 54, in __init__
    self._parse_seekhead(seek_head, segment, stream, specs)
  File "/home/xbian/apps/sickrage/sickrage/lib/enzyme/mkv.py", line 61, in _parse_seekhead
    element_name = specs[element_id][1]
KeyError: None
```

* Branch: master
* Commit hash: 41dfcaeaf855297d6a478355746d6b769ca8b0da
* Your operating system and python version: Raspbian on a raspberry pi 2. Python 2.7.9
* What you did: Nothing
* What happened: Traceback on the logs
* What you expected: No tracebacks
* Link to a copy/paste of your logfile with clear debug info of the error on GIST: https://paste.debian.net/313524/

**Comment by OmgImAlexis** [comment]
@SiCKRAGETV/moderators

**Comment by Dohnerd** [comment]
Same problem here...

**Comment by WebSpider** [comment]
Please provide all needed info for opening a new issue, such as platform, branch, commit, and a link to the complete debug log

**Comment by hackedbellini** [comment]
@WebSpider information added to the first post

**Comment by medariox** [comment]
@hackedbellini @Dohnerd 
What language(s) are you searching the subtitles for? Subtitle settings? Issues with other shows?
Please give us enough information to be able to reproduce the error.

**Comment by Dohnerd** [comment]
1. Danish
2. Standard settings with all 5 providers added
3. Log says:
     2015-09-26 23:44:21 FINDSUBTITLES :: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/tv.py", line 1460, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/tv.py", line 1438, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/lib/subliminal/video.py", line 204, in scan_video
    video.size = os.path.getsize(path)
  File "/opt/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 98: ordinal not in range(128)

        2015-09-26 22:07:10 FINDSUBTITLES :: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/tv.py", line 1460, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/tv.py", line 1438, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/lib/subliminal/video.py", line 204, in scan_video
    video.size = os.path.getsize(path)
  File "/opt/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 77: ordinal not in range(128)

        2015-09-26 21:15:01 FINDSUBTITLES :: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/tv.py", line 1460, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/tv.py", line 1438, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/lib/subliminal/video.py", line 204, in scan_video
    video.size = os.path.getsize(path)
  File "/opt/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 88: ordinal not in range(128)

        2015-09-26 17:05:29 FINDSUBTITLES :: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/tv.py", line 1460, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/tv.py", line 1438, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/lib/subliminal/video.py", line 203, in scan_video
    video = Video.fromguess(path, guessit.guess_file_info(path))
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/lib/subliminal/video.py", line 65, in fromguess
    return Episode.fromguess(name, guess)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/lib/subliminal/video.py", line 114, in fromguess
    raise ValueError('Insufficient data to process the guess')
ValueError: Insufficient data to process the guess

        2015-09-26 15:47:05 FINDSUBTITLES :: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/tv.py", line 1460, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/tv.py", line 1438, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/lib/subliminal/video.py", line 204, in scan_video
    video.size = os.path.getsize(path)
  File "/opt/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 98: ordinal not in range(128)

        2015-09-26 13:59:12 FINDSUBTITLES :: Not enough services selected. At least 1 service is required to search subtitles in the background
        2015-09-26 12:59:11 FINDSUBTITLES :: Not enough services selected. At least 1 service is required to search subtitles in the background
        2015-09-26 12:53:59 FINDSUBTITLES :: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/tv.py", line 1460, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/tv.py", line 1438, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/lib/subliminal/video.py", line 204, in scan_video
    video.size = os.path.getsize(path)
  File "/opt/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 77: ordinal not in range(128)

        2015-09-26 12:05:16 FINDSUBTITLES :: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/tv.py", line 1460, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/tv.py", line 1438, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/lib/subliminal/video.py", line 204, in scan_video
    video.size = os.path.getsize(path)
  File "/opt/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 88: ordinal not in range(128)

        2015-09-26 07:33:34 FINDSUBTITLES :: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/tv.py", line 1460, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/tv.py", line 1438, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/lib/subliminal/video.py", line 203, in scan_video
    video = Video.fromguess(path, guessit.guess_file_info(path))
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/lib/subliminal/video.py", line 65, in fromguess
    return Episode.fromguess(name, guess)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/lib/subliminal/video.py", line 114, in fromguess
    raise ValueError('Insufficient data to process the guess')
ValueError: Insufficient data to process the guess

        2015-09-26 05:22:37 FINDSUBTITLES :: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/tv.py", line 1460, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/tv.py", line 1438, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/lib/subliminal/video.py", line 204, in scan_video
    video.size = os.path.getsize(path)
  File "/opt/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 98: ordinal not in range(128)

**Comment by miigotu** [comment]
@medariox we need to move as much of that subtitle stuff as we can from TV.py into subtitles.py and combine some if the duplicate code.

**Comment by medariox** [comment]
@Dohnerd 
We seem to have two problems here, both unrelated to OPs 'KeyError: None'.
 ```
ValueError: Insufficient data to process the guess
```
Means that your episode file name is missing some parameters that are required by GuessIt to determine its properties. Make sure that the files have both season and episode number in the name.
Same issue as here: https://github.com/SiCKRAGETV/sickrage-issues/issues/2950#issuecomment-143417245

```
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 98: ordinal not in range(128)
```
Is a whole other story. Seems like some information can't be converted to ASCII, it may be related to the video name or the path. Do you have any special chars in your video file path?
What I would need from you:
- Name of the show, season and episode which gives this error.
- Possibly name of your full path to the video you are processing.
Thank you!

@miigotu 
Yeah, this should be the goal in the long run, as it is really messy right now. The ultimate goal is to upgrade to subliminal 1.0.1 (let me dream...).

**Comment by WebSpider** [comment]
The information that cannot be converted is the filename of the file SR is trying to get the size of, which is strange, since the builtin os.* functions should be unicode-aware, really.

Maybe we're forcing the variable to be string, somewhere, this I will check.

-----Original Message-----

**Comment by Dohnerd** [comment]
No special characters in show paths, and everything was working perfect until update.

I don't know if it is a specific show that gives the error, I can only follow the error log, and its like the one i pasted.

**Comment by medariox** [comment]
@WebSpider Sounds great! Thanks

@Dohnerd 
Yes, we changed a few things in the subtitle recognition - we can't just go back and everyone is happy again, that's not how it works. If I asked you that information it is because I want to reproduce your issue, so that I can debug it. I can't help you with the information you gave me.

**Comment by Dohnerd** [comment]
OK, well got some additional errors now, so I'm having trouble with following shows:

Hawaii Five-0 (can't process and can't refresh subs)
Penny Dreadful (can't refresh subs)
Gotham (can't refresh subs)
Hannibal  (can't refresh subs)
The Flash (can't refresh subs)

Tried deleting Hawaii Five-0 and adding it again (same errors)

        2015-09-27 13:20:25 SHOWQUEUE-ADD :: 164541: Could not refresh subtitles
        2015-09-27 12:15:38 SHOWQUEUE-REFRESH :: 265766: Could not refresh subtitles
        2015-09-27 12:03:13 SHOWQUEUE-REFRESH :: 274431: Could not refresh subtitles
        2015-09-27 11:55:44 FINDSUBTITLES :: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/tv.py", line 1460, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/tv.py", line 1438, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/lib/subliminal/video.py", line 204, in scan_video
    video.size = os.path.getsize(path)
  File "/opt/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 77: ordinal not in range(128)

        2015-09-27 11:03:26 SHOWQUEUE-REFRESH :: 279121: Could not refresh subtitles
        2015-09-27 10:51:29 SHOWQUEUE-REFRESH :: 164541: Could not refresh subtitles
        2015-09-27 10:18:04 FINDSUBTITLES :: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/tv.py", line 1460, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/tv.py", line 1438, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/lib/subliminal/video.py", line 204, in scan_video
    video.size = os.path.getsize(path)
  File "/opt/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 88: ordinal not in range(128)

        2015-09-27 10:03:09 SHOWQUEUE-REFRESH :: 259063: Could not refresh subtitles

When trying to manual process Hawaii Five-0:

Processing folder /share/Multimedia/Downloaded/done
TV_DOWNLOAD_DIR: /share/Multimedia/Downloaded/done
PostProcessing Path: /share/MD0_DATA/Multimedia/Downloaded/done
PostProcessing Dirs: ['.@__thumb']
PostProcessing Files: ['Hawaii.Five-0.2010.S06E01.HDTV.x264-LOL.[VTV].mp4']
PostProcessing VideoFiles: ['Hawaii.Five-0.2010.S06E01.HDTV.x264-LOL.[VTV].mp4']
PostProcessing RarContent: []
PostProcessing VideoInRar: []
Processing /share/MD0_DATA/Multimedia/Downloaded/done/Hawaii.Five-0.2010.S06E01.HDTV.x264-LOL.[VTV].mp4 (None)
This show isn't in your list, you need to add it to SB before post-processing an episode
Processing failed for /share/MD0_DATA/Multimedia/Downloaded/done/Hawaii.Five-0.2010.S06E01.HDTV.x264-LOL.[VTV].mp4: 
Processing folder .@__thumb
Ignoring hidden folder: .@__thumb
Problem(s) during processing, failed the following files/folders: 
[/share/MD0_DATA/Multimedia/Downloaded/done/Hawaii.Five-0.2010.S06E01.HDTV.x264-LOL.[VTV].mp4 : Processing failed: ]
[.@__thumb : Hidden folder]

Hawaii five-0 is added... and was functioning before

**Comment by neoatomic** [comment]
@Dohnerd You are using an outdated package for your QNAP. 
Use this one to make sure the package isn't an issue here.:  
http://apps.qnap.community/11-community/17-qsickrage

**Comment by medariox** [comment]
@Dohnerd 
I'm not having issues with any of the shows you mentioned and Danish subtitles. Sadly can't reproduce any of the errors you have.

**Comment by fernandog** [comment]
@Dohnerd are you using linux ? check if user running SR is using UTF-8 locale (specially LC_ALL). you can see the SR user at localhost:xxxx/config

**Comment by fernandog** [comment]
if you are using windows, before start SR run: `chcp 65001`

**Comment by Dohnerd** [comment]
@fernandog how do i change locale, its set to none atm

**Comment by fernandog** [comment]
@Dohnerd

https://sickrage.tv/forums/forum/help-support/general-support/12825-ensuring-your-locale-s-are-set-properly-to-avoid-unicode-issues

**Comment by Dohnerd** [comment]
Actually allready tried that, it did nothing .... Still none, none

**Comment by fernandog** [comment]
please post the results of 

`locale` in ssh

**Comment by Dohnerd** [comment]
[admin@NASGATE ~]# locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
[admin@NASGATE ~]#

**Comment by fernandog** [comment]
post contents of localhost:xxxx/config

**Comment by Dohnerd** [comment]
Configuration
SR Version:	BRANCH: (master) / COMMIT: (41dfcaeaf855297d6a478355746d6b769ca8b0da) 
SR User:	admin
SR Locale:	(None, None)
SR Config:	/share/MD0_DATA/.qpkg/SickBeard-TVRage/config.ini
SR Database:	/share/MD0_DATA/.qpkg/SickBeard-TVRage/sickbeard.db
SR Cache Dir:	/share/MD0_DATA/.qpkg/SickBeard-TVRage/cache
SR Log Dir:	/share/MD0_DATA/.qpkg/SickBeard-TVRage/Logs
SR Arguments:	['--daemon', '--pidfile', '/tmp/SickBeard-TVRage.pid', '--nolaunch']
Python Version:	2.7.3 (default, Apr 12 2012, 13:08:47) [GCC 4.2.3]
 Homepage	http://www.sickrage.tv/
 WiKi	https://github.com/SiCKRAGETV/sickrage-issues/wiki
 Forums	http://sickrage.tv/forums/
 Source	https://github.com/SiCKRAGETV/SickRage/
 IRChat	#sickrage on irc.freenode.net

**Comment by fernandog** [comment]
@neoatomic any clue why locale is none? do you have this?

**Comment by neoatomic** [comment]
@fernandog Yes, my Syno also shows None, None.
The thing here is that he uses an outdated package that has at least SSL problems. So thats why i commented earlier about that. Wondering if that is part of the problem.

**Comment by Dohnerd** [comment]
But there is no newer package for the ARM ?
The one u linked is for x86

**Comment by fernandog** [comment]
@hackedbellini is another issue. still have that issue?

**Comment by Dohnerd** [comment]
And a really annoying thing right now is that Hawaii Five-0 want be processed from download dir.. no matter what i do it keeps saying that the show isn't added to SR

**Comment by fernandog** [comment]
@Dohnerd don't hijack this issue. open another please. we already changed the discussion about the OP issue

**Comment by brouzz** [comment]
Hi,

Same problem on a Windows 10 X64

2015-09-28 07:32:04 FINDSUBTITLES :: Traceback (most recent call last):
  File "C:\SickRage-master\sickbeard\tv.py", line 1460, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "C:\SickRage-master\sickbeard\tv.py", line 1438, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "C:\SickRage-master\sickbeard\subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "C:\SickRage-master\lib\subliminal\video.py", line 218, in scan_video
    mkv = enzyme.MKV(f)
  File "C:\SickRage-master\lib\enzyme\mkv.py", line 54, in __init__
    self._parse_seekhead(seek_head, segment, stream, specs)
  File "C:\SickRage-master\lib\enzyme\mkv.py", line 61, in _parse_seekhead
    element_name = specs[element_id][1]
KeyError: None

SR Version: 	BRANCH: (master) / COMMIT: (41dfcaeaf855297d6a478355746d6b769ca8b0da)
SR User:	nuc
SR Locale:	('fr_BE', 'cp1252')
SR Config:	C:\SickRage-master\config.ini
SR Database:	C:\SickRage-master\sickbeard.db
SR Cache Dir:	C:\SickRage-master\cache
SR Log Dir:	C:\SickRage-master\Logs
SR Arguments:	[]
Python Version:	2.7.7 (default, Jun 1 2014, 14:21:57) [MSC v.1500 64 bit (AMD64)]

**Comment by Dohnerd** [comment]
Quick question.. is there anyway i can "force" SR to set locale to UTF8, when i dosn't read my locale ?

**Comment by fernandog** [comment]
still not sure is this error an enzyme or subliminal or SR ?

**Comment by Dohnerd** [comment]
Well considering "locale" on the NAS gives correct information, it has to be the way SR retrieves the locale... and if there was a way to "force" SR to the locale settings, i would assume it would solve the problem....

**Comment by hackedbellini** [comment]
@fernandog sorry for not being able to reply sooner. I don't think I have the issue anymore
