### ISSUE TITLE
Match of the Day search

### ISSUE THREAD

**Issue by henryforever14** [SiCKRAGETV/sickrage-issues#2990]
Hi,

It seems that SickRage is having trouble of obtaining both shows "Match of the Day" and "Match of the Day 2". For example, for the show that I am searching (see the following log), it goes by the name "Match of the Day - S51E08 - 26th September 2015 - 720p x264" on kickass. But SickRage is searching for "Match of the Day - 2015x08 - MOTD - 26th September 2015". Is there any way I can manually fix this?
```
2015-09-27 20:52:27 INFO     SEARCHQUEUE-MANUAL-109411 :: [Cpasbien] :: Unable to find a download for: [Match of the Day - 2015x08 - MOTD - 26th September 2015]
2015-09-27 20:52:26 INFO     SEARCHQUEUE-MANUAL-109411 :: [Cpasbien] :: Performing episode search for Match of the Day
2015-09-27 20:52:26 INFO     SEARCHQUEUE-MANUAL-109411 :: [BTDigg] :: No data returned to be parsed!!!
AA
AATypeError: __str__ returned non-string (type Error)
AA    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
AA    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
AA    body=body, headers=headers)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
AA    timeout=timeout
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/adapters.py", line 370, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/cachecontrol/adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/sessions.py", line 476, in get
AA    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "/Users/yimingzhao/TV database/SickRage/sickbeard/helpers.py", line 1621, in getURL
2015-09-27 20:52:26 WARNING  SEARCHQUEUE-MANUAL-109411 :: [BTDigg] :: Traceback (most recent call last):
2015-09-27 20:52:26 WARNING  SEARCHQUEUE-MANUAL-109411 :: [BTDigg] :: Unknown exception in getURL https://api.btdigg.org/api/private-341ada3245790954/s02?q=Match.of.the.Day S2015E08&p=0&order=1 Error: __str__ returned non-string (type Error)
2015-09-27 20:52:26 INFO     SEARCHQUEUE-MANUAL-109411 :: [BTDigg] :: Performing Search: Match.of.the.Day S2015E08
2015-09-27 20:52:26 INFO     SEARCHQUEUE-MANUAL-109411 :: [BTDigg] :: Performing episode search for Match of the Day
2015-09-27 20:52:26 INFO     SEARCHQUEUE-MANUAL-109411 :: [Strike] :: No data returned to be parsed!!!
2015-09-27 20:52:25 INFO     SEARCHQUEUE-MANUAL-109411 :: [Strike] :: Performing Search: Match.of.the.Day S2015E08
2015-09-27 20:52:25 INFO     SEARCHQUEUE-MANUAL-109411 :: [Strike] :: Performing episode search for Match of the Day
AA
AATypeError: __str__ returned non-string (type Error)
AA    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
AA    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
AA    body=body, headers=headers)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
AA    timeout=timeout
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/adapters.py", line 370, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/cachecontrol/adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/sessions.py", line 476, in get
AA    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "/Users/yimingzhao/TV database/SickRage/sickbeard/helpers.py", line 1621, in getURL
2015-09-27 20:52:25 WARNING  SEARCHQUEUE-MANUAL-109411 :: [ThePirateBay] :: Traceback (most recent call last):
2015-09-27 20:52:25 WARNING  SEARCHQUEUE-MANUAL-109411 :: [ThePirateBay] :: Unknown exception in getURL https://thepiratebay.gd/search/Match.of.the.Day%20S2015E08%7C2015x08%20/0/7/200 Error: __str__ returned non-string (type Error)
2015-09-27 20:52:25 INFO     SEARCHQUEUE-MANUAL-109411 :: [ThePirateBay] :: Performing episode search for Match of the Day
2015-09-27 20:52:20 INFO     SEARCHQUEUE-MANUAL-109411 :: [Rarbg] :: Performing episode search for Match of the Day
2015-09-27 20:52:20 INFO     SEARCHQUEUE-MANUAL-109411 :: [showrss] :: Performing episode search for Match of the Day
2015-09-27 20:52:20 INFO     SEARCHQUEUE-MANUAL-109411 :: [KickAssTorrents] :: Performing episode search for Match of the Day
2015-09-27 20:52:13 INFO     SEARCHQUEUE-MANUAL-109411 :: Beginning manual search for: [Match of the Day - 2015x08 - MOTD - 26th September 2015]
```

**Comment by SiCKRAGEB0T** [comment]
Thanks for the issue report! To make sure issues are handled quickly, it helps if all info is there. Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md) and followed all the steps. 

Make the title describe your issue. Having "SR not working" or "I am getting this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the devs don't like you, but because they are on mobile or busy other fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by OmgImAlexis** [comment]
I'm assuming you have "sports mode" enabled for this show?

**Comment by neoatomic** [comment]
@henryforever14 You are running

**Comment by fernandog** [comment]
@miigotu cant we prevent SR from starting if py2.6?

**Comment by miigotu** [comment]
@neoatomic @fernandog that log line is from requests, it doesnt mean he is necessarily running python 2.6.

**Comment by henryforever14** [comment]
@neoatomic Turning on "sports mode" doesn't really help. I tried that already.

**Comment by henryforever14** [comment]
@neoatomic @miigotu I have python 2.7 on my mac. And I am sure that I am running that version

**Comment by neoatomic** [comment]
@henryforever14 There where some improvements made to TPB. Update and see if its solved.

**Comment by henryforever14** [comment]
@neoatomic @miigotu Hi, the problem is still there. I am on 4.0.68 (2015-09-28).

Here is the log:

2015-09-30 09:54:32 INFO     SEARCHQUEUE-MANUAL-109411 :: [Cpasbien] :: Unable to find a download for: [Match of the Day - 2015x08 - MOTD - 26th September 2015]
2015-09-30 09:54:32 INFO     SEARCHQUEUE-MANUAL-109411 :: [Cpasbien] :: Performing episode search for Match of the Day
2015-09-30 09:54:32 INFO     SEARCHQUEUE-MANUAL-109411 :: [BTDigg] :: No data returned to be parsed!!!
AA
AATypeError: __str__ returned non-string (type Error)
AA    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
AA    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
AA    body=body, headers=headers)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
AA    timeout=timeout
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/adapters.py", line 370, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/cachecontrol/adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/sessions.py", line 476, in get
AA    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "/Users/yimingzhao/TV database/SickRage/sickbeard/helpers.py", line 1622, in getURL
2015-09-30 09:54:32 WARNING  SEARCHQUEUE-MANUAL-109411 :: [BTDigg] :: Traceback (most recent call last):
2015-09-30 09:54:32 WARNING  SEARCHQUEUE-MANUAL-109411 :: [BTDigg] :: Unknown exception in getURL https://api.btdigg.org/api/private-341ada3245790954/s02?q=Match.of.the.Day S2015E08&p=0&order=1 Error: __str__ returned non-string (type Error)
2015-09-30 09:54:31 INFO     SEARCHQUEUE-MANUAL-109411 :: [BTDigg] :: Performing Search: Match.of.the.Day S2015E08
2015-09-30 09:54:31 INFO     SEARCHQUEUE-MANUAL-109411 :: [BTDigg] :: Performing episode search for Match of the Day
2015-09-30 09:54:31 INFO     SEARCHQUEUE-MANUAL-109411 :: [Strike] :: No data returned to be parsed!!!
2015-09-30 09:54:30 INFO     SEARCHQUEUE-MANUAL-109411 :: [Strike] :: Performing Search: Match.of.the.Day S2015E08
2015-09-30 09:54:30 INFO     SEARCHQUEUE-MANUAL-109411 :: [Strike] :: Performing episode search for Match of the Day
AA
AATypeError: __str__ returned non-string (type Error)
AA    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
AA    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
AA    body=body, headers=headers)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
AA    timeout=timeout
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/adapters.py", line 370, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/cachecontrol/adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/sessions.py", line 476, in get
AA    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "/Users/yimingzhao/TV database/SickRage/sickbeard/helpers.py", line 1622, in getURL
2015-09-30 09:54:30 WARNING  SEARCHQUEUE-MANUAL-109411 :: [ThePirateBay] :: Traceback (most recent call last):
2015-09-30 09:54:30 WARNING  SEARCHQUEUE-MANUAL-109411 :: [ThePirateBay] :: Unknown exception in getURL https://thepiratebay.gd/s/ Error: __str__ returned non-string (type Error)
2015-09-30 09:54:29 INFO     SEARCHQUEUE-MANUAL-109411 :: [ThePirateBay] :: Performing episode search for Match of the Day
2015-09-30 09:54:28 INFO     SEARCHQUEUE-MANUAL-109411 :: [Rarbg] :: Performing episode search for Match of the Day
2015-09-30 09:54:28 INFO     SEARCHQUEUE-MANUAL-109411 :: [showrss] :: Performing episode search for Match of the Day
2015-09-30 09:54:27 INFO     SEARCHQUEUE-MANUAL-109411 :: [KickAssTorrents] :: Performing episode search for Match of the Day
2015-09-30 09:54:27 INFO     SEARCHQUEUE-MANUAL-109411 :: Beginning manual search for: [Match of the Day - 2015x08 - MOTD - 26th September 2015]

**Comment by miigotu** [comment]
"Website is offline No cached version of this page is available."

**Comment by henryforever14** [comment]
@miigotu weird. I will try later when the website is reachable.

**Comment by henryforever14** [comment]
@neoatomic @miigotu Even with TPB up and running, problem persists. The main problem, in my opinion, is still that sickRage is searching for the wrong name. For example, SickRage searches for "Match of the Day - 2015x08 - MOTD - 26th September 2015", but on kickass torrent, it goes by the name "Match of the Day - S51E08 - 26th September 2015 - 720p x264".

2015-09-30 14:16:16 INFO     SEARCHQUEUE-MANUAL-109411 :: [Cpasbien] :: Unable to find a download for: [Match of the Day - 2015x08 - MOTD - 26th September 2015]
2015-09-30 14:16:16 INFO     SEARCHQUEUE-MANUAL-109411 :: [Cpasbien] :: Performing episode search for Match of the Day
2015-09-30 14:16:16 INFO     SEARCHQUEUE-MANUAL-109411 :: [BTDigg] :: No data returned to be parsed!!!
AA
AATypeError: __str__ returned non-string (type Error)
AA    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
AA    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
AA    body=body, headers=headers)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
AA    timeout=timeout
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/adapters.py", line 370, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/cachecontrol/adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/sessions.py", line 476, in get
AA    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "/Users/yimingzhao/TV database/SickRage/sickbeard/helpers.py", line 1622, in getURL
2015-09-30 14:16:16 WARNING  SEARCHQUEUE-MANUAL-109411 :: [BTDigg] :: Traceback (most recent call last):
2015-09-30 14:16:16 WARNING  SEARCHQUEUE-MANUAL-109411 :: [BTDigg] :: Unknown exception in getURL https://api.btdigg.org/api/private-341ada3245790954/s02?q=Match.of.the.Day S2015E08&p=0&order=1 Error: __str__ returned non-string (type Error)
2015-09-30 14:16:15 INFO     SEARCHQUEUE-MANUAL-109411 :: [BTDigg] :: Performing Search: Match.of.the.Day S2015E08
2015-09-30 14:16:15 INFO     SEARCHQUEUE-MANUAL-109411 :: [BTDigg] :: Performing episode search for Match of the Day
2015-09-30 14:16:15 INFO     SEARCHQUEUE-MANUAL-109411 :: [Strike] :: No data returned to be parsed!!!
2015-09-30 14:16:14 INFO     SEARCHQUEUE-MANUAL-109411 :: [Strike] :: Performing Search: Match.of.the.Day S2015E08
2015-09-30 14:16:14 INFO     SEARCHQUEUE-MANUAL-109411 :: [Strike] :: Performing episode search for Match of the Day
AA
AATypeError: __str__ returned non-string (type Error)
AA    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
AA    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
AA    body=body, headers=headers)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
AA    timeout=timeout
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/adapters.py", line 370, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/cachecontrol/adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/sessions.py", line 476, in get
AA    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "/Users/yimingzhao/TV database/SickRage/sickbeard/helpers.py", line 1622, in getURL
2015-09-30 14:16:14 WARNING  SEARCHQUEUE-MANUAL-109411 :: [ThePirateBay] :: Traceback (most recent call last):
2015-09-30 14:16:14 WARNING  SEARCHQUEUE-MANUAL-109411 :: [ThePirateBay] :: Unknown exception in getURL https://thepiratebay.gd/s/ Error: __str__ returned non-string (type Error)
2015-09-30 14:16:14 INFO     SEARCHQUEUE-MANUAL-109411 :: [ThePirateBay] :: Performing episode search for Match of the Day
2015-09-30 14:16:09 INFO     SEARCHQUEUE-MANUAL-109411 :: [Rarbg] :: Performing episode search for Match of the Day
2015-09-30 14:16:09 INFO     SEARCHQUEUE-MANUAL-109411 :: [showrss] :: Performing episode search for Match of the Day
2015-09-30 14:16:09 INFO     SEARCHQUEUE-MANUAL-109411 :: [KickAssTorrents] :: Performing episode search for Match of the Day
2015-09-30 14:16:01 INFO     SEARCHQUEUE-MANUAL-109411 :: Beginning manual search for: [Match of the Day - 2015x08 - MOTD - 26th September 2015]

**Comment by miigotu** [comment]
1.) we have no info about the commit you are on
2.) we have no info about your OS
3.) the bot is there for a reason.

**Comment by henryforever14** [comment]
@miigotu I am sorry. Here is all the information. 

Commit: 4d37c1352e1a27023ffd520a4da8ab0f024333e6 (master branch)

OS: Mac OS yosemite version 10.10.5

What you did: I ran a manual search for the show "Match of the day" released on 09/26/2015.

What happened: It wasn't getting any result back. 

What you expected: This show is there on, for example, kickass torrent.

Here is the debug log:

2015-09-30 20:33:50 INFO     SEARCHQUEUE-MANUAL-109411 :: [Cpasbien] :: Unable to find a download for: [Match of the Day - 2015x08 - MOTD - 26th September 2015]
2015-09-30 20:33:50 DEBUG    SEARCHQUEUE-MANUAL-109411 :: [Cpasbien] :: formatting pattern: %SN - %Sx%0E - %EN -> Match of the Day - 2015x08 - MOTD - 26th September 2015
2015-09-30 20:33:50 DEBUG    SEARCHQUEUE-MANUAL-109411 :: [Cpasbien] :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
2015-09-30 20:33:50 DEBUG    SEARCHQUEUE-MANUAL-109411 :: [Cpasbien] :: formatting pattern: %SN - %Sx%0E - %EN -> Match of the Day - 2015x08 - MOTD - 26th September 2015
2015-09-30 20:33:50 DEBUG    SEARCHQUEUE-MANUAL-109411 :: [Cpasbien] :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
2015-09-30 20:33:50 DEBUG    SEARCHQUEUE-MANUAL-109411 :: [Cpasbien] :: Match of the Day is not an anime, skiping
2015-09-30 20:33:50 DEBUG    SEARCHQUEUE-MANUAL-109411 :: [Cpasbien] :: Requested getURL http://www.cpasbien.pw/recherche/Match-of-the-Day-2015|09|26|Sep.html returned status code is 503: Service Unavailable
2015-09-30 20:33:50 DEBUG    SEARCHQUEUE-MANUAL-109411 :: [Cpasbien] :: search_strings = [{'Episode': [u'Match.of.the.Day.2015|09|26|Sep']}]
2015-09-30 20:33:50 INFO     SEARCHQUEUE-MANUAL-109411 :: [Cpasbien] :: Performing episode search for Match of the Day
2015-09-30 20:33:50 INFO     SEARCHQUEUE-MANUAL-109411 :: [BTDigg] :: No data returned to be parsed!!!
AA
AATypeError: __str__ returned non-string (type Error)
AA    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
AA    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
AA    body=body, headers=headers)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
AA    timeout=timeout
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/adapters.py", line 370, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/cachecontrol/adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/sessions.py", line 476, in get
AA    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "/Users/yimingzhao/TV database/SickRage/sickbeard/helpers.py", line 1622, in getURL
2015-09-30 20:33:50 WARNING  SEARCHQUEUE-MANUAL-109411 :: [BTDigg] :: Traceback (most recent call last):
2015-09-30 20:33:50 WARNING  SEARCHQUEUE-MANUAL-109411 :: [BTDigg] :: Unknown exception in getURL https://api.btdigg.org/api/private-341ada3245790954/s02?q=Match.of.the.Day S2015E08&p=0&order=1 Error: __str__ returned non-string (type Error)
2015-09-30 20:33:50 INFO     SEARCHQUEUE-MANUAL-109411 :: [BTDigg] :: Performing Search: Match.of.the.Day S2015E08
2015-09-30 20:33:50 DEBUG    SEARCHQUEUE-MANUAL-109411 :: [BTDigg] :: search_strings = [u'Match.of.the.Day S2015E08']
2015-09-30 20:33:50 INFO     SEARCHQUEUE-MANUAL-109411 :: [BTDigg] :: Performing episode search for Match of the Day
2015-09-30 20:33:50 DEBUG    SEARCHQUEUE-MANUAL-109411 :: [Strike] :: Match of the Day is not an anime, skiping
2015-09-30 20:33:50 INFO     SEARCHQUEUE-MANUAL-109411 :: [Strike] :: No data returned to be parsed!!!
2015-09-30 20:33:50 DEBUG    SEARCHQUEUE-MANUAL-109411 :: [Strike] :: Requested getURL https://getstrike.net/api/v2/torrents/search/?category=TV&phrase=Match.of.the.Day S2015E08 returned status code is 404: Not Found
2015-09-30 20:33:50 INFO     SEARCHQUEUE-MANUAL-109411 :: [Strike] :: Performing Search: Match.of.the.Day S2015E08
2015-09-30 20:33:50 DEBUG    SEARCHQUEUE-MANUAL-109411 :: [Strike] :: search_strings = [u'Match.of.the.Day S2015E08']
2015-09-30 20:33:50 INFO     SEARCHQUEUE-MANUAL-109411 :: [Strike] :: Performing episode search for Match of the Day
AA
AATypeError: __str__ returned non-string (type Error)
AA    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
AA    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
AA    body=body, headers=headers)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
AA    timeout=timeout
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/adapters.py", line 370, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/cachecontrol/adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/Users/yimingzhao/TV database/SickRage/lib/requests/sessions.py", line 476, in get
AA    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "/Users/yimingzhao/TV database/SickRage/sickbeard/helpers.py", line 1622, in getURL
2015-09-30 20:33:50 WARNING  SEARCHQUEUE-MANUAL-109411 :: [ThePirateBay] :: Traceback (most recent call last):
2015-09-30 20:33:50 WARNING  SEARCHQUEUE-MANUAL-109411 :: [ThePirateBay] :: Unknown exception in getURL https://thepiratebay.gd/s/ Error: __str__ returned non-string (type Error)
2015-09-30 20:33:50 DEBUG    SEARCHQUEUE-MANUAL-109411 :: [ThePirateBay] :: Search string: Match.of.the.Day 2015|09|26|Sep
2015-09-30 20:33:50 DEBUG    SEARCHQUEUE-MANUAL-109411 :: [ThePirateBay] :: search_strings = [{'Episode': [u'Match.of.the.Day 2015|09|26|Sep']}]
2015-09-30 20:33:50 INFO     SEARCHQUEUE-MANUAL-109411 :: [ThePirateBay] :: Performing episode search for Match of the Day
2015-09-30 20:33:50 DEBUG    SEARCHQUEUE-MANUAL-109411 :: [Rarbg] :: Rarbg no results found.
2015-09-30 20:33:49 DEBUG    SEARCHQUEUE-MANUAL-109411 :: [Rarbg] :: Rarbg search page URL: http://torrentapi.org/pubapi_v2.php?mode=search&app_id=sickrage&search_tvdb=109411&search_string=Match of the Day 2015|09|26|Sep&category=tv&limit=100&format=json&min_seeders=1&sort=seeders
2015-09-30 20:33:49 DEBUG    SEARCHQUEUE-MANUAL-109411 :: [Rarbg] :: search_strings = [{'Episode': [u'Match of the Day 2015|09|26|Sep']}]
2015-09-30 20:33:49 INFO     SEARCHQUEUE-MANUAL-109411 :: [Rarbg] :: Performing episode search for Match of the Day
2015-09-30 20:33:49 INFO     SEARCHQUEUE-MANUAL-109411 :: [showrss] :: Performing episode search for Match of the Day
2015-09-30 20:33:49 DEBUG    SEARCHQUEUE-MANUAL-109411 :: [KickAssTorrents] :: Unable to parse the filename EPL.-.Match.of.the.Day.26.09.2015.SD into a valid show
2015-09-30 20:33:49 DEBUG    SEARCHQUEUE-MANUAL-109411 :: [KickAssTorrents] :: Search string: {'q': u'Match.of.the.Day 2015 09 26|Sep', 'field': 'seeders', 'category': 'tv', 'sorder': 'desc', 'rss': 1}
2015-09-30 20:33:49 DEBUG    SEARCHQUEUE-MANUAL-109411 :: [KickAssTorrents] :: search_strings = [{'Episode': [u'Match.of.the.Day 2015 09 26|Sep']}]
2015-09-30 20:33:49 INFO     SEARCHQUEUE-MANUAL-109411 :: [KickAssTorrents] :: Performing episode search for Match of the Day
2015-09-30 20:33:49 DEBUG    SEARCHQUEUE-MANUAL-109411 :: [TokyoToshokan] :: Last update was too soon, using old cache: 2015-09-30 20:31:40. Updated less then 15 minutes ago
2015-09-30 20:33:49 DEBUG    SEARCHQUEUE-MANUAL-109411 :: [Cpasbien] :: Last update was too soon, using old cache: 2015-09-30 20:31:33. Updated less then 10 minutes ago
2015-09-30 20:33:49 DEBUG    SEARCHQUEUE-MANUAL-109411 :: [NyaaTorrents] :: Last update was too soon, using old cache: 2015-09-30 20:31:40. Updated less then 15 minutes ago
2015-09-30 20:33:49 DEBUG    SEARCHQUEUE-MANUAL-109411 :: [ThePirateBay] :: Last update was too soon, using old cache: 2015-09-30 20:31:35. Updated less then 30 minutes ago
2015-09-30 20:33:49 DEBUG    SEARCHQUEUE-MANUAL-109411 :: [Rarbg] :: Last update was too soon, using old cache: 2015-09-30 20:31:35. Updated less then 5 minutes ago
2015-09-30 20:33:49 DEBUG    SEARCHQUEUE-MANUAL-109411 :: [showrss] :: Last update was too soon, using old cache: 2015-09-30 20:31:35. Updated less then 15 minutes ago
2015-09-30 20:33:49 DEBUG    SEARCHQUEUE-MANUAL-109411 :: [KickAssTorrents] :: Last update was too soon, using old cache: 2015-09-30 20:31:35. Updated less then 20 minutes ago
2015-09-30 20:33:49 DEBUG    SEARCHQUEUE-MANUAL-109411 :: Internal name cache for Match of the Day set to: [ match of the day ]
2015-09-30 20:33:49 DEBUG    SEARCHQUEUE-MANUAL-109411 :: Building internal name cache for Match of the Day
2015-09-30 20:33:49 DEBUG    SEARCHQUEUE-MANUAL-109411 :: No scene exceptions update needed
2015-09-30 20:33:49 INFO     SEARCHQUEUE-MANUAL-109411 :: Beginning manual search for: [Match of the Day - 2015x08 - MOTD - 26th September 2015]
2015-09-30 20:33:49 DEBUG    SEARCHQUEUE-MANUAL-109411 :: formatting pattern: %SN - %Sx%0E - %EN -> Match of the Day - 2015x08 - MOTD - 26th September 2015
2015-09-30 20:33:49 DEBUG    SEARCHQUEUE-MANUAL-109411 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN

**Comment by miigotu** [comment]
Ok thats enough logs in this issue lol.
