### ISSUE TITLE
Problem with subtitles

### ISSUE THREAD

**Issue by 03397** [SiCKRAGETV/sickrage-issues#2997]
I am running f913285d1decce196c6054c43507582fb2a2a7ee version of Sickrage with 2.7 (r27:82500, Aug 21 2010, 07:52:47) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2) and after restart I am getting 
  2015-09-28 12:48:35 FINDSUBTITLES :: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/tv.py", line 1472, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/tv.py", line 1446, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/share/MD0_DATA/.qpkg/SickRage/lib/subliminal/video.py", line 204, in scan_video
    video.size = os.path.getsize(path)
  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
UnicodeEncodeError: 'ascii' codec can't encode character u'\u03c0' in position 98: ordinal not in range(128)

        2015-09-28 12:48:35 FINDSUBTITLES :: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/tv.py", line 1472, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/tv.py", line 1446, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/share/MD0_DATA/.qpkg/SickRage/lib/subliminal/video.py", line 204, in scan_video
    video.size = os.path.getsize(path)
  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 89: ordinal not in range(128)

        2015-09-28 12:48:34 FINDSUBTITLES :: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/tv.py", line 1472, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/tv.py", line 1446, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/share/MD0_DATA/.qpkg/SickRage/lib/subliminal/video.py", line 204, in scan_video
    video.size = os.path.getsize(path)
  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 94: ordinal not in range(128)

        2015-09-28 12:48:34 FINDSUBTITLES :: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/tv.py", line 1472, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/tv.py", line 1446, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/share/MD0_DATA/.qpkg/SickRage/lib/subliminal/video.py", line 204, in scan_video
    video.size = os.path.getsize(path)
  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 81: ordinal not in range(128)

        2015-09-28 12:48:34 FINDSUBTITLES :: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/tv.py", line 1472, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/tv.py", line 1446, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/share/MD0_DATA/.qpkg/SickRage/lib/subliminal/video.py", line 204, in scan_video
    video.size = os.path.getsize(path)
  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 90: ordinal not in range(128)

        2015-09-28 12:48:32 FINDSUBTITLES :: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/tv.py", line 1472, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/tv.py", line 1446, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/share/MD0_DATA/.qpkg/SickRage/lib/subliminal/video.py", line 204, in scan_video
    video.size = os.path.getsize(path)
  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 109: ordinal not in range(128)

        2015-09-28 12:48:32 FINDSUBTITLES :: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/tv.py", line 1472, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/tv.py", line 1446, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/share/MD0_DATA/.qpkg/SickRage/lib/subliminal/video.py", line 204, in scan_video
    video.size = os.path.getsize(path)
  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 84: ordinal not in range(128)

        2015-09-28 12:48:32 FINDSUBTITLES :: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/tv.py", line 1472, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/tv.py", line 1446, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/share/MD0_DATA/.qpkg/SickRage/lib/subliminal/video.py", line 204, in scan_video
    video.size = os.path.getsize(path)
  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 112: ordinal not in range(128)

        2015-09-28 12:48:32 FINDSUBTITLES :: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/tv.py", line 1472, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/tv.py", line 1446, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/share/MD0_DATA/.qpkg/SickRage/lib/subliminal/video.py", line 204, in scan_video
    video.size = os.path.getsize(path)
  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 136: ordinal not in range(128)

        2015-09-28 12:48:32 FINDSUBTITLES :: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/tv.py", line 1472, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/tv.py", line 1446, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/share/MD0_DATA/.qpkg/SickRage/lib/subliminal/video.py", line 204, in scan_video
    video.size = os.path.getsize(path)
  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 136: ordinal not in range(128)
This happens aslo when sickrage tries to download subtitles

**Comment by SiCKRAGEB0T** [comment]
Thanks for the issue report! To make sure issues are handled quickly, it helps if all info is there. Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md) and followed all the steps. 

Make the title describe your issue. Having "SR not working" or "I am getting this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the devs don't like you, but because they are on mobile or busy other fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by OmgImAlexis** [comment]
Please make sure use [gist](https://gist.github.com) for the logs or put them in a [https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting](code block).
