### ISSUE TITLE
[APP SUBMITTED]: <MatchTree: root=.ZiLLA.There's.a.Whole.Slew.of.Ladies.with.Bad.Things.to.Say.About.th> is not in list

### ISSUE THREAD

**Issue by sverleysen** [SiCKRAGETV/sickrage-issues#2998]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@f913285d1decce196c6054c43507582fb2a2a7ee
Link to Log: https://gist.github.com/4e3d76a00531cd87972a
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/tv.py", line 1491, in downloadSubtitles
    foundSubs = subliminal.download_best_subtitles([video], languages=languages, providers=providers, single=not sickbeard.SUBTITLES_MULTI, hearing_impaired=False)
  File "/usr/local/sickrage/var/SickRage/lib/subliminal/api.py", line 88, in download_best_subtitles
    for subtitle, score in sorted([(s, s.compute_score(video)) for s in video_subtitles],
  File "/usr/local/sickrage/var/SickRage/lib/subliminal/subtitle.py", line 131, in compute_score
    initial_matches = self.compute_matches(video)
  File "/usr/local/sickrage/var/SickRage/lib/subliminal/providers/opensubtitles.py", line 62, in compute_matches
    matches |= compute_guess_matches(video, guessit.guess_episode_info(self.movie_release_name + '.mkv'))
  File "/usr/local/sickrage/var/SickRage/lib/guessit/__init__.py", line 370, in guess_episode_info
    return guess_file_info(filename, info=info, options=options, type='episode', **kwargs)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/__init__.py", line 302, in guess_file_info
    result.append(_guess_filename(filename, options, **kwargs))
  File "/usr/local/sickrage/var/SickRage/lib/guessit/__init__.py", line 114, in _guess_filename
    mtree = _build_filename_mtree(filename, options=options, **kwargs)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/__init__.py", line 127, in _build_filename_mtree
    mtree = IterativeMatcher(filename, options=merged_options, **kwargs)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/matcher.py", line 120, in __init__
    self._process(transformer, False)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/matcher.py", line 138, in _process
    transformer.process(self.match_tree, self.options)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/transfo/guess_release_group.py", line 223, in process
    GuessFinder(self.guess_release_group, None, self.log, options).process_nodes(mtree.unidentified_leaves())
  File "/usr/local/sickrage/var/SickRage/lib/guessit/matcher.py", line 227, in process_nodes
    self.process_node(node)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/matcher.py", line 286, in process_node
    self.process_node(node, partial_span=relative_span, skip_nodes=next_skip_nodes)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/matcher.py", line 241, in process_node
    matcher_result = self.guess_func(string, node, self.options)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/transfo/guess_release_group.py", line 175, in guess_release_group
    if self.validate_node(leaf, node, True):
  File "/usr/local/sickrage/var/SickRage/lib/guessit/transfo/guess_release_group.py", line 143, in validate_node
    if not self.validate_next_leaves(node):
  File "/usr/local/sickrage/var/SickRage/lib/guessit/transfo/guess_release_group.py", line 126, in validate_next_leaves
    next_leaf = node.root.next_leaf(node)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/matchtree.py", line 318, in next_leaf
    return self._other_leaf(leaf, +1)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/matchtree.py", line 322, in _other_leaf
    index = leaves.index(leaf) + offset
ValueError: <MatchTree: root=.ZiLLA.There's.a.Whole.Slew.of.Ladies.with.Bad.Things.to.Say.About.th> is not in list

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
Thanks for the issue report! To make sure issues are handled quickly, it helps if all info is there. Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md) and followed all the steps. 

Make the title describe your issue. Having "SR not working" or "I am getting this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the devs don't like you, but because they are on mobile or busy other fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
@sverleysen There was a fix submitted to master, update and see if it is fixed.

**Comment by sverleysen** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4d37c1352e1a27023ffd520a4da8ab0f024333e6
No Log available with ERRORS: 
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/tv.py", line 1491, in downloadSubtitles
    foundSubs = subliminal.download_best_subtitles([video], languages=languages, providers=providers, single=not sickbeard.SUBTITLES_MULTI, hearing_impaired=False)
  File "/usr/local/sickrage/var/SickRage/lib/subliminal/api.py", line 88, in download_best_subtitles
    for subtitle, score in sorted([(s, s.compute_score(video)) for s in video_subtitles],
  File "/usr/local/sickrage/var/SickRage/lib/subliminal/subtitle.py", line 131, in compute_score
    initial_matches = self.compute_matches(video)
  File "/usr/local/sickrage/var/SickRage/lib/subliminal/providers/opensubtitles.py", line 62, in compute_matches
    matches |= compute_guess_matches(video, guessit.guess_episode_info(self.movie_release_name + '.mkv'))
  File "/usr/local/sickrage/var/SickRage/lib/guessit/__init__.py", line 370, in guess_episode_info
    return guess_file_info(filename, info=info, options=options, type='episode', **kwargs)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/__init__.py", line 302, in guess_file_info
    result.append(_guess_filename(filename, options, **kwargs))
  File "/usr/local/sickrage/var/SickRage/lib/guessit/__init__.py", line 114, in _guess_filename
    mtree = _build_filename_mtree(filename, options=options, **kwargs)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/__init__.py", line 127, in _build_filename_mtree
    mtree = IterativeMatcher(filename, options=merged_options, **kwargs)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/matcher.py", line 120, in __init__
    self._process(transformer, False)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/matcher.py", line 138, in _process
    transformer.process(self.match_tree, self.options)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/transfo/guess_release_group.py", line 223, in process
    GuessFinder(self.guess_release_group, None, self.log, options).process_nodes(mtree.unidentified_leaves())
  File "/usr/local/sickrage/var/SickRage/lib/guessit/matcher.py", line 227, in process_nodes
    self.process_node(node)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/matcher.py", line 286, in process_node
    self.process_node(node, partial_span=relative_span, skip_nodes=next_skip_nodes)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/matcher.py", line 241, in process_node
    matcher_result = self.guess_func(string, node, self.options)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/transfo/guess_release_group.py", line 175, in guess_release_group
    if self.validate_node(leaf, node, True):
  File "/usr/local/sickrage/var/SickRage/lib/guessit/transfo/guess_release_group.py", line 143, in validate_node
    if not self.validate_next_leaves(node):
  File "/usr/local/sickrage/var/SickRage/lib/guessit/transfo/guess_release_group.py", line 126, in validate_next_leaves
    next_leaf = node.root.next_leaf(node)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/matchtree.py", line 318, in next_leaf
    return self._other_leaf(leaf, +1)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/matchtree.py", line 322, in _other_leaf
    index = leaves.index(leaf) + offset
ValueError: <MatchTree: root=.ZiLLA.There's.a.Whole.Slew.of.Ladies.with.Bad.Things.to.Say.About.th> is not in list

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by Inervo** [comment]
I also encounter this issue: #3048
