### ISSUE TITLE
Notifications: email not working anymore.

### ISSUE THREAD

**Issue by AubreyKloppers** [SiCKRAGETV/sickrage-issues#3000]
I get the following error in my errorlog:

*Thread-48 :: Exception generated while sending e-mail: [Errno -2] Name or service not known*

Further on this, when a download is complete and an email needs to send I get the following in my logfile:

*2015-09-28 15:39:41 INFO     POSTPROCESSER :: PostProcessing Path: /media/93aa77f4-b8e5-475e-85c8-0b3c7a648c13/downloads
AA
AAgaierror: [Errno -2] Name or service not known
AA    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
AA  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
AA    return socket.create_connection((port, host), timeout)
AA  File "/usr/lib/python2.7/smtplib.py", line 284, in _get_socket
AA    self.sock = self._get_socket(host, port, self.timeout)
AA  File "/usr/lib/python2.7/smtplib.py", line 309, in connect
AA    (code, msg) = self.connect(host, port)
AA  File "/usr/lib/python2.7/smtplib.py", line 249, in __init__
AA    srv = smtplib.SMTP(host, int(port))
AA  File "/opt/sickbeard/sickbeard/notifiers/emailnotify.py", line 194, in _sendmail
AAgaierror: [Errno -2] Name or service not known
AA    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
AA  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
AA    return socket.create_connection((port, host), timeout)
AA  File "/usr/lib/python2.7/smtplib.py", line 284, in _get_socket
AA    self.sock = self._get_socket(host, port, self.timeout)
AA  File "/usr/lib/python2.7/smtplib.py", line 309, in connect
AA    (code, msg) = self.connect(host, port)
AA  File "/usr/lib/python2.7/smtplib.py", line 249, in __init__
AA    srv = smtplib.SMTP(host, int(port))
AA  File "/opt/sickbeard/sickbeard/notifiers/emailnotify.py", line 194, in _sendmail
AATraceback (most recent call last):
2015-09-28 15:39:00 ERROR    Thread-53 :: Exception generated while sending e-mail: [Errno -2] Name or service not known
AA
AAgaierror: [Errno -2] Name or service not known
AA    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
AA  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
AA    return socket.create_connection((port, host), timeout)
AA  File "/usr/lib/python2.7/smtplib.py", line 284, in _get_socket
AA    self.sock = self._get_socket(host, port, self.timeout)
AA  File "/usr/lib/python2.7/smtplib.py", line 309, in connect
AA    (code, msg) = self.connect(host, port)
AA  File "/usr/lib/python2.7/smtplib.py", line 249, in __init__
AA    srv = smtplib.SMTP(host, int(port))
AA  File "/opt/sickbeard/sickbeard/notifiers/emailnotify.py", line 194, in _sendmail
AAgaierror: [Errno -2] Name or service not known
AA    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
AA  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
AA    return socket.create_connection((port, host), timeout)
AA  File "/usr/lib/python2.7/smtplib.py", line 284, in _get_socket
AA    self.sock = self._get_socket(host, port, self.timeout)
AA  File "/usr/lib/python2.7/smtplib.py", line 309, in connect
AA    (code, msg) = self.connect(host, port)
AA  File "/usr/lib/python2.7/smtplib.py", line 249, in __init__
AA    srv = smtplib.SMTP(host, int(port))
AA  File "/opt/sickbeard/sickbeard/notifiers/emailnotify.py", line 194, in _sendmail
AATraceback (most recent call last):
2015-09-28 15:30:42 ERROR    Thread-49 :: Exception generated while sending e-mail: [Errno -2] Name or service not known*

**Comment by SiCKRAGEB0T** [comment]
Thanks for the issue report! To make sure issues are handled quickly, it helps if all info is there. Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md) and followed all the steps. 

Make the title describe your issue. Having "SR not working" or "I am getting this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the devs don't like you, but because they are on mobile or busy other fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment]
This hasnt worked already for at least 6 months afaik.

**Comment by AubreyKloppers** [comment]
Hi @miigotu 
It actually worked till 20 Sept 2015...

kind regards
cyber7 (aka Aubrey Kloppers)

**Comment by AubreyKloppers** [comment]
More on this:
IT is working on another "test" server...  Everything (except content and network) the same...

**Comment by miigotu** [comment]
Stop sickrage, and try deleting sickrage/sickbeard/notifiers/*.pyc

**Comment by AubreyKloppers** [comment]
Hi @miigotu 
Thank you - it worked!

kind regards
