### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u206f' in position 42: ordinal not in range(128)

### ISSUE THREAD

**Issue by Houwaard** [SiCKRAGETV/sickrage-issues#3001]
Every hour i get an log & error. This is the latest i got
```
        2015-09-28 17:49:20 FINDSUBTITLES :: Traceback (most recent call last):
  File "/usr/share/sickrage/sickbeard/tv.py", line 1472, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/usr/share/sickrage/sickbeard/tv.py", line 1446, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/usr/share/sickrage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/usr/share/sickrage/lib/subliminal/video.py", line 204, in scan_video
    video.size = os.path.getsize(path)
  File "/usr/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
UnicodeEncodeError: 'ascii' codec can't encode character u'\u206f' in position 42: ordinal not in range(128)
```

**Comment by SiCKRAGEB0T** [comment]
Thanks for the issue report! To make sure issues are handled quickly, it helps if all info is there. Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md) and followed all the steps. 

Make the title describe your issue. Having "SR not working" or "I am getting this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the devs don't like you, but because they are on mobile or busy other fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
