### ISSUE TITLE
[APP SUBMITTED]: '_home_raydias_sickrage_gui_slick_views_home_addShows_mako'

### ISSUE THREAD

**Issue by rrd911** [SiCKRAGETV/sickrage-issues#3008]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-28-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@f913285d1decce196c6054c43507582fb2a2a7ee
Link to Log: https://gist.github.com/926a222f854cc38e9ce9
### ERROR
```
Thread-16 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/raydias/sickrage/sickbeard/webserve.py", line 275, in async_call
    result = function(**kwargs)
  File "/home/raydias/sickrage/sickbeard/webserve.py", line 2185, in index
    t = PageTemplate(rh=self, file="home_addShows.mako")
  File "/home/raydias/sickrage/sickbeard/webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/home/raydias/sickrage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/raydias/sickrage/lib/mako/template.py", line 380, in _compile_from_file
    del sys.modules[self.module_id]
KeyError: '_home_raydias_sickrage_gui_slick_views_home_addShows_mako'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
Thanks for the issue report! To make sure issues are handled quickly, it helps if all info is there. Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md) and followed all the steps. 

Make the title describe your issue. Having "SR not working" or "I am getting this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the devs don't like you, but because they are on mobile or busy other fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
