### ISSUE TITLE
[APP SUBMITTED]: 2806227

### ISSUE THREAD

**Issue by squareflapjack** [SiCKRAGETV/sickrage-issues#3017]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.16.0-49-generic-x86_64-with-elementary_OS-0.3.1-freya**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@f913285d1decce196c6054c43507582fb2a2a7ee
No Log available with ERRORS: 
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/tv.py", line 1472, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/opt/sickrage/sickbeard/tv.py", line 1446, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/opt/sickrage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/opt/sickrage/lib/subliminal/video.py", line 218, in scan_video
    mkv = enzyme.MKV(f)
  File "/opt/sickrage/lib/enzyme/mkv.py", line 54, in __init__
    self._parse_seekhead(seek_head, segment, stream, specs)
  File "/opt/sickrage/lib/enzyme/mkv.py", line 61, in _parse_seekhead
    element_name = specs[element_id][1]
KeyError: 2806227

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
Thanks for the issue report! To make sure issues are handled quickly, it helps if all info is there. Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md) and followed all the steps. 

Make the title describe your issue. Having "SR not working" or "I am getting this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the devs don't like you, but because they are on mobile or busy other fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
