### ISSUE TITLE
Cant delete shows

### ISSUE THREAD

**Issue by gielie** [SiCKRAGETV/sickrage-issues#3019]
Branch: master

Commit: (f913285d1decce196c6054c43507582fb2a2a7ee) 

OS: Synology

Python Version: 2.7.10

What I believe went wrong: I cant delete shows

error code:

```
2015-09-29 12:39:00 Thread-42 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 275, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 1499, in deleteShow
    error, show = Show.delete(show, full)
  File "/volume1/@appstore/sickrage/var/SickRage/sickrage/show/Show.py", line 47, in delete
    sickbeard.showQueueScheduler.action.removeShow(show, bool(remove_files))
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/show_queue.py", line 156, in removeShow
    if self._isInQueue(show, ShowQueueActions.REMOVE):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/show_queue.py", line 46, in _isInQueue
    return show.indexerid in [x.show.indexerid for x in self.queue if x.action_id in actions]
TypeError: argument of type 'int' is not iterable
```

**Comment by SiCKRAGEB0T** [comment]
Thanks for the issue report! To make sure issues are handled quickly, it helps if all info is there. Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md) and followed all the steps. 

Make the title describe your issue. Having "SR not working" or "I am getting this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the devs don't like you, but because they are on mobile or busy fixing other bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
Just added a show and removed it. not problems.

Try to shutdown Sickrage, delete your cache/sessions and cache/mako folders. And start Sickrage again.

**Comment by gielie** [comment]
Just did a whole restart on the synology and everything works again, 

case closed
