### ISSUE TITLE
[APP SUBMITTED]: 'ascii' codec can't encode character u'\u016b' in position 95: ordinal not in range(128)

### ISSUE THREAD

**Issue by reisrdok** [SiCKRAGETV/sickrage-issues#3024]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-63-generic-i686-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5aac5803f2e1df3385a5cb19580b8fd6b4eb6191
Link to Log: https://gist.github.com/d029d0c5cf625b8e2491
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/tv.py", line 1472, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/opt/sickrage/sickbeard/tv.py", line 1446, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/opt/sickrage/sickbeard/subtitles.py", line 97, in subtitlesLanguages
    embedded_languages = subliminal.scan_video(video_path, subtitles=False, embedded_subtitles=not sickbeard.EMBEDDED_SUBTITLES_ALL)
  File "/opt/sickrage/lib/subliminal/video.py", line 204, in scan_video
    video.size = os.path.getsize(path)
  File "/usr/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
UnicodeEncodeError: 'ascii' codec can't encode character u'\u016b' in position 95: ordinal not in range(128)

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
Thanks for the issue report! To make sure issues are handled quickly, it helps if all info is there. Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md) and followed all the steps. 

Make the title describe your issue. Having "SR not working" or "I am getting this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the devs don't like you, but because they are on mobile or busy fixing other bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by reisrdok** [comment]
I keep getting hundreds of these in a day. But everything seems to work?

reisrdok@lootserver:~$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=fi_FI.UTF-8
LC_TIME=fi_FI.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=fi_FI.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=fi_FI.UTF-8
LC_NAME=fi_FI.UTF-8
LC_ADDRESS=fi_FI.UTF-8
LC_TELEPHONE=fi_FI.UTF-8
LC_MEASUREMENT=fi_FI.UTF-8
LC_IDENTIFICATION=fi_FI.UTF-8
LC_ALL=

**Comment by reisrdok** [comment]
Tried this, did not help. https://sickrage.tv/forums/forum/help-support/general-support/12825-ensuring-your-locale-s-are-set-properly-to-avoid-unicode-issues

Example episode name that causes this (Hannibal S02E11): Kō No Mono

**Comment by neoatomic** [comment]
@reisrdok There was a fix submitted to master. Update and see if it is fixed.

**Comment by reisrdok** [comment]
Nope. Still error with Hannibal episode.

2015-09-30 15:22:19 Thread-28 :: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/tv.py", line 1472, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/opt/sickrage/sickbeard/tv.py", line 1446, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/opt/sickrage/sickbeard/subtitles.py", line 100, in subtitlesLanguages
    with open(video_path, 'rb') as f:
UnicodeEncodeError: 'ascii' codec can't encode character u'\u014d' in position 60: ordinal not in range(128)

Also, changelog is not updated? Commit seems to be latest (and no subliminal) so i think update worked:

2015-09-30 15:15:03 DEBUG    Thread-19 :: cur_commit = 1c3577ae6df29cad345f64d23647d0a2d8a4e008, newest_commit = 1c3577ae6df29cad345f64d23647d0a2d8a4e008, num_commits_behind = 0, num_commits_ahead = 0

I will recheck everything when I get home in a few hours. Server is behind ISP NAT and Teamviewer is a bit slow today..

**Comment by miigotu** [comment]
Locale: unknown

**Comment by reisrdok** [comment]
See 3. and 4. post. Tried to fix locales with  https://sickrage.tv/forums/forum/help-support/general-support/12825-ensuring-your-locale-s-are-set-properly-to-avoid-unicode-issues, did not work.

Currently locales are:

LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8

**Comment by miigotu** [comment]
locales are per user, is that the local for the SR user?

**Comment by reisrdok** [comment]
Running SR as root because of many kinds of cifs problems. These are root locales. And all users have same locales.

reisrdok@lootserver:~$ ps aux | grep sick
root     19110  1.8  7.4 599544 76776 ?        Sl   15:11   0:36 /usr/bin/python /opt/sickrage/SickBeard.py -q --daemon --nolaunch --pidfile=/var/run/sickrage/sickrage.pid --datadir=/opt/sickrage

**Comment by 03397** [comment]
I have updated to the latest and still have the same errors.
I am starting Sickrage as root

**Comment by 03397** [comment]
After restart
  2015-09-30 16:25:17 FINDSUBTITLES :: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/tv.py", line 1472, in downloadSubtitles
    languages = self.getWantedLanguages();
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/tv.py", line 1446, in getWantedLanguages
    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/subtitles.py", line 101, in subtitlesLanguages
    with open(video_path, 'rb') as f:
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 90: ordinal not in range(128)

**Comment by fernandog** [comment]
@miigotu can't we do unicode here?

` with open(video_path.unicode, 'rb') as f:`

**Comment by miigotu** [comment]
@medariox you chould be using codecs.open...

also you might need to encode `video_path` to `utf-8` with `video_path.encode('utf-8')` if it is unicode, or maybe decode it to unicode with `unicode(video_path, 'utf-8')`
```python
import codecs

with codecs.open(video_path, 'rb', encoding='utf-8') as f:
```

**Comment by medariox** [comment]
@miigotu 

We can try this, but I'm quite sure this might break things for other people. It would be better to properly configure the locals I think (as many people have it working fine). Surely needs testing.

**Comment by fernandog** [comment]
why it will break?

**Comment by medariox** [comment]
@fernandog 
I'm not saying it will break something for sure, IMO it is just not a good idea to mess with encodings at that point.

**Comment by reisrdok** [comment]
Locales were correct for root user also. Everything is en_US.UTF-8. I was afraid that they were inherited from normal user when doing 'sudo su', not so.

After this change error is gone:

with open(video_path.encode('utf-8'), 'rb') as f:

Few hundred subtitles were downloaded. Subtitles with name "Kō No Mono" are not found though even when they exist in Addic7ed.

Will do 'git reset' now..

**Comment by medariox** [comment]
```
Few hundred subtitles were downloaded. Subtitles with name "Kō No Mono" are not found though even when they exist in Addic7ed.
```
This is what I mean when I say it might break things. If we encode things we need proper testing.

**Comment by reisrdok** [comment]
I am using cifs mounted NAS (Zyxel nsa325) as storage. SR writes directly to the mounted dir. I have to check if there is some problem with mounting options. Maybe force UTF-8 or something.

**Comment by miigotu** [comment]
`.encode(sickbeard.SYS_ENCODING)`

**Comment by medariox** [comment]
@reisrdok 
Can you please tell us if you are having any luck with
```
.encode(sickbeard.SYS_ENCODING)
```
?

**Comment by reisrdok** [comment]
Hmm, very confusing. Two "Kō No Mono" subtitle files have appeared to disk at some point for en/fi languages. I do not know when this has happened. I did not even think to check this because SR says that subtitles are missing, and they actually were missing originally. SR still shows the "CC" icon after the show name, and pressing it says "no subtitles downloaded". Files seem to be ok and work.

Now, if I delete the problematic subtitles, everything works. Without any changes to code. New subtitles are downloaded with exactly the same names, history shows the download, and CC icon disappears.

I have to test this more. Why some of the existing sub files with special chars in their name are not recognized, and where did they come from?

**Comment by medariox** [comment]
@reisrdok 
This is normal, if you remove the error, SickRage can continue its normal work and do all the rest without any problem. The point is that there are other users like you, that have this issue and we would really like to have something working for everyone. It would be great if you could test some fixes in the develop branch. Can you help us with testing?

**Comment by miigotu** [comment]
I think he is saying that with the change `Kō No Mono` subtitles DO download now.

**Comment by reisrdok** [comment]
Ehh, this problem reminds me a bit too much of my day job.. Debugging RTOS faults on arm cortex is like chasing a chicken in a snowstorm..

Yes, subtitles do download now. If I delete the old subtitles that SR has downloaded, and now does not recognize anymore. I wonder if this is also the case with other people.

**Comment by medariox** [comment]
@reisrdok 
So what fixed it for you now?

**Comment by reisrdok** [comment]
Deleting existing subtitles.

**Comment by miigotu** [comment]
@reisrdok the ones it did not recognize probable needed a refresh.

**Comment by reisrdok** [comment]
Did refresh many times, also reboots etc. I always try to refresh/reinit everything after every step, otherwise results are usually garbage.

**Comment by miigotu** [comment]
I meant refresh/rescan the show. SR is supposed to do that itself on subtitle check and download so it update it in the episode object. maybe it isnt being done or it got interrupted on an older error and never got refreshed in the db.

**Comment by reisrdok** [comment]
@miigotu you sir, are correct. I did not press the "Re-scan files" button after latest update.

Oh ffs now it works.. How did I miss that? Just after boasting how I always refresh everything..

My humble apologies everyone. I may have wasted your time.

**Comment by medariox** [comment]
@reisrdok 
Oh boy, fixed that long time ago. Was a nice ride, glad it's over.

**Comment by fernandog** [comment]
@reisrdok feel free to pay an energy drink to @miigotu and @medariox  LOL

**Comment by reisrdok** [comment]
It did not help before latest update. I DID re-scan files yesterday. So possibly the latest update fixed this.

Will pay, thank you a lot!!

**Comment by 03397** [comment]
I am facing the same problem.
I have  noticed that some subtitles indeed contains characters that are not recognized. AA  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/tv.py", line 1472, in downloadSubtitles
2015-09-30 22:07:36 ERROR    FINDSUBTITLES :: Traceback (most recent call last):
2015-09-30 22:07:36 INFO     FINDSUBTITLES :: Error occurred when downloading subtitles for: /share/Multimedia/Video/Series/Game Of Thrones/Season 5/Game.of.Thrones.S05E10.HDTV-Mother’s Mercy.mkv
AAUnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 81: ordinal not in range(128)
AA    with open(video_path, 'rb') as f:



why is this happening? What have changed in Sickrage and what I can do to fix this?

**Comment by medariox** [comment]
@03397 
Are your locals set to utf-8? If yes, delete the problematic subtitles and re-scan files. You should be able to download the subtitles again and this time with no errors.

**Comment by reisrdok** [comment]
Rebooted server, error came back. Deleting subs & re-scan helps until reboot.


AA
AAUnicodeEncodeError: 'ascii' codec can't encode character u'\u014d' in position 60: ordinal not in range(128)
AA    with open(video_path, 'rb') as f:
AA  File "/opt/sickrage/sickbeard/subtitles.py", line 101, in subtitlesLanguages
AA    self.subtitles = subtitles.subtitlesLanguages(self.location)
AA  File "/opt/sickrage/sickbeard/tv.py", line 1453, in refreshSubtitles
AA    curEpisode.refreshSubtitles()
AA  File "/opt/sickrage/sickbeard/tv.py", line 463, in loadEpisodesFromDir
2015-09-30 22:38:06 DEBUG    SHOWQUEUE-REFRESH :: Traceback (most recent call last):
AAUnicodeEncodeError: 'ascii' codec can't encode character u'\u014d' in position 60: ordinal not in range(128)
AA    with open(video_path, 'rb') as f:
AA  File "/opt/sickrage/sickbeard/subtitles.py", line 101, in subtitlesLanguages
AA    self.subtitles = subtitles.subtitlesLanguages(self.location)
AA  File "/opt/sickrage/sickbeard/tv.py", line 1453, in refreshSubtitles
AA    curEpisode.refreshSubtitles()
AA  File "/opt/sickrage/sickbeard/tv.py", line 463, in loadEpisodesFromDir
AATraceback (most recent call last):
2015-09-30 22:38:06 ERROR    SHOWQUEUE-REFRESH :: 259063: Could not refresh subtitles
2015-09-30 22:38:06 DEBUG    SHOWQUEUE-REFRESH :: Using cached parse result for: Hannibal - S02E11 - Kō No Mono

**Comment by 03397** [comment]
@medariox 
I have deleted one of the problematic subtitles. try to download again. Error the same
AAUnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 109: ordinal not in range(128)
AA    with open(video_path, 'rb') as f:
AA  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/subtitles.py", line 101, in subtitlesLanguages
AA    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
AA  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/tv.py", line 1446, in getWantedLanguages
AA    languages = self.getWantedLanguages();
AA  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/tv.py", line 1472, in downloadSubtitles
AATraceback (most recent call last):
AAUnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 109: ordinal not in range(128)
AA    with open(video_path, 'rb') as f:
AA  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/subtitles.py", line 101, in subtitlesLanguages
AA    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
AA  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/tv.py", line 1446, in getWantedLanguages
AA    languages = self.getWantedLanguages();
AA  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/tv.py", line 1472, in downloadSubtitles
2015-09-30 22:54:10 ERROR    Thread-17 :: Traceback (most recent call last):
2015-09-30 22:54:10 INFO     Thread-17 :: Error occurred when downloading subtitles for: /share/Multimedia/Video/Series/The Walking Dead/Season 5/The.Walking.Dead.S05E09.HD.TV-What Happened and What’s Going On.mkv


My locale
[/share/homes/admin] # locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8

**Comment by miigotu** [comment]
It still needs .encode.

**Comment by medariox** [comment]
@reisrdok @03397 
Please replace the following line: https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/subtitles.py#L101
with this one:
```
 with open(str(video_path), 'rb') as f:
```
and tell me what you get. Thanks!

**Comment by miigotu** [comment]
@medariox that will not work. You must `video_path.encode('utf-8')` and that makes it a string. Otherwise you are forcing to ascii and the video path might have non ascii unicode characters.

**Comment by 03397** [comment]
@reisrdok 
This change did the trick, no more errors. I have restarted the Sickrage and I did not get any more errors.
What;s the difference between the change and ths previous line?
Will this be inlcuded in future updates or this is the old one before it broke things?

**Comment by miigotu** [comment]
no its proper this way. you have to encode before doing any IO such as file io or console logging.

**Comment by medariox** [comment]
@03397
Can you tell us exactly which suggestion worked, so we can push the fix? Is it just .encode('utf-8') or is there more to it? Thanks.

**Comment by reisrdok** [comment]
>>Locales were correct for root user also. Everything is en_US.UTF-8. I was afraid that they were inherited from normal user when doing 'sudo su', not so.
>>
>>After this change error is gone:
>>
>>with open(video_path.encode('utf-8'), 'rb') as f:
>>Few hundred subtitles were downloaded. Subtitles with name "Kō No Mono" are not found though >>even when they exist in Addic7ed.

This probably actually worked for me, I just did not do the rescan for the show. 

But I did press the CC -icon. You mentioned that it runs rescan?

**Comment by 03397** [comment]
@medariox
My locales are utf8.
I just changed line with open(str(video_path), 'rb') as
Then I restarted and the error were gone.

**Comment by medariox** [comment]
@03397 
Nice, that's what I was hoping to hear. Thanks for the feedback. @reisrdok can you try it as well maybe?
@miigotu 
If what I think is correct, utf-8 is not the problem here (both users have utf-8 locales), but the unicode u in front of the character sequence, which can't be correctly encoded to ASCII (which is required by open). If that's the case, it would spare us some trouble.

**Comment by reisrdok** [comment]
Made this change to subtitles line:  **with open(str(video_path), 'rb') as f:**
- Rebooted server, Simpsons episode S12E09 shows missing subtitle. After Re-scan, still showing missing subtitle. **Subtile file "The Simpsons - S12E09 - HOMЯ.srt" exists**.
- Pressing CC button gave popup "no subtitles downloaded". Error log is empty, debug log shows these two lines:

>>2015-10-01 14:45:08 DEBUG    Thread-46 :: 71663: Exception caught in subliminal.scan_video for S12E09
>>2015-10-01 14:45:08 DEBUG    Thread-46 :: 71663: Downloading subtitles for S12E09

- Pressing force full update&wait until done, subtitle still shows missing.

Then I tried this change: **with open(video_path.encode('utf-8'), 'rb') as f:**
- Rebooted server, Simpsons episode S12E09 still shows missing subtitle. After Re-scan, still showing missing subtitle. Subtile file "The Simpsons - S12E09 - HOMЯ.srt" still exists.
- Pressing CC button gave popup "no subtitles downloaded". Error log is empty, debug log shows these two lines:

>>2015-10-01 15:11:05 DEBUG    Thread-45 :: 71663: Exception caught in subliminal.scan_video for S12E09
>>2015-10-01 15:11:05 DEBUG    Thread-45 :: 71663: Downloading subtitles for S12E09

Then I deleted the subtile file "The Simpsons - S12E09 - HOMЯ.srt" .
- After Re-scan, Simpsons episode S12E09 still shows missing subtitle. 
- Pressing CC button gave popup "no subtitles downloaded". Error log is empty, debug log shows these two lines:

>>2015-10-01 15:20:23 DEBUG    Thread-40 :: 71663: Exception caught in subliminal.scan_video for S12E09
>>2015-10-01 15:20:23 DEBUG    Thread-40 :: 71663: Downloading subtitles for S12E09

- Rebooted server, Simpsons episode S12E09 still shows missing subtitle. 
- Pressing CC button gave popup "no subtitles downloaded". Error log is empty, debug log shows these two lines:

>>2015-10-01 15:25:58 DEBUG    Thread-27 :: 71663: Exception caught in subliminal.scan_video for S12E09
>>2015-10-01 15:25:58 DEBUG    Thread-27 :: 71663: Downloading subtitles for S12E09

Then I run "sudo git reset --hard" in sickrage folder.
- Last commit is now **4d37c1352e1a27023ffd520a4da8ab0f024333e6**, no local changes.
- Rebooted server, Simpsons episode S12E09 still shows missing subtitle. 
- Pressing CC button gave popup "no subtitles downloaded". Debug log shows these two lines:

>>2015-10-01 15:31:41 DEBUG    Thread-21 :: 71663: Exception caught in subliminal.scan_video for S12E09
>>2015-10-01 15:31:41 DEBUG    Thread-21 :: 71663: Downloading subtitles for S12E09

- Error log shows this:

>> 2015-10-01 15:30:43 FINDSUBTITLES :: Traceback (most recent call last):
>>  File "/opt/sickrage/sickbeard/tv.py", line 1472, in downloadSubtitles
>>    languages = self.getWantedLanguages();
>>  File "/opt/sickrage/sickbeard/tv.py", line 1446, in getWantedLanguages
>>    for language in frozenset(subtitles.wantedLanguages()).difference(subtitles.subtitlesLanguages(self.location)):
>>  File "/opt/sickrage/sickbeard/subtitles.py", line 101, in subtitlesLanguages
>>    with open(video_path, 'rb') as f:
>>UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 69: ordinal not in range(128)

SR media folder on my NAS is mounted with:
**//192.168.0.105/video /media/video cifs guest,uid=reisrdok,gid=reisrdok,file_mode=0777,dir_mode=0777,forceuid,forcegid,iocharset=utf8 0 0**
Had to force a bit stupid file mode because of reasons. But at least it does not prevent anything.


Now I cannot get it to work at all.

**Comment by reisrdok** [comment]
This is a minor bug, SR otherwise works flawlessly. I can live with it :)

**Comment by medariox** [comment]
@reisrdok 
The error you get now is after the problem you had before str() or .encode(). Keep str() for now and let's continue debugging there. The exception you are getting has most probably the same reason as the other error you were getting. Go to tv.py and replace https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/tv.py#L1481
with
```
video = subliminal.scan_video(str(vname), subtitles=False, embedded_subtitles=False)
```
or .encode('utf-8') and let us know what you get.

**Comment by miigotu** [comment]
If you use str() the PR will be denied. Using str() it does the exact same thing that is causing the error because that forces it to ascii. You have to encode to probably sickbeard.SYS_ENCODING (which is detected at startup and falls back to utf-8)

**Comment by medariox** [comment]
@miigotu 
No, the error is caused by open() trying to read the path as ASCII while it is unicode. What we need is a representation of the unicode which is accepted by open(). This can either be str or utf-8, it doesn't make any difference in this case, as it will be accepted in both situations. Since open() defaults to ASCII and it works fine for most users that way, it would make more sense to encode it as str in my opinion, but I don't really care tbh. More important is that this issue gets resolved either way.

**Comment by miigotu** [comment]
str() IS converting it to ASCII. its exactly what is used to coerce it to Unicode in stdlib. @Diaoul back me up

**Comment by miigotu** [comment]
unidecode is not allowed either.

**Comment by medariox** [comment]
@miigotu 
???? Please read again what I wrote:
```
No, the error is caused by open() trying to read the path as ASCII while it is unicode.
```
The problem IS that it isn't ASCII right now, but unicode. We need either ASCII string or UTF-8 string or whatever - the problem is that it is Unicode right now and that is not accepted by open(). So we need to encode it to either ASCII or UTF-8 or whatever.

**Comment by Diaoul** [comment]
You need to use a bytestring not unicode, that's all. The encoding must be the same as the filesystem encoding otherwise open will fail. Encoding to ASCII will fail with the same error as some character don't exist in ASCII character encoding.

**Comment by miigotu** [comment]
@medariox no, open is converting it to a bytestring, not ascii. If the filename contains non-ascii characters and is unicode and the builtin calls str() on it it tries to coerce it to ascii (because python2 ALWAYS assumes ascii) and it cannot coerce non-ascii characters to ascii. You MUST encode it to something that handles the non-ascii chracters.

Proof:
```
>>> print str(u'Iлｔｅｒлãｔíｏｎâｌíƶáｔï߀ԉ')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-19: ordinal not in range(128)
>>> print str(u'Iлｔｅｒлãｔíｏｎâｌíƶáｔï߀ԉ'.encode('utf-8'))
Iлｔｅｒлãｔíｏｎâｌíƶáｔï߀ԉ
>>>
```

**Comment by miigotu** [comment]
This is the problem you though you fixed by adding enzyme directly instead of using subliminal to scan for embedded subs. That needs reverted.

**Comment by medariox** [comment]
@miigotu 
I never said that open is converting it to ascii. I said that open() does not take unicode and that we need it to encode to either string version of the object with str() (which will default to UTF-8 by the way and NOT ascii, even on python 2) or a utf-8 string with encode() or the system utf, why not. Just not how it is right now.

No, scan_video has been replaced with enzyme directly at that point, because we need only the embedded subtitles. Scan_video of subliminal calls many other tools e.g. GuessIt, making it extremely inefficient for that task.

**Comment by miigotu** [comment]
https://docs.python.org/3/library/stdtypes.html#str <-- python 3 docs.
We use a hack that I am trying to get rid of, which is also not always working unless the user truly has utf-8 filesystem.
https://anonbadger.wordpress.com/2015/06/16/why-sys-setdefaultencoding-will-break-code/

We need to handle unicode properly.

**Comment by medariox** [comment]
Should be fixed with https://github.com/SiCKRAGETV/SickRage/pull/2681
