### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'indexerid'

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#3025]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-57-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5aac5803f2e1df3385a5cb19580b8fd6b4eb6191
Link to Log: https://gist.github.com/f8decfad3691082c622f
### ERROR
```
Thread-33 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/media/sickrage/sickbeard/webserve.py", line 275, in async_call
    result = function(**kwargs)
  File "/home/media/sickrage/sickbeard/webserve.py", line 1499, in deleteShow
    error, show = Show.delete(show, full)
  File "/home/media/sickrage/sickrage/show/Show.py", line 47, in delete
    sickbeard.showQueueScheduler.action.removeShow(show, bool(remove_files))
  File "/home/media/sickrage/sickbeard/show_queue.py", line 156, in removeShow
    if self._isInQueue(show, ShowQueueActions.REMOVE):
  File "/home/media/sickrage/sickbeard/show_queue.py", line 46, in _isInQueue
    return show.indexerid in [x.show.indexerid for x in self.queue if x.action_id in actions]
AttributeError: 'NoneType' object has no attribute 'indexerid'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
Thanks for the issue report! To make sure issues are handled quickly, it helps if all info is there. Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md) and followed all the steps. 

Make the title describe your issue. Having "SR not working" or "I am getting this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the devs don't like you, but because they are on mobile or busy fixing other bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by OmgImAlexis** [comment]
@miigotu seems the remove show thread doesn't work properly if you remove two shows at the same time in two different tabs. I was left with a show still showing up on on home and displayShow even thought it was "removed", I removed it a second time and it instantly redirected me to the homepage with it completely gone from the ui this time.

@WebSpider we need to work on the bot's detection as it's not picking up the commit, branch, etc. and it shouldn't be adding this for people in the Sickrage teams as we know what needs to be added to an issue.

**Comment by WebSpider** [comment]
@OmgImAlexis yeah, im getting familiar with nodejs github api to find out how to see if a submitting user has a team membership. Once that is done, we can ignore new issues/pr’s from anyone in the SiCKRAGETV org teams

**Comment by fernandog** [comment]
related? https://github.com/SiCKRAGETV/sickrage-issues/issues/2764

**Comment by OmgImAlexis** [comment]
@fernandog yeah I think so. @WebSpider I'll jump on IRC later and see if I can add that in, should be easy enough if we use a function from underscore to check the js object passed with the user details.

**Comment by miigotu** [comment]
I can fix this error probably.

**Comment by miigotu** [comment]
Hope that fixes it, closing for now.

**Comment by frank3427** [comment]
### INFO
Python Version: **2.7.10 (default, Jul  8 2015, 08:04:18) [GCC 4.3.6]**
Operating System: **Linux-3.4.6-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@85df569d8d7b60c9e2453aea355df8ec5e8f1d62
Link to Log: https://gist.github.com/524e5e77ac5035135d90
### ERROR
```
Thread-47 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "/share/MD0_DATA/.qpkg/QSickRage/SickRage/sickbeard/webserve.py", line 1476, in deleteShow
    error, show = Show.delete(show, full)
  File "/share/MD0_DATA/.qpkg/QSickRage/SickRage/sickrage/show/Show.py", line 47, in delete
    sickbeard.showQueueScheduler.action.removeShow(show, bool(remove_files))
  File "/share/MD0_DATA/.qpkg/QSickRage/SickRage/sickbeard/show_queue.py", line 164, in removeShow
    if show.indexerid == x.show.indexerid and x != self.currentItem:
AttributeError: 'NoneType' object has no attribute 'indexerid'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by springah** [comment]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@c19526435dc15ba1bcd5827dd24d6a8e69c83e2b
Link to Log: https://gist.github.com/1b49bf6bb75a13d2861e
### ERROR
```
Thread-48 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 259, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 1532, in deleteShow
    error, show = Show.delete(show, full)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickrage/show/Show.py", line 50, in delete
    sickbeard.showQueueScheduler.action.removeShow(show, bool(remove_files))
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/show_queue.py", line 163, in removeShow
    if show.indexerid == x.show.indexerid and x != self.currentItem:
AttributeError: 'NoneType' object has no attribute 'indexerid'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by webnar** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-33-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
Thread-21 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/webnar/.sickrage/sickbeard/webserve.py", line 259, in async_call
    result = function(**kwargs)
  File "/home/webnar/.sickrage/sickbeard/webserve.py", line 1532, in deleteShow
    error, show = Show.delete(show, full)
  File "/home/webnar/.sickrage/sickrage/show/Show.py", line 50, in delete
    sickbeard.showQueueScheduler.action.removeShow(show, bool(remove_files))
  File "/home/webnar/.sickrage/sickbeard/show_queue.py", line 163, in removeShow
    if show.indexerid == x.show.indexerid and x != self.currentItem:
AttributeError: 'NoneType' object has no attribute 'indexerid'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rebelmethod** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@d294e9faf48d45051a50d4e2cf3a0252c28d5b17
No Log available with ERRORS: 
### ERROR
```
Thread-60 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 259, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 1532, in deleteShow
    error, show = Show.delete(show, full)
  File "C:\SickRage\SickRage\sickrage\show\Show.py", line 50, in delete
    sickbeard.showQueueScheduler.action.removeShow(show, bool(remove_files))
  File "C:\SickRage\SickRage\sickbeard\show_queue.py", line 163, in removeShow
    if show.indexerid == x.show.indexerid and x != self.currentItem:
AttributeError: 'NoneType' object has no attribute 'indexerid'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
