### ISSUE TITLE
[APP SUBMITTED]: string indices must be integers

### ISSUE THREAD

**Issue by duramato** [SiCKRAGETV/sickrage-issues#3028]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-28-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@280b1eb8d1aeec32611e45af68a92e8318d728f5
Link to Log: https://gist.github.com/1adad0bde8abd7d2b509
### ERROR
```
SEARCHQUEUE-MANUAL-268583 ::[ExtraTorrent] :: Failed parsing ExtraTorrent Traceback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/extratorrent.py", line 126, in _doSearch
    seeders = int(item['seeders'])
ValueError: invalid literal for int() with base 10: '---'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by duramato** [comment]
@miigotu ugh ,will try to fix

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-28-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: SiCKRAGETV/SickRage@62671dd0f7b6f6f8ea6dfc4a8365e67d291dc18c
Link to Log: https://gist.github.com/6ae6be6e56579afa24e4
### ERROR
```
SEARCHQUEUE-RETRY-300674 :: [ExtraTorrent] :: Failed parsing ExtraTorrent Traceback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/extratorrent.py", line 122, in _doSearch
    title = item['title']
TypeError: string indices must be integers

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
