### ISSUE TITLE
Getting errors when searching ExtraTorrent

### ISSUE THREAD

**Issue by Sacrilegium** [SiCKRAGETV/sickrage-issues#3031]
Anyone else getting similar errors?  

Here's part of my log:

2015-09-30 01:12:50 INFO     SEARCHQUEUE-MANUAL-279227 :: [ExtraTorrent] :: Unable to find a download for: [The Bastard Executioner - 1x04 - A Hunger - Newyn]
2015-09-30 01:12:50 INFO     SEARCHQUEUE-MANUAL-279227 :: [ExtraTorrent] :: Performing season pack search for The Bastard Executioner
2015-09-30 01:12:50 INFO     SEARCHQUEUE-MANUAL-279227 :: [ExtraTorrent] :: Ignoring result The.Bastard.Executioner.S01E04.HDTV.XviD-FUM[ettv] because we don't want an episode that is SDTV
AAValueError: invalid literal for int() with base 10: '---'
AA    seeders = int(item['seeders'])
AA  File "c:\sickrage\sickbeard\providers\extratorrent.py", line 126, in _doSearch
AATraceback (most recent call last):
AAValueError: invalid literal for int() with base 10: '---'
AA    seeders = int(item['seeders'])
AA  File "c:\sickrage\sickbeard\providers\extratorrent.py", line 126, in _doSearch
2015-09-30 01:12:50 ERROR    SEARCHQUEUE-MANUAL-279227 :: [ExtraTorrent] :: Failed parsing ExtraTorrent Traceback: Traceback (most recent call last):
2015-09-30 01:12:50 INFO     SEARCHQUEUE-MANUAL-279227 :: [ExtraTorrent] :: Performing episode search for The Bastard Executioner
2015-09-30 01:12:48 INFO     SEARCHQUEUE-MANUAL-279227 :: [ThePirateBay] :: Performing episode search for The Bastard Executioner
2015-09-30 01:12:47 INFO     SEARCHQUEUE-MANUAL-279227 :: [KickAssTorrents] :: Performing episode search for The Bastard Executioner
2015-09-30 01:12:47 INFO     SEARCHQUEUE-MANUAL-279227 :: Beginning manual search for: [The Bastard Executioner - 1x04 - A Hunger - Newyn]
2015-09-30 01:11:07 INFO     SEARCHQUEUE-MANUAL-279227 :: [ExtraTorrent] :: Unable to find a download for: [The Bastard Executioner - 1x04 - A Hunger - Newyn]
2015-09-30 01:11:07 INFO     SEARCHQUEUE-MANUAL-279227 :: [ExtraTorrent] :: Ignoring result The.Bastard.Executioner.S01E04.HDTV.XviD-FUM[ettv] because we don't want an episode that is SDTV
AAValueError: invalid literal for int() with base 10: '---'
AA    seeders = int(item['seeders'])
AA  File "c:\sickrage\sickbeard\providers\extratorrent.py", line 126, in _doSearch
AATraceback (most recent call last):
AAValueError: invalid literal for int() with base 10: '---'
AA    seeders = int(item['seeders'])
AA  File "c:\sickrage\sickbeard\providers\extratorrent.py", line 126, in _doSearch
2015-09-30 01:11:06 ERROR    SEARCHQUEUE-MANUAL-279227 :: [ExtraTorrent] :: Failed parsing ExtraTorrent Traceback: Traceback (most recent call last):
2015-09-30 01:11:06 INFO     SEARCHQUEUE-MANUAL-279227 :: [ExtraTorrent] :: Performing episode search for The Bastard Executioner
2015-09-30 01:11:03 INFO     SEARCHQUEUE-MANUAL-279227 :: [ThePirateBay] :: Performing episode search for The Bastard Executioner
2015-09-30 01:11:02 INFO     SEARCHQUEUE-MANUAL-279227 :: [KickAssTorrents] :: Performing episode search for The Bastard Executioner
2015-09-30 01:11:02 INFO     SEARCHQUEUE-MANUAL-279227 :: Beginning manual search for: [The Bastard Executioner - 1x04 - A Hunger - Newyn]
2015-09-30 01:10:23 INFO     POSTPROCESSER :: Processing completed
2015-09-30 01:10:23 INFO     POSTPROCESSER :: PostProcessing Path: C:\Users\AMD\Desktop\Downloads\_postprocessing
2015-09-30 01:09:05 INFO     SEARCHQUEUE-BACKLOG-293302 :: [ExtraTorrent] :: No needed episodes found during backlog search for: [Scream Queens (2015)]
2015-09-30 01:09:05 INFO     SEARCHQUEUE-BACKLOG-293302 :: [ExtraTorrent] :: Ignoring result Scream.Queens.2015.S01E03.HDTV.XviD-FUM[ettv] because we don't want an episode that is SDTV
AAValueError: invalid literal for int() with base 10: '---'
AA    seeders = int(item['seeders'])
AA  File "c:\sickrage\sickbeard\providers\extratorrent.py", line 126, in _doSearch
AATraceback (most recent call last):
AAValueError: invalid literal for int() with base 10: '---'
AA    seeders = int(item['seeders'])
AA  File "c:\sickrage\sickbeard\providers\extratorrent.py", line 126, in _doSearch

**Comment by miigotu** [comment]
Already known, and '---' error is fixed, about to release to master. Might get another error with that about indices needing to be integers, will be working on that one also later.
