### ISSUE TITLE
Search fails at finding propers on KAT and TPB

### ISSUE THREAD

**Issue by rmbleeker** [SiCKRAGETV/sickrage-issues#3034]
BRANCH: (master) / COMMIT: (ec887f38a338fc1e7e627ed330c2b7ee4ecfdec3)
Ubuntu 14.04.3 LTS running python 2.7.6

There seems to be an issue with KAT and TPB when searching for propers. I hope below is enough information, if not let me know what else I can provide.

**From the error log:**

2015-09-30 13:16:40 FINDPROPERS :: [KickAssTorrents] :: Error while searching KickAssTorrents, skipping: 'list' object has no attribute 'keys'
2015-09-30 13:16:40 FINDPROPERS :: [ThePirateBay] :: Error while searching ThePirateBay, skipping: 'list' object has no attribute 'keys'

**From the regular log:**

2015-09-30 13:16:40 INFO     FINDPROPERS :: [ThePirateBay] :: Completed the search for new propers, next check in approx. 3h, 58m
AA
AAAttributeError: 'list' object has no attribute 'keys'
AA    for mode in search_strings.keys():
AA  File "/opt/sickrage/sickbeard/providers/thepiratebay.py", line 126, in _doSearch
AA    for item in self._doSearch(searchStrings):
AA  File "/opt/sickrage/sickbeard/providers/thepiratebay.py", line 219, in findPropers
AA    curPropers = curProvider.findPropers(search_date)
AA  File "/opt/sickrage/sickbeard/properFinder.py", line 92, in _getProperList
AAAttributeError: 'list' object has no attribute 'keys'
AA    for mode in search_strings.keys():
AA  File "/opt/sickrage/sickbeard/providers/thepiratebay.py", line 126, in _doSearch
AA    for item in self._doSearch(searchStrings):
AA  File "/opt/sickrage/sickbeard/providers/thepiratebay.py", line 219, in findPropers
AA    curPropers = curProvider.findPropers(search_date)
AA  File "/opt/sickrage/sickbeard/properFinder.py", line 92, in _getProperList
AATraceback (most recent call last):
2015-09-30 13:16:40 ERROR    FINDPROPERS :: [ThePirateBay] :: Error while searching ThePirateBay, skipping: 'list' object has no attribute 'keys'
2015-09-30 13:16:40 INFO     FINDPROPERS :: [ThePirateBay] :: Searching for any new PROPER releases from ThePirateBay
AA
AAAttributeError: 'list' object has no attribute 'keys'
AA    for mode in search_strings.keys():
AA  File "/opt/sickrage/sickbeard/providers/kat.py", line 126, in _doSearch
AA    for item in self._doSearch(searchStrings):
AA  File "/opt/sickrage/sickbeard/providers/kat.py", line 226, in findPropers
AA    curPropers = curProvider.findPropers(search_date)
AA  File "/opt/sickrage/sickbeard/properFinder.py", line 92, in _getProperList
AAAttributeError: 'list' object has no attribute 'keys'
AA    for mode in search_strings.keys():
AA  File "/opt/sickrage/sickbeard/providers/kat.py", line 126, in _doSearch
AA    for item in self._doSearch(searchStrings):
AA  File "/opt/sickrage/sickbeard/providers/kat.py", line 226, in findPropers
AA    curPropers = curProvider.findPropers(search_date)
AA  File "/opt/sickrage/sickbeard/properFinder.py", line 92, in _getProperList
AATraceback (most recent call last):
2015-09-30 13:16:40 ERROR    FINDPROPERS :: [KickAssTorrents] :: Error while searching KickAssTorrents, skipping: 'list' object has no attribute 'keys'
2015-09-30 13:16:40 INFO     FINDPROPERS :: [KickAssTorrents] :: Searching for any new PROPER releases from KickAssTorrents

**Comment by fernandog** [comment]
Same issue I have with HDT.

**Comment by miigotu** [comment]
Hotfixed, thanks for reporting.
