### ISSUE TITLE
TypeError in getUrl

### ISSUE THREAD

**Issue by WebSpider** [SiCKRAGETV/sickrage-issues#3038]
Latest master release seems to have a TypeError in getUrl when the connection to a provider times out.

Will append the debug log when this occurs again. I've missed it now.

```
SR Version: 	BRANCH: (master) / COMMIT: (1c3577ae6df29cad345f64d23647d0a2d8a4e008)
SR User:	sickbeard-custom
SR Locale:	('en_US', 'UTF-8')
SR Config:	/usr/local/sickbeard-custom/var/config.ini
SR Database:	/usr/local/sickbeard-custom/var/sickbeard.db
SR Cache Dir:	/usr/local/sickbeard-custom/var/cache
SR Log Dir:	/usr/local/sickbeard-custom/var/Logs
SR Arguments:	['--daemon', '--pidfile', '/usr/local/sickbeard-custom/var/sickbeard-custom.pid', '--config', '/usr/local/sickbeard-custom/var/config.ini', '--datadir', '/usr/local/sickbeard-custom/var/', '--nolaunch']
SR Web Root:	/sr
Python Version:	2.7.10 (default, Jun 3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]
```

```
2015-09-30 15:31:16 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
AA
AATypeError: __str__ returned non-string (type SysCallError)
AA    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
AA  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
AA    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
AA  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
AA    body=body, headers=headers)
AA  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
AA    timeout=timeout
AA  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/adapters.py", line 370, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/usr/local/sickbeard-custom/var/SickBeard/lib/cachecontrol/adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 476, in get
AA    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1622, in getURL
2015-09-30 15:30:32 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: Traceback (most recent call last):
2015-09-30 15:30:30 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: Unknown exception in getURL https://iptorrents.eu/torrents/ Error: __str__ returned non-string (type SysCallError)
2015-09-30 15:29:11 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
```

**Comment by miigotu** [comment]
@WebSpider this seems to happen with IPTorrents and BTDig atm. I think it is cloudflare, need to set the User-Agent for them specifically.

**Comment by miigotu** [comment]
```python
from sickbeard.common import USER_AGENT

(in __init__):

self.headers.update({'User-Agent': USER_AGENT})
```

Need to stop sr and clear sessions for this to take effect.

Let me know if that fixes it for you and I can PR or you can.

**Comment by duramato** [comment]
@miigotu II also think cloud flare isn't allowing extra torrent to be searched but not sure..

**Comment by miigotu** [comment]
@duramato you could try those changes in extratorrent and find out for sure.

**Comment by miigotu** [comment]
I think I need to dynamically create a user agent for each provider, and stick with it.
They should be semi unique.
https://www.eff.org/deeplinks/2010/01/tracking-by-user-agent

**Comment by WebSpider** [comment]
This hasnt happened since. Do we keep the issue open?

**Comment by miigotu** [comment]
I've fixed it in most providers, so let's close it.
