### ISSUE TITLE
Update fails when shows are being updated

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#3039]
Need to check if thread is amActive before start backup/update

```
2015-09-30 11:16:59 ERROR    Thread-29 :: Config backup failed, aborting update
AAOSError: [Errno 2] Arquivo ou diretório não encontrado: '/home/osmc/SickRage/cache/indexers/theTVDB/5/b/e/c/f/5becf352bec59397e6b41b42744eccd35876f796b1625136cd136d48'
AA    st = os.stat(filename)
AA  File "/usr/lib/python2.7/zipfile.py", line 1123, in write
AA    a.write(f, os.path.relpath(f, arcname))
AA  File "/home/osmc/SickRage/sickbeard/helpers.py", line 1406, in backupConfigZip
AATraceback (most recent call last):
2015-09-30 11:16:59 ERROR    Thread-29 :: Zip creation error: [Errno 2] Arquivo ou diretório não encontrado: '/home/osmc/SickRage/cache/indexers/theTVDB/5/b/e/c/f/5becf352bec59397e6b41b42744eccd35876f796b1625136cd136d48'
```

**Comment by fernandog** [comment]
@miigotu this code is wrong isn't? as isn't running the def, just returning True always:


```
    def run_backup_if_safe(self):
        return self.safe_to_update() is True and self._runbackup() is True
```

shouldn't be:

```
    def run_backup_if_safe(self): 

        if self.safe_to_update() is True:
              if self._runbackup() is True:
              return True
              else
              return False
       else
            return False
```


https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/versionChecker.py#L86

**Comment by fernandog** [comment]
As SR don't detects showupdate is running as we talked in IRC, I still have that issue. Even deleting cache/* except images

maybe the showupdate is updating that file and lock it

```
AAOSError: [Errno 2] Arquivo ou diretório não encontrado: '/home/osmc/SickRage/cache/indexers/theTVDB/5/b/e/c/f/5becf352bec59397e6b41b42744eccd35876f796b1625136cd136d48'
AA    st = os.stat(filename)
AA  File "/usr/lib/python2.7/zipfile.py", line 1123, in write
AA    a.write(f, os.path.relpath(f, arcname))
AA  File "/home/osmc/SickRage/sickbeard/helpers.py", line 1406, in backupConfigZip
AATraceback (most recent call last):
2015-09-30 11:16:59 ERROR    Thread-29 :: Zip creation error: [Errno 2] Arquivo ou diretório não encontrado: '/home/osmc/SickRage/cache/indexers/theTVDB/5/b/e/c/f/5becf352bec59397e6b41b42744eccd35876f796b1625136cd136d48'
```

**Comment by fernandog** [comment]
@webspide he is the issue

**Comment by miigotu** [comment]
stop trying to back up the cache, or stop doing version checks wrong.

**Comment by fernandog** [comment]
needs a PR to stop back up cache. lol. you fixed the nt.path and didn't change the cache backup as you said.

**Comment by miigotu** [comment]
I didn't remove the cache backup because you argued with me for two hours that it needed to be backed up.

**Comment by fernandog** [comment]
I said because users complain about missing IMAGES. that's it

**Comment by miigotu** [comment]
.
