### ISSUE TITLE
Kickass Torrents issue

### ISSUE THREAD

**Issue by m184711** [SiCKRAGETV/sickrage-issues#3045]
Latest master release i can no longer grab torrent from kickass, here is the log
AA
AAAttributeError: '_socketobject' object has no attribute 'set_tlsext_host_name'
AA    cnx.set_tlsext_host_name(server_hostname)
AA  File "/share/HDC_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 296, in ssl_wrap_socket
AA    ssl_version=resolved_ssl_version)
AA  File "/share/HDC_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connection.py", line 238, in connect
AA    conn.connect()
AA  File "/share/HDC_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 762, in _validate_conn
AA    self._validate_conn(conn)
AA  File "/share/HDC_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
AA    body=body, headers=headers)
AA  File "/share/HDC_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
AA    timeout=timeout
AA  File "/share/HDC_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/adapters.py", line 370, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/share/HDC_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/cachecontrol/adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/share/HDC_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/share/HDC_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "/share/HDC_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 476, in get
AA    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "/share/HDC_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1622, in getURL
2015-10-01 06:00:41 WARNING  SEARCHQUEUE-BACKLOG-295721 :: [KickAssTorrents] :: Traceback (most recent call last):
2015-10-01 06:00:41 WARNING  SEARCHQUEUE-BACKLOG-295721 :: [KickAssTorrents] :: Unknown exception in getURL https://kat.cr/usearch/ Error: '_socketobject' object has no attribute 'set_tlsext_host_name'
2015-10-01 06:00:40 DEBUG    SEARCHQUEUE-BACKLOG-295721 :: [KickAssTorrents] :: Search string: {'q': u'The.Muppets S01E02|1x02', 'field': 'seeders', 'category': 'tv', 'sorder': 'desc', 'rss': 1}
2015-10-01 06:00:40 DEBUG    SEARCHQUEUE-BACKLOG-295721 :: [KickAssTorrents] :: search_strings = [{'Episode': [u'The.Muppets S01E02|1x02']}]
2015-10-01 06:00:40 INFO     SEARCHQUEUE-BACKLOG-295721 :: [KickAssTorrents] :: Performing episode search for The Muppets

**Comment by SiCKRAGEB0T** [comment]
Thanks for the bug/issue report! Please sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), other wise we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.
For basic **questions* use the [forum](https://sickrage.tv/forums/), and for **Feature Requests** [Feathub](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Many issues can simply be solved by:
- Making sure you update to the latest version.
- Using the **search** function to see if this issue has already been reported/solved.
- Checking out the [Wiki](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [Config/Install Guides](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [Main settings explained](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [Show settings explained](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) and [Remaining settings explained](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cachemako` & `cachesessions` folders.
- If SickRage doesnt find any episodes you probably need to add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering) or check if you have the [default episode status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) set to `wanted`
- If you use a QNAP try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- Have you tried turning it off and on again?

ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.

**Comment by neoatomic** [comment]
http://apps.qnap.community/11-community/17-qsickrage

**Comment by rd1** [comment]
i'm getting a lot of "Unknown exception in getURL" warnings in the logs for Kat

Qnap, Arm cpu
SR Version:	BRANCH: (master) / COMMIT: (0b2254c884f833bbb54b8c7e6f6231f4d61557d0) 
Python Version:	2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]


2015-10-04 06:34:18 SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: Unknown exception in getURL https://kat.cr/tv/ Error: '_socketobject' object has no attribute 'set_tlsext_host_name'
2015-10-04 06:34:18 SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: Traceback (most recent call last):
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1622, in getURL
    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 762, in _validate_conn
    conn.connect()
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 296, in ssl_wrap_socket
    cnx.set_tlsext_host_name(server_hostname)
AttributeError: '_socketobject' object has no attribute 'set_tlsext_host_name'




repeat that 70 times since last night.
