### ISSUE TITLE
[APP SUBMITTED]: <MatchTree: root=-FQM.Live.Free.or.Twi-hard> is not in list

### ISSUE THREAD

**Issue by Inervo** [SiCKRAGETV/sickrage-issues#3048]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 23:30:53) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@4d37c1352e1a27023ffd520a4da8ab0f024333e6
No Log available with ERRORS: 
### ERROR
```
FINDSUBTITLES :: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/tv.py", line 1491, in downloadSubtitles
    foundSubs = subliminal.download_best_subtitles([video], languages=languages, providers=providers, single=not sickbeard.SUBTITLES_MULTI, hearing_impaired=False)
  File "/usr/local/sickrage/var/SickRage/lib/subliminal/api.py", line 88, in download_best_subtitles
    for subtitle, score in sorted([(s, s.compute_score(video)) for s in video_subtitles],
  File "/usr/local/sickrage/var/SickRage/lib/subliminal/subtitle.py", line 131, in compute_score
    initial_matches = self.compute_matches(video)
  File "/usr/local/sickrage/var/SickRage/lib/subliminal/providers/opensubtitles.py", line 62, in compute_matches
    matches |= compute_guess_matches(video, guessit.guess_episode_info(self.movie_release_name + '.mkv'))
  File "/usr/local/sickrage/var/SickRage/lib/guessit/__init__.py", line 370, in guess_episode_info
    return guess_file_info(filename, info=info, options=options, type='episode', **kwargs)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/__init__.py", line 302, in guess_file_info
    result.append(_guess_filename(filename, options, **kwargs))
  File "/usr/local/sickrage/var/SickRage/lib/guessit/__init__.py", line 114, in _guess_filename
    mtree = _build_filename_mtree(filename, options=options, **kwargs)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/__init__.py", line 127, in _build_filename_mtree
    mtree = IterativeMatcher(filename, options=merged_options, **kwargs)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/matcher.py", line 120, in __init__
    self._process(transformer, False)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/matcher.py", line 138, in _process
    transformer.process(self.match_tree, self.options)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/transfo/guess_release_group.py", line 223, in process
    GuessFinder(self.guess_release_group, None, self.log, options).process_nodes(mtree.unidentified_leaves())
  File "/usr/local/sickrage/var/SickRage/lib/guessit/matcher.py", line 227, in process_nodes
    self.process_node(node)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/matcher.py", line 286, in process_node
    self.process_node(node, partial_span=relative_span, skip_nodes=next_skip_nodes)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/matcher.py", line 241, in process_node
    matcher_result = self.guess_func(string, node, self.options)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/transfo/guess_release_group.py", line 175, in guess_release_group
    if self.validate_node(leaf, node, True):
  File "/usr/local/sickrage/var/SickRage/lib/guessit/transfo/guess_release_group.py", line 143, in validate_node
    if not self.validate_next_leaves(node):
  File "/usr/local/sickrage/var/SickRage/lib/guessit/transfo/guess_release_group.py", line 126, in validate_next_leaves
    next_leaf = node.root.next_leaf(node)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/matchtree.py", line 318, in next_leaf
    return self._other_leaf(leaf, +1)
  File "/usr/local/sickrage/var/SickRage/lib/guessit/matchtree.py", line 322, in _other_leaf
    index = leaves.index(leaf) + offset
ValueError: <MatchTree: root=-FQM.Live.Free.or.Twi-hard> is not in list

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
Thanks for the bug/issue report! Please sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), other wise we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.
For basic **questions* use the [forum](https://sickrage.tv/forums/), and for **Feature Requests** [Feathub](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Many issues can simply be solved by:
- Making sure you update to the latest version.
- Using the **search** function to see if this issue has already been reported/solved.
- Checking out the [Wiki](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [Config/Install Guides](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [Main settings explained](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [Show settings explained](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) and [Remaining settings explained](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cachemako` & `cachesessions` folders.
- If SickRage doesnt find any episodes you probably need to add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering) or check if you have the [default episode status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) set to `wanted`
- If you use a QNAP try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- Have you tried turning it off and on again?

ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.
