### ISSUE TITLE
Unable to add Emmerdale from thetvdb

### ISSUE THREAD

**Issue by Swsystem-ATuin** [SiCKRAGETV/sickrage-issues#3078]
Branch: Master
Commit hash: f8da2f08a098731dc648794f137177ade2f4bb49
Your operating system and python version: linux Python 2.7.10
What you did: Search and add tv series (Emmerdale)
What happened: Search works as expected but notification after adding that show doesn't exist.
What you expected: Show to be added.

Further details and log entries:
```
2015-10-03 21:17:22 DEBUG    Thread-14 :: Setting permissions for /Storage/Soaps/Emmerdale to 755 as parent directory has 755
2015-10-03 21:17:25 INFO     SHOWQUEUE-ADD :: Starting to add show /Storage/Soaps/Emmerdale
2015-10-03 21:17:25 INFO     SHOWQUEUE-ADD :: theTVDB: {'useZip': False, 'apikey': 'F9C450E78D99172E', 'proxy': '127.0.0.1:8118', 'language': 'en', 'debug': True, 'cache': '/var/lib/sickrage/cache/indexers/theTVDB'}
```
```
==> /var/log/privoxy/privoxy.log <==
127.0.0.1 - - [03/Oct/2015:21:17:25 +0100] "GET http://thetvdb.com/api/F9C450E78D99172E/series/77715/en.xml HTTP/1.1" 200 1233
127.0.0.1 - - [03/Oct/2015:21:17:26 +0100] "GET http://thetvdb.com/api/F9C450E78D99172E/series/77715/all/en.xml HTTP/1.1" 200 216807
```
```
==> /var/log/sickrage/sickrage.log <==
2015-10-03 21:17:31 ERROR    SHOWQUEUE-ADD :: Show name with ID 77715 doesn't exist on theTVDB anymore. If you are using trakt, it will be removed from your TRAKT watchlist. If you are adding manually, try removing the nfo and adding again
Traceback (most recent call last):
  File "/root/SickRage/sickbeard/show_queue.py", line 287, in run
    s = t[self.indexer_id]
  File "/root/SickRage/lib/tvdb_api/tvdb_api.py", line 951, in __getitem__
    self._getShowData(key, self.config['language'], True)
  File "/root/SickRage/lib/tvdb_api/tvdb_api.py", line 920, in _getShowData
    v = self._cleanData(v)
  File "/root/SickRage/lib/tvdb_api/tvdb_api.py", line 674, in _cleanData
    data = data.replace(u"&amp;", u"&")
TypeError: an integer is required
```

```<miigotu> confirmed same problem on IRC and suggested opening issue, ```

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Using the **search** function to see if this issue has already been reported/solved.
- Checking out the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Config/Install Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) and [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering) or check if you have the [default episode status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) set to `wanted`
- If you use a QNAP try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- Have you tried turning it off and on again?

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by OmgImAlexis** [comment]
The show is definitely still there. http://thetvdb.com/?tab=series&id=77715&lid=7

**Comment by neoatomic** [comment]
Getting the same error when adding that show. Not sure what is happening here. Show started in 1972 could it be a date bug.?


```
2015-10-04 14:54:39 INFO     SHOWQUEUE-ADD :: Starting to add show /volume1/video/=_Series_=/=_Nieuw_=/Emmerdale
2015-10-04 14:54:39 INFO     SHOWQUEUE-ADD :: theTVDB: {'useZip': True, 'apikey': 'F9C450E78D99172E', 'cache': '/usr/local/sickrage/var/cache/indexers/theTVDB', 'language': 'nl'}
2015-10-04 14:54:50 ERROR    SHOWQUEUE-ADD :: Show name with ID 77715 doesn't exist on theTVDB anymore. If you are using trakt, it will be removed from your TRAKT watchlist. If you are adding manually, try removing the nfo and adding again
Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/show_queue.py", line 287, in run
    s = t[self.indexer_id]
  File "/usr/local/sickrage/var/SickRage/lib/tvdb_api/tvdb_api.py", line 951, in __getitem__
    self._getShowData(key, self.config['language'], True)
  File "/usr/local/sickrage/var/SickRage/lib/tvdb_api/tvdb_api.py", line 920, in _getShowData
    v = self._cleanData(v)
  File "/usr/local/sickrage/var/SickRage/lib/tvdb_api/tvdb_api.py", line 674, in _cleanData
    data = data.replace(u"&amp;", u"&")
TypeError: an integer is required
```

**Comment by Swsystem-ATuin** [comment]
I've just tested the date theory with "The Brothers (1972)" and that seems to add fine. My initial thought was that there were maybe too many episodes for something to process or the size of the data returned causes a problem, this is however only a guess at the moment.

**Comment by Swsystem-ATuin** [comment]
After some messing about, I've got this importing my changing the _cleanData function in lib/tvdb_api/tvdb_api.py to the below. It's not clean but it may help someone diagnose what's going on here. There was also a point where the strip was throwing "AttributeError: 'datetime.date' object has no attribute 'strip'" so I put a test round the string functions.

    def _cleanData(self, data):
        """Cleans up strings returned by TheTVDB.com

        Issues corrected:
        - Replaces &amp; with &
        - Trailing whitespace
        """
        if isinstance(data, basestring):
            data = data.replace(u"&amp;", u"&")
            data = data.strip()

        return data

Now it seems happier, I imagine there's xml being parsed to non-string and passed to _cleanData somewhere.

2015-10-04 15:24:58 DEBUG    Thread-16 :: Searching for Show with searchterm: Emmerdale on Indexer: theTVDB
2015-10-04 15:25:28 INFO     SHOWQUEUE-ADD :: Starting to add show /Storage/Soaps/Emmerdale
2015-10-04 15:25:28 INFO     SHOWQUEUE-ADD :: theTVDB: {'useZip': True, 'apikey': 'F9C450E78D99172E', 'cache': '/var/lib/sickrage/cache/indexers/theTVDB', 'language': 'en'}
2015-10-04 15:25:34 DEBUG    SHOWQUEUE-ADD :: 77715: Loading show info from database
2015-10-04 15:25:34 INFO     SHOWQUEUE-ADD :: 77715: Unable to find the show in the database
2015-10-04 15:25:34 DEBUG    SHOWQUEUE-ADD :: 77715: Loading show info from theTVDB
2015-10-04 15:25:41 DEBUG    SHOWQUEUE-ADD :: Setter sets location to /Storage/Soaps/Emmerdale
2015-10-04 15:25:41 INFO     SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5
2015-10-04 15:25:41 DEBUG    SHOWQUEUE-ADD :: Retrieving show info from IMDb
2015-10-04 15:25:41 DEBUG    SHOWQUEUE-ADD :: 77715: Loading show info from IMDb

**Comment by Swsystem-ATuin** [comment]
After some more thinking and a bit more work, I'm now convering data to a string in _cleanData with:

data = str(data)

added before the string manipulations, this seems to be working but doesn't explain why datetime objects seemed to be getting passed etc. The previous workaround was generating the below which was why the listing wasn't being imported.

2015-10-04 15:45:18 ERROR    SHOWQUEUE-ADD :: Error with theTVDB, not creating episode list: 'datetime.date' object has no attribute 'split'
Traceback (most recent call last):
  File "/root/SickRage/sickbeard/show_queue.py", line 424, in run
    self.show.loadEpisodesFromIndexer()
  File "/root/SickRage/sickbeard/tv.py", line 587, in loadEpisodesFromIndexer
    ep.loadFromIndexer(tvapi=t)
  File "/root/SickRage/sickbeard/tv.py", line 1775, in loadFromIndexer
    rawAirdate = [int(x) for x in firstaired.split("-")]
AttributeError: 'datetime.date' object has no attribute 'split'
2015-10-04 15:45:18 DEBUG    SHOWQUEUE-ADD :: Traceback (most recent call last):
  File "/root/SickRage/sickbeard/show_queue.py", line 424, in run
    self.show.loadEpisodesFromIndexer()
  File "/root/SickRage/sickbeard/tv.py", line 587, in loadEpisodesFromIndexer
    ep.loadFromIndexer(tvapi=t)
  File "/root/SickRage/sickbeard/tv.py", line 1775, in loadFromIndexer
    rawAirdate = [int(x) for x in firstaired.split("-")]
AttributeError: 'datetime.date' object has no attribute 'split'

**Comment by miigotu** [comment]
I still havent gotten a chance to look into this myself, I have reproduced the error though and determined it was indeed in the tvdb api. Strange that a datetime is there.

I will try and look at it tonight after football, or tomorrow.

**Comment by miigotu** [comment]
I fixed this. Committing a fix soon to develop.

**Comment by miigotu** [comment]
This will be in master soon.
