### ISSUE TITLE
[APP SUBMITTED]: Loaded module _Users_ovidijus_Apps_SickRage_gui_slick_views_home_mako not found in sys.modules

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [SiCKRAGETV/sickrage-issues#3096]
### INFO
Python Version: **2.7.10 (default, Sep 23 2015, 04:34:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)]**
Operating System: **Darwin-15.0.0-x86_64-i386-64bit**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@8985c2f3d5376227aa7603cb9aad574f4341ab33
Link to Log: https://gist.github.com/bd45be9b3918da4cc194
### ERROR
```
Thread-14 :: Failed doing webui callback: Traceback (most recent call last):
  File "/Users/Admin/Apps/SickRage/sickbeard/webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "/Users/Admin/Apps/SickRage/sickbeard/webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/Users/Admin/Apps/SickRage/sickbeard/webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/Users/Admin/Apps/SickRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/Users/Admin/Apps/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/Users/Admin/Apps/SickRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _Users_Admin_Apps_SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by XxUnkn0wnxX** [comment]
i get this error or a error page each time i update sickrage it fails to auto load the page back to home and gets stuck on

![](http://puu.sh/kysOc.png)

**Comment by miigotu** [comment]
It happens when the gui is updated. We dont know how to fix it yet, and has been reported many times.
