### ISSUE TITLE
Updated to latest version

### ISSUE THREAD

**Issue by krash1220** [SiCKRAGETV/sickrage-issues#3118]
BRANCH: (master) / COMMIT: (555ca46fa798c76d608827815816761116e19f02) 
Windows 8.1 Python 2.7

2015-10-05 12:09:21 SHOWQUEUE-ADD :: Unknown exception in getURL http://thetvdb.com/banners/fanart/original/79490-11.jpg Error: error 10054 : An existing connection was forcibly closed by the remote host
2015-10-05 12:09:21 SHOWQUEUE-ADD :: Traceback (most recent call last):
  File "D:\TV\SickRage\sickbeard\helpers.py", line 1622, in getURL
    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
  File "D:\TV\SickRage\lib\requests\sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "D:\TV\SickRage\lib\requests\sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\TV\SickRage\lib\requests\sessions.py", line 613, in send
    r.content
  File "D:\TV\SickRage\lib\requests\models.py", line 733, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "D:\TV\SickRage\lib\requests\models.py", line 656, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "D:\TV\SickRage\lib\requests\packages\urllib3\response.py", line 273, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "D:\TV\SickRage\lib\requests\packages\urllib3\response.py", line 203, in read
    data = self._fp.read(amt)
  File "D:\TV\SickRage\lib\cachecontrol\filewrapper.py", line 49, in read
    data = self.__fp.read(amt)
  File "C:\Python27\lib\httplib.py", line 573, in read
    s = self.fp.read(amt)
  File "C:\Python27\lib\socket.py", line 380, in read
    data = self._sock.recv(left)
error: [Errno 10054] An existing connection was forcibly closed by the remote host

2015-10-05 12:09:21 SHOWQUEUE-ADD :: There was an error trying to retrieve the image, aborting
2015-10-05 12:07:06 SHOWQUEUE-ADD :: MKV seems to be malformed, ignoring embedded subtitles
2015-10-05 12:05:40 SHOWQUEUE-ADD :: Connection error to getURL http://thetvdb.com/banners/fanart/original/281381-6.jpg Error: error HTTPConnectionPool(host='thetvdb.com', port=80): Read timed out.
2015-10-05 12:05:40 SHOWQUEUE-ADD :: There was an error trying to retrieve the image, aborting
2015-10-05 12:03:46 SHOWQUEUE-ADD :: Connection error to getURL http://thetvdb.com/banners/graphical/281381-g3.jpg Error: error ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host'))
2015-10-05 12:03:46 SHOWQUEUE-ADD :: There was an error trying to retrieve the image, aborting

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
`Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)`

**Comment by krash1220** [comment]
I don't even know what the issue is. That's why I included the error log. I updated to the latest version and then got the errors listed above.

**Comment by miigotu** [comment]
You were trying to add `Almost Royal` and thetvdb blocked your connection for some reason.

Stop SR and delete cache/sessions and cache/indexers
