### ISSUE TITLE
[APP SUBMITTED]: Loaded module _opt_sickbeard_gui_slick_views_home_mako not found in sys.modules

### ISSUE THREAD

**Issue by MilhouseVH** [SiCKRAGETV/sickrage-issues#3128]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-4.0.6-v7+-armv7l-with-debian-7.8**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@2380148b926e0e731d7fbac805d3a88c42cf1e31
Link to Log: https://gist.github.com/8e17b0c8a5ac3f694f11
### ERROR
```
Thread-22 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/opt/sickbeard/sickbeard/webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/opt/sickbeard/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/opt/sickbeard/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/opt/sickbeard/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _opt_sickbeard_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by MilhouseVH** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-4.0.6-v7+-armv7l-with-debian-7.8**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@2380148b926e0e731d7fbac805d3a88c42cf1e31
Link to Log: https://gist.github.com/cc4c7c56695ea9dcb997
### ERROR
```
Thread-23 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/opt/sickbeard/sickbeard/webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/opt/sickbeard/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/opt/sickbeard/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/opt/sickbeard/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _opt_sickbeard_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by MilhouseVH** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-4.0.6-v7+-armv7l-with-debian-7.8**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@2380148b926e0e731d7fbac805d3a88c42cf1e31
Link to Log: https://gist.github.com/231330732ca6f4322cb3
### ERROR
```
Thread-35 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/opt/sickbeard/sickbeard/webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/opt/sickbeard/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/opt/sickbeard/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/opt/sickbeard/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _opt_sickbeard_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
@MilhouseVH we has an issue with updating and the mako cache. Stop SR and delete cache/mako

**Comment by MilhouseVH** [comment]
@miigotu: I'm on latest master (3c63ee88e6e6ef033d841986decf7a3086fad7fe), I delete `cache/mako`, restart SR, and continue to have this problem... I notice the addition of https://github.com/SiCKRAGETV/SickRage/pull/3015 but I'm not seeing this message in the log...

`cache/mako` deleted while SR service stopped, then SR service started which creates a new `cache/mako`:
```
neil@raspberrypi ~/.sickbeard $ ps aux|grep sickbeard
neil     16265  3.8  5.9 608956 59612 ?        SNl  04:27   0:50 python2.7 /opt/sickbeard/SickBeard.py --daemon --datadir /home/neil/.sickbeard
neil@raspberrypi ~/.sickbeard $ ls -la cache/mako/
total 24
drwxrwxr-x  4 neil neil 4096 Oct 30 04:27 .
drwxr-xr-x 10 neil neil 4096 Oct 30 04:27 ..
-rw-------  1 neil neil 3317 Oct 30 04:27 inc_defs.mako.py
-rw-------  1 neil neil 2502 Oct 30 04:27 inc_defs.mako.pyc
drwxrwxr-x  2 neil neil 4096 Oct 30 04:27 layouts
drwxrwxr-x  3 neil neil 4096 Oct 30 04:27 opt
```
13 minutes after I cleared `cache/mako`, the following errors occur when clicking on "Show Lists" in the menu - despite the error, the Show Lists page appears to be displayed correctly:
```
2015-10-30 04:40:51 ERROR    Thread-29 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 251, in async_call
    result = function(**kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 646, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/opt/sickbeard/sickbeard/webserve.py", line 102, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/opt/sickbeard/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/opt/sickbeard/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/opt/sickbeard/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _opt_sickbeard_gui_slick_views_home_mako not found in sys.modules
Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 251, in async_call
    result = function(**kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 646, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/opt/sickbeard/sickbeard/webserve.py", line 102, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/opt/sickbeard/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/opt/sickbeard/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/opt/sickbeard/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _opt_sickbeard_gui_slick_views_home_mako not found in sys.modules
2015-10-30 04:40:51 DEBUG    TORNADO :: Failed doing webui request "index": Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 236, in get
    results = yield self.async_call(method)
  File "/opt/sickbeard/tornado/gen.py", line 870, in run
    value = future.result()
  File "/opt/sickbeard/lib/concurrent/futures/_base.py", line 400, in result
    return self.__get_result()
  File "/opt/sickbeard/lib/concurrent/futures/_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "/opt/sickbeard/lib/concurrent/futures/_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "/opt/sickbeard/lib/concurrent/futures/thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 251, in async_call
    result = function(**kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 646, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/opt/sickbeard/sickbeard/webserve.py", line 102, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/opt/sickbeard/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/opt/sickbeard/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/opt/sickbeard/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _opt_sickbeard_gui_slick_views_home_mako not found in sys.modules
```

**Comment by miigotu** [comment]
Very shitty annoying bug. I really just havent been able to figure it out. I found an old bug report on mako about it from like 2006 and made the changes that fixed it for them and no profit.

Someday.
