### ISSUE TITLE
[APP SUBMITTED]: Loaded module _home_pi_SickRage_gui_slick_views_home_mako not found in sys.modules

### ISSUE THREAD

**Issue by count00zero** [SiCKRAGETV/sickrage-issues#3181]
### INFO
Python Version: **2.7.9 (default, Mar  8 2015, 00:52:26) [GCC 4.9.2]**
Operating System: **Linux-4.1.7-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@638270689679f3958d1b593c329e7c6e5cb7448e
No Log available with ERRORS: 
### ERROR
```
Thread-14 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/pi/SickRage/sickbeard/webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "/home/pi/SickRage/sickbeard/webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/home/pi/SickRage/sickbeard/webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/home/pi/SickRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/pi/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/home/pi/SickRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _home_pi_SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by MickHussey** [comment]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]**
Operating System: **Linux-3.18.11+-armv6l-with-debian-7.8**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@638270689679f3958d1b593c329e7c6e5cb7448e
Link to Log: https://gist.github.com/902ba94845445bfaa447
### ERROR
```
Thread-14 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/pi/SickRage/sickbeard/webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "/home/pi/SickRage/sickbeard/webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/home/pi/SickRage/sickbeard/webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/home/pi/SickRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/pi/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/home/pi/SickRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _home_pi_SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rmilyard** [comment]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@bad3e2ebd18493764fcea43da7018d06708710c2
Link to Log: https://gist.github.com/45554a85a0362ab04ed7
### ERROR
```
Thread-13 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _usr_pbi_sickrage_amd64_share_sickrage_SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fragstealern** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@1c57cce2d73d9775acb01f256e07d22a93f4c1f4
Link to Log: https://gist.github.com/8d3f48259ca6968fa6c3
### ERROR
```
Thread-20 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module C__SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fragstealern** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@1c57cce2d73d9775acb01f256e07d22a93f4c1f4
Link to Log: https://gist.github.com/c1c4a28e6fe48dd434fd
### ERROR
```
Thread-17 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module C__SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fragstealern** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@1c57cce2d73d9775acb01f256e07d22a93f4c1f4
Link to Log: https://gist.github.com/f9c0c13080bf6bd600bf
### ERROR
```
Thread-19 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module C__SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fragstealern** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@1c57cce2d73d9775acb01f256e07d22a93f4c1f4
Link to Log: https://gist.github.com/a9c0bfcb05f94a088dad
### ERROR
```
Thread-23 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module C__SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fragstealern** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@1c57cce2d73d9775acb01f256e07d22a93f4c1f4
Link to Log: https://gist.github.com/dfb8683258c7ca950705
### ERROR
```
Thread-22 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module C__SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fragstealern** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@1c57cce2d73d9775acb01f256e07d22a93f4c1f4
Link to Log: https://gist.github.com/9028fe077e2c67455048
### ERROR
```
Thread-26 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module C__SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by OmgImAlexis** [comment]
Shutdown SickRage, delete cache/mako, restart SickRage.

**Comment by rmilyard** [comment]
Where is that located?

**Comment by duramato** [comment]
Sickrage directory

**Comment by rd1** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@1c57cce2d73d9775acb01f256e07d22a93f4c1f4
Link to Log: https://gist.github.com/fd74a0a1e6f20e822772
### ERROR
```
Thread-18 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _share_HDA_DATA__qpkg_SickBeard_TVRage_SickBeard_TVRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rd1** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@1c57cce2d73d9775acb01f256e07d22a93f4c1f4
Link to Log: https://gist.github.com/20a8bd3af8e13d3f8bae
### ERROR
```
Thread-17 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _share_HDA_DATA__qpkg_SickBeard_TVRage_SickBeard_TVRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by rd1** [comment]
### INFO
Python Version: **2.7 (r27:82500, Aug 21 2010, 10:10:43) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@1c57cce2d73d9775acb01f256e07d22a93f4c1f4
Link to Log: https://gist.github.com/53d85395914077510a0e
### ERROR
```
Thread-15 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/share/HDA_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module _share_HDA_DATA__qpkg_SickBeard_TVRage_SickBeard_TVRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by JackDanl** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@1c57cce2d73d9775acb01f256e07d22a93f4c1f4
Link to Log: https://gist.github.com/eb7c25b18f8d93aa17ef
### ERROR
```
Thread-27 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module C__SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by JackDanl** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@1c57cce2d73d9775acb01f256e07d22a93f4c1f4
Link to Log: https://gist.github.com/7fe22567d42947c78877
### ERROR
```
Thread-23 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module C__SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by JackDanl** [comment]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@1c57cce2d73d9775acb01f256e07d22a93f4c1f4
Link to Log: https://gist.github.com/9d2cc9bdb567da579a0a
### ERROR
```
Thread-32 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 265, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 660, in index
    t = PageTemplate(rh=self, file="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 116, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
ImportError: Loaded module C__SickRage_gui_slick_views_home_mako not found in sys.modules

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by miigotu** [comment]
Locate your SickRage cache directory (usually in your data folder where your databases are, which is usually in your SickRage folder unless otherwise configured)

Delete cache/mako folder.
