### ISSUE TITLE
Set episode to wanted results in error.

### ISSUE THREAD

**Issue by mapleleafs89** [SiCKRAGETV/sickrage-issues#319]
I'm having an issue trying to set any number of episodes to wanted status.

I received this plain text html page when I do. I tried switching to master using the gui to see if that resolved it but then sickrage wouldn't start up

```
SR Version:	BRANCH: (master) / COMMIT: (514e9d848fda265ca3c012bc3e41f45918ed4f96) 
SR Config file:	/home/ctrought/apps/sickbeard/config.ini
SR Database file:	/home/ctrought/apps/sickbeard/sickbeard.db
SR Cache Dir:	/home/ctrought/apps/sickbeard/cache
SR Arguments:	['-q', '--daemon', '--nolaunch', '--datadir=/home/ctrought/apps/sickbeard']
SR Web Root:	
Python Version:	2.7.5 (default, Feb 11 2014, 07:46:25) [GCC 4.8.2 20140120 (Red Hat 4.8.2-13)]
```

```
Error

invalid literal for int() with base 10: 'undefined'

Traceback

Traceback (most recent call last): 
File "/home/ctrought/apps/sickbeard/tornado/web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback)) 
File "/home/ctrought/apps/sickbeard/tornado/stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs) 
File "/home/ctrought/apps/sickbeard/tornado/concurrent.py", line 226, in lambda future: callback(future.result())) 
File "/home/ctrought/apps/sickbeard/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result() 
File "/home/ctrought/apps/sickbeard/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "/home/ctrought/apps/sickbeard/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "/home/ctrought/apps/sickbeard/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "/home/ctrought/apps/sickbeard/sickbeard/webserve.py", line 230, in async_call result = function(**kwargs) 
File "/home/ctrought/apps/sickbeard/sickbeard/webserve.py", line 1548, in setStatus if not statusStrings.has_key(int(status)): 
ValueError: invalid literal for int() with base 10: 'undefined' 

Request Info

body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /home/setStatus?show=74709&eps=23x22|23x21|23x20|23x19|23x18|23x17|23x16|23x15|23x14|23x13|23x12|23x11|23x10|23x9|23x8|23x7|23x6|23x5|23x4|23x3|23x2|23x1&status=undefined
query_arguments: {'status': ['undefined'], 'eps': ['23x22|23x21|23x20|23x19|23x18|23x17|23x16|23x15|23x14|23x13|23x12|23x11|23x10|23x9|23x8|23x7|23x6|23x5|23x4|23x3|23x2|23x1'], 'show': ['74709']}
_start_time: 1420158553.12
headers: {'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36', 'Host': '192.168.1.150:8081', 'Referer': 'http://192.168.1.150:8081/home/displayShow?show=74709', 'Cookie': 'plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0; compact_display_state=false; JSESSIONID=rdgzhrl1awyu; jwplayer.volume=50; player-61646d696e=1; advanced_toggle_checked=1; manage_view2=list; snatched_view2=list; soon_view2=thumbs; suggestions_charts_menu_selected=charts; late_view2=list; wanted_view2=details; user="2|1:0|10:1420158222|4:user|44:OTc0OWMyMTVhZWY3MWQ4M2Y5N2YwMjllNmEyYzMxOGM=|e1cb5af513fd700f38e8e7d8b12e57e489bbd7561c4619941eabeb6744b97f0b"'}
host: 192.168.1.150:8081
version: HTTP/1.1
arguments: {'status': 'undefined', 'eps': '23x22|23x21|23x20|23x19|23x18|23x17|23x16|23x15|23x14|23x13|23x12|23x11|23x10|23x9|23x8|23x7|23x6|23x5|23x4|23x3|23x2|23x1', 'show': '74709'}
_finish_time: None
query: show=74709&eps=23x22|23x21|23x20|23x19|23x18|23x17|23x16|23x15|23x14|23x13|23x12|23x11|23x10|23x9|23x8|23x7|23x6|23x5|23x4|23x3|23x2|23x1&status=undefined
path: /home/setStatus
_cookies: Set-Cookie: JSESSIONID=rdgzhrl1awyu Set-Cookie: advanced_toggle_checked=1 Set-Cookie: compact_display_state=false Set-Cookie: jwplayer.volume=50 Set-Cookie: late_view2=list Set-Cookie: manage_view2=list Set-Cookie: player-61646d696e=1 Set-Cookie: plushContainerWidth=100%25 Set-Cookie: plushMultiOps=1 Set-Cookie: plushNoTopMenu=0 Set-Cookie: snatched_view2=list Set-Cookie: soon_view2=thumbs Set-Cookie: suggestions_charts_menu_selected=charts Set-Cookie: user="2|1:0|10:1420158222|4:user|44:OTc0OWMyMTVhZWY3MWQ4M2Y5N2YwMjllNmEyYzMxOGM=|e1cb5af513fd700f38e8e7d8b12e57e489bbd7561c4619941eabeb6744b97f0b" Set-Cookie: wanted_view2=details
method: GET
remote_ip: 192.168.1.37
```

Sickrage Log

```
2015-01-01 19:29:59 Thread-29 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/ctrought/apps/sickbeard/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/home/ctrought/apps/sickbeard/sickbeard/webserve.py", line 1548, in setStatus
    if not statusStrings.has_key(int(status)):
ValueError: invalid literal for int() with base 10: 'undefined'

2015-01-01 19:29:13 Thread-33 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/ctrought/apps/sickbeard/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/home/ctrought/apps/sickbeard/sickbeard/webserve.py", line 1548, in setStatus
    if not statusStrings.has_key(int(status)):
ValueError: invalid literal for int() with base 10: 'undefined'
```

Error when starting sickrage when using master after switching in the gui.
```
[root@rhel7 ~]# systemctl status sickbeard.service
sickbeard.service - SickBeard Daemon
   Loaded: loaded (/usr/lib/systemd/system/sickbeard.service; enabled)
   Active: failed (Result: exit-code) since Thu 2015-01-01 19:27:39 EST; 25s ago
  Process: 27439 ExecStart=/usr/bin/python /home/ctrought/apps/sickbeard/SickBeard.py -q --daemon --nolaunch --datadir=/home/ctrought/apps/sickbeard (code=exited, status=1/FAILURE)

Jan 01 19:27:39 rhel7 python[27439]: File "/home/ctrought/apps/sickbeard/sickbeard/logger.py", line 125, in log_error_and_exit
Jan 01 19:27:39 rhel7 python[27439]: self.log(error_msg, ERROR, *args, **kwargs)
Jan 01 19:27:39 rhel7 python[27439]: File "/home/ctrought/apps/sickbeard/sickbeard/logger.py", line 120, in log
Jan 01 19:27:39 rhel7 python[27439]: classes.ErrorViewer.add(classes.UIError(message))
Jan 01 19:27:39 rhel7 python[27439]: File "/home/ctrought/apps/sickbeard/sickbeard/classes.py", line 275, in __init__
Jan 01 19:27:39 rhel7 python[27439]: self.title = sys.exc_info()[1].message or None
Jan 01 19:27:39 rhel7 python[27439]: AttributeError: 'NoneType' object has no attribute 'message'
Jan 01 19:27:39 rhel7 systemd[1]: sickbeard.service: control process exited, code=exited status=1
Jan 01 19:27:39 rhel7 systemd[1]: Failed to start SickBeard Daemon.
Jan 01 19:27:39 rhel7 systemd[1]: Unit sickbeard.service entered failed state.
```

**Comment by mapleleafs89** [comment]
Hmm well this is odd, I WAS on develop and switched to master in the gui - waiting for sickrage to start and it never did, the error above showed when checking the status. I had to manually do a git checkout develop and start to get it back running. But then the GUI showed I was on master (which I don't think I was) as you can see from the version information in my first post. So I attempted to switch to develop and it failed, I shut sickrage down completely. Did a git checkout master and git pull and then it appears all was corrected, please ignore.
