### ISSUE TITLE
Sickrage wont start with SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by alekslyse** [SiCKRAGETV/sickrage-issues#3194]
Probably after an recent update (everything worked fine yesterday) sickrage wont start anymore. 

It dies with the following (ubuntu 14 os):

Starting SickBeard
Traceback (most recent call last):
  File "SickBeard.py", line 58, in <module>
    import sickbeard
  File "/opt/sickbeard/sickbeard/__init__.py", line 37, in <module>
    from sickbeard import metadata
  File "/opt/sickbeard/sickbeard/metadata/__init__.py", line 22, in <module>
    import kodi, kodi_12plus, mediabrowser, ps3, wdtv, tivo, mede8er
  File "/opt/sickbeard/sickbeard/metadata/kodi.py", line 19, in <module>
    import generic
  File "/opt/sickbeard/sickbeard/metadata/generic.py", line 31, in <module>
    from sickbeard import helpers
  File "/opt/sickbeard/sickbeard/helpers.py", line 66, in <module>
    from sickbeard import logger, classes
  File "/opt/sickbeard/sickbeard/logger.py", line 277
    if title_Error.rsplit(' :: ')[-1] in report.title or
                                                       ^
SyntaxError: invalid syntax

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by alekslyse** [comment]
Branch: master, auto update. 

Last lines from the log:

2015-10-07 18:17:59 DEBUG    CHECKVERSION :: git submodule update --init --recursive : returned successful
2015-10-07 18:17:59 DEBUG    CHECKVERSION :: Executing git rev-parse HEAD with your shell in /opt/sickbeard
2015-10-07 18:17:59 DEBUG    CHECKVERSION :: git rev-parse HEAD : returned successful
2015-10-07 18:17:59 INFO     CHECKVERSION :: Update was successful!
2015-10-07 18:17:59 DEBUG    CHECKVERSION :: check_for_new_news: Checking GitHub for latest news.
2015-10-07 18:17:59 INFO     EVENT-QUEUE :: Aborting all threads
2015-10-07 18:17:59 INFO     EVENT-QUEUE :: Waiting for the EVENTS thread to exit
2015-10-07 18:17:59 INFO     EVENT-QUEUE :: Waiting for the DAILYSEARCH thread to exit
2015-10-07 18:17:59 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: Transaction with 2 queries executed
2015-10-07 18:17:59 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: Transaction with 419 queries executed
2015-10-07 18:17:59 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Transaction with 419 queries executed
2015-10-07 18:18:00 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: Transaction with 419 queries executed
2015-10-07 18:18:00 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [NyaaTorrents] :: Transaction with 419 queries executed
2015-10-07 18:18:00 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2015-10-07 18:18:00 INFO     EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2015-10-07 18:18:01 INFO     EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2015-10-07 18:18:01 INFO     EVENT-QUEUE :: Waiting for the VERSIONCHECKER thread to exit
2015-10-07 18:18:01 INFO     EVENT-QUEUE :: Waiting for the SHOWQUEUE thread to exit
2015-10-07 18:18:02 INFO     EVENT-QUEUE :: Waiting for the SEARCHQUEUE thread to exit
2015-10-07 18:18:03 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSER thread to exit
2015-10-07 18:18:03 INFO     EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2015-10-07 18:18:04 INFO     EVENT-QUEUE :: Waiting for the PROPERFINDER thread to exit
2015-10-07 18:18:05 INFO     EVENT-QUEUE :: Waiting for the SUBTITLESFINDER thread to exit
2015-10-07 18:18:06 INFO     EVENT-QUEUE :: Saving all shows to the database
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 76290: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 262414: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 273181: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 261106: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 80727: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 269586: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 70760: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 78957: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 272127: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 259249: Saving show info to database
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 121361: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 83610: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 183831: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 273761: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 95011: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 73388: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 272737: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 76733: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 250181: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 268592: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 77666: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 80379: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 95021: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 269644: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 260449: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 76808: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 260586: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 167751: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 205281: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 79490: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 269640: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 253273: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 168571: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 92091: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 267788: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 277462: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 281381: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 80273: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 255326: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 248618: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 175001: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 269602: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 257655: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 159651: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 261181: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 74626: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 260980: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 279977: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 277169: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 280494: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 274431: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 161511: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 281620: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 153021: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 279121: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 281532: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 281511: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 281458: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 287534: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 111051: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 204371: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 76706: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 72549: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 76237: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 208111: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 207621: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 247808: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 79313: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 74608: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 71221: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 271671: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 83642: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 288064: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 75795: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 276804: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 100981: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 279553: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 72829: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 219331: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 261926: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 274827: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 228041: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 269895: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 126681: Saving show info to database
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 104891: Saving show info to database
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 259063: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 281630: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 281618: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 257715: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 224361: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 257609: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 117701: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 272644: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 281622: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 281700: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 281593: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 134441: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 254203: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 264416: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 291056: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 268619: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 267736: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 74379: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 74549: Saving show info to database
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 74897: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 293583: Saving show info to database
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 281977: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 80691: Saving show info to database
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 83497: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 295583: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 83051: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 289590: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 292174: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 281534: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 298997: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 239851: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 283468: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 279033: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 278469: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 281592: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 295680: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 281367: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 279201: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 71663: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 281536: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 248835: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 290853: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 294169: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 78874: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 83268: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 286522: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 269689: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 295743: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 295778: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 295515: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 295647: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 295555: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 295682: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 298566: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 293302: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 295780: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 295777: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 295681: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 295759: Not saving show to db - record is not dirty
2015-10-07 18:18:06 DEBUG    EVENT-QUEUE :: 264234: Not saving show to db - record is not dirty
2015-10-07 18:18:06 INFO     EVENT-QUEUE :: Saving config file to disk
2015-10-07 18:18:06 INFO     EVENT-QUEUE :: Shutting down Tornado
2015-10-07 18:18:06 INFO     EVENT-QUEUE :: Restarting SickRage with ['/usr/bin/python', '/opt/sickbeard/SickBeard.py', '-q', '--daemon', '--nolaunch', '--pidfile=/var/run/sickbeard/sickbeard.pid', '--datadir=/opt/sickbeard']

**Comment by fernandog** [comment]
Git pull

**Comment by kossboss** [comment]
You could try git pull as recommended by fernandog, or git reset hard.

    cd /yoursickragedir
    git pull

Here is how to do a hard reset:

Stop SickRage, SSH(Linux)/CMD(Windows) and enter SickRage folder

    cd /yoursickragedir
    git remote set-url origin https://github.com/SiCKRAGETV/SickRage.git
    git fetch origin
    git checkout master
    git branch -u origin/master
    git reset --hard origin/master
    git pull

See if that works.

If it doesnt, try to do the same methods but also backup your cache.db and failed.db and delete them and try again. (just dont delete your sickbeard.db)
