### ISSUE TITLE
Can't delete shows

### ISSUE THREAD

**Issue by gabryk91** [SiCKRAGETV/sickrage-issues#321]
Branch develop, last commit, win 8.1 x64

When pressing "Remove" button on a show, it returns a white page with this error:

Error

503 Server Error: Service Unavailable
Traceback

Traceback (most recent call last):
File "C:\SickRage\tornado\web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback))
File "C:\SickRage\tornado\stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs)
File "C:\SickRage\tornado\concurrent.py", line 226, in lambda future: callback(future.result()))
File "C:\SickRage\lib\concurrent\futures\_base.py", line 400, in result return self.__get_result()
File "C:\SickRage\lib\concurrent\futures\_base.py", line 359, in __get_result reraise(self._exception, self._traceback)
File "C:\SickRage\lib\concurrent\futures\_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_)
File "C:\SickRage\lib\concurrent\futures\thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs)
File "C:\SickRage\sickbeard\webserve.py", line 230, in async_call result = function(**kwargs)
File "C:\SickRage\sickbeard\webserve.py", line 1442, in deleteShow sickbeard.traktCheckerScheduler.action.removeShowFromTraktLibrary(showObj)
File "C:\SickRage\sickbeard\traktChecker.py", line 85, in removeShowFromTraktLibrary if self.findShow(show_obj.indexer, show_obj.indexerid):
File "C:\SickRage\sickbeard\traktChecker.py", line 62, in findShow library = self.trakt_api.traktRequest("user/library/shows/all.json/%APIKEY%/%USER%")
File "C:\SickRage\lib\trakt\trakt.py", line 35, in traktRequest raise traktServerBusy(e)
traktServerBusy: 503 Server Error: Service Unavailable
Request Info

body:
files: {}
protocol: http
connection:
body_arguments: {}
uri: /home/deleteShow?show=281709&full=1
query_arguments: {'full': ['1'], 'show': ['281709']}
_start_time: 1420189464.93
headers: {'Accept-Language': 'it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0', 'Host': 'localhost:8081', 'Referer': 'http://localhost:8081/home/displayShow?show=281709', 'Cookie': 'sortby=name; _ga=GA1.1.398267758.1411318361; SESSION-GUID=h4ktmv7dv6v; advanced_toggle_checked=1; wanted_view2=details; manage_view2=details; snatched_view2=list; soon_view2=thumbs; suggestions_charts_menu_selected=charts; late_view2=list'}
host: localhost:8081
version: HTTP/1.1
arguments: {'full': '1', 'show': '281709'}
_finish_time: None
query: show=281709&full=1
path: /home/deleteShow
method: GET
remote_ip: 127.0.0.1

**Comment by fernandog** [comment]
not an issue

**Comment by gabryk91** [comment]
What do you mean "not an issue"?

**Comment by fernandog** [comment]
Service Unavailable = Trakt it not available at the moment.
The show was removed but not from trakt.

**Comment by gabryk91** [comment]
Ah OK sorry, thanks for explaining
Il 02/gen/2015 12:29 "Fernando" <notifications@github.com> ha scritto:

**Comment by gabryk91** [comment]
I think there's something wrong with trakt... the page http://trakt.tv/settings/api return a 404 error, maybe they changed something? Testing SR trakt settings with apposite test button, that once worked, now return error Bad gateway

**Comment by fernandog** [comment]
It's not API anymore.

It's token based authentication
http://trakt.tv/oauth/authorized_applications

**Comment by gabryk91** [comment]
Ok thanks
