### ISSUE TITLE
[APP SUBMITTED]: u'_layouts_main_mako'

### ISSUE THREAD

**Issue by francisconora** [SiCKRAGETV/sickrage-issues#3228]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 18:49:44) [GCC 4.6.4]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@c0a1e4335dac26e97d4375ad2c56f2aeb836a7a8
Link to Log: https://gist.github.com/16e9bfbb3f8ecd80c150
### ERROR
```
Thread-15 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 4885, in index
    return t.render(header="Logs &amp; Errors", title="Logs &amp; Errors", topmenu="system", submenu=self.ErrorLogsMenu(level), logLevel=level)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 141, in render
    return super(PageTemplate, self).render(*args, **kwargs)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 834, in _render_context
    (inherit, lclcontext) = _populate_self_namespace(context, tmpl)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 780, in _populate_self_namespace
    ret = template.module._mako_inherit(template, context)
  File "/usr/local/sickbeard-custom/var/cache/mako/usr/local/sickbeard-custom/var/SickBeard/gui/slick/views/errorlogs.mako.py", line 31, in _mako_inherit
    return runtime._inherit_from(context, u'/layouts/main.mako', _template_uri)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 739, in _inherit_from
    template = _lookup_template(context, uri, calling_uri)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/runtime.py", line 769, in _lookup_template
    return lookup.get_template(uri)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/lookup.py", line 245, in get_template
    return self._load(srcfile, uri)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/lookup.py", line 311, in _load
    **self.template_args)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/mako/template.py", line 380, in _compile_from_file
    del sys.modules[self.module_id]
KeyError: u'_layouts_main_mako'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
Shutting down SickRage and removing the cache/mako & cache/sessions folders.

**Comment by rjohnsen65** [comment]
### INFO
Python Version: **2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]**
Operating System: **Linux-3.4.6-i686-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@9e00354545b81d96007afe1a3c02da852b0f10e1
Link to Log: https://gist.github.com/b91546d4335a408f3052
### ERROR
```
Thread-15 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/webserve.py", line 251, in async_call
    result = function(**kwargs)
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/webserve.py", line 659, in index
    return t.render(title="Home", header="Show List", topmenu="home", showlists=showlists)
  File "/share/MD0_DATA/.qpkg/SickRage/sickbeard/webserve.py", line 142, in render
    return super(PageTemplate, self).render(*args, **kwargs)
  File "/share/MD0_DATA/.qpkg/SickRage/lib/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/share/MD0_DATA/.qpkg/SickRage/lib/mako/runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "/share/MD0_DATA/.qpkg/SickRage/lib/mako/runtime.py", line 834, in _render_context
    (inherit, lclcontext) = _populate_self_namespace(context, tmpl)
  File "/share/MD0_DATA/.qpkg/SickRage/lib/mako/runtime.py", line 780, in _populate_self_namespace
    ret = template.module._mako_inherit(template, context)
  File "/share/MD0_DATA/.qpkg/SickRage/cache/mako/share/MD0_DATA/.qpkg/SickRage/gui/slick/views/home.mako.py", line 68, in _mako_inherit
    return runtime._inherit_from(context, u'/layouts/main.mako', _template_uri)
  File "/share/MD0_DATA/.qpkg/SickRage/lib/mako/runtime.py", line 739, in _inherit_from
    template = _lookup_template(context, uri, calling_uri)
  File "/share/MD0_DATA/.qpkg/SickRage/lib/mako/runtime.py", line 769, in _lookup_template
    return lookup.get_template(uri)
  File "/share/MD0_DATA/.qpkg/SickRage/lib/mako/lookup.py", line 245, in get_template
    return self._load(srcfile, uri)
  File "/share/MD0_DATA/.qpkg/SickRage/lib/mako/lookup.py", line 311, in _load
    **self.template_args)
  File "/share/MD0_DATA/.qpkg/SickRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/share/MD0_DATA/.qpkg/SickRage/lib/mako/template.py", line 380, in _compile_from_file
    del sys.modules[self.module_id]
KeyError: u'_layouts_main_mako'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
