### ISSUE TITLE
FINDPROPERS: Proper instance has no attribute 'resultType'

### ISSUE THREAD

**Issue by neoatomic** [SiCKRAGETV/sickrage-issues#323]
Some properFinder errors i get in my log.

```
SR Version: 	BRANCH: (develop) / COMMIT: (8b84e4f4bc6cdebdc605438e9e75d15f1133d65e)
SR Config file:	/usr/local/sickbeard-custom/var/config.ini
SR Database file:	/usr/local/sickbeard-custom/var/sickbeard.db
SR Cache Dir:	/usr/local/sickbeard-custom/var/cache
SR Arguments:	['--daemon', '--pidfile', '/usr/local/sickbeard-custom/var/sickbeard-custom.pid', '--config', '/usr/local/sickbeard-custom/var/config.ini', '--datadir', '/usr/local/sickbeard-custom/var/', '--nolaunch']
```

```
2015-01-02 16:57:14 DEBUG    FINDPROPERS :: Unable to parse the filename Adventure.Time.S06E21.The.Dentist.PROPER.720p.HDTV.x264-W4F into a valid show
2015-01-02 16:57:14 DEBUG    FINDPROPERS :: Using ALL regexes
2015-01-02 16:57:14 DEBUG    FINDPROPERS :: Parsed The.Walking.Dead.S05E08.REPACK.720p.HDTV.x264-KILLERS into The Walking Dead - S5E8 [ANIME VER: -1] [GROUP: KILLERS] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-01-02 16:57:14 DEBUG    FINDPROPERS :: Successful match! Result The.Walking.Dead.S05E08.REPACK.720p.HDTV.x264-KILLERS matched to show The Walking Dead
2015-01-02 16:57:14 DEBUG    FINDPROPERS :: Picking the best result out of [u'The.Walking.Dead.S05E08.REPACK.720p.HDTV.x264-KILLERS']
2015-01-02 16:57:14 ERROR    FINDPROPERS :: Exception generated in thread FINDPROPERS: Proper instance has no attribute 'resultType'
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/scheduler.py", line 80, in run
    self.action.run(self.force)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/properFinder.py", line 52, in run
    propers = self._getProperList()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/properFinder.py", line 149, in _getProperList
    bestResult = pickBestResult(curProper)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 204, in pickBestResult
    if cur_result.resultType == "torrent" and sickbeard.TORRENT_METHOD != "blackhole":
AttributeError: Proper instance has no attribute 'resultType'
2015-01-02 16:57:14 DEBUG    FINDPROPERS :: 'Traceback (most recent call last):\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/scheduler.py", line 80, in run\n    self.action.run(self.force)\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/properFinder.py", line 52, in run\n    propers = self._getProperList()\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/properFinder.py", line 149, in _getProperList\n    bestResult = pickBestResult(curProper)\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 204, in pickBestResult\n    if cur_result.resultType == "torrent" and sickbeard.TORRENT_METHOD != "blackhole":\nAttributeError: Proper instance has no attribute \'resultType\'\n'
```

This error is given with only http://opennzb.net/ other newznab providers dont give this error.
Need to add that opennzb.net does not require a API key, so thats a difference from other providers.

```
2015-01-02 16:55:54 INFO     FINDPROPERS :: [opennzb.net] :: Searching for any new PROPER releases from opennzb.net
2015-01-02 16:55:54 DEBUG    FINDPROPERS :: [opennzb.net] :: Search url: https://opennzb.net/api?maxage=4&cat=5020%2C5030%2C5040%2C5050&q=.proper.&limit=100&attrs=rageid&offset=0&t=tvsearch
2015-01-02 16:56:04 DEBUG    FINDPROPERS :: [opennzb.net] :: -16 No more searches needed, could find anything I was looking for! 100 items.
2015-01-02 16:56:04 ERROR    FINDPROPERS :: [opennzb.net] :: Error while searching opennzb.net, skipping: published_parsed
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/properFinder.py", line 85, in _getProperList
    curPropers = curProvider.findPropers(search_date)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/newznab.py", line 362, in findPropers
    result_date = datetime.datetime(*item['published_parsed'][0:6])
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/feedparser/feedparser.py", line 353, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'published_parsed'
2015-01-02 16:56:04 DEBUG    FINDPROPERS :: [opennzb.net] :: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/properFinder.py", line 85, in _getProperList
    curPropers = curProvider.findPropers(search_date)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/newznab.py", line 362, in findPropers
    result_date = datetime.datetime(*item['published_parsed'][0:6])
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/feedparser/feedparser.py", line 353, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'published_parsed'

2015-01-02 16:56:04 INFO     FINDPROPERS :: [nzbtv.net] :: Searching for any new PROPER releases from nzbtv.net

```

When trying to submit the errors to GIT hub from the webui i get this. :

```
2015-01-02 18:29:01 ERROR    Thread-55 :: cannot concatenate 'str' and 'exceptions.AttributeError' objects
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/logger.py", line 192, in submit_errors
    issue = gh.get_organization(gh_org).get_repo(gh_repo).create_issue("[APP SUBMITTED]: " + curError.title, message)
TypeError: cannot concatenate 'str' and 'exceptions.AttributeError' objects

```

**Comment by Vodka2014** [comment]
Since the update that was released today the Propers is getting processed and no errors in the SickRage Logs. I just need a proper to get updated to the nab sites to see if it grabs it. Other then that all looking good so far.

**Comment by markheloking** [comment]
Lets close it then. If you see that anything is still off, please reopen/report back @Vodka2014 .

**Comment by Vodka2014** [comment]
So i just added a new show and it did find the PROPER Releases :)

**Comment by ajp2k13** [comment]
I'm still seeing this on dev branch...

SR Version: 	BRANCH: (develop) / COMMIT: (91cb8d885ca278e5829ed53d856d578c8ee8cbe0)
SR Config file:	/usr/local/sickbeard-custom/var/config.ini
SR Database file:	/usr/local/sickbeard-custom/var/sickbeard.db
SR Cache Dir:	/usr/local/sickbeard-custom/var/cache
SR Arguments:	['--daemon', '--pidfile', '/usr/local/sickbeard-custom/var/sickbeard-custom.pid', '--config', '/usr/local/sickbeard-custom/var/config.ini', '--datadir', '/usr/local/sickbeard-custom/var/', '--nolaunch']
SR Web Root:	
Python Version:	2.7.8 (default, Dec 12 2014, 20:41:51) [GCC 4.6.4]

**Comment by fernandog** [comment]
@ajp2k13 I'm not cause I didn't see your log =)

**Comment by ajp2k13** [comment]
Sorry, I knew I should have.... ;) Can't do it right now though. I'll try and uncheck some of the providers first and see if it's one of them, I have a feeling it could be... it's just that it seems to have missed a couple of propers yesterday and I got worried.

**Comment by neoatomic** [comment]
I'm still having those FINDPROPERS errors. 
Also not sure why the log is saying "blackhole" as i use Synology DS as torrent client...
Opennzb is the only provider that gives this error. And is the only newsnab provider i have that doesn't need a api key. ("0" is set as key as the help is saying.)

Could this error be caused by having set wrong or non existing category's under opennzb search settings.?  

```
BRANCH: (develop) / COMMIT: (91cb8d885ca278e5829ed53d856d578c8ee8cbe0) 
```

```
2015-01-27 13:32:36 DEBUG    FINDPROPERS :: Parsed Vikings.S01E03.PROPER.VOSTFR.HDTV into Vikings - S1E3 [ANIME VER: -1] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-01-27 13:32:36 DEBUG    FINDPROPERS :: Successful match! Result Vikings.S01E03.PROPER.VOSTFR.HDTV matched to show Vikings
2015-01-27 13:32:36 DEBUG    FINDPROPERS :: Picking the best result out of [u'Vikings.S01E03.PROPER.VOSTFR.HDTV']
2015-01-27 13:32:36 ERROR    FINDPROPERS :: Exception generated in thread FINDPROPERS: Proper instance has no attribute 'resultType'
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/scheduler.py", line 80, in run
    self.action.run(self.force)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/properFinder.py", line 52, in run
    propers = self._getProperList()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/properFinder.py", line 149, in _getProperList
    bestResult = pickBestResult(curProper)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 204, in pickBestResult
    if cur_result.resultType == "torrent" and sickbeard.TORRENT_METHOD != "blackhole":
AttributeError: Proper instance has no attribute 'resultType'
```
``` 
2015-01-27 13:31:33 INFO     FINDPROPERS :: [opennzb.net] :: Searching for any new PROPER releases from opennzb.net
2015-01-27 13:31:33 DEBUG    FINDPROPERS :: [opennzb.net] :: Search url: https://opennzb.net/api?maxage=4&cat=5020%2C5030%2C5040%2C5050&q=.proper.&limit=100&attrs=rageid&offset=0&t=tvsearch
2015-01-27 13:31:43 DEBUG    FINDPROPERS :: [opennzb.net] :: 0 No more searches needed, could find anything I was looking for! 100 items.
2015-01-27 13:31:43 ERROR    FINDPROPERS :: [opennzb.net] :: Error while searching opennzb.net, skipping: published_parsed
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/properFinder.py", line 85, in _getProperList
    curPropers = curProvider.findPropers(search_date)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/newznab.py", line 362, in findPropers
    result_date = datetime.datetime(*item['published_parsed'][0:6])
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/feedparser/feedparser.py", line 353, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'published_parsed'
2015-01-27 13:31:43 DEBUG    FINDPROPERS :: [opennzb.net] :: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/properFinder.py", line 85, in _getProperList
    curPropers = curProvider.findPropers(search_date)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/newznab.py", line 362, in findPropers
    result_date = datetime.datetime(*item['published_parsed'][0:6])
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/feedparser/feedparser.py", line 353, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'published_parsed'
```

**Comment by neoatomic** [comment]
Strange, https://opennzb.net/api?t=c doesn't return any data...
I have disabled opennzb for the time. Will keep an eye on the log if the error comes back or not.

**Comment by abeloin** [comment]
@neoatomic Could you try this pull requests https://github.com/SiCKRAGETV/SickRage/pull/1209

**Comment by abeloin** [comment]
Also if you don't want to wait to long for the results, change in your config.ini "check_propers_interval" to 15m.
Don't forget to revert it back to it's original value after.

**Comment by abeloin** [comment]
@ajp2k13 Could you try this pull request SiCKRAGETV/SickRage#1209?

**Comment by neoatomic** [comment]
I added the changed code in amnually. 

The findproper did just run and got the same error. : 
```
2015-01-27 16:09:44 INFO     FINDPROPERS :: [opennzb.net] :: Searching for any new PROPER releases from opennzb.net
2015-01-27 16:09:44 DEBUG    FINDPROPERS :: [opennzb.net] :: Search url: https://opennzb.net/api?maxage=4&cat=5020%2C5030%2C5040%2C5050&q=.proper.&limit=100&attrs=rageid&offset=0&t=tvsearch
2015-01-27 16:09:48 DEBUG    FINDPROPERS :: [opennzb.net] :: 0 No more searches needed, could find anything I was looking for! 100 items.
2015-01-27 16:09:48 ERROR    FINDPROPERS :: [opennzb.net] :: Error while searching opennzb.net, skipping: published_parsed
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/properFinder.py", line 85, in _getProperList
    curPropers = curProvider.findPropers(search_date)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/newznab.py", line 362, in findPropers
    result_date = datetime.datetime(*item['published_parsed'][0:6])
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/feedparser/feedparser.py", line 353, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'published_parsed'
2015-01-27 16:09:48 DEBUG    FINDPROPERS :: [opennzb.net] :: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/properFinder.py", line 85, in _getProperList
    curPropers = curProvider.findPropers(search_date)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/newznab.py", line 362, in findPropers
    result_date = datetime.datetime(*item['published_parsed'][0:6])
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/feedparser/feedparser.py", line 353, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'published_parsed'

```

**Comment by abeloin** [comment]
@neoatomic It's failing because the doesn't contain a publish date:
```<pubDate>Sun, 06 Jun 2010 17:29:23 +0100</pubDate>```

Will make a fix for it.

**Comment by fernandog** [comment]
@neoatomic  please update SR and report back please. Fix was merged

**Comment by udochrist** [comment]
@fernandog on the latest version and getting the 

2015-01-31 05:09:47 FINDPROPERS :: Exception generated in thread FINDPROPERS: Proper instance has no attribute 'size'

Provider is nzb.su

**Comment by fernandog** [comment]
What about others providers? Try disable this one. We need to exclude a problem with the provider

**Comment by abeloin** [comment]
@neoatomic Do you still have the issue with opennzb.net? As looking at there feed I see a pubdate now.

**Comment by Koal4** [comment]
I've been running SR for a couple of days now and I also noticed this error popping up every time.

**Comment by neoatomic** [comment]
Yes. i still have one of the errors. (the other is gone as i mentioned before.)

```
2015-01-31 19:03:34 FINDPROPERS :: [opennzb.net] :: Error while searching opennzb.net, skipping: published_parsed
```

If pubdate is added and that was the problem. then the other error should be gone tomorrow. Will give an update than.

**Comment by abeloin** [comment]
@neoatomic Can you apply [this commit](https://github.com/abeloin/SickRage/commit/cf6b61e4fe87a355896cc3543b82468b92490c0f)?

**Comment by abeloin** [comment]
@Koal4 Can you open a new issue and provide full log? Thank You

**Comment by neoatomic** [comment]
Now i'm also having the same error as Koal4.
( can't post the log as it doesn't contain the bug anymore..)

```
2015-02-01 19:06:53 FINDPROPERS :: Exception generated in thread FINDPROPERS: Proper instance has no attribute 'size' ```

I just changed the code manually with the new commit.
Will report back tomorrow.

**Comment by neoatomic** [comment]
```
2015-02-03 12:04:35 DEBUG    FINDPROPERS :: Unable to parse the filename Remarkable-men.at.work.s03E10.repack.720p.hdtv.x264 into a valid show
2015-02-03 12:04:35 DEBUG    FINDPROPERS :: Using ALL regexes
2015-02-03 12:04:35 DEBUG    FINDPROPERS :: Parsed The.First.48.S14E02.HDTV.REPACK.x264-CRiMSON into The First 48 - S14E2 [ANIME VER: -1] [GROUP: CRiMSON] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-02-03 12:04:35 DEBUG    FINDPROPERS :: Successful match! Result The.First.48.S14E02.HDTV.REPACK.x264-CRiMSON matched to show The First 48
2015-02-03 12:04:35 DEBUG    FINDPROPERS :: Picking the best result out of [u'The.First.48.S14E02.HDTV.REPACK.x264-CRiMSON']
2015-02-03 12:04:37 INFO     FINDPROPERS :: Quality of The.First.48.S14E02.HDTV.REPACK.x264-CRiMSON is Unknown
2015-02-03 12:04:37 ERROR    FINDPROPERS :: Exception generated in thread FINDPROPERS: Proper instance has no attribute 'size'
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/scheduler.py", line 80, in run
    self.action.run(self.force)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/properFinder.py", line 52, in run
    propers = self._getProperList()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/properFinder.py", line 149, in _getProperList
    bestResult = pickBestResult(curProper, parse_result.show)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 245, in pickBestResult
    if sickbeard.USE_FAILED_DOWNLOADS and failed_history.hasFailed(cur_result.name, cur_result.size,
AttributeError: Proper instance has no attribute 'size'
2015-02-03 12:04:37 DEBUG    FINDPROPERS :: 'Traceback (most recent call last):\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/scheduler.py", line 80, in run\n    self.action.run(self.force)\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/properFinder.py", line 52, in run\n    propers = self._getProperList()\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/properFinder.py", line 149, in _getProperList\n    bestResult = pickBestResult(curProper, parse_result.show)\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 245, in pickBestResult\n    if sickbeard.USE_FAILED_DOWNLOADS and failed_history.hasFailed(cur_result.name, cur_result.size,\nAttributeError: Proper instance has no attribute \'size\'\n'

```

**Comment by Koal4** [comment]
I just changed it and will report back.

Btw here is still a debug log if you need it, still want me to create a new issue for it? (sorry was a bit afk last couple of days)

**Comment by abeloin** [comment]
@Koal4 No need to create a new issue.

By the way you can force the findproper search with:
* Menu manage ->manageSearches.
* Click on force button in section Find Propers Search.

**Comment by abeloin** [comment]
@neoatomic @Koal4 Any update?

**Comment by neoatomic** [comment]
Just tested. Error seems to be gone now with the new code.
Thank you abeloin for your help and supporting Sickrage. :+1:

**Comment by abeloin** [comment]
@neoatomic Great and thank you for testing it.

**Comment by abeloin** [comment]
@fernandog This pull request fixed the issue SiCKRAGETV/SickRage#1283

**Comment by abeloin** [comment]
@timrettop Try this SiCKRAGETV/SickRage#1283 it should fix your attribute size issue

**Comment by Koal4** [comment]
@abeloin  had it in test for last couple of days and it seems to be resolved with your code, thanks :)

**Comment by abeloin** [comment]
@Koal4 Thank you for the testing.

**Comment by timrettop** [comment]
@abeloin I confirm as well, this commit resolves the size error that occurred with me. 

Thanks!

**Comment by ChrisLahaye** [comment]
@neoatomic I believe the value "c" for the t argument isn't specified in the official Newznab documentation, it is "caps" not "c".

**Comment by neoatomic** [comment]
@ChrisLahaye Thanks for reporting.

@fernandog Could you verify what we are using in the Newznab code.?

**Comment by fernandog** [comment]
@ChrisLahaye @neoatomic I'm lost here. is this a new issue? this one is fix/closed, isn't?
