### ISSUE TITLE
Sickrage issues post processing

### ISSUE THREAD

**Issue by thomass02** [SiCKRAGETV/sickrage-issues#324]
Running windows 7. This is what I get from sabnzb:
Traceback (most recent call last):
  File "C:\SickRage\Scripts\nzbToMedia\nzbToMedia.py", line 782, in <module>
    exit(main(sys.argv))
  File "C:\SickRage\Scripts\nzbToMedia\nzbToMedia.py", line 612, in main
    nzbtomedia.initialize(section)
  File "C:\SickRage\Scripts\nzbToMedia\nzbtomedia\__init__.py", line 221, in initialize
    MYAPP = RunningProcess()
  File "C:\SickRage\Scripts\nzbToMedia\nzbtomedia\nzbToMediaUtil.py", line 1098, in __init__
    self.process = WindowsProcess()
  File "C:\SickRage\Scripts\nzbToMedia\nzbtomedia\nzbToMediaUtil.py", line 1113, in __init__
    from win32event import CreateMutex
ImportError: No module named win32event
Exception AttributeError: "WindowsProcess instance has no attribute 'mutex'" in <bound method WindowsProcess.__del__ of <nzbtomedia.nzbToMediaUtil.WindowsProcess instance at 0x034007B0>> ignored

Please help. I have my python path variables. Changed all the nessessary info on the autoprocessMedia.cfg file. Have my categories set up correctly in sab.

Thanks

**Comment by Hellowlol** [comment]
This is a issue for the nzbtomedia board on the forum, but in short your missing pywin32. This isn't needed to run nzbtomedia.
