### ISSUE TITLE
no such column: epiisode

### ISSUE THREAD

**Issue by cwallen19803** [SiCKRAGETV/sickrage-issues#3241]
SR Version:	BRANCH: (master) / COMMIT: (d1118cb1c9114778535b85b7e59758fde57ad9a5) 
SR User:	TVIDEO$
SR Locale:	('en_US', 'cp1252')
SR Config:	C:\SickRage\Data\config.ini
SR Database:	C:\SickRage\Data\sickbeard.db
SR Cache Dir:	C:\SickRage\Data\cache
SR Log Dir:	C:\SickRage\Data\Logs
SR Arguments:	['--nolaunch', '--port=8081', '--datadir=C:\\SickRage\\Data']
Python Version:	2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]

AAOperationalError: no such column: epiisode
AA    return self.connection.cursor().execute(query)
AA  File "C:\SickRage\SickRage\sickbeard\db.py", line 79, in _execute
AA    return self._execute(query, args).fetchall()
AA  File "C:\SickRage\SickRage\sickbeard\db.py", line 96, in execute
AA    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
AA  File "C:\SickRage\SickRage\sickbeard\db.py", line 201, in action
AATraceback (most recent call last):
2015-10-10 07:34:30 ERROR    Thread-16 :: DB error: no such column: epiisode
2015-10-10 07:34:16 INFO     FINDSUBTITLES :: Checking for subtitles
2015-10-10 07:34:16 INFO     MAIN :: Building internal name cache for all shows
2015-10-10 07:34:16 INFO     CHECKVERSION :: Checking for updates using GIT
2015-10-10 07:34:16 INFO     TORNADO :: Starting SickRage on http://0.0.0.0:8081/
2015-10-10 07:34:16 INFO     MAIN :: Forcing web server to port 8081
2015-10-10 07:33:50 INFO     EVENT-QUEUE :: Restarting SickRage with ['C:\\SickRage\\Python\\python.exe', 'C:\\SickRage\\SickRage\\SickBeard.py', '--nolaunch', '--port=8081', '--datadir=C:\\SickRage\\Data']
2015-10-10 07:33:50 INFO     EVENT-QUEUE :: Shutting down Tornado
2015-10-10 07:33:50 INFO     EVENT-QUEUE :: Saving config file to disk
2015-10-10 07:33:38 INFO     EVENT-QUEUE :: Saving all shows to the database
2015-10-10 07:33:37 INFO     EVENT-QUEUE :: Waiting for the SUBTITLESFINDER thread to exit
2015-10-10 07:33:37 INFO     EVENT-QUEUE :: Waiting for the PROPERFINDER thread to exit
2015-10-10 07:33:36 INFO     EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2015-10-10 07:33:35 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSER thread to exit
2015-10-10 07:33:34 INFO     EVENT-QUEUE :: Waiting for the SEARCHQUEUE thread to exit
2015-10-10 07:33:34 INFO     EVENT-QUEUE :: Waiting for the SHOWQUEUE thread to exit
2015-10-10 07:33:33 INFO     EVENT-QUEUE :: Waiting for the VERSIONCHECKER thread to exit
2015-10-10 07:33:33 INFO     EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2015-10-10 07:33:32 INFO     EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2015-10-10 07:33:31 INFO     EVENT-QUEUE :: Waiting for the DAILYSEARCH thread to exit
2015-10-10 07:33:31 INFO     EVENT-QUEUE :: Waiting for the EVENTS thread to exit
2015-10-10 07:33:31 INFO     EVENT-QUEUE :: Aborting all threads
2015-10-10 07:33:17 INFO     Thread-145 :: Config backup successful, updating...
2015-10-10 07:33:04 INFO     Thread-145 :: Config backup in progress...
2015-10-10 07:32:55 INFO     Thread-143 :: Processing completed
2015-10-10 07:32:55 INFO     Thread-143 :: Deleting folder (if it's empty): U:\Torrents\Completed\Continuum.S04E06.HDTV.x264-KILLERS[ettv]
2015-10-10 07:32:55 INFO     Thread-143 :: PostProcessing Path: U:\Torrents\Completed
2015-10-10 07:29:50 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2015-10-10 07:29:49 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2015-10-10 07:29:49 INFO     DAILYSEARCHER :: No new released episodes found ...
2015-10-10 07:29:49 INFO     DAILYSEARCHER :: Searching for new released episodes ...
2015-10-10 07:29:42 INFO     Thread-134 :: Processing completed
2015-10-10 07:29:42 INFO     Thread-134 :: Processing succeeded for U:\Torrents\Completed\Continuum.S04E06.HDTV.x264-KILLERS[ettv]\Continuum.S04E06.HDTV.x264-KILLERS[ettv].mp4
AANone
2015-10-10 07:29:36 ERROR    Thread-133 :: [U:\Torrents\Completed\Continuum.S04E06.HDTV.x264-KILLERS[ettv]\Continuum.S04E06.HDTV.x264-KILLERS[ettv].mp4 : Processing failed: Unable to move the files to their new home]
AANone
2015-10-10 07:29:36 ERROR    Thread-133 :: Problem(s) during processing, failed the following files/folders:  
2015-10-10 07:29:36 INFO     Thread-133 :: Deleting folder (if it's empty): U:\Torrents\Completed\The Blacklist S03E02 2015 HDTV x264 - BLOW
2015-10-10 07:29:35 INFO     Thread-133 :: Deleting folder (if it's empty): U:\Torrents\Completed\Sleepy Hollow S03E02 2015 HDTV x264 - BLOW
2015-10-10 07:29:35 INFO     Thread-133 :: Deleting folder (if it's empty): U:\Torrents\Completed\Last.Man.Standing.US.S05E03.HDTV.x264-LOL[ettv]
2015-10-10 07:29:35 INFO     Thread-133 :: Processing succeeded for U:\Torrents\Completed\Last.Man.Standing.US.S05E03.HDTV.x264-LOL[ettv]\last.man.standing.us.503.hdtv-lol[ettv].mp4
2015-10-10 07:29:25 INFO     Thread-133 :: Processing U:\Torrents\Completed\Last.Man.Standing.US.S05E03.HDTV.x264-LOL[ettv]\last.man.standing.us.503.hdtv-lol[ettv].mp4 (None)
2015-10-10 07:29:24 INFO     Thread-133 :: Deleting folder (if it's empty): U:\Torrents\Completed\Heroes Reborn S01E04 2015 HDTV x264 - AFG
AAEpisodePostProcessingFailedException: Unable to move the files to their new home
AA    raise EpisodePostProcessingFailedException("Unable to move the files to their new home")
AA  File "C:\SickRage\SickRage\sickbeard\postProcessor.py", line 1071, in process
AA    result.result = processor.process()
AA  File "C:\SickRage\SickRage\sickbeard\processTV.py", line 555, in process_media
AATraceback (most recent call last):
2015-10-10 07:29:24 ERROR    Thread-133 :: Processing failed for U:\Torrents\Completed\Continuum.S04E06.HDTV.x264-KILLERS[ettv]\Continuum.S04E06.HDTV.x264-KILLERS[ettv].mp4: Unable to move the files to their new home
AAOSError: [Errno 13] Permission denied
AA    fout = os.open(dst, WRITE_FLAGS)
AA  File "C:\SickRage\SickRage\lib\shutil_custom\__init__.py", line 42, in copyfile_custom
AA    result = function(*args, **kwargs)
AA  File "C:\SickRage\SickRage\sickrage\helper\encoding.py", line 37, in ek
AA    ek(shutil.copyfile, srcFile, destFile)
AA  File "C:\SickRage\SickRage\sickbeard\helpers.py", line 514, in copyFile
AA    copyFile(srcFile, destFile)
AA  File "C:\SickRage\SickRage\sickbeard\helpers.py", line 533, in moveFile
AA    helpers.moveFile(cur_file_path, new_file_path)
AA  File "C:\SickRage\SickRage\sickbeard\postProcessor.py", line 342, in _int_move
AATraceback (most recent call last):
2015-10-10 07:29:24 ERROR    Thread-133 :: Unable to move file U:\Torrents\Completed\Continuum.S04E06.HDTV.x264-KILLERS[ettv]\Continuum.S04E06.HDTV.x264-KILLERS[ettv].mp4 to T:\Continuum\Continuum.S04E06.Final.Hour.mp4: error 13 : Permission denied
2015-10-10 07:29:22 INFO     Thread-133 :: Processing U:\Torrents\Completed\Continuum.S04E06.HDTV.x264-KILLERS[ettv]\Continuum.S04E06.HDTV.x264-KILLERS[ettv].mp4 (None)
2015-10-10 07:29:22 INFO     Thread-133 :: PostProcessing Path: U:\Torrents\Completed
2015-10-10 07:29:16 INFO     Thread-134 :: Processing U:\Torrents\Completed\Continuum.S04E06.HDTV.x264-KILLERS[ettv]\Continuum.S04E06.HDTV.x264-KILLERS[ettv].mp4 (None)
2015-10-10 07:29:15 INFO     Thread-134 :: PostProcessing Path: U:\Torrents\Completed
2015-10-10 07:02:23 INFO     FINDSUBTITLES :: Checking for subtitles
2015-10-10 06:59:59 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2015-10-10 06:59:57 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2015-10-10 06:59:55 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
AAConnectionError: ('Connection aborted.', gaierror(11001, 'getaddrinfo failed'))
AA    raise ConnectionError(err, request=request)
AA  File "C:\SickRage\SickRage\lib\requests\adapters.py", line 415, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "C:\SickRage\SickRage\lib\cachecontrol\adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "C:\SickRage\SickRage\lib\requests\sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "C:\SickRage\SickRage\lib\requests\sessions.py", line 464, in request
AA    return self.request('GET', url, **kwargs)
AA  File "C:\SickRage\SickRage\lib\requests\sessions.py", line 476, in get
AA    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
AA  File "C:\SickRage\SickRage\sickbeard\helpers.py", line 1620, in getURL
AATraceback (most recent call last):
2015-10-10 06:59:53 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Connection error to getURL https://thepiratebay.gd/tv/latest?q=&orderby=7&category=200&type=search&page=0 Error: error ('Connection aborted.', gaierror(11001, 'getaddrinfo failed'))
2015-10-10 06:59:48 INFO     DAILYSEARCHER :: No new released episodes found ...
2015-10-10 06:59:48 INFO     DAILYSEARCHER :: Searching for new released episodes ...

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*
