### ISSUE TITLE
[APP SUBMITTED]: [Errno 8] hostname nor servname provided, or not known

### ISSUE THREAD

**Issue by ThomasDK81** [SiCKRAGETV/sickrage-issues#3250]
### INFO
Python Version: **2.7.9 (default, May 23 2015, 07:37:15) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@4e9e5310f1e41a68e4f568f3a87c4211a3b29a3c
Link to Log: https://gist.github.com/002cb4222c70db906f2f
### ERROR
```
Thread-47 :: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/logger.py", line 276, in submit_errors
    for report in reports:
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/PaginatedList.py", line 48, in __iter__
    newElements = self._grow()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/PaginatedList.py", line 60, in _grow
    newElements = self._fetchNextPage()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/PaginatedList.py", line 158, in _fetchNextPage
    parameters=self.__nextParams
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 212, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 251, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 275, in __requestRaw
    requestHeaders
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 1204, in connect
    HTTPConnection.connect(self)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/httplib.py", line 793, in connect
    self.timeout, self.source_address)
  File "/usr/pbi/sickrage-amd64/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] hostname nor servname provided, or not known

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
Your net was out when trying to submit issues.
