### ISSUE TITLE
POSTPROCESSER dies when processing a corrupt rar file

### ISSUE THREAD

**Issue by regueiro** [SiCKRAGETV/sickrage-issues#3252]
Sometimes my downloads get market as complete on rtorrent but they have some corrupt data
When sickrage tries to unrar the files, one of the rar parts is corrupted so the extraction can't be completed and the expected file is not created.

When sickrage tries to read the extracted file, it doesn't find it because it doesn't exist and the thread dies.

This is the relevant part of the log:
```
2015-10-11 15:27:55 DEBUG    POSTPROCESSER :: Processing folder /media/callisto/*******s/completed/sickrage/Hand.Of.God.S01E04.1080p.WEBRip.x264-FaiLED
2015-10-11 15:27:55 DEBUG    POSTPROCESSER :: Parsed /media/callisto/*******s/completed/sickrage/Hand.Of.God.S01E04.1080p.WEBRip.x264-FaiLED into Hand Of God - S01E04 [GROUP: FaiLED] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-10-11 15:27:55 DEBUG    POSTPROCESSER :: Packed Releases detected: ['hand.of.god.s01e04.1080p.webrip.x264-failed.rar']
2015-10-11 15:27:55 DEBUG    POSTPROCESSER :: Unpacking archive: hand.of.god.s01e04.1080p.webrip.x264-failed.rar
2015-10-11 15:27:56 DEBUG    POSTPROCESSER :: Parsed /media/callisto/*******s/completed/sickrage/Hand.Of.God.S01E04.1080p.WEBRip.x264-FaiLED into Hand Of God - S01E04 [GROUP: FaiLED] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-10-11 15:28:14 DEBUG    Thread-61 :: check_for_new_news: Checking GitHub for latest news.
2015-10-11 15:30:51 DEBUG    POSTPROCESSER :: UnRar content: ['hand.of.god.s01e04.1080p.webrip.x264-failed.mkv']
2015-10-11 15:30:51 DEBUG    POSTPROCESSER :: Found unwanted files: ['hand.of.god.s01e04.1080p.webrip.x264-failed.r00', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r01', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r02', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r03', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r04', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r05', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r06', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r07', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r08', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r09', 'hand.of.god.s01e04.1080p.webrip.x264-failed.rar', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r28', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r29', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r22', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r23', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r20', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r21', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r26', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r27', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r24', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r25', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r13', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r12', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r11', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r10', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r17', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r16', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r15', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r14', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r19', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r18', 'hand.of.god.s01e04.1080p.webrip.x264-failed.nfo', 'hand.of.god.s01e04.1080p.webrip.x264-failed.sfv', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r35', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r34', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r31', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r30', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r33', 'hand.of.god.s01e04.1080p.webrip.x264-failed.r32']
2015-10-11 15:30:51 DEBUG    POSTPROCESSER :: Using cached parse result for: /media/callisto/*******s/completed/sickrage/Hand.Of.God.S01E04.1080p.WEBRip.x264-FaiLED
2015-10-11 15:30:51 INFO     POSTPROCESSER :: Processing /media/callisto/*******s/completed/sickrage/Hand.Of.God.S01E04.1080p.WEBRip.x264-FaiLED/hand.of.god.s01e04.1080p.webrip.x264-failed.mkv (None)
2015-10-11 15:30:51 DEBUG    POSTPROCESSER :: Found result in history: (<sickbeard.tv.TVShow object at 0x7fe1d3089250>, 1, [], 64, -1)
2015-10-11 15:30:51 DEBUG    POSTPROCESSER :: Analyzing name u'hand.of.god.s01e04.1080p.webrip.x264-failed.mkv'
2015-10-11 15:30:51 DEBUG    POSTPROCESSER :: Parsed hand.of.god.s01e04.1080p.webrip.x264-failed into hand of god - S01E04 [GROUP: failed] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-10-11 15:30:51 DEBUG    POSTPROCESSER :: Retrieving episode object for 1x4
2015-10-11 15:30:51 DEBUG    POSTPROCESSER :: 284643: Loading episode details from DB for episode Hand of God S01E04
2015-10-11 15:30:51 DEBUG    POSTPROCESSER :: Setter sets location to /media/proteus/Series/Hand of God/Season 1/Hand of God 1x04 - He So Loved [720p WEB-DL].mkv
2015-10-11 15:30:51 DEBUG    POSTPROCESSER :: Checking if /media/proteus/Series/Hand of God/Season 1/Hand of God 1x04 - He So Loved [720p WEB-DL].nfo exists: True
2015-10-11 15:30:51 DEBUG    POSTPROCESSER :: Checking if /media/proteus/Series/Hand of God/Season 1/Hand of God 1x04 - He So Loved [720p WEB-DL]-thumb.jpg exists: True
2015-10-11 15:30:51 DEBUG    POSTPROCESSER :: Snatch history had a quality in it, using that: 1080p WEB-DL
2015-10-11 15:30:51 DEBUG    POSTPROCESSER :: Quality of the episode we're processing: 64
2015-10-11 15:30:51 DEBUG    POSTPROCESSER :: SB snatched this episode and it is not processed before
2015-10-11 15:30:51 DEBUG    POSTPROCESSER :: Is ep a priority download: True
2015-10-11 15:30:51 DEBUG    POSTPROCESSER :: Snatch history had a version in it, using that: v-1
2015-10-11 15:30:51 ERROR    POSTPROCESSER :: Exception generated in thread POSTPROCESSER: error 2 : No existe el archivo o el directorio
Traceback (most recent call last):
  File "/home/user/sickrage/sickbeard/scheduler.py", line 105, in run
    self.action.run(self.force)
  File "/home/user/sickrage/sickbeard/autoPostProcesser.py", line 55, in run
    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR)
  File "/home/user/sickrage/sickbeard/processTV.py", line 268, in processDir
    process_media(processPath, videoInRar, nzbName, process_method, force, is_priority, result)
  File "/home/user/sickrage/sickbeard/processTV.py", line 555, in process_media
    result.result = processor.process()
  File "/home/user/sickrage/sickbeard/postProcessor.py", line 905, in process
    existing_file_status = self._checkForExistingFile(ep_obj.location)
  File "/home/user/sickrage/sickbeard/postProcessor.py", line 130, in _checkForExistingFile
    if ek(os.path.getsize, existing_file) > ek(os.path.getsize, self.file_path):
  File "/home/user/sickrage/sickrage/helper/encoding.py", line 39, in ek
    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
  File "/usr/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No existe el archivo o el directorio: '/media/callisto/*******s/completed/sickrage/Hand.Of.God.S01E04.1080p.WEBRip.x264-FaiLED/hand.of.god.s01e04.1080p.webrip.x264-failed.mkv'
2015-10-11 15:30:51 DEBUG    POSTPROCESSER :: 'Traceback (most recent call last):\n  File "/home/user/sickrage/sickbeard/scheduler.py", line 105, in run\n    self.action.run(self.force)\n  File "/home/user/sickrage/sickbeard/autoPostProcesser.py", line 55, in run\n    processTV.processDir(sickbeard.TV_DOWNLOAD_DIR)\n  File "/home/user/sickrage/sickbeard/processTV.py", line 268, in processDir\n    process_media(processPath, videoInRar, nzbName, process_method, force, is_priority, result)\n  File "/home/user/sickrage/sickbeard/processTV.py", line 555, in process_media\n    result.result = processor.process()\n  File "/home/user/sickrage/sickbeard/postProcessor.py", line 905, in process\n    existing_file_status = self._checkForExistingFile(ep_obj.location)\n  File "/home/user/sickrage/sickbeard/postProcessor.py", line 130, in _checkForExistingFile\n    if ek(os.path.getsize, existing_file) > ek(os.path.getsize, self.file_path):\n  File "/home/user/sickrage/sickrage/helper/encoding.py", line 39, in ek\n    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)\n  File "/usr/lib/python2.7/genericpath.py", line 49, in getsize\n    return os.stat(filename).st_size\nOSError: [Errno 2] No existe el archivo o el directorio: \'/media/callisto/*******s/completed/sickrage/Hand.Of.God.S01E04.1080p.WEBRip.x264-FaiLED/hand.of.god.s01e04.1080p.webrip.x264-failed.mkv\'\n'
```
If I unrar the file manually, I get the error
```
hand.of.god.s01e04.1080p.webrip.x264-failed.mkv : packed data checksum error in volume hand.of.god.s01e04.1080p.webrip.x264-failed.r18
```

To reproduce:
- Add a rared release split in parts to the watch folder
- Delete one of the parts
- Start sickrage
- The postprocesser thread will die when trying to extract the file

What I expect:
- Postprocesser to show a warning and continue processing the rest of the folder.

I have tried to delete cache/mako, cache/sessions and cache.db but it didn't help.

I'm on master, on commit 4e9e5310f1e41a68e4f568f3a87c4211a3b29a3c, but it has been happening all week.
My OS is Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-65-generic x86_64) and Python 2.7.6.
The full log is at http://pastebin.com/8eacmKjx

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by duramato** [comment]
@miigotu this is what also happen to me , https://www.irccloud.com/pastebin/K2jFfYrh/
one of the part files got curropt
