### ISSUE TITLE
[APP SUBMITTED]: ('The read operation timed out',)

### ISSUE THREAD

**Issue by frriction** [SiCKRAGETV/sickrage-issues#3253]
### INFO
Python Version: **2.7.10 (default, Sep 17 2015, 18:40:31) [GCC 5.2.0]**
Operating System: **Linux-4.1.10-2-ARCH-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SiCKRAGETV/SickRage@4e9e5310f1e41a68e4f568f3a87c4211a3b29a3c
Link to Log: https://gist.github.com/b779b17d59dd14c381e4
### ERROR
```
Thread-55 :: Traceback (most recent call last):
  File "/srv/http/SickRage/sickbeard/logger.py", line 276, in submit_errors
    for report in reports:
  File "/srv/http/SickRage/lib/github/PaginatedList.py", line 48, in __iter__
    newElements = self._grow()
  File "/srv/http/SickRage/lib/github/PaginatedList.py", line 60, in _grow
    newElements = self._fetchNextPage()
  File "/srv/http/SickRage/lib/github/PaginatedList.py", line 158, in _fetchNextPage
    parameters=self.__nextParams
  File "/srv/http/SickRage/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/srv/http/SickRage/lib/github/Requester.py", line 212, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/srv/http/SickRage/lib/github/Requester.py", line 251, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/srv/http/SickRage/lib/github/Requester.py", line 281, in __requestRaw
    output = response.read()
  File "/usr/lib/python2.7/httplib.py", line 596, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python2.7/httplib.py", line 703, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 734, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 621, in read
    v = self._sslobj.read(len or 1024)
SSLError: ('The read operation timed out',)

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by miigotu** [comment]
Github wasnt responding. This is cause by people spamming the issue submitter.

**Comment by fernandog** [comment]
Cant we handle the sockets timout here too?

**Comment by miigotu** [comment]
Its not a socket timeout, its SSLError

**Comment by Skandian** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@d5a336dc0bf98249902ec3c455846624ac19387e
Link to Log: https://gist.github.com/d9fc2ea3213a8e463c3c
### ERROR
```
Thread-69 :: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\logger.py", line 281, in submit_errors
    for report in reports:
  File "C:\SickRage\lib\github\PaginatedList.py", line 48, in __iter__
    newElements = self._grow()
  File "C:\SickRage\lib\github\PaginatedList.py", line 60, in _grow
    newElements = self._fetchNextPage()
  File "C:\SickRage\lib\github\PaginatedList.py", line 158, in _fetchNextPage
    parameters=self.__nextParams
  File "C:\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickRage\lib\github\Requester.py", line 212, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "C:\SickRage\lib\github\Requester.py", line 251, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "C:\SickRage\lib\github\Requester.py", line 281, in __requestRaw
    output = response.read()
  File "C:\Python27\lib\httplib.py", line 596, in read
    s = self._safe_read(self.length)
  File "C:\Python27\lib\httplib.py", line 703, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "C:\Python27\lib\socket.py", line 384, in read
    data = self._sock.recv(left)
  File "C:\Python27\lib\ssl.py", line 734, in recv
    return self.read(buflen)
  File "C:\Python27\lib\ssl.py", line 621, in read
    v = self._sslobj.read(len or 1024)
SSLError: ('The read operation timed out',)

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
User error or SR error? Should we catch that?

**Comment by megabitus98** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@3572446c66615e7876bf996e3eaf4d6d26400a7d
No Log available with ERRORS: 
### ERROR
```
Thread-42 :: Traceback (most recent call last):
  File "J:\SickRage\sickbeard\logger.py", line 281, in submit_errors
    for report in reports:
  File "J:\SickRage\lib\github\PaginatedList.py", line 48, in __iter__
    newElements = self._grow()
  File "J:\SickRage\lib\github\PaginatedList.py", line 60, in _grow
    newElements = self._fetchNextPage()
  File "J:\SickRage\lib\github\PaginatedList.py", line 158, in _fetchNextPage
    parameters=self.__nextParams
  File "J:\SickRage\lib\github\Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "J:\SickRage\lib\github\Requester.py", line 212, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "J:\SickRage\lib\github\Requester.py", line 251, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "J:\SickRage\lib\github\Requester.py", line 281, in __requestRaw
    output = response.read()
  File "C:\Python27\lib\httplib.py", line 596, in read
    s = self._safe_read(self.length)
  File "C:\Python27\lib\httplib.py", line 703, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "C:\Python27\lib\socket.py", line 384, in read
    data = self._sock.recv(left)
  File "C:\Python27\lib\ssl.py", line 734, in recv
    return self.read(buflen)
  File "C:\Python27\lib\ssl.py", line 621, in read
    v = self._sslobj.read(len or 1024)
SSLError: ('The read operation timed out',)

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by repmeer** [comment]
### INFO
Python Version: **2.7.10 (default, Jun  3 2015, 23:30:53) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@5d4bec2c6022a9e2d5ec934791cf80a0b2553a6f
Link to Log: https://gist.github.com/7831dfe188806f8f5822
### ERROR
```
Thread-46 :: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/logger.py", line 281, in submit_errors
    for report in reports:
  File "/usr/local/sickrage/var/SickRage/lib/github/PaginatedList.py", line 48, in __iter__
    newElements = self._grow()
  File "/usr/local/sickrage/var/SickRage/lib/github/PaginatedList.py", line 60, in _grow
    newElements = self._fetchNextPage()
  File "/usr/local/sickrage/var/SickRage/lib/github/PaginatedList.py", line 158, in _fetchNextPage
    parameters=self.__nextParams
  File "/usr/local/sickrage/var/SickRage/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/local/sickrage/var/SickRage/lib/github/Requester.py", line 212, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/local/sickrage/var/SickRage/lib/github/Requester.py", line 251, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/usr/local/sickrage/var/SickRage/lib/github/Requester.py", line 281, in __requestRaw
    output = response.read()
  File "/usr/local/python/lib/python2.7/httplib.py", line 596, in read
    s = self._safe_read(self.length)
  File "/usr/local/python/lib/python2.7/httplib.py", line 703, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/usr/local/python/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/local/python/lib/python2.7/ssl.py", line 734, in recv
    return self.read(buflen)
  File "/usr/local/python/lib/python2.7/ssl.py", line 621, in read
    v = self._sslobj.read(len or 1024)
SSLError: ('The read operation timed out',)

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
