### ISSUE TITLE
[APP SUBMITTED]: undefined entity: line 88, column 44

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#3292]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-57-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@30435190ef8880901df555bcda0d46902ea81fb5
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-79511 :: [KickAssTorrents] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/media/sickrage/sickbeard/providers/kat.py", line 100, in _doSearch\n    data = xmltodict.parse(data.replace(\'&nbsp;\',\'&#xA0;\'))\n  File "/home/media/sickrage/lib/xmltodict.py", line 248, in parse\n    parser.Parse(xml_input, True)\nExpatError: undefined entity: line 88, column 44\n'
'<?xml version="1.0" encoding="UTF-8"?>\n<rss version="2.0" xmlns:torrent="http://xmlns.ezrss.it/0.1/">\n<channel>\n    <title>tv torrents RSS feed - KickassTorrents</title>\n    <link>http://kat.cr/</link>\n    <description>tv torrents RSS feed</description>\n    <item>\n        <title>Torchwood.S02E05.Adam.HDTV.XviD-FoV</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/torchwood-s02e05-adam-hdtv-xvid-fov-t21107.html</link>\n        <guid>http://kat.cr/torchwood-s02e05-adam-hdtv-xvid-fov-t21107.html</guid>\n        <pubDate>Tue, 12 Feb 2008 22:00:00 +0000</pubDate>\n        <torrent:contentLength>367422568</torrent:contentLength>\n        <torrent:infoHash>6bb63ca95813a34a13598ffa3077674009f9502e</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:6bb63ca95813a34a13598ffa3077674009f9502e&dn=torchwood+s02e05+adam+hdtv+xvid+fov&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>3</torrent:seeds>\n        <torrent:peers>4</torrent:peers>\n        <torrent:verified>1</torrent:verified>\n        <torrent:fileName>torchwood.s02e05.adam.hdtv.xvid.fov.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/6BB63CA95813A34A13598FFA3077674009F9502E.torrent?title=[kat.cr]torchwood.s02e05.adam.hdtv.xvid.fov" length="367422568" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>Torchwood.S02E05.720p.HDTV.x264-BiA</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/torchwood-s02e05-720p-hdtv-x264-bia-t22576.html</link>\n        <guid>http://kat.cr/torchwood-s02e05-720p-hdtv-x264-bia-t22576.html</guid>\n        <pubDate>Wed, 13 Feb 2008 22:00:00 +0000</pubDate>\n        <torrent:contentLength>1178929780</torrent:contentLength>\n        <torrent:infoHash>b5d0ecdd5b8772f730fc8d33855e53892161d679</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:b5d0ecdd5b8772f730fc8d33855e53892161d679&dn=torchwood+s02e05+720p+hdtv+x264+bia&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>1</torrent:seeds>\n        <torrent:peers>1</torrent:peers>\n        <torrent:verified>1</torrent:verified>\n        <torrent:fileName>torchwood.s02e05.720p.hdtv.x264.bia.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/B5D0ECDD5B8772F730FC8D33855E53892161D679.torrent?title=[kat.cr]torchwood.s02e05.720p.hdtv.x264.bia" length="1178929780" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>Torchwood.Declassified.S02E05.WS.PDTV.XviD-BiA</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/torchwood-declassified-s02e05-ws-pdtv-xvid-bia-t31778.html</link>\n        <guid>http://kat.cr/torchwood-declassified-s02e05-ws-pdtv-xvid-bia-t31778.html</guid>\n        <pubDate>Fri, 15 Feb 2008 22:00:00 +0000</pubDate>\n        <torrent:contentLength>99357600</torrent:contentLength>\n        <torrent:infoHash>e82ce49bacb04c3971ce2b216e89ea4db812d541</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:e82ce49bacb04c3971ce2b216e89ea4db812d541&dn=torchwood+declassified+s02e05+ws+pdtv+xvid+bia&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>1</torrent:seeds>\n        <torrent:peers>1</torrent:peers>\n        <torrent:verified>1</torrent:verified>\n        <torrent:fileName>torchwood.declassified.s02e05.ws.pdtv.xvid.bia.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/E82CE49BACB04C3971CE2B216E89EA4DB812D541.torrent?title=[kat.cr]torchwood.declassified.s02e05.ws.pdtv.xvid.bia" length="99357600" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>Torchwood S02E05 Adam [MM] HQ Edition (x264-MP3-MKV)</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/torchwood-s02e05-adam-mm-hq-edition-x264-mp3-mkv-t722456.html</link>\n        <guid>http://kat.cr/torchwood-s02e05-adam-mm-hq-edition-x264-mp3-mkv-t722456.html</guid>\n        <pubDate>Tue, 25 Mar 2008 21:50:49 +0000</pubDate>\n        <torrent:contentLength>367921018</torrent:contentLength>\n        <torrent:infoHash>30c9f802e987d529b0ae585a16b377afeb90cde5</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:30c9f802e987d529b0ae585a16b377afeb90cde5&dn=torchwood+s02e05+adam+mm+hq+edition+x264+mp3+mkv&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>1</torrent:seeds>\n        <torrent:peers>1</torrent:peers>\n        <torrent:verified>1</torrent:verified>\n        <torrent:fileName>torchwood.s02e05.adam.mm.hq.edition.x264.mp3.mkv.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/30C9F802E987D529B0AE585A16B377AFEB90CDE5.torrent?title=[kat.cr]torchwood.s02e05.adam.mm.hq.edition.x264.mp3.mkv" length="367921018" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>Torchwood S02E05 720p HDTV x264-BiA</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/torchwood-s02e05-720p-hdtv-x264-bia-t1341580.html</link>\n        <guid>http://kat.cr/torchwood-s02e05-720p-hdtv-x264-bia-t1341580.html</guid>\n        <pubDate>Fri, 15 Feb 2008 03:02:18 +0000</pubDate>\n        <torrent:contentLength>1152795029</torrent:contentLength>\n        <torrent:infoHash>b97f9dc0a175af733721ba0db292008e190c059e</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:b97f9dc0a175af733721ba0db292008e190c059e&dn=torchwood+s02e05+720p+hdtv+x264+bia&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>1</torrent:seeds>\n        <torrent:peers>1</torrent:peers>\n        <torrent:verified>0</torrent:verified>\n        <torrent:fileName>torchwood.s02e05.720p.hdtv.x264.bia.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/B97F9DC0A175AF733721BA0DB292008E190C059E.torrent?title=[kat.cr]torchwood.s02e05.720p.hdtv.x264.bia" length="1152795029" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>Torchwood S02E05 Fr avi{{{WWW&bull;APPOCALIPTEAM&bull;MINE&bull;NU FRENCH}}}</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/torchwood-s02e05-fr-avi-www-bull-appocalipteam-bull-mine-bull-nu-french-t2087640.html</link>\n        <guid>http://kat.cr/torchwood-s02e05-fr-avi-www-bull-appocalipteam-bull-mine-bull-nu-french-t2087640.html</guid>\n        <pubDate>Fri, 20 Feb 2009 16:47:17 +0000</pubDate>\n        <torrent:contentLength>367935488</torrent:contentLength>\n        <torrent:infoHash>7562a0117e5d6bf2ee800960dea0734b2ad027c6</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:7562a0117e5d6bf2ee800960dea0734b2ad027c6&dn=torchwood+s02e05+fr+avi+www+bull+appocalipteam+bull+mine+bull+nu+french&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>1</torrent:seeds>\n        <torrent:peers>1</torrent:peers>\n        <torrent:verified>0</torrent:verified>\n        <torrent:fileName>torchwood.s02e05.fr.avi.www.bull.appocalipteam.bull.mine.bull.nu.french.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/7562A0117E5D6BF2EE800960DEA0734B2AD027C6.torrent?title=[kat.cr]torchwood.s02e05.fr.avi.www.bull.appocalipteam.bull.mine.bull.nu.french" length="367935488" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>Torchwood S02E05 Adam [xvid].avi</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/torchwood-s02e05-adam-xvid-avi-t1231259.html</link>\n        <guid>http://kat.cr/torchwood-s02e05-adam-xvid-avi-t1231259.html</guid>\n        <pubDate>Fri, 22 Aug 2008 04:00:00 +0000</pubDate>\n        <torrent:contentLength>430438400</torrent:contentLength>\n        <torrent:infoHash>8013ad2ee1788dd9715d4818623f3c62c0264c56</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:8013ad2ee1788dd9715d4818623f3c62c0264c56&dn=torchwood+s02e05+adam+xvid+avi&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>0</torrent:seeds>\n        <torrent:peers>0</torrent:peers>\n        <torrent:verified>1</torrent:verified>\n        <torrent:fileName>torchwood.s02e05.adam.xvid.avi.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/8013AD2EE1788DD9715D4818623F3C62C0264C56.torrent?title=[kat.cr]torchwood.s02e05.adam.xvid.avi" length="430438400" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>Torchwood S02E05 Adam [MM] avi</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/torchwood-s02e05-adam-mm-avi-t1334425.html</link>\n        <guid>http://kat.cr/torchwood-s02e05-adam-mm-avi-t1334425.html</guid>\n        <pubDate>Wed, 13 Feb 2008 21:56:28 +0000</pubDate>\n        <torrent:contentLength>366639104</torrent:contentLength>\n        <torrent:infoHash>7adf87d6a5fdbf151e5e995c20e7dce2d82799a3</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:7adf87d6a5fdbf151e5e995c20e7dce2d82799a3&dn=torchwood+s02e05+adam+mm+avi&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>0</torrent:seeds>\n        <torrent:peers>0</torrent:peers>\n        <torrent:verified>1</torrent:verified>\n        <torrent:fileName>torchwood.s02e05.adam.mm.avi.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/7ADF87D6A5FDBF151E5E995C20E7DCE2D82799A3.torrent?title=[kat.cr]torchwood.s02e05.adam.mm.avi" length="366639104" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>Torchwood.S02E05.FRENCH.DVTV.XViD-EPZ</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/torchwood-s02e05-french-dvtv-xvid-epz-t1336204.html</link>\n        <guid>http://kat.cr/torchwood-s02e05-french-dvtv-xvid-epz-t1336204.html</guid>\n        <pubDate>Sun, 21 Sep 2008 22:02:19 +0000</pubDate>\n        <torrent:contentLength>352940398</torrent:contentLength>\n        <torrent:infoHash>3960e0ce389fc4b860fe123f87a55ff7812ac968</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:3960e0ce389fc4b860fe123f87a55ff7812ac968&dn=torchwood+s02e05+french+dvtv+xvid+epz&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>0</torrent:seeds>\n        <torrent:peers>0</torrent:peers>\n        <torrent:verified>0</torrent:verified>\n        <torrent:fileName>torchwood.s02e05.french.dvtv.xvid.epz.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/3960E0CE389FC4B860FE123F87A55FF7812AC968.torrent?title=[kat.cr]torchwood.s02e05.french.dvtv.xvid.epz" length="352940398" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>torchwood s02e05-08 hdtv vostfr-LBP</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/torchwood-s02e05-08-hdtv-vostfr-lbp-t2291207.html</link>\n        <guid>http://kat.cr/torchwood-s02e05-08-hdtv-vostfr-lbp-t2291207.html</guid>\n        <pubDate>Tue, 25 Mar 2008 23:09:03 +0000</pubDate>\n        <torrent:contentLength>1470601216</torrent:contentLength>\n        <torrent:infoHash>899a6b898eb45c9c20e79e271e5105d1c32fc995</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:899a6b898eb45c9c20e79e271e5105d1c32fc995&dn=torchwood+s02e05+08+hdtv+vostfr+lbp&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>0</torrent:seeds>\n        <torrent:peers>0</torrent:peers>\n        <torrent:verified>0</torrent:verified>\n        <torrent:fileName>torchwood.s02e05.08.hdtv.vostfr.lbp.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/899A6B898EB45C9C20E79E271E5105D1C32FC995.torrent?title=[kat.cr]torchwood.s02e05.08.hdtv.vostfr.lbp" length="1470601216" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>Torchwood Declassified S02E05 WS PDTV XviD-BiA WWW PHANTOMBITZ COM</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/torchwood-declassified-s02e05-ws-pdtv-xvid-bia-www-phantombitz-com-t2297165.html</link>\n        <guid>http://kat.cr/torchwood-declassified-s02e05-ws-pdtv-xvid-bia-www-phantombitz-com-t2297165.html</guid>\n        <pubDate>Sat, 16 Feb 2008 22:00:20 +0000</pubDate>\n        <torrent:contentLength>99357600</torrent:contentLength>\n        <torrent:infoHash>6c055868c0f717019f8d91501bf2b39719d5c15a</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:6c055868c0f717019f8d91501bf2b39719d5c15a&dn=torchwood+declassified+s02e05+ws+pdtv+xvid+bia+www+phantombitz+com&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>0</torrent:seeds>\n        <torrent:peers>0</torrent:peers>\n        <torrent:verified>0</torrent:verified>\n        <torrent:fileName>torchwood.declassified.s02e05.ws.pdtv.xvid.bia.www.phantombitz.com.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/6C055868C0F717019F8D91501BF2B39719D5C15A.torrent?title=[kat.cr]torchwood.declassified.s02e05.ws.pdtv.xvid.bia.www.phantombitz.com" length="99357600" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>Torchwood S02E05 NEW WS avi</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/torchwood-s02e05-new-ws-avi-t2297388.html</link>\n        <guid>http://kat.cr/torchwood-s02e05-new-ws-avi-t2297388.html</guid>\n        <pubDate>Thu, 14 Feb 2008 02:53:28 +0000</pubDate>\n        <torrent:contentLength>401081790</torrent:contentLength>\n        <torrent:infoHash>052849adfc68775511b3d61d990f2feb0b176514</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:052849adfc68775511b3d61d990f2feb0b176514&dn=torchwood+s02e05+new+ws+avi&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>0</torrent:seeds>\n        <torrent:peers>0</torrent:peers>\n        <torrent:verified>0</torrent:verified>\n        <torrent:fileName>torchwood.s02e05.new.ws.avi.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/052849ADFC68775511B3D61D990F2FEB0B176514.torrent?title=[kat.cr]torchwood.s02e05.new.ws.avi" length="401081790" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>Torchwood S02E05 ITA[http;//newscine.helloweb.eu]</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/torchwood-s02e05-ita-http-newscine-helloweb-eu-t2298127.html</link>\n        <guid>http://kat.cr/torchwood-s02e05-ita-http-newscine-helloweb-eu-t2298127.html</guid>\n        <pubDate>Wed, 06 Aug 2008 01:10:17 +0000</pubDate>\n        <torrent:contentLength>367003648</torrent:contentLength>\n        <torrent:infoHash>201a052ad033471649662c3f05c65c53e86331ef</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:201a052ad033471649662c3f05c65c53e86331ef&dn=torchwood+s02e05+ita+http+newscine+helloweb+eu&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>0</torrent:seeds>\n        <torrent:peers>0</torrent:peers>\n        <torrent:verified>0</torrent:verified>\n        <torrent:fileName>torchwood.s02e05.ita.http.newscine.helloweb.eu.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/201A052AD033471649662C3F05C65C53E86331EF.torrent?title=[kat.cr]torchwood.s02e05.ita.http.newscine.helloweb.eu" length="367003648" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>Torchwood S02E05 German Dubbed DVDRip XviD-ITG</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/torchwood-s02e05-german-dubbed-dvdrip-xvid-itg-t2788878.html</link>\n        <guid>http://kat.cr/torchwood-s02e05-german-dubbed-dvdrip-xvid-itg-t2788878.html</guid>\n        <pubDate>Wed, 08 Jul 2009 22:02:29 +0000</pubDate>\n        <torrent:contentLength>366678000</torrent:contentLength>\n        <torrent:infoHash>2c445a69eabb0c1f082a064ff952bf7fc5cbb33a</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:2c445a69eabb0c1f082a064ff952bf7fc5cbb33a&dn=torchwood+s02e05+german+dubbed+dvdrip+xvid+itg&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>0</torrent:seeds>\n        <torrent:peers>0</torrent:peers>\n        <torrent:verified>0</torrent:verified>\n        <torrent:fileName>torchwood.s02e05.german.dubbed.dvdrip.xvid.itg.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/2C445A69EABB0C1F082A064FF952BF7FC5CBB33A.torrent?title=[kat.cr]torchwood.s02e05.german.dubbed.dvdrip.xvid.itg" length="366678000" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>Torchwood S02E05 German Dubbed DVDRip XviD-ITG</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/torchwood-s02e05-german-dubbed-dvdrip-xvid-itg-t2797013.html</link>\n        <guid>http://kat.cr/torchwood-s02e05-german-dubbed-dvdrip-xvid-itg-t2797013.html</guid>\n        <pubDate>Fri, 10 Jul 2009 21:05:49 +0000</pubDate>\n        <torrent:contentLength>370823437</torrent:contentLength>\n        <torrent:infoHash>3390c51a2669d1cc8b3c0b7a082ca4e148c8a24a</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:3390c51a2669d1cc8b3c0b7a082ca4e148c8a24a&dn=torchwood+s02e05+german+dubbed+dvdrip+xvid+itg&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>0</torrent:seeds>\n        <torrent:peers>0</torrent:peers>\n        <torrent:verified>0</torrent:verified>\n        <torrent:fileName>torchwood.s02e05.german.dubbed.dvdrip.xvid.itg.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/3390C51A2669D1CC8B3C0B7A082CA4E148C8A24A.torrent?title=[kat.cr]torchwood.s02e05.german.dubbed.dvdrip.xvid.itg" length="370823437" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>Torchwood S02E05 German Dubbed DVDRip XviD-ITG</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/torchwood-s02e05-german-dubbed-dvdrip-xvid-itg-t2799361.html</link>\n        <guid>http://kat.cr/torchwood-s02e05-german-dubbed-dvdrip-xvid-itg-t2799361.html</guid>\n        <pubDate>Sat, 11 Jul 2009 12:46:50 +0000</pubDate>\n        <torrent:contentLength>366678000</torrent:contentLength>\n        <torrent:infoHash>94b7d07f5759c21e1e89fb3b2ee7f3dd57c5fbfa</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:94b7d07f5759c21e1e89fb3b2ee7f3dd57c5fbfa&dn=torchwood+s02e05+german+dubbed+dvdrip+xvid+itg&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>0</torrent:seeds>\n        <torrent:peers>0</torrent:peers>\n        <torrent:verified>0</torrent:verified>\n        <torrent:fileName>torchwood.s02e05.german.dubbed.dvdrip.xvid.itg.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/94B7D07F5759C21E1E89FB3B2EE7F3DD57C5FBFA.torrent?title=[kat.cr]torchwood.s02e05.german.dubbed.dvdrip.xvid.itg" length="366678000" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>Torchwood S02E05 German Dubbed DVDRip XviD-ITG</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/torchwood-s02e05-german-dubbed-dvdrip-xvid-itg-t2804936.html</link>\n        <guid>http://kat.cr/torchwood-s02e05-german-dubbed-dvdrip-xvid-itg-t2804936.html</guid>\n        <pubDate>Sun, 12 Jul 2009 19:55:04 +0000</pubDate>\n        <torrent:contentLength>366678000</torrent:contentLength>\n        <torrent:infoHash>498ffb8be74b5964116c48a90cf6db46f035a95e</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:498ffb8be74b5964116c48a90cf6db46f035a95e&dn=torchwood+s02e05+german+dubbed+dvdrip+xvid+itg&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>0</torrent:seeds>\n        <torrent:peers>0</torrent:peers>\n        <torrent:verified>0</torrent:verified>\n        <torrent:fileName>torchwood.s02e05.german.dubbed.dvdrip.xvid.itg.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/498FFB8BE74B5964116C48A90CF6DB46F035A95E.torrent?title=[kat.cr]torchwood.s02e05.german.dubbed.dvdrip.xvid.itg" length="366678000" type="application/x-bittorrent" />\n    </item>\n    </channel>\n</rss>'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*
