### ISSUE TITLE
[APP SUBMITTED]: undefined entity: line 104, column 47

### ISSUE THREAD

**Issue by OmgImAlexis** [SiCKRAGETV/sickrage-issues#3293]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]**
Operating System: **Linux-3.13.0-57-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: unknown
Branch: **master**
Commit: SiCKRAGETV/SickRage@30435190ef8880901df555bcda0d46902ea81fb5
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-161511 :: [KickAssTorrents] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/media/sickrage/sickbeard/providers/kat.py", line 100, in _doSearch\n    data = xmltodict.parse(data.replace(\'&nbsp;\',\'&#xA0;\'))\n  File "/home/media/sickrage/lib/xmltodict.py", line 248, in parse\n    parser.Parse(xml_input, True)\nExpatError: undefined entity: line 104, column 47\n'
'<?xml version="1.0" encoding="UTF-8"?>\n<rss version="2.0" xmlns:torrent="http://xmlns.ezrss.it/0.1/">\n<channel>\n    <title>tv torrents RSS feed - KickassTorrents</title>\n    <link>http://kat.cr/</link>\n    <description>tv torrents RSS feed</description>\n    <item>\n        <title>Shameless US S03E01 HDTV x264-ASAP [VTV] mp4</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/shameless-us-s03e01-hdtv-x264-asap-vtv-mp4-t6985539.html</link>\n        <guid>http://kat.cr/shameless-us-s03e01-hdtv-x264-asap-vtv-mp4-t6985539.html</guid>\n        <pubDate>Mon, 14 Jan 2013 06:18:03 +0000</pubDate>\n        <torrent:contentLength>631642507</torrent:contentLength>\n        <torrent:infoHash>8B62FED38743C49AD4B7A8FFC8BD8A89FB4D0730</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:8B62FED38743C49AD4B7A8FFC8BD8A89FB4D0730&dn=shameless+us+s03e01+hdtv+x264+asap+vtv+mp4&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>17</torrent:seeds>\n        <torrent:peers>19</torrent:peers>\n        <torrent:verified>0</torrent:verified>\n        <torrent:fileName>shameless.us.s03e01.hdtv.x264.asap.vtv.mp4.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/8B62FED38743C49AD4B7A8FFC8BD8A89FB4D0730.torrent?title=[kat.cr]shameless.us.s03e01.hdtv.x264.asap.vtv.mp4" length="631642507" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>Shameless US S03E01 FASTSUB VOSTFR HDTV XviD-MiND</title>\n\n        <category>TV</category>\n      <author>http://kat.cr/user/maximersk/</author>        <link>http://kat.cr/shameless-us-s03e01-fastsub-vostfr-hdtv-xvid-mind-t6990084.html</link>\n        <guid>http://kat.cr/shameless-us-s03e01-fastsub-vostfr-hdtv-xvid-mind-t6990084.html</guid>\n        <pubDate>Tue, 15 Jan 2013 14:31:16 +0000</pubDate>\n        <torrent:contentLength>575323797</torrent:contentLength>\n        <torrent:infoHash>EB6E3ED61F829884F3F0971274411BB548DAB3F1</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:EB6E3ED61F829884F3F0971274411BB548DAB3F1&dn=shameless+us+s03e01+fastsub+vostfr+hdtv+xvid+mind&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>12</torrent:seeds>\n        <torrent:peers>14</torrent:peers>\n        <torrent:verified>1</torrent:verified>\n        <torrent:fileName>shameless.us.s03e01.fastsub.vostfr.hdtv.xvid.mind.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/EB6E3ED61F829884F3F0971274411BB548DAB3F1.torrent?title=[kat.cr]shameless.us.s03e01.fastsub.vostfr.hdtv.xvid.mind" length="575323797" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>Shameless US S03E01 HDTV XviD AFG</title>\n\n        <category>TV</category>\n      <author>http://kat.cr/user/ettv/</author>        <link>http://kat.cr/shameless-us-s03e01-hdtv-xvid-afg-t6985641.html</link>\n        <guid>http://kat.cr/shameless-us-s03e01-hdtv-xvid-afg-t6985641.html</guid>\n        <pubDate>Mon, 14 Jan 2013 07:05:29 +0000</pubDate>\n        <torrent:contentLength>508745426</torrent:contentLength>\n        <torrent:infoHash>9E8FB9FFDA987334FCD84A6F60E53E9EAF31E5DC</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:9E8FB9FFDA987334FCD84A6F60E53E9EAF31E5DC&dn=shameless+us+s03e01+hdtv+xvid+afg&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>5</torrent:seeds>\n        <torrent:peers>5</torrent:peers>\n        <torrent:verified>1</torrent:verified>\n        <torrent:fileName>shameless.us.s03e01.hdtv.xvid.afg.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/9E8FB9FFDA987334FCD84A6F60E53E9EAF31E5DC.torrent?title=[kat.cr]shameless.us.s03e01.hdtv.xvid.afg" length="508745426" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>Shameless US S03E01 HDTV Subtitulado Esp SC avi</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/shameless-us-s03e01-hdtv-subtitulado-esp-sc-avi-t7599501.html</link>\n        <guid>http://kat.cr/shameless-us-s03e01-hdtv-subtitulado-esp-sc-avi-t7599501.html</guid>\n        <pubDate>Wed, 10 Jul 2013 15:48:02 +0000</pubDate>\n        <torrent:contentLength>430092438</torrent:contentLength>\n        <torrent:infoHash>5048F1AB0D54FE72651B5FD82CFEC77785528257</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:5048F1AB0D54FE72651B5FD82CFEC77785528257&dn=shameless+us+s03e01+hdtv+subtitulado+esp+sc+avi&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>5</torrent:seeds>\n        <torrent:peers>6</torrent:peers>\n        <torrent:verified>1</torrent:verified>\n        <torrent:fileName>shameless.us.s03e01.hdtv.subtitulado.esp.sc.avi.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/5048F1AB0D54FE72651B5FD82CFEC77785528257.torrent?title=[kat.cr]shameless.us.s03e01.hdtv.subtitulado.esp.sc.avi" length="430092438" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>Shameless US S03E01 720p HDTV x264 EVOLVE</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/shameless-us-s03e01-720p-hdtv-x264-evolve-t6985456.html</link>\n        <guid>http://kat.cr/shameless-us-s03e01-720p-hdtv-x264-evolve-t6985456.html</guid>\n        <pubDate>Mon, 14 Jan 2013 05:39:03 +0000</pubDate>\n        <torrent:contentLength>2131735890</torrent:contentLength>\n        <torrent:infoHash>57CCD5B419F992E730D327FA0D1A68E7B62F68AB</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:57CCD5B419F992E730D327FA0D1A68E7B62F68AB&dn=shameless+us+s03e01+720p+hdtv+x264+evolve&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>2</torrent:seeds>\n        <torrent:peers>2</torrent:peers>\n        <torrent:verified>1</torrent:verified>\n        <torrent:fileName>shameless.us.s03e01.720p.hdtv.x264.evolve.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/57CCD5B419F992E730D327FA0D1A68E7B62F68AB.torrent?title=[kat.cr]shameless.us.s03e01.720p.hdtv.x264.evolve" length="2131735890" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>Shameless US S03E01 HDTV x264-ASAP[ettv]</title>\n\n        <category>TV</category>\n      <author>http://kat.cr/user/ettv/</author>        <link>http://kat.cr/shameless-us-s03e01-hdtv-x264-asap-ettv-t6985470.html</link>\n        <guid>http://kat.cr/shameless-us-s03e01-hdtv-x264-asap-ettv-t6985470.html</guid>\n        <pubDate>Mon, 14 Jan 2013 05:46:01 +0000</pubDate>\n        <torrent:contentLength>631642860</torrent:contentLength>\n        <torrent:infoHash>D722EC398E2705B5EC99B9158891531D2C6C5089</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:D722EC398E2705B5EC99B9158891531D2C6C5089&dn=shameless+us+s03e01+hdtv+x264+asap+ettv&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>2</torrent:seeds>\n        <torrent:peers>2</torrent:peers>\n        <torrent:verified>1</torrent:verified>\n        <torrent:fileName>shameless.us.s03e01.hdtv.x264.asap.ettv.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/D722EC398E2705B5EC99B9158891531D2C6C5089.torrent?title=[kat.cr]shameless.us.s03e01.hdtv.x264.asap.ettv" length="631642860" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>Shameless (US) S03E01 El Gran Ca&ntilde; HDTV XVID-AVIGUY avi</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/shameless-us-s03e01-el-gran-ca-ntilde-hdtv-xvid-aviguy-avi-t6986202.html</link>\n        <guid>http://kat.cr/shameless-us-s03e01-el-gran-ca-ntilde-hdtv-xvid-aviguy-avi-t6986202.html</guid>\n        <pubDate>Mon, 14 Jan 2013 11:21:25 +0000</pubDate>\n        <torrent:contentLength>417585698</torrent:contentLength>\n        <torrent:infoHash>13CB2BE1D09947A634BE8A255AA83CE1068D9044</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:13CB2BE1D09947A634BE8A255AA83CE1068D9044&dn=shameless+us+s03e01+el+gran+ca+ntilde+hdtv+xvid+aviguy+avi&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>2</torrent:seeds>\n        <torrent:peers>2</torrent:peers>\n        <torrent:verified>1</torrent:verified>\n        <torrent:fileName>shameless.us.s03e01.el.gran.ca.ntilde.hdtv.xvid.aviguy.avi.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/13CB2BE1D09947A634BE8A255AA83CE1068D9044.torrent?title=[kat.cr]shameless.us.s03e01.el.gran.ca.ntilde.hdtv.xvid.aviguy.avi" length="417585698" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>Shameless US S03E01-12 720p BluRay x264-DEMAND</title>\n\n        <category>TV</category>\n      <author>http://kat.cr/user/davidwebs1452/</author>        <link>http://kat.cr/shameless-us-s03e01-12-720p-bluray-x264-demand-t8313352.html</link>\n        <guid>http://kat.cr/shameless-us-s03e01-12-720p-bluray-x264-demand-t8313352.html</guid>\n        <pubDate>Fri, 06 Dec 2013 07:34:38 +0000</pubDate>\n        <torrent:contentLength>29179380208</torrent:contentLength>\n        <torrent:infoHash>850E170CD7EF7F9698E4D8A12E7ED82A04A3F1E0</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:850E170CD7EF7F9698E4D8A12E7ED82A04A3F1E0&dn=shameless+us+s03e01+12+720p+bluray+x264+demand&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>2</torrent:seeds>\n        <torrent:peers>2</torrent:peers>\n        <torrent:verified>0</torrent:verified>\n        <torrent:fileName>shameless.us.s03e01.12.720p.bluray.x264.demand.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/850E170CD7EF7F9698E4D8A12E7ED82A04A3F1E0.torrent?title=[kat.cr]shameless.us.s03e01.12.720p.bluray.x264.demand" length="29179380208" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>Shameless US S03E01 480p HDTV x264 mSD</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/shameless-us-s03e01-480p-hdtv-x264-msd-t6985607.html</link>\n        <guid>http://kat.cr/shameless-us-s03e01-480p-hdtv-x264-msd-t6985607.html</guid>\n        <pubDate>Mon, 14 Jan 2013 06:42:02 +0000</pubDate>\n        <torrent:contentLength>390062199</torrent:contentLength>\n        <torrent:infoHash>6E8D8CFBC3B882BE61755A94F221CE7149C36332</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:6E8D8CFBC3B882BE61755A94F221CE7149C36332&dn=shameless+us+s03e01+480p+hdtv+x264+msd&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>1</torrent:seeds>\n        <torrent:peers>2</torrent:peers>\n        <torrent:verified>1</torrent:verified>\n        <torrent:fileName>shameless.us.s03e01.480p.hdtv.x264.msd.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/6E8D8CFBC3B882BE61755A94F221CE7149C36332.torrent?title=[kat.cr]shameless.us.s03e01.480p.hdtv.x264.msd" length="390062199" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>Shameless US S03E01 HDTV XviD AFG</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/shameless-us-s03e01-hdtv-xvid-afg-t6985645.html</link>\n        <guid>http://kat.cr/shameless-us-s03e01-hdtv-xvid-afg-t6985645.html</guid>\n        <pubDate>Mon, 14 Jan 2013 07:06:03 +0000</pubDate>\n        <torrent:contentLength>508746233</torrent:contentLength>\n        <torrent:infoHash>A33850D26F72370164B9C52DC35290E07B386023</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:A33850D26F72370164B9C52DC35290E07B386023&dn=shameless+us+s03e01+hdtv+xvid+afg&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>1</torrent:seeds>\n        <torrent:peers>1</torrent:peers>\n        <torrent:verified>1</torrent:verified>\n        <torrent:fileName>shameless.us.s03e01.hdtv.xvid.afg.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/A33850D26F72370164B9C52DC35290E07B386023.torrent?title=[kat.cr]shameless.us.s03e01.hdtv.xvid.afg" length="508746233" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>Shameless US S03E01 720p HDTV x264-EVOLVE [PublicHD]</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/shameless-us-s03e01-720p-hdtv-x264-evolve-publichd-t6985749.html</link>\n        <guid>http://kat.cr/shameless-us-s03e01-720p-hdtv-x264-evolve-publichd-t6985749.html</guid>\n        <pubDate>Mon, 14 Jan 2013 07:57:02 +0000</pubDate>\n        <torrent:contentLength>2087399621</torrent:contentLength>\n        <torrent:infoHash>B14D938B7A020473249FBF3E2B7F404B8896C29F</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:B14D938B7A020473249FBF3E2B7F404B8896C29F&dn=shameless+us+s03e01+720p+hdtv+x264+evolve+publichd&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>1</torrent:seeds>\n        <torrent:peers>1</torrent:peers>\n        <torrent:verified>1</torrent:verified>\n        <torrent:fileName>shameless.us.s03e01.720p.hdtv.x264.evolve.publichd.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/B14D938B7A020473249FBF3E2B7F404B8896C29F.torrent?title=[kat.cr]shameless.us.s03e01.720p.hdtv.x264.evolve.publichd" length="2087399621" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>Shameless US S03E01 480p WEB DL x264 mSD</title>\n\n        <category>TV</category>\n        <link>http://kat.cr/shameless-us-s03e01-480p-web-dl-x264-msd-t7256266.html</link>\n        <guid>http://kat.cr/shameless-us-s03e01-480p-web-dl-x264-msd-t7256266.html</guid>\n        <pubDate>Fri, 29 Mar 2013 13:12:05 +0000</pubDate>\n        <torrent:contentLength>547263139</torrent:contentLength>\n        <torrent:infoHash>746D34B99315EBD614AC80E4883A9C7AA2F41A32</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:746D34B99315EBD614AC80E4883A9C7AA2F41A32&dn=shameless+us+s03e01+480p+web+dl+x264+msd&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>1</torrent:seeds>\n        <torrent:peers>1</torrent:peers>\n        <torrent:verified>1</torrent:verified>\n        <torrent:fileName>shameless.us.s03e01.480p.web.dl.x264.msd.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/746D34B99315EBD614AC80E4883A9C7AA2F41A32.torrent?title=[kat.cr]shameless.us.s03e01.480p.web.dl.x264.msd" length="547263139" type="application/x-bittorrent" />\n    </item>\n    <item>\n        <title>Shameless US S03E01 HDTV x264 ASAP</title>\n\n        <category>TV</category>\n      <author>http://kat.cr/user/ChrisDen/</author>        <link>http://kat.cr/shameless-us-s03e01-hdtv-x264-asap-t6985493.html</link>\n        <guid>http://kat.cr/shameless-us-s03e01-hdtv-x264-asap-t6985493.html</guid>\n        <pubDate>Mon, 14 Jan 2013 05:54:02 +0000</pubDate>\n        <torrent:contentLength>631648465</torrent:contentLength>\n        <torrent:infoHash>1BB03971A5596DC0866E58297EB8B69C0AFD1120</torrent:infoHash>\n        <torrent:magnetURI><![CDATA[magnet:?xt=urn:btih:1BB03971A5596DC0866E58297EB8B69C0AFD1120&dn=shameless+us+s03e01+hdtv+x264+asap&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337]]></torrent:magnetURI>\n        <torrent:seeds>0</torrent:seeds>\n        <torrent:peers>0</torrent:peers>\n        <torrent:verified>1</torrent:verified>\n        <torrent:fileName>shameless.us.s03e01.hdtv.x264.asap.torrent</torrent:fileName>\n        <enclosure url="https://torcache.net/torrent/1BB03971A5596DC0866E58297EB8B69C0AFD1120.torrent?title=[kat.cr]shameless.us.s03e01.hdtv.x264.asap" length="631648465" type="application/x-bittorrent" />\n    </item>\n    </channel>\n</rss>'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by OmgImAlexis** [comment]
This really needs to be made into some kind of info log instead of being an error that's submittable.

**Comment by miigotu** [comment]
Actually we need this one submitted. We need to know when feed parsing fails (in this case it is `&ntilde;` which there is no DTD to define it.)
