### ISSUE TITLE
Thread-56 :: Unable to connect to theTVDB while creating meta files - skipping - Series result returned zero 

### ISSUE THREAD

**Issue by zflash** [SiCKRAGETV/sickrage-issues#3304]
Happend since the pull from yesterday:

SR Version:	BRANCH: (master) / COMMIT: (0503591bdb856456bdd7709ce45a11fcd6ce1b26) 

Error:

2015-10-15 09:06:18 ERROR    Thread-81 :: Unable to connect to theTVDB while creating meta files - skipping - Series result returned zero
Traceback (most recent call last):
  File "c:\sickrage\sickbeard\metadata\kodi_12plus.py", line 230, in _ep_data
    myShow = t[ep_obj.show.indexerid]
  File "c:\sickrage\lib\tvdb_api\tvdb_api.py", line 953, in __getitem__
    self._getShowData(key, self.config['language'], True)
  File "c:\sickrage\lib\tvdb_api\tvdb_api.py", line 853, in _getShowData
    raise tvdb_error("Series result returned zero")
tvdb_error: Series result returned zero
2015-10-15 09:06:18 DEBUG    Thread-81 :: Checking if G:\5. Series\Arrow\Season 04\Arrow - 4x2 - The Candidate-thumb.jpg exists: False
2015-10-15 09:06:18 DEBUG    Thread-81 :: Parsed G:\5. Series\Arrow\Season 04\Arrow - 4x2 - The Candidate into Arrow - S04E02 [ABD: False] [ANIME: False] [whichReg: ['fov', 'season_only']]
2015-10-15 09:06:18 DEBUG    Thread-81 :: Parsed Arrow.S04E02.720p.HDTV.X264-DIMENSION into Arrow - S04E02 [GROUP: DIMENSION] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-10-15 09:06:18 DEBUG    Thread-81 :: formatting pattern: %SN - %Sx%0E - %EN -> Arrow - 4x02 - The Candidate
2015-10-15 09:06:18 DEBUG    Thread-81 :: Metadata provider KODI 12+ creating episode thumbnail for Arrow - 4x02 - The Candidate
2015-10-15 09:06:18 ERROR    Thread-81 :: Failed doing webui callback: Traceback (most recent call last):
  File "c:\sickrage\sickbeard\webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "c:\sickrage\sickbeard\webserve.py", line 2152, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "c:\sickrage\sickbeard\processTV.py", line 273, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "c:\sickrage\sickbeard\processTV.py", line 555, in process_media
    result.result = processor.process()
  File "c:\sickrage\sickbeard\postProcessor.py", line 1104, in process
    ep_obj.createMetaFiles()
  File "c:\sickrage\sickbeard\tv.py", line 1866, in createMetaFiles
    self.createThumbnail()
  File "c:\sickrage\sickbeard\tv.py", line 1885, in createThumbnail
    result = cur_provider.create_episode_thumb(self) or result
  File "c:\sickrage\sickbeard\metadata\generic.py", line 334, in create_episode_thumb
    return self.save_thumbnail(ep_obj)
  File "c:\sickrage\sickbeard\metadata\generic.py", line 501, in save_thumbnail
    thumb_url = self._get_episode_thumb_url(ep_obj)
  File "c:\sickrage\sickbeard\metadata\generic.py", line 388, in _get_episode_thumb_url
    myEp = helpers.validateShow(cur_ep.show, cur_ep.season, cur_ep.episode)
  File "c:\sickrage\sickbeard\helpers.py", line 1295, in validateShow
    return t[show.indexerid][season][episode]
  File "c:\sickrage\lib\tvdb_api\tvdb_api.py", line 953, in __getitem__
    self._getShowData(key, self.config['language'], True)
  File "c:\sickrage\lib\tvdb_api\tvdb_api.py", line 853, in _getShowData
    raise tvdb_error("Series result returned zero")
tvdb_error: Series result returned zero
Traceback (most recent call last):
  File "c:\sickrage\sickbeard\webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "c:\sickrage\sickbeard\webserve.py", line 2152, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "c:\sickrage\sickbeard\processTV.py", line 273, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "c:\sickrage\sickbeard\processTV.py", line 555, in process_media
    result.result = processor.process()
  File "c:\sickrage\sickbeard\postProcessor.py", line 1104, in process
    ep_obj.createMetaFiles()
  File "c:\sickrage\sickbeard\tv.py", line 1866, in createMetaFiles
    self.createThumbnail()
  File "c:\sickrage\sickbeard\tv.py", line 1885, in createThumbnail
    result = cur_provider.create_episode_thumb(self) or result
  File "c:\sickrage\sickbeard\metadata\generic.py", line 334, in create_episode_thumb
    return self.save_thumbnail(ep_obj)
  File "c:\sickrage\sickbeard\metadata\generic.py", line 501, in save_thumbnail
    thumb_url = self._get_episode_thumb_url(ep_obj)
  File "c:\sickrage\sickbeard\metadata\generic.py", line 388, in _get_episode_thumb_url
    myEp = helpers.validateShow(cur_ep.show, cur_ep.season, cur_ep.episode)
  File "c:\sickrage\sickbeard\helpers.py", line 1295, in validateShow
    return t[show.indexerid][season][episode]
  File "c:\sickrage\lib\tvdb_api\tvdb_api.py", line 953, in __getitem__
    self._getShowData(key, self.config['language'], True)
  File "c:\sickrage\lib\tvdb_api\tvdb_api.py", line 853, in _getShowData
    raise tvdb_error("Series result returned zero")
tvdb_error: Series result returned zero
2015-10-15 09:06:18 DEBUG    TORNADO :: Failed doing webui request "processEpisode": Traceback (most recent call last):
  File "c:\sickrage\sickbeard\webserve.py", line 235, in get
    results = yield self.async_call(method)
  File "c:\sickrage\tornado\gen.py", line 807, in run
    value = future.result()
  File "c:\sickrage\lib\concurrent\futures\_base.py", line 400, in result
    return self.__get_result()
  File "c:\sickrage\lib\concurrent\futures\_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "c:\sickrage\lib\concurrent\futures\_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "c:\sickrage\lib\concurrent\futures\thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\sickrage\sickbeard\webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "c:\sickrage\sickbeard\webserve.py", line 2152, in processEpisode
    is_priority=is_priority, delete_on=delete_on, failed=failed, type=type)
  File "c:\sickrage\sickbeard\processTV.py", line 273, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "c:\sickrage\sickbeard\processTV.py", line 555, in process_media
    result.result = processor.process()
  File "c:\sickrage\sickbeard\postProcessor.py", line 1104, in process
    ep_obj.createMetaFiles()
  File "c:\sickrage\sickbeard\tv.py", line 1866, in createMetaFiles
    self.createThumbnail()
  File "c:\sickrage\sickbeard\tv.py", line 1885, in createThumbnail
    result = cur_provider.create_episode_thumb(self) or result
  File "c:\sickrage\sickbeard\metadata\generic.py", line 334, in create_episode_thumb
    return self.save_thumbnail(ep_obj)
  File "c:\sickrage\sickbeard\metadata\generic.py", line 501, in save_thumbnail
    thumb_url = self._get_episode_thumb_url(ep_obj)
  File "c:\sickrage\sickbeard\metadata\generic.py", line 388, in _get_episode_thumb_url
    myEp = helpers.validateShow(cur_ep.show, cur_ep.season, cur_ep.episode)
  File "c:\sickrage\sickbeard\helpers.py", line 1295, in validateShow
    return t[show.indexerid][season][episode]
  File "c:\sickrage\lib\tvdb_api\tvdb_api.py", line 953, in __getitem__
    self._getShowData(key, self.config['language'], True)
  File "c:\sickrage\lib\tvdb_api\tvdb_api.py", line 853, in _getShowData
    raise tvdb_error("Series result returned zero")
tvdb_error: Series result returned zero

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by zflash** [comment]
Pulling the new update did the trick.
