### ISSUE TITLE
Kickass Error and Error when submitting errors

### ISSUE THREAD

**Issue by MrsAngelD** [SiCKRAGETV/sickrage-issues#3317]
SR Version: 	BRANCH: (master) / COMMIT: (a3a3b92f0fb813beffa5473576396b0e49aa04ba)
SR Locale:	(None, None)
SR Config:	/home/angel/.sickbeard/config.ini
SR Database:	/home/angel/.sickbeard/sickbeard.db
SR Cache Dir:	/home/angel/.sickbeard/cache
SR Log Dir:	/home/angel/.sickbeard/Logs
SR Arguments:	['-q', '--daemon', '--nolaunch', '--pidfile=/var/run/sickbeard/sickbeard.pid', '--datadir=/home/angel/.sickbeard/']
Python Version:	2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
```
2015-10-15 14:51:02 Thread-29 :: Traceback (most recent call last):
  File "/home/angel/.sickbeard/sickbeard/logger.py", line 242, in submit_errors
    gist = gh.get_user().create_gist(True, {"sickrage.log": InputFileContent(paste_data)})
  File "/home/angel/.sickbeard/lib/github/AuthenticatedUser.py", line 473, in create_gist
    input=post_parameters
  File "/home/angel/.sickbeard/lib/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/home/angel/.sickbeard/lib/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
TwoFactorException: 401 {u'documentation_url': u'https://developer.github.com/v3/auth#working-with-two-factor-authentication', u'message': u'Must specify two-factor authentication OTP code.'}

2015-10-15 14:46:37 SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/angel/.sickbeard/sickbeard/providers/kat.py", line 100, in _doSearch\n    data = xmltodict.parse(HTMLParser.HTMLParser().unescape(data))\n  File "/home/angel/.sickbeard/lib/xmltodict.py", line 248, in parse\n    parser.Parse(xml_input, True)\nExpatError: not well-formed (invalid token): line 344, column 22\n'
'\n\n\n    \n    http://kat.cr/\n    tv torrents RSS feed\n    \n        \n\n        TV\n      http://kat.cr/user/z0n321/        http://kat.cr/wabbit-s01e14-hdtv-x264-w4f-rartv-t11417777.html\n        http://kat.cr/wabbit-s01e14-hdtv-x264-w4f-rartv-t11417777.html\n        Thu, 15 Oct 2015 18:25:25 +0000\n        65927619\n        B3ED465DD4D88D0345E6FD788EF3977AEA3DCC11\n        \n        0\n        0\n        1\n        wabbit.s01e14.hdtv.x264.w4f.rartv.torrent\n        \n    \n    \n        \n\n        TV\n      http://kat.cr/user/lucifer22/        http://kat.cr/arrow-s04e02-s02e02-hdtv-720p-hevc-lucifer22-t11417775.html\n        http://kat.cr/arrow-s04e02-s02e02-hdtv-720p-hevc-lucifer22-t11417775.html\n        Thu, 15 Oct 2015 18:24:09 +0000\n        148951930\n        190EA29A65B812FE8F4424517A1C8B8AE6233576\n        \n        0\n        0\n        0\n        arrow.s04e02.s02e02.hdtv.720p.hevc.lucifer22.torrent\n        \n    \n    \n        \n\n        TV\n      http://kat.cr/user/rosa1917/        http://kat.cr/limitless-tv-serie-2015-s01e04-vostfr-hdtv-x264-brn-seedbox-mp4-t11417754.html\n        http://kat.cr/limitless-tv-serie-2015-s01e04-vostfr-hdtv-x264-brn-seedbox-mp4-t11417754.html\n        Thu, 15 Oct 2015 18:13:34 +0000\n        276771488\n        62A7695FFCE8A84F09FAA2B723BF989F30AF6824\n        \n        0\n        0\n        1\n        limitless.tv.serie.2015.s01e04.vostfr.hdtv.x264.brn.seedbox.mp4.torrent\n        \n    \n    \n        \n\n        TV\n      http://kat.cr/user/makpufterpup/        http://kat.cr/face-of-britain-by-simon-schama-s01e03-en-sub-x265-webrip-mpup-the-face-of-fame-t11417737.html\n        http://kat.cr/face-of-britain-by-simon-schama-s01e03-en-sub-x265-webrip-mpup-the-face-of-fame-t11417737.html\n        Thu, 15 Oct 2015 18:07:30 +0000\n        182679853\n        97950C222356A2B9087C41CD77393A9D51932F51\n        \n        0\n        0\n        1\n        face.of.britain.by.simon.schama.s01e03.en.sub.x265.webrip.mpup.the.face.of.fame.torrent\n        \n    \n    \n        \n\n        TV\n      http://kat.cr/user/z0n321/        http://kat.cr/drunk-history-s03e07-oklahoma-1080p-web-dl-aac2-0-h-264-btn-rartv-t11417715.html\n        http://kat.cr/drunk-history-s03e07-oklahoma-1080p-web-dl-aac2-0-h-264-btn-rartv-t11417715.html\n        Thu, 15 Oct 2015 18:02:09 +0000\n        818966948\n        E2E62729D8F17F703123EE58626047AABDF2F524\n        \n        0\n        0\n        1\n        drunk.history.s03e07.oklahoma.1080p.web.dl.aac2.0.h.264.btn.rartv.torrent\n        \n    \n    \n        \n\n        TV\n      http://kat.cr/user/z0n321/        http://kat.cr/drunk-history-s03e07-oklahoma-720p-web-dl-aac2-0-h-264-btn-rartv-t11417697.html\n        http://kat.cr/drunk-history-s03e07-oklahoma-720p-web-dl-aac2-0-h-264-btn-rartv-t11417697.html\n        Thu, 15 Oct 2015 17:58:42 +0000\n        674195204\n        489CB886F2291780F03F67760CC9553802806F9C\n        \n        0\n        0\n        1\n        drunk.history.s03e07.oklahoma.720p.web.dl.aac2.0.h.264.btn.rartv.torrent\n        \n    \n    \n        \n\n        TV\n      http://kat.cr/user/dinuka00/        http://kat.cr/empire-2015-s02e04-poor-yorick-720p-web-dl-2ch-x265-hevc-psa-t11417683.html\n        http://kat.cr/empire-2015-s02e04-poor-yorick-720p-web-dl-2ch-x265-hevc-psa-t11417683.html\n        Thu, 15 Oct 2015 17:55:48 +0000\n        217492018\n        307A00A0ED08C0A20C190E5E94F2C0FF7476A21E\n        \n        0\n        0\n        0\n        empire.2015.s02e04.poor.yorick.720p.web.dl.2ch.x265.hevc.psa.torrent\n        \n    \n    \n        \n\n        TV\n      http://kat.cr/user/AL459/        http://kat.cr/the-walking-dead-1-5-complete-t11417663.html\n        http://kat.cr/the-walking-dead-1-5-complete-t11417663.html\n        Thu, 15 Oct 2015 17:52:00 +0000\n        35626260778\n        6E730C0847093861DECCA25B1E733A947A36039E\n        \n        0\n        0\n        0\n        the.walking.dead.1.5.complete.torrent\n        \n    \n    \n        \n\n        TV\n      http://kat.cr/user/Lewiswill/        http://kat.cr/gotham-s02e04-1080p-webdl-10bit-5-1-x265-hevc-lewiswill-utr-mkv-t11417652.html\n        http://kat.cr/gotham-s02e04-1080p-webdl-10bit-5-1-x265-hevc-lewiswill-utr-mkv-t11417652.html\n        Thu, 15 Oct 2015 17:49:51 +0000\n        358688754\n        C2D29A940A7123E2BD663FC7A2C10E89BDDB0293\n        \n        0\n        0\n        1\n        gotham.s02e04.1080p.webdl.10bit.5.1.x265.hevc.lewiswill.utr.mkv.torrent\n        \n    \n    \n        \n\n        TV\n      http://kat.cr/user/dinuka00/        http://kat.cr/from-dusk-till-dawn-s02e08-the-last-temptation-of-richard-gecko-720p-web-dl-2ch-x265-hevc-psa-t11417640.html\n        http://kat.cr/from-dusk-till-dawn-s02e08-the-last-temptation-of-richard-gecko-720p-web-dl-2ch-x265-hevc-psa-t11417640.html\n        Thu, 15 Oct 2015 17:46:13 +0000\n        158115418\n        2C61C30538D412E49EB31B11F0FEED034426E7D5\n        \n        0\n        0\n        0\n        from.dusk.till.dawn.s02e08.the.last.temptation.of.richard.gecko.720p.web.dl.2ch.x265.hevc.psa.torrent\n        \n    \n    \n        \n\n        TV\n      http://kat.cr/user/ColdAssHonkey/        http://kat.cr/deadly-women-s02e03-twisted-minds-g-unit-t11417635.html\n        http://kat.cr/deadly-women-s02e03-twisted-minds-g-unit-t11417635.html\n        Thu, 15 Oct 2015 17:45:12 +0000\n        119459370\n        BCCCEFC78A8A71DF25EFB84B675EC5988C8F6452\n        \n        0\n        0\n        1\n        deadly.women.s02e03.twisted.minds.g.unit.torrent\n        \n    \n    \n        \n\n        TV\n      http://kat.cr/user/ColdAssHonkey/        http://kat.cr/deadly-women-s02e02-fatal-attractions-g-unit-t11417630.html\n        http://kat.cr/deadly-women-s02e02-fatal-attractions-g-unit-t11417630.html\n        Thu, 15 Oct 2015 17:44:37 +0000\n        852184328\n        F0B52A10568C65805E66F7951F56C7B12AEC0984\n        \n        0\n        0\n        1\n        deadly.women.s02e02.fatal.attractions.g.unit.torrent\n        \n    \n    \n        \n\n        TV\n      http://kat.cr/user/ColdAssHonkey/        http://kat.cr/deadly-women-s02e01-thrill-killers-g-unit-t11417627.html\n        http://kat.cr/deadly-women-s02e01-thrill-killers-g-unit-t11417627.html\n        Thu, 15 Oct 2015 17:43:45 +0000\n        177570695\n        33DE3EC07A1A5C88EA3577DAC056AF68516B59C6\n        \n        0\n        0\n        1\n        deadly.women.s02e01.thrill.killers.g.unit.torrent\n        \n    \n    \n        \n\n        TV\n      http://kat.cr/user/SRIGGA/        http://kat.cr/dallas-car-sharks-s03e06-get-your-motor-running-ws-dsr-x264-ny2-mp4-t11417608.html\n        http://kat.cr/dallas-car-sharks-s03e06-get-your-motor-running-ws-dsr-x264-ny2-mp4-t11417608.html\n        Thu, 15 Oct 2015 17:41:07 +0000\n        192798942\n        F54967A23CC4482F8EBCA5A9EBAB637932354D2C\n        \n        0\n        0\n        1\n        dallas.car.sharks.s03e06.get.your.motor.running.ws.dsr.x264.ny2.mp4.torrent\n        \n    \n    \n        \n\n        TV\n      http://kat.cr/user/z0n321/        http://kat.cr/scream-queens-2015-s01e05-pumpkin-patch-1080p-web-dl-dd5-1-h-264-ntb-rartv-t11417595.html\n        http://kat.cr/scream-queens-2015-s01e05-pumpkin-patch-1080p-web-dl-dd5-1-h-264-ntb-rartv-t11417595.html\n        Thu, 15 Oct 2015 17:38:42 +0000\n        1714688598\n        FABA761A92DF275D27849749F76FF0EAA0C74BB5\n        \n        0\n        0\n        1\n        scream.queens.2015.s01e05.pumpkin.patch.1080p.web.dl.dd5.1.h.264.ntb.rartv.torrent\n        \n    \n    \n        \n\n        TV\n      http://kat.cr/user/cognito/        http://kat.cr/danger-mouse-2015-s01e14-1280x720-t11417576.html\n        http://kat.cr/danger-mouse-2015-s01e14-1280x720-t11417576.html\n        Thu, 15 Oct 2015 17:35:40 +0000\n        263263603\n        20CB51D4B0E98182158AE7EEE09B2DCDC932FE71\n        \n        0\n        0\n        0\n        danger.mouse.2015.s01e14.1280x720.torrent\n        \n    \n    \n        \n\n        TV\n      http://kat.cr/user/SRIGGA/        http://kat.cr/strictly-come-dancing-s13e06-720p-webrip-h264-spamtv-mkv-t11417574.html\n        http://kat.cr/strictly-come-dancing-s13e06-720p-webrip-h264-spamtv-mkv-t11417574.html\n        Thu, 15 Oct 2015 17:35:24 +0000\n        448188010\n        96E47876CBED13083F348C57499C2D557D2B63DB\n        \n        0\n        0\n        1\n        strictly.come.dancing.s13e06.720p.webrip.h264.spamtv.mkv.torrent\n        \n    \n    \n        \n\n        TV\n      http://kat.cr/user/z0n321/        http://kat.cr/scream-queens-2015-s01e05-pumpkin-patch-720p-web-dl-dd5-1-h-264-ntb-rartv-t11417569.html\n        http://kat.cr/scream-queens-2015-s01e05-pumpkin-patch-720p-web-dl-dd5-1-h-264-ntb-rartv-t11417569.html\n        Thu, 15 Oct 2015 17:34:11 +0000\n        1385209941\n        B7B9B179B2F7870ADAF681337A0D72CF30B0767A\n        \n        0\n        0\n        1\n        scream.queens.2015.s01e05.pumpkin.patch.720p.web.dl.dd5.1.h.264.ntb.rartv.torrent\n        \n    \n    \n        \n\n        TV\n      http://kat.cr/user/SRIGGA/        http://kat.cr/little-women-la-s03e12-hawaiian-couples-retreat-ws-dsr-x264-ny2-mp4-t11417555.html\n        http://kat.cr/little-women-la-s03e12-hawaiian-couples-retreat-ws-dsr-x264-ny2-mp4-t11417555.html\n        Thu, 15 Oct 2015 17:32:07 +0000\n        427831664\n        B57E3DF77A55A1A008DBB0466E1480B6E483CAA5\n        \n        0\n        0\n        1\n        little.women.la.s03e12.hawaiian.couples.retreat.ws.dsr.x264.ny2.mp4.torrent\n        \n    \n    \n        \n\n        TV\n      http://kat.cr/user/psmv/        http://kat.cr/star-wars-rebels-s02e02-hdtv-subtitulado-esp-sc-avi-t11417514.html\n        http://kat.cr/star-wars-rebels-s02e02-hdtv-subtitulado-esp-sc-avi-t11417514.html\n        Thu, 15 Oct 2015 17:24:25 +0000\n        149180846\n        DF3132F288429BE668F0347B5F7B978D412349D8\n        \n        0\n        0\n        0\n        star.wars.rebels.s02e02.hdtv.subtitulado.esp.sc.avi.torrent\n        \n    \n    \n        \n\n        TV\n      http://kat.cr/user/clayb04/        http://kat.cr/the-romeo-section-s01e01-hdtv-x264-hack1-t11417513.html\n        http://kat.cr/the-romeo-section-s01e01-hdtv-x264-hack1-t11417513.html\n        Thu, 15 Oct 2015 17:24:18 +0000\n        190009849\n        6BFE2F57DE270F1D818547CEA91298E931190BC1\n        \n        0\n        0\n        0\n        the.romeo.section.s01e01.hdtv.x264.hack1.torrent\n        \n    \n    \n        \n\n        TV\n      http://kat.cr/user/RuneMagle/        http://kat.cr/young-hungry-s02e20-young-younger-brother-part-2-itunes-1080p-dcmagic-t11417512.html\n        http://kat.cr/young-hungry-s02e20-young-younger-brother-part-2-itunes-1080p-dcmagic-t11417512.html\n        Thu, 15 Oct 2015 17:24:12 +0000\n        894105595\n        26F1C34387E0A2760BA639AA16A559E50C809C2B\n        \n        0\n        0\n        1\n        young.hungry.s02e20.young.younger.brother.part.2.itunes.1080p.dcmagic.torrent\n        \n    \n    \n        \n\n        TV\n      http://kat.cr/user/SRIGGA/        http://kat.cr/big-freedia-queen-of-bounce-s04e03-she-wanna-have-a-good-time-ws-dsr-x264-ny2-mp4-t11417509.html\n        http://kat.cr/big-freedia-queen-of-bounce-s04e03-she-wanna-have-a-good-time-ws-dsr-x264-ny2-mp4-t11417509.html\n        Thu, 15 Oct 2015 17:23:02 +0000\n        237134642\n        CF6F16599442D82964CF074C34A79FEB054320A6\n        \n        0\n        0\n        1\n        big.freedia.queen.of.bounce.s04e03.she.wanna.have.a.good.time.ws.dsr.x264.ny2.mp4.torrent\n        \n    \n    \n        \n\n        TV\n      http://kat.cr/user/mothergoose58/        http://kat.cr/2015-10-14-legion-of-skanks-episode-40-anthony-cumia-mike-finoia-nick-mullen-mp4-mp3-t11417499.html\n        http://kat.cr/2015-10-14-legion-of-skanks-episode-40-anthony-cumia-mike-finoia-nick-mullen-mp4-mp3-t11417499.html\n        Thu, 15 Oct 2015 17:21:04 +0000\n        179549437\n        206C6C827EB4535E17E92056161AEE3B598561C7\n        \n        0\n        0\n        0\n        2015.10.14.legion.of.skanks.episode.40.anthony.cumia.mike.finoia.nick.mullen.mp4.mp3.torrent\n        \n    \n    \n        \n\n        TV\n      http://kat.cr/user/z0n321/        http://kat.cr/scream-queens-2015-s01e04-pumpkin-patch-1080p-web-dl-dd5-1-h-264-ntb-rartv-t11417490.html\n        http://kat.cr/scream-queens-2015-s01e04-pumpkin-patch-1080p-web-dl-dd5-1-h-264-ntb-rartv-t11417490.html\n        Thu, 15 Oct 2015 17:18:06 +0000\n        1714688598\n        C5894DC33C79B2699F43F75926F089A0A637FD24\n        \n        0\n        0\n        1\n        scream.queens.2015.s01e04.pumpkin.patch.1080p.web.dl.dd5.1.h.264.ntb.rartv.torrent\n        \n    \n    \n'
```

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
Not SR issue

TwoFactorException: 401 {u'documentation_url': u'https://developer.github.com/v3/auth#working-with-two-factor-authentication', u'message': u'Must specify two-factor authentication OTP code.'}

**Comment by fernandog** [comment]
Other is duplicate
