### ISSUE TITLE
ValueError: set_wakeup_fd only works in main thread

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#3331]
@SiCKRAGETV/moderators any of you have this?
This only happens when failed login and using self signed certificate. I didn't get this wihtout cert

Are we using the latest tornado? should we update it (security issues) ?

```
2015-10-16 10:16:10 INFO     TORNADO :: User logged into the SickRage web interface
AAValueError: set_wakeup_fd only works in main thread
AA    old_wakeup_fd = signal.set_wakeup_fd(self._waker.write_fileno())
AA  File "/home/osmc/SickRage/tornado/ioloop.py", line 738, in start
AATraceback (most recent call last):
2015-10-16 10:15:57 ERROR    TORNADO :: User attempted a failed login to the SickRage web interface from IP: *.*.*.*
```

```
SR Version:	BRANCH: (develop) / COMMIT: (73b3811f5cf2131cb6ccfeac0c1f3e38b47483d7) 
Python Version:	2.7.9 (default, Mar 1 2015, 13:48:22) [GCC 4.9.2]
```

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by neoatomic** [comment]
Haven't seen this error before. 
Try'd to remove the account details from the config.ini and removing the cache folder.?

Think we use version 4.10 of Tornado, the latest stable is 4.2.1
https://github.com/tornadoweb/tornado/releases

**Comment by fernandog** [comment]
Do you have self-certificate?

**Comment by neoatomic** [comment]
Yes, my Syno uses a self-singed cert.

**Comment by fernandog** [comment]
but If I remove account details, SR will be open.
Do you have user/pass set? If not, try set any and login with wrong cred.

**Comment by neoatomic** [comment]
I mean remove them for config.ini and than re-add them in the SR webui.
Recalling a problem where encrypted passwords where coursing login probs, and after removing/reading it was fine.

**Comment by fernandog** [comment]
will try

**Comment by fernandog** [comment]
nope. same error. 
@miigotu any clue?

```
2015-10-17 10:23:38 INFO     TORNADO :: User logged into the SickRage web interface
AAValueError: set_wakeup_fd only works in main thread
AA    old_wakeup_fd = signal.set_wakeup_fd(self._waker.write_fileno())
AA  File "/home/osmc/SickRage/tornado/ioloop.py", line 738, in start
AATraceback (most recent call last):
```

**Comment by fernandog** [comment]
found this but don't know what if means:

```
        # In python's signal handling semantics, this only matters on the
        # main thread (fortunately, set_wakeup_fd only works on the main
        # thread and will raise a ValueError otherwise).
        #
        # If someone has already set a wakeup fd, we don't want to
        # disturb it.  This is an issue for twisted, which does its
        # SIGCHLD processing in response to its own wakeup fd being
        # written to.  As long as the wakeup fd is registered on the IOLoop,
        # the loop will still wake up and everything should work.
```

http://www.tornadoweb.org/en/stable/_modules/tornado/ioloop.html

**Comment by fernandog** [comment]
maybe we need to set `old_wakeup_fd` in the login page?
