### ISSUE TITLE
404 on scene exception abort episodes search

### ISSUE THREAD

**Issue by Amnacog** [SiCKRAGETV/sickrage-issues#3391]
* Branch: `master`
* Commit hash: `fa18bcded76de211f272a26095e0a4172707e8fb`
* OS: `linux (deb 8.1)`
* What you did: `Performing simple episode search`
* What happened: `Did not worked`
* What you expected: `Get the damn episode`
* How can we reproduce your issue: `Perform a simple search`

Aditional infos: 

```
- dereferer activated (disabling it did not help)
- curl the uri returned a 200 outside of sickrage
- all providers are affected
```

Log:

```
2015-10-19 17:33:26 INFO     SEARCHQUEUE-MANUAL-279121 :: Checking for scene exception updates for theTVDB
2015-10-19 17:33:26 DEBUG    SEARCHQUEUE-MANUAL-279121 :: Requested getURL http://sickragetv.github.io/sb_tvdb_scene_exceptions/exceptions.txt returned status code is 404: Not Found
2015-10-19 17:33:26 DEBUG    SEARCHQUEUE-MANUAL-279121 :: Check scene exceptions update failed. Unable to update from: http://sickragetv.github.io/sb_tvdb_scene_exceptions/exceptions.txt
2015-10-19 17:33:26 INFO     SEARCHQUEUE-MANUAL-279121 :: Checking for XEM scene exception updates for theTVDB
2015-10-19 17:33:26 DEBUG    SEARCHQUEUE-MANUAL-279121 :: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/search_queue.py", line 178, in run
    searchResult = search.searchProviders(self.show, [self.segment], True, self.downCurQuality)
  File "/opt/sickbeard/sickbeard/search.py", line 449, in searchProviders
    sickbeard.name_cache.buildNameCache(show)
  File "/opt/sickbeard/sickbeard/name_cache.py", line 92, in buildNameCache
    sickbeard.scene_exceptions.retrieve_exceptions()
  File "/opt/sickbeard/sickbeard/scene_exceptions.py", line 224, in retrieve_exceptions
    _xem_exceptions_fetcher()
  File "/opt/sickbeard/sickbeard/scene_exceptions.py", line 315, in _xem_exceptions_fetcher
    parsedJSON = helpers.getURL(url, session=xem_session, timeout = 90, json=True)
  File "/opt/sickbeard/sickbeard/helpers.py", line 1653, in getURL
    return resp.content if not json else resp.json()
  File "/opt/sickbeard/lib/requests/models.py", line 802, in json
    return json.loads(self.text, **kwargs)
  File "/opt/sickbeard/lib/simplejson/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/opt/sickbeard/lib/simplejson/decoder.py", line 335, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/sickbeard/lib/simplejson/decoder.py", line 353, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by neoatomic** [comment]
@Amnacog can you open the url in your browser.? 
http://sickragetv.github.io/sb_tvdb_scene_exceptions/exceptions.txt

And try to shutdown SR and remove/rename the cache.db & cache folder.

**Comment by Amnacog** [comment]
after removing the cache.db Im stuck in infinite loop with: 

```
2015-10-19 17:55:25 DEBUG    Thread-13 :: Requested getURL http://sickragetv.github.io/sb_network_timezones/zoneinfo.txt returned status code is 404: Not Found
2015-10-19 17:55:25 ERROR    Thread-13 :: Loading zoneinfo.txt failed, this can happen from time to time. Unable to get URL: http://sickragetv.github.io/sb_network_timezones/zoneinfo.txt
Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/network_timezones.py", line 85, in _update_zoneinfo
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
```

and the curl : 

```
curl -v http://sickragetv.github.io/sb_network_timezones/network_timezones.txt                                                                                                                                                                    sickbeard/git/master
*   Trying 185.31.17.133...
* Connected to sickragetv.github.io (185.31.17.133) port 80 (#0)
> GET /sb_network_timezones/network_timezones.txt HTTP/1.1
> Host: sickragetv.github.io
> User-Agent: curl/7.42.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: GitHub.com
< Content-Type: text/plain; charset=utf-8
...
< Vary: Accept-Encoding
...
[v] (AU):Australia/Sydney
...
```
