### ISSUE TITLE
ERROR    "Thread-46 :: Problem(s) during processing, failed the following files/folders:"

### ISSUE THREAD

**Issue by amzeus** [SiCKRAGETV/sickrage-issues#3393]
Since updating I can no longer PP, also cant update metadata (as if the drive is is un-write able i can cp the file manually 

the source and destination are SMB shares on a readynas 304, have set it to everyone full acess for testing but same result

 
Python Version:	2.7.9
Operating System: Windows-10
Branch: master
COMMIT: (7045417b59bb23cbc2426e2e1f7b0e59f21a87fb) 

**Error**
2015-10-19 18:00:20 INFO     DAILYSEARCHER :: No new released episodes found ...
2015-10-19 18:00:18 INFO     DAILYSEARCHER :: Searching for new released episodes ...
AANone
2015-10-19 17:57:46 ERROR    Thread-46 :: [X:\TV\The.Walking.Dead.S06E02.HDTV.x264-FLEET\The.Walking.Dead.S06E02.HDTV.x264-FLEET.mp4 : Processing failed: Unable to move the files to their new home]
AANone
2015-10-19 17:57:42 ERROR    Thread-46 :: Problem(s) during processing, failed the following files/folders:  
AAEpisodePostProcessingFailedException: Unable to move the files to their new home
AA    raise EpisodePostProcessingFailedException("Unable to move the files to their new home")
AA  File "C:\SickRage\sickbeard\postProcessor.py", line 1071, in process
AA    result.result = processor.process()
AA  File "C:\SickRage\sickbeard\processTV.py", line 555, in process_media
AATraceback (most recent call last):
2015-10-19 17:57:32 ERROR    Thread-46 :: Processing failed for X:\TV\The.Walking.Dead.S06E02.HDTV.x264-FLEET\The.Walking.Dead.S06E02.HDTV.x264-FLEET.mp4: Unable to move the files to their new home
AAOSError: [Errno 13] Permission denied
AA    fout = os.open(dst, WRITE_FLAGS)
AA  File "C:\SickRage\lib\shutil_custom\__init__.py", line 42, in copyfile_custom
AA    result = function(*args, **kwargs)
AA  File "C:\SickRage\sickrage\helper\encoding.py", line 37, in ek
AA    ek(shutil.copyfile, srcFile, destFile)
AA  File "C:\SickRage\sickbeard\helpers.py", line 513, in copyFile
AA    helpers.copyFile(cur_file_path, new_file_path)
AA  File "C:\SickRage\sickbeard\postProcessor.py", line 365, in _int_copy
AATraceback (most recent call last):
2015-10-19 17:57:12 ERROR    Thread-46 :: Unable to copy file X:\TV\The.Walking.Dead.S06E02.HDTV.x264-FLEET\The.Walking.Dead.S06E02.HDTV.x264-FLEET.mp4 to Y:\The Walking Dead\Season 06\The Walking Dead - S06E02 - JSS.mp4: error 13 : Permission denied
2015-10-19 17:57:07 INFO     Thread-46 :: Release name (the.walking.dead.s06e02.hdtv.x264-fleet) found from file (the.walking.dead.s06e02.hdtv.x264-fleet.nfo)
2015-10-19 17:57:03 INFO     Thread-46 :: This download is marked a priority download so I'm going to replace an existing file if I find one
2015-10-19 17:57:01 INFO     Thread-46 :: Processing X:\TV\The.Walking.Dead.S06E02.HDTV.x264-FLEET\The.Walking.Dead.S06E02.HDTV.x264-FLEET.mp4 (None)
2015-10-19 17:57:00 INFO     Thread-46 :: PostProcessing Path: X:\TV\The.Walking.Dead.S06E02.HDTV.x264-FLEET
2015-10-19 17:21:25 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2015-10-19 17:20:23 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2015-10-19 17:20:20 INFO     DAILYSEARCHER :: No new released episodes found ...

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by amzeus** [comment]
**Debug report**
2015-10-19 18:36:16 ERROR    Thread-54 :: Problem(s) during processing, failed the following files/folders:  
AAEpisodePostProcessingFailedException: Unable to move the files to their new home
AA    raise EpisodePostProcessingFailedException("Unable to move the files to their new home")
AA  File "C:\SickRage\sickbeard\postProcessor.py", line 1071, in process
AA    result.result = processor.process()
AA  File "C:\SickRage\sickbeard\processTV.py", line 555, in process_media
AATraceback (most recent call last):
2015-10-19 18:36:02 ERROR    Thread-54 :: Processing failed for X:\TV\The.Walking.Dead.S06E02.HDTV.x264-FLEET\The.Walking.Dead.S06E02.HDTV.x264-FLEET.mp4: Unable to move the files to their new home
AAOSError: [Errno 13] Permission denied
AA    fout = os.open(dst, WRITE_FLAGS)
AA  File "C:\SickRage\lib\shutil_custom\__init__.py", line 42, in copyfile_custom
AA    result = function(*args, **kwargs)
AA  File "C:\SickRage\sickrage\helper\encoding.py", line 37, in ek
AA    ek(shutil.copyfile, srcFile, destFile)
AA  File "C:\SickRage\sickbeard\helpers.py", line 513, in copyFile
AA    helpers.copyFile(cur_file_path, new_file_path)
AA  File "C:\SickRage\sickbeard\postProcessor.py", line 365, in _int_copy
AATraceback (most recent call last):
2015-10-19 18:35:46 ERROR    Thread-54 :: Unable to copy file X:\TV\The.Walking.Dead.S06E02.HDTV.x264-FLEET\The.Walking.Dead.S06E02.HDTV.x264-FLEET.mp4 to Y:\The Walking Dead\Season 06\The Walking Dead - S06E02 - JSS.mp4: error 13 : Permission denied
2015-10-19 18:35:46 DEBUG    Thread-54 :: Copying file from X:\TV\The.Walking.Dead.S06E02.HDTV.x264-FLEET\The.Walking.Dead.S06E02.HDTV.x264-FLEET.mp4 to Y:\The Walking Dead\Season 06\The Walking Dead - S06E02 - JSS.mp4
2015-10-19 18:35:46 DEBUG    Thread-54 :: Checking if the path Y:\The Walking Dead\Season 06 already exists
2015-10-19 18:35:46 DEBUG    Thread-54 :: Destination folder for this episode: Y:\The Walking Dead\Season 06
2015-10-19 18:35:46 DEBUG    Thread-54 :: formatting pattern: Season %0S -> Season 06
2015-10-19 18:35:46 DEBUG    Thread-54 :: Using cached parse result for: The.Walking.Dead.S06E02.HDTV.x264-FLEET
2015-10-19 18:35:46 DEBUG    Thread-54 :: formatting pattern: %SN - S%0SE%0E - %EN -> The Walking Dead - S06E02 - JSS
2015-10-19 18:35:46 DEBUG    Thread-54 :: Using cached parse result for: The.Walking.Dead.S06E02.HDTV.x264-FLEET
2015-10-19 18:35:46 INFO     Thread-54 :: Release name (the.walking.dead.s06e02.hdtv.x264-fleet) found from file (the.walking.dead.s06e02.hdtv.x264-fleet.nfo)
2015-10-19 18:35:46 DEBUG    Thread-54 :: Using cached parse result for: the.walking.dead.s06e02.hdtv.x264-fleet
2015-10-19 18:35:46 DEBUG    Thread-54 :: Found release name The.Walking.Dead.S06E02.HDTV.x264-FLEET
2015-10-19 18:35:46 DEBUG    Thread-54 :: Trying to determine free space on destination drive
2015-10-19 18:35:46 DEBUG    Thread-54 :: There is no existing file so there's no worries about replacing it
2015-10-19 18:35:46 DEBUG    Thread-54 :: Snatch history had a version in it, using that: v-1
2015-10-19 18:35:46 DEBUG    Thread-54 :: Is ep a priority download: False
2015-10-19 18:35:46 DEBUG    Thread-54 :: Quality of the episode we're processing: 1
2015-10-19 18:35:46 DEBUG    Thread-54 :: Snatch history had a quality in it, using that: SDTV
2015-10-19 18:35:46 DEBUG    Thread-54 :: Retrieving episode object for 6x2
2015-10-19 18:35:46 DEBUG    Thread-54 :: Using cached parse result for: The.Walking.Dead.S06E02.HDTV.x264-FLEET
2015-10-19 18:35:46 DEBUG    Thread-54 :: Analyzing name u'The.Walking.Dead.S06E02.HDTV.x264-FLEET.mp4'
2015-10-19 18:35:46 DEBUG    Thread-54 :: Found result in history: (, 6, [], 1, -1)
2015-10-19 18:35:43 INFO     Thread-54 :: Processing X:\TV\The.Walking.Dead.S06E02.HDTV.x264-FLEET\The.Walking.Dead.S06E02.HDTV.x264-FLEET.mp4 (None)
2015-10-19 18:35:43 DEBUG    Thread-54 :: Using cached parse result for: X:\TV\The.Walking.Dead.S06E02.HDTV.x264-FLEET
2015-10-19 18:35:43 DEBUG    Thread-54 :: PostProcessing VideoInRar: []
2015-10-19 18:35:43 DEBUG    Thread-54 :: PostProcessing RarContent: []
2015-10-19 18:35:43 DEBUG    Thread-54 :: PostProcessing VideoFiles: [u'The.Walking.Dead.S06E02.HDTV.x264-FLEET.mp4']
2015-10-19 18:35:43 DEBUG    Thread-54 :: PostProcessing Files: [u'the.walking.dead.s06e02.hdtv.x264-fleet.nfo', u'The.Walking.Dead.S06E02.HDTV.x264-FLEET.mp4']
2015-10-19 18:35:43 DEBUG    Thread-54 :: PostProcessing Dirs: []
2015-10-19 18:35:43 INFO     Thread-54 :: PostProcessing Path: X:\TV\The.Walking.Dead.S06E02.HDTV.x264-FLEET
2015-10-19 18:35:43 DEBUG    Thread-54 :: TV_DOWNLOAD_DIR: X:\TV\aaa to file
2015-10-19 18:35:43 DEBUG    Thread-54 :: Processing folder X:\TV\The.Walking.Dead.S06E02.HDTV.x264-FLEET

**Comment by neoatomic** [comment]
Its a permissions problem as you can see in the log. : 
`Y:\The Walking Dead\Season 06\The Walking Dead - S06E02 - JSS.mp4: error 13 : Permission denied`

So check those. And make sure the files aren't in use/seeding, and that PP is not set to fast as the file can be in use than also.

**Comment by amzeus** [comment]
if you look at the original post you will see that i can cp the file from the same box running SR so it isn't a permissions issue with the file and the file isn't being seeded PP is being done manually and auto has been set to 720 minutes. 

it has only become an issue since the last update (git pull) prior to this it was PPing fine how could updating effect SR process user account ? and what would it be now as 777 should allow any user to read and write

**Comment by neoatomic** [comment]
Only thing i can say is that sickrage has no permissions to the files.
Maybe your download client has set different permissions on the file.? Read-only.? etc...

You can try to remove the cache folder, but i doubt that will work. And you could always backup and reinstall SR.

**Comment by amzeus** [comment]
its baffling the hell out of me if I manually CP the file to the destination SR will Rename it and add metadata files
it will unrar a file but then fail to copy it over
