### ISSUE TITLE
init.debian errors

### ISSUE THREAD

**Issue by brunis** [SiCKRAGETV/sickrage-issues#346]
Hi,

I've been starting sickrage manually for awhile with: python -d SickBeard.py but got tired of the manual labor, so i copied the init.debian script to my /etc/init.d/

But when i try to start it up i get this:
root@debian:/etc/init.d# ./sickrage start
Traceback (most recent call last):
  File "SickBeard.py", line 58, in <module>
    import sickbeard
  File "/opt/SickRage-3.3.3/sickbeard/__init__.py", line 33, in <module>
    from sickbeard import providers, metadata, config, webserveInit
  File "/opt/SickRage-3.3.3/sickbeard/metadata/__init__.py", line 22, in <module>
    import kodi, kodi_12plus, mediabrowser, ps3, wdtv, tivo, mede8er
  File "/opt/SickRage-3.3.3/sickbeard/metadata/kodi.py", line 19, in <module>
    import generic
  File "/opt/SickRage-3.3.3/sickbeard/metadata/generic.py", line 38, in <module>
    import fanart
ImportError: No module named fanart

**Comment by fernandog** [comment]
follow this please after the "Once that's through we need to create the call file:"
https://sickrage.tv/forums/forum/help-support/general-support/6013-sickrage-ubuntu-install-guide#post6013

**Comment by brunis** [comment]
I have a call file already, but i have an /opt/sickbeard/ symlink pointing to /opt/SickRage-3.3.3, so all files are where SickRage expects and looks.
Unsurprisingly, setting the entries again did not yield better results.

**Comment by fernandog** [comment]
can you try without the symlink?
I also using debian and it's working. So must be something in your setup
