### ISSUE TITLE
Rename of episode fails...

### ISSUE THREAD

**Issue by AubreyKloppers** [SiCKRAGETV/sickrage-issues#3509]
Trying to rename a file to the same name:
The GUI:
	2	Season 01/Crazy Ex-Girlfriend - S01E02 - Josh’s Girlfriend is Really Cool!.mp4	Season 01/Crazy Ex-Girlfriend - S01E02 - Josh’s Girlfriend Is Really Cool!.mp4

The log:
2015-10-30 11:56:43 DEBUG    Thread-26 :: formatting pattern: Season %0S -> Season 01
2015-10-30 11:56:43 DEBUG    Thread-26 :: Renaming/moving episode from the base path /mnt/tv/Crazy Ex-Girlfriend/Season 01/Crazy Ex-Girlfriend - S01E02 - Joshâs Girlfriend is Really Cool!.mp4 to /mnt/tv/Crazy Ex-Girlfriend/Season 01/Crazy Ex-Girlfriend - S01E02 - Joshâs Girlfriend Is Really Cool!
2015-10-30 11:56:43 ERROR    Thread-26 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 251, in async_call
    result = function(**kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 1840, in doRename
    root_ep_obj.rename()
  File "/opt/sickbeard/sickbeard/tv.py", line 2481, in rename
    self.location, base_name_only=True, subfolders=True)
  File "/opt/sickbeard/sickbeard/postProcessor.py", line 185, in list_associated_files
    filelist = recursive_glob(ek(os.path.dirname, globbable_file_path), base_name + '*') # just create the list of all files starting with the basename
  File "/opt/sickbeard/sickbeard/postProcessor.py", line 159, in recursive_glob
    for base, dirs, files in os.walk(treeroot):
  File "/usr/lib/python2.7/os.py", line 284, in walk
    if isdir(join(top, name)):
  File "/usr/lib/python2.7/genericpath.py", line 41, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 73: ordinal not in range(128)
Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 251, in async_call
    result = function(**kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 1840, in doRename
    root_ep_obj.rename()
  File "/opt/sickbeard/sickbeard/tv.py", line 2481, in rename
    self.location, base_name_only=True, subfolders=True)
  File "/opt/sickbeard/sickbeard/postProcessor.py", line 185, in list_associated_files
    filelist = recursive_glob(ek(os.path.dirname, globbable_file_path), base_name + '*') # just create the list of all files starting with the basename
  File "/opt/sickbeard/sickbeard/postProcessor.py", line 159, in recursive_glob
    for base, dirs, files in os.walk(treeroot):
  File "/usr/lib/python2.7/os.py", line 284, in walk
    if isdir(join(top, name)):
  File "/usr/lib/python2.7/genericpath.py", line 41, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 73: ordinal not in range(128)
2015-10-30 11:56:43 DEBUG    TORNADO :: Failed doing webui request "doRename": Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 236, in get
    results = yield self.async_call(method)
  File "/opt/sickbeard/tornado/gen.py", line 870, in run
    value = future.result()
  File "/opt/sickbeard/lib/concurrent/futures/_base.py", line 400, in result
    return self.__get_result()
  File "/opt/sickbeard/lib/concurrent/futures/_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "/opt/sickbeard/lib/concurrent/futures/_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "/opt/sickbeard/lib/concurrent/futures/thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 251, in async_call
    result = function(**kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 1840, in doRename
    root_ep_obj.rename()
  File "/opt/sickbeard/sickbeard/tv.py", line 2481, in rename
    self.location, base_name_only=True, subfolders=True)
  File "/opt/sickbeard/sickbeard/postProcessor.py", line 185, in list_associated_files
    filelist = recursive_glob(ek(os.path.dirname, globbable_file_path), base_name + '*') # just create the list of all files starting with the basename
  File "/opt/sickbeard/sickbeard/postProcessor.py", line 159, in recursive_glob
    for base, dirs, files in os.walk(treeroot):
  File "/usr/lib/python2.7/os.py", line 284, in walk
    if isdir(join(top, name)):
  File "/usr/lib/python2.7/genericpath.py", line 41, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 73: ordinal not in range(128)

**Comment by neoatomic** [comment]
Special characters are the problem `Joshâs`.
Remove those, or make sure u have UTF-8 setup correctly as your locale.
