### ISSUE TITLE
DB error: database is locked

### ISSUE THREAD

**Issue by brianjmurrell** [SiCKRAGETV/sickrage-issues#3511]
SickRage was complaining that the database was locked.  So I restarted it and it still complains.  I have restarted a number of times and it continues to complain:

```
06:29:46 DEBUG::MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: ['standard']]
06:29:46 DEBUG::MAIN :: Episode has no release group, replacing it with 'RLSGROUP'
06:29:46 DEBUG::MAIN :: formatting pattern: S%0SE%0E - %EN -> S02E03 - Ep Name
06:29:46 DEBUG::MAIN :: Trying to parse S02E03 - Ep Name.ext
06:29:46 DEBUG::MAIN :: Parsed S02E03 - Ep Name.ext into S02E03 [ABD: False] [ANIME: False] [whichReg: ['standard']]
06:29:46 DEBUG::MAIN :: The name S02E03 - Ep Name.ext parsed into S02E03 [ABD: False] [ANIME: False] [whichReg: ['standard']]
06:29:46 DEBUG::MAIN :: Checking database structure...sickbeard.db
06:29:47 DEBUG::MAIN :: Checking Initial Schema database upgrade
06:29:47 DEBUG::MAIN :: InitialSchema upgrade not required
06:29:47 DEBUG::MAIN :: Checking Add Size And Scene Name Fields database upgrade
06:29:47 DEBUG::MAIN :: AddSizeAndSceneNameFields upgrade not required
06:29:47 DEBUG::MAIN :: Checking Rename Season Folders database upgrade
06:29:47 DEBUG::MAIN :: RenameSeasonFolders upgrade not required
06:29:47 DEBUG::MAIN :: Checking Add1080p And Raw Qualities database upgrade
06:29:47 DEBUG::MAIN :: Add1080pAndRawHDQualities upgrade not required
06:29:47 DEBUG::MAIN :: Checking Add Showid Tvdbid Index database upgrade
06:29:47 DEBUG::MAIN :: AddShowidTvdbidIndex upgrade not required
06:29:47 DEBUG::MAIN :: Checking Add Last Update database upgrade
06:29:47 DEBUG::MAIN :: AddLastUpdateTVDB upgrade not required
06:29:47 DEBUG::MAIN :: Checking Add Increase To15 database upgrade
06:29:47 DEBUG::MAIN :: AddDBIncreaseTo15 upgrade not required
06:29:47 DEBUG::MAIN :: Checking Add Db Info database upgrade
06:29:47 DEBUG::MAIN :: AddIMDbInfo upgrade not required
06:29:47 DEBUG::MAIN :: Checking Add Proper Naming Support database upgrade
06:29:47 DEBUG::MAIN :: AddProperNamingSupport upgrade not required
06:29:47 DEBUG::MAIN :: Checking Add Email Subscription Table database upgrade
06:29:47 DEBUG::MAIN :: AddEmailSubscriptionTable upgrade not required
06:29:47 DEBUG::MAIN :: Checking Add Proper Search database upgrade
06:29:47 DEBUG::MAIN :: AddProperSearch upgrade not required
06:29:47 DEBUG::MAIN :: Checking Add Dvd Order Option database upgrade
06:29:47 DEBUG::MAIN :: AddDvdOrderOption upgrade not required
06:29:47 DEBUG::MAIN :: Checking Add Subtitles Support database upgrade
06:29:48 DEBUG::MAIN :: AddSubtitlesSupport upgrade not required
06:29:48 DEBUG::MAIN :: Checking Convert Shows To Indexer Scheme database upgrade
06:29:48 DEBUG::MAIN :: ConvertTVShowsToIndexerScheme upgrade not required
06:29:48 DEBUG::MAIN :: Checking Convert Episodes To Indexer Scheme database upgrade
06:29:48 DEBUG::MAIN :: ConvertTVEpisodesToIndexerScheme upgrade not required
06:29:48 DEBUG::MAIN :: Checking Convert Info To Indexer Scheme database upgrade
06:29:48 DEBUG::MAIN :: ConvertIMDBInfoToIndexerScheme upgrade not required
06:29:48 DEBUG::MAIN :: Checking Convert Info To Indexer Scheme database upgrade
06:29:48 DEBUG::MAIN :: ConvertInfoToIndexerScheme upgrade not required
06:29:48 DEBUG::MAIN :: Checking Add Archive First Match Option database upgrade
06:29:48 DEBUG::MAIN :: AddArchiveFirstMatchOption upgrade not required
06:29:48 DEBUG::MAIN :: Checking Add Scene Numbering database upgrade
06:29:48 DEBUG::MAIN :: AddSceneNumbering upgrade not required
06:29:48 DEBUG::MAIN :: Checking Convert Indexer To Integer database upgrade
06:29:48 DEBUG::MAIN :: ConvertIndexerToInteger upgrade not required
06:29:48 DEBUG::MAIN :: Checking Add Require And Ignore Words database upgrade
06:29:48 DEBUG::MAIN :: AddRequireAndIgnoreWords upgrade not required
06:29:48 DEBUG::MAIN :: Checking Add Sports Option database upgrade
06:29:48 DEBUG::MAIN :: AddSportsOption upgrade not required
06:29:48 DEBUG::MAIN :: Checking Add Scene Numbering To Tv Episodes database upgrade
06:29:48 DEBUG::MAIN :: AddSceneNumberingToTvEpisodes upgrade not required
06:29:48 DEBUG::MAIN :: Checking Add Anime Show database upgrade
06:29:48 DEBUG::MAIN :: AddAnimeTVShow upgrade not required
06:29:48 DEBUG::MAIN :: Checking Add Absolute Numbering database upgrade
06:29:48 DEBUG::MAIN :: AddAbsoluteNumbering upgrade not required
06:29:48 DEBUG::MAIN :: Checking Add Scene Absolute Numbering database upgrade
06:29:49 DEBUG::MAIN :: AddSceneAbsoluteNumbering upgrade not required
06:29:49 DEBUG::MAIN :: Checking Add Anime Blacklist Whitelist database upgrade
06:29:49 DEBUG::MAIN :: AddAnimeBlacklistWhitelist upgrade not required
06:29:49 DEBUG::MAIN :: Checking Add Scene Absolute Numbering2 database upgrade
06:29:49 DEBUG::MAIN :: AddSceneAbsoluteNumbering2 upgrade not required
06:29:49 DEBUG::MAIN :: Checking Add Xem Refresh database upgrade
06:29:49 DEBUG::MAIN :: AddXemRefresh upgrade not required
06:29:49 DEBUG::MAIN :: Checking Add Scene To Tv Shows database upgrade
06:29:49 DEBUG::MAIN :: AddSceneToTvShows upgrade not required
06:29:49 DEBUG::MAIN :: Checking Add Indexer Mapping database upgrade
06:29:49 DEBUG::MAIN :: AddIndexerMapping upgrade not required
06:29:49 DEBUG::MAIN :: Checking Add Version To Tv Episodes database upgrade
06:29:49 DEBUG::MAIN :: AddVersionToTvEpisodes upgrade not required
06:29:49 DEBUG::MAIN :: Checking Add Default Ep Status To Tv Shows database upgrade
06:29:49 DEBUG::MAIN :: AddDefaultEpStatusToTvShows upgrade not required
06:29:49 DEBUG::MAIN :: Checking Alter Shows Field Types database upgrade
06:29:49 DEBUG::MAIN :: AlterTVShowsFieldTypes upgrade not required
06:29:49 DEBUG::MAIN :: Checking database structure...cache.db
06:29:49 DEBUG::MAIN :: Checking Initial Schema database upgrade
06:29:49 DEBUG::MAIN :: InitialSchema upgrade not required
06:29:49 DEBUG::MAIN :: Checking Add Scene Exceptions database upgrade
06:29:49 DEBUG::MAIN :: AddSceneExceptions upgrade not required
06:29:49 DEBUG::MAIN :: Checking Add Scene Name Cache database upgrade
06:29:49 DEBUG::MAIN :: AddSceneNameCache upgrade not required
06:29:50 DEBUG::MAIN :: Checking Add Network Timezones database upgrade
06:29:50 DEBUG::MAIN :: AddNetworkTimezones upgrade not required
06:29:50 DEBUG::MAIN :: Checking Add Last Search database upgrade
06:29:50 DEBUG::MAIN :: AddLastSearch upgrade not required
06:29:50 DEBUG::MAIN :: Checking Add Scene Exceptions Seasons database upgrade
06:29:50 DEBUG::MAIN :: AddSceneExceptionsSeasons upgrade not required
06:29:50 DEBUG::MAIN :: Checking Add Scene Exceptions Custom database upgrade
06:29:50 DEBUG::MAIN :: AddSceneExceptionsCustom upgrade not required
06:29:50 DEBUG::MAIN :: Checking Add Scene Exceptions Refresh database upgrade
06:29:50 DEBUG::MAIN :: AddSceneExceptionsRefresh upgrade not required
06:29:50 DEBUG::MAIN :: Checking database structure...failed.db
06:29:50 DEBUG::MAIN :: Checking Initial Schema database upgrade
06:29:50 DEBUG::MAIN :: InitialSchema upgrade not required
06:29:50 DEBUG::MAIN :: Checking Size And Provider database upgrade
06:29:50 DEBUG::MAIN :: SizeAndProvider upgrade not required
06:29:50 DEBUG::MAIN :: Checking History database upgrade
06:29:50 DEBUG::MAIN :: History upgrade not required
06:29:50 DEBUG::MAIN :: Checking History Status database upgrade
06:29:50 DEBUG::MAIN :: HistoryStatus upgrade not required
06:30:11 ERROR::MAIN :: DB error: database is locked
Traceback (most recent call last):
  File "/src/SickRage/sickbeard/db.py", line 202, in action
    self.connection.commit()
OperationalError: database is locked
06:30:32 ERROR::MAIN :: DB error: database is locked
Traceback (most recent call last):
  File "/src/SickRage/sickbeard/db.py", line 202, in action
    self.connection.commit()
OperationalError: database is locked
06:30:53 ERROR::MAIN :: DB error: database is locked
Traceback (most recent call last):
  File "/src/SickRage/sickbeard/db.py", line 202, in action
    self.connection.commit()
OperationalError: database is locked
06:31:14 ERROR::MAIN :: DB error: database is locked
Traceback (most recent call last):
  File "/src/SickRage/sickbeard/db.py", line 202, in action
    self.connection.commit()
OperationalError: database is locked
06:31:35 ERROR::MAIN :: DB error: database is locked
Traceback (most recent call last):
  File "/src/SickRage/sickbeard/db.py", line 202, in action
    self.connection.commit()
OperationalError: database is locked
06:31:56 ERROR::MAIN :: DB error: database is locked
Traceback (most recent call last):
  File "/src/SickRage/sickbeard/db.py", line 202, in action
    self.connection.commit()
OperationalError: database is locked
06:32:17 ERROR::MAIN :: DB error: database is locked
Traceback (most recent call last):
  File "/src/SickRage/sickbeard/db.py", line 202, in action
    self.connection.commit()
OperationalError: database is locked
```

Nothing else has the database open:

```
$ fuser sickbeard.db
sickbeard.db: 27750
$ ps -p27750 fw
  PID TTY      STAT   TIME COMMAND
27750 pts/14   S+     0:01 python SickBeard.py
```

Suffice to say, this has been running for weeks now before this happened, so this is not some kind of new-user problem.

Any ideas?

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by neoatomic** [comment]
This mainly happens when 2 instances of sickrage are running. Or when the permissions/owner is not correct. (sometimes happens when a manual restore is not done correctly.)

**Comment by brianjmurrell** [comment]
On Fri, 2015-10-30 at 05:00 -0700, neoatomic wrote:
> This mainly happens when 2 instances of sickrage are running.

Nope.  Double, triple and quadruple checked.  There was only ever one.

>  Or when the permissions/owner is not correct.

Nope.  Permissions were fine.  Always 0644 and owned by me.

>  (sometimes happens when a manual restore is not done correctly.)

There was no manual restore.  As I said in my description, this was a
running SR that just suddenly started returning these errors.

I even shut down SR and tried to do something with the database
directly, using sqlite3 and it complained that the database was locked
also (and still is).

I have since just recreated the database with a:

$ echo ".dump" | sqlite3 sickbeard.db | sqlite3 sickbeard-new.db
$ mv sickbeard.db sickbeard.db-locked
$ mv sickbeard-new.db sickbeard.db

and started SR again and it's now working.  But sickbeard.db-locked is
still showing as locked when I try to do anything with it using
sqlite3:

$ sqlite3 sickbeard.db-locked
SQLite version 3.8.10.2 2015-05-20 18:17:19
Enter ".help" for usage hints.
sqlite> insert into whitelist(show_id) values(1); 
Error: database is locked
sqlite>

**Comment by neoatomic** [comment]
Then the DB might got corrupted. Anyway glad its working again. :)
