### ISSUE TITLE
database disk image is malformed / recuurent problem

### ISSUE THREAD

**Issue by jadm557** [SiCKRAGETV/sickrage-issues#3590]
I seem to have a recurrent problem.
Phython, 2.7 / windows
I can solve it temporarily by making a dump of the sickrage db in a new version.
Every couple of days (sometimes faster) the problem reoccurs.

below the log

2015-11-08 09:40:50 INFO     MAIN :: Building internal name cache for all shows
2015-11-08 09:40:48 INFO     MAIN :: Checking for scene exception updates for AniDB
2015-11-08 09:40:47 INFO     MAIN :: Checking for XEM scene exception updates for theTVDB
2015-11-08 09:40:47 INFO     FINDSUBTITLES :: Checking for subtitles
2015-11-08 09:40:47 INFO     MAIN :: Checking for scene exception updates for theTVDB
2015-11-08 09:40:47 INFO     TORNADO :: Starting SickRage on http://0.0.0.0:9095/
2015-11-08 09:40:47 INFO     MAIN :: 264628: Unable to find IMDb show info in the database
2015-11-08 09:40:46 INFO     MAIN :: 71462: Unable to find IMDb show info in the database
2015-11-08 09:40:46 INFO     MAIN :: 71493: Unable to find IMDb show info in the database
2015-11-08 09:40:45 INFO     MAIN :: 71619: Unable to find IMDb show info in the database
2015-11-08 09:40:45 INFO     MAIN :: 263239: Unable to find IMDb show info in the database
2015-11-08 09:40:45 INFO     MAIN :: 83756: Unable to find IMDb show info in the database
2015-11-08 09:40:45 INFO     MAIN :: 79508: Unable to find IMDb show info in the database
2015-11-08 09:40:44 INFO     MAIN :: 80596: Unable to find IMDb show info in the database
AADatabaseError: database disk image is malformed
AA    return self._execute(query, args).fetchall()
AA  File "D:\SickRage\sickbeard\db.py", line 95, in execute
AA    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
AA  File "D:\SickRage\sickbeard\db.py", line 200, in action
AATraceback (most recent call last):
2015-11-08 09:38:43 ERROR    Thread-55 :: Fatal error executing query: database disk image is malformed
2015-11-08 09:37:55 INFO     FINDSUBTITLES :: Checking for subtitles
2015-11-08 09:09:58 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by neoatomic** [comment]
Sadly cant say much with the current info.

But sounds more like you have a bad DB or a bad installation. 
Would recommend to use the windows installer to setup SickRage and start with a fresh DB.

**Comment by fernandog** [comment]
You cant touch database (copy/backup/else) while SR is running

**Comment by jadm557** [comment]
fernandog: I do a shutdown of sickrage before making the dump 
neoatomic: if you need any additional info: just ask.
My setup predates the windows installer, so maybe it is time to switch?
I have the latest updates but I did have problems with special characters in the past.
Maybe a residual problem?
https://github.com/SiCKRAGETV/sickrage-issues/issues/2319

**Comment by fernandog** [comment]
So you have any backup script running while SR is running? Disable windowx indexer for SR folder

I used to have this while backup database file while SR was running
