### ISSUE TITLE
Sick rage + TPB search error - 

### ISSUE THREAD

**Issue by rosskinard** [SiCKRAGETV/sickrage-issues#3610]
Get this error when it tries to search TPB for anything:
12:24:50 ERROR::SEARCHQUEUE-BACKLOG-73543 :: [ThePirateBay] :: Connection timed out (sockets) accessing getURL https://pirateproxy.la/s/?q=The+13+Ghosts+of+Scooby-Doo+S01E12&orderby=7&category=200&type=search&page=0 Error: '__str__ returned non-string (type Error)'
Traceback (most recent call last):
  File "/Users/me/SickRage/sickbeard/helpers.py", line 1608, in getURL
    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
  File "/Users/me/SickRage/lib/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/Users/me/SickRage/lib/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/me/SickRage/lib/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Users/me/SickRage/lib/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/Users/me/SickRage/lib/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/Users/me/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/Users/me/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/Users/me/SickRage/lib/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type Error)

If I put the URL listed in the error into a browser it connects and returns the results, so it's not that the site is blocked.

OS X 10.11.1
Python 2.7.10
OpenSSL 1.0.2d 9 Jul 2015

Turned off SIP and created proper symlinks to insure all apps can connect to the components needed.

Any ideas? All the other threads I searched for and read listed things I've already done, so not sure what's up with my config.

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by larrysharon** [comment]
Same issue...have you been able to resolve?

**Comment by rosskinard** [comment]
Nope...not so far.

**Comment by pATYbulaire** [comment]
Hello,

You may have installed the same package i did, because at some point, i don't remember when, i've been requested to. A pyOpenSSL pip package.

It broke my sickrage with the same error.

Using the following command, try to see if you don't have something like this:

pip freeze
....
pyOpenSSL==0.15.1
....

If installed, remove it:

pip uninstall pyOpenSSL

restart Sickrage.

it worked for me.

PaT

**Comment by Nikola-K** [comment]
Happens to me too for KAT and TPB, for all searches. Also OS X 10.11.1, same python version and openssl. pyOpenSSL is not installed.

**Comment by duramato** [comment]
@Nikola-K Then install pyOpenSSL !!!! ,its needed for proper SSL handling

**Comment by fernandog** [comment]
i think we should add a big WARNING in red like the "updates available" so users install this damm pyOpenSSL

**Comment by duramato** [comment]
@fernandog yeah like the develop branch warning if it isnt isntalled

**Comment by larrysharon** [comment]
I've tried installing and uninstalling and nothing is working. Can anyone walk
me through it. On OSX.

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.1]
On Wed, Nov 11, 2015 at 5:02 PM, supergonkas <notifications@github.com> wrote:
@fernandog [https://github.com/fernandog] yeah like the develop branch warning if it isnt isntalled

—
Reply to this email directly or view it on GitHub
[https://github.com/SiCKRAGETV/sickrage-issues/issues/3610#issuecomment-155923393] .[https://github.com/notifications/beacon/AFvGlJ6Sk7MdMHZTuoVbVT6NzVtvwZk0ks5pE7JhgaJpZM4GfqmR.gif]

**Comment by Nikola-K** [comment]
@duramato @fernandog 

Sorry, I've forgot to specify that I've tried installing and uninstalling pyopenssl (pyOpenSSL==0.15.1). I was more referring to the comment above that says to uninstall it.

**Comment by pATYbulaire** [comment]
Hello,

Be careful, as explained in my very first comment, I installed it, that's
right, but it was a mistake as I already had it installed another way. This
second installation broke my sickrage on tpb and Kat.

You still need it, but properly installed.

Le jeu. 12 nov. 2015 07:42, Nikola Kovacevic [Masked]
<FWD-737QTYSMENAIYCQANIQDDYATEFMCCYCTAC6AEUAEQAY4M5BDDMZU4Q2EFZQVGCCAAKAAF3KTEEDC2KBVI45WZPJDVAJCUSN4HZHEYLLZVAI6QJXNIDVVOUJSTRBCY7NSGQAQHLCCH4LSGLT4AARFBMCQEFUCGTBCFQQFYIBMEJOZA4AAA7IALUADANJEGUEVBEMCAIAAEA======@
opayq.com> a écrit :

**Comment by pATYbulaire** [comment]
Also, just to be sure this isn't a provider block situation, when you
browse the https URL (the one in the log) with your browser, does it work?

Le jeu. 12 nov. 2015 08:03, Anthony Basile <9ed369dc@opayq.com> a
écrit :

**Comment by Nikola-K** [comment]
> $ which pip 
    /usr/local/bin/pip

    > $ which python
    /usr/local/bin/python

    > $ python --version
    Python 2.7.10

    > $ pip freeze | grep "pyOpenSSL" 
    pyOpenSSL==0.15.1

URL checked (from logs):

    2015-11-12 07:37:55 SEARCHQUEUE-MANUAL-95011 :: [ThePirateBay] :: Connection timed out (sockets) accessing getURL https://pirateproxy.la/s/?q=Modern+Family+S07E06&orderby=7&category=200&type=search&page=0 Error: '__str__ returned non-string (type Error)'

Loads fine in browser and there aren't any blocks.

**Comment by pATYbulaire** [comment]
Hello,

In this page, they say to not install the 0.15.

It's for Windows, I agree. But it worth a try for you to find the 0.13 as
they suggest.

http://www.htpcguides.com/install-sickrage-windows-usenet-torrent-tv/

PaT

Le jeu. 12 nov. 2015 18:02, Nikola Kovacevic [Masked]
<FWD-737QTYSMENAIYCQANIQDDYATEFMCCYCTAC6AEUZQSY3KWMBFIBFRJWBEAIFTAARZNVMF3OLUOEUZODTPDXODK2SNUAE3GE2QICBQAUYCPECNSQ3IE3BWFPCOJZNVURFQHDUCARABHMDDYGBACUUQKIAOUAOOAEXAAXQAFYAV6B5OIQE3AB5QATRGFAIT2DWIICZAAIAAEA======@
opayq.com> a écrit :

**Comment by Nikola-K** [comment]
pyopenssl 0.13.x has issues building against newer versions of openssl see: https://github.com/pyca/pyopenssl/issues/276

So I guess the workaround might be to downgrade openssl, which doesn't sound like the best solution to this bug. I'll look into it over weekend to see if downgrading openssl and pyopenssl solves the issue if nobody tests it by then.
