### ISSUE TITLE
sslv3 alert handshake failures when trying to search for new files

### ISSUE THREAD

**Issue by drinn** [SiCKRAGETV/sickrage-issues#3637]
I'm running SickRage on FreeBSD and somewhere in the last 9 commits, my searches for files stopped working with errors relating to SSL handshake failures.  I am currently running BRANCH: (master) / COMMIT: (c19526435dc15ba1bcd5827dd24d6a8e69c83e2b).

Prior to updating my last commits, things were working just fine.  I tried disabling "Verify SSL Certs" and deleting my cache.db and mako/sessions directories to no avail.  After a little more research, I tried updating my openssl version to a later version and then recompiling python against the newer version of openssl which seemed to resolve the issue.

That solution isn't particularly ideal as I'll now have to recompile python every time there is a new update for it instead of just installing the version that comes as a package with the system.  It's not a huge issue to do so, but I figured I'd post a bug report as I've had SickRage installed for many months without any SSL issues before.

Below are the relevant portions of the log file for your perusal:

2015-11-14 03:33:53 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Site1] :: Connection error to getURL https://site1.url.example.com Error: u'error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)'
Traceback (most recent call last):
  File "/path/to/SickRage-master/sickbeard/helpers.py", line 1608, in getURL
    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
  File "/path/to/SickRage-master/lib/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/path/to/SickRage-master/lib/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/path/to/SickRage-master/lib/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/path/to/SickRage-master/lib/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/path/to/SickRage-master/lib/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)
2015-11-14 03:33:53 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Site2] :: Connection error to getURL https://site2.url.example.com Error: u'error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)'
Traceback (most recent call last):
  File "/path/to/SickRage-master/sickbeard/helpers.py", line 1608, in getURL
    resp = session.get(url, timeout=timeout, allow_redirects=True, verify=session.verify)
  File "/path/to/SickRage-master/lib/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/path/to/SickRage-master/lib/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/path/to/SickRage-master/lib/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/path/to/SickRage-master/lib/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/path/to/SickRage-master/lib/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*
