### ISSUE TITLE
Can´t change episode status

### ISSUE THREAD

**Issue by networkpadawan** [SiCKRAGETV/sickrage-issues#366]
When trying to change the status of an episode sr crashes:

BRANCH: (develop) / COMMIT: (8b84e4f4bc6cdebdc605438e9e75d15f1133d65e) 

2015-01-09 14:24:34 Thread-101 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/tiago/SickRage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/home/tiago/SickRage/sickbeard/webserve.py", line 1548, in setStatus
    if not statusStrings.has_key(int(status)):
ValueError: invalid literal for int() with base 10: 'undefined'

2015-01-09 14:24:16 Thread-99 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/tiago/SickRage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/home/tiago/SickRage/sickbeard/webserve.py", line 1548, in setStatus
    if not statusStrings.has_key(int(status)):
ValueError: invalid literal for int() with base 10: 'undefined'

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/285
