### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character ordinal not in range (128)

### ISSUE THREAD

**Issue by brando56894** [SiCKRAGETV/sickrage-issues#3703]
Edit: While adding in my info I noticed that my SickRage locale is set to (None, None). How do I fix this?

I know this is a long standing issue that can be resolved by setting your locale but this doesn't seem to be the case for me in FreeBSD. Python itself works fine with these characters, SickRage doesn't seem to like them though for some reason. What's going on here?

I have all the variables set:

[root@UsenetApps /usenet]# locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"

And it clearly works in the python shell:

[root@UsenetApps /usenet]$ python
 python 2.7.10 (default, Oct 20 2015, 17:24:44) 
[GCC 4.2.1 20070831 patched [FreeBSD]] on freebsd9
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.getdefaultencoding()
'ascii'
>>> print u"\xfa"
ú
>>> print u'\u2019'
’
>>> print u"\u2019"
’
>>> print u"\u2026"
…
>>> print u"\u2014"
—

Yet it just crashes in SickRage:
2015-11-19 07:24:57 Thread-13 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/local/sickrage/sickbeard/webserve.py", line 259, in async_call
    result = function(**kwargs)
  File "/usr/local/sickrage/sickbeard/webserve.py", line 2203, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), type=type
  File "/usr/local/sickrage/sickbeard/processTV.py", line 272, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/usr/local/sickrage/sickbeard/processTV.py", line 554, in process_media
    result.result = processor.process()
  File "/usr/local/sickrage/sickbeard/postProcessor.py", line 951, in process
    self._delete(cur_ep.location, associated_files=True)
  File "/usr/local/sickrage/sickbeard/postProcessor.py", line 234, in _delete
    file_list = file_list + self.list_associated_files(file_path, base_name_only=True, subfolders=True)
  File "/usr/local/sickrage/sickbeard/postProcessor.py", line 186, in list_associated_files
    filelist = recursive_glob(ek(os.path.dirname, globbable_file_path), base_name + '*') # just create the list of all files starting with the basename
  File "/usr/local/sickrage/sickbeard/postProcessor.py", line 160, in recursive_glob
    for base, _, files in os.walk(treeroot):
  File "/usr/local/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/local/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 47: ordinal not in range(128)

2015-11-19 07:23:52 Thread-25 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/local/sickrage/sickbeard/webserve.py", line 259, in async_call
    result = function(**kwargs)
  File "/usr/local/sickrage/sickbeard/webserve.py", line 2203, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), type=type
  File "/usr/local/sickrage/sickbeard/processTV.py", line 272, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/usr/local/sickrage/sickbeard/processTV.py", line 554, in process_media
    result.result = processor.process()
  File "/usr/local/sickrage/sickbeard/postProcessor.py", line 951, in process
    self._delete(cur_ep.location, associated_files=True)
  File "/usr/local/sickrage/sickbeard/postProcessor.py", line 234, in _delete
    file_list = file_list + self.list_associated_files(file_path, base_name_only=True, subfolders=True)
  File "/usr/local/sickrage/sickbeard/postProcessor.py", line 186, in list_associated_files
    filelist = recursive_glob(ek(os.path.dirname, globbable_file_path), base_name + '*') # just create the list of all files starting with the basename
  File "/usr/local/sickrage/sickbeard/postProcessor.py", line 160, in recursive_glob
    for base, _, files in os.walk(treeroot):
  File "/usr/local/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/local/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 47: ordinal not in range(128)

2015-11-19 07:21:27 Thread-52 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/local/sickrage/sickbeard/webserve.py", line 259, in async_call
    result = function(**kwargs)
  File "/usr/local/sickrage/sickbeard/webserve.py", line 2203, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), type=type
  File "/usr/local/sickrage/sickbeard/processTV.py", line 272, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/usr/local/sickrage/sickbeard/processTV.py", line 554, in process_media
    result.result = processor.process()
  File "/usr/local/sickrage/sickbeard/postProcessor.py", line 951, in process
    self._delete(cur_ep.location, associated_files=True)
  File "/usr/local/sickrage/sickbeard/postProcessor.py", line 234, in _delete
    file_list = file_list + self.list_associated_files(file_path, base_name_only=True, subfolders=True)
  File "/usr/local/sickrage/sickbeard/postProcessor.py", line 186, in list_associated_files
    filelist = recursive_glob(ek(os.path.dirname, globbable_file_path), base_name + '*') # just create the list of all files starting with the basename
  File "/usr/local/sickrage/sickbeard/postProcessor.py", line 160, in recursive_glob
    for base, _, files in os.walk(treeroot):
  File "/usr/local/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/local/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 81: ordinal not in range(128)

SR Version: 	BRANCH: (master) / COMMIT: (c19526435dc15ba1bcd5827dd24d6a8e69c83e2b)
SR User:	root
SR Locale:	(None, None)
SR Config:	/usenet/sickrage/config.ini
SR Database:	/usenet/sickrage/sickbeard.db
SR Cache Dir:	/usenet/sickrage/cache
SR Log Dir:	/usenet/sickrage/logs
SR Arguments:	['--datadir', '/usenet/sickrage', '-d', '--pidfile', '/var/run/sickrage/sickrage.pid', '--quiet', '--nolaunch']
Python Version:	2.7.10 (default, Oct 20 2015, 17:24:44) [GCC 4.2.1 20070831 patched [FreeBSD]]

**Comment by brando56894** [comment]
no one?

**Comment by chonkworld** [comment]
I'm having this issue as well.

**Comment by chonkworld** [comment]
Oddly enough, my SickRage locale was set to (None, None). Checking out Develop and switching back to Master resolved this for me.

**Comment by brando56894** [comment]
Did it resolve just the (None, None) issue or the UnicodeDecode error? It doesn't want to work I try to switch branches and says to check the logs even though there aren't any errors in the logs, everything looks fine.

**Comment by chonkworld** [comment]
It resolved the (None, None) issue, which in turn resolved the post-processing issue. I had to manually switch branches via the command line using the git tools.

|| Michael Ryan

**Comment by brando56894** [comment]
Ah cool thanks, I'll give it a try.
