### ISSUE TITLE
PostProcessor won't overwrite a higher quality file with lower quality file.

### ISSUE THREAD

**Issue by systemloc** [SiCKRAGETV/sickrage-issues#3712]
I prefer SDTV as my archival quality, but often only HDTV is initially available. I have my quality setting as custom, with all qualities selected in 'allowed', but only sdtv in 'preferred'. 

Post processor won't overwrite an HDTV file with an SDTV file.

OS: Slackware 14.1
SR Version:	BRANCH: (master) / COMMIT: (d294e9faf48d45051a50d4e2cf3a0252c28d5b17) 
SR Arguments:	['-d']
Python Version:	2.7.5 (default, May 29 2013, 03:26:28) [GCC 4.8.0]

2015-11-22 08:49:17 INFO     POSTPROCESSER :: Processing /mnt/home/system/share/SickRageTorrents/American.Horror.Story.S02E05.HDTV.x264-LOL.[VTV].mp4 (None)
2015-11-22 08:49:17 DEBUG    POSTPROCESSER :: Analyzing name u'American.Horror.Story.S02E05.HDTV.x264-LOL.[VTV].mp4'
2015-11-22 08:49:17 DEBUG    POSTPROCESSER :: Parsed American.Horror.Story.S02E05.HDTV.x264-LOL into American Horror Story - S02E05 [GROUP: LOL] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-11-22 08:49:17 DEBUG    POSTPROCESSER :: Retrieving episode object for 2x5
2015-11-22 08:49:17 DEBUG    POSTPROCESSER :: Snatch history had a quality in it, using that: SDTV
2015-11-22 08:49:17 DEBUG    POSTPROCESSER :: Quality of the episode we're processing: 1
2015-11-22 08:49:17 DEBUG    POSTPROCESSER :: Is ep a priority download: False
2015-11-22 08:49:17 DEBUG    POSTPROCESSER :: File /home/system/share/sickrage_dl/American Horror Story/Season 02/American.Horror.Story.S02E05.I.Am.Anne.Frank.Pt.2.SDTV-SiCKRAGE.avi is larger than /mnt/home/system/share/SickRageTorrents/American.Horror.Story.S02E05.HDTV.x264-LOL.[VTV].mp4
2015-11-22 08:49:17 INFO     POSTPROCESSER :: File exists and new file is smaller, marking it unsafe to replace
2015-11-22 08:49:17 ERROR    POSTPROCESSER :: Processing failed for /mnt/home/system/share/SickRageTorrents/American.Horror.Story.S02E05.HDTV.x264-LOL.[VTV].mp4:
Traceback (most recent call last):
  File "/mnt/home/system/.sickrage/sickbeard/processTV.py", line 554, in process_media
    result.result = processor.process()
  File "/mnt/home/system/.sickrage/sickbeard/postProcessor.py", line 877, in process
    raise EpisodePostProcessingFailedException()
EpisodePostProcessingFailedException

**Comment by systemloc** [comment]
Browsing the post processor code, it doesn't seem that the post processor directly references the quality setting in determining priority. Whats the point of having 'allowed' and 'preferred' if it isn't used by the post processor?
