### ISSUE TITLE
QNAP 870pro 4.2.0 breaks postprocessing / renaming

### ISSUE THREAD

**Issue by sadsack5000** [SiCKRAGETV/sickrage-issues#3714]
Since upgrading my QNAP 870pro to 4.2.0 build 23.10.2015 post processing (either manual or auto) does not seem to work. Something to do with it failing to rename but I am a complete amateur so havent got a clue really.

Error below

Please assist

Branch: master | Now: 2015-11-22 14:00:35.800590-07:00

2015-11-22 13:55:06 Thread-49 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 259, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 1885, in doRename
    root_ep_obj.rename()
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/tv.py", line 2459, in rename
    self.location, base_name_only=True, subfolders=True)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/postProcessor.py", line 186, in list_associated_files
    filelist = recursive_glob(ek(os.path.dirname, globbable_file_path), base_name + '*') # just create the list of all files starting with the basename
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/postProcessor.py", line 160, in recursive_glob
    for base, _, files in os.walk(treeroot):
  File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/genericpath.py", line 41, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 117: ordinal not in range(128)

**Comment by sadsack5000** [comment]
Extra info:

SR Version:	BRANCH: (master) / COMMIT: (d294e9faf48d45051a50d4e2cf3a0252c28d5b17) 
SR User:	admin
SR Locale:	(None, None)
SR Config:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/config.ini
SR Database:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/sickbeard.db
SR Cache Dir:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/cache
SR Log Dir:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/Logs
SR Arguments:	['--daemon', '--datadir', '/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config', '--pidfile', '/tmp/SickBeard-TVRage.pid']
Python Version:	2.7.9 (default, Mar 24 2015, 00:42:24) [GCC 4.1.3 20070929 (prerelease) (Ubuntu 4.1.2-16ubuntu2)]

**Comment by doczong** [comment]
See this: 

https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do

**Comment by sadsack5000** [comment]
sorry about this but i dont know where sickrage gets installed to on the QNAP. I can access via SSL but havent got a clue where those files sit

**Comment by sadsack5000** [comment]
ok so i finally figured out how to add those lines to the ./.bashrc and ./.profile files. I run source ~/.bashrc and it comes up [admin@xxxxxxxx ~]# and that is all.

Once i have done this i tried post processing again... on a file which contains no special characters in the existing filename or new filename but still get the issue

Seems like it might just be this one folder im getting issues with as i have post processed another folder fine

**Comment by doczong** [comment]
those files are in /root (and are hidden but you can edit them with "vi" or even if you are using an FTP type client like WinSCP)...

and they only apply to "new" processes.  so assuming you edited the correct files in the correct location, you would still have to stop and restart sickrage to take effect.

The reason this probably broke is that the QNAP upgrade blew away the configuration that was already there.  You could always remove and reinstall the SR QPKG to get those configs back as well, but then you'll have to setup your media library.

I would suggest calling QNAP support if you are unable to do the above, because well, they broke it.

I'm still on 3.8.3 firmware, and I'm not changing because QNAP breaks more on upgrades than they fix.
