### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by bacevs** [SiCKRAGETV/sickrage-issues#3716]
Branch:	Master
Commit hash:	d294e9faf48d45051a50d4e2cf3a0252c28d5b17
Your operating system and python version:	QNAP v4.2.0(2015/10/23) Python v2.7
What you did:	Copied some episodes manually into TV root directory. Rescanned the show. Tried to perform a rename on the episodes I copied within SickRage.
What happened:	It didn't rename the episodes and instead kicked me from the tv show url to /home/. It also gave the following error log: http://paste2.org/OpJx1e1k
What you expected: For it to rename the episodes and move into the correct season folder. 
How can we reproduce your issue: Not sure. 

Additional Info:
I have also tried doing this suggested [Fix](https://sickrage.tv/forums/forum/help-support/general-support/12825-ensuring-your-locale-s-are-set-properly-to-avoid-unicode-issues). It didn't help.
 
![Image of preview Rename](http://i.imgur.com/Bmaa5ye.png)

![Image of error log](http://i.imgur.com/v5GX6OP.png)

![Image of folder contents](http://i.imgur.com/SzeHoJG.png)

**Comment by doczong** [comment]
Did you restart SR after making those changes?  Those changes are applied only to new processes.
I'm running QNAP 3.8.3, I do not have these issues you guys on the newer firmware seem to have.

**Comment by Naesstrom** [comment]
Feels like this is related to the same problem that I'm having with the latest release (BRANCH: (master) / COMMIT: (d294e9faf48d45051a50d4e2cf3a0252c28d5b17))


```
2015-11-23 22:58:20 Thread-57 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 259, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 2203, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), type=type
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 272, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/processTV.py", line 554, in process_media
    result.result = processor.process()
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/postProcessor.py", line 951, in process
    self._delete(cur_ep.location, associated_files=True)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/postProcessor.py", line 234, in _delete
    file_list = file_list + self.list_associated_files(file_path, base_name_only=True, subfolders=True)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/postProcessor.py", line 186, in list_associated_files
    filelist = recursive_glob(ek(os.path.dirname, globbable_file_path), base_name + '*') # just create the list of all files starting with the basename
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/postProcessor.py", line 160, in recursive_glob
    for base, _, files in os.walk(treeroot):
  File "/usr/pbi/sickrage-amd64/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/pbi/sickrage-amd64/lib/python2.7/genericpath.py", line 41, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 85: ordinal not in range(128)
```

**Comment by rmbleeker** [comment]
It seems to be an issue with python 2.7, it's fixed in python 3, see #3554

**Comment by doczong** [comment]
Interesting, I'm on 2.7.10 and I do not have any of these issues.

**Comment by rmbleeker** [comment]
The issue should only occur when python 2.7 encounters a filename that has non-ASCII characters in it. Since ASCII was modelled after the English language and I dare say most shows people watch are from the US, you'll probably only rarely encounter this.

Python 3 is full Unicode and therefore shouldn't have this issue.

**Comment by doczong** [comment]
Gotcha... although... if you look through the recent tickets, a lot of the Unicode issues are in fact with English language shows, on what looks to be English language OSes.  So while Py3 will probably fix it, something else does seem to be in play and I suspect it had something to do with the old devs saying they were going to start transitioning to Py3 at some point.  Probably to get around this, but the Unicode bug as echel0n calls it seems to remain regardless.

**Comment by rmbleeker** [comment]
I encountered this too a short while ago with episode 6 of Marvel's Agents of S.H.I.E.L.D "Among Us Hide" which used to have a triple dot (…) character at the end of the show name, which is a non-ASCII character. So yes, it can occur with English language shows in a en_US locale like mine. TheTVDB has since changed the episode's name to not contain that character anymore.

**Comment by doczong** [comment]
En, also weird because I didn't get burned by that Episode.  Perhaps it was a different source.

Marvels.Agents.of.S.H.I.E.L.D.S03E06.Among.Us.Hide….SDTV-FLEET.mp4

Got this in my .profile:
LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
LC_CTYPE=en_US.UTF-8

**Comment by labrys** [comment]
FYI: Python 3 also has unicode issues, it just handles them differently, since it forces you to encode / decode you generally know where and what the issues are as you go.  Python 2 tries to be smart and auto-convert things for you which can lead to issues.
