### ISSUE TITLE
manual issue: post-processing fail 

### ISSUE THREAD

**Issue by miton18** [SiCKRAGETV/sickrage-issues#3719]
2015-11-23 12:52:41 Thread-51 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 259, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 1885, in doRename
    root_ep_obj.rename()
  File "/opt/sickrage/sickbeard/tv.py", line 2459, in rename
    self.location, base_name_only=True, subfolders=True)
  File "/opt/sickrage/sickbeard/postProcessor.py", line 186, in list_associated_files
    filelist = recursive_glob(ek(os.path.dirname, globbable_file_path), base_name + '*') # just create the list of all files starting with the basename
  File "/opt/sickrage/sickbeard/postProcessor.py", line 160, in recursive_glob
    for base, _, files in os.walk(treeroot):
  File "/usr/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/lib/python2.7/genericpath.py", line 41, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 69: ordinal not in range(128)

**Comment by doczong** [comment]
Did you do this (and then restart SR)
https://sickrage.tv/forums/forum/help-support/general-support/12825-ensuring-your-locale-s-are-set-properly-to-avoid-unicode-issues

**Comment by reisrdok** [comment]
FYI, only way I could fix this old "ordinal not in range" bug was to add following line to SickRage.py, after "import locale":

locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')
