### ISSUE TITLE
Issues with TVChaos, TorrentDay and Speed.cd

### ISSUE THREAD

**Issue by bigmattp** [SiCKRAGETV/sickrage-issues#3731]
2015-11-25 16:44:05 SEARCHQUEUE-MANUAL-71067 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded
2015-11-25 16:43:56 SEARCHQUEUE-MANUAL-71067 :: [Speedcd] :: Error while searching Speedcd, skipping: No JSON object could be decoded
2015-11-25 16:43:49 SEARCHQUEUE-MANUAL-71067 :: [TvChaosUK] :: Error while searching TvChaosUK, skipping: 'NoneType' object has no attribute 'find_all'

**Comment by polyneux** [comment]
Also showing: Error while searching Speedcd, skipping: No JSON object could be decoded

Do not have others.

**Comment by ProjectLane** [comment]
Also getting the same issue, and here is the stacktrace for what it's worth:
```
AAValueError: No JSON object could be decoded
AA    raise ValueError("No JSON object could be decoded")
AA  File "/usr/local/sickbeard/lib/simplejson/decoder.py", line 353, in raw_decode
AA    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
AA  File "/usr/local/sickbeard/lib/simplejson/decoder.py", line 335, in decode
AA    return _default_decoder.decode(s)
AA  File "/usr/local/sickbeard/lib/simplejson/__init__.py", line 307, in loads
AA    return json.loads(self.text, **kwargs)
AA  File "/usr/local/sickbeard/lib/requests/models.py", line 802, in json
AA    return resp.content if not json else resp.json()
AA  File "/usr/local/sickbeard/sickbeard/helpers.py", line 1650, in getURL
AA    session=self.session, json=json, proxyGlypeProxySSLwarning=self.proxyGlypeProxySSLwarning)
AA  File "/usr/local/sickbeard/sickbeard/providers/generic.py", line 153, in getURL
AA    parsedJSON = self.getURL(self.urls['search'], post_data=post_data, json=True)
AA  File "/usr/local/sickbeard/sickbeard/providers/speedcd.py", line 94, in _doSearch
AA    itemList += self._doSearch(curString, search_mode, len(episodes), epObj=epObj)
AA  File "/usr/local/sickbeard/sickbeard/providers/generic.py", line 349, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/usr/local/sickbeard/sickbeard/search.py", line 495, in searchProviders
AATraceback (most recent call last):
```

**Comment by mvarrieur** [comment]
:+1: same issue here, I'm guessing the API changed since these sites are all run similarly or the same from what I remember.

**Comment by echel0n** [comment]
which branch ?

**Comment by mvarrieur** [comment]
master for me

**Comment by imrathion** [comment]
Same here... also on master
