### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: u'/home/osmc/.sickrage/gui/slick/images/network/fx (us).png'

### ISSUE THREAD

**Issue by dsoms** [SiCKRAGETV/sickrage-issues#3737]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.2.3-2-osmc-armv7l-with-debian-8.2**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@089a7115571d9fe0db80c60d193809d380b5f7b0
Link to Log: https://gist.github.com/6ad35ca89e9fe12c0199
### ERROR
```
Thread-27::Failed doing webui callback: Traceback (most recent call last):
  File "/home/osmc/.sickrage/sickbeard/webserve.py", line 261, in async_call
    result = function(**kwargs)
  File "/home/osmc/.sickrage/sickbeard/webserve.py", line 389, in showPoster
    return media.get_media()
  File "/home/osmc/.sickrage/sickrage/media/GenericMedia.py", line 62, in get_media
    with open(static_media_path, 'rb') as content:
IOError: [Errno 2] No such file or directory: u'/home/osmc/.sickrage/gui/slick/images/network/fx (us).png'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dsoms** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.2.3-2-osmc-armv7l-with-debian-8.2**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@089a7115571d9fe0db80c60d193809d380b5f7b0
Link to Log: https://gist.github.com/5ef4d1e6461e976d54a0
### ERROR
```
Thread-44::Failed doing webui callback: Traceback (most recent call last):
  File "/home/osmc/.sickrage/sickbeard/webserve.py", line 261, in async_call
    result = function(**kwargs)
  File "/home/osmc/.sickrage/sickbeard/webserve.py", line 389, in showPoster
    return media.get_media()
  File "/home/osmc/.sickrage/sickrage/media/GenericMedia.py", line 62, in get_media
    with open(static_media_path, 'rb') as content:
IOError: [Errno 2] No such file or directory: u'/home/osmc/.sickrage/gui/slick/images/network/fx (us).png'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dsoms** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.2.3-2-osmc-armv7l-with-debian-8.2**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@089a7115571d9fe0db80c60d193809d380b5f7b0
Link to Log: https://gist.github.com/7657152853dbc67a75ee
### ERROR
```
Thread-30::Failed doing webui callback: Traceback (most recent call last):
  File "/home/osmc/.sickrage/sickbeard/webserve.py", line 261, in async_call
    result = function(**kwargs)
  File "/home/osmc/.sickrage/sickbeard/webserve.py", line 389, in showPoster
    return media.get_media()
  File "/home/osmc/.sickrage/sickrage/media/GenericMedia.py", line 62, in get_media
    with open(static_media_path, 'rb') as content:
IOError: [Errno 2] No such file or directory: u'/home/osmc/.sickrage/gui/slick/images/network/fx (us).png'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by dsoms** [comment]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.2.3-2-osmc-armv7l-with-debian-8.2**
Locale: unknown
Branch: **develop**
Commit: SiCKRAGETV/SickRage@089a7115571d9fe0db80c60d193809d380b5f7b0
No Log available with ERRORS: 
### ERROR
```
Thread-34::Failed doing webui callback: Traceback (most recent call last):
  File "/home/osmc/.sickrage/sickbeard/webserve.py", line 261, in async_call
    result = function(**kwargs)
  File "/home/osmc/.sickrage/sickbeard/webserve.py", line 389, in showPoster
    return media.get_media()
  File "/home/osmc/.sickrage/sickrage/media/GenericMedia.py", line 62, in get_media
    with open(static_media_path, 'rb') as content:
IOError: [Errno 2] No such file or directory: u'/home/osmc/.sickrage/gui/slick/images/network/fx (us).png'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators
