### ISSUE TITLE
invalid literal for int() with base 10: 'undefined' 

### ISSUE THREAD

**Issue by meokey** [SiCKRAGETV/sickrage-issues#374]
Error

invalid literal for int() with base 10: 'undefined'

Traceback

Traceback (most recent call last): 
File "/usr/share/SickRage/tornado/web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback)) 
File "/usr/share/SickRage/tornado/stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs) 
File "/usr/share/SickRage/tornado/concurrent.py", line 226, in lambda future: callback(future.result())) 
File "/usr/share/SickRage/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result() 
File "/usr/share/SickRage/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "/usr/share/SickRage/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "/usr/share/SickRage/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "/usr/share/SickRage/sickbeard/webserve.py", line 230, in async_call result = function(**kwargs) 
File "/usr/share/SickRage/sickbeard/webserve.py", line 1548, in setStatus if not statusStrings.has_key(int(status)): 
ValueError: invalid literal for int() with base 10: 'undefined' 

Request Info

body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /home/setStatus?show=265145&eps=0x2|0x1&status=undefined
query_arguments: {'status': ['undefined'], 'eps': ['0x2|0x1'], 'show': ['265145']}
_start_time: 1420868054.76
headers: {'Accept-Language': 'en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4', 'Accept-Encoding': 'gzip, deflate, sdch', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36', 'Dnt': '1', 'Host': 'vhost:8080', 'Referer': 'http://vhost:8080/home/displayShow?show=265145', 'Cookie': 'snatched_view2=list; soon_view2=thumbs; late_view2=list; locale=en_US; user="2|1:0|10:1420844573|4:user|44:NzdkNGU3ODQ3MmZlMjE5ZTMwMDc1Nzk4NzliNjM2ZDY=|3d3d934e35693ade5a0f43694371efb49a3e7e758058a46ef8c01f167a545fdd"'}
host: vhost:8080
version: HTTP/1.1
arguments: {'status': 'undefined', 'eps': '0x2|0x1', 'show': '265145'}
_finish_time: None
query: show=265145&eps=0x2|0x1&status=undefined
path: /home/setStatus
_cookies: Set-Cookie: late_view2=list Set-Cookie: locale=en_US Set-Cookie: snatched_view2=list Set-Cookie: soon_view2=thumbs Set-Cookie: user="2|1:0|10:1420844573|4:user|44:NzdkNGU3ODQ3MmZlMjE5ZTMwMDc1Nzk4NzliNjM2ZDY=|3d3d934e35693ade5a0f43694371efb49a3e7e758058a46ef8c01f167a545fdd"
method: GET
remote_ip: 192.168.0.99

View Log(Errors)

**Comment by bahamas10** [comment]
same issue here... show is Total Riff Off

```
Error

invalid literal for int() with base 10: ''
Traceback

Traceback (most recent call last):
File "/opt/sickrage/SickRage/tornado/web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback))
File "/opt/sickrage/SickRage/tornado/stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs)
File "/opt/sickrage/SickRage/tornado/concurrent.py", line 226, in lambda future: callback(future.result()))
File "/opt/sickrage/SickRage/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result()
File "/opt/sickrage/SickRage/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback)
File "/opt/sickrage/SickRage/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_)
File "/opt/sickrage/SickRage/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs)
File "/opt/sickrage/SickRage/sickbeard/webserve.py", line 230, in async_call result = function(**kwargs)
File "/opt/sickrage/SickRage/sickbeard/webserve.py", line 1165, in displayShow return t.respond()
File "/opt/sickrage/SickRage/cache/cheetah/_opt_sickrage_SickRage_gui_slick_interfaces_default_displayShow_tmpl.py", line 968, in respond
ValueError: invalid literal for int() with base 10: ''
Request Info

body:
files: {}
protocol: http
connection:
body_arguments: {}
uri: /home/displayShow?show=279893
query_arguments: {'show': ['279893']}
_start_time: 1420871801.41
headers: {'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:34.0) Gecko/20100101 Firefox/34.0', 'Host': 'XXXXXXXXX:8081', 'Referer': 'http://XXXXXXX:8081/home/', 'Cookie': 'snatched_view2=list; soon_view2=thumbs; suggestions_charts_menu_selected=suggestions; compact_display_state=true; wanted_view2=details; late_view2=list; sort_direction=descending; sort_method=queue_order; advanced_toggle_checked=1'}
host: XXXXXXXXXXX
version: HTTP/1.1
arguments: {'show': '279893'}
_finish_time: None
query: show=279893
path: /home/displayShow
method: GET
remote_ip: X.X.X.X
```
