### ISSUE TITLE
Error  downloading Subtitles

### ISSUE THREAD

**Issue by Terminator-X** [SiCKRAGETV/sickrage-issues#375]
Hi,

I keep getting this error message and I am no code-expert like many of you. Any idea's what's wrong?
- BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8) 
- Python 2.7.6
- running on a Thecus NAS, thecus OS, linux based
- Arguments: ['-d', '-p', '8081', '--datadir', '/raid/data/MOD_CONFIG/SICK/DATA', '--config', '/raid/data/MOD_CONFIG/SICK/CONF/sickbeard.conf']

```python
2015-01-04 23:36:36 FINDSUBTITLES :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/sickbeard/tv.py", line 1392, in downloadSubtitles
    multi=sickbeard.SUBTITLES_MULTI, cache_dir=sickbeard.CACHE_DIR)
  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/lib/subliminal/api.py", line 95, in download_subtitles
    subtitles_by_video = list_subtitles(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/lib/subliminal/api.py", line 62, in list_subtitles
    service_instance.terminate()
  File "/raid0/data/module/SickBeardTVR/sys/SickBeard/lib/subliminal/services/opensubtitles.py", line 103, in terminate
    raise ServiceError(str(e))
```

**Comment by fernandog** [comment]
@Terminator-X still happening? maybe opensubtitles were down.
