### ISSUE TITLE
postprocessing errors

### ISSUE THREAD

**Issue by distracto** [SiCKRAGETV/sickrage-issues#3752]
constant errors on file size being the same, and manual processing gives this error:

2015-11-30 11:00:46 Thread-26 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 259, in async_call
    result = function(**kwargs)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 2203, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), type=type
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/processTV.py", line 225, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/processTV.py", line 554, in process_media
    result.result = processor.process()
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/postProcessor.py", line 940, in process
    if not helpers.isFileLocked(self.file_path, False):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1878, in isFileLocked
    if not os.path.exists(checkfile):
  File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\ua789' in position 75: ordinal not in range(128)

**Comment by echel0n** [comment]
This issue is being worked on just out right now with family for my birthday so will tend to this shortly.
