### ISSUE TITLE
DB error: disk I/O error and Errors when searching

### ISSUE THREAD

**Issue by Tass5233** [SiCKRAGETV/sickrage-issues#379]
Hi, 

Im very new to SickRage, so please forgive me if this has been addressed. I was initially getting 
DB error: disk I/O error when updating, but I left Sickrage on for the evening and have gotten a whole bunch of more errors, I believe it may have been trying to search for shows which caused this..?

I believe I had set up SickRage correctly and had followed the htpc guide (http://www.htpcguides.com/configure-sickrage-usenet-torrent-tv/)

Im pasting this below, if anyone can help or point me in the right direction I would really appreciate it, 

2015-01-10 22:35:54 Thread-62 :: Failed doing webui callback: Traceback (most recent call last):
  File "/Applications/SickRage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/Applications/SickRage/sickbeard/webserve.py", line 3390, in index
    return t.respond()
  File "/Applications/SickRage/cache/cheetah/_Applications_SickRage_gui_slick_interfaces_default_config_general_tmpl.py", line 952, in respond
    for cur_branch in VFN(VFSL([locals()]+SL+[globals(), builtin],"sickbeard.versionCheckScheduler.action",True),"list_remote_branches",False)(): # generated from line 521, col 10
TypeError: 'NoneType' object is not iterable

2015-01-10 22:13:56 FINDPROPERS :: [KickAssTorrents] :: Failed to parsing KickAssTorrents Traceback: Traceback (most recent call last):
  File "/Applications/SickRage/sickbeard/providers/kat.py", line 235, in _doSearch
    entries = self.cache.getRSSFeed(searchURL, items=['entries', 'feed'])['entries']
  File "/Applications/SickRage/sickbeard/tvcache.py", line 144, in getRSSFeed
    return RSSFeeds(self.providerID).getFeed(self.provider.proxy._buildURL(url), post_data, self.provider.headers, items)
  File "/Applications/SickRage/sickbeard/rssfeeds.py", line 57, in getFeed
    self.rssDB.close()
  File "/Applications/SickRage/lib/sqliteshelf.py", line 142, in close
    self.conn.commit()
OperationalError: cannot commit - no transaction is active

2015-01-10 22:13:54 FINDPROPERS :: [KickAssTorrents] :: Failed to parsing KickAssTorrents Traceback: Traceback (most recent call last):
  File "/Applications/SickRage/sickbeard/providers/kat.py", line 235, in _doSearch
    entries = self.cache.getRSSFeed(searchURL, items=['entries', 'feed'])['entries']
  File "/Applications/SickRage/sickbeard/tvcache.py", line 144, in getRSSFeed
    return RSSFeeds(self.providerID).getFeed(self.provider.proxy._buildURL(url), post_data, self.provider.headers, items)
  File "/Applications/SickRage/sickbeard/rssfeeds.py", line 57, in getFeed
    self.rssDB.close()
  File "/Applications/SickRage/lib/sqliteshelf.py", line 142, in close
    self.conn.commit()
OperationalError: cannot commit - no transaction is active

2015-01-10 21:31:33 SEARCHQUEUE-DAILY-SEARCH :: [NyaaTorrents] :: Error while searching NyaaTorrents, skipping: cannot commit - no transaction is active
2015-01-10 21:31:33 SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: Failed to parsing KickAssTorrents Traceback: Traceback (most recent call last):
  File "/Applications/SickRage/sickbeard/providers/kat.py", line 235, in _doSearch
    entries = self.cache.getRSSFeed(searchURL, items=['entries', 'feed'])['entries']
  File "/Applications/SickRage/sickbeard/tvcache.py", line 144, in getRSSFeed
    return RSSFeeds(self.providerID).getFeed(self.provider.proxy._buildURL(url), post_data, self.provider.headers, items)
  File "/Applications/SickRage/sickbeard/rssfeeds.py", line 57, in getFeed
    self.rssDB.close()
  File "/Applications/SickRage/lib/sqliteshelf.py", line 142, in close
    self.conn.commit()
OperationalError: cannot commit - no transaction is active

2015-01-10 20:11:33 SEARCHQUEUE-DAILY-SEARCH :: [NyaaTorrents] :: Error while searching NyaaTorrents, skipping: cannot commit - no transaction is active
2015-01-10 20:11:32 SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: Failed to parsing KickAssTorrents Traceback: Traceback (most recent call last):
  File "/Applications/SickRage/sickbeard/providers/kat.py", line 235, in _doSearch
    entries = self.cache.getRSSFeed(searchURL, items=['entries', 'feed'])['entries']
  File "/Applications/SickRage/sickbeard/tvcache.py", line 144, in getRSSFeed
    return RSSFeeds(self.providerID).getFeed(self.provider.proxy._buildURL(url), post_data, self.provider.headers, items)
  File "/Applications/SickRage/sickbeard/rssfeeds.py", line 57, in getFeed
    self.rssDB.close()
  File "/Applications/SickRage/lib/sqliteshelf.py", line 142, in close
    self.conn.commit()
OperationalError: cannot commit - no transaction is active

2015-01-10 08:26:13 SHOWQUEUE-REFRESH :: No episode number found in /Users/qaizervisram/Movies and Tv Shows/Current Shows/Anime/Fate Stay Night - Unlimited Blade Works 2014/Season 0/Fate stay night [Unlimited Blade Works].S01E.Prologue.mkv, ignoring it
2015-01-10 08:22:38 SHOWQUEUE-FORCE-UPDATE :: DB error: disk I/O error
2015-01-10 08:22:26 SHOWQUEUE-FORCE-UPDATE :: DB error: disk I/O error
2015-01-10 08:22:26 SHOWQUEUE-FORCE-UPDATE :: Error saving show info to the database: disk I/O error
2015-01-10 08:21:05 SHOWQUEUE-FORCE-UPDATE :: DB error: disk I/O error

**Comment by Tass5233** [comment]
Incase this is needed, 

SR Version:	BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8) 
SR Config file:	/Applications/SickRage/config.ini
SR Database file:	/Applications/SickRage/sickbeard.db
SR Cache Dir:	/Applications/SickRage/cache
SR Arguments:	['-q']
SR Web Root:	
Python Version:	2.7.6 (default, Sep 9 2014, 15:04:36) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]

**Comment by fernandog** [comment]
Error while searching ..., skipping: 'NoneType' object is not iterable'''

Close Sickbeard, then delete cache.db in your SickBeard directory. This may solve the problem.

If you still have the same issues, search the repository for the error message (without the specific provider name) and if there's an open issue, copy your log (at Debug level). If no such issue exists, open a new one.

https://github.com/SiCKRAGETV/SickRage/wiki/Frequently-Asked-Questions

**Comment by Tass5233** [comment]
@fernandog 

Thank you for your quick response, 

I deleted the cache.db, and then started getting a database disk image is malformed, so I have deleted it again, and edited the config.ini file for debugging, so far no errors, but once it shows up I will open a ticket,

**Comment by fernandog** [comment]
@Tass5233 to fix database disk image is malformed:

install sqlite3 if not already installed.
cd into your sickbrage directory

Run the commands:
```
mv sickbeard.db sickbeard.db.bak
sqlite3 sickbeard.db.bak .dump | sqlite3  sickbeard.db
```
Restart sickbeard

**Comment by Tass5233** [comment]
@fernandog 

Hi,
I havent gotten the database disk image is malformed error since the last time when I had deleted the cache.db and edited the config file mentioned earlier however I am now getting the below errors 

2015-01-11 14:38:01 FINDPROPERS :: DB error: disk I/O error
2015-01-11 14:38:01 FINDPROPERS :: Exception generated in thread FINDPROPERS: disk I/O error
2015-01-11 14:38:01 SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: DB error: disk I/O error
2015-01-11 14:38:01 SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: Error while searching KickAssTorrents, skipping: disk I/O error

Does this mean anything to you? should I go ahead and try installing sqlite3 and running the commands?

**Comment by fernandog** [comment]
backup your entire folder to SickRage-backup and re-install SickRage. Use the config.ini from backup. Let it create another database (sickbeard.db). If the error still persists then is something wrong with your HDD.

**Comment by Tass5233** [comment]
@fernandog 
Thank you for all your help, I decided to just check my hard disk and there were some errors which have now been repaired by Disk Utility. 

I would like to uninstall SickRage completely and do a fresh install, sorry for the very silly question, but would I go about this, do i just drag the sickrage folder to the trash like i would for a normal app (im on a mac) or was there an unistaller..? Ive tried googling it but I couldnt see an answer, sorry Im sure thats a very silly question, but Im totally green with this stuff :)

**Comment by fernandog** [comment]
@Tass5233 yes. only sickrage folder. do a backup as I told you. Don't delete it.

**Comment by Tass5233** [comment]
@fernandog 
Awesome! Thanks will do as soon as I get home from work!

**Comment by markheloking** [comment]
@Tass5233 please use markdown in the future.

**Comment by Tass5233** [comment]
Sorry, my first time posting on Github, will do in the future
