### ISSUE TITLE
Unable to change status of episode from wanted to archived

### ISSUE THREAD

**Issue by Rhazi3l** [SiCKRAGETV/sickrage-issues#381]
Python Version:	2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]
SR Version:	BRANCH: (develop) / COMMIT: (8b84e4f4bc6cdebdc605438e9e75d15f1133d65e)

After trying to change the status from Wanted to Archived i get the following error:

"2015-01-11 00:39:12 Thread-72 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 1548, in setStatus
    if not statusStrings.has_key(int(status)):
ValueError: invalid literal for int() with base 10: 'undefined'"

"Error

invalid literal for int() with base 10: 'undefined'

Traceback

Traceback (most recent call last): 
File "C:\SickRage\tornado\web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback)) 
File "C:\SickRage\tornado\stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs) 
File "C:\SickRage\tornado\concurrent.py", line 226, in lambda future: callback(future.result())) 
File "C:\SickRage\lib\concurrent\futures\_base.py", line 400, in result return self.__get_result() 
File "C:\SickRage\lib\concurrent\futures\_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "C:\SickRage\lib\concurrent\futures\_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "C:\SickRage\lib\concurrent\futures\thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "C:\SickRage\sickbeard\webserve.py", line 230, in async_call result = function(**kwargs) 
File "C:\SickRage\sickbeard\webserve.py", line 1548, in setStatus if not statusStrings.has_key(int(status)): 
ValueError: invalid literal for int() with base 10: 'undefined' 

Request Info

body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /home/setStatus?show=281249&eps=2x1&status=undefined
query_arguments: {'status': ['undefined'], 'eps': ['2x1'], 'show': ['281249']}
_start_time: 1420936752.94
headers: {'Accept-Language': 'pt-PT,en-GB;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.69 Safari/537.36', 'Host': 'localhost:8088', 'Referer': 'http://localhost:8088/home/displayShow?show=281249', 'Cookie': '_ga=GA1.1.418484398.1417319905'}
host: localhost:8088
version: HTTP/1.1
arguments: {'status': 'undefined', 'eps': '2x1', 'show': '281249'}
_finish_time: None
query: show=281249&eps=2x1&status=undefined
path: /home/setStatus
method: GET
remote_ip: 127.0.0.1"

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/285
