### ISSUE TITLE
Change show navigation not working - BRANCH: (develop)

### ISSUE THREAD

**Issue by TekGamer** [SiCKRAGETV/sickrage-issues#387]
When viewing a show,... the left, right, and dropdown "Change Show" navigation elements are not working... Error details:

2015-01-11 15:55:00 Thread-46 :: Failed doing webui callback: Traceback (most recent call last): File "C:\SickRage\sickbeard\webserve.py", line 230, in async_call result = function(**kwargs) File "C:\SickRage\sickbeard\webserve.py", line 1048, in displayShow showObj = sickbeard.helpers.findCertainShow(sickbeard.showLi st, int(show)) ValueError: invalid literal for int() with base 10: 'undefined' -------------------------- Error

invalid literal for int() with base 10: 'undefined'
Traceback

Traceback (most recent call last):
File "C:\SickRage\tornado\web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback))
File "C:\SickRage\tornado\stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs)
File "C:\SickRage\tornado\concurrent.py", line 226, in lambda future: callback(future.result()))
File "C:\SickRage\lib\concurrent\futures\_base.py", line 400, in result return self.__get_result()
File "C:\SickRage\lib\concurrent\futures\_base.py", line 359, in __get_result reraise(self._exception, self._traceback)
File "C:\SickRage\lib\concurrent\futures\_compat.py ", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_)
File "C:\SickRage\lib\concurrent\futures\thread.py" , line 61, in run result = self.fn(*self.args, **self.kwargs)
File "C:\SickRage\sickbeard\webserve.py", line 230, in async_call result = function(**kwargs)
File "C:\SickRage\sickbeard\webserve.py", line 1048, in displayShow showObj = sickbeard.helpers.findCertainShow(sickbeard.showLi st, int(show))
ValueError: invalid literal for int() with base 10: 'undefined'
Request Info

body: files: {} protocol: http connection: body_arguments: {} uri: /home/displayShow?show=undefined query_arguments: {'show': ['undefined']} _start_time: 1421013581.58 headers: {'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0', 'Dnt': '1', 'Host': '127.0.0.1:8081', 'Cookie': '_ga=GA1.1.724928525.1418335123'} host: 127.0.0.1:8081 version: HTTP/1.1 arguments: {'show': 'undefined'} _finish_time: None query: show=undefined path: /home/displayShow method: GET remote_ip

SR Version: 	BRANCH: (develop) / COMMIT: (8b84e4f4bc6cdebdc605438e9e75d15f1133d65e)
SR Config file: 	C:\SickRage\config.ini
SR Database file: 	C:\SickRage\sickbeard.db
SR Cache Dir: 	C:\SickRage\cache
SR Arguments: 	[]
SR Web Root: 	
Python Version: 	2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/285
