### ISSUE TITLE
Crash While Viewing General Settings

### ISSUE THREAD

**Issue by brando56894** [SiCKRAGETV/sickrage-issues#388]
Branch: Develop
OS: FreeBSD 9.3-RELEASE-p5 
commit: 8b84e4f4bc6cdebdc605438e9e75d15f1133d65e
Python Version: 2.7.9 (default, Jan 9 2015, 14:27:53) [GCC 4.2.1 20070831 patched [FreeBSD]]

What I do: I try to navigate to /config/general/ via anyway possible (directly by typing or via the buttons)
What I expect: it brings me to the general settings page
What it does: crashes
Repeatable: yes

Sickbeard log:

 2015-01-11 22:48:11 Thread-112 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/local/sickrage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/usr/local/sickrage/sickbeard/webserve.py", line 3390, in index
    return t.respond()
  File "/usr/local/sickrage/cache/cheetah/_usr_local_sickrage_gui_slick_interfaces_default_config_general_tmpl.py", line 952, in respond
    for cur_branch in VFN(VFFSL(SL,"sickbeard.versionCheckScheduler.action",True),"list_remote_branches",False)(): # generated from line 521, col 10
TypeError: 'NoneType' object is not iterable

Traceback (most recent call last): 
File "/usr/local/sickrage/tornado/web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback)) 
File "/usr/local/sickrage/tornado/stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs) 
File "/usr/local/sickrage/tornado/concurrent.py", line 226, in lambda future: callback(future.result())) 
File "/usr/local/sickrage/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result() 
File "/usr/local/sickrage/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "/usr/local/sickrage/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "/usr/local/sickrage/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "/usr/local/sickrage/sickbeard/webserve.py", line 230, in async_call result = function(**kwargs) 
File "/usr/local/sickrage/sickbeard/webserve.py", line 3390, in index return t.respond() 
File "/usr/local/sickrage/cache/cheetah/_usr_local_sickrage_gui_slick_interfaces_default_config_general_tmpl.py", line 952, in respond for cur_branch in VFN(VFFSL(SL,"sickbeard.versionCheckScheduler.action",True),"list_remote_branches",False)(): # generated from line 521, col 10 
TypeError: 'NoneType' object is not iterable 

Request Info

body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /config/general/
query_arguments: {}
_start_time: 1421034491.1
headers: {'Accept-Language': 'en-US,en;q=0.8,de;q=0.6', 'Accept-Encoding': 'gzip, deflate, sdch', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36', 'Dnt': '1', 'Host': '192.168.1.100:8081', 'Referer': 'http://192.168.1.100:8081/config/', 'Cookie': 'wanted_view2=details; advanced_toggle_checked=0; plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0'}
host: 192.168.1.100:8081
version: HTTP/1.1
arguments: {}
_finish_time: None
query: 
path: /config/general/
method: GET
remote_ip: 192.168.1.114

**Comment by fernandog** [comment]
@brando56894 stop your SR, edit config.ini and make sure version_notify = 1
start SR and try again please

please post you config.ini settings:
```
[General]
git_autoissues = 
git_username = 
git_password = 
git_reset = 
branch = 
git_remote = 
git_remote_url = 
cur_commit_hash = 
cur_commit_branch = 
```

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/307

**Comment by brando56894** [comment]
Yep it's enabled, here's the "general" section from my config.ini: http://pastebin.com/pNimfqVu

**Comment by Bokaii** [comment]
I am also having the same exact issue on branch Master, Synology DS215j, Python 2.7.8-11

Log:
2015-01-15 09:18:12 Thread-69 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 3390, in index
    return t.respond()
  File "/usr/local/sickbeard-custom/var/cache/cheetah/_usr_local_sickbeard_custom_var_SickBeard_gui_slick_interfaces_default_config_general_tmpl.py", line 952, in respond
    for cur_branch in VFN(VFFSL(SL,"sickbeard.versionCheckScheduler.action",True),"list_remote_branches",False)(): # generated from line 521, col 10
TypeError: 'NoneType' object is not iterable

**Comment by jlo88** [comment]
I am also having this issue for a month now on:
Branch: Master
COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8) 
Python: 2.7.8
Xubuntu

Log: 
2015-01-17 17:28:25 Thread-55 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/jan/sickrage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/home/jan/sickrage/sickbeard/webserve.py", line 3390, in index
    return t.respond()
  File "/home/jan/sickrage/cache/cheetah/_home_jan_sickrage_gui_slick_interfaces_default_config_general_tmpl.py", line 952, in respond
    for cur_branch in VFN(VFFSL(SL,"sickbeard.versionCheckScheduler.action",True),"list_remote_branches",False)(): # generated from line 521, col 10
TypeError: 'NoneType' object is not iterable

2015-01-17 14:58:33 Thread-44 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/jan/sickrage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/home/jan/sickrage/sickbeard/webserve.py", line 858, in testPLEX
    curResult = notifiers.plex_notifier.test_notify(urllib.unquote_plus(curHost), username, password)
  File "/home/jan/sickrage/sickbeard/notifiers/plex.py", line 78, in test_notify
    password, force=True)
  File "/home/jan/sickrage/sickbeard/notifiers/plex.py", line 56, in _notify_pmc
    force=True)
  File "/home/jan/sickrage/sickbeard/notifiers/kodi.py", line 131, in _notify_kodi
    kodiapi = self._get_kodi_version(curHost, username, password)
  File "/home/jan/sickrage/sickbeard/notifiers/kodi.py", line 78, in _get_kodi_version
    result = self._send_to_kodi_json(checkCommand, host, username, password)
  File "/home/jan/sickrage/sickbeard/notifiers/kodi.py", line 400, in _send_to_kodi_json
    logger.log(u"Unable to decode JSON: " + response, logger.WARNING)
TypeError: coercing to Unicode: need string or buffer, instance found

**Comment by markheloking** [comment]
Closing this as it's a duplicate. Please continue the discussion over at https://github.com/SiCKRAGETV/sickrage-issues/issues/307.

**Comment by markheloking** [comment]
Closing this as this is a duplicate.
