### ISSUE TITLE
Crash When Changing Episode Status

### ISSUE THREAD

**Issue by brando56894** [SiCKRAGETV/sickrage-issues#396]
Branch: Develop
OS: FreeBSD 9.3-RELEASE-p5 
commit: 8b84e4f4bc6cdebdc605438e9e75d15f1133d65e
Python Version: 2.7.9 (default, Jan 9 2015, 14:27:53) [GCC 4.2.1 20070831 patched [FreeBSD]]

What I was doing: changing the status of episodes from 'skipped' to 'wanted'
What happened: it crashed

Error

invalid literal for int() with base 10: 'undefined'

Traceback

Traceback (most recent call last): 
File "/usr/local/sickrage/tornado/web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback)) 
File "/usr/local/sickrage/tornado/stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs) 
File "/usr/local/sickrage/tornado/concurrent.py", line 226, in lambda future: callback(future.result())) 
File "/usr/local/sickrage/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result() 
File "/usr/local/sickrage/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "/usr/local/sickrage/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "/usr/local/sickrage/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "/usr/local/sickrage/sickbeard/webserve.py", line 230, in async_call result = function(**kwargs) 
File "/usr/local/sickrage/sickbeard/webserve.py", line 1548, in setStatus if not statusStrings.has_key(int(status)): 
ValueError: invalid literal for int() with base 10: 'undefined' 

Request Info

body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /home/setStatus?show=79257&eps=0x27|0x26|0x25|0x24|0x23|0x22|0x21|0x20|0x19|0x18|0x17|0x16|0x15|0x14|0x13|0x12|0x11|0x10|0x9|0x8|0x7|0x6|0x5|0x4|0x3|0x2|0x1&status=undefined
query_arguments: {'status': ['undefined'], 'eps': ['0x27|0x26|0x25|0x24|0x23|0x22|0x21|0x20|0x19|0x18|0x17|0x16|0x15|0x14|0x13|0x12|0x11|0x10|0x9|0x8|0x7|0x6|0x5|0x4|0x3|0x2|0x1'], 'show': ['79257']}
_start_time: 1421106737.42
headers: {'Accept-Language': 'en-US,en;q=0.8,de;q=0.6', 'Accept-Encoding': 'gzip, deflate, sdch', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36', 'Dnt': '1', 'Host': '192.168.1.100:8081', 'Referer': 'http://192.168.1.100:8081/home/displayShow?show=79257', 'Cookie': 'wanted_view2=details; plushRefreshRate=1; advanced_toggle_checked=1; snatched_view2=list; soon_view2=thumbs; suggestions_charts_menu_selected=suggestions; late_view2=list; plushQueuePerPage=20; plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0; plushHistPerPage=1'}
host: 192.168.1.100:8081
version: HTTP/1.1
arguments: {'status': 'undefined', 'eps': '0x27|0x26|0x25|0x24|0x23|0x22|0x21|0x20|0x19|0x18|0x17|0x16|0x15|0x14|0x13|0x12|0x11|0x10|0x9|0x8|0x7|0x6|0x5|0x4|0x3|0x2|0x1', 'show': '79257'}
_finish_time: None
query: show=79257&eps=0x27|0x26|0x25|0x24|0x23|0x22|0x21|0x20|0x19|0x18|0x17|0x16|0x15|0x14|0x13|0x12|0x11|0x10|0x9|0x8|0x7|0x6|0x5|0x4|0x3|0x2|0x1&status=undefined
path: /home/setStatus
method: GET
remote_ip: 192.168.1.114

Sickrage Log

2015-01-12 18:52:17 Thread-119 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/local/sickrage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/usr/local/sickrage/sickbeard/webserve.py", line 1548, in setStatus
    if not statusStrings.has_key(int(status)):
ValueError: invalid literal for int() with base 10: 'undefined'

General section of config file: http://pastebin.com/pNimfqVu

**Comment by brando56894** [comment]
What is this a duplicate of?

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/search?q=undefined&state=open&type=Issues&utf8=%E2%9C%93

https://github.com/SiCKRAGETV/sickrage-issues/issues/285

**Comment by markheloking** [comment]
@brando56894 please use markdown in the future.
