### ISSUE TITLE
NotFound: cannot find 'LOG_NR' while searching for 'sickbeard.LOG_NR'

### ISSUE THREAD

**Issue by meokey** [SiCKRAGETV/sickrage-issues#407]
right after new updates just now

2015-01-13 22:55:17 Thread-264 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/share/SickRage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/usr/share/SickRage/sickbeard/webserve.py", line 3390, in index
    {'title': 'Anime', 'path': 'config/anime/'},
  File "/usr/share/SickRage/cache/cheetah/_usr_share_SickRage_gui_slick_interfaces_default_config_general_tmpl.py", line 243, in respond
    _v = VFFSL(SL,"sickbeard.LOG_NR",True) # u'$sickbeard.LOG_NR' on line 104, col 62
NotFound: cannot find 'LOG_NR' while searching for 'sickbeard.LOG_NR'

2015-01-13 22:52:56 Thread-268 :: 
2015-01-13 22:52:25 Thread-254 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/share/SickRage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/usr/share/SickRage/sickbeard/webserve.py", line 4322, in index
  File "/usr/share/SickRage/cache/cheetah/_usr_share_SickRage_gui_slick_interfaces_default_config_notifications_tmpl.py", line 1987, in respond
    if VFFSL(SL,"sickbeard.USE_FREEMOBILE",True) : # generated from line 1206, col 118
NotFound: cannot find 'USE_FREEMOBILE' while searching for 'sickbeard.USE_FREEMOBILE'

**Comment by TagForce** [comment]
Probably because those values aren't yet set in the config file (as they are both new settings after the latest commits).

Can you restart SickRage? It should save the config upon a clean exit and add those values to the config.ini.

**Comment by meokey** [comment]
Yes, it works after restarting using sudo service command. Thank you.

Best Regards,
Biao

**Comment by TagForce** [comment]
Actually, the restart solved it, but probably not because of the new values...

I tried, and it looks like your cache/cheetah/ folder was filled with the old template caches. Restarting the service using sudo would probably solve that too (as it should attempt to clear the cache upon starting) :)
