### ISSUE TITLE
cant acess web ui

### ISSUE THREAD

**Issue by gimpacause** [SiCKRAGETV/sickrage-issues#408]
hi all , had sickrage running grat on my ubuntu machine, copied settings from my windows box over and it scred everything up, so idecided to wipe the install off ubuntu and start from scratch

Version : I am unsure an server is offline for matenance at the moment will report back once i find out 
would be latest from last night

this is the error i am recieving when i try to open webui

Traceback (most recent call last): 
File "/home/***/sickrage/tornado/web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback)) 
File "/home/***/sickrage/tornado/stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs) 
File "/home/***/sickrage/tornado/concurrent.py", line 226, in lambda future: callback(future.result())) 
File "/home/***/sickrage/lib/concurrent/futures/_base.py", line 400, in result 
File "/home/***/sickrage/lib/concurrent/futures/_base.py", line 359, in __get_result 
File "/home/***/sickrage/lib/concurrent/futures/_compat.py", line 107, in reraise 
File "/home/***/sickrage/lib/concurrent/futures/thread.py", line 61, in run 
File "/home/***/sickrage/sickbeard/webserve.py", line 230, in async_call func = getattr(klass, 'index', None) 
File "/home/***/sickrage/sickbeard/webserve.py", line 692, in index 
File "/home/***/sickrage/cache/cheetah/cheetah__home_***_sickrage_gui_slick_interfaces_default_home_tmpl_1420955487_61_20303.py", line 102, in respond 
File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1615, in _handleCheetahInclude self._CHEETAH__cheetahIncludes[_includeID].respond(trans) 
File "cheetah__home_***_sickrage_gui_slick_interfaces_default_inc_top_tmpl_1420955487_69_99233.py", line 525, in respond 
NotFound: cannot find 'USE_XBMC' while searching for 'sickbeard.USE_XBMC' 

Request Info

body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /home
query_arguments: {}
_start_time: 1421222114.01
headers: {'Accept-Language': 'en-US', 'Accept-Encoding': 'gzip,deflate', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/4.4.3.4000 Chrome/30.0.1599.101 Safari/537.36', 'Dnt': '1', 'Host': '192.168.0.19:8081', 'Cookie': 'plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0; snatched_view2=list; soon_view2=thumbs; suggestions_charts_menu_selected=suggestions; late_view2=list'}
host: 192.168.0.19:8081
version: HTTP/1.1
arguments: {}
_finish_time: None
query: 
path: /home
method: GET
remote_ip: 192.168.0.11

any ideas i have deleted everything sickbeard related and started with a fresh install, still i keep recieving this error, many thanks

**Comment by gimpacause** [comment]
hi guys i sorted it out, was still some files from old installation hideen, once deleted re installed and updated all working fine, thanks
