### ISSUE TITLE
subtitle download failing

### ISSUE THREAD

**Issue by pct00** [SiCKRAGETV/sickrage-issues#414]
Python Version: 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]
Operating System: Windows-7-6.1.7601-SP1
SR Version: BRANCH: (master) / 
COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8)

errors logged:
```python
2015-01-14 16:54:04 FINDSUBTITLES :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "C:\Users\Pedro\Desktop\SickRage-master\sickbeard\tv.py", line 1392, in downloadSubtitles
    multi=sickbeard.SUBTITLES_MULTI, cache_dir=sickbeard.CACHE_DIR)
  File "C:\Users\Pedro\Desktop\SickRage-master\lib\subliminal\api.py", line 95, in download_subtitles
    subtitles_by_video = list_subtitles(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "C:\Users\Pedro\Desktop\SickRage-master\lib\subliminal\api.py", line 54, in list_subtitles
    tasks = create_list_tasks(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "C:\Users\Pedro\Desktop\SickRage-master\lib\subliminal\core.py", line 58, in create_list_tasks
    scan_result.extend(scan(p, max_depth, scan_filter))
  File "C:\Users\Pedro\Desktop\SickRage-master\lib\subliminal\videos.py", line 240, in scan
    logger.debug(u'Scanning file %s with depth %d/%d' % (entry, depth, max_depth))
  File "C:\Python27\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 63: character maps to 

2015-01-14 15:53:48 FINDSUBTITLES :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "C:\Users\Pedro\Desktop\SickRage-master\sickbeard\tv.py", line 1392, in downloadSubtitles
    multi=sickbeard.SUBTITLES_MULTI, cache_dir=sickbeard.CACHE_DIR)
  File "C:\Users\Pedro\Desktop\SickRage-master\lib\subliminal\api.py", line 95, in download_subtitles
    subtitles_by_video = list_subtitles(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "C:\Users\Pedro\Desktop\SickRage-master\lib\subliminal\api.py", line 54, in list_subtitles
    tasks = create_list_tasks(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "C:\Users\Pedro\Desktop\SickRage-master\lib\subliminal\core.py", line 58, in create_list_tasks
    scan_result.extend(scan(p, max_depth, scan_filter))
  File "C:\Users\Pedro\Desktop\SickRage-master\lib\subliminal\videos.py", line 240, in scan
    logger.debug(u'Scanning file %s with depth %d/%d' % (entry, depth, max_depth))
  File "C:\Python27\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 71: character maps to 
```

**Comment by pct00** [comment]
forgot to mention, same error happens in develop branch

**Comment by Soulplayer** [comment]
I have the same issue:

2015-01-15 20:15:42 Thread-16 :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/tv.py", line 1392, in downloadSubtitles
    multi=sickbeard.SUBTITLES_MULTI, cache_dir=sickbeard.CACHE_DIR)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/api.py", line 111, in download_subtitles
    service_instance.terminate()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/services/opensubtitles.py", line 103, in terminate
    raise ServiceError(str(e))
ServiceError:

**Comment by markheloking** [comment]
@Soulplayer please use markdown in the future.

**Comment by markheloking** [comment]
I now have the same issue.

**Comment by fernandog** [comment]
closing this one because you already opened a 611
