### ISSUE TITLE
"'NoneType' object is not iterable" when clicking on 'General'

### ISSUE THREAD

**Issue by megapearl** [SiCKRAGETV/sickrage-issues#416]
Sickrage then give White Screen with black letters with following error screen:

[code]
Error

'NoneType' object is not iterable

Traceback

Traceback (most recent call last): 
File "/usr/local/share/sickbeard/tornado/web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback)) 
File "/usr/local/share/sickbeard/tornado/stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs) 
File "/usr/local/share/sickbeard/tornado/concurrent.py", line 226, in lambda future: callback(future.result())) 
File "/usr/local/share/sickbeard/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result() 
File "/usr/local/share/sickbeard/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "/usr/local/share/sickbeard/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "/usr/local/share/sickbeard/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "/usr/local/share/sickbeard/sickbeard/webserve.py", line 230, in async_call result = function(**kwargs) 
File "/usr/local/share/sickbeard/sickbeard/webserve.py", line 3390, in index return t.respond() 
File "/usr/local/share/sickbeard/cache/cheetah/_usr_local_share_sickbeard_gui_slick_interfaces_default_config_general_tmpl.py", line 952, in respond for cur_branch in VFN(VFFSL(SL,"sickbeard.versionCheckScheduler.action",True),"list_remote_branches",False)(): # generated from line 521, col 10 
TypeError: 'NoneType' object is not iterable 

Request Info

body: 
files: {}
protocol: https
connection: 
body_arguments: {}
uri: /tvshows/config/general/
query_arguments: {}
_start_time: 1421273643.66
headers: {'Accept-Language': 'nl-NL,nl;q=0.8,en-US;q=0.6,en;q=0.4', 'Accept-Encoding': 'gzip, deflate, sdch', 'X-Forwarded-Host': 'donald.flissinger.com', 'X-Forwarded-For': '10.0.0.15', 'Connection': 'Keep-Alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36', 'Dnt': '1', 'Host': 'donald.flissinger.com', 'Referer': 'https://donald.flissinger.com/tvshows/config/', 'Cookie': 'user="2|1:0|10:1418837882|4:user|44:ZT***changedsomeothecharactersinthisline***2NmY=|7829f61f0792384f1cc297fdef81c075eb682f88f75c4b0394d4af112e1"; _ga=GA1.2.144632222.1412075828; __utma=197364344.144632222.1412075828.1419444792.1419688481.14; __utmz=197364344.1412075828.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); snatched_view2=list; soon_view2=thumbs; suggestions_charts_menu_selected=suggestions; late_view2=list; advanced_toggle_checked=1; wanted_view2=mass_edit; manage_view2=details', 'X-Forwarded-Server': 'donald.flissinger.com'}
host: donald.flissinger.com
version: HTTP/1.1
arguments: {}
_finish_time: None
query: 
path: /tvshows/config/general/
_cookies: Set-Cookie: __utma=197364344.144632222.1412075828.1419444792.1419688481.14 Set-Cookie: __utmz=197364344.1412075828.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none) Set-Cookie: _ga=GA1.2.144632222.1412075828 Set-Cookie: advanced_toggle_checked=1 Set-Cookie: late_view2=list Set-Cookie: manage_view2=details Set-Cookie: snatched_view2=list Set-Cookie: soon_view2=thumbs Set-Cookie: suggestions_charts_menu_selected=suggestions Set-Cookie: user="2|1:0|10:1418837882|4:user|4***changedsomeothecharactersinthisline***Y0MGE2NmY=|7829f61f0792384f1cc297fdef81c075eb89154682f88f75c4b0394d4af112e1" Set-Cookie: wanted_view2=mass_edit
method: GET
remote_ip: 10.0.0.1
[/code]

Already tried to delete cache.db and didn't make any difference...
Using latest sickrage version via git: BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8) 

Running FreeBSD 10.1-RELEASE-p3
And python27-2.7.9

What could be wrong?

Regards,
Donald.

**Comment by markheloking** [comment]
@megapearl please use markdown in the future.

**Comment by markheloking** [comment]
Duplicate of https://github.com/SiCKRAGETV/sickrage-issues/issues/307.
