### ISSUE TITLE
Spcial char/Upgrade issue

### ISSUE THREAD

**Issue by madpuma13** [SiCKRAGETV/sickrage-issues#427]
So I am new to Sickrage and have set everything up and was having problems with Sickrage returning results for my searches (backlog and manual). In an effort to see if changing the fork would help, I changed to the develop over master.

In the process of upgrading it gives me this:
```python
2015-01-15 19:56:14 ERROR Thread-42 :: Error while trying to update: ascii : /usr/pbi/sickrage-amd64/share/sickrage/SickRage/sr-update/SiCKRAGETV-SickRage-0bb8446/gui/slick/images/network/télé-québec.png : error 112 : error 113 : ordinal not in range(128)

2015-01-15 19:56:14 INFO Thread-42 :: Extracting file /usr/pbi/sickrage-amd64/share/sickrage/SickRage/sr-update/sr-update.tar

2015-01-15 19:55:42 INFO Thread-42 :: Downloading update from 'http://github.com/SiCKRAGETV/SickRage/tarball/develop'

2015-01-15 19:55:42 INFO Thread-42 :: Creating update folder /usr/pbi/sickrage-amd64/share/sickrage/SickRage/sr-update before extracting

2015-01-15 19:55:42 INFO Thread-42 :: Clearing out update folder /usr/pbi/sickrage-amd64/share/sickrage/SickRage/sr-update
```
Before extracting after researching it as much as I could there are two things that I have found out. 1. It is a python problem with unclear directions of how to go about fixing it. (ive updated a number of scripts to run as utf8 but no go) 2. The other thing I mostly sawe regarding this issue was to upgrade sickrage to the develop fork which I cant do.

Any ideas?

SR Version: BRANCH: (develop) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8)

**Comment by fernandog** [comment]
@madpuma13 follow the guidelines:
https://github.com/SiCKRAGETV/sickrage-issues

**Comment by madpuma13** [comment]
Sorry github's layout is not very intuitive. 

SR Version: BRANCH: (develop) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8)
Freenas 9.3 / Python 2.7.8
Clicking upgrade to letest develop edition
Error popped up preveting upgrade from happening
the upgrade to happen
http://pastebin.com/uASqQwQ1

**Comment by fernandog** [comment]
@madpuma13 FULL logs please

**Comment by MarcoV1980** [comment]
2015-01-21 22:32:32 DEBUG    Thread-112 :: cur_commit = 401cb666016e45b42fe675bafdf7908ad6c2b9bb, newest_commit = 91cb8d885ca278e5829ed53d856d578c8ee8cbe0, num_commits_behind = 83
2015-01-21 22:32:32 DEBUG    Thread-112 :: Branch checkout: master->develop
2015-01-21 22:32:32 INFO     Thread-112 :: Clearing out update folder /storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/sr-update before extracting
2015-01-21 22:32:32 ERROR    Thread-112 :: Error while trying to update: ascii : /storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/sr-update/SiCKRAGETV-SickRage-91cb8d8/gui/slick/images/network/tÃ©lÃ©-quÃ©bec.png : error 134 : error 135 : ordinal not in range(128)
Traceback (most recent call last):
  File "/storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/sickbeard/versionChecker.py", line 561, in update
    shutil.rmtree(sr_update_dir)
  File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.0/Python-2.7.3/.install_pkg/usr/lib/python2.7/shutil.py", line 245, in rmtree
  File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.0/Python-2.7.3/.install_pkg/usr/lib/python2.7/shutil.py", line 245, in rmtree
  File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.0/Python-2.7.3/.install_pkg/usr/lib/python2.7/shutil.py", line 245, in rmtree
  File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.0/Python-2.7.3/.install_pkg/usr/lib/python2.7/shutil.py", line 245, in rmtree
  File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.0/Python-2.7.3/.install_pkg/usr/lib/python2.7/shutil.py", line 245, in rmtree
  File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.0/Python-2.7.3/.install_pkg/usr/lib/python2.7/shutil.py", line 241, in rmtree
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 134: ordinal not in range(128)
2015-01-21 22:32:32 DEBUG    Thread-112 :: Traceback: Traceback (most recent call last):
  File "/storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/sickbeard/versionChecker.py", line 561, in update
    shutil.rmtree(sr_update_dir)
  File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.0/Python-2.7.3/.install_pkg/usr/lib/python2.7/shutil.py", line 245, in rmtree
  File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.0/Python-2.7.3/.install_pkg/usr/lib/python2.7/shutil.py", line 245, in rmtree
  File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.0/Python-2.7.3/.install_pkg/usr/lib/python2.7/shutil.py", line 245, in rmtree
  File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.0/Python-2.7.3/.install_pkg/usr/lib/python2.7/shutil.py", line 245, in rmtree
  File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.0/Python-2.7.3/.install_pkg/usr/lib/python2.7/shutil.py", line 245, in rmtree
  File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.0/Python-2.7.3/.install_pkg/usr/lib/python2.7/shutil.py", line 241, in rmtree
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 134: ordinal not in range(128)

**Comment by MarcoV1980** [comment]
Oeps, but that's the whole part for the update to fail.

Seems it just can't read/ write the file télé-québec.png

**Comment by awagnon** [comment]
BRANCH: (develop) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb) 
Running on OpenElec 5.0 x86_64. Python 2.7.3. 
Any attempt to update results in the same error as above. 
I check out developer branch and expect it to download and install the updates. 
Error while trying to update: ascii : /storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/sr-update/SiCKRAGETV-SickRage-91cb8d8/gui/slick/images/network/télé-québec.png : error 134 : error 135 : ordinal not in range(128)

Update fails, here is the log: http://pastebin.com/eGwUAxWs

**Comment by abeloin** [comment]
Check your language locale and make sure it use UTF-8 for the user running sickrage.
```
$ locale
LANG=fr_CA.utf8
LC_CTYPE="fr_CA.utf8"
LC_NUMERIC="fr_CA.utf8"
LC_TIME="fr_CA.utf8"
LC_COLLATE="fr_CA.utf8"
LC_MONETARY="fr_CA.utf8"
LC_MESSAGES="fr_CA.utf8"
LC_PAPER="fr_CA.utf8"
LC_NAME="fr_CA.utf8"
LC_ADDRESS="fr_CA.utf8"
LC_TELEPHONE="fr_CA.utf8"
LC_MEASUREMENT="fr_CA.utf8"
LC_IDENTIFICATION="fr_CA.utf8"
LC_ALL=
```

**Comment by MarcoV1980** [comment]
OpenELEC (official) Version: 5.0.0
OpenELEC:~ # locale
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
OpenELEC:~ #



Is there a special reason that filename needs to use those characters?

**Comment by abeloin** [comment]
@MarcoV1980 Sickrage look for the logo image by appending the networkname + .png

**Comment by MarcoV1980** [comment]
I see, but maybe make it an option?

I'd reckon this network mostly speaks to the Canadians and French perhaps,
while the rest doesn't actually need it that bad.
I am (and i saw some other with me in this thread) using openelec, and they
don't compile the OS with UTF8 unfortunately. Perhaps there are some hacks
available, but for most users this would be too hard to do.

**Comment by abeloin** [comment]
@MarcoV1980 What's the result of:
```
locale -a
```

**Comment by MarcoV1980** [comment]
> c
> P0SIX

That's the only ones they have. Shame though, didn't think it would hurt implementing UTF8 also.

**Comment by abeloin** [comment]
I think the reason was space issue, see https://github.com/OpenELEC/OpenELEC.tv/issues/364

**Comment by abeloin** [comment]
@MarcoV1980 The pull request should fix the issue when it will be merge in develop.

**Comment by MarcoV1980** [comment]
Awesome, thanks a lot, will check back when it's merged into dev!

**Comment by fernandog** [comment]
@madpuma13 develop updated. please test and report back

**Comment by awagnon** [comment]
It solved the issue for me. 
Thank you!!!!
