### ISSUE TITLE
Boxcar 2 - Test Failing

### ISSUE THREAD

**Issue by rubberbird** [SiCKRAGETV/sickrage-issues#430]
SR Version: 	BRANCH: (master) / COMMIT: (33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8)
Host: Synology NAS

Error Message:

2015-01-17 18:09:21 Thread-39 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
TypeError: testBoxcar2() got an unexpected keyword argument 'accessToken'

2015-01-17 18:08:17 Thread-26 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
TypeError: testBoxcar2() got an unexpected keyword argument 'accessToken'

Issue:

Looks like parse of accessToken object is not valid.

**Comment by ThePieMan** [comment]
Too funny, I just signed in to report this issue as well.

Appears with the proper information that the notifications themselves work just fine, but the 'Test Boxcar2' button is failing.

**Comment by rubberbird** [comment]
@ThePieMan Great minds think alike. Yeah, I noticed afterwards that notification are working fine, just the test box fails.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/311
