### ISSUE TITLE
No JSON object could be decoded - TorrentDay Search - API Change?

### ISSUE THREAD

**Issue by Trever123** [SiCKRAGETV/sickrage-issues#435]
As i am having issues with a previous issue to do with TorrentDay cookie not being found (issue 291). I have loaded a virtual machine up and started from scratch with a fresh install of sickrage to see if it is a problem on my end (if so ill do a fresh install). 

I am now getting the following error - No JSON object could be decoded.

The logs are here: http://pastebin.com/GGqzAg2d

I have done some investigation and when i follow the link mentioned in the logs, it says that "Hotlinking directly to proxied pages is not permitted." but provides a link on the page to the url we are trying to go to anyway "[Reload http://www.td.af/V3/API/API.php]". If i follow this link i get to the following page:

```
File Not Found
No page exists at your destination address,

http://www.torrentday.com /V3/API/API.php

but the TorrentDay home page should help you to find what you need.
Return to TorrentDay Home Page
```

Is there a chance that the page has changed or there is a new API?

Sickrage info:
BRANCH: (develop) / COMMIT: (ce997c79fe83e0899450f01df2dfc38608935f4c)

**Comment by fernandog** [comment]
@Trever123 are you using proxy for provider? (general config page)
my TD is working.

```
2015-01-19 05:39:22 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [TorrentDay] :: Attempting to add item to cache: ****.S01E01.HDTV.x264-LOL
2015-01-19 05:39:22 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [TorrentDay] :: Using ALL regexes
2015-01-19 05:39:22 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [TorrentDay] :: Using cached parse result for: ****.S01E01.HDTV.x264-LOL
2015-01-19 05:39:22 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [TorrentDay] :: Added RSS item: [****.S01E01.HDTV.x264-LOL] to cache: [torrentday]
```

**Comment by Trever123** [comment]
@fernadog I am having to use the proxies as I am in the UK and torrent day is now blocked here (the https site torrentday.eu isn't blocked but the original td.af and torrentday.com are). I have tried all 4 proxies available in the settings and get the same results as posted for each

**Comment by fernandog** [comment]
@Trever123 

stop your SR
edit /home/pi/SickRage/sickbeard/providers/torrentday.py

from:
```
        self.urls = {'base_url': 'http://www.td.af',
                'login': 'http://www.td.af/torrents/',
                'search': 'http://www.td.af/V3/API/API.php',
                'download': 'http://www.td.af/download.php/%s/%s'
        }
```

to:
from:
```
        self.urls = {'base_url': 'http://www.torrentday.eu',
                'login': 'http://www.torrentday.eu/torrents/',
                'search': 'http://www.torrentday.eu/V3/API/API.php',
                'download': 'http://www.torrentday.eu/download.php/%s/%s'
        }
```

restart SR
you will lose this change if you update

**Comment by Trever123** [comment]
@fernandog thanks for this, I'll give it a go. Will it make a difference that the new url is https instead of just http? (not sure if extra code is needed for https) 

Will this change me made to the master and develop branch or shall I disable updates?

If there a fix planned to make this work through the proxy in case the new url gets blocked?

**Comment by fernandog** [comment]
@Trever123 you can test it and let me know!

**Comment by Trever123** [comment]
@fernandog So i have tested it on my main setup and no longer get my original error of 
```
2015-01-19 12:24:59 SEARCHQUEUE-BACKLOG-79556 :: [TorrentDay] :: Unable to obtain cookie for TorrentDay
```

But i am still getting the error
```
2015-01-19 12:28:50 SEARCHQUEUE-BACKLOG-79556 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded
```

For this i have changed the code as suggested and also disabled the proxy i had. Also when checking the logs with debug set to 1, i am still seeing the same error. Just about to check the 2nd instance i have in a virtual machine to make sure its not to do with my main setup.

**Comment by fernandog** [comment]
@Trever123 I got this error too using torrentday.eu BUT no error using td.af

```
2015-01-19 11:09:26 INFO     SEARCHQUEUE-MANUAL-269159 :: Unable to find a download for: [**** - 1x01 ******]
2015-01-19 11:09:26 DEBUG    SEARCHQUEUE-MANUAL-269159 :: formatting pattern: %SN - %Sx%0E - %EN -> **** - 1x01 ******
2015-01-19 11:09:26 DEBUG    SEARCHQUEUE-MANUAL-269159 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
2015-01-19 11:09:26 DEBUG    SEARCHQUEUE-MANUAL-269159 :: formatting pattern: %SN - %Sx%0E - %EN -> **** - 1x01 ******
2015-01-19 11:09:26 DEBUG    SEARCHQUEUE-MANUAL-269159 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
2015-01-19 11:09:25 DEBUG    SEARCHQUEUE-MANUAL-269159 :: Search string: ****** S01E01 
2015-01-19 11:09:25 INFO     SEARCHQUEUE-MANUAL-269159 :: Performing episode search for ****
2015-01-19 11:09:25 INFO     SEARCHQUEUE-MANUAL-269159 :: FALLBACK EPISODE SEARCH INITIATED ...
2015-01-19 11:09:24 DEBUG    SEARCHQUEUE-MANUAL-269159 :: [TorrentDay] :: Search string: ****** S01E01 
2015-01-19 11:09:22 INFO     SEARCHQUEUE-MANUAL-269159 :: [TorrentDay] :: Performing season pack search for ****
2015-01-19 11:09:22 DEBUG    SEARCHQUEUE-MANUAL-269159 :: [TorrentDay] :: Last update was too soon, using old cache: today()-2015-01-19 11:01:53<0:10:0
```

Don't know what is wrong. We only changed the URL

**Comment by fernandog** [comment]
@Trever123 

can you try this file:

https://raw.githubusercontent.com/SickGear/SickGear/master/sickbeard/providers/torrentday.py

**Comment by Trever123** [comment]
@fernandog Think i need some other files as well, i get this error:

```
parallels@ubuntu:~/Downloads/SickRage-master$ Traceback (most recent call last):
  File "SickBeard.py", line 58, in <module>
    import sickbeard
  File "/home/parallels/Downloads/SickRage-master/sickbeard/__init__.py", line 35, in <module>
    from providers import ezrss, tvtorrents, btn, newznab, womble, thepiratebay, torrentleech, kat, iptorrents, \
  File "/home/parallels/Downloads/SickRage-master/sickbeard/providers/torrentday.py", line 286, in <module>
    provider = TorrentDayProvider()
  File "/home/parallels/Downloads/SickRage-master/sickbeard/providers/torrentday.py", line 62, in __init__
    self.url = self.urls['base_url']
KeyError: 'base_url'
```

**Comment by fernandog** [comment]
let's wait @echel0n 

until then, try using other proxy servers

**Comment by Trever123** [comment]
Ok thanks, i have tried the 4 provided, i will try to find my own and add that to the code instead

**Comment by maZuFC** [comment]
hey everybody... having this exact problem...

@Trever123 were you able to resolve it?

ive tried using a vpn connected to another country but i still get the same error...
also tried entering a proxy site but that didnt work.

2015-01-30 21:36:18 SEARCHQUEUE-MANUAL-75978 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded

**Comment by fernandog** [comment]
@maZuFC  @Trever123 
try this:
https://github.com/SiCKRAGETV/SickRage/pull/1207/files

**Comment by maZuFC** [comment]
@fernandog  thanks for the code, but it still doesnt work..
i get the following... :/

will try with a vpn now...

2015-01-30 21:47:06 SEARCHQUEUE-MANUAL-75978 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded
2015-01-30 21:47:06 SEARCHQUEUE-MANUAL-75978 :: No NZB/Torrent providers found or enabled in the sickrage config for backlog searches. Please check your settings.
2015-01-30 21:46:57 SEARCHQUEUE-DAILY-SEARCH :: [TorrentDay] :: Unable to obtain cookie for TorrentDay

**Comment by maZuFC** [comment]
i should add ive also tried having the url as https://www.torrentday.com and that didnt work either.
can definitely access the site using that..

**Comment by maZuFC** [comment]
well changing vpns didnt work either... im stumped with this one...

**Comment by Trever123** [comment]
I have tried other proxies and that has also not worked. This issue needs to be reopened as it is not fixed.

**Comment by abeloin** [comment]
@Trever123  https://torrentday.eu doesn't work for you?

**Comment by maZuFC** [comment]
i agree that the issue has to be reopened... but the question is..
is it a sickrage or torrent day or JSON issue...  or is it because we are based in the UK?

can anybody outside the UK confirm that torrentday is working?

correct me if im wrong but JSON is javascript?
maybe a java update is needed...?

**Comment by abeloin** [comment]
@maZuFC Works fine here

**Comment by maZuFC** [comment]
@abeloin thanks, just to confirm torrentday is working for with sickrage.. searching / downloading..

not that you can access the web page..

**Comment by abeloin** [comment]
@maZuFC Yes using https://torrentday.eu and "Access provider via proxy" unchecked
```
2015-01-30 18:15:37 INFO     SEARCHQUEUE-MANUAL-269618 :: Downloading Undateable.2014.S01E13.720p.HDTV.X264-DIMENSION from TorrentDay
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: Checking if we should keep searching after we've found Undateable.2014.S01E13.720p.HDTV.X264-DIMENSION
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: Picked Undateable.2014.S01E13.720p.HDTV.X264-DIMENSION as the best
2015-01-30 18:15:37 INFO     SEARCHQUEUE-MANUAL-269618 :: Quality of Undateable.2014.S01E13.720p.HDTV.X264-DIMENSION is HD TV
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: Picking the best result out of [u'Undateable.2014.S01E13.720p.HDTV.X264-DIMENSION']
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: The highest quality of any match is HD TV
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Ignoring result Undateable.2014.S01E13.HDTV.x264-LOL because we don't want an episode that is SD TV
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Don't want this quality, ignoring found episode
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: any,best = [4, 32, 128] [] and found 1
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Checking if found episode 1x13 is wanted at quality SD TV
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Parsed Undateable.2014.S01E13.HDTV.x264-LOL into Undateable 2014 - S1E13 [ANIME VER: -1] [GROUP: LOL] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Converted parsed result Undateable.2014.S01E13.HDTV.x264-LOL into Undateable 2014 - S1E13 [ANIME VER: -1] [GROUP: LOL] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Using ALL regexes
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Ignoring result Undateable.2014.S01E13.HDTV.XviD-AFG because we don't want an episode that is SD TV
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Don't want this quality, ignoring found episode
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: any,best = [4, 32, 128] [] and found 1
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Checking if found episode 1x13 is wanted at quality SD TV
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Parsed Undateable.2014.S01E13.HDTV.XviD-AFG into Undateable 2014 - S1E13 [ANIME VER: -1] [GROUP: AFG] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Converted parsed result Undateable.2014.S01E13.HDTV.XviD-AFG into Undateable 2014 - S1E13 [ANIME VER: -1] [GROUP: AFG] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Using ALL regexes
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Ignoring result Undateable.2014.S01E13.480p.HDTV.x264-mSD because we don't want an episode that is SD TV
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Don't want this quality, ignoring found episode
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: any,best = [4, 32, 128] [] and found 1
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Checking if found episode 1x13 is wanted at quality SD TV
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Parsed Undateable.2014.S01E13.480p.HDTV.x264-mSD into Undateable 2014 - S1E13 [ANIME VER: -1] [GROUP: mSD] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Converted parsed result Undateable.2014.S01E13.480p.HDTV.x264-mSD into Undateable 2014 - S1E13 [ANIME VER: -1] [GROUP: mSD] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Using ALL regexes
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Single episode result.
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Found result Undateable.2014.S01E13.720p.HDTV.X264-DIMENSION at http://www.td.af/download.php/879592/Undateable.2014.S01E13.720p.HDTV.X264-DIMENSION.torrent
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Existing episode status is wanted/unaired/skipped, getting found episode
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Existing episode status: 5 (Skipped)
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: any,best = [4, 32, 128] [] and found 4
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Checking if found episode 1x13 is wanted at quality HD TV
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Parsed Undateable.2014.S01E13.720p.HDTV.X264-DIMENSION into Undateable 2014 - S1E13 [ANIME VER: -1] [GROUP: DIMENSION] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Converted parsed result Undateable.2014.S01E13.720p.HDTV.X264-DIMENSION into Undateable 2014 - S1E13 [ANIME VER: -1] [GROUP: DIMENSION] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-01-30 18:15:37 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Using ALL regexes
2015-01-30 18:15:36 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Search string: Undateable.2014 S01E13 
2015-01-30 18:15:36 INFO     SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Performing episode search for Undateable (2014)
2015-01-30 18:15:36 DEBUG    SEARCHQUEUE-MANUAL-269618 :: Undateable (2014) is not an anime, skiping
2015-01-30 18:15:36 DEBUG    SEARCHQUEUE-MANUAL-269618 :: [TorrentDay] :: Last update was too soon, using old cache: today()-2015-01-30 18:14:41<0:10:00
```

**Comment by maZuFC** [comment]
@abeloin thanks for confirming

out of curiosity what country are you in?

**Comment by abeloin** [comment]
Canada.
Which version of python do you have?

**Comment by fernandog** [comment]
Maybe torrentday.eu got blocked too.
can you access from browser?

**Comment by maZuFC** [comment]
im gonna try a canadian vpn for kicks... see what happens.

Python version 2.7.9

**Comment by maZuFC** [comment]
@fernandog yes i can, ive tried all variations of the link and they all work

**Comment by abeloin** [comment]
There's an issue with python 2.7.9

**Comment by maZuFC** [comment]
oh... which version should i try?

**Comment by abeloin** [comment]
@maZuFC Sorry it doesn't apply in this case. Does https://torrentday.eu work in your browser?

You could try adding ```logging.getLogger("requests.packages.urllib3"),``` to sickbeard/logger.py around line 73, it will add the web requests and status to the log file.

**Comment by maZuFC** [comment]
@abeloin yes, that link works

i will add that code and see what happens.

i just noticed this... something about not having the C version of NameMapper... is this important?

C:\Python27\lib\site-packages\cheetah-2.4.4-py2.7.egg\Cheetah\Compiler.py:1509:
UserWarning:
You don't have the C version of NameMapper installed! I'm disabling Cheetah's us
eStackFrames option as it is painfully slow with the Python version of NameMappe
r. You should get a copy of Cheetah with the compiled C version of NameMapper.
  "\nYou don't have the C version of NameMapper installed! "

**Comment by fernandog** [comment]
No

**Comment by abeloin** [comment]
@maZuFC And you are using these urls in torrentday.py?
```
 self.urls = {'base_url': 'https://torrentday.eu',
 'login': 'https://torrentday.eu/torrents/',
 'search': 'https://torrentday.eu/V3/API/API.php',
 'download': 'https://torrentday.eu/download.php/%s/%s'
```

**Comment by maZuFC** [comment]
ok,

i installed version 2.7.8 (64bit) of python.


added that logging code you mentioned above and it didnt show anything different in the logs.

**Comment by maZuFC** [comment]
@abeloin 

yes i am.

this is what i have

self.cache = TorrentDayCache(self)

        self.urls = {'base_url': 'https://torrentday.eu/',
                'login': 'https://torrentday.eu/torrents/',
                'search': 'https://torrentday.eu/V3/API/API.php',
                'download': 'https://torrentday.eu/download.php/%s/%s'
        }

**Comment by abeloin** [comment]
You should see something like this in your log:
```
2015-01-30 18:53:12 DEBUG    SEARCHQUEUE-BACKLOG-72454 :: [TorrentDay] :: Search string: Detective.Conan 765
2015-01-30 18:53:12 INFO     Starting new HTTPS connection (1): torrentday.eu
2015-01-30 18:53:12 INFO     Starting new HTTPS connection (1): torrentday.eu
2015-01-30 18:53:13 DEBUG    "POST /V3/API/API.php HTTP/1.1" 200 None
2015-01-30 18:53:13 DEBUG    "POST /V3/API/API.php HTTP/1.1" 200 None
2015-01-30 18:53:13 DEBUG    SEARCHQUEUE-BACKLOG-72454 :: [TorrentDay] :: Search string: Meitantei.Conan 765
2015-01-30 18:53:13 INFO     Starting new HTTPS connection (1): torrentday.eu
2015-01-30 18:53:13 INFO     Starting new HTTPS connection (1): torrentday.eu
2015-01-30 18:53:13 DEBUG    "POST /V3/API/API.php HTTP/1.1" 200 None
2015-01-30 18:53:13 DEBUG    "POST /V3/API/API.php HTTP/1.1" 200 None
```

**Comment by maZuFC** [comment]
nope, doesnt show any of that... just the same 3 errors.
i restarted sickrage again just incase... and this is what i got
i can confirm the logging.logger code is in the logger.py file

2015-01-30 23:55:56 SEARCHQUEUE-MANUAL-75978 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded
2015-01-30 23:55:56 SEARCHQUEUE-MANUAL-75978 :: No NZB/Torrent providers found or enabled in the sickrage config for backlog searches. Please check your settings.
2015-01-30 23:55:50 SEARCHQUEUE-DAILY-SEARCH :: [TorrentDay] :: Unable to obtain cookie for TorrentDay

**Comment by maZuFC** [comment]
bah... if i knew how to troubleshoot python code and JSON error codes might be able to determine what its actually doing...

can you guys recommend which python version and cheetah version i should be using?


i think im going to blow away my win8.1 VM and start from scratch (will take snapshot next time!)

**Comment by abeloin** [comment]
@maZuFC Can you try this python file https://gist.github.com/abeloin/46c78d4a47f7ccdeb54f and give me the results?

**Comment by maZuFC** [comment]
im confused.. where is that code meant to go?

is that meant to replace my torrentday.py ?

**Comment by abeloin** [comment]
No, create a new file named test.py, paste the text inside it, remember the location. Then open a command line and go to python bin path(python.exe) and run the command:
```
python.exe c:\path\to\test.py
```

**Comment by maZuFC** [comment]
oh..

i got this

C:\Python27>python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import requests
ImportError: No module named requests

**Comment by abeloin** [comment]
Requests lib is missing. Download this file https://bootstrap.pypa.io/get-pip.py then:
```
python.exe c:\path\to\get-pip.py
```
When done you should have pip.exe in c:\Python27\Scripts. From that folder, run:
```
pip.exe install requests
```
then run python test.py again

**Comment by maZuFC** [comment]
ok i got this

C:\Python27>python test.py
[]
{'content-encoding': 'gzip', 'transfer-encoding': 'chunked', 'set-cookie': '__cf
duid=d1a933889e792eb1881659322e643ef341422664954; expires=Sun, 31-Jan-16 00:42:3
4 GMT; path=/; domain=.torrentday.eu; HttpOnly', 'server': 'cloudflare-nginx', '
connection': 'keep-alive', 'date': 'Sat, 31 Jan 2015 00:42:34 GMT', 'cf-ray': '1
b11debb2f4502fd-LHR', 'content-type': 'text/html; charset=utf-8'}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.or
g/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xht
ml"><head><link rel="stylesheet" href="/CSS/torrentday-pager.css?z" type="text/c
ss"><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title>
Torrentday :: Login</title><style>body{background:#526169;height: 100%;font-size
:9pt;margin: 0;}a{color:#000!important}.sizer{width:220px;}img.reload{width:223p
x;}</style></head><body><div align="center" style="position: relative;margin-top
: 2%"><img src="/pic/loginF.png" /><br /><form method="post"><table border="0" c
ellpadding="5"><tr><td colspan="2" align="center" class="navigation"><a href="/t
orrents/">Login</a> - <a href="/signup.php">Sign up</a><br><a href="/recover.php
">Forgot your password?</a></td></tr><tr><td colspan="2"><div align="center" sty
le="font-weight:bold; color:red"> </div></td></tr><tr><td class=rowhead>Username
:</td><td align=left><input class="sizer" type="text" name="username" /></td></t
r><tr><td class=rowhead>Password:</td><td align=left><input class="sizer" type="
password" name="password" /></td></tr><tr><td colspan="2" align="center"><input
type="image" src="/pic/login.png" name="submit"></td></tr></table></form><p>Don'
t have an account? <a href="/signup.php">Sign up</a> right now!<br /><br />If yo
u need help please contact us at: <b><a class="__cf_email__" href="/cdn-cgi/l/em
ail-protection" data-cfemail="fb8f9489899e958f9f9a82939e978bbb9c969a9297d5989496
">[email&#160;protected]</a><script cf-hash='f9e31' type="text/javascript">
/* <![CDATA[ */!function(){try{var t="currentScript"in document?document.current
Script:function(){for(var t=document.getElementsByTagName("script"),e=t.length;e
--;)if(t[e].getAttribute("cf-hash"))return t[e]}();if(t&&t.previousSibling){var
e,r,n,i,c=t.previousSibling,a=c.getAttribute("data-cfemail");if(a){for(e="",r=pa
rseInt(a.substr(0,2),16),n=2;a.length-n;n+=2)i=parseInt(a.substr(n,2),16)^r,e+=S
tring.fromCharCode(i);e=document.createTextNode(e),c.parentNode.replaceChild(e,c
)}}}catch(u){}}();/* ]]> */</script></b></p></div></body></html>

**Comment by abeloin** [comment]
Can you edit your post and use the markdown for code, see https://guides.github.com/features/mastering-markdown/

Did you change the login and password in the file to your torrentday credential?

**Comment by maZuFC** [comment]
yeah im trying to figure out which syntax to use to mark it down..

yep i changed username and password in the code you sent.

**Comment by maZuFC** [comment]
sorry i stuffed it up.. ok i got a response 302

C:\Python27>python test.py
[<Response [302]>]
{'content-encoding': 'gzip', 'x-powered-by': 'PHP/5.4.36-0+deb7u3', 'transfer-en
coding': 'chunked', 'expires': 'Sat, 31 Jan 2015 00:52:10 GMT', 'server': 'cloud
flare-nginx', 'connection': 'keep-alive', 'cache-control': 'max-age=0', 'date':
'Sat, 31 Jan 2015 00:52:10 GMT', 'cf-ray': '1b11eccff2551389-LHR', 'content-type
': 'text/html'}
<meta http-equiv="refresh" content="3;URL=/browse.php">
<p><br>
  </p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p><br>
  <br><br>
</p>
<div align="center">
  <p>Logging you in securely...

  </p>
  <p><img src="pic/login.gif" width="186" height="42" alt=""></p>
  <p>If this page appears for more than 5 seconds, <a href="/browse.php">click h
ere</a> to reload.</p>
</div>

C:\Python27>

**Comment by abeloin** [comment]
Ok so you are successfully authenticated

For the markdown, it's the ` repeated 3 times at the beginning and at the end of the text.

**Comment by maZuFC** [comment]
```test```

**Comment by abeloin** [comment]
Is "Access provider via proxy" is activated for TorrentDay?

**Comment by maZuFC** [comment]
ive been turning it on / off to see if its making any difference
it was ON, but i just turned it off

**Comment by maZuFC** [comment]
holy crap i dont know what just happened but it just worked!

``` 2015-01-31 01:03:37 INFO     SEARCHQUEUE-MANUAL-110381 :: Saved magnet link to Archer.2009.S06E04.720p.HDTV.x264-KILLERS.[NO.RAR].torrent
2015-01-31 01:03:37 INFO     SEARCHQUEUE-MANUAL-110381 :: Downloading a result from TorrentDay at https://torrentday.eu/download.php/1038967/Archer.2009.S06E04.720p.HDTV.x264-KILLERS%20%5BNO%20RAR%5D.torrent
AA2015-01-31 01:03:37 DEBUG    "GET /download.php/1038967/Archer.2009.S06E04.720p.HDTV.x264-KILLERS%20%5BNO%20RAR%5D.torrent HTTP/1.1" 200 None
AA2015-01-31 01:03:37 DEBUG    "GET /download.php/1038967/Archer.2009.S06E04.720p.HDTV.x264-KILLERS%20%5BNO%20RAR%5D.torrent HTTP/1.1" 200 None
AA2015-01-31 01:03:37 INFO     Starting new HTTPS connection (1): torrentday.eu
AA2015-01-31 01:03:37 INFO     Starting new HTTPS connection (1): torrentday.eu
2015-01-31 01:03:37 INFO     SEARCHQUEUE-MANUAL-110381 :: Downloading Archer.2009.S06E04.720p.HDTV.x264-KILLERS.[NO.RAR] from TorrentDay
2015-01-31 01:03:37 INFO     SEARCHQUEUE-MANUAL-110381 :: Quality of Archer.2009.S06E04.720p.HDTV.x264-KILLERS is HD TV
2015-01-31 01:03:37 INFO     SEARCHQUEUE-MANUAL-110381 :: Quality of Archer.2009.S06E04.720p.HDTV.x264-KILLERS.[NO.RAR] is HD TV
2015-01-31 01:03:37 INFO     SEARCHQUEUE-MANUAL-110381 :: Quality of Archer.2009.S06E04.720p.HDTV.x264-KILLERS is HD TV
2015-01-31 01:03:37 INFO     SEARCHQUEUE-MANUAL-110381 :: Quality of Archer.2009.S06E04.720p.HDTV.x264-KILLERS.[NO.RAR] is HD TV
2015-01-31 01:03:37 INFO     SEARCHQUEUE-MANUAL-110381 :: [TorrentDay] :: Performing episode search for Archer (2009) ```

**Comment by maZuFC** [comment]
i dont understand why its suddenly working...

**Comment by abeloin** [comment]
Taking a wild guess... Maybe when you changed the url you forgot to restart sickrage? Then when you downgraded to 2.7.8 you restarted but "Access provider via proxy" was activated.

**Comment by maZuFC** [comment]
not sure, ive been restarting sickrage pretty much everytime ive down a change..
and ive restarted the vm too... 

maybe that test.py we did actually logged into the site... is it possible that sickrage was failing to log in hence why i was getting the errors?
that test.py may have kick started it?

very strange... well im glad its working.. pity its on my VM!
i now have to redo all of this on my mediacentre that ill be building hopefully over the weekend..

at least ill be able to reference this thread and everything we did!


really appreciate your help with this... not sure if we learn anything from this but i think the solution is in here somewhere!

thanks again for everything, ill post back in a few days if i have any issues with my mediacentre
... hopefully will go smoothly!

**Comment by abeloin** [comment]
No, the test.py didn't do that as the login info is lost when the script stop.

On your mediacentre, use python 2.7.8 as there are some breaking changes in 2.7.9.

**Comment by fernandog** [comment]
Dns/cache problems. Not first time I saw it.

**Comment by maZuFC** [comment]
ok will do, 

thanks again

right i gotta get to bed.. .early wake up call tomorrow!

**Comment by maZuFC** [comment]
@fernandog maybe.. cache.. i did try 3 different browsers.. but i did not cleardns, will remember for next time to do this if i have issues

cheers

**Comment by Trever123** [comment]
@maZuFC when you find out what made it work can you let me know so I can apply the same changes here

**Comment by fernandog** [comment]
@Trever123 did you try this ?
https://github.com/SiCKRAGETV/SickRage/pull/1207/files

stop SR, edit the file, save the file. reboot your entire system: router/modem/nas/etc...

**Comment by Trever123** [comment]
@fernandog I tried that previously but didn't restart my entire system or router. I was thinking maybe it was something to do with the python version or the install of python requests. I'll try them all later. Just wondered if @maZuFC could streamline the process

**Comment by maZuFC** [comment]
@Trever123 ill do what i can and take notes of what i did, versions etc..

will give it a shot hopefully tomorrow on my media  centre...

**Comment by abeloin** [comment]
@Trever123 Try the following, which is essentially what was done on maZuFC's system:
* Make sure you're using the url provided by this [commit](https://github.com/SiCKRAGETV/SickRage/pull/1207/files).
* Uncheck "Access provider via proxy" in the TorrentDay config options.
* Restart sickrage.

As for installing Requests, it's only needed for testing with the torrentday test script I've asked maZuFC to try.

**Comment by maZuFC** [comment]
@Trever123 @abeloin @fernandog 

ok guys, so i did the sickrage install on my media centre and it worked straight away.. snatched torrents without any problems and started downloading.. just have to configure it for processing and where to put downloaded episodes etc.. that should be easy! (hopefully)

Trever, i followed these steps... let me know if you need me to clarify anything

follow these instructions: http://www.htpcguides.com/install-sickrage-windows-usenet-torrent-tv/
when it says install python, install python-2.7.8.amd64.msi https://www.python.org/ftp/python/2.7.8/python-2.7.8.amd64.msi and follow the instructions
continue with cheetah install as instructed
continue onto sickrage install as instructed
create the vbs script as instructed
done with the install.

now comes the fun part, configuring sickrage so it works with torrentday
after setting up your sickrage settings with your preferred torrent client and torrent search provider do the following

- modify torrentday.py to point to the new torrenday url https://torrentday.eu

replace the old torrentday URLs with the following

self.urls = {'base_url': 'https://torrentday.eu/',
                'login': 'https://torrentday.eu//torrents/',
                'search': 'https://torrentday.eu//V3/API/API.php',
                'download': 'https://torrentday.eu/download.php/%s/%s'
        }
SAVE AND RESTART SICKRAGE

i just did this and it worked straight away... 

many thanks to @fernandog @abeloin for their help

**Comment by Trever123** [comment]
DONE! FIXED! Just a side note for anyone else who stumbles across this. I am running my setup on an Ubuntu 14.04 server so updating python is very difficult (a lot of ubuntu runs on python supposedly). I did the steps as above but only the change of the URL's and disabling the proxy use. So the steps as follows were:

1. sudo apt-get update
2. sudo apt-get upgrade
3. sudo apt-get install python-cheetah (made sure cheetah was up to date)
4. stop sickrage
5. change torrentday.py in providers to the above (do not put www. in front of the URL's)
6. start sick rage back up
7. FIXED!

Thanks everyone for the patience and help. I believe this can be included in a fix and this issue now closed. Also the following issue can also be closed that was raised by me for an issue caused by the same thing. Issue 291

**Comment by abeloin** [comment]
For reference: SiCKRAGETV/SickRage#1207

**Comment by fernandog** [comment]
@Trever123 develop update. please test and report back

**Comment by Trever123** [comment]
@fernandog All fixed. Had no issues with the manual change and had no problems since getting the develop branch update. Thanks
