### ISSUE TITLE
Renamed file includes symbols

### ISSUE THREAD

**Issue by lost89577** [SiCKRAGETV/sickrage-issues#440]
Main branch - latest commit 401cb66601

the episode name on TheTVDB includes symbols which cause sickrage to show error page when going the episode list. These files where renamed by sickrage when scanned / added. 

Can we have a filter that removes and symbols and special characters that will cause problems in file renaming script.

- Named in folder

Super Mario Brothers Amada Anime Series - 1x03 - Shirayuki-hime‎ Chapter-thumb.jpg

- Error in web browser
```python
[Error 123] The filename, directory name, or volume label syntax is incorrect: u'M:\\Video\\Anime\\thtvdb\\Amada Anime Series Super Mario Brothers\\Super Mario Brothers Amada Anime Series - 1x03 - Shirayuki-hime? Chapter-thumb.jpg'
```
- Named in folder

Place to Place - 1x01 - That Way ⇔ This Way.mkv

- Error in web browser
```python
[Error 123] The filename, directory name, or volume label syntax is incorrect: u'M:\\Video\\Anime\\thtvdb\\Acchi Kocchi\\Place to Place - 1x01 - That Way ? This Way.mkv'
```
Traceback
```python
Traceback (most recent call last):
File "D:\SickRage-master\tornado\web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback))
File "D:\SickRage-master\tornado\stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs)
File "D:\SickRage-master\tornado\concurrent.py", line 226, in lambda future: callback(future.result()))
File "D:\SickRage-master\lib\concurrent\futures\_base.py", line 400, in result return self.__get_result()
File "D:\SickRage-master\lib\concurrent\futures\_base.py", line 359, in __get_result reraise(self._exception, self._traceback)
File "D:\SickRage-master\lib\concurrent\futures\_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_)
File "D:\SickRage-master\lib\concurrent\futures\thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs)
File "D:\SickRage-master\sickbeard\webserve.py", line 230, in async_call result = function(**kwargs)
File "D:\SickRage-master\sickbeard\webserve.py", line 1165, in displayShow return t.respond()
File "D:\SickRage-master\cache\cheetah\_SickRage_master_gui_slick_interfaces_default_displayShow_tmpl.py", line 658, in respond _v = VFN(VFSL([locals()]+SL+[globals(), builtin],"sickbeard.helpers",True),"pretty_filesize",False)(sickbeard.helpers.get_size(VFSL([locals()]+SL+[globals(), builtin],"showLoc",True)[0])) # u'$sickbeard.helpers.pretty_filesize(sickbeard.helpers.get_size($showLoc[0]))' on line 247, col 46
File "D:\SickRage-master\sickbeard\helpers.py", line 1279, in get_size total_size += ek.ek(os.path.getsize, fp)
File "D:\SickRage-master\sickbeard\encodingKludge.py", line 56, in ek result = func(*args, **kwargs)
File "c:\Python27\Lib\genericpath.py", line 49, in getsize return os.stat(filename).st_size
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: u'M:\\Video\\Anime\\thtvdb\\Acchi Kocchi\\Place to Place - 1x01 - That Way ? This Way.mkv'
```
Request Info
```python
body:
files: {}
protocol: http
connection:
body_arguments: {}
uri: /home/displayShow?show=257888
query_arguments: {'show': ['257888']}
_start_time: 1421670846.54
headers: {'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0', 'Dnt': '1', 'Host': 'localhost:8083', 'Referer': 'http://localhost:8083/home/', 'Cookie': 'plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0; plushQueuePerPage=10; plushHistPerPage=10; plushFailedOnly=0'}
host: localhost:8083
version: HTTP/1.1
arguments: {'show': '257888'}
_finish_time: None
query: show=257888
path: /home/displayShow
method: GET
remote_ip: 127.0.0.1
```

**Comment by fernandog** [comment]
please SSH and run:

```
locale
```

you should see something like this. must be UTF-8
```
$ locale
LANG=fr_CA.utf8
LC_CTYPE="fr_CA.utf8"
LC_NUMERIC="fr_CA.utf8"
LC_TIME="fr_CA.utf8"
LC_COLLATE="fr_CA.utf8"
LC_MONETARY="fr_CA.utf8"
LC_MESSAGES="fr_CA.utf8"
LC_PAPER="fr_CA.utf8"
LC_NAME="fr_CA.utf8"
LC_ADDRESS="fr_CA.utf8"
LC_TELEPHONE="fr_CA.utf8"
LC_MEASUREMENT="fr_CA.utf8"
LC_IDENTIFICATION="fr_CA.utf8"
LC_ALL=
```

if you don't please do this
https://sickrage.tv/forums/forum/help-support/general-support/12825-ensuring-your-locale-s-are-set-properly-to-avoid-unicode-issues

**Comment by abeloin** [comment]
@fernandog I think this symbol could be added to SanitizeFileName
