### ISSUE TITLE
Unpack with windows 7

### ISSUE THREAD

**Issue by Jezze83** [SiCKRAGETV/sickrage-issues#451]
Everytime when i try enable unpack sickrage says: Unrar Executable not found.
This is from error log: 2015-01-21 22:50:49 Thread-119 :: Rar Not Supported: exception: access violation writing 0x000093A8
SR Version:	BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb)
I tested different versions of winrar. What is correct and what are correct paths?

**Comment by abeloin** [comment]
See the FAQ: https://github.com/SiCKRAGETV/SickRage/wiki/Frequently%20Asked%20Questions

Check section: Error: Rar Not Supported: No suitable RAR unpacker installed

**Comment by Jezze83** [comment]
my path is C:\SickRage\lib\unrar2\ is it correct? I downloaded from that link but not working.

**Comment by abeloin** [comment]
@Jezze83 
Yes the path is correct. Try renaming the file to unrar.exe and restart sickrage.

**Comment by Jezze83** [comment]
Its unrar.exe and not working.

**Comment by abeloin** [comment]
What is your OS? Can you provide me with a log with the error part

**Comment by Jezze83** [comment]
Windows 7 32bit. This is only log what i get from sickrage about unpack:
2015-01-22 00:02:09 Thread-88 :: Rar Not Supported: exception: access violation writing 0x000093A8

**Comment by abeloin** [comment]
@Jezze83 Ok, Maybe you have a corrupt dll in ? Could you try to download the dll in lib/unrar2/UnRARDLL again?

@fernandog Any idea?

**Comment by abeloin** [comment]
@Jezze83 Python version?

**Comment by Jezze83** [comment]
Just tested with new dll and not working.
Python Version:	2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]

**Comment by abeloin** [comment]
For reference: https://sickrage.tv/forums/forum/help-support/general-support/16513-unpack?p=16606#post16606

**Comment by Jezze83** [comment]
Yes, thats mine post :)

**Comment by abeloin** [comment]
Can you try to replace the following code in lib/unrar2/test_UNRAR2.py:
```
import os, sys

import UnRAR2
from UnRAR2.rar_exceptions import *
```
with
```
import os,sys,inspect
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parentdir = os.path.dirname(currentdir)
sys.path.insert(0,parentdir)

import unrar2 as UnRAR2
from unrar2.rar_exceptions import *
```

Open a command line and go to the folder lib/unrar2/.
Try running test_UNRAR2.py(replace to your python path):
```
c:\python27\python.exe test_UNRAR2.py
```

Tell me the results

**Comment by Jezze83** [comment]
C:\SickRage\lib\unrar2>c:\Python27\python.exe test_UnRAR2.py
Traceback (most recent call last):
  File "test_UnRAR2.py", line 20, in <module>
    rarc = UnRAR2.RarFile('test.rar')
  File "C:\SickRage\lib\unrar2\__init__.py", line 102, in __init__
    RarFileImplementation.init(self, password)
  File "C:\SickRage\lib\unrar2\windows.py", line 240, in init
    RARSetCallback(self._handle, self.c_callback, 1)
WindowsError: exception: access violation writing 0x000093A8

**Comment by abeloin** [comment]
Ok can you try to upgrade to the latest version of unrar2?
https://code.google.com/p/py-unrar2/source/browse/

Remove everything in lib/unrar2/ and replace with the content of the zip/path.

**Comment by Jezze83** [comment]
Now unpack works, thanks alot! If i want keep original file name, do i have to use episode rename option if i want still use post-process unpack and move function?

**Comment by abeloin** [comment]
No

**Comment by abeloin** [comment]
@fernandog The unrar part in the wiki should be updated as it's outdated.

**Comment by fernandog** [comment]
@abeloin yes. @echelon must give write access to the wiki otherwise @markheloking and I can do nothing.

**Comment by fernandog** [comment]
@Jezze83 please update SR and report back please. Fix was merged

**Comment by Jezze83** [comment]
It says no update needed.

**Comment by fernandog** [comment]
chance branch to develop. config > advanced > github

**Comment by Jezze83** [comment]
Great, now it fucked up my sickrage when i chance it. Cant go anymore to settings.

Error

cannot find 'LOG_NR'

Traceback

Traceback (most recent call last): 
File "C:\SickRage\tornado\web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback)) 
File "C:\SickRage\tornado\stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs) 
File "C:\SickRage\tornado\concurrent.py", line 226, in lambda future: callback(future.result())) 
File "C:\SickRage\lib\concurrent\futures\_base.py", line 400, in result return self.__get_result() 
File "C:\SickRage\lib\concurrent\futures\_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "C:\SickRage\lib\concurrent\futures\_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "C:\SickRage\lib\concurrent\futures\thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "C:\SickRage\sickbeard\webserve.py", line 230, in async_call result = function(**kwargs) 
File "C:\SickRage\sickbeard\webserve.py", line 3390, in index 
File "C:\SickRage\cache\cheetah\cheetah__SickRage_gui_slick_interfaces_default_config_general_tmpl_1422576511_06_34084.py", line 243, in respond _v = VFSL([locals()]+SL+[globals(), builtin],"sickbeard.LOG_NR",True) # u'$sickbeard.LOG_NR' on line 104, col 62 
File "C:\Python27\lib\site-packages\cheetah-2.4.4-py2.7.egg\Cheetah\NameMapper.py", line 245, in valueFromSearchList executeCallables=executeCallables) 
File "C:\Python27\lib\site-packages\cheetah-2.4.4-py2.7.egg\Cheetah\NameMapper.py", line 226, in _valueForName _raiseNotFoundException(key, obj) 
File "C:\Python27\lib\site-packages\cheetah-2.4.4-py2.7.egg\Cheetah\NameMapper.py", line 167, in _raiseNotFoundException raise NotFound(excString) 
NotFound: cannot find 'LOG_NR'

**Comment by fernandog** [comment]
@Jezze83 it's a new feature. Restart SR

**Comment by Jezze83** [comment]
Is this latest? SR Version:	BRANCH: (develop) / COMMIT: (c62d8f2c799edd7daad5648f45276a3464d83a9e) 
Just said no update needed

**Comment by fernandog** [comment]
@Jezze83 yes

**Comment by Jezze83** [comment]
Yes it works now. Should i chance back to master?

**Comment by fernandog** [comment]
No. The error still exists at master. Stay in develop
