### ISSUE TITLE
[APP SUBMITTED]: 422 {u'documentation_url': u'https://developer.github.com/v3/gists/#create-a-gist', u'message': u'Validation Failed', u'errors': [{u'field': u'files', u'code': u'missing_field', u'resource': u'Gist'}]}

### ISSUE THREAD

**Issue by abeloin** [SiCKRAGETV/sickrage-issues#460]
### INFO
Python Version: **2.7.5 (default, Nov  3 2014, 14:26:24) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-7)]**
Operating System: **Linux-3.17.7-200.fc20.x86_64-x86_64-with-fedora-20-Heisenbug**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@91cb8d885ca278e5829ed53d856d578c8ee8cbe0
Link to Log: https://gist.github.com/da1f6de078ef4383cf34
### ERROR
```
Thread-27 :: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
Please ignore this was a test.

**Comment by fernandog** [comment]
@abeloin I added the str() as you said but I got this error too:

```
AAGithubException: 422 {u'documentation_url': u'https://developer.github.com/v3/gists/#create-a-gist', u'message': u'Validation Failed', u'errors': [{u'field': u'files', u'code': u'missing_field', u'resource': u'Gist'}]}
AA    raise self.__createException(status, responseHeaders, output)
AA  File "/home/pi/SickRage/lib/github/Requester.py", line 177, in __check
AA    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
AA  File "/home/pi/SickRage/lib/github/Requester.py", line 169, in requestJsonAndCheck
AA    input=post_parameters
AA  File "/home/pi/SickRage/lib/github/AuthenticatedUser.py", line 473, in create_gist
AA    gist = gh.get_user().create_gist(True, {"sickrage.log": InputFileContent(paste_data)})
AA  File "/home/pi/SickRage/sickbeard/logger.py", line 175, in submit_errors
AATraceback (most recent call last):
```
