### ISSUE TITLE
Config - General/Updating

### ISSUE THREAD

**Issue by Youmi15** [SiCKRAGETV/sickrage-issues#465]
This morning I did a clean install of SR, but now I can't get to the General page and the 'Check for updates' sends me to 'home' . I have seen the earlier issue #388, but it's not clear to me what I have to do to fix this. 

It might have to do with the fact that SR does not recognize the version:
SR Version: 	BRANCH: () / COMMIT: ()
You are using BETA software

I noticed here that the new config.ini file was empty, so I replaced it with the old one, but the problems still occurred. Only the SR version changed to this:

SR Version: 	BRANCH: (null) / COMMIT: (9466bddc3ee2679fe476b02d94b6227381536637) 

Edit:

When I try the fix of @fernandog (edit versiochecker.py), I am unable to open the webUI.

Hopefully someone can shed a light on this!

*Python 2.7.9 on a Popcorn Hour A300

**Comment by abeloin** [comment]
Could you provide a log? It would be useful

**Comment by Youmi15** [comment]
This is the message I get:
```
Error

'NoneType' object is not iterable
Traceback

Traceback (most recent call last):
File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/sickrage/tornado/web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback))
File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/sickrage/tornado/stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs)
File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/sickrage/tornado/concurrent.py", line 226, in lambda future: callback(future.result()))
File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/sickrage/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result()
File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/sickrage/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback)
File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/sickrage/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_)
File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/sickrage/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs)
File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/sickrage/sickbeard/webserve.py", line 230, in async_call result = function(**kwargs)
File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/sickrage/sickbeard/webserve.py", line 3390, in index return t.respond()
File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/sickrage/cache/cheetah/_opt_sybhttpd_localhost_drives_SATA_DISK_Apps_sickrage_gui_slick_interfaces_default_config_general_tmpl.py", line 952, in respond for cur_branch in VFN(VFSL([locals()]+SL+[globals(), builtin],"sickbeard.versionCheckScheduler.action",True),"list_remote_branches",False)(): # generated from line 521, col 10
TypeError: 'NoneType' object is not iterable
Request Info

body:
files: {}
protocol: http
connection:
body_arguments: {}
uri: /config/general/
query_arguments: {}
_start_time: 1422112238.44
headers: {'Accept-Language': 'nl,en-US;q=0.7,en;q=0.3', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0', 'Host': '192.168.1.2:8081', 'Referer': 'http://192.168.1.2:8081/errorlogs/viewlog/?minLevel=40', 'Cookie': 'snatched_view2=list; soon_view2=thumbs; suggestions_charts_menu_selected=charts; wanted_view2=details; advanced_toggle_checked=1; late_view2=list; manage_view2=details'}
host: 192.168.1.2:8081
version: HTTP/1.1
arguments: {}
_finish_time: None
query:
path: /config/general/
method: GET
remote_ip: 192.168.1.6
```
And the error log:
```
2015-01-24 16:10:38 Thread-39 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/sickrage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/sickrage/sickbeard/webserve.py", line 3390, in index
    return t.respond()
  File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/sickrage/cache/cheetah/_opt_sybhttpd_localhost_drives_SATA_DISK_Apps_sickrage_gui_slick_interfaces_default_config_general_tmpl.py", line 952, in respond
    for cur_branch in VFN(VFSL([locals()]+SL+[globals(), builtin],"sickbeard.versionCheckScheduler.action",True),"list_remote_branches",False)(): # generated from line 521, col 10
TypeError: 'NoneType' object is not iterable

2015-01-24 16:05:02 Thread-45 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/sickrage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/sickrage/sickbeard/webserve.py", line 3390, in index
    return t.respond()
  File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/sickrage/cache/cheetah/_opt_sybhttpd_localhost_drives_SATA_DISK_Apps_sickrage_gui_slick_interfaces_default_config_general_tmpl.py", line 952, in respond
    for cur_branch in VFN(VFSL([locals()]+SL+[globals(), builtin],"sickbeard.versionCheckScheduler.action",True),"list_remote_branches",False)(): # generated from line 521, col 10
TypeError: 'NoneType' object is not iterable
```

**Comment by fernandog** [comment]
@Youmi15 I suggest waiting the fix to be merged.

**Comment by Youmi15** [comment]
Alright, thanks anyway!
