### ISSUE TITLE
[APP SUBMITTED]: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by abeloin** [SiCKRAGETV/sickrage-issues#469]
### INFO
Python Version: **2.7.5 (default, Nov  3 2014, 14:26:24) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-7)]**
Operating System: **Linux-3.17.7-200.fc20.x86_64-x86_64-with-fedora-20-Heisenbug**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@91cb8d885ca278e5829ed53d856d578c8ee8cbe0
### ERROR
```
Thread-51 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/SickRage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/opt/SickRage/sickbeard/webserve.py", line 374, in showPoster
    return self.redirect(static_image_path)
  File "/opt/SickRage/sickbeard/webserve.py", line 191, in redirect
    super(BaseHandler, self).redirect(url, permanent, status)
  File "/opt/SickRage/tornado/web.py", line 630, in redirect
    self.finish()
  File "/opt/SickRage/tornado/web.py", line 892, in finish
    self.flush(include_footers=True)
  File "/opt/SickRage/tornado/web.py", line 846, in flush
    start_line, self._headers, chunk, callback=callback)
  File "/opt/SickRage/tornado/http1connection.py", line 385, in write_headers
    self._pending_write = self.stream.write(data)
  File "/opt/SickRage/tornado/iostream.py", line 348, in write
    self._handle_write()
  File "/opt/SickRage/tornado/iostream.py", line 800, in _handle_write
    _merge_prefix(self._write_buffer, num_bytes)
  File "/opt/SickRage/tornado/iostream.py", line 1382, in _merge_prefix
    if len(deque) == 1 and len(deque[0]) <= size:
TypeError: object of type 'NoneType' has no len()

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
This is a test
