### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'close'

### ISSUE THREAD

**Issue by abeloin** [SiCKRAGETV/sickrage-issues#470]
### INFO
Python Version: **2.7.5 (default, Nov  3 2014, 14:26:24) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-7)]**
Operating System: **Linux-3.17.7-200.fc20.x86_64-x86_64-with-fedora-20-Heisenbug**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@91cb8d885ca278e5829ed53d856d578c8ee8cbe0
### ERROR
```
Thread-38 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/SickRage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/opt/SickRage/sickbeard/webserve.py", line 374, in showPoster
    return self.redirect(static_image_path)
  File "/opt/SickRage/sickbeard/webserve.py", line 191, in redirect
    super(BaseHandler, self).redirect(url, permanent, status)
  File "/opt/SickRage/tornado/web.py", line 630, in redirect
    self.finish()
  File "/opt/SickRage/tornado/web.py", line 893, in finish
    self.request.finish()
  File "/opt/SickRage/tornado/httputil.py", line 392, in finish
    self.connection.finish()
  File "/opt/SickRage/tornado/http1connection.py", line 451, in finish
    self._pending_write.add_done_callback(self._finish_request)
  File "/opt/SickRage/tornado/concurrent.py", line 135, in add_done_callback
    fn(self)
  File "/opt/SickRage/tornado/http1connection.py", line 480, in _finish_request
    self.close()
  File "/opt/SickRage/tornado/http1connection.py", line 293, in close
    self.stream.close()
  File "/opt/SickRage/tornado/iostream.py", line 386, in close
    self.close_fd()
  File "/opt/SickRage/tornado/iostream.py", line 937, in close_fd
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
This is a test
