### ISSUE TITLE
[APP SUBMITTED]: 

Some #directives are missing their corresponding #end ___ tag: if
Line 100, column 91 in file /home/pi/SickRage/gui/slick/interfaces/default/viewlogs.tmpl

Line|Cheetah Code
----|-------------------------------------------------------------
97  |//-->
98  |</script>
99  |
100 |#include $os.path.join($sickbeard.PROG_DIR,"gui/slick/interfaces/default/inc_bottom.tmpl")
                                                                                               ^


### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#472]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) 
[GCC 4.6.3]**
Operating System: **Linux-3.12.31-armv6l-with-debian-7.6**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@91cb8d885ca278e5829ed53d856d578c8ee8cbe0
Link to Log: https://gist.github.com/6b672bc83aad82b259d2
### ERROR
```
Thread-20 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/pi/SickRage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/home/pi/SickRage/sickbeard/webserve.py", line 4709, in viewlog
    t = PageTemplate(rh=self, file="viewlogs.tmpl")
  File "/home/pi/SickRage/sickbeard/webserve.py", line 101, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1259, in __init__
    self._compile(source, file, compilerSettings=compilerSettings)
  File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1553, in _compile
    keepRefToGeneratedCode=True)
  File "/home/pi/SickRage/sickbeard/webserve.py", line 144, in compile
    return super(PageTemplate, self).compile(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 743, in compile
    compiler.compile()
  File "/usr/lib/python2.7/dist-packages/Cheetah/Compiler.py", line 1664, in compile
    self._parser.parse()
  File "/usr/lib/python2.7/dist-packages/Cheetah/Parser.py", line 1497, in parse
    self.assertEmptyOpenDirectivesStack()
  File "/usr/lib/python2.7/dist-packages/Cheetah/Parser.py", line 2657, in assertEmptyOpenDirectivesStack
    raise ParseError(self, msg=errorMsg)
ParseError: 

Some #directives are missing their corresponding #end ___ tag: if
Line 100, column 91 in file /home/pi/SickRage/gui/slick/interfaces/default/viewlogs.tmpl

Line|Cheetah Code
----|-------------------------------------------------------------
97  |//-->
98  |</script>
99  |
100 |#include $os.path.join($sickbeard.PROG_DIR,"gui/slick/interfaces/default/inc_bottom.tmpl")
                                                                                               ^


```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
test
