### ISSUE TITLE
SSL errors with lollipop

### ISSUE THREAD

**Issue by malikeye** [SiCKRAGETV/sickrage-issues#498]
Either coming from firefox or nzb360 on lollipop, I get tons of repeated SSL errors on the server:
```
2015-01-26 23:30:40 WARNING  SSL Error on 24 ('192.168.100.1', 40382): [Errno 1] _ssl.c:504: error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown
2015-01-26 23:30:40 ERROR    Uncaught exception
Traceback (most recent call last):
  File "/opt/downloader/sickrage/tornado/http1connection.py", line 681, in _server_request_loop
    ret = yield conn.read_response(request_delegate)
  File "/opt/downloader/sickrage/tornado/gen.py", line 642, in run
    value = future.result()
  File "/opt/downloader/sickrage/tornado/concurrent.py", line 110, in result
    raise_exc_info(self._exc_info)
  File "/opt/downloader/sickrage/tornado/gen.py", line 645, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/opt/downloader/sickrage/tornado/http1connection.py", line 165, in _read_message
    io_loop=self.stream.io_loop)
  File "/opt/downloader/sickrage/tornado/gen.py", line 642, in run
    value = future.result()
  File "/opt/downloader/sickrage/tornado/concurrent.py", line 112, in result
    raise self._exception
SSLError: [Errno 1] _ssl.c:504: error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown
```

This is centos7 VM running the latest git pull. Is this something on the SR side or on the android side? I don't get this error with desktop browsers.

**Comment by abeloin** [comment]
Is HTTPS activated on your sickrage? Also what branch are you using?

**Comment by malikeye** [comment]
Yep, SSL/HTTPS, definitely. Master branch.

**Comment by malikeye** [comment]
Also, I'm running couch and SAB on the same VM, all with SSL, and I don't see any other python errors. I am using a self-signed cert.

**Comment by abeloin** [comment]
For some reason your server(sickrage) doesn't like the client certificate. Can you try to remove the certificate on Lollipop?

**Comment by malikeye** [comment]
I'm looking for how to do it. I don't want to do something unless I fully understand the effect. I kinda need my phone :) I'll keep looking...

**Comment by abeloin** [comment]
Maybe it changed with lollipop but I think you can access the certificate in Settings > General > Profiles

**Comment by abeloin** [comment]
Sorry that was for gingerbead, try Settings -> security -> Trusted credential

**Comment by abeloin** [comment]
@malikeye Any news?

**Comment by abeloin** [comment]
@fernandog I think you can close this issue, no reply from the OP for the last 9 days.
