### ISSUE TITLE
Errors when grabbing subs automatically

### ISSUE THREAD

**Issue by Laidb** [SiCKRAGETV/sickrage-issues#502]
Branch ~ master
commit ~(401cb666016e45b42fe675bafdf7908ad6c2b9bb) 
OS ~ Win10 (and win 8.1, same thing there), python2.7
What I did ~ This just happens randomly when its grabbing subs for my collection automatically. 
What happened ~ http://pastebin.com/jN5SZ4LL - this can happen anything from 1 - 15 times in one instance, just grabbed the top ones now as they all seem the same. 

Its not a huge issue at all, its just at times flooding my error logs.  

```
2015-01-27 08:38:37 FINDSUBTITLES :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "C:\Games\SickRage\sickbeard\tv.py", line 1392, in downloadSubtitles
    multi=sickbeard.SUBTITLES_MULTI, cache_dir=sickbeard.CACHE_DIR)
  File "C:\Games\SickRage\lib\subliminal\api.py", line 95, in download_subtitles
    subtitles_by_video = list_subtitles(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "C:\Games\SickRage\lib\subliminal\api.py", line 54, in list_subtitles
    tasks = create_list_tasks(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "C:\Games\SickRage\lib\subliminal\core.py", line 58, in create_list_tasks
    scan_result.extend(scan(p, max_depth, scan_filter))
  File "C:\Games\SickRage\lib\subliminal\videos.py", line 246, in scan
    video = Video.from_path(entry)
  File "C:\Games\SickRage\lib\subliminal\videos.py", line 79, in from_path
    guess = guessit.guess_file_info(path, 'autodetect')
  File "C:\Games\SickRage\lib\guessit\__init__.py", line 210, in guess_file_info
    result.append(_guess_filename(filename, filetype))
  File "C:\Games\SickRage\lib\guessit\__init__.py", line 138, in _guess_filename
    title2 = next(find_nodes(mtree2.match_tree, 'title'))
StopIteration
```

**Comment by fernandog** [comment]
@Laidb can you post some of the tv-show filenames ?

**Comment by Laidb** [comment]
http://pastebin.com/ngq9uwYb

The logs are huge, but I cut out a big part that didnt mention subtitles.  I'm guessing the Friday Night Lights - S01E19 - Ch-Ch-Ch-Ch-Changes.avi is the problem here becuase of all the - - - - -. 

It only threw this one instance of the error after I turned on debug tho, ofc.

**Comment by fernandog** [comment]
@Laidb any news on this?
