### ISSUE TITLE
Freshon.tv not able to fetch torrents

### ISSUE THREAD

**Issue by combres** [SiCKRAGETV/sickrage-issues#504]
I have searched the forums and cannot find a solution. 

Here is my issue. I have setup and can connect to search provider freshon, user id and pw are correct, I checked the logs. However, no torrents can be found when a search is done by sickrage. 

Here is the log. 
2015-01-26 06:30:44 DEBUG SEARCHQUEUE-MANUAL-74608 :: [FreshOnTV] :: The Data returned from FreshOnTV do not contains any torrent 2015-01-26 06:30:44 DEBUG SEARCHQUEUE-MANUAL-74608 :: [FreshOnTV] :: Search string: http://freshon.tv/browse.php?incldea...earch=Top.Gear S22E01 2015-01-26 06:30:44 INFO SEARCHQUEUE-MANUAL-74608 :: [FreshOnTV] :: Performing episode search for Top Gear 

The url for search string works. I can see several listings if I go via a browser to the url, but as you can see no torrents found. I am not sure how to debug "The Data", since it seems like nothing is returned. 

Any help would be appreciated.

**Comment by flightlevel** [comment]
Its working well here, give the HTTPS version a try and see if the same thing happens. https://github.com/SiCKRAGETV/SickRage/pull/1245
```
2015-01-28 21:07:41 INFO     SEARCHQUEUE-BACKLOG-71663 :: [FreshOnTV] :: Performing episode search for The Simpsons
2015-01-28 21:07:41 DEBUG    SEARCHQUEUE-BACKLOG-71663 :: [FreshOnTV] :: Search string: https://freshon.tv/browse.php?incldead=0&words=0&cat=0&search=The.Simpsons S26E12 
2015-01-28 21:07:44 DEBUG    SEARCHQUEUE-BACKLOG-71663 :: [FreshOnTV] :: Found result: The.Simpsons.S26E12.720p.WEB-DL.DD5.1.H.264-NTb(https://freshon.tv/browse.php?incldead=0&words=0&cat=0&search=The.Simpsons S26E12 )
2015-01-28 21:07:44 DEBUG    SEARCHQUEUE-BACKLOG-71663 :: [FreshOnTV] :: Found result: The.Simpsons.S26E12.1080p.WEB-DL.DD5.1.H.264-NTb(https://freshon.tv/browse.php?incldead=0&words=0&cat=0&search=The.Simpsons S26E12 )
2015-01-28 21:07:44 DEBUG    SEARCHQUEUE-BACKLOG-71663 :: [FreshOnTV] :: Found result: The.Simpsons.S26E12.HDTV.x264-KILLERS(https://freshon.tv/browse.php?incldead=0&words=0&cat=0&search=The.Simpsons S26E12 )
2015-01-28 21:07:44 DEBUG    SEARCHQUEUE-BACKLOG-71663 :: [FreshOnTV] :: Found result: The.Simpsons.S26E12.720p.HDTV.x264-KILLERS(https://freshon.tv/browse.php?incldead=0&words=0&cat=0&search=The.Simpsons S26E12 )
```

**Comment by combres** [comment]
tried that but still doesn't work: 

Maybe this has something to do with it: 
BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb) 

Here is a log.  

2015-01-29 01:12:38 INFO     SEARCHQUEUE-MANUAL-74608 :: Unable to find a download for: [Top Gear - 22x01 - Race Across St Petersburg]
2015-01-29 01:12:38 DEBUG    SEARCHQUEUE-MANUAL-74608 :: formatting pattern: %SN - %Sx%0E - %EN -> Top Gear - 22x01 - Race Across St Petersburg
2015-01-29 01:12:38 DEBUG    SEARCHQUEUE-MANUAL-74608 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
2015-01-29 01:12:38 DEBUG    SEARCHQUEUE-MANUAL-74608 :: formatting pattern: %SN - %Sx%0E - %EN -> Top Gear - 22x01 - Race Across St Petersburg
2015-01-29 01:12:38 DEBUG    SEARCHQUEUE-MANUAL-74608 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
2015-01-29 01:12:38 DEBUG    SEARCHQUEUE-MANUAL-74608 :: [FreshOnTV] :: The Data returned from FreshOnTV do not contains any torrent
2015-01-29 01:12:38 DEBUG    SEARCHQUEUE-MANUAL-74608 :: [FreshOnTV] :: Search string: https://freshon.tv/browse.php?incldead=0&words=0&cat=0&search=Top.Gear S22E01 
2015-01-29 01:12:38 INFO     SEARCHQUEUE-MANUAL-74608 :: [FreshOnTV] :: Performing episode search for Top Gear

Thanks for your help.

**Comment by flightlevel** [comment]
Stop SickRage.
Change your freshontv.py file to this one (Just adds three more lines of debugging) in the link https://github.com/flightlevel/SickRage/blob/Freshon/sickbeard/providers/freshontv.py and then report back. Note: the log will be hundreds of lines, so you'll have to use pastebin for the log.

**Comment by Kybber** [comment]
I modified the file similarly earlier today. The data output is as follows:
------------->
AA	AA	» Internet Explorer 6 isn't 100% supported! Please update! AA	
AA	» For maximum experience on this site use an up-to-date browser (the latest update of your browser). AA	
AA	
AA	» If you have problems loggin in try clearing your browser's cookies and/or recover your password via email. AA	
AA	» You need cookies enabled to log in AA	AA	
AA	
AA	
AA	AA	Note AA	AA
AA AA
AA
AA
AA
AA	AA	» If your account was disabled or you simply can't log in go to our iRC channel and we'll try to help you. AA	AA	
AA	
AA	
AA	AA	Can't log in? AA	AA
... etc...
<--------
And hence nothing in torrent_table nor torrent_rows. I suspect this error to be relevant:
2015-01-29 13:00:11 SEARCHQUEUE-MANUAL-281619 :: [FreshOnTV] :: Unable to obtain cookie for FreshOnTV

Does sickrage report itself as IE 6 when trying to connect?

**Comment by Kybber** [comment]
Hmm... no it apparently doesn't. I added
logger.log("SESSION:" + str(self.session.headers), logger.DEBUG)
which resulted in
SESSION:CaseInsensitiveDict({'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-Agent': 'python-requests/2.3.0 CPython/2.6.6 Linux/2.6.32-504.3.3.el6.x86_64'})

In case the response regarding IE 6.0 from freshon.tv was a fallback for unknown user-agents, I hard-coded the session with the user agent taken from my current web-browser (which works):
self.session.headers['User-agent']='Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'
logger.log("SESSION:" + str(self.session.headers), logger.DEBUG) # To verify

The result was the same:
2015-01-29 14:06:50 ERROR    SEARCHQUEUE-MANUAL-281619 :: [FreshOnTV] :: Unable to obtain cookie for FreshOnTV
2015-01-29 14:06:50 DEBUG    SEARCHQUEUE-MANUAL-281619 :: [FreshOnTV] :: SESSION:CaseInsensitiveDict({'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'})

**Comment by fernandog** [comment]
follow guidelines please

**Comment by Kybber** [comment]
Sorry, updated my posts above. Please let me know if you need any further info.

**Comment by flightlevel** [comment]
@Kybber  Give this a go and see if it catches the cookie error
https://github.com/flightlevel/SickRage/blob/Freshon/sickbeard/providers/freshontv.py

@combres @Kybber Are you guys in the UK or behind a proxy? Are you using the 'Access provider via proxy' option in SickRage?

**Comment by Kybber** [comment]
Thanks. I notices there's a difference between when I search for the first after restarting sickrage, and searching again. I added a couple of debug lines to identify what happens differently inside doLogin() - you'll recognise the lines in your code as lines 97 and 91. 

Here's the output from searching immediately after starting sickrage:
```
2015-01-30 13:01:49 INFO     SEARCHQUEUE-MANUAL-74608 :: [FreshOnTV] :: Performing episode search for Top Gear
2015-01-30 13:01:49 DEBUG    SEARCHQUEUE-MANUAL-74608 :: [FreshOnTV] :: DEBUG ENTERED else after if self._uid and self._hash
2015-01-30 13:01:50 DEBUG    SEARCHQUEUE-MANUAL-74608 :: [FreshOnTV] :: DEBUG COOKIE: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/providers/freshontv.py", line 119, in _doLogin
    if requests.utils.dict_from_cookiejar(self.session.cookies)['uid'] and requests.utils.dict_from_cookiejar(self.session.cookies)['pass']:
KeyError: 'uid'

2015-01-30 13:01:50 ERROR    SEARCHQUEUE-MANUAL-74608 :: [FreshOnTV] :: Unable to obtain cookie for FreshOnTV
Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/providers/freshontv.py", line 119, in _doLogin
    if requests.utils.dict_from_cookiejar(self.session.cookies)['uid'] and requests.utils.dict_from_cookiejar(self.session.cookies)['pass']:
KeyError: 'uid'
```

If I try the same search again, the output differs:

```
2015-01-30 13:03:19 INFO     SEARCHQUEUE-MANUAL-74608 :: [FreshOnTV] :: Performing episode search for Top Gear
2015-01-30 13:03:19 DEBUG    SEARCHQUEUE-MANUAL-74608 :: [FreshOnTV] :: DEBUG ENTERED if any(requests.utils.dict_from_cookiejar(self.session.cookies).values())
2015-01-30 13:03:19 DEBUG    SEARCHQUEUE-MANUAL-74608 :: [FreshOnTV] :: Search string: https://freshon.tv/browse.php?incldead=0&words=0&cat=0&search=Top.Gear S22E01 
2015-01-30 13:03:19 DEBUG    SEARCHQUEUE-MANUAL-74608 :: [FreshOnTV] :: DEBUG ENTERED if any(requests.utils.dict_from_cookiejar(self.session.cookies).values())
2015-01-30 13:03:20 DEBUG    SEARCHQUEUE-MANUAL-74608 :: [FreshOnTV] :: DEBUG TABLE: None
2015-01-30 13:03:20 DEBUG    SEARCHQUEUE-MANUAL-74608 :: [FreshOnTV] :: DEBUG ROWS: []
2015-01-30 13:03:20 DEBUG    SEARCHQUEUE-MANUAL-74608 :: [FreshOnTV] :: The Data returned from FreshOnTV do not contains any torrent
```

I am not in the UK nor behind a proxy, and SickRage is not set to 'Access provider via proxy'. The only thing I can think of is that this is a virtual server (KVM) which has a secondary network device via  OpenVPN, used only for Deluge as mentioned above, but I would be very surprised if that is the reason since no other services are experiencing any kind of issues.

**Comment by flightlevel** [comment]
@combres 

Can you have another go with this
https://github.com/flightlevel/SickRage/blob/Freshon/sickbeard/providers/freshontv.py

**Comment by flightlevel** [comment]
Whoops @Kybber can you have a go at the above

**Comment by combres** [comment]
@flightlevel @Kybber I am actually using a standard setup on seedboxes.cc, which I think is hosted from somewhere in the netherlands. I am not entirely sure how they have this setup. I can probably find out. let me know what details you need and I will source. 
thx

**Comment by flightlevel** [comment]
@combres Don't worry, the same thing started happening to me and I managed to find the problem.

Freshon was/is under DDOS attack and have started using CloudFlare. [More Detail](https://www.reddit.com/r/trackers/comments/2t5vrc/it_seems_freshontv_has_gotten_ddos_protection/)
This involves a 'javascript challenge' which SickRage is unable to pass.[More Detail](https://support.cloudflare.com/hc/en-us/articles/200170176-Why-am-I-getting-a-Checking-your-Browser-before-accessing-message-before-entering-a-site-on-CloudFlare-)

The long term solution (being able to handle the CloudFlare check), doesn't seem that easy to implement. [Example](https://github.com/RuudBurger/CouchPotatoServer/issues/4153)

I've got a temporary fix using the IP instead of hostname, not sure how long it will work for though.
https://github.com/flightlevel/SickRage/blob/develop/sickbeard/providers/freshontv.py
Just replace your freshontv.py with the one above and restart sickrage

**Comment by combres** [comment]
Ah ddos... Thanks looks like I got it working, but now I have issues rtorrent syncing up. On to the next bug
Thx

**Comment by Kybber** [comment]
Nice find! Thank you for the hotfix -  I can confirm that it is currently working for me.

Let's hope they disable the CF check soon, or at least don't correct their setup for a long time so that your fix keeps on working...

**Comment by abeloin** [comment]
@flightlevel Have you tried putting a:
```self.session.get(self.urls['base_url'])```
before
```response = self.session.post(self.urls['login'], data=login_params, timeout=30, verify=False)```
it should pick the required __cfduid cookie

**Comment by abeloin** [comment]
If doesn't work have a look a this: https://github.com/Anorov/cloudflare-scrape it might help.

**Comment by flightlevel** [comment]
@abeloin the cookie won't work as there is a test to see if your browser has javascript enabled.
Option 2, the cloudflare-scrape, should work, but the CouchPotato developer says that its not a good solution and it looks too complicated for me https://github.com/RuudBurger/CouchPotatoServer/issues/4153#issuecomment-61372848
Hopefully the cloudflare check will be gone in a month or two, as it looks like it costs $200 a month for the DDOS protection.

**Comment by fernandog** [comment]
@flightlevel why don't change the freshon.tv to 104.28.15.126 ? cloudfare won't be in the way.

**Comment by abeloin** [comment]
@flightlevel Yikes! that pricey.

**Comment by fernandog** [comment]
@flightlevel @combres @Kybber the IP fix is still valid? what should we do with this issue? Is there something we can code or just wait?

https://github.com/flightlevel/SickRage/blob/develop/sickbeard/providers/freshontv.py

**Comment by flightlevel** [comment]
Hi @fernandog 
The hostname has been back working for me now for the last 24 hours, so I don't think we should change it to the IP.

However, do you think the _doLogin section https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/providers/freshontv.py (from line 90) is coded well?
At the moment it assumes any http response that doesn't contain ```Username does not exist in the userbase or the account is not confirmed yet``` as a successful login. Then when anything else but a login happens it gives the error ``` logger.log(u'Unable to obtain cookie for FreshOnTV', logger.ERROR)``` which is what threw everyone on this issue, looking for cookie problems.

Maybe we should be checking for a successful login or at least adding
`if re.search('DDoS protection by CloudFlare', response.text):`
`logger.log(u'Unable to login to ' + self.name + ' due to CloudFlare DDoS javascript check.', logger.ERROR)`
`return False`

**Comment by fernandog** [comment]
Good idea. But still keep the username check.

**Comment by flightlevel** [comment]
@fernandog Created PR https://github.com/SiCKRAGETV/SickRage/pull/1326 to improve logging. Think this issue can be closed now.

**Comment by fernandog** [comment]
@combres update and report back

**Comment by patrickmonte** [comment]
Bitsoup has same problem

2015-03-01 18:30:18 INFO     SEARCHQUEUE-MANUAL-281612 :: Building internal name cache for Allegiance
2015-03-01 18:30:18 INFO     SEARCHQUEUE-MANUAL-281612 :: No scene exceptions update needed
2015-03-01 18:30:18 INFO     SEARCHQUEUE-MANUAL-281612 :: Beginning manual search for: [Allegiance - 1x04 - Chasing Ghosts]
2015-03-01 18:30:18 DEBUG    SEARCHQUEUE-MANUAL-281612 :: formatting pattern: %SN - %Sx%0E - %EN -> Allegiance - 1x04 - Chasing Ghosts
2015-03-01 18:30:18 DEBUG    SEARCHQUEUE-MANUAL-281612 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
2015-03-01 18:30:17 INFO     SEARCHQUEUE-MANUAL-281612 :: Unable to find a download for: [Allegiance - 1x03 - Surreptitious Entry]
2015-03-01 18:30:17 DEBUG    SEARCHQUEUE-MANUAL-281612 :: formatting pattern: %SN - %Sx%0E - %EN -> Allegiance - 1x03 - Surreptitious Entry
2015-03-01 18:30:17 DEBUG    SEARCHQUEUE-MANUAL-281612 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
2015-03-01 18:30:17 DEBUG    SEARCHQUEUE-MANUAL-281612 :: formatting pattern: %SN - %Sx%0E - %EN -> Allegiance - 1x03 - Surreptitious Entry
2015-03-01 18:30:17 DEBUG    SEARCHQUEUE-MANUAL-281612 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
2015-03-01 18:30:00 DEBUG    SEARCHQUEUE-MANUAL-281612 :: Search string: https://www.bitsoup.me/browse.php?search=Allegiance S01E03 &c42=1&c45=1&c49=1&c7=1
2015-03-01 18:29:57 INFO     SEARCHQUEUE-MANUAL-281612 :: Performing season pack search for Allegiance
2015-03-01 18:29:57 INFO     SEARCHQUEUE-MANUAL-281612 :: FALLBACK SEASON PACK SEARCH INITIATED ...

**Comment by abeloin** [comment]
Please refrain from posting in old post, if you have an issue and it's not covered by any open issue, open a new one. Also use markdown for the code.

Thank you for your understanding
