### ISSUE TITLE
Exception generated in thread FINDPROPERS

### ISSUE THREAD

**Issue by gielie** [SiCKRAGETV/sickrage-issues#514]
BRANCH: (master)
COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb)
Synology 415play 

```
2015-01-29 08:02:19 DEBUG    FINDPROPERS :: 'Traceback (most recent call last):\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/scheduler.py", line 80, in run\n    self.action.run(self.force)\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/properFinder.py", line 52, in run\n    propers = self._getProperList()\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/properFinder.py", line 148, in _getProperList\n    if not pickBestResult(curProper):\n  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 224, in pickBestResult\n    if show.rls_ignore_words and filter_release_name(cur_result.name, cur_result.show.rls_ignore_words):\nAttributeError: \'NoneType\' object has no attribute \'rls_ignore_words\'\n'
2015-01-29 08:02:19 DEBUG    FINDSUBTITLES :: 281485: Saving episode details to database
AAAttributeError: 'NoneType' object has no attribute 'rls_ignore_words'
AA    if show.rls_ignore_words and filter_release_name(cur_result.name, cur_result.show.rls_ignore_words):
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 224, in pickBestResult
AA    if not pickBestResult(curProper):
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/properFinder.py", line 148, in _getProperList
AA    propers = self._getProperList()
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/properFinder.py", line 52, in run
AA    self.action.run(self.force)
AA  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/scheduler.py", line 80, in run
AATraceback (most recent call last):
2015-01-29 08:02:19 ERROR    FINDPROPERS :: Exception generated in thread FINDPROPERS: 'NoneType' object has no attribute 'rls_ignore_words'
```

**Comment by gielie** [comment]
btw how do i put this code into a box?

**Comment by fernandog** [comment]
Enclose with ```
