### ISSUE TITLE
Error:  Cannot find attribute 'contentrating'

### ISSUE THREAD

**Issue by ahaghgoo** [SiCKRAGETV/sickrage-issues#540]
When post processing I get this: 

## Error
> Cannot find attribute 'contentrating'

## Traceback

Traceback (most recent call last): 
File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/tornado/web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback)) 
File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/tornado/web.py", line 1479, in wrapper result = method(self, *args, **kwargs) 
File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 247, in post self.finish(self._dispatch()) 
File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 233, in _dispatch return func(**args) 
File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 2728, in processEpisode is_priority=is_priority, failed=failed, type=type) 
File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/processTV.py", line 210, in processDir process_media(processPath, videoFiles, nzbName, process_method, force, is_priority) 
File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/processTV.py", line 407, in process_media process_result = processor.process() 
File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/postProcessor.py", line 1004, in process ep_obj.createMetaFiles() 
File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/tv.py", line 1849, in createMetaFiles self.createNFO() 
File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/tv.py", line 1860, in createNFO result = cur_provider.create_episode_metadata(self) or result 
File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/metadata/generic.py", line 273, in create_episode_metadata return self.write_ep_file(ep_obj) 
File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/metadata/generic.py", line 459, in write_ep_file data = self._ep_data(ep_obj) 
File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/metadata/mede8er.py", line 305, in _ep_data if myShow["contentrating"] != None: 
File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/tvrage_api/tvrage_api.py", line 158, in __getitem__ raise tvrage_attributenotfound("Cannot find attribute %s" % (repr(key))) 
tvrage_attributenotfound: Cannot find attribute 'contentrating' 

## Request Info

body: type=manual&dir=%2Fshare%2FDownload%2Frtorrent%2Fdownloads&process_method=hardlink&force=on
files: {}
protocol: http
connection: 
body_arguments: {'type': ['manual'], 'force': ['on'], 'dir': ['/share/Download/rtorrent/downloads'], 'process_method': ['hardlink']}
uri: /home/postprocess/processEpisode
query_arguments: {}
_start_time: 1422979940.84
headers: {'Origin': '*****:7073', 'Content-Length': '91', 'Accept-Language': 'en-us', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18', 'Dnt': '1', 'Host': 'pacmannas.ddns.me:7073', 'Referer': 'http://*********:7073/home/postprocess/', 'Cookie': 'advanced_toggle_checked=1; cc.collabd_session_guid=76c33101-a1ef-4ad6-9aed-533524a4001f; late_view2=list; manage_view2=list; qtoken=944af67d8affa7a543eb2b457ab47f53; qtoken_account=YWhhZ2hnb28=; remeber=1; snatched_view2=list; soon_view2=thumbs; suggestions_charts_menu_selected=charts; user="2|1:0|10:1421120590|4:user|44:Zjk0YTM0MjIwMzIxNGZmYWI1NGU2YjJhNTMzMjA0ZDc=|412dc5c7097f7efd0238978f2728757750fb87f41517562b5c63d0ac1c36c561"; wanted_view2=details', 'Content-Type': 'application/x-www-form-urlencoded'}
host: *********:7073
version: HTTP/1.1
arguments: {'force': 'on', 'type': 'manual', 'dir': '/share/Download/rtorrent/downloads', 'process_method': 'hardlink'}
_finish_time: None
query: 
path: /home/postprocess/processEpisode
method: POST
remote_ip: *********

**Comment by fernandog** [comment]
@ahaghgoo when reply, will reopen
