### ISSUE TITLE
Sickrage crashes after post processing 

### ISSUE THREAD

**Issue by Kwebbel** [SiCKRAGETV/sickrage-issues#549]
Today I've noticed an error in Sabnzb which comes from sick rage post processing. After googling I removed cache.db but on the next download it happens again. Trying to access the sick rage web interface I got the same.

```
Error

database disk image is malformed

Traceback

Traceback (most recent call last): 
File "/opt/sickbeard/tornado/web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback)) 
File "/opt/sickbeard/tornado/stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs) 
File "/opt/sickbeard/tornado/concurrent.py", line 226, in lambda future: callback(future.result())) 
File "/opt/sickbeard/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result() 
File "/opt/sickbeard/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "/opt/sickbeard/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "/opt/sickbeard/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "/opt/sickbeard/sickbeard/webserve.py", line 230, in async_call result = function(**kwargs) 
File "/opt/sickbeard/sickbeard/webserve.py", line 692, in index return t.respond() 
File "/opt/sickbeard/cache/cheetah/_opt_sickbeard_gui_slick_interfaces_default_home_tmpl.py", line 131, in respond sql_result = VFN(VFFSL(SL,"myDB",True),"select",False)(VFFSL(SL,"sql_statement",True)) 
File "/opt/sickbeard/sickbeard/db.py", line 192, in select sqlResults = self.action(query, args, fetchall=True) 
File "/opt/sickbeard/sickbeard/db.py", line 170, in action sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone) 
File "/opt/sickbeard/sickbeard/db.py", line 92, in execute raise e 
DatabaseError: database disk image is malformed 

Request Info

body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /home/
query_arguments: {}
_start_time: 1423050684.49
headers: {'Accept-Language': 'en-us', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 8_1_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12B466 Safari/600.1.4', 'Dnt': '1', 'Host': '192.168.1.10:8081', 'Cookie': 'late_view2=list; plushContainerWidth=100%25; plushHistPerPage=50; plushMultiOps=1; plushNoTopMenu=0; plushQueuePerPage=50; snatched_view2=list; soon_view2=thumbs; suggestions_charts_menu_selected=charts; wanted_view2=list', 'Cache-Control': 'max-age=0'}
host: 192.168.1.10:8081
version: HTTP/1.1
arguments: {}
_finish_time: None
query: 
path: /home/
method: GET
remote_ip: 192.168.1.35

View Log(Errors)
```

**Comment by fernandog** [comment]
If you are on linux, have access to a linux box, or have a cygwin installation handy use the following steps:

install sqlite3 if not already installed.
Stop SickRage
cd into your SickRage directory
Run the commands

```
mv sickbeard.db sickbeard.db.bak
```

```
sqlite3 sickbeard.db.bak .dump | sqlite3  sickbeard.db
```

Restart sickrage

**Comment by Kwebbel** [comment]
Ouch. After removing cache.db once again now the error stays. It seems the installation is corrupted...

**Comment by fernandog** [comment]
@Kwebbel read reply please
