### ISSUE TITLE
Cannot save subtitles when tvshow description has chars that aren't common (like ' or words with accents)

### ISSUE THREAD

**Issue by TiagoDM** [SiCKRAGETV/sickrage-issues#551]
I'm portuguese and many words use accents like á or â ò, etc... every time a tvshow has chars like that, the subtitles are not saved into tvshows folder, yet they appear on history as downloaded.

SR Version:	BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb) 
SR Arguments:	['--nolaunch']
SR Web Root:	
Python Version:	2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
OS: Windows 8.1 professional

For instance I was downloading subtitles in portuguese for tvshow Hannibal, S01E12 - Relevés ...

2015-02-04 23:10:03 Thread-67 :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "C:\Users\Tiago\Desktop\SickRage-dev\sickbeard\tv.py", line 1392, in downloadSubtitles
    multi=sickbeard.SUBTITLES_MULTI, cache_dir=sickbeard.CACHE_DIR)
  File "C:\Users\Tiago\Desktop\SickRage-dev\lib\subliminal\api.py", line 95, in download_subtitles
    subtitles_by_video = list_subtitles(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "C:\Users\Tiago\Desktop\SickRage-dev\lib\subliminal\api.py", line 54, in list_subtitles
    tasks = create_list_tasks(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "C:\Users\Tiago\Desktop\SickRage-dev\lib\subliminal\core.py", line 58, in create_list_tasks
    scan_result.extend(scan(p, max_depth, scan_filter))
  File "C:\Users\Tiago\Desktop\SickRage-dev\lib\subliminal\videos.py", line 240, in scan
    logger.debug(u'Scanning file %s with depth %d/%d' % (entry, depth, max_depth))
  File "C:\Python27\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 69: character maps to 

Thank you,

Tiago

**Comment by fernandog** [comment]
change your locale to UTF-8
https://sickrage.tv/forums/forum/help-support/general-support/12825-ensuring-your-locale-s-are-set-properly-to-avoid-unicode-issues
