### ISSUE TITLE
 Failed doing webui callback

### ISSUE THREAD

**Issue by brando56894** [SiCKRAGETV/sickrage-issues#564]
2015-02-07 22:11:22 Thread-36 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usenet/SickRage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/usenet/SickRage/sickbeard/webserve.py", line 1857, in getManualSearchStatus
    if not [i for i, j in zip(searchThread.segment[0], episodes) if i.indexerid == j['episodeindexid']]:
TypeError: 'TVEpisode' object does not support indexing

debug log: http://pastebin.com/91BVmsA4

**Comment by abeloin** [comment]
That report is based on the error after applying the path from #536. You should put the original error

**Comment by brando56894** [comment]
Yea, I don't seem to have it anymore, closing issue.
