### ISSUE TITLE
Error when accessing general settings

### ISSUE THREAD

**Issue by Kwebbel** [SiCKRAGETV/sickrage-issues#566]
BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb) 

I found an error in my sick rage error log.

```
2015-02-08 16:19:04 FINDPROPERS :: Exception generated in thread FINDPROPERS: 'NoneType' object has no attribute 'rls_ignore_words'
2015-02-08 12:19:01 FINDPROPERS :: Exception generated in thread FINDPROPERS: 'NoneType' object has no attribute 'rls_ignore_words'
2015-02-08 08:19:01 FINDPROPERS :: Exception generated in thread FINDPROPERS: 'NoneType' object has no attribute 'rls_ignore_words'
2015-02-08 04:19:00 FINDPROPERS :: Exception generated in thread FINDPROPERS: 'NoneType' object has no attribute 'rls_ignore_words'
```

When I open general settings I get an error page and can't proceed.

```
Error

'NoneType' object is not iterable

Traceback

Traceback (most recent call last): 
File "/opt/sickbeard/tornado/web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback)) 
File "/opt/sickbeard/tornado/stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs) 
File "/opt/sickbeard/tornado/concurrent.py", line 226, in lambda future: callback(future.result())) 
File "/opt/sickbeard/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result() 
File "/opt/sickbeard/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "/opt/sickbeard/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "/opt/sickbeard/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "/opt/sickbeard/sickbeard/webserve.py", line 230, in async_call result = function(**kwargs) 
File "/opt/sickbeard/sickbeard/webserve.py", line 3390, in index return t.respond() 
File "/opt/sickbeard/cache/cheetah/_opt_sickbeard_gui_slick_interfaces_default_config_general_tmpl.py", line 952, in respond for cur_branch in VFN(VFFSL(SL,"sickbeard.versionCheckScheduler.action",True),"list_remote_branches",False)(): # generated from line 521, col 10 
TypeError: 'NoneType' object is not iterable 

Request Info

body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /config/general/
query_arguments: {}
_start_time: 1423414583.34
headers: {'Accept-Language': 'en-us', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18', 'Host': '192.168.1.10:8081', 'Cookie': 'late_view2=list; plushContainerWidth=100%25; plushHistPerPage=40; plushMultiOps=1; plushNoTopMenu=0; plushQueuePerPage=50; snatched_view2=list; soon_view2=thumbs; suggestions_charts_menu_selected=charts', 'Referer': 'http://192.168.1.10:8081/home/'}
host: 192.168.1.10:8081
version: HTTP/1.1
arguments: {}
_finish_time: None
query: 
path: /config/general/
method: GET
remote_ip: 192.168.1.58
```

**Comment by Kwebbel** [comment]
Solved by rebooting
