### ISSUE TITLE
Transmission: Failed Sending Torrent

### ISSUE THREAD

**Issue by moust4ki** [SiCKRAGETV/sickrage-issues#572]
Hello,

I switched from Sickbeard custom to SickRage yesterday. Everything went well as I managed to snatch a lot of full seasons and episodes. However since this morning I get no new torrent passed to Transmission. I tried to reboot, change settings without luck:
No new torrent are getting DL (old but also new show)...

Here is a sample of the errors I get, I changed the log view to Debug but I did not manage to get a better error (with more infos)

`2015-02-09 17:53:27 SEARCHQUEUE-BACKLOG-74543 :: Transmission: Failed Sending Torrent: Entourage.S08E07.VO+STFR.720p.HDTV.x264.-.IMMERSE - `
`2015-02-09 17:52:11 SEARCHQUEUE-BACKLOG-273181 :: Transmission: Failed Sending Torrent: Better.Call.Saul.S01E01.VOSTFR.720p.HDTV.x264-KiLLERMiX - `

Here are the infos of my installation (NAS Synology DS413J):
> SR Version:	BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb) 
> SR Config file:	/usr/local/sickbeard-custom/var/config.ini
> SR Database file:	/usr/local/sickbeard-custom/var/sickbeard.db
> SR Cache Dir:	/usr/local/sickbeard-custom/var/cache
> SR Arguments:	['--daemon', '--pidfile', '/usr/local/sickbeard-custom/var/sickbeard-custom.pid', '--config', '/usr/local/sickbeard-custom/var/config.ini', '--datadir', '/usr/local/sickbeard-custom/var/', '--nolaunch']
> SR Web Root:	
> Python Version:	2.7.8 (default, Dec 12 2014, 20:09:05) [GCC 4.6.4]

Edit: Could this be because my search providers are: TPB, Kickass and T411.
TPB and Kickass are down right now but T411 files are in french so SickRage "drop" them instead of passing them to Transmission?

**Comment by fernandog** [comment]
@moust4ki Config>Search Settings>Torren Search

check your settings and click "Test connection". Post the result here.

**Comment by moust4ki** [comment]
> Success: Connected and Authenticated
http://cl.ly/image/0F2N0I1h2x20

I keep getting errors:

> 2015-02-09 19:36:34 SEARCHQUEUE-DAILY-SEARCH :: Transmission: Failed Sending Torrent: Better.Call.Saul.S01E01.VOSTFR.720p.HDTV.x264-KiLLERMiX - 
> 2015-02-09 18:56:31 SEARCHQUEUE-DAILY-SEARCH :: Transmission: Failed Sending Torrent: Better.Call.Saul.S01E01.VOSTFR.720p.HDTV.x264-KiLLERMiX - 
> 2015-02-09 18:16:26 SEARCHQUEUE-DAILY-SEARCH :: Transmission: Failed Sending Torrent: Better.Call.Saul.S01E01.VOSTFR.720p.HDTV.x264-KiLLERMiX - 
> 2015-02-09 17:53:27 SEARCHQUEUE-BACKLOG-74543 :: Transmission: Failed Sending Torrent: Entourage.S08E07.VO+STFR.720p.HDTV.x264.-.IMMERSE - 
> 2015-02-09 17:52:11 SEARCHQUEUE-BACKLOG-273181 :: Transmission: Failed Sending Torrent: Better.Call.Saul.S01E01.VOSTFR.720p.HDTV.x264-KiLLERMiX -

**Comment by fernandog** [comment]
Full logs please. Get log file at /SickRage/Logs

**Comment by moust4ki** [comment]
Here is a full log:
http://pastebin.com/CUCrX8Xk

**Comment by abeloin** [comment]
Relevent bit from the log:
```
2015-02-09 18:56:31 ERROR    SEARCHQUEUE-DAILY-SEARCH :: Transmission: Failed Sending Torrent: Better.Call.Saul.S01E01.VOSTFR.720p.HDTV.x264-KiLLERMiX - 
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/clients/generic.py", line 171, in sendTORRENT
    result = self._get_torrent_hash(result)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/clients/generic.py", line 151, in _get_torrent_hash
    info = bdecode(result.content)["info"]
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/bencode/bencode.py", line 68, in bdecode
    raise BTFailure("not a valid bencoded string")
BTFailure: not a valid bencoded string
2015-02-09 18:56:31 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Transmission: Exception raised when sending torrent: not a valid bencoded string
```

**Comment by abeloin** [comment]
File download fine from t411.me.

Can you switch to develop branch there was a fix merged recently?

**Comment by moust4ki** [comment]
Ok so this solved the issue with Transmission! Thanks
Questions on the side: 
Oldpiratebay does not seems to have a lot of files as for example i can't seems to find any of my wanted items which included very old stuff like Breaking Bad and Entourage. Do you plan on using the "new" piratebay anytime soon?
As Kickass.to is planned to be changed, how long should it take to be reflected on dev branch?

Thanks for the help guys :)

**Comment by fernandog** [comment]
@moust4ki there's a commit to split oldpiratebay and piratebay. waiting to be merged

**Comment by abeloin** [comment]
The answer to both question is those 2 pull requests:
https://github.com/SiCKRAGETV/SickRage/pull/1270
https://github.com/SiCKRAGETV/SickRage/pull/1288

As to when they will be merge into develop, that's the question. ;)

**Comment by moust4ki** [comment]
I get it but i'm pretty new to software dev. Does it take long before changes like this are merged? Like Months? Weeks? Days?

Thanks again for all your help, it was amazingly fast :+1:

**Comment by abeloin** [comment]
Have a look a the commit log for the dev branch: https://github.com/SiCKRAGETV/SickRage/commits/develop
Right now it's around a merge every15 days.

**Comment by moust4ki** [comment]
Thanks @abeloin !

**Comment by MilhouseVH** [comment]
This still seems to be an issue with latest master ae2c0e8006bf0c8ec3d3379148a951847b2c5f39

```
2015-06-29 19:28:42 DEBUG    SEARCHQUEUE-MANUAL-205281 :: Transmission: Response to POST request is {"arguments":{"alt-speed-down":50,"alt-speed-enabled":false,"alt-speed-time-begin":540,"alt-speed-time-day":127,"alt-speed-time-enabled":false,"alt-speed-time-end":1020,"alt-speed-up":50,"blocklist-enabled":false,"blocklist-size":0,"blocklist-url":"http://www.example.com/blocklist","cache-size-mb":4,"config-dir":"/var/lib/transmission-daemon/info","dht-enabled":true,"download-dir":"/home/neil/transmission/tvshows","download-dir-free-space":23643426816,"download-queue-enabled":true,"download-queue-size":3,"encryption":"preferred","idle-seeding-limit":30,"idle-seeding-limit-enabled":false,"incomplete-dir":"/home/neil/transmission/tvshows-tmp","incomplete-dir-enabled":true,"lpd-enabled":false,"peer-limit-global":200,"peer-limit-per-torrent":100,"peer-port":51413,"peer-port-random-on-start":false,"pex-enabled":true,"port-forwarding-enabled":false,"queue-stalled-enabled":true,"queue-stalled-minutes":30,"rename-partial-files":true,"rpc-version":14,"rpc-version-minimum":1,"script-torrent-done-enabled":true,"script-torrent-done-filename":"/home/neil/transmission/bin/torrentComplete.sh","seed-queue-enabled":false,"seed-queue-size":10,"seedRatioLimit":2,"seedRatioLimited":false,"speed-limit-down":100,"speed-limit-down-enabled":false,"speed-limit-up":100,"speed-limit-up-enabled":false,"start-added-torrents":true,"trash-original-torrent-files":false,"units":{"memory-bytes":1024,"memory-units":["KiB","MiB","GiB","TiB"],"size-bytes":1000,"size-units":["kB","MB","GB","TB"],"speed-bytes":1000,"speed-units":["kB/s","MB/s","GB/s","TB/s"]},"utp-enabled":true,"version":"2.52 (13304)"},"result":"success"}

2015-06-29 19:28:42 ERROR    SEARCHQUEUE-MANUAL-205281 :: Unable to bdecode torrent
Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/clients/generic.py", line 157, in _get_torrent_hash
    torrent_bdecode = bdecode(result.content)
  File "/opt/sickbeard/lib/bencode/bencode.py", line 68, in bdecode
    raise BTFailure("not a valid bencoded string")
BTFailure: not a valid bencoded string
2015-06-29 19:28:42 ERROR    SEARCHQUEUE-MANUAL-205281 :: Transmission: Failed Sending Torrent
Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/clients/generic.py", line 186, in sendTORRENT
    result = self._get_torrent_hash(result)
  File "/opt/sickbeard/sickbeard/clients/generic.py", line 160, in _get_torrent_hash
    logger.log('Torrent bencoded data: {0}'.format(str(result.content)), logger.DEBUG)
  File "/opt/sickbeard/sickbeard/logger.py", line 133, in log
    message = meThread + u" :: " + msg
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 24: invalid start byte
2015-06-29 19:28:42 DEBUG    SEARCHQUEUE-MANUAL-205281 :: Transmission: Exception raised when sending torrent: KickAssTorrents @ http://torcache.net/torrent/671290C49DF65F28E1BCB83F82E756988F7B2EB6.torrent
Extra Info:
Episode: [<sickbeard.tv.TVEpisode object at 0x3a7b610>]
Quality: HDTV
Name: Falling.Skies.S05E01.720p.HDTV.x264-KILLERS[rartv]
Size: 1234531433
Release Group: KILLERS[rartv]
. Error: 'utf8' codec can't decode byte 0x8b in position 24: invalid start byte
```

Test connection to Transmission is working fine. This problem only started in the last week (I normally update once a week or so).
