### ISSUE TITLE
Fresh install gives errors when trying to access config menu

### ISSUE THREAD

**Issue by danielb2** [SiCKRAGETV/sickrage-issues#580]
Completely fresh install. On page `http://192.168.1.9:8081/config/general/`

    FreeBSD luffy 10.1-RELEASE FreeBSD 10.1-RELEASE #0
    $ python --version
    Python 2.7.9

It does seem to work on local OSX.  So it appears to be FreeBSD related.

Any help on this is appreciated. 

``` python
Error

'NoneType' object is not iterable

Traceback

Traceback (most recent call last): 
File "/usr/home/daniel/tmp/SickRage/tornado/web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback)) 
File "/usr/home/daniel/tmp/SickRage/tornado/stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs) 
File "/usr/home/daniel/tmp/SickRage/tornado/concurrent.py", line 226, in lambda future: callback(future.result())) 
File "/usr/home/daniel/tmp/SickRage/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result() 
File "/usr/home/daniel/tmp/SickRage/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "/usr/home/daniel/tmp/SickRage/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "/usr/home/daniel/tmp/SickRage/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "/usr/home/daniel/tmp/SickRage/sickbeard/webserve.py", line 230, in async_call result = function(**kwargs) 
File "/usr/home/daniel/tmp/SickRage/sickbeard/webserve.py", line 3390, in index return t.respond() 
File "/usr/home/daniel/tmp/SickRage/cache/cheetah/_usr_home_daniel_tmp_SickRage_gui_slick_interfaces_default_config_general_tmpl.py", line 952, in respond for cur_branch in VFN(VFFSL(SL,"sickbeard.versionCheckScheduler.action",True),"list_remote_branches",False)(): # generated from line 521, col 10 
TypeError: 'NoneType' object is not iterable 

Request Info

body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /config/general/
query_arguments: {}
_start_time: 1423587215.76
headers: {'Accept-Language': 'en-US,en;q=0.8,sv;q=0.6', 'Accept-Encoding': 'gzip, deflate, sdch', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36', 'Dnt': '1', 'Host': 'luffy:8081', 'Referer': 'http://luffy:8081/home/', 'Cookie': 'advanced_toggle_checked=1; manage_view2=details; wanted_view2=details; snatched_view2=list; soon_view2=thumbs; suggestions_charts_menu_selected=charts; late_view2=list; _ga=GA1.1.1477072176.1413140344'}
host: luffy:8081
version: HTTP/1.1
arguments: {}
_finish_time: None
query: 
path: /config/general/
method: GET
remote_ip: 192.168.1.15
```

**Comment by danielb2** [comment]
Additional note:  Recently I came across an SSL issue which has been fixed in later releases. When I updated, everything broke. I've tried rolling back, but I come across the SSL issue before things start working.

**Comment by abeloin** [comment]
Master or develop ? As this issue was fixed in the develop branch

**Comment by danielb2** [comment]
Ah, it was on master, and develop works fine :) thanks!
