### ISSUE TITLE
Failed doing webui callback error

### ISSUE THREAD

**Issue by Kolmain** [SiCKRAGETV/sickrage-issues#593]
I'm getting this error repeatedly on the latest update.

```
2015-02-13 08:27:46 Thread-90 :: Failed doing webui callback: Traceback (most recent call last):
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 1825, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 1787, in getEpisodes
    results.append({'episode': epObj.episode,
AttributeError: 'list' object has no attribute 'episode'

2015-02-13 08:27:15 Thread-78 :: Failed doing webui callback: Traceback (most recent call last):
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 1825, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 1787, in getEpisodes
    results.append({'episode': epObj.episode,
AttributeError: 'list' object has no attribute 'episode'

2015-02-13 08:26:44 Thread-89 :: Failed doing webui callback: Traceback (most recent call last):
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 1825, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 1787, in getEpisodes
    results.append({'episode': epObj.episode,
AttributeError: 'list' object has no attribute 'episode'

2015-02-13 08:26:13 Thread-115 :: Failed doing webui callback: Traceback (most recent call last):
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 1825, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 1787, in getEpisodes
    results.append({'episode': epObj.episode,
AttributeError: 'list' object has no attribute 'episode'

2015-02-13 08:25:42 Thread-113 :: Failed doing webui callback: Traceback (most recent call last):
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 1825, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 1787, in getEpisodes
    results.append({'episode': epObj.episode,
AttributeError: 'list' object has no attribute 'episode'

2015-02-13 08:25:11 Thread-114 :: Failed doing webui callback: Traceback (most recent call last):
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 1825, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 1787, in getEpisodes
    results.append({'episode': epObj.episode,
AttributeError: 'list' object has no attribute 'episode'

2015-02-13 08:14:36 Thread-114 :: Failed doing webui callback: Traceback (most recent call last):
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 1801, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 1787, in getEpisodes
    results.append({'episode': epObj.episode,
AttributeError: 'list' object has no attribute 'episode'

2015-02-13 08:14:05 Thread-112 :: Failed doing webui callback: Traceback (most recent call last):
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 1801, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 1787, in getEpisodes
    results.append({'episode': epObj.episode,
AttributeError: 'list' object has no attribute 'episode'

2015-02-13 08:13:44 Thread-103 :: Failed doing webui callback: Traceback (most recent call last):
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 1801, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 1787, in getEpisodes
    results.append({'episode': epObj.episode,
AttributeError: 'list' object has no attribute 'episode'

2015-02-12 11:29:50 Thread-74 :: Failed doing webui callback: Traceback (most recent call last):
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "D:\Common Programs\SickRage\sickbeard\webserve.py", line 4391, in saveNotifications
    sickbeard.PLEX_SERVER_TOKEN = config.clean_host(plex_server_token)
  File "D:\Common Programs\SickRage\sickbeard\config.py", line 270, in clean_host
    host = host.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by fernandog** [comment]
please switch to DEVELOP branch. It's fixed
