### ISSUE TITLE
Repeated error in Logs & Errors

### ISSUE THREAD

**Issue by vzoltan** [SiCKRAGETV/sickrage-issues#615]
Solved.

updated properly like this:

git remote add upstream https://github.com/SiCKRAGETV/SickRage.git
git fetch upstream
git checkout master / OR git checkout develop
git reset --hard upstream/master / OR git reset --hard upstream/develop
git pull

**Comment by vzoltan** [comment]
Sorry, but not solved, should i open a new one for this, or just copy paste the error log here?

thanks

**Comment by vzoltan** [comment]
2015-02-16 17:05:34 Thread-60 :: Failed doing webui callback: Traceback (most recent call last):
  File "/USER/SBTPB/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/USER/SBTPB/sickbeard/webserve.py", line 1690, in setStatus
    return self.redirect("/home/displayShow?show=" + show)
  File "/USER/SBTPB/sickbeard/webserve.py", line 191, in redirect
    super(BaseHandler, self).redirect(url, permanent, status)
  File "/USER/SBTPB/tornado/web.py", line 630, in redirect
    self.finish()
  File "/USER/SBTPB/tornado/web.py", line 892, in finish
    self.flush(include_footers=True)
  File "/USER/SBTPB/tornado/web.py", line 846, in flush
    start_line, self._headers, chunk, callback=callback)
  File "/USER/SBTPB/tornado/http1connection.py", line 385, in write_headers
    self._pending_write = self.stream.write(data)
  File "/USER/SBTPB/tornado/iostream.py", line 348, in write
    self._handle_write()
  File "/USER/SBTPB/tornado/iostream.py", line 800, in _handle_write
    _merge_prefix(self._write_buffer, num_bytes)
  File "/USER/SBTPB/tornado/iostream.py", line 1383, in _merge_prefix
    if len(deque) == 1 and len(deque[0]) <= size:
TypeError: object of type 'NoneType' has no len()

2015-02-16 17:05:23 Thread-67 :: Failed doing webui callback: Traceback (most recent call last):
  File "/USER/SBTPB/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/USER/SBTPB/sickbeard/webserve.py", line 1690, in setStatus
    return self.redirect("/home/displayShow?show=" + show)
  File "/USER/SBTPB/sickbeard/webserve.py", line 191, in redirect
    super(BaseHandler, self).redirect(url, permanent, status)
  File "/USER/SBTPB/tornado/web.py", line 630, in redirect
    self.finish()
  File "/USER/SBTPB/tornado/web.py", line 892, in finish
    self.flush(include_footers=True)
  File "/USER/SBTPB/tornado/web.py", line 846, in flush
    start_line, self._headers, chunk, callback=callback)
  File "/USER/SBTPB/tornado/http1connection.py", line 385, in write_headers
    self._pending_write = self.stream.write(data)
  File "/USER/SBTPB/tornado/iostream.py", line 348, in write
    self._handle_write()
  File "/USER/SBTPB/tornado/iostream.py", line 800, in _handle_write
    _merge_prefix(self._write_buffer, num_bytes)
  File "/USER/SBTPB/tornado/iostream.py", line 1383, in _merge_prefix
    if len(deque) == 1 and len(deque[0]) <= size:
TypeError: object of type 'NoneType' has no len()

**Comment by fernandog** [comment]
Known issue. Search for
object of type 'NoneType' has no len()

**Comment by vzoltan** [comment]
Ok thank you!

**Comment by fernandog** [comment]
Can you explain what do did so we can reproduce it?

**Comment by vzoltan** [comment]
Changed a downloaded episods to wanted

Thats all i dis

**Comment by vzoltan** [comment]
Episode/did :)

**Comment by vzoltan** [comment]
After login also happend rigth now

**Comment by vzoltan** [comment]
just got home and reproduced like this:

SR stopped/Started
error log is empty

changed the status of an episode to wanted 
i got 1 error 
changed back to downloded 
i got 2 errors



2015-02-16 19:04:41 Thread-100 :: Failed doing webui callback: Traceback (most recent call last):
  File "/USER/SBTPB/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/USER/SBTPB/sickbeard/webserve.py", line 1690, in setStatus
    return self.redirect("/home/displayShow?show=" + show)
  File "/USER/SBTPB/sickbeard/webserve.py", line 191, in redirect
    super(BaseHandler, self).redirect(url, permanent, status)
  File "/USER/SBTPB/tornado/web.py", line 630, in redirect
    self.finish()
  File "/USER/SBTPB/tornado/web.py", line 892, in finish
    self.flush(include_footers=True)
  File "/USER/SBTPB/tornado/web.py", line 846, in flush
    start_line, self._headers, chunk, callback=callback)
  File "/USER/SBTPB/tornado/http1connection.py", line 385, in write_headers
    self._pending_write = self.stream.write(data)
  File "/USER/SBTPB/tornado/iostream.py", line 348, in write
    self._handle_write()
  File "/USER/SBTPB/tornado/iostream.py", line 800, in _handle_write
    _merge_prefix(self._write_buffer, num_bytes)
  File "/USER/SBTPB/tornado/iostream.py", line 1383, in _merge_prefix
    if len(deque) == 1 and len(deque[0]) <= size:
TypeError: object of type 'NoneType' has no len()

2015-02-16 19:04:32 Thread-73 :: Failed doing webui callback: Traceback (most recent call last):
  File "/USER/SBTPB/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/USER/SBTPB/sickbeard/webserve.py", line 1690, in setStatus
    return self.redirect("/home/displayShow?show=" + show)
  File "/USER/SBTPB/sickbeard/webserve.py", line 191, in redirect
    super(BaseHandler, self).redirect(url, permanent, status)
  File "/USER/SBTPB/tornado/web.py", line 630, in redirect
    self.finish()
  File "/USER/SBTPB/tornado/web.py", line 892, in finish
    self.flush(include_footers=True)
  File "/USER/SBTPB/tornado/web.py", line 846, in flush
    start_line, self._headers, chunk, callback=callback)
  File "/USER/SBTPB/tornado/http1connection.py", line 385, in write_headers
    self._pending_write = self.stream.write(data)
  File "/USER/SBTPB/tornado/iostream.py", line 348, in write
    self._handle_write()
  File "/USER/SBTPB/tornado/iostream.py", line 800, in _handle_write
    _merge_prefix(self._write_buffer, num_bytes)
  File "/USER/SBTPB/tornado/iostream.py", line 1383, in _merge_prefix
    if len(deque) == 1 and len(deque[0]) <= size:
TypeError: object of type 'NoneType' has no len()

**Comment by fernandog** [comment]
would you send your DB so we can trace it?

@TagForce is it possible to trace with the DB?

**Comment by TagForce** [comment]
@fernandog @vzoltan No need for the DB...
There's actually no DB information in the call that causes this, other than the indexerid.
