### ISSUE TITLE
[APP SUBMITTED]: HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out. (read timeout=30)

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#616]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) 
[GCC 4.6.3]**
Operating System: **Linux-3.12.31-armv6l-with-debian-7.8**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@dbb0e551fc5e3c493c3ebd906f712a13aaa7de58
Link to Log: https://gist.github.com/bb8ca86910d3513b4a2a
### ERROR
```
Thread-49 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/pi/SickRage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/home/pi/SickRage/sickbeard/webserve.py", line 2242, in getRecommendedShows
    recommendedlist = trakt_api.traktRequest("recommendations/shows?extended=full,images")
  File "/home/pi/SickRage/lib/trakt/trakt.py", line 57, in traktRequest
    self.validateAccount()
  File "/home/pi/SickRage/lib/trakt/trakt.py", line 29, in validateAccount
    data=json.dumps(data), timeout=self.timeout, verify=self.verify)
  File "/home/pi/SickRage/lib/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/pi/SickRage/lib/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/SickRage/lib/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/SickRage/lib/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out. (read timeout=30)

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Is it possible to don't show the traceback to the user? Show a WARNING log message instead?!

**Comment by abeloin** [comment]
It's already cached in webserve.py L2253, the issue is the trakt library doesn't catch all requests error(trakt.py L71)

**Comment by fernandog** [comment]
@abeloin but all Exceptions has a RAISE. It will raise all exceptions

**Comment by abeloin** [comment]
Yes they are handled by line https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/webserve.py#L2253

**Comment by abeloin** [comment]
@fernandog Try this pull request https://github.com/SiCKRAGETV/SickRage/pull/1330
