### ISSUE TITLE
AniDBCommandTimeoutError

### ISSUE THREAD

**Issue by TuRDMaN** [SiCKRAGETV/sickrage-issues#624]
I've been encountering this a lot lately. Mostly when trying to save after editing a show, or when trying to manually post-process (for anime, obviously).

I'm running the latest dev version, currently, BRANCH: (develop) / COMMIT: (048212102e3dafa4e9325e8979526c5b6db0dba3)

Here is the full error from when I just tried to manually post-process a folder with a bunch of downloaded shows (which happens to be my "TV Download Dir", because they're not being automatically processed).

=============================================

Error

Command has timed out
Traceback
```
Traceback (most recent call last):
File "/usr/share/sickanime/tornado/web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback))
File "/usr/share/sickanime/tornado/stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs)
File "/usr/share/sickanime/tornado/concurrent.py", line 226, in lambda future: callback(future.result()))
File "/usr/share/sickanime/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result()
File "/usr/share/sickanime/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback)
File "/usr/share/sickanime/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_)
File "/usr/share/sickanime/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs)
File "/usr/share/sickanime/sickbeard/webserve.py", line 230, in async_call result = function(**kwargs)
File "/usr/share/sickanime/sickbeard/webserve.py", line 2029, in processEpisode is_priority=is_priority, failed=failed, type=type)
File "/usr/share/sickanime/sickbeard/processTV.py", line 181, in processDir result.result = process_media(path, [video], nzbName, process_method, force, is_priority, result)
File "/usr/share/sickanime/sickbeard/processTV.py", line 421, in process_media result.result = processor.process()
File "/usr/share/sickanime/sickbeard/postProcessor.py", line 966, in process self._add_to_anidb_mylist(self.file_path)
File "/usr/share/sickanime/sickbeard/postProcessor.py", line 514, in _add_to_anidb_mylist if helpers.set_up_anidb_connection():
File "/usr/share/sickanime/sickbeard/helpers.py", line 1013, in set_up_anidb_connection if not sickbeard.ADBA_CONNECTION.authed():
File "/usr/share/sickanime/lib/adba/__init__.py", line 139, in authed self._reAuthenticate()
File "/usr/share/sickanime/lib/adba/__init__.py", line 147, in _reAuthenticate resp = self.auth(self._username, self._password)
File "/usr/share/sickanime/lib/adba/__init__.py", line 207, in auth return self.handle(AuthCommand(username, password, 3, self.clientname, self.clientver, nat, 1, 'utf8', mtu), callback)
File "/usr/share/sickanime/lib/adba/__init__.py", line 127, in handle raise AniDBCommandTimeoutError("Command has timed out")
AniDBCommandTimeoutError: Command has timed out 
```

**Comment by fernandog** [comment]
@TuRDMaN isn't possible to increase the timeout value?
"Command has timed out "

stop SR, edit config.ini and set a higher value (seconds) to 
socket_timeout

**Comment by TuRDMaN** [comment]
Thanks for the reply @fernandog 

In my config file, I believe it was still at the default setting which was "socket_timeout = None". I changed it to 60 and I'll see what happens.

**Comment by abeloin** [comment]
That's usually an indication that you've been temporarily ban from anidb's api. Disable the anidb option for the next 24h.

Ref http://wiki.anidb.net/w/UDP_API_Definition#Connection_Problems section Flood Protection

**Comment by abeloin** [comment]
@TuRDMaN Can you test this pull request https://github.com/SiCKRAGETV/SickRage/issues/1339 ?
It will fixed the error being generated.

**Comment by TuRDMaN** [comment]
@abeloin How do I go about testing that? Is there a git command? Or do I need to edit the file manually (sorry, not so familiar with Git besides clone and pull)

**Comment by abeloin** [comment]
PR1339 Will not remove the ban on your ip but you should have a log msg instead of a traceback. Can you show me the traceback after applying the PR?

**Comment by TuRDMaN** [comment]
```
Error

Command has timed out
Traceback

Traceback (most recent call last):
File "/usr/share/sickanime/tornado/web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback))
File "/usr/share/sickanime/tornado/stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs)
File "/usr/share/sickanime/tornado/concurrent.py", line 226, in lambda future: callback(future.result()))
File "/usr/share/sickanime/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result()
File "/usr/share/sickanime/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback)
File "/usr/share/sickanime/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_)
File "/usr/share/sickanime/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs)
File "/usr/share/sickanime/sickbeard/webserve.py", line 230, in async_call result = function(**kwargs)
File "/usr/share/sickanime/sickbeard/webserve.py", line 1331, in editShow if helpers.set_up_anidb_connection():
File "/usr/share/sickanime/sickbeard/helpers.py", line 1017, in set_up_anidb_connection if not sickbeard.ADBA_CONNECTION.authed():
File "/usr/share/sickanime/lib/adba/__init__.py", line 139, in authed self._reAuthenticate()
File "/usr/share/sickanime/lib/adba/__init__.py", line 147, in _reAuthenticate resp = self.auth(self._username, self._password)
File "/usr/share/sickanime/lib/adba/__init__.py", line 207, in auth return self.handle(AuthCommand(username, password, 3, self.clientname, self.clientver, nat, 1, 'utf8', mtu), callback)
File "/usr/share/sickanime/lib/adba/__init__.py", line 127, in handle raise AniDBCommandTimeoutError("Command has timed out")
AniDBCommandTimeoutError: Command has timed out
Request Info

body: show=47109&location=%2Fmnt%2Fuser%2FAnime+-+ShowZ%2FSaenai+Heroine+no+Sodatekata&anyQualities=4&anyQualities=32768&defaultEpStatus=3&indexerLang=en&anime=on&rls_ignore_words=&rls_require_words=&whitelist=Saenai-Subs&blacklist=
files: {}
protocol: http
connection:
body_arguments: {'rls_ignore_words': [''], 'defaultEpStatus': ['3'], 'rls_require_words': [''], 'show': ['47109'], 'anyQualities': ['4', '32768'], 'indexerLang': ['en'], 'blacklist': [''], 'anime': ['on'], 'whitelist': ['Saenai-Subs'], 'location': ['/mnt/user/Anime - ShowZ/Saenai Heroine no Sodatekata']}
uri: /home/editShow
query_arguments: {}
_start_time: 1424203038.64
headers: {'Content-Length': '235', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0', 'Host': '192.168.2.136:8089', 'Referer': 'http://192.168.2.136:8089/home/editShow?show=47109', 'Cookie': 'snatched_view2=list; soon_view2=thumbs; suggestions_charts_menu_selected=suggestions; late_view2=list; _ga=GA1.1.1037445523.1419692915; advanced_toggle_checked=1; wanted_view2=list; manage_view2=list; user="2|1:0|10:1423770662|4:user|44:ZGM2ODUzMDYwMzljNDc5YjkyN2E1MjQ2ZjRhY2I4MjY=|618ebf4429080c7f9dbad8be11d62f96a5178b2537f38bb8b7cf77b1fee95640"; sickrage_user="2|1:0|10:1424201737|13:sickrage_user|44:MmIxMTFlYzdhNjdhZDgwMDkxNjYyMzYxYWM3MTk5NjU=|97e136f51a9a46035b11e30d68594546664ad2adf83e76dd978210bb93effd1c"; sessionid=nLh6rAY0GTXA17vgJigCckoBo15zORRP; CSRF-Token=tlTFLbbwkcAi11lHeIkhAUVNZTpZRFAC; JSESSIONID=nd2wgwimijtujxj6xxd2beln', 'Content-Type': 'application/x-www-form-urlencoded'}
host: 192.168.2.136:8089
version: HTTP/1.1
arguments: {'rls_ignore_words': '', 'defaultEpStatus': '3', 'rls_require_words': '', 'show': '47109', 'anyQualities': ['4', '32768'], 'indexerLang': 'en', 'blacklist': '', 'anime': 'on', 'whitelist': 'Saenai-Subs', 'location': '/mnt/user/Anime - ShowZ/Saenai Heroine no Sodatekata'}
_finish_time: None
query:
path: /home/editShow
_cookies: Set-Cookie: CSRF-Token=tlTFLbbwkcAi11lHeIkhAUVNZTpZRFAC Set-Cookie: JSESSIONID=nd2wgwimijtujxj6xxd2beln Set-Cookie: _ga=GA1.1.1037445523.1419692915 Set-Cookie: advanced_toggle_checked=1 Set-Cookie: late_view2=list Set-Cookie: manage_view2=list Set-Cookie: sessionid=nLh6rAY0GTXA17vgJigCckoBo15zORRP Set-Cookie: sickrage_user="2|1:0|10:1424201737|13:sickrage_user|44:MmIxMTFlYzdhNjdhZDgwMDkxNjYyMzYxYWM3MTk5NjU=|97e136f51a9a46035b11e30d68594546664ad2adf83e76dd978210bb93effd1c" Set-Cookie: snatched_view2=list Set-Cookie: soon_view2=thumbs Set-Cookie: suggestions_charts_menu_selected=suggestions Set-Cookie: user="2|1:0|10:1423770662|4:user|44:ZGM2ODUzMDYwMzljNDc5YjkyN2E1MjQ2ZjRhY2I4MjY=|618ebf4429080c7f9dbad8be11d62f96a5178b2537f38bb8b7cf77b1fee95640" Set-Cookie: wanted_view2=list
method: POST
remote_ip: 192.168.2.135
```

**Comment by abeloin** [comment]
@TuRDMaN I pushed some new code, can you try it?

**Comment by TuRDMaN** [comment]
Woohoo! Updated to BRANCH: (develop) / COMMIT: (e0204d048e2cfdf6ba27ee6f0a2800b8e942a1f0) 
Before, even just loading a show page took a fair amount of time sometimes, and loading the edit page would take at least 30 seconds. Now, everything seems much snappier. And I haven't encountered any errors thus far!

**Comment by abeloin** [comment]
@TuRDMaN I pushed some new code, can you try it? It will show you a ui notification when sickrage is unable to retrieve the groups from AniDB.

**Comment by TuRDMaN** [comment]
Running BRANCH: (develop) / COMMIT: (e1ea0135441662fae914b7579aaa6485e6df806d), I still managed to get an error/traceback when trying to open a bunch of edit pages at the same time. No UI notification, just an error page.

```
Error

Command has timed out
Traceback

Traceback (most recent call last):
File "/usr/share/sickanime/tornado/web.py", line 1292, in _stack_context_handle_exception raise_exc_info((type, value, traceback))
File "/usr/share/sickanime/tornado/stack_context.py", line 314, in wrapped ret = fn(*args, **kwargs)
File "/usr/share/sickanime/tornado/concurrent.py", line 226, in lambda future: callback(future.result()))
File "/usr/share/sickanime/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result()
File "/usr/share/sickanime/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback)
File "/usr/share/sickanime/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_)
File "/usr/share/sickanime/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs)
File "/usr/share/sickanime/sickbeard/webserve.py", line 230, in async_call result = function(**kwargs)
File "/usr/share/sickanime/sickbeard/webserve.py", line 1274, in editShow t.groups = anime.get_groups()
File "/usr/share/sickanime/lib/adba/aniDBAbstracter.py", line 167, in get_groups self.rawData = self.aniDB.groupstatus(aid=self.aid)
File "/usr/share/sickanime/lib/adba/__init__.py", line 581, in groupstatus return self.handle(GroupstatusCommand(aid, state), callback)
File "/usr/share/sickanime/lib/adba/__init__.py", line 127, in handle raise AniDBCommandTimeoutError("Command has timed out")
AniDBCommandTimeoutError: Command has timed out
Request Info

body:
files: {}
protocol: http
connection:
body_arguments: {}
uri: /home/editShow?show=47109
query_arguments: {'show': ['47109']}
_start_time: 1424278996.06
headers: {'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0', 'Host': '192.168.2.136:8089', 'Referer': 'http://192.168.2.136:8089/home/displayShow?show=47109', 'Cookie': 'snatched_view2=list; soon_view2=thumbs; suggestions_charts_menu_selected=suggestions; late_view2=list; _ga=GA1.1.1037445523.1419692915; advanced_toggle_checked=1; wanted_view2=list; manage_view2=list; user="2|1:0|10:1423770662|4:user|44:ZGM2ODUzMDYwMzljNDc5YjkyN2E1MjQ2ZjRhY2I4MjY=|618ebf4429080c7f9dbad8be11d62f96a5178b2537f38bb8b7cf77b1fee95640"; sickrage_user="2|1:0|10:1424277608|13:sickrage_user|44:MmIxMTFlYzdhNjdhZDgwMDkxNjYyMzYxYWM3MTk5NjU=|783a7952290a5961556985486fcb9ea76ec37af428f62fbc667437b385116db7"; sessionid=nLh6rAY0GTXA17vgJigCckoBo15zORRP; CSRF-Token=tlTFLbbwkcAi11lHeIkhAUVNZTpZRFAC; JSESSIONID=nd2wgwimijtujxj6xxd2beln'}
host: 192.168.2.136:8089
version: HTTP/1.1
arguments: {'show': '47109'}
_finish_time: None
query: show=47109
path: /home/editShow
_cookies: Set-Cookie: CSRF-Token=tlTFLbbwkcAi11lHeIkhAUVNZTpZRFAC Set-Cookie: JSESSIONID=nd2wgwimijtujxj6xxd2beln Set-Cookie: _ga=GA1.1.1037445523.1419692915 Set-Cookie: advanced_toggle_checked=1 Set-Cookie: late_view2=list Set-Cookie: manage_view2=list Set-Cookie: sessionid=nLh6rAY0GTXA17vgJigCckoBo15zORRP Set-Cookie: sickrage_user="2|1:0|10:1424277608|13:sickrage_user|44:MmIxMTFlYzdhNjdhZDgwMDkxNjYyMzYxYWM3MTk5NjU=|783a7952290a5961556985486fcb9ea76ec37af428f62fbc667437b385116db7" Set-Cookie: snatched_view2=list Set-Cookie: soon_view2=thumbs Set-Cookie: suggestions_charts_menu_selected=suggestions Set-Cookie: user="2|1:0|10:1423770662|4:user|44:ZGM2ODUzMDYwMzljNDc5YjkyN2E1MjQ2ZjRhY2I4MjY=|618ebf4429080c7f9dbad8be11d62f96a5178b2537f38bb8b7cf77b1fee95640" Set-Cookie: wanted_view2=list
method: GET
remote_ip: 192.168.2.135
```

**Comment by abeloin** [comment]
Did you apply the pull requests?
https://github.com/SiCKRAGETV/SickRage/pull/1339

**Comment by TuRDMaN** [comment]
No, I had just pulled the latest dev version. I'll edit my helpers.py and webserve.py files now

**Comment by abeloin** [comment]
The same error with exactly the same traceback? If not please provide the error page. Thanks

**Comment by abeloin** [comment]
Ok I've pushed some new code. Please update helpers.py and webserve.py files and try again.

**Comment by fernandog** [comment]
@TuRDMaN any luck?

**Comment by TuRDMaN** [comment]
Sorry, haven't had a chance to test yet. I'll try it out now.

**Comment by abeloin** [comment]
Yes because is as to wait for each command to timeout. Let me see if I can improve it

**Comment by abeloin** [comment]
@TuRDMaN I've updated the pull request, it should be faster.

**Comment by TuRDMaN** [comment]
Yes, it seems a little faster now. In any case, I have not gotten any more error pages, and the UI notifications are working. Thanks so much!
