### ISSUE TITLE
[APP SUBMITTED]: <sickbeard.tv.TVEpisode object at 0x3c90330>

### ISSUE THREAD

**Issue by Alexwijn** [SiCKRAGETV/sickrage-issues#641]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) 
[GCC 4.6.3]**
Operating System: **Linux-3.18.7+-armv6l-with-debian-7.8**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@b29f5122fc557fc2bab7ed907d3a76221fb58535
Link to Log: https://gist.github.com/e8e66fbeb71ab746b5d3
### ERROR
```
SEARCHQUEUE-BACKLOG-95491 :: [ThePirateBay] :: Unable to get the torrent file list for The.Vampire.Diaries.S05.by.ifigenia
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by abeloin** [comment]
Related to #626

**Comment by fernandog** [comment]
Yes. Here we have the traceback
```
2015-02-17 22:23:34 DEBUG    SEARCHQUEUE-BACKLOG-95491 :: [ThePirateBay] :: Result The.Vampire.Diaries.S05-E12.(2013).XviD.Custom.NLsubs.NLtoppers have 20 episode and episodes retrived in torrent are 0
KeyError: <sickbeard.tv.TVEpisode object at 0x3c90330>
    return neededEps[episode] if len(neededEps) > 0 else []
  File "/opt/sickrage/sickbeard/tvcache.py", line 285, in searchCache
    cacheResult = self.cache.searchCache(epObj, manualSearch)
  File "/opt/sickrage/sickbeard/providers/generic.py", line 266, in findSearchResults
    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch)
  File "/opt/sickrage/sickbeard/search.py", line 476, in searchProviders
Traceback (most recent call last):
```

**Comment by fernandog** [comment]
@mwarnaar do you have this issue too ? as you PR TPB new code

**Comment by fernandog** [comment]
@Alexwijn please update and report back

**Comment by Alexwijn** [comment]
Is it fixed or just suppressed?

**Comment by fernandog** [comment]
@Alexwijn suppressed. Its a TPB issue:

read here: https://github.com/SiCKRAGETV/SickRage/pull/1359
