### ISSUE TITLE
[APP SUBMITTED]: coercing to Unicode: need string or buffer, instance found

### ISSUE THREAD

**Issue by ryanf86** [SiCKRAGETV/sickrage-issues#649]
### INFO
Python Version: **2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]**
Operating System: **Darwin-14.1.0-x86_64-i386-64bit**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@e0204d048e2cfdf6ba27ee6f0a2800b8e942a1f0
Link to Log: https://gist.github.com/29d29f3fd4bf2d16b266
### ERROR
```
Thread-60 :: Failed doing webui callback: Traceback (most recent call last):
  File "/Users/ryanfoyle/SickRage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/Users/ryanfoyle/SickRage/sickbeard/webserve.py", line 1063, in update
    if sickbeard.versionCheckScheduler.action.update():
  File "/Users/ryanfoyle/SickRage/sickbeard/versionChecker.py", line 126, in update
    return self.updater.update()
  File "/Users/ryanfoyle/SickRage/sickbeard/versionChecker.py", line 632, in update
    notifiers.notify_git_update(sickbeard.NEWEST_VERSION_STRING)
  File "/Users/ryanfoyle/SickRage/sickbeard/notifiers/__init__.py", line 111, in notify_git_update
    n.notify_git_update(new_version)
  File "/Users/ryanfoyle/SickRage/sickbeard/notifiers/plex.py", line 74, in notify_git_update
    self._notify_pmc(update_text + new_version, title)
  File "/Users/ryanfoyle/SickRage/sickbeard/notifiers/plex.py", line 56, in _notify_pmc
    force=True)
  File "/Users/ryanfoyle/SickRage/sickbeard/notifiers/kodi.py", line 131, in _notify_kodi
    kodiapi = self._get_kodi_version(curHost, username, password)
  File "/Users/ryanfoyle/SickRage/sickbeard/notifiers/kodi.py", line 78, in _get_kodi_version
    result = self._send_to_kodi_json(checkCommand, host, username, password)
  File "/Users/ryanfoyle/SickRage/sickbeard/notifiers/kodi.py", line 400, in _send_to_kodi_json
    logger.log(u"Unable to decode JSON: " + response, logger.WARNING)
TypeError: coercing to Unicode: need string or buffer, instance found

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by educatedwarrior** [comment]
I'm having the same issue.   Not finding episodes in search.   I updated Sickrage; now no errors but still not finding episodes.  When I go to the search provider and search, it works.   I think the search api calls may be wrong for usenet-crawler.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/658
