### ISSUE TITLE
[APP SUBMITTED]: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by ErsinErce** [SiCKRAGETV/sickrage-issues#662]
### INFO
Python Version: **2.7.3 (default, Mar 14 2014, 11:57:14) 
[GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-686-pae-i686-with-debian-7.8**
Branch: **master**
Commit: SiCKRAGETV/SickRage@93f0f0ad1fa278afb17f73d47c099b82a766dede
Link to Log: https://gist.github.com/90276f551c9752d85ddf
### ERROR
```
Thread-41 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 3580, in saveGeneral
    return self.redirect("/config/general/")
  File "/opt/sickbeard/sickbeard/webserve.py", line 191, in redirect
    super(BaseHandler, self).redirect(url, permanent, status)
  File "/opt/sickbeard/tornado/web.py", line 630, in redirect
    self.finish()
  File "/opt/sickbeard/tornado/web.py", line 892, in finish
    self.flush(include_footers=True)
  File "/opt/sickbeard/tornado/web.py", line 846, in flush
    start_line, self._headers, chunk, callback=callback)
  File "/opt/sickbeard/tornado/http1connection.py", line 385, in write_headers
    self._pending_write = self.stream.write(data)
  File "/opt/sickbeard/tornado/iostream.py", line 348, in write
    self._handle_write()
  File "/opt/sickbeard/tornado/iostream.py", line 800, in _handle_write
    _merge_prefix(self._write_buffer, num_bytes)
  File "/opt/sickbeard/tornado/iostream.py", line 1383, in _merge_prefix
    if len(deque) == 1 and len(deque[0]) <= size:
TypeError: object of type 'NoneType' has no len()

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/231
