### ISSUE TITLE
[APP SUBMITTED]: HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out.

### ISSUE THREAD

**Issue by MasterAslan** [SiCKRAGETV/sickrage-issues#685]
### INFO
Python Version: **2.7.8 (default, Jul  2 2014, 19:50:44) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@ac153cf2320b3b6d0a8aa9a1b1646a51347581d6
Link to Log: https://gist.github.com/f738cbbc5bc3a6fc34ed
### ERROR
```
Thread-56 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\Users\Brian\Desktop\SickRage\sickbeard\webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "C:\Users\Brian\Desktop\SickRage\sickbeard\webserve.py", line 2029, in processEpisode
    is_priority=is_priority, failed=failed, type=type)
  File "C:\Users\Brian\Desktop\SickRage\sickbeard\processTV.py", line 211, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "C:\Users\Brian\Desktop\SickRage\sickbeard\processTV.py", line 421, in process_media
    result.result = processor.process()
  File "C:\Users\Brian\Desktop\SickRage\sickbeard\postProcessor.py", line 1037, in process
    notifiers.trakt_notifier.update_library(ep_obj)
  File "C:\Users\Brian\Desktop\SickRage\sickbeard\notifiers\trakt.py", line 81, in update_library
    trakt_api.traktRequest("sync/collection", data, method='POST')
  File "C:\Users\Brian\Desktop\SickRage\lib\trakt\trakt.py", line 64, in traktRequest
    data=json.dumps(data) if data else [], verify=self.verify)
  File "C:\Users\Brian\Desktop\SickRage\lib\requests\api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Brian\Desktop\SickRage\lib\requests\sessions.py", line 393, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Brian\Desktop\SickRage\lib\requests\sessions.py", line 496, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Brian\Desktop\SickRage\lib\requests\adapters.py", line 385, in send
    raise Timeout(e, request=request)
Timeout: HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out.

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
fixed in develop. wait merge to master
