### ISSUE TITLE
[APP SUBMITTED]: invalid literal for int() with base 10: 'undefined'

### ISSUE THREAD

**Issue by ripper1967** [SiCKRAGETV/sickrage-issues#688]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@55d0d213e48909ca5944260e937be72b693a7b8b
Link to Log: https://gist.github.com/5ad85e129a9d8937351d
### ERROR
```
Thread-34 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\Users\Rusty\SickRage\sickbeard\webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "C:\Users\Rusty\SickRage\sickbeard\webserve.py", line 1864, in getManualSearchStatus
    episodes += getEpisodes(searchThread, searchstatus)
  File "C:\Users\Rusty\SickRage\sickbeard\webserve.py", line 1827, in getEpisodes
    showObj = sickbeard.helpers.findCertainShow(sickbeard.showList, int(show))
ValueError: invalid literal for int() with base 10: 'undefined'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@ripper1967  please update and report back
