### ISSUE TITLE
[APP SUBMITTED]: sequence item 0: expected string, Language found

### ISSUE THREAD

**Issue by TiagoDM** [SiCKRAGETV/sickrage-issues#694]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@ac153cf2320b3b6d0a8aa9a1b1646a51347581d6
### ERROR
```
Thread-100 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\Users\Tiago\Desktop\SickRage-dev\sickbeard\webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "C:\Users\Tiago\Desktop\SickRage-dev\sickbeard\webserve.py", line 1647, in setStatus
    sql_l.append(epObj.get_sql())
  File "C:\Users\Tiago\Desktop\SickRage-dev\sickbeard\tv.py", line 1957, in get_sql
    [self.indexerid, self.indexer, self.name, self.description, ",".join([sub for sub in self.subtitles]),
TypeError: sequence item 0: expected string, Language found

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
fixed on develop
