### ISSUE TITLE
[APP SUBMITTED]: HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out.

### ISSUE THREAD

**Issue by ThePieMan** [SiCKRAGETV/sickrage-issues#711]
### INFO
Python Version: **2.7.3 (default, Apr 10 2012, 23:24:47) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **master**
Commit: SiCKRAGETV/SickRage@ac153cf2320b3b6d0a8aa9a1b1646a51347581d6
Link to Log: https://gist.github.com/13c619e72a4849a07bd4
### ERROR
```
Thread-325 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\MyPrograms\SickRage\sickbeard\webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "C:\MyPrograms\SickRage\sickbeard\webserve.py", line 1477, in deleteShow
    sickbeard.traktCheckerScheduler.action.removeShowFromTraktLibrary(showObj)
  File "C:\MyPrograms\SickRage\sickbeard\traktChecker.py", line 106, in removeShowFromTraktLibrary
    self.trakt_api.traktRequest("sync/collection/remove", data, method='POST')
  File "C:\MyPrograms\SickRage\lib\trakt\trakt.py", line 64, in traktRequest
    data=json.dumps(data) if data else [], verify=self.verify)
  File "C:\MyPrograms\SickRage\lib\requests\api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\MyPrograms\SickRage\lib\requests\sessions.py", line 393, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\MyPrograms\SickRage\lib\requests\sessions.py", line 496, in send
    r = adapter.send(request, **kwargs)
  File "C:\MyPrograms\SickRage\lib\requests\adapters.py", line 385, in send
    raise Timeout(e, request=request)
Timeout: HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out.

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Duplicate

**Comment by fernandog** [comment]
Increate trakt timeout please
