### ISSUE TITLE
[APP SUBMITTED]: HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out.

### ISSUE THREAD

**Issue by Bane89** [SiCKRAGETV/sickrage-issues#735]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Branch: **master**
Commit: SiCKRAGETV/SickRage@2d8aad80cdfb8983832206af445039de0decded9
### ERROR
```
Thread-69 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 2298, in getTrendingShows
    shows = trakt_api.traktRequest("shows/trending?limit=50&extended=full,images") or []
  File "C:\SickRage\lib\trakt\trakt.py", line 57, in traktRequest
    self.validateAccount()
  File "C:\SickRage\lib\trakt\trakt.py", line 29, in validateAccount
    data=json.dumps(data), timeout=self.timeout, verify=self.verify)
  File "C:\SickRage\lib\requests\api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\SickRage\lib\requests\sessions.py", line 393, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\SickRage\lib\requests\sessions.py", line 496, in send
    r = adapter.send(request, **kwargs)
  File "C:\SickRage\lib\requests\adapters.py", line 385, in send
    raise Timeout(e, request=request)
Timeout: HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out.

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Increate trakt timeout
