### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters in position 75-80: character maps to <undefined>

### ISSUE THREAD

**Issue by gborri** [SiCKRAGETV/sickrage-issues#744]
**INFO**

Python Version: Python 2.7.6 (default, Mar 22 2014, 22:59:38) [GCC 4.8.2] on linux2
Operating System: Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-43-generic i686)
Branch: develop
Commit: SiCKRAGETV/SickRage@commit 3c083d45d283a57b9f515b0fd2897f0584939f59

**ERROR**

```
2015-02-24 09:51:54 DEBUG    SHOWQUEUE-ADD :: Looking up XEM scene mapping using for show 79222 on theTVDB
2015-02-24 09:51:54 DEBUG    SHOWQUEUE-ADD :: Empty lookup result - no XEM data for show 79222 on theTVDB
2015-02-24 09:51:55 INFO     SHOWQUEUE-ADD :: Starting to add show /home/mediacenter/src/sickbeard/TVShow-Merge/Continuum
2015-02-24 09:51:55 INFO     SHOWQUEUE-ADD :: theTVDB: {'useZip': True, 'apikey': 'F9C450E78D99172E', 'cache': '/home/mediacenter/src/sickbeard/sickrage/sickrage_test/cache/indexers/theTVDB', 'language': 'en'}
2015-02-24 09:51:56 ERROR    Uncaught exception GET /images/network/%D1%80%D0%BE%D1%81%D1%81%D0%B8%D1%8F%201.png (xxx.xxx.xxx.xxx)
HTTPServerRequest(protocol='https', host='xxx.xxx.xxx.xxx', method='GET', uri='/images/network/%D1%80%D0%BE%D1%81%D1%81%D0%B8%D1%8F%201.png', version='HTTP/1.1', remote_ip='xxx.xxx.xxx.xxx', headers={'Accept-Language': 'it-IT,it;q=0.8,en-US;q=0.6,en;q=0.4', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': 'xxx.xxx.xxx.xxx:8084', 'Accept': 'image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'https://xxx.xxx.xxx.xxx:8084/home/', 'Cache-Control': 'max-age=0', 'Cookie': 'snatched_view2=list; soon_view2=thumbs; wanted_view2=details; suggestions_charts_menu_selected=suggestions; late_view2=list; user="2|1:0|10:1423826153|4:user|44:OGQyY2E3ZDljMTM3MjRiZmQ3NTZlNzgzY2E3ZmFkOWE=|b40bc2f182799c8db02f3d68f3d52d7296757bb79702317c34e62b7cff66b0c7"; sickrage_user="2|1:0|10:1424687543|13:sickrage_user|44:OGQyY2E3ZDljMTM3MjRiZmQ3NTZlNzgzY2E3ZmFkOWE=|f8dcac4216f891a875d28e98a47684ae295ca473157f17377325ddbd3c981db5"'})
Traceback (most recent call last):
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/tornado/web.py", line 1338, in _execute
    result = yield result
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/tornado/gen.py", line 642, in run
    value = future.result()
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/tornado/concurrent.py", line 110, in result
    raise_exc_info(self._exc_info)
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/tornado/gen.py", line 189, in wrapper
    yielded = next(result)
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/tornado/web.py", line 2115, in get
    self.root, absolute_path)
  File "/home/mediacenter/src/sickbeard/sickrage/sickrage/tornado/web.py", line 2284, in validate_absolute_path
    if (os.path.isdir(absolute_path) and
  File "/usr/lib/python2.7/genericpath.py", line 41, in isdir
    st = os.stat(s)
  File "/usr/lib/python2.7/encodings/iso8859_15.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 75-80: character maps to <undefined>
```

**Comment by fernandog** [comment]
Change locale and please use UTF-8

**Comment by neoatomic** [comment]
Cant reproduce this error on Develop.
I added the "Continuum" show from Tvdb without any errors. :

![naamloos](https://cloud.githubusercontent.com/assets/7928052/6346799/2900072e-bc13-11e4-90af-9f77227338f4.jpg)

Please provide more information on what you where doing.

**Comment by fernandog** [comment]
@neoatomic he is not using utf. 
whats the resulf in SSH of your:
locale

**Comment by neoatomic** [comment]
@fernandog Didn't see your message before submitting...

Btw this is the output of my Synology?  :

```
/$  locale
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

**Comment by abeloin** [comment]
@gborri I see that you are on your own custom branch. Can you switch back to the develop branch and retry?

**Comment by abeloin** [comment]
For ref:
`/images/network/%D1%80%D0%BE%D1%81%D1%81%D0%B8%D1%8F%201.png`
is
`/images/network/россия 1.png`

**Comment by fernandog** [comment]
@abeloin so this error can happen not only with windows, Am I right?

**Comment by abeloin** [comment]
Yes

**Comment by fernandog** [comment]
isn't possible to set locale to utf-8 in python when starting SR? we wont' be able to catch all exceptions about this

**Comment by abeloin** [comment]
I'm surprised that Ubuntu isn't defaulting to UTF by default.

**Comment by abeloin** [comment]
No, it console dependent. The main issue isn't with the console codepage, but the fact that sickrage isn't fully unicode internally which gives us all those weird decoding error.

**Comment by abeloin** [comment]
See this: https://pythonhosted.org/kitchen/unicode-frustrations.html

**Comment by fernandog** [comment]
@abeloin what if we show a big message in the screen to use UTF-8 (like the update div) if system locale it's not UTF-8 (linux machines only)?

**Comment by gborri** [comment]
@abeloin ubuntu default UTF8, some times ago i have change it. Sorry for the issue.

**Comment by gborri** [comment]
@abeloin checked out develop, rebase to upstream/develop, changed locale and seems to work.
you could close. Sorry for this fake issue.
