### ISSUE TITLE
Manual post-processing results in deleting completed file before moving it

### ISSUE THREAD

**Issue by suprdave23** [SiCKRAGETV/sickrage-issues#760]
I checked "Force already Post Processed Dir/Files:" and "Mark Dir/Files as priority download:". It resulted in this error. It appears it deleted my completed file before trying to move it into it's correct "TV Shows" folder location. This doesn't seem right?

2015-02-24 22:12:53 WARNING  Thread-25 :: Problem(s) during processing
2015-02-24 22:12:53 WARNING  Thread-25 :: Processing failed for D:\Torrents\Completed\The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS[rarbg]\The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS.mkv: Unable to move the files to their new home
AAIOError: [Errno 2] No such file or directory: u'D:\\Torrents\\Completed\\The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS[rarbg]\\The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS.mkv'
AA    with open(src, 'rb') as fsrc:
AA  File "C:\Python27\lib\shutil.py", line 82, in copyfile
AA    copyfile(src, dst)
AA  File "C:\Python27\lib\shutil.py", line 130, in copy2
AA    copy2(src, real_dst)
AA  File "C:\Python27\lib\shutil.py", line 302, in move
AA    result = func(*args, **kwargs)
AA  File "c:\sickrage\sickbeard\encodingKludge.py", line 56, in ek
AA    ek.ek(shutil.move, srcFile, destFile)
AA  File "c:\sickrage\sickbeard\helpers.py", line 361, in moveFile
AA    helpers.moveFile(cur_file_path, new_file_path)
AA  File "c:\sickrage\sickbeard\postProcessor.py", line 319, in _int_move
AATraceback (most recent call last):
2015-02-24 22:12:53 ERROR    Thread-25 :: Unable to move file D:\Torrents\Completed\The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS[rarbg]\The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS.mkv to D:\TV Shows\The Americans\Season 03\The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS.mkv: [Errno 2] No such file or directory: u'D:\\Torrents\\Completed\\The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS[rarbg]\\The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS.mkv'
2015-02-24 22:12:53 DEBUG    Thread-25 :: Moving file from D:\Torrents\Completed\The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS[rarbg]\The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS.mkv to D:\TV Shows\The Americans\Season 03\The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS.mkv
2015-02-24 22:12:53 DEBUG    Thread-25 :: Folder D:\TV Shows\The Americans\Season 03 didn't exist, creating it
2015-02-24 22:12:53 DEBUG    Thread-25 :: Checking if the path D:\TV Shows\The Americans\Season 03 already exists
2015-02-24 22:12:53 DEBUG    Thread-25 :: Destination folder for this episode: D:\TV Shows\The Americans\Season 03
2015-02-24 22:12:53 DEBUG    Thread-25 :: formatting pattern: Season %0S -> Season 03
2015-02-24 22:12:53 DEBUG    Thread-25 :: Using cached parse result for: The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS
2015-02-24 22:12:53 DEBUG    Thread-25 :: Using NORMAL regexs
2015-02-24 22:12:53 DEBUG    Thread-25 :: formatting pattern: %SN - S%0SE%0E - %EN -> The Americans (2013) - S03E04 - Dimebag
2015-02-24 22:12:53 DEBUG    Thread-25 :: Using cached parse result for: The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS
2015-02-24 22:12:53 DEBUG    Thread-25 :: Using NORMAL regexs
2015-02-24 22:12:53 INFO     Thread-25 :: Folder name (The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS[rarbg]) appears to be a valid release name. Using it.
2015-02-24 22:12:53 DEBUG    Thread-25 :: Parsed The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS[rarbg] into The Americans 2013 - S3E4 [ANIME VER: -1] [GROUP: KILLERS[rarbg]] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-02-24 22:12:53 DEBUG    Thread-25 :: Using ALL regexes
2015-02-24 22:12:53 DEBUG    Thread-25 :: Transaction with 1 queries executed
2015-02-24 22:12:53 DEBUG    Thread-25 :: Found release name The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS
2015-02-24 22:12:53 INFO     Thread-25 :: Trying to clean any empty folders under D:\TV Shows\The Americans\The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS[rarbg]
2015-02-24 22:12:53 DEBUG    Thread-25 :: Read only mode on file D:\Torrents\Completed\The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS[rarbg]\The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS.mkv Will try to make it writeable
2015-02-24 22:12:53 DEBUG    Thread-25 :: Deleting file D:\Torrents\Completed\The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS[rarbg]\The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS.mkv
2015-02-24 22:12:53 DEBUG    Thread-25 :: Deleting file D:\TV Shows\The Americans\The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS[rarbg]\The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS.mkv
2015-02-24 22:12:53 DEBUG    Thread-25 :: This download is marked a priority download so I'm going to replace an existing file if I find one
2015-02-24 22:12:53 DEBUG    Thread-25 :: File D:\TV Shows\The Americans\The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS[rarbg]\The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS.mkv is the same size as D:\Torrents\Completed\The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS[rarbg]\The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS.mkv
2015-02-24 22:12:53 DEBUG    Thread-25 :: Snatch history had a version in it, using that: v-1
2015-02-24 22:12:53 DEBUG    Thread-25 :: Is ep a priority download: True
2015-02-24 22:12:53 DEBUG    Thread-25 :: Quality of the episode we're processing: 4
2015-02-24 22:12:53 DEBUG    Thread-25 :: Snatch history had a quality in it, using that: HD TV
2015-02-24 22:12:53 DEBUG    Thread-25 :: Retrieving episode object for 3x4
2015-02-24 22:12:53 DEBUG    Thread-25 :: Parsed The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS into The Americans 2013 - S3E4 [ANIME VER: -1] [GROUP: KILLERS] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-02-24 22:12:53 DEBUG    Thread-25 :: Converted parsed result The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS into The Americans 2013 - S3E4 [ANIME VER: -1] [GROUP: KILLERS] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-02-24 22:12:52 DEBUG    Thread-25 :: Using ALL regexes
2015-02-24 22:12:52 INFO     Thread-25 :: Analyzing name u'The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS.mkv'
2015-02-24 22:12:52 INFO     Thread-25 :: Analyzing name None
2015-02-24 22:12:52 DEBUG    Thread-25 :: Found result in history: (, 3, [], 4, -1)
2015-02-24 22:12:52 INFO     Thread-25 :: Processing D:\Torrents\Completed\The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS[rarbg]\The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS.mkv (None)
2015-02-24 22:12:52 DEBUG    Thread-25 :: PostProcessing VideoInRar: []
2015-02-24 22:12:52 DEBUG    Thread-25 :: PostProcessing RarContent: []
2015-02-24 22:12:52 DEBUG    Thread-25 :: PostProcessing VideoFiles: [u'The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS.mkv']
2015-02-24 22:12:52 DEBUG    Thread-25 :: PostProcessing Files: [u'The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS.mkv']
2015-02-24 22:12:52 DEBUG    Thread-25 :: PostProcessing Dirs: []
2015-02-24 22:12:52 DEBUG    Thread-25 :: PostProcessing Path: D:\Torrents\Completed\The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS[rarbg]
2015-02-24 22:12:52 DEBUG    Thread-25 :: TV_DOWNLOAD_DIR: D:\Torrents\Completed
2015-02-24 22:12:52 DEBUG    Thread-25 :: Processing folder D:\Torrents\Completed\The.Americans.2013.S03E04.720p.HDTV.x264-KILLERS[rarbg]

**Comment by fernandog** [comment]
Follow guidelines
https://github.com/SiCKRAGETV/sickrage-issues/

**Comment by kkuhle** [comment]
Same issue for me.  Here is my log.  http://pastebin.com/0F7tJgrx
