### ISSUE TITLE
Manually setting shows back to "Wanted" status is not being handled by post-processing properly

### ISSUE THREAD

**Issue by suprdave23** [SiCKRAGETV/sickrage-issues#770]
* Branch
BRANCH: (master)

* Commit hash
COMMIT: (2d8aad80cdfb8983832206af445039de0decded9)

* Your operating system and python version
Windows 7 x64, Python 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]

* What you did
Manually set several episodes of a show back to "Wanted" status so that they would re-download. 

* What happened
The torrents were grabbed successfully and downloaded. However during post-processing the message "You're trying to post process a video that's already been processed, skipping" is shown and the file/folders are deleted.

* What you expected
I purposefully set the episode to be redownloaded, so I would expect SickRage to honor that request and treat the file as if it's never been downloaded before.

* Link to a copy/paste of your logfile with clear debug info of the error on PASTEBIN
N/A unless you really need the logs showing this :)

Please let me know if there's a workaround for this. I've tried setting it to both "Wanted" and manually clicking the search button for the episode, it results in the same outcome.

**Comment by mmazur519** [comment]
Did the same thing and these are the errors I am getting in proccessing.

SR Version:	BRANCH: (develop) / COMMIT: (7c6fe7fcbe9a8ccdb8d90a252f8680f2af7fa7ec) 

Error Log:
2015-02-25 17:38:48 POSTPROCESSER :: Exception generated in thread POSTPROCESSER: execv() arg 2 must contain only strings
2015-02-25 17:28:48 POSTPROCESSER :: Exception generated in thread POSTPROCESSER: execv() arg 2 must contain only strings
2015-02-25 17:26:49 Thread-38 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/sickbeard/sickrage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/home/sickbeard/sickrage/sickbeard/webserve.py", line 2044, in processEpisode
    is_priority=is_priority, failed=failed, type=type)
  File "/home/sickbeard/sickrage/sickbeard/processTV.py", line 221, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/home/sickbeard/sickrage/sickbeard/processTV.py", line 431, in process_media
    result.result = processor.process()
  File "/home/sickbeard/sickrage/sickbeard/postProcessor.py", line 972, in process
    sickbeard.USE_SUBTITLES and ep_obj.show.subtitles)
  File "/home/sickbeard/sickrage/sickbeard/postProcessor.py", line 347, in _copy
    subtitles=subtitles)
  File "/home/sickbeard/sickrage/sickbeard/postProcessor.py", line 305, in _combined_file_operation
    action(cur_file_path, new_file_path)
  File "/home/sickbeard/sickrage/sickbeard/postProcessor.py", line 340, in _int_copy
    helpers.copyFile(cur_file_path, new_file_path)
  File "/home/sickbeard/sickrage/sickbeard/helpers.py", line 351, in copyFile
    subprocess.call(['cp', srcFile, destFile])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings

2015-02-25 17:18:48 POSTPROCESSER :: Exception generated in thread POSTPROCESSER: execv() arg 2 must contain only strings
2015-02-25 17:16:06 Thread-43 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/sickbeard/sickrage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/home/sickbeard/sickrage/sickbeard/webserve.py", line 2044, in processEpisode
    is_priority=is_priority, failed=failed, type=type)
  File "/home/sickbeard/sickrage/sickbeard/processTV.py", line 221, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/home/sickbeard/sickrage/sickbeard/processTV.py", line 431, in process_media
    result.result = processor.process()
  File "/home/sickbeard/sickrage/sickbeard/postProcessor.py", line 972, in process
    sickbeard.USE_SUBTITLES and ep_obj.show.subtitles)
  File "/home/sickbeard/sickrage/sickbeard/postProcessor.py", line 347, in _copy
    subtitles=subtitles)
  File "/home/sickbeard/sickrage/sickbeard/postProcessor.py", line 305, in _combined_file_operation
    action(cur_file_path, new_file_path)
  File "/home/sickbeard/sickrage/sickbeard/postProcessor.py", line 340, in _int_copy
    helpers.copyFile(cur_file_path, new_file_path)
  File "/home/sickbeard/sickrage/sickbeard/helpers.py", line 351, in copyFile
    subprocess.call(['cp', srcFile, destFile])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings

**Comment by suprdave23** [comment]
@abeloin @fernandog 

This just got me again when I was trying to redownload an episode I had already downloaded once before but the file was no longer on disk, super frustrating! Can we please get an option to always treat files as if we are manually post processing them? It's irritating to download a file through SR and expect it to handle the file but just have it ignored/deleted instead. 

I understand the rationale behind the behavior, but at the same time if a user has manually clicked "Search", or set the episode back to "Wanted" status, clearly they want the episode downloaded again.

Thanks!

**Comment by fernandog** [comment]
@suprdave23 we will change how manual search works. wait for new thing on this!

**Comment by suprdave23** [comment]
@fernandog Great! Thanks for getting back to me!

Looking forward to this new feature. Let me know once it is ready and I'll be happy to update my copy and test it.

**Comment by hugoduraes** [comment]
Having the same problem as @suprdave23. Please fix/change this behaviour.

Please notify us when the new features will be available.

**Comment by TagForce** [comment]
It could be as simple as setting the release_name to "" in the epObj when setting the status to Wanted.
But then, the releasename would be lost forever.
Because if ```sqlResult = myDB.select("SELECT * FROM tv_episodes WHERE release_name = ?", [videofile.rpartition('.')[0]])``` returns a result, it will tell you it has already been post processed.

**Comment by hugoduraes** [comment]
When you post process files manually you've an option to "Force already Post Processed Dir/Files". So it should be as simple as using the same behaviour when setting the status to Wanted.

**Comment by TagForce** [comment]
Now that I'm thinking about it...
We could also move the already_processed check from before processing the file to when we're already processing it, but not yet moving or copying it or adding anything to the db.
Then if the status is WANTED we can simply ignore the already_processed outcome, and process it anyway (with priority and force)

**Comment by TagForce** [comment]
@hugoduraes Not that simple. Since Post Processing and setting a status are not in the slightest bit related, there's no way to set any PP options when setting a status. We CAN however check some things during post processing.
However, the status for a Wanted episode will be Snatched by the time it gets to PP... Ugh.. This is gonna get ugly :hammer:

**Comment by hugoduraes** [comment]
I see... I've suggested that without looking at the code!

Well, the only solution I can think of right now is to create a new special status called "ReSnatched" and force post processing for episodes with this status. Don't know if this is viable... just throwing ideas into the table.

**Comment by fernandog** [comment]
@TagForce what if we create another field: previous_release_name, previous_status?

this maybe help in the other feature that is if the better quality fails to download, get previous status.

https://github.com/SiCKRAGETV/sickrage-issues/issues/674#issuecomment-77431532

https://github.com/SiCKRAGETV/sickrage-issues/issues/547

**Comment by TagForce** [comment]
@fernandog Yes. I think it'll come to something like that.
I think I can make it work by setting release_name to "" when setting status from downloaded to wanted for now.

**Comment by fernandog** [comment]
@TagForce ok!

**Comment by fernandog** [comment]
@TagForce are we going to set release_name to "" ?

**Comment by TagForce** [comment]
@fernandog Ah... This one slipped under my radar...
I'll fix it tonigght or tomorrow

**Comment by fernandog** [comment]
@TagForce I added the new fields suggestion to the TO DO list in issue STATs. Anything in your radar that we shoud add there?

**Comment by fernandog** [comment]
@suprdave23 did you tested the fix on develop
