### ISSUE TITLE
[APP SUBMITTED]: execv() arg 2 must contain only strings

### ISSUE THREAD

**Issue by mmazur519** [SiCKRAGETV/sickrage-issues#773]
### INFO
Python Version: **2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2]**
Operating System: **Linux-3.13.0-45-generic-x86_64-with-Ubuntu-14.04-trusty**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@7c6fe7fcbe9a8ccdb8d90a252f8680f2af7fa7ec
### ERROR
```
POSTPROCESSER :: Exception generated in thread POSTPROCESSER: execv() arg 2 must contain only strings
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

```
2015-02-25 17:38:48 POSTPROCESSER :: Exception generated in thread POSTPROCESSER: execv() arg 2 must contain only strings
2015-02-25 17:28:48 POSTPROCESSER :: Exception generated in thread POSTPROCESSER: execv() arg 2 must contain only strings
2015-02-25 17:26:49 Thread-38 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/sickbeard/sickrage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/home/sickbeard/sickrage/sickbeard/webserve.py", line 2044, in processEpisode
    is_priority=is_priority, failed=failed, type=type)
  File "/home/sickbeard/sickrage/sickbeard/processTV.py", line 221, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/home/sickbeard/sickrage/sickbeard/processTV.py", line 431, in process_media
    result.result = processor.process()
  File "/home/sickbeard/sickrage/sickbeard/postProcessor.py", line 972, in process
    sickbeard.USE_SUBTITLES and ep_obj.show.subtitles)
  File "/home/sickbeard/sickrage/sickbeard/postProcessor.py", line 347, in _copy
    subtitles=subtitles)
  File "/home/sickbeard/sickrage/sickbeard/postProcessor.py", line 305, in _combined_file_operation
    action(cur_file_path, new_file_path)
  File "/home/sickbeard/sickrage/sickbeard/postProcessor.py", line 340, in _int_copy
    helpers.copyFile(cur_file_path, new_file_path)
  File "/home/sickbeard/sickrage/sickbeard/helpers.py", line 351, in copyFile
    subprocess.call(['cp', srcFile, destFile])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings

2015-02-25 17:18:48 POSTPROCESSER :: Exception generated in thread POSTPROCESSER: execv() arg 2 must contain only strings
2015-02-25 17:16:06 Thread-43 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/sickbeard/sickrage/sickbeard/webserve.py", line 230, in async_call
    result = function(**kwargs)
  File "/home/sickbeard/sickrage/sickbeard/webserve.py", line 2044, in processEpisode
    is_priority=is_priority, failed=failed, type=type)
  File "/home/sickbeard/sickrage/sickbeard/processTV.py", line 221, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/home/sickbeard/sickrage/sickbeard/processTV.py", line 431, in process_media
    result.result = processor.process()
  File "/home/sickbeard/sickrage/sickbeard/postProcessor.py", line 972, in process
    sickbeard.USE_SUBTITLES and ep_obj.show.subtitles)
  File "/home/sickbeard/sickrage/sickbeard/postProcessor.py", line 347, in _copy
    subtitles=subtitles)
  File "/home/sickbeard/sickrage/sickbeard/postProcessor.py", line 305, in _combined_file_operation
    action(cur_file_path, new_file_path)
  File "/home/sickbeard/sickrage/sickbeard/postProcessor.py", line 340, in _int_copy
    helpers.copyFile(cur_file_path, new_file_path)
  File "/home/sickbeard/sickrage/sickbeard/helpers.py", line 351, in copyFile
    subprocess.call(['cp', srcFile, destFile])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
```

**Comment by abeloin** [comment]
Can you provide the logs where it show what the post process is trying to process?

**Comment by fernandog** [comment]
@mmazur519 reply please or we will close
