### ISSUE TITLE
Restore impossible

### ISSUE THREAD

**Issue by moust4ki** [SiCKRAGETV/sickrage-issues#784]
Hello,

SR Version:	BRANCH: (develop) / COMMIT: (9226ae9ad5ba58499f69968da524f0873427f455) 
Python Version:	2.7.8 (default, Dec 12 2014, 20:09:05) [GCC 4.6.4]

I was on Dev branch because of the T411 bug, and I wanted to switch back to master.
I backed up my settings and changed my branch.
For some reason it crashed and I had to reinstall my SickRage install on my Synology.
After that I tried to reinstall my backup, I have the message: 
>  Successfully extracted restore files to /usr/local/sickbeard-custom/var/restore
> Restart sickrage to complete the restore.

However when I try to restart my SR install nothing happens:
> Waiting for SickRage to shut down:  CHECK
> Waiting for SickRage to start again: SPINNING

Is it a know bug?

Can I restore my backup manually?

Thanks

**Comment by fernandog** [comment]
Refresh the page

**Comment by moust4ki** [comment]
I end up on an empty show list...

**Comment by fernandog** [comment]
Click the gear, select backup/restore

**Comment by moust4ki** [comment]
Thats what i'm doing.
I tried to full reinstall but I end on up on the same thing:
No restore at all: 

0 Shows (0 Active) | 0 / 0 Episodes Downloaded | Daily Search: 0:31:20 | Backlog Search: 02/27/2015

**Comment by abeloin** [comment]
@moust4ki You did your backup in develop? If so there were some changes in the backup mechanism on the develop that aren't on the master branch. You will have to manually move the file from the restore folder and delete that folder.

**Comment by moust4ki** [comment]
I tried to do 3 things that all failed:

Install a dev branch and restore my dev backup
Install a master branch and restore my dev backup
Install a master branch and restore my dev backup but changing the branch in the backup's config.ini to master

All failed and I ended up on a spinning wheel of death ! :lollipop: 

To manually restore I need to connect in SSH to my Syno and restore to the same folders of the .zip backup ? or find the files and overwrite them?

**Comment by fernandog** [comment]
Restore to the same folder as in zip. Overwrite.
and delete restore folder inside SR

**Comment by moust4ki** [comment]
Ok thanks I will try when I get back home as SSH is blocked at work..
Is there a way to have Synology filesystem inside DSM (the Diskstation webinterface)?

Thanks

**Comment by neoatomic** [comment]
Use WinSCP for restoring the files. http://winscp.net/

```Note: Synology users can use WinSCP to gain access/browse to the root where the Sickrage log is located. /volume1/@appstore/sickbeard-custom/var/Logs/sickrage.log ```

**Comment by moust4ki** [comment]
Thanks for all the help... I'm locked out: 
When i'm connecting via SFTP I can only connect with my admin account but not root so I can't see @appstore...
Does anyone has a clue on how to connect to it?

**Comment by neoatomic** [comment]
Did you enable SSH in the DSM.? 
And are you using WinSCP.? And with protocol SCP.?

**Comment by moust4ki** [comment]
Thank you VERY MUCH!
So I managed to connect and overwrite the file via WinSCP, protocope SCP (SFTP does not work)
Before that I tried many SFTP/SSH client and none worked!

However I can tell you that there is definetly a bug with the restore as I was completely unable to restore my backup, even with reinstalling numerous time SickRage...

Thanks again and have a great day :+1:

**Comment by moust4ki** [comment]
Ok i spoke a bit to fast.. Here are what I have in my logs now:

2015-02-27 15:32:08 SEARCHQUEUE-BACKLOG-73762 :: Failed to parsing KickAssTorrents Traceback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/kat.py", line 235, in _doSearch
    entries = self.cache.getRSSFeed(searchURL)['entries']
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/tvcache.py", line 142, in getRSSFeed
    return RSSFeeds(self.providerID).getFeed(self.provider.proxy._buildURL(url), post_data, self.provider.headers, items)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/rssfeeds.py", line 41, in getFeed
    resp = Cache(self.rssDB).fetch(url, force_update=True, request_headers=request_headers)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/feedcache/cache.py", line 202, in fetch
    self.storage[key] = (now, parsed_result)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/sqliteshelf.py", line 157, in __setitem__
    SQLiteDict.__setitem__(self, key, pickle.dumps(item))
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/sqliteshelf.py", line 106, in __setitem__
    self.conn.execute(ADD_ITEM, (key, sqlite3.Binary(item)))
OperationalError: attempt to write a readonly database

2015-02-27 15:32:03 SEARCHQUEUE-BACKLOG-73762 :: Failed to parsing KickAssTorrents Traceback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/kat.py", line 235, in _doSearch
    entries = self.cache.getRSSFeed(searchURL)['entries']
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/tvcache.py", line 142, in getRSSFeed
    return RSSFeeds(self.providerID).getFeed(self.provider.proxy._buildURL(url), post_data, self.provider.headers, items)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/rssfeeds.py", line 41, in getFeed
    resp = Cache(self.rssDB).fetch(url, force_update=True, request_headers=request_headers)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/feedcache/cache.py", line 202, in fetch
    self.storage[key] = (now, parsed_result)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/sqliteshelf.py", line 157, in __setitem__
    SQLiteDict.__setitem__(self, key, pickle.dumps(item))
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/sqliteshelf.py", line 106, in __setitem__
    self.conn.execute(ADD_ITEM, (key, sqlite3.Binary(item)))
OperationalError: attempt to write a readonly database

2015-02-27 15:32:02 SEARCHQUEUE-BACKLOG-73762 :: [KickAssTorrents] :: Failed to parsing KickAssTorrents Traceback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/kat.py", line 235, in _doSearch
    entries = self.cache.getRSSFeed(searchURL)['entries']
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/tvcache.py", line 142, in getRSSFeed
    return RSSFeeds(self.providerID).getFeed(self.provider.proxy._buildURL(url), post_data, self.provider.headers, items)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/rssfeeds.py", line 41, in getFeed
    resp = Cache(self.rssDB).fetch(url, force_update=True, request_headers=request_headers)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/feedcache/cache.py", line 202, in fetch
    self.storage[key] = (now, parsed_result)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/sqliteshelf.py", line 157, in __setitem__
    SQLiteDict.__setitem__(self, key, pickle.dumps(item))
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/sqliteshelf.py", line 106, in __setitem__
    self.conn.execute(ADD_ITEM, (key, sqlite3.Binary(item)))
OperationalError: attempt to write a readonly database

2015-02-27 15:31:57 SEARCHQUEUE-BACKLOG-73762 :: [KickAssTorrents] :: Failed to parsing KickAssTorrents Traceback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/kat.py", line 235, in _doSearch
    entries = self.cache.getRSSFeed(searchURL)['entries']
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/tvcache.py", line 142, in getRSSFeed
    return RSSFeeds(self.providerID).getFeed(self.provider.proxy._buildURL(url), post_data, self.provider.headers, items)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/rssfeeds.py", line 41, in getFeed
    resp = Cache(self.rssDB).fetch(url, force_update=True, request_headers=request_headers)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/feedcache/cache.py", line 202, in fetch
    self.storage[key] = (now, parsed_result)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/sqliteshelf.py", line 157, in __setitem__
    SQLiteDict.__setitem__(self, key, pickle.dumps(item))
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/sqliteshelf.py", line 106, in __setitem__
    self.conn.execute(ADD_ITEM, (key, sqlite3.Binary(item)))
OperationalError: attempt to write a readonly database

2015-02-27 15:30:19 SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: Failed to parsing KickAssTorrents Traceback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/kat.py", line 235, in _doSearch
    entries = self.cache.getRSSFeed(searchURL)['entries']
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/tvcache.py", line 142, in getRSSFeed
    return RSSFeeds(self.providerID).getFeed(self.provider.proxy._buildURL(url), post_data, self.provider.headers, items)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/rssfeeds.py", line 41, in getFeed
    resp = Cache(self.rssDB).fetch(url, force_update=True, request_headers=request_headers)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/feedcache/cache.py", line 202, in fetch
    self.storage[key] = (now, parsed_result)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/sqliteshelf.py", line 157, in __setitem__
    SQLiteDict.__setitem__(self, key, pickle.dumps(item))
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/sqliteshelf.py", line 106, in __setitem__
    self.conn.execute(ADD_ITEM, (key, sqlite3.Binary(item)))
OperationalError: attempt to write a readonly database

**Comment by abeloin** [comment]
Make sure the restored files permissions are set to the user running sickrage

**Comment by moust4ki** [comment]
@abeloin How coud I do that? 
I'm logged as root on winscp: The only thing I know how to is to change permissions via right click on the files. and change the R W X parameters

**Comment by neoatomic** [comment]
Did you shutdown Sickrage in the DSM before you overwrite the files.? Otherwise they are overwritten again if Sickrage shuts down.

Can it be that sickbeard.db is missing in your directory ?

**Comment by moust4ki** [comment]
Yes I shut it down BEFORE copying the files.
I copied from the backup; 
cache/
cache.db
config.ini
failed.db
sickbeard.db

As @abeloin stated I also think it is related to permissions as the error is 
> OperationalError: attempt to write a readonly database

Would it work if i change all copied item's permissions to 0666 ?

**Comment by neoatomic** [comment]
Check what owner is behind the file. is it Root or Sickbear.?

**Comment by moust4ki** [comment]
Sickbeard.db

Group: root
Owner: sickbeard
Permissions 0644

**Comment by moust4ki** [comment]
![snap 2015-02-27 at 15 00 17](https://cloud.githubusercontent.com/assets/10527028/6413589/6cd8f73c-be91-11e4-97af-01ff7ad58258.jpg)

**Comment by neoatomic** [comment]
Should work. Did you try to restart the Synology.?

**Comment by neoatomic** [comment]
I just read you did make the backup on Develop and are trying to restore it on Master.?
Its possible that some changes where made on Develop but not yet on Master, so that might cause an error.

**Comment by abeloin** [comment]
@moust4ki Stop sickrage, and make sure no python process run. Change the permission to 666 on sickbeard.db then restart sickrage. If you don't see the error anymore it's permission issue.

**Comment by moust4ki** [comment]
Yes, I restored my dev backup over master as I understood it would be ok.
After reboot, same prob.

I will fully uninstall sickrage, resinstall the dev, and restore backup to see if it works.

**Comment by moust4ki** [comment]
@abeloin Still have errors, will reinstall the dev and get back.

**Comment by moust4ki** [comment]
I reinstalled the develop branch, copied via WinSCP the backup files and here is the same error...
I'm getting crazy!
````
2015-02-27 17:23:09 SEARCHQUEUE-DAILY-SEARCH :: [KickAssTorrents] :: Failed to parsing KickAssTorrents Traceback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/kat.py", line 235, in _doSearch
    entries = self.cache.getRSSFeed(searchURL)['entries']
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/tvcache.py", line 142, in getRSSFeed
    return RSSFeeds(self.providerID).getFeed(self.provider.proxy._buildURL(url), post_data, self.provider.headers, items)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/rssfeeds.py", line 41, in getFeed
    resp = Cache(self.rssDB).fetch(url, force_update=True, request_headers=request_headers)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/feedcache/cache.py", line 202, in fetch
    self.storage[key] = (now, parsed_result)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/sqliteshelf.py", line 157, in __setitem__
    SQLiteDict.__setitem__(self, key, pickle.dumps(item))
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/sqliteshelf.py", line 106, in __setitem__
    self.conn.execute(ADD_ITEM, (key, sqlite3.Binary(item)))
OperationalError: attempt to write a readonly database
````

**Comment by neoatomic** [comment]
Remove all files that you have restored. except config.ini and sickbeard.db.

**Comment by moust4ki** [comment]
Cannot restart it after deleting all the files except Sickbeard.db and config.ini
![snap 2015-02-27 at 16 43 11](https://cloud.githubusercontent.com/assets/10527028/6415501/ccf11ba0-be9f-11e4-93d7-d8062316a2ae.jpg)

**Comment by neoatomic** [comment]
Hope you did not misread my comment. ?
Not remove all Sickbeard files but only those you restored so the cache folder cache.db etc...

**Comment by moust4ki** [comment]
Yeah yeah I did what you asked: remove all COPIED files except the Sickbeard.db and config.ini.
I think I managed to get something by another time reinstalling sickrage, starting it, stopping it, copying the 2 files, and then restarting it.
At the moment (started 2 min ago) no error but some warning about files (.mkv) not present in the show list, and no images at all (cache is building...)
Will update you in an hour or so.

Thanks

**Comment by moust4ki** [comment]
So, it seems that i'm back to my original situation:
After restoring the config.ini and sickbeard.db on a clean Develop version I seems to be back to before my try to go back to master.
However I have a problem with House of cards as it is widely present over my selected providers but Sickrage do not snatch it. I had to manually add it to transmission.
I will see how it goes with a different tv show.

**Comment by Smiggel** [comment]
Same issue here. I use the master branche. I did a backup of sickrage. I copied the file to my new nas and tried a restore there. Doesn't do anything at all. No show and no settings are restored. I use the latest version of Sickrage.

**Comment by fernandog** [comment]
No logs. No help. Please open new issue

**Comment by MikeyMan83** [comment]
Same issue here through the backup/restore function
I've got a working backup, when i select it, it says it placed the files in the correct folder, but upon restart, whole sickrage is empty :(
