### ISSUE TITLE
cannot navigate through webui

### ISSUE THREAD

**Issue by tchirou** [SiCKRAGETV/sickrage-issues#796]
hello
branch develop
commit 0f49f21e93ad7b10d19087e392c99a95c085fb68
python 2.7.6
Windows 8.1

When I click on most of any item of navigation like going into a show sheet or general settings, i am taken back to the show list
```
2015-03-01 10:04:51 Thread-118 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\Program Files (x86)\SABnzbd\SickRage\sickbeard\webserve.py", line 250, in async_call
    result = function(**kwargs)
  File "C:\Program Files (x86)\SABnzbd\SickRage\sickbeard\webserve.py", line 1212, in displayShow
    return t.respond()
  File "C:\Program Files (x86)\SABnzbd\SickRage\cache\cheetah\_Program_Files__x86__SABnzbd_SickRage_gui_slick_interfaces_default_displayShow_tmpl.py", line 1171, in respond
    if _v is not None: write(_filter(_v))
  File "C:\Program Files (x86)\SABnzbd\SickRage\sickbeard\webserve.py", line 91, in filter
    filtered = val.decode('utf-8').encode('ascii', 'xmlcharrefreplace')
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 15: invalid continuation byte
```

Thanks in advance for your help

**Comment by abeloin** [comment]
PLease update it should be resolved

**Comment by tchirou** [comment]
Yes it does
Many thanks



Le 1 mars 2015 à 12:08, Alexandre Beloin <notifications@github.com> a
écrit :

PLease update it should be resolved

—
Reply to this email directly or view it on GitHub
<https://github.com/SiCKRAGETV/sickrage-issues/issues/796#issuecomment-76592292>
.

**Comment by abeloin** [comment]
Can you try this PR? https://github.com/SiCKRAGETV/SickRage/pull/1442

**Comment by tchirou** [comment]
Are you asking "me" ?
Because it already works what you did this morning

**Comment by abeloin** [comment]
Yes as I reverted the previous PR which caused your issue and now I'm reintroducing a new version and want to make sure it work on your system.

**Comment by fernandog** [comment]
@tchirou reply or will assume is fixed and will close issue

**Comment by tchirou** [comment]
Well, before I had the chance to modify, the PR was merged in the new develop branch and it was closed
So yes it works and I close

**Comment by fernandog** [comment]
@tchirou you can still verify! We have lof issues waiting feedback and users don't reply. It's complicated  . We have to close them if no reply

**Comment by tchirou** [comment]
Sorry, I presumed that when multiples issues were referenced by the same PR which was merged, all issues were automatically closed
I will remember it for next times

**Comment by fernandog** [comment]
@tchirou 
sometimes PR it's merged to test faster. sometimes PR are not merged because we are uncertain about the fix. we need user to reproduce the error and confirm that issue is fixed

**Comment by tchirou** [comment]
Yes i understand but the PR was merged and already labeled tested and approved by Alexandre when I looked up, that is why i (mistakenly) presumed all related issues would be closed by the team

**Comment by fernandog** [comment]
@tchirou in his test it's fixed. but is it fixed in your SR? if yes, will keep this closed

**Comment by tchirou** [comment]
Yes it works for me.
