### ISSUE TITLE
Repeated error in logs (Failed doing webui callback)

### ISSUE THREAD

**Issue by AnalogJ** [SiCKRAGETV/sickrage-issues#802]
I'm getting the following failure repeated in my logs. 

FYI, the folder is called sickbeard but it is running sickrage.

    2015-02-28 22:15:21 Thread-27 :: Failed doing webui callback: Traceback (most recent call last):
      File "/srv/apps/sickbeard/sickbeard/webserve.py", line 230, in async_call
        result = function(**kwargs)
      File "/srv/apps/sickbeard/sickbeard/webserve.py", line 374, in showPoster
        return self.redirect(static_image_path)
      File "/srv/apps/sickbeard/sickbeard/webserve.py", line 191, in redirect
        super(BaseHandler, self).redirect(url, permanent, status)
      File "/srv/apps/sickbeard/tornado/web.py", line 630, in redirect
        self.finish()
      File "/srv/apps/sickbeard/tornado/web.py", line 892, in finish
        self.flush(include_footers=True)
      File "/srv/apps/sickbeard/tornado/web.py", line 846, in flush
        start_line, self._headers, chunk, callback=callback)
      File "/srv/apps/sickbeard/tornado/http1connection.py", line 385, in write_headers
        self._pending_write = self.stream.write(data)
      File "/srv/apps/sickbeard/tornado/iostream.py", line 348, in write
        self._handle_write()
      File "/srv/apps/sickbeard/tornado/iostream.py", line 800, in _handle_write
        _merge_prefix(self._write_buffer, num_bytes)
      File "/srv/apps/sickbeard/tornado/iostream.py", line 1383, in _merge_prefix
        if len(deque) == 1 and len(deque[0]) <= size:
    TypeError: object of type 'NoneType' has no len()

    2015-02-28 22:15:19 Thread-40 :: Failed doing webui callback: Traceback (most recent call last):
      File "/srv/apps/sickbeard/sickbeard/webserve.py", line 230, in async_call
        result = function(**kwargs)
      File "/srv/apps/sickbeard/sickbeard/webserve.py", line 374, in showPoster
        return self.redirect(static_image_path)
      File "/srv/apps/sickbeard/sickbeard/webserve.py", line 191, in redirect
        super(BaseHandler, self).redirect(url, permanent, status)
      File "/srv/apps/sickbeard/tornado/web.py", line 630, in redirect
        self.finish()
      File "/srv/apps/sickbeard/tornado/web.py", line 892, in finish
        self.flush(include_footers=True)
      File "/srv/apps/sickbeard/tornado/web.py", line 846, in flush
        start_line, self._headers, chunk, callback=callback)
      File "/srv/apps/sickbeard/tornado/http1connection.py", line 385, in write_headers
        self._pending_write = self.stream.write(data)
      File "/srv/apps/sickbeard/tornado/iostream.py", line 348, in write
        self._handle_write()
      File "/srv/apps/sickbeard/tornado/iostream.py", line 800, in _handle_write
        _merge_prefix(self._write_buffer, num_bytes)
      File "/srv/apps/sickbeard/tornado/iostream.py", line 1383, in _merge_prefix
        if len(deque) == 1 and len(deque[0]) <= size:
    TypeError: object of type 'NoneType' has no len()

**Comment by fernandog** [comment]
Duplicate
