### ISSUE TITLE
[APP SUBMITTED]: expected string or buffer

### ISSUE THREAD

**Issue by sverleysen** [SiCKRAGETV/sickrage-issues#809]
### INFO
Python Version: **2.7.8 (default, Dec 12 2014, 21:57:17) 
[GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Branch: **master**
Commit: SiCKRAGETV/SickRage@2d8aad80cdfb8983832206af445039de0decded9
Link to Log: https://gist.github.com/60727e8fb5168c803d68
### ERROR
```
FINDSUBTITLES :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/tv.py", line 1399, in downloadSubtitles
    multi=sickbeard.SUBTITLES_MULTI, cache_dir=sickbeard.CACHE_DIR)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/api.py", line 95, in download_subtitles
    subtitles_by_video = list_subtitles(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/api.py", line 54, in list_subtitles
    tasks = create_list_tasks(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/core.py", line 58, in create_list_tasks
    scan_result.extend(scan(p, max_depth, scan_filter))
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/videos.py", line 247, in scan
    return [(video, video.scan())]
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/videos.py", line 140, in scan
    results.extend([subtitles.EmbeddedSubtitle.from_enzyme(self.path, s) for s in video_infos.subtitles])
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/subtitles.py", line 75, in from_enzyme
    language = Language(subtitle.language, strict=False)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/language.py", line 856, in __init__
    for regexp in [r.match(language) for r in self.with_country_regexps]:
TypeError: expected string or buffer

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/778
