### ISSUE TITLE
[APP SUBMITTED]: u'\u0447'

### ISSUE THREAD

**Issue by jharwood0** [SiCKRAGETV/sickrage-issues#829]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) 
[GCC 4.6.3]**
Operating System: **Linux-3.18.7+-armv7l-with-debian-7.8**
Branch: **master**
Commit: SiCKRAGETV/SickRage@2d8aad80cdfb8983832206af445039de0decded9
### ERROR
```
SEARCHQUEUE-BACKLOG-76290 :: [KickAssTorrents] :: Failed to parsing KickAssTorrents Traceback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/providers/kat.py", line 261, in _doSearch
    title = self._find_season_quality(title, link, ep_number)
  File "/opt/sickrage/sickbeard/providers/kat.py", line 109, in _find_season_quality
    data = self.getURL(torrent_link)
  File "/opt/sickrage/sickbeard/providers/generic.py", line 131, in getURL
    return helpers.getURL(self.proxy._buildURL(url), post_data=post_data, params=params, headers=self.headers, timeout=timeout,
  File "/opt/sickrage/sickbeard/providers/generic.py", line 507, in _buildURL
    url = self.getProxyURL() + self.param + urllib.quote_plus(url) + self.option
  File "/usr/lib/python2.7/urllib.py", line 1275, in quote_plus
    return quote(s, safe)
  File "/usr/lib/python2.7/urllib.py", line 1268, in quote
    return ''.join(map(quoter, s))
KeyError: u'\u0447'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
fixed in develop. wait the fix go to master
