### ISSUE TITLE
[APP SUBMITTED]: Cannot find attribute 'rating'

### ISSUE THREAD

**Issue by nytemyst** [SiCKRAGETV/sickrage-issues#867]
### INFO
Python Version: **2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@f97b696c6dc2f6cd9a83bdaf9a55ebfb13e049a2
### ERROR
```
Thread-68 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 257, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 2176, in processEpisode
    is_priority=is_priority, failed=failed, type=type)
  File "C:\SickRage\sickbeard\processTV.py", line 228, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "C:\SickRage\sickbeard\processTV.py", line 459, in process_media
    result.result = processor.process()
  File "C:\SickRage\sickbeard\postProcessor.py", line 1030, in process
    ep_obj.createMetaFiles()
  File "C:\SickRage\sickbeard\tv.py", line 1904, in createMetaFiles
    self.createNFO()
  File "C:\SickRage\sickbeard\tv.py", line 1915, in createNFO
    result = cur_provider.create_episode_metadata(self) or result
  File "C:\SickRage\sickbeard\metadata\generic.py", line 275, in create_episode_metadata
    return self.write_ep_file(ep_obj)
  File "C:\SickRage\sickbeard\metadata\generic.py", line 461, in write_ep_file
    data = self._ep_data(ep_obj)
  File "C:\SickRage\sickbeard\metadata\mede8er.py", line 308, in _ep_data
    if myEp["rating"] != None:
  File "C:\SickRage\lib\tvrage_api\tvrage_api.py", line 246, in __getitem__
    raise tvrage_attributenotfound("Cannot find attribute %s" % (repr(key)))
tvrage_attributenotfound: Cannot find attribute 'rating'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by TagForce** [comment]
@nytemyst Update to the latest develop. I've run into the same issues and rewrote the data assignments throughout the mede8er file. That should no longer throw exceptions on missing data.
