### ISSUE TITLE
metadata during post processing.

### ISSUE THREAD

**Issue by crazyasyou** [SiCKRAGETV/sickrage-issues#901]
After the most recent update on the master branch there are issues during post processing (its fails) if metadata for xml output is enabled (image data eg folder.jpg still works ok.)

If show metadata > series.xml and/or episode metadate > filename.xml are enable processing fails and the below is returned in the logs.

SR Version: 	BRANCH: (master) / COMMIT: (558684cca7605dc4c2c3058d1f92e13f23881bd3)

log:
```
2015-03-09 15:05:12 Thread-13 :: Failed doing webui callback: Traceback (most recent call last):
  File "/root/Sickrage/sickbeard/webserve.py", line 257, in async_call
    result = function(**kwargs)
  File "/root/Sickrage/sickbeard/webserve.py", line 2176, in processEpisode
    is_priority=is_priority, failed=failed, type=type)
  File "/root/Sickrage/sickbeard/processTV.py", line 193, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, result)
  File "/root/Sickrage/sickbeard/processTV.py", line 459, in process_media
    result.result = processor.process()
  File "/root/Sickrage/sickbeard/postProcessor.py", line 1030, in process
    ep_obj.createMetaFiles()
  File "/root/Sickrage/sickbeard/tv.py", line 1904, in createMetaFiles
    self.createNFO()
  File "/root/Sickrage/sickbeard/tv.py", line 1915, in createNFO
    result = cur_provider.create_episode_metadata(self) or result
  File "/root/Sickrage/sickbeard/metadata/generic.py", line 275, in create_episode_metadata
    return self.write_ep_file(ep_obj)
  File "/root/Sickrage/sickbeard/metadata/generic.py", line 461, in write_ep_file
    data = self._ep_data(ep_obj)
  File "/root/Sickrage/sickbeard/metadata/mede8er.py", line 308, in _ep_data
    if myEp["rating"] != None:
  File "/root/Sickrage/lib/tvrage_api/tvrage_api.py", line 246, in __getitem__
    raise tvrage_attributenotfound("Cannot find attribute %s" % (repr(key)))
tvrage_attributenotfound: Cannot find attribute 'rating'
```

**Comment by crazyasyou** [comment]
forgot to add this is for Mede8er, I've not tested other metadata options and for now as a temp fix I've disabled xml output but left the images output enabled and PP is working ok.

**Comment by TagForce** [comment]
@crazyasyou Hmmm, apparently I forgot two assignments when redoing the mede8er.py to fix these errors...

**Comment by TagForce** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1508

**Comment by TagForce** [comment]
This was fixed in both develop and master... Please update and try again.

**Comment by crazyasyou** [comment]
Thanks for the fix, it seems to be working as normal again.
