### ISSUE TITLE
[APP SUBMITTED]: Some #directives are missing their corresponding 

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#910]
### INFO
Python Version: **2.7.3 (default, Mar 18 2014, 05:13:23) 
[GCC 4.6.3]**
Operating System: **Linux-3.12.31-armv6l-with-debian-7.8**
Locale: UTF-8
User: pi
Branch: **develop**
Commit: SiCKRAGETV/SickRage@586cc2a35cbf033b3297c62d8220656ddf246acf
Link to Log: https://gist.github.com/2b343365d1205857bf1f
### ERROR
```
Thread-31 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/pi/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/pi/SickRage/sickbeard/webserve.py", line 3347, in manageTorrents
    t = PageTemplate(rh=self, file="manage_torrents.tmpl")
  File "/home/pi/SickRage/sickbeard/webserve.py", line 110, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1259, in __init__
    self._compile(source, file, compilerSettings=compilerSettings)
  File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1553, in _compile
    keepRefToGeneratedCode=True)
  File "/home/pi/SickRage/sickbeard/webserve.py", line 153, in compile
    return super(PageTemplate, self).compile(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 743, in compile
    compiler.compile()
  File "/usr/lib/python2.7/dist-packages/Cheetah/Compiler.py", line 1664, in compile
    self._parser.parse()
  File "/usr/lib/python2.7/dist-packages/Cheetah/Parser.py", line 1497, in parse
    self.assertEmptyOpenDirectivesStack()
  File "/usr/lib/python2.7/dist-packages/Cheetah/Parser.py", line 2657, in assertEmptyOpenDirectivesStack
    raise ParseError(self, msg=errorMsg)
ParseError: 

Some #directives are missing their corresponding #end ___ tag: if
Line 22, column 92 in file /home/pi/SickRage/gui/slick/interfaces/default/manage_torrents.tmpl

Line|Cheetah Code
----|-------------------------------------------------------------
19  |$info_download_station
20  |<iframe id="extFrame" src="$webui_url" width="100%" height="500" frameBorder="0" style="border: 1px black solid;"></iframe>
21  |
22  |#include $os.path.join($sickbeard.PROG_DIR, "gui/slick/interfaces/default/inc_bottom.tmpl")
                                                                                                ^


```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
Testing purposes
