### ISSUE TITLE
[APP SUBMITTED]: 422 {u'documentation_url': u'https://developer.github.com/v3/issues/#create-an-issue', u'message': u'Validation Failed', u'errors': [{u'field': u'title', u'message': u'title is too long', u'code': u'custom', u'resource': u'Issue'}]}

### ISSUE THREAD

**Issue by maxcore** [SiCKRAGETV/sickrage-issues#917]
### INFO
Python Version: **2.7.8 (default, Dec 12 2014, 21:20:40) 
[GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.2.40-x86_64-with-glibc2.2.5**
Branch: **master**
Commit: SiCKRAGETV/SickRage@019a8b363d65db598d85173d457fa40aed6328fc
Link to Log: https://gist.github.com/218cd186d6f819dd48fb
### ERROR
```
Thread-56 :: 
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@maxcore  Can you post the log error?

**Comment by maxcore** [comment]
@fernandog close it i think TVDB have problem ....

**Comment by maxcore** [comment]
2015-03-10 21:48:53 SHOWQUEUE-REFRESH :: Unable to connect to theTVDB while creating meta files - skipping - error Unknown exception while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/278686/fr.xml: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tvdb_api/tvdb_api.py", line 574, in _loadUrl
    resp = session.get(url.strip(), cache_auto=True, params=params)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/cachecontrol/session.py", line 23, in get
    return super(CacheControlSession, self).get(*args, **kw)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/cachecontrol/adapter.py", line 27, in send
    cached_response = self.controller.cached_request(request)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/cachecontrol/controller.py", line 145, in cached_request
    self.cache.delete(cache_url)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/cachecontrol/caches/file_cache.py", line 81, in delete
    os.remove(name)
OSError: [Errno 13] Permission denied: '/usr/local/sickbeard-custom/var/cache/indexers/theTVDB/dd58c31d34838c2d6a6d38446a6e10dc6ef1c5a5b3c16d5c33408f77'

**Comment by abeloin** [comment]
@maxcore Can you provide the log from:
`2015-03-10 21:50:40 INFO     SEARCHQUEUE-BACKLOG-83462 :: Quality of Castle.2009.S07E08.HDTV.x264-LOL is SD TV`
to
`2015-03-10 21:50:42 ERROR    Thread-56 ::`
including other Thread-56

We would like to check why the submit app didn't the info.

**Comment by maxcore** [comment]
@abeloin check bellow its me or TVDB ?

**Comment by abeloin** [comment]
Check the permission for that file: `'/usr/local/sickbeard-custom/var/cache/indexers/theTVDB/dd58c31d34838c2d6a6d38446a6e10dc6ef1c5a5b3c16d5c33408f77'`

**Comment by maxcore** [comment]
2015-03-10 22:15:29 ERROR    SHOWQUEUE-ADD :: Unable to find show ID:278686 on Indexer: theTVDB

**Comment by fernandog** [comment]
@abeloin 

Error is too long:
OSError: [Errno 13] Permission denied: '/usr/local/sickbeard-custom/var/cache/indexers/theTVDB/dd58c31d34838c2d6a6d38446a6e10dc6ef1c5a5b3c16d5c33408f77'

**Comment by fernandog** [comment]
Opened a ticket im github asking the max lenght of TITLE

**Comment by abeloin** [comment]
How come it's to long?

**Comment by abeloin** [comment]
Possible fix for length for title: https://github.com/abeloin/SickRage/commit/a9d53482eaefb15e5fa8d81bf57b2851567f507a

**Comment by maxcore** [comment]
@fernandog @abeloin all work good now with the tvdb fr error

**Comment by fernandog** [comment]
@maxcore can you send the full log ? I'm investigating something

2015-03-10 21:50:42 ERROR    Thread-56 :: 
need 200 lines after this and 200 before

thanks!

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/922

**Comment by maxcore** [comment]
When am back i check!
