### ISSUE TITLE
[APP SUBMITTED]: cannot find 'TRAKT_USE_WATCHLIST'

### ISSUE THREAD

**Issue by konomimaster** [SiCKRAGETV/sickrage-issues#918]
### INFO
Python Version: **2.7.3 (default, Feb 27 2015, 20:47:22) 
[GCC 4.9.2]**
Operating System: **Linux-3.18.8-armv7l-with-glibc2.4**
Branch: **master**
Commit: SiCKRAGETV/SickRage@019a8b363d65db598d85173d457fa40aed6328fc
Link to Log: https://gist.github.com/eb2a8239e1a8f6567698
### ERROR
```
Thread-62 :: Failed doing webui callback: Traceback (most recent call last):
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/webserve.py", line 257, in async_call
    result = function(**kwargs)
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/sickbeard/webserve.py", line 4560, in index
    return t.respond()
  File "/storage/.kodi/userdata/addon_data/service.downloadmanager.SickPotatoHead/sbcache/cheetah/cheetah__storage__kodi_addons_service_downloadmanager_SickPotatoHead_resources_SickBeard_gui_slick_interfaces_default_config_notifications_tmpl_1426056824_56_42863.py", line 2352, in respond
    if VFSL([locals()]+SL+[globals(), builtin],"sickbeard.TRAKT_USE_WATCHLIST",True) : # generated from line 1450, col 132
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/lib/Cheetah/NameMapper.py", line 245, in valueFromSearchList
    executeCallables=executeCallables)
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/lib/Cheetah/NameMapper.py", line 226, in _valueForName
    _raiseNotFoundException(key, obj)
  File "/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/lib/Cheetah/NameMapper.py", line 167, in _raiseNotFoundException
    raise NotFound(excString)
NotFound: cannot find 'TRAKT_USE_WATCHLIST'

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by fernandog** [comment]
@gborri

**Comment by gborri** [comment]
@fernandog i've seen it, but i can't fine 'TRAKT_USE_WATCHLIST' in the whole code either master or develop. @konomimaster could you please give some more info? I see in the log that you are using a kodi addon....

**Comment by konomimaster** [comment]
@gborri  i'm running a Kodi-distro called OPENELEC (http://openelec.tv/) on a Raspberry PI 2. Earlier on i've used the same OS on a pc running the same addon but without the errors i'm experiencing now. I'm suspecting it might be a problem with the OS and not Sickrage.

**Comment by gborri** [comment]
@konomimaster recently we have changed the parameter TRAKT_USE_WATCHLIST with TRAKT_SYNC_WATCHLIST, but in SickRage code i can't find any instance of TRAKT_USE_WATCHLIST as said before.

**Comment by TagForce** [comment]
@konomimaster /storage/.kodi/userdata/addon_data/service.downloadmanager.SickPotatoHead/sbcache/cheetah/
Delete everything in that folder... It looks like it's using an old cache entry with the old parameter name.

**Comment by fernandog** [comment]
@konomimaster did you updated using git pull? this cache problems can happen with you do that and we had changes in templates

**Comment by abeloin** [comment]
As @fernandog said these kind of error happen when you manually update sickrage from the command line(or via sickrage but fail to restart). This leave sickrage in inconsistent state: old code from the py files and new code from the tmpl files(the webui). Restarting sickrage usually fix the issue.
