### ISSUE TITLE
viewlogs.tmpl isn't filtering html tags from the log when sending to the browser

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#923]
SR Version:	BRANCH: (develop) / COMMIT: (7089fa9ac0959195e9ba4e642b2b7ae410bbe512) 
SR User:	pi
SR Locale:	('pt_BR', 'UTF-8')
SR Config file:	/home/pi/SickRage/config.ini
SR Database file:	/home/pi/SickRage/sickbeard.db
SR Cache Dir:	/home/pi/SickRage/cache
SR Arguments:	['-q', '--daemon', '--nolaunch', '--pidfile=/var/run/sickrage/sickrage.pid', '--datadir=/home/pi/SickRage']
SR Web Root:	
Python Version:	2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]

**Error message**
```
2015-03-11 09:54:18 ERROR    Thread-17 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/pi/SickRage/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/home/pi/SickRage/sickbeard/webserve.py", line 3347, in manageTorrents
    t = PageTemplate(rh=self, file="manage_torrents.tmpl")
  File "/home/pi/SickRage/sickbeard/webserve.py", line 110, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1259, in __init__
    self._compile(source, file, compilerSettings=compilerSettings)
  File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1553, in _compile
    keepRefToGeneratedCode=True)
  File "/home/pi/SickRage/sickbeard/webserve.py", line 153, in compile
    return super(PageTemplate, self).compile(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 743, in compile
    compiler.compile()
  File "/usr/lib/python2.7/dist-packages/Cheetah/Compiler.py", line 1664, in compile
    self._parser.parse()
  File "/usr/lib/python2.7/dist-packages/Cheetah/Parser.py", line 1497, in parse
    self.assertEmptyOpenDirectivesStack()
  File "/usr/lib/python2.7/dist-packages/Cheetah/Parser.py", line 2657, in assertEmptyOpenDirectivesStack
    raise ParseError(self, msg=errorMsg)
ParseError: 

Some #directives are missing their corresponding #end ___ tag: if
Line 22, column 92 in file /home/pi/SickRage/gui/slick/interfaces/default/manage_torrents.tmpl

Line|Cheetah Code
----|-------------------------------------------------------------
19  |$info_download_station
20  |<iframe id="extFrame" src="$webui_url" width="100%" height="500" frameBorder="0" style="border: 1px black solid;"></iframe>
21  |
22  |#include $os.path.join($sickbeard.PROG_DIR, "gui/slick/interfaces/default/inc_bottom.tmpl")
```

**appears in viewlog as:**

![4](https://cloud.githubusercontent.com/assets/2620870/6596918/85a2f836-c7d7-11e4-9d09-154427d7cac8.png)

**Comment by fernandog** [comment]
viewlogs.tmpl

```
<div class="align-left"><pre>
$logLines
</pre>
```

maybe we need to add something to the div

**Comment by abeloin** [comment]
Some info are missing, see https://github.com/SiCKRAGETV/sickrage-issues on how to fill a proper ticket :stuck_out_tongue_winking_eye: 

Joke aside: you get this in the latest develop branch?

**Comment by TagForce** [comment]
@abeloin LOL... You just made my day :)

**Comment by fernandog** [comment]
I was expecting this....=)

first post updated - notice the new user and locale!

**Comment by abeloin** [comment]
@fernandog Can you post the log from when that error happened?

**Comment by fernandog** [comment]
I dont have it.
to reproduce just edit managetorrents.tmpl and remod any directive like #end if

**Comment by abeloin** [comment]
This will do the trick

viewlogs.tmpl:
```
<div class="align-left"><pre>
#filter WebSafe
$logLines
#filter Filter
</pre>
</div>
```
