### ISSUE TITLE
[APP SUBMITTED]: No module named pwd

### ISSUE THREAD

**Issue by copekyle** [SiCKRAGETV/sickrage-issues#953]
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Branch: **develop**
Commit: SiCKRAGETV/SickRage@d15e9e0bb698b02be5202a5b4255b69e02566e59
Link to Log: https://gist.github.com/1fccb5cd830d098fc8e7
### ERROR
```
Thread-188 :: Failed doing webui callback: Traceback (most recent call last):
  File "C:\Users\Ktrain_Media\Sickbeard\SickRage\sickbeard\webserve.py", line 257, in async_call
  File "C:\Users\Ktrain_Media\Sickbeard\SickRage\sickbeard\webserve.py", line 3579, in index
    display_filesize=None, fuzzy_dating=None, trim_zero=None, date_preset=None, date_preset_na=None, time_preset=None,
  File "C:\Users\Ktrain_Media\Sickbeard\SickRage\sickbeard\webserve.py", line 109, in __init__
    kwargs['filter'] = html_entities
  File "C:\Python27\lib\site-packages\Cheetah\Template.py", line 1259, in __init__
    self._compile(source, file, compilerSettings=compilerSettings)
  File "C:\Python27\lib\site-packages\Cheetah\Template.py", line 1553, in _compile
    keepRefToGeneratedCode=True)
  File "C:\Users\Ktrain_Media\Sickbeard\SickRage\sickbeard\webserve.py", line 152, in compile
    kwargs['cacheDirForModuleFiles'] = os.path.join(sickbeard.CACHE_DIR, 'cheetah')
  File "C:\Python27\lib\site-packages\Cheetah\Template.py", line 788, in compile
    exec(co, mod.__dict__)
  File "C:\Users\Ktrain_Media\Sickbeard\SickRage\cache\cheetah\_Users_Ktrain_Media_Sickbeard_SickRage_gui_slick_interfaces_default_config_tmpl.py", line 30, in <module>
    import pwd
ImportError: No module named pwd

```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by copekyle** [comment]
I'm sorry guys... I had two errors that were exactly the same and it submitted them in separate tickets... please delete this one
