### ISSUE TITLE
Error on Sickrage startup

### ISSUE THREAD

**Issue by TheBigC53** [SiCKRAGETV/sickrage-issues#957]
I have no idea where to start with this:

```
C:\Users\MediaBot>cd \sickrage

C:\SickRage>python sickbeard.py
Traceback (most recent call last):
  File "sickbeard.py", line 69, in <module>
    import sickbeard
  File "C:\SickRage\sickbeard\__init__.py", line 37, in <module>
    from sickbeard import providers, metadata, config, webserveInit
  File "C:\SickRage\sickbeard\webserveInit.py", line 6, in <module>
    from sickbeard.webserve import LoginHandler, LogoutHandler, KeyHandler, Cale
ndarHandler
  File "C:\SickRage\sickbeard\webserve.py", line 32, in <module>
    from sickbeard import history, notifiers, processTV
  File "C:\SickRage\sickbeard\processTV.py", line 35, in <module>
    from lib.unrar2 import RarFile, RarInfo
  File "C:\SickRage\lib\unrar2\__init__.py", line 45, in <module>
    from windows import RarFileImplementation
  File "C:\SickRage\lib\unrar2\windows.py", line 77, in <module>
    unrar = ctypes.WinDLL(dll_name)
  File "c:\python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

C:\SickRage>
```

**Comment by fernandog** [comment]
https://sickrage.tv/forums/forum/help-support/general-support/14420-sickrage-installation-guides-windows-mac-osx-linux-raspberry-pi
