### ISSUE TITLE
Deluge: commit 646a3092813aa2bd22bbe908951a81a5b9ec7ebe broke sending torrent

### ISSUE THREAD

**Issue by abeloin** [SiCKRAGETV/sickrage-issues#964]
```
SR Version: 	BRANCH: (production-stage) / COMMIT: (2646fd6850c0d19a902fba4cade16e513d7cedf9)
SR Locale:	('en_CA', 'UTF-8')
SR Config file:	/opt/SickRage/config.ini
SR Database file:	/opt/SickRage/sickbeard.db
SR Cache Dir:	/opt/SickRage/cache
SR Arguments:	['-q', '--daemon', '--nolaunch', '--datadir=/opt/SickRage']
SR Web Root:	
Python Version:	2.7.5 (default, Nov 3 2014, 14:26:24) [GCC 4.8.3 20140911 (Red Hat 4.8.3-7)]
Deluge: 1.3.11
```

While testing for release to master tomorrow, every time Sickrage tries to send a a torrent to deluge it fails.

```
2015-03-14 08:09:17 DEBUG    SEARCHQUEUE-BACKLOG-284169 :: Deluge: Exception raised when sending torrent:
AAValueError: No JSON object could be decoded
AA    raise ValueError("No JSON object could be decoded")
AA  File "/opt/SickRage/lib/simplejson/decoder.py", line 353, in raw_decode
AA    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
AA  File "/opt/SickRage/lib/simplejson/decoder.py", line 335, in decode
AA    return _default_decoder.decode(s)
AA  File "/opt/SickRage/lib/simplejson/__init__.py", line 307, in loads
AA    return json.loads(self.text, **kwargs)
AA  File "/opt/SickRage/lib/requests/models.py", line 799, in json
AA    result.hash = self.response.json()['result']
AA  File "/opt/SickRage/sickbeard/clients/deluge.py", line 117, in _add_torrent_file
AA    r_code = self._add_torrent_file(result)
AA  File "/opt/SickRage/sickbeard/clients/generic.py", line 176, in sendTORRENT
AATraceback (most recent call last):
2015-03-14 08:09:17 ERROR    SEARCHQUEUE-BACKLOG-284169 :: Deluge: Failed Sending Torrent
2015-03-14 08:09:17 DEBUG    SEARCHQUEUE-BACKLOG-284169 :: Deluge: Gateway Timeout
```
 System logs:
```
Mar 14 08:08:17 machine.test.local deluge[10403]: Unhandled error in Deferred:
Mar 14 08:08:17 machine.test.local deluge[10403]: Unhandled Error
Mar 14 08:08:17 machine.test.local deluge[10403]: Traceback (most recent call last):
Mar 14 08:08:17 machine.test.local deluge[10403]: Failure: twisted.internet.error.ConnectionRefusedError: Connection was refused by othe
Mar 14 08:08:17 machine.test.local deluged[11546]: [ERROR   ] 08:08:17 rpcserver:304 Exception calling RPC request: add_torrent_file() t
Mar 14 08:08:17 machine.test.local deluged[11546]: Traceback (most recent call last):
Mar 14 08:08:17 machine.test.local deluged[11546]: File "/usr/lib/python2.7/site-packages/deluge/core/rpcserver.py", line 299, in dispat
Mar 14 08:08:17 machine.test.local deluged[11546]: ret = self.factory.methods[method](*args, **kwargs)
Mar 14 08:08:17 machine.test.local deluged[11546]: TypeError: add_torrent_file() takes exactly 4 arguments (3 given)
Mar 14 08:08:17 machine.test.local deluge[10403]: [ERROR   ] 08:08:17 client:391 RPCError Message Received!
Mar 14 08:08:17 machine.test.local deluge[10403]: --------------------------------------------------------------------------------
Mar 14 08:08:17 machine.test.local deluge[10403]: RPCRequest: core.add_torrent_file(Testing_torrent_file_videos.mp4.torrent, ZDg6YW5ub3Va
Mar 14 08:08:17 machine.test.local deluge[10403]: --------------------------------------------------------------------------------
Mar 14 08:08:17 machine.test.local deluge[10403]: File "/usr/lib/python2.7/site-packages/deluge/core/rpcserver.py", line 299, in dispatc
Mar 14 08:08:17 machine.test.local deluge[10403]: ret = self.factory.methods[method](*args, **kwargs)
Mar 14 08:08:17 machine.test.local deluge[10403]: TypeError: add_torrent_file() takes exactly 4 arguments (3 given)
Mar 14 08:08:17 machine.test.local deluge[10403]: --------------------------------------------------------------------------------
```

Reverting commit : https://github.com/SiCKRAGETV/SickRage/commit/646a3092813aa2bd22bbe908951a81a5b9ec7ebe restore the functionality.

**Comment by abeloin** [comment]
Reference:
http://deluge.readthedocs.org/en/develop/core/rpc.html#deluge.__rpcapi.RpcApi.core.add_torrent_file

**Comment by fernandog** [comment]
Didnt need to revert that?

**Comment by abeloin** [comment]
I should have said blame commit is ... instead of reverting commit as I meant to show the commit introducing the issue. PR 1557 restore the dict even if it is empty as it is required by deluge's api
